### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by OffifialMITX** [SimpleMobileTools/Simple-Gallery#100]
Already done via <a href="https://github.com/LonamiWebs/Stringlate">Stringlate</a>.
<a href="https://gist.github.com/adbcee0ad2bb14f8e5f89196db3fd360">German translation</a>

**Comment by tibbi** [comment]
they are sorted alphabetically, while my strings were ordered by usage. Can you please compare them to https://github.com/SimpleMobileTools/Simple-Gallery/blob/master/app/src/main/res/values-de/strings.xml and check what is different? In the link I gave there is a pencil at the top right corner, you can press it and suggest file edits really easily. Thanks!

**Comment by XyLoNaMiyX** [comment]
@tibbi my application currently doesn't support keeping the original structure of the file, but I will keep an eye on it. Hopefully it's not so hard to implement!

**Comment by tibbi** [comment]
the app seems to be translated in german just fine, so Ill close it. Please use the pencil at top right corner of https://github.com/SimpleMobileTools/Simple-Gallery/blob/master/app/src/main/res/values-de/strings.xml for suggesting specific changes to individual strings, not sending all strings at once.

**Comment by XyLoNaMiyX** [comment]
>  for suggesting specific changes to individual strings, not sending all strings at once.

Doesn't that actually fork the whole repository and opens an online editor? And you submit the whole file, only with some lines changed? Just curious :)

**Comment by tibbi** [comment]
well it submits only the changed things, at least thats whats shown. I can immediately see what has been changed, I dont have to reorder and compare strings one by one.
