### ISSUE TITLE
latest version crashes on startup...

### ISSUE THREAD

**Issue by fake-fur** [SimpleMobileTools/Simple-Gallery#1003]
hi and thanks for great work

the latest update suddenly crashes on startup on my lineageos + microg sgs7

haven't had any problems before - any idea what could be causing this change?

thanks

**Comment by fake-fur** [comment]
no even after a complete uninstall with data & cache cleared a new install does the exact same thing

**Comment by xyrolaith** [comment]
Same issue (the latest Calendar app also crashes) here on an Honor 9 running the official Android 8 with the latest September 2018 security patches.

**Comment by OJE9** [comment]
Were you using Yalp Store to update/install it?

I just tried installing fresh from GitHub and it works:
4.6.5 --> 5.0 --> 5.1

- Version 5.0 gave me a nag about choosing a root OTG folder. Wasn't able to see root folders though. No idea what that was.
- Yalp store says "The APK is split, choose a root or priviliged option to install". I have no idea what this is.
-  Im going to try the other apps aswell, I'll update if they work.

Im using Lineage 14 with Micro G.

**Comment by tibbi** [comment]
I started using App Bundles https://developer.android.com/guide/app-bundle/ in version 5.0, probably that is what they mean. Anyway you could also try installing the latest gallery-release.apk at https://github.com/SimpleMobileTools/Simple-Gallery/releases , to see if it works. Thanks

**Comment by OJE9** [comment]
Found the option in Yalp store to install apps as root:
Settings --> Installation method --> Using root

I was also using the legacy version of Yalp Store. Switched to the contemporary version.

Also downloading the apps from GitHub and sideloding them worked for me.

Im using Lineage 14 (Nougat) with Micro G.

**Comment by tibbi** [comment]
ok, thanks. Guess the original issue is related to bundling, google is doing something wrong on its side. Not sure if there is anything I can improve on my side. we will see how it ends up.

**Comment by tibbi** [comment]
does any of you have Simple Thank You installed? If you do, can you try uninstalling it, if it fixes your issues? You wont have to pay again for redownloading it.

**Comment by fake-fur** [comment]
sideloading works fine but every yalp update breaks it again, so sideloading is fine for me
thanks again :+1:

**Comment by tibbi** [comment]
ok, well so that is the expected behaviour now, caused by app bundles. My primary audience is Google Play, where it seems to works fine.

**Comment by dylmye** [comment]
I'm getting this issue and I'm getting the app from Google Play. Anything I can provide to help diagnose? Logcat etc
