### ISSUE TITLE
Favorites deleted (after update?) 

### ISSUE THREAD

**Issue by thosoo** [SimpleMobileTools/Simple-Gallery#1004]
Today I have opened simple gallery to work on filtering pictures through the favorites feature, but suddenly all of them were gone. I dont know if an update was the reason, but on startup  whenI I have first seen that the favorotes were gone, I have received the changelog of 5.0.1.
I am not sure if there is a good way to reproduce. 

Huawei P10 
Android 8.0 
SimpleGallery Playstore version

**Comment by tibbi** [comment]
Ye there was a glitch at updating from older version to new. So if you mark some favorite items now and restart the app, do they stay?

**Comment by tibbi** [comment]
the glitch has been fixed already
