### ISSUE TITLE
settings import/export from/to file?

### ISSUE THREAD

**Issue by patrickdrd** [SimpleMobileTools/Simple-Gallery#1006]
I like this app, but it has too many settings to remember from scratch when setting up again,
so, could we please have a setting import/export functionality please?

**Comment by endeavorz** [comment]
Thank you Tibor !  

fix #1006, allow exporting/importing settings to files - I can't wait to try this later !

**Comment by F3000** [comment]
How this feature is working ? @tibbi

**Comment by tibbi** [comment]
well there are 2 new items at the bottom of the app settings, Export and Import. First you can export some data in a text file, then import it. Not sure what else you mean :)

**Comment by F3000** [comment]
can you add this seeeting also for file manager and camera ? Would be grade.

**Comment by tibbi** [comment]
maybe someday, for now those apps have only a few settings.

**Comment by patrickdrd** [comment]
> well there are 2 new items at the bottom of the app settings, Export and Import. First you can export some data in a text file, then import it. Not sure what else you mean :)

_Originally posted by @tibbi in https://github.com/SimpleMobileTools/Simple-Gallery/issues/1006#issuecomment-458867444_

in which version? 
I can't find these "2 new items"

**Comment by tibbi** [comment]
it was added in 6.4.0
