### ISSUE TITLE
Please disable Split Apk

### ISSUE THREAD

**Issue by Rikk** [SimpleMobileTools/Simple-Gallery#1019]
Using split apk makes it very hard for the user to install using alternative store apps, and to share apk installed from Google Play with others.

**Comment by tibbi** [comment]
My primary focus on Google Play, as that is where 99% installs come from. And since app bundling decreases app size by up to 60%, I definitely want to have it.

**Comment by Rikk** [comment]
I think if you use the traditional method of building one apk per architecture, the final size will be almost the same. In some zip recompression tests I did, traditional method would increase only 1MB the size, possibly only because I didn't exclude resources files (split apk seems to filter resources by dpi).
Another reduction in the apk size could be increasing zip compression ratio, if the SDK program permits this control (I don't know). I recompressed the contents of the full apk in zip format and got 11.32MB vs 12.75MB of the official full apk. Btw, something you could remove is mips, which has no known device, and maybe x86_64, dunno if someone uses it in Android world.

Anyway, please keep the full apk on Releases (and the Changelog, which is a very useful thing).

You are doing a great job on current versions, old versions were much less pleasant.

**Comment by tibbi** [comment]
I will have full releases on github and f-droid. It is Google Play taking care of creating the split apks. not me.

**Comment by SebiderSushi** [comment]
@Rikk If you haven't yet switched to get Simple Gallery from F-Droid  and are running Android 5.0 or newer you might give this split apk installer a shot: https://f-droid.org/en/packages/com.aefyr.sai.fdroid/
