### ISSUE TITLE
Sort by creation date not working correctly

### ISSUE THREAD

**Issue by yan-** [SimpleMobileTools/Simple-Gallery#1022]
Using the photo's creation date as sort order, some images appear where they shouldn't. I have a folder with about 100 pictures, almost all of them taken with DSLR or alike, with correct meta data etc. When I tap on the information icon, the creation dates of the images is shown correctly, but they appear further down than they should (using descendant ordering).

I can't figure out why that happens, because these images are not different from others in the same folder taken the same day with the same camera. I already tried the option to "correct creation date", but that doesn't change anything.

**Comment by tibbi** [comment]
try long pressing image thumbnails and selecting "Fix Date Taken values"

**Comment by yan-** [comment]
That's what I already tried, tibbi. But it doesn't solve the problem.

**Comment by yan-** [comment]
Another problem with some of these images: When I share them through WhatsApp or alike, it seems they are not recognized as images but rather sent as a file (no preview of the image).

**Comment by PFDaily** [comment]
I have this same issue. It would be much easier to diagnose if in "properties" both "Last Modified" and "Date Created" were populated.

**Comment by yan-** [comment]
In my case "Last Modified" and "Date Created" are displayed correctly, but still the sort order is wrong.

**Comment by tibbi** [comment]
let me know if any of you are willing to help debug the issue. Just send me a mail at hello@simplemobiletools.com, I will send you a test version with a message appearing, and you just send me a screenshot of it.

**Comment by Waalkamaan** [comment]
I'm still using v5.1.3 but i had a very similar issue that maybe is related to the first comment.

My settings for "sort by" are set to "date taken" and "ascending".
Some images taken during this year were displayed as if they were taken in december. All of these images had one thing in common... i edited them the last few days with GIMP. Next i checked and manipulated the dates of the images with XNVIEW.

Dates available in XNVIEW:
1. File - date created
2. File - date changed
3. EXIF - date taken
4. EXIF - date digitized
5. EXIF - date changed

The dates for "EXIF - date taken" and "EXIF - date digitized" were always identical and correct.
The dates for "File - date created", "File - date changed" and "EXIF - date changed" were different to each other and different to "EXIF - date taken" but interestingly all the values for "EXIF - date changed" were set to december.

So... just to be sure i changed these three values one by one to the value of "EXIF - date taken" and checked if the sorting by SIMPLE-GALLERY changed too:

1. File - date created --> no effect
2. File - date changed --> no effect
5. EXIF - date changed --> this did it. sorting order correct

Conclusion:
SIMPLE-GALLERY should use "EXIF - date taken" for "sort by date taken".
SIMPLE-GALLERY should not use "EXIF - date changed" for "sort by date taken".

**Comment by tibbi** [comment]
recheck with version 6.1.0 released soon please

**Comment by tibbi** [comment]
someone retry the "Fix Date Taken values" with 6.1.3 please. If you get an error that it failed, just retry once again. Did you still get an error? Is the sorting still bad?

**Comment by yan-** [comment]
Still no luck, sorry. I get the success message but sort order stays the same (with errors).

**Comment by tibbi** [comment]
retry with 6.6.0. Many things have changed since the original report, so if some issues still persist please open a new issue.
