### ISSUE TITLE
"Not sure what else, nobody reads this anyway"

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Gallery#1029]
I read the changelog! Pretty much every time I update.

**Comment by smichel17** [comment]
Closing since there's nothing actionable here

**Comment by touzainanboku** [comment]
I read it too. I actually visit GitHub frequently to see all the upcoming changes in some of the open source apps I'm using, including this one.

**Comment by TacoTheDank** [comment]
same

**Comment by smichel17** [comment]
So that we don't spam people with notifications forever: future people who want to add your +1, you can leave a :+1: reaction to the top comment.

**Comment by ShadyGaDa** [comment]
I am reading this now +√ +∆
