### ISSUE TITLE
Feature request: Unselect/Deselect multiple images

### ISSUE THREAD

**Issue by vertigo220** [SimpleMobileTools/Simple-Gallery#1033]
Currently, you can select multiple images at once, but then the only way to unselect them is to either do so one by one or by unselecting all the currently selected images. It would be nice to be able to simply long-press and drag over selected ones to unselect them just as you would to select them.

Tags: un-select, de-select

**Comment by tibbi** [comment]
I dont like that behaviour, it is not expected.
