### ISSUE TITLE
Slow + Request

### ISSUE THREAD

**Issue by vertigo220** [SimpleMobileTools/Simple-Gallery#1034]
The app can sometimes be a bit slow to load the main screen content, sometimes taking a few seconds (granted, that's not terrible by any means, but it definitely seems slower than QuickPic). Also, when switching the sort method/order it displays the message "No media has been found with the selected filters" for several seconds, giving the appearance it's not working. The first couple times I tried refreshing and messing with the app to see what the problem was, but then I discovered it was just taking a long time, though even then I still think for a second that it's not working when the message appears.

And it's _very_ slow to load content when switching to "Show all folders content." Perhaps there could be a separate mode for showing it like it currently does and one for showing all content grouped by month, which should load much faster. I'd also like to have this action accessible directly on the toolbar, so maybe it could be three separate buttons or a single button with a menu that lets you pick the mode (Folder view, All folders content, or Timeline/Moments). The single button with a menu would also allow for the (hopefully) future addition of toggling between a flat vs explorer type view mode.

**Comment by tibbi** [comment]
performance can always be better, but it also heavily depends on your device and the amount of images. In some cases it will just never be butter smooth.

**Comment by vertigo220** [comment]
I understand that, but I know my device, with the number of images, can perform better, based on other apps. I'd still rather use this one, even if it is a bit slower, but it seems like it's slower than it should be, displaying the message like that while it's loading is confusing, and adding the option for grouping the "Show all folders content" view by month should help significantly with that part of it.
