### ISSUE TITLE
Hide Photos,album, folder(project Enhancement)

### ISSUE THREAD

**Issue by SubhamTyagi** [SimpleMobileTools/Simple-Gallery#1045]
You know the importance of hiding the photos, album. this cool app is providing a feature for hide but this is not effective if we have another gallery app or a File Manager (as mostly phone have) these photos are accessible to these apps.

For this feature app need some works as follows
1. You can encrypt the photos. or 
2. You can move these photos to only app accessible storages

i think first method is useful as if users delete app then the hide photos is still on external storage but in encrypted form, in second method these will be deleted as soon as  gallery app uninstalled and app only storage  photo will be accessible on rooted phone.

**Comment by touzainanboku** [comment]
If this were to be implemented I'd like to request the current implementation to remain as well. It's good enough for my needs and I don't like the hassle of being tied to an app-specific implementation.

**Comment by tibbi** [comment]
encryption might be added only someday in the further future. I was already checking it, but it seemed to be a lot more difficult than I wanted it to be.

**Comment by SubhamTyagi** [comment]
@tibbi could i do some work for this?

**Comment by tibbi** [comment]
well you can try, we will see how will it look like

**Comment by SubhamTyagi** [comment]
@tibbi 
what i use for password for encryption? Hash of password or Plain password.

**Comment by SubhamTyagi** [comment]
As most of the algorithm for ciphering required minimum API 23  for android keystore. so system keystore in unavailable for this app as this also supporting minimum Api 21.

 thus convenient method is to store passwords digest to in app database.

**Comment by tibbi** [comment]
I dont want to store keys in the app, that isnt real encryption then. We can hide the Encrypt button on Android 5, that isnt a big issue.

**Comment by SubhamTyagi** [comment]
i agree with your concern about in app storage of password or any hashes but also other methods such as not store any encryption related data.

we simply store a encrypted text which is encrypted with user password. this encrypted text is only used for password authentication.

**Comment by tibbi** [comment]
by encryption I mean that if I encrypt a folder in Simple Gallery, you will need the password for opening it in any file manager too.

**Comment by SubhamTyagi** [comment]
sorry for too late comment 
This feature required lot of time but i had no time but i have created a [simple library](https://github.com/SubhamTyagi/encryption-example) for encryption which will be helpful for this app.

**Comment by tibbi** [comment]
thanks, Ill take a look at it someday, when Ill revisit this issue

**Comment by SevastianGit** [comment]
> sorry for too late comment This feature required lot of time but i had no time but i have created a [simple library](https://github.com/SubhamTyagi/encryption-lib/) for encryption which will be helpful for this app.
> 
> EDIT 1: changed the url
Why did you delete it?
