### ISSUE TITLE
Toolbar selects/deselects all without visible action

### ISSUE THREAD

**Issue by jahirfiquitiva** [SimpleMobileTools/Simple-Gallery#1061]
Hi

The toolbar allows selecting or deselecting all items, by pressing any empty space after selection has started, but it does **not** show any visible action for that, which is **not** intuitive.

Can you add an icon for that functionality instead of making the whole toolbar work like that?
Or allow disabling it in settings?

Thanks

**Comment by tibbi** [comment]
it should obviously show that the items are selected. 
1. If you select menu -> Select all, does it work well? 
2. What app version do you have?
3. Do you use grid or list view?
4. If grid, do you use horizontal or vertical scrolling?

**Comment by jahirfiquitiva** [comment]
Yeah, it should show that the items are selected, but I mean that pressing the toolbar selects/deselects all.

1. Yes
2. The new Pro app v 6.0.0
3. Grid
4. Vertical

**Comment by tibbi** [comment]
Hm ok, I will take a look at it, it is definitely a bug. Im calling the same function from pressing the toolbar and "Select all". So not even the selected item counter at the top left corner gets updated? Just if you select for example Properties, you see that all items are selected? Does it always happen, so you can easily reproduce it? Thanks

**Comment by jahirfiquitiva** [comment]
Here's a gif reproducing the issue, just in case it wasn't clear yet
See how I press the toolbar in an "empty" space where no icons are shown and hence no action should be executed

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10360816/48021630-1057a480-e107-11e8-90e2-c2dd3b0b48cf.gif)

**Comment by tibbi** [comment]
aha, I thought that you cannot see the checkmarks at selecting them. Ye I wanted to make the clicking only on the text at the left corner, but somehow it always stretches to the whole line. Ill try improving it. Thanks

**Comment by tibbi** [comment]
I made that selector smaller (just the width of the text) and also added click animation, that should be good enough.
