### ISSUE TITLE
settings not retained for pro version

### ISSUE THREAD

**Issue by tessus** [SimpleMobileTools/Simple-Gallery#1067]
I've installed the pro version and noticed that all settings are gone.

Is there any way to copy the settings or export/import them? Having to set it up again, can be quite tedious.

P.S.: I did not send an email, because this might be useful to others as well.

**Comment by tibbi** [comment]
No, sadly there is no way of migrating settings yet. It might be added someday in the further future.

**Comment by endeavorz** [comment]
Again I also vote for an import/export of settings - it would be so helpful
