### ISSUE TITLE
Icon in recents does not match selected icon color

### ISSUE THREAD

**Issue by jahirfiquitiva** [SimpleMobileTools/Simple-Gallery#1068]
Pretty much what the title says. Screenshots for reference, tho...

![screenshot_20181106-235456](https://user-images.githubusercontent.com/10360816/48111491-b7c7fa80-e21f-11e8-97ce-8eb8012cd44d.png)

![screenshot_20181106-235500](https://user-images.githubusercontent.com/10360816/48111521-e80f9900-e21f-11e8-9e56-bbcd38171b89.png)

**Comment by tibbi** [comment]
I moved it to https://github.com/SimpleMobileTools/General-Discussion/issues/94 as it affects all apps. Thanks
