### ISSUE TITLE
No support for very light themes

### ISSUE THREAD

**Issue by jahirfiquitiva** [SimpleMobileTools/Simple-Gallery#1072]
Hi

I would like to use this light theme, but the toolbar icons and status bar icons remain white. Only the toolbar title updates its color to something visible and usable.

Can you add theming for the toolbar icons and enabling the light status bar flag in cases like this?

Thanks in advance!

![screenshot_20181108-170421](https://user-images.githubusercontent.com/10360816/48230402-d8f02e80-e378-11e8-87b8-ccef35bd17b3.png)

**Comment by tibbi** [comment]
it will be improved in 6.9.2, icons will be properly colored. The three dots at the top right corner wont be colored yet, I havent figured out how to do that.

**Comment by tibbi** [comment]
everything should be working fine already
