### ISSUE TITLE
Can't install pro version from Yalp Store

### ISSUE THREAD

**Issue by zekooooo** [SimpleMobileTools/Simple-Gallery#1078]
Sorry if this is the wrong place to post, F-Droid gave me this link and it only updated today with the 7 day notice so sorry about asking so late too.

I downloaded and installed Gallery, File Manager & Calendar Pro via Yalp Store (I don't have Google Play) but when I try to run them they instantly crash ("Gallery has stopped. Open app again"). The old (F-Droid) apps still work luckily.

**Comment by tibbi** [comment]
there shouldnt be a Pro version on f-droid yet, it probably just somehow got updated by accident. Try fully  uninstalling your current version and just install the latest one.

**Comment by zekooooo** [comment]
No, I got the pro version from Yalp Store (a sort of Play Store mirror). I also have the non-pro version from F-Droid installed side by side and that one is still working fine. I tried uninstalling and reinstalling in various combinations multiple times and this always happens. Maybe my blocking of Google bloat is breaking it?

**Comment by tibbi** [comment]
well the Pro version is paid on Google Play, not sure if Yalp supports that well. I dont think there is any issue on my side.

**Comment by tibbi** [comment]
yalp does not support app bundling, that might be the issue. Im leaving Simple Thank You active also for the Shared Theme, I will also make it a bit cheaper.
