### ISSUE TITLE
Version 6.0.0 is very slow at startup compared to 5.1.3

### ISSUE THREAD

**Issue by Wasnix** [SimpleMobileTools/Simple-Gallery#1079]
When gallery apps starts only a blank background is shown without any images. After some seconds the images are displayed and app works as expected.

The old f-droid version 5.1.3 displays same pictures immediately. The settings of version 6.0.0 are identical to 5.1.3. There a many thousand pictures on my smartphone but version 5.1.3 never had performance problems. 

This behavior happens every time when app starts. My smartphone has 4 GB RAM, 64 GB internal memory and 64 GB sdcard, Android 7.1.2 with octacore Snapdragon 625

**Comment by tibbi** [comment]
should be better with 6.0.1, reopen if not

**Comment by tibbi** [comment]
recheck with 6.1.0

**Comment by lu-x** [comment]
I can confirm this still is an issue with the latest version from F-Droid 6.1.1.

**Comment by tibbi** [comment]
so when is it slow? At "Show all folders view"? Retest with 6.1.2 once available, some things have been improved.

**Comment by tibbi** [comment]
should be better with 6.2.0, reopen if not
