### ISSUE TITLE
option to select folders to index/view

### ISSUE THREAD

**Issue by itmike** [SimpleMobileTools/Simple-Gallery#108]
I happened to store a very large collection of small images in a deep directory heirarchy and noticed that the gallery app is now struggling every time it is started. Usally only shows a black screen until it sometimes manages to index/list/generate thumbnails. (a 'generating index..' notice would be helpful)

But, would it be simple to add an option to select what folders you like to watch for images?

Eg.
Default as-is but if some folders is selected only those.

...or speed up indexing of deep directory hierarchies. :)

**Comment by Cormak** [comment]
We definitely need this instead of the exclude folder feature. It makes things a lot simpler and more precise.

**Comment by touzainanboku** [comment]
Why not both? I'd rather have exclude.

**Comment by tibbi** [comment]
you can long press an item, press "Select all" and click exclude, then in Settings include the directories you want to see. If I understand it correctly..

**Comment by tibbi** [comment]
should be better in 3.7.0, Im rewriting the way media files are fetched
