### ISSUE TITLE
what is this "pro" version

### ISSUE THREAD

**Issue by schiessle** [SimpleMobileTools/Simple-Gallery#1083]
First let me say that I'm a huge fan, not only from Simple Gallery but from many of the Simple Mobile Tools. Thanks a lot for this great apps. Today my Simple Gallery from F-Droid told me that it is no longer maintained and that I should update to the "pro" version which I can't find in fdroid. Does this mean that Simple Gallery become proprietary? This would be really sad. Or what is the meaning of this pro version?

**Comment by tibbi** [comment]
you can find everything at https://medium.com/@tibbi/some-simple-mobile-tools-apps-are-becoming-paid-d053268f0fb2 . F-droid will receive free pro versions soon, as new apps.
