### ISSUE TITLE
6.0/pro issue as default app

### ISSUE THREAD

**Issue by krc** [SimpleMobileTools/Simple-Gallery#1084]
I updated Simple Gallery and Simple File Manager to the pro versions and then removed the non-pro versions, now if I try to upload/attach an image in the browser (e.g. FB) or Twidere, the "Complete action using" screen doesn't have Simple Gallery or Simple File Manager as options at all. I have already opened the apps directly, and granted permissions...

**Comment by tibbi** [comment]
and you saw the old apps there? There wasnt really anything related to that changed. Try reinstalling them.

**Comment by krc** [comment]
no, the old apps were already uninstalled. Tried uninstalling and reinstalling, still nothing, also rebooted... nothing.

**Comment by krc** [comment]
![screenshot_20181117-160109_android system](https://user-images.githubusercontent.com/211671/48667124-59ebac00-ea84-11e8-92e8-6cf42dfb0563.jpg)

**Comment by chripo** [comment]
To fix this I had to remove 'simple thank you' and reinstalled gallery.

**Comment by chripo** [comment]
Try to reset the theme / app icon color.
