### ISSUE TITLE
App disappears in launcher

### ISSUE THREAD

**Issue by radasbona** [SimpleMobileTools/Simple-Gallery#1087]
Hi,
i replaced the app with the new 6.0 version. But the app disappears after a few seconds from the app launcher (Nova). 

I tried both versions, gplay and f-droid. 
Also after a restart. The app is visible for a few seconds and then it's gone.

Opening pictures with another file explorer works correct.

This newer happened before. 
Android 7.1. LineageOs.

**Comment by tibbi** [comment]
do you use Shared Theme? If you do, try uninstalling Simple Thank You.

**Comment by radasbona** [comment]
yes. That was it. Thank you.
