### ISSUE TITLE
No warning about shift to "pro" versions, and to short a timeframe for them to be free. 

### ISSUE THREAD

**Issue by Ryonez** [SimpleMobileTools/Simple-Gallery#1088]
Now, I'm not someone who uses their gallery a lot. However, I opened it up yesterday to have it inform me that my version was being depreciated,and to get the pro version from the store. Only to find it was only free for a week. That ended 5 days ago. 

This is to short a time frame, with not enough notification. Sure it's cheep, but I don't even know what to think. This was/is an open source app, and now a fee has been slapped on it. What's going on, and why wasn't there a more in you face warning about what happened?

**Comment by tibbi** [comment]
the dialog appears at app upgrade, I cannot give an even better warning. And 1 week free pro period is the most Google Play allows, even though I initially wanted to give 3 weeks. You can read the rest at https://medium.com/@tibbi/some-simple-mobile-tools-apps-are-becoming-paid-d053268f0fb2

**Comment by Ryonez** [comment]
A notification on the users device would have alerted me...

**Comment by tibbi** [comment]
I cannot send out any notifications, the apps are offline

**Comment by ouzowtf** [comment]
@Ryonez it's stated in the changelog you clearly didn't read.
Don't blame the developer for your fault.
You said it's cheap, then go buy it and support the dev for all the efforts he does to produce this awesome apps.

**Comment by Ryonez** [comment]
> @Ryonez it's stated in the changelog you clearly didn't read.
> Don't blame the developer for your fault.
> You said it's cheap, then go buy it and support the dev for all the efforts he does to produce this awesome apps.

>However, I opened it up yesterday to have it inform me that my version was being depreciated,and to get the pro version from the store.

Clearly didn't read, right... Or are you referring to the changelog on the play store? Cause you don't tend to read those when they are set to auto update (Also not helped by most devs always saying the update is "Bug and performance updates").

And while I say it's cheep, I am still completely miffed at the lack of advanced warning when there where steps that could have been done to inform the user clearly. Not all of us open every app on our phones every week. Steps were made, but I'm pointing out it wasn't quite enough.

I'm also not arguing for getting his other apps, I don't use them, he switch to a paid model, and I'll buy them if I want them. But gallery is one I do use, albeit not every week, which is why I'm annoyed at the lack of warning.

Nothing wrong with the app in the slightest.

A few notes:

>I will let you know both in the particular app, 

You should have it push a notification after the "final" update, not every user opens their apps weekly.

>in the app changelogs

Users will easily miss this if they have apps auto update.

>and on social media.

And most users won't follow devs on their social media.

I can't argue with the price, but yeah, when I could have had it for free, if I was informed of it... That does annoy me.

**Comment by ouzowtf** [comment]
If the non-pro version works for you, then keep on using it in the future.
Don't blame others.
The dev is very generous already and you still nag to get even more at no charge.
That's very rude behavior.

**Comment by Ryonez** [comment]
Ugh, of course, I'm rude.

I can't help but feel more and more bitter when I reach out in GitHub now and it must be really showing. 

The blame is fair, extra steps could have been made, that would have prevented me from missing the one week we had to shift to the new version for free. Nothing rude about it, I'm trying to remain level while trying to get that point across.

And while the the non-pro version obviously works, it's been depreciated and replaced. I would have changed straight away if I had been adequately warned.

At any point have I turned around and said, "Omg gimme it for free!!!"?
No, I brought up the issue of communication. I expected I have to pay, not happy about it, but that was my expectation before even opening this. I probably even will, as I don't like using F-Droid all that much, where I can get it for free later.

**Comment by chesio** [comment]
@Ryonez I got your sentiment, I also missed the one week offer, but I prefer app developer to spend his time on developing the app instead of coming up with extra steps trying to make sure everyone would notice the change in distribution/pricing model. If you don't like F-Droid and are not willing to pay € 0,69 for the app on the Play Store, you can compile the app from the sources yourself...

**Comment by michaelof** [comment]
... or, as @Ryonez is able to write issues here = has a github account: 

Take the APK from here and install yourself. That's what I did before Tibor decided to publish even the Pro apps on F-Droid

**Comment by Ryonez** [comment]
> I expected I have to pay, not happy about it, but that was my expectation before even opening this. *I probably even will*, as I don't like using F-Droid all that much, where I can get it for free later.

I don't mind, the cost isn't a horrible trade off for ease of installation. The issue is only for the lack of warning on my end.
