### ISSUE TITLE
Increase the area of instant media change with a tap

### ISSUE THREAD

**Issue by azat11** [SimpleMobileTools/Simple-Gallery#1089]
Now it's very narrow at the sides. I'd love for it to be at least tripled, otherwise you have to be very precise, and it's not convenient.

**Comment by tibbi** [comment]
It will be increased from 30dp to 50dp in version 6.0.1. I dont want to increase it further as gestures dont go through it and so it could be glitchy at zooming.

**Comment by azat11** [comment]
@tibbi That makes sense. Thanks.
