### ISSUE TITLE
Per-folder sorting 

### ISSUE THREAD

**Issue by touzainanboku** [SimpleMobileTools/Simple-Gallery#109]
I'd like to have sort order be separate for each folder. So for example one folder is sorted by name, while another one is sorted by date.

**Comment by tibbi** [comment]
I dont really want to implement something as complex, not many people would need it

**Comment by touzainanboku** [comment]
> not many people would need it

Really? I personally consider it a deal breaker.

Well, thanks anyway.

**Comment by touzainanboku** [comment]
Thank you for implementing this!

**Comment by tibbi** [comment]
yea, apparently more people requested it than Id imagine :)
