### ISSUE TITLE
Better way of managing excluded folders

### ISSUE THREAD

**Issue by touzainanboku** [SimpleMobileTools/Simple-Gallery#110]
The current implementation seems to be:

Long press folder -> action overflow -> Hide folder

Unless I missed it, there doesn't seem to be any option for undoing this. Also, you can only exclude folder that have images in them. So if you have (for example) five folders that you want to exclude, and they all have the same parent folder, you have to exclude them one by one, instead of just excluding their parent folder. 

My request is:

An option in the settings where you can manage your excluded folders. You can add new folders, and removing previously excluded ones. When you try to add a new folder to exclude, the app will ask the you to go to the desired directory. This means you can exclude folders even if they don't directly have images inside them.

**Comment by tp0** [comment]
> Unless I missed it, there doesn't seem to be any option for undoing this.

Long press again and "unhide".

**Comment by touzainanboku** [comment]
> Enable "show hidden folders" in settings, then long press again and "unhide folder".

Thanks for the tip. Although I do think that's a very confusing way of doing things.

**Comment by tibbi** [comment]
The next version will contain 2 ways of hiding the folder, both with a brief explanation at first usage. "Hide folder" will create a .nomedia file, you can still see those folders with toggling "Show hidden folders". The "Exclude folder" will hide it only within Simple Gallery, you can manage those in settings.

**Comment by touzainanboku** [comment]
Thank you for this!

Is it possible you could add some button to add excluded folders as well? Something like QuickPic?

I have a bunch of folders I don't want to see (hundreds), and having to select them one by one isn't really pleasant. If the new manage excluded folders screen had an add button, I could just as their parent folder and be done with it.

**Comment by tibbi** [comment]
ye I can add it, I have a lot of facebook stickers spread to hundreads of folders on one of my devices too ;)

**Comment by touzainanboku** [comment]
Thanks for that! 

BTW, it looks like excluding a folder doesn't exclude its children, so that's something to keep in mind.

**Comment by tibbi** [comment]
ye currently its intentional, I might find some way to make it selectable

**Comment by touzainanboku** [comment]
Yeah making it optional would be even better. Thanks again.

**Comment by tibbi** [comment]
excluding got a couple changes, in the next version subfolders will be excluded too. Also you will be able to easily exclude the parent folder from the exclude dialog. Thats the clearest solution I could think of.

**Comment by touzainanboku** [comment]
Thanks! It's working great.
