### ISSUE TITLE
Group by Date Taken not working

### ISSUE THREAD

**Issue by malnvenshorn** [SimpleMobileTools/Simple-Gallery#1100]
After selecting "group by date taken" all pictures show up under "today", which is the last modified date, because I moved them from another phone. In the properties the "date taken" is shown correctly. Therefore I think it's an issue with that feature.

**Comment by tibbi** [comment]
try selecting the image thumbnails and using the "Fix date taken values" menu item

**Comment by malnvenshorn** [comment]
Thanks it works now.
