### ISSUE TITLE
Is there a maximum number of folders allowed to be shown at once?

### ISSUE THREAD

**Issue by azat11** [SimpleMobileTools/Simple-Gallery#1112]
I seem to not be able to make the app show all folders with images. And they are not excluded or hidden.
I'm using the latest Pro version, btw.
I'm guessing that folders some levels down within the file tree are ignored.

**Comment by tibbi** [comment]
some spam prevention has been added, I guess folders with more than 50 subfolders are getting excluded in your case? Ill try improving that.
