### ISSUE TITLE
Issues with setting wallpapers through the android settings

### ISSUE THREAD

**Issue by malnvenshorn** [SimpleMobileTools/Simple-Gallery#1113]
First of all when I launch simple gallery and set a wallpaper with the "set as" option everything works as expected. But when I launch simple gallery through the android settings menu  to set a wallpaper the actions at the bottom (e.g. rotate)  don't work. That means I can only set a square(?) wallpaper which then gets cropped and scaled at the end.

Tested on a S3 Mini (Stock Android 4.2.2) and S5 Mini (LineageOS 14.1).

**Comment by tibbi** [comment]
what app version do you have? Android 4 isnt even supported anymore.

**Comment by malnvenshorn** [comment]
On my S5 Mini the latest available from f-droid (6.0.2).

I mentioned the old one, because I switched just recently to the new phone and thought the bug might be fixed by now. But that's not the case so I opened this ticket.

**Comment by Chipe1** [comment]
+1, same problem on OxygenOS 10.5.6(android 10) and MIUI Global 10.3.9(android 9)

**Comment by seazzon** [comment]
+1, same problem on Android 6 and 7.1.2 via Launcher3 (AOSP).
