### ISSUE TITLE
Issue In Video.

### ISSUE THREAD

**Issue by stizzo1** [SimpleMobileTools/Simple-Gallery#1119]
Correct this boring problem and I will definitely go to this beautiful program.

https://www36.zippyshare.com/v/mAnQBVzD/file.html

**Comment by tibbi** [comment]
just describe the issue please, Im not going to watch a 2 minutes video everytime just to find the glitch. The video might also become unavailable soon. Thanks

**Comment by stizzo1** [comment]
in test, two programs, Google Photo and your program.

I started with Google photo, with several steps between one window and the other, I have no problems with the sound and with the video (mp3 / mp4), it never stops.

Then, I started your program, the result can also be seen on video, continuous blocks between the passage of one tower to another, especially when I close in the background.

The glithe, are not the problem.

Android 8.1

**Comment by tibbi** [comment]
retry with 6.2.0 please, the video player has been fully rewritten
