### ISSUE TITLE
[Request] Support animated WebP

### ISSUE THREAD

**Issue by utack** [SimpleMobileTools/Simple-Gallery#1124]
Hi,

could you please consider support for animated WebP.
At the moment the first frame is displayed as static image, but I think the Android system should support all facilities to do the decoding of the animated thing.

Thanks for consideration!

**Comment by hjyoung1** [comment]
Any update on this?

**Comment by Mar2ck** [comment]
+1 ive been waiting on this for a while. Is there any progress?

**Comment by tibbi** [comment]
I havent worked on it yet

**Comment by tibbi** [comment]
sample file sent by Michal on February 6 2020

**Comment by Mar2ck** [comment]
> sample file sent by Michal on February 6 2020

?

**Comment by tibbi** [comment]
just a note to myself
