### ISSUE TITLE
Video goes black when focus is lost and regained

### ISSUE THREAD

**Issue by TheRandomLabs** [SimpleMobileTools/Simple-Gallery#1132]
Adding a few lines to `VideoFragment.onResume` like I did [here](https://github.com/TheRandomLabs/Simple-Gallery/commit/c3fb564da055b191afc98f8a5cc97cb285f27504) seems to fix this issue, but I don't know if that's the proper way to do it.

**Comment by tibbi** [comment]
ye there are some black video issues, but Im not yet sure how to fix it. That code is just about the play button.

**Comment by TheRandomLabs** [comment]
The last two lines are, but the first reinitalizes the ExoPlayer, which
seems to work for some reason.

**Comment by tibbi** [comment]
aha I see, those extra tabs confused me. Ill take a look at it someday again. Thanks

**Comment by tibbi** [comment]
retry with 6.2.0 please, video playback has been fully rewritten and changed
