### ISSUE TITLE
Unable to set wallpaper on a custom ROM

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#114]
its a Aosp-caf ROM for op3, getting "No app capable of it has been found" error

**Comment by mueller-ma** [comment]
It works on Fire Nexus ROM for Amazon Fire 7" 2015 Tablet

**Comment by Theobald93** [comment]
Get the same error on LineageOS 14.1 (= Android 7.1.1).
Device: Xiaomi Redmi 3
I am playing a lot around with wallpapers, so i would really appreciate it if you could fix this :)

**Comment by gsantner** [comment]
Same here. LOS 14.1. No problem with other gallery or launcher apps with setting wallpapers so far.

**Comment by Theobald93** [comment]
Its working now. :)
LineageOS 14.1 20170628
Android 7.1.2
Xiaomi Redmi 3
Simple Gallery 2.12.2
