### ISSUE TITLE
Add .avif (AV1 Image File Format) support

### ISSUE THREAD

**Issue by utack** [SimpleMobileTools/Simple-Gallery#1143]
Inspired by https://github.com/derf/feh/issues/437

The AV1 Image File Format (AVIF) is a new image format based on the AV1 video codec. It would be great if support for this format could be added.

The AVIF spec can be found here: https://aomediacodec.github.io/av1-avif/
Netflix published a bunch of test images: http://download.opencontent.netflix.com/?prefix=AV1/Chimera/AVIF/

Seems far outside the scope of the project to implement everything, but It probably makes sense to see if something like a "libavif" will be made, or if ffmpeg can be tied into the app to decode it, once support lands there.

**Comment by EwoutH** [comment]
[libavif](https://github.com/joedrago/avif) tagged a new release, [0.1.3](https://github.com/joedrago/avif/releases/tag/v0.1.3). See [Colorist](https://github.com/joedrago/colorist) for an example [implementation](https://github.com/joedrago/colorist/blob/master/lib/src/format_avif.c).

**Comment by tibbi** [comment]
that library and project arent even related to android

**Comment by ForgottenUmbrella** [comment]
Support for uncommon file types should be requested upstream, in the Android Open Source Project for image formats, and the ExoPlayer repo for video formats. This would mean that all galleries and video players could automatically support the formats without everyone needing to implement their own special logic to handle them.

**Comment by TheLastGimbus** [comment]
Hi there! I recently spent good few hours planning on compressing my whole photo collection, and wanted to use AV1 for all videos, as it seems totally based. I found that
- Toten (default player in Ubuntu) doesn't work
- VLC does work :tada:
- SimpleGallery doesn't work :cry: 
- Google Photos (normal as well as Go edition) does work!
- Default Lineage17 doesn't even see them :c
- Signal desktop does work!
- Signal android (on Lineage14) does not :(

@tibbi if you could get it to work in SimpleGallery it would be awesome! 

> Support for uncommon file types should be requested [...] in the ExoPlayer repo for video formats.

Seems like you need to compile av1 extension yourself to add it to exoplayer:
- https://medium.com/google-exoplayer/playing-av1-videos-with-exoplayer-a7cb19bedef9
- https://github.com/google/ExoPlayer/blob/dev-v2/extensions/av1/README.md

**Comment by tjk918** [comment]
Even in Android 12 (has native avif support), this app still does not open or recognize avif. Simple Files from the same Simple Mobile Tools project, however, will display avif image thumbnails. I can't say I'm not confused. Does Simple Files use a thumbnailing library that supports avif? Either way it would be better to get this implemented sooner or later to stay ahead of the curve. It seems like with more phones having hardware based av1 decoders and encoders built in, it could become the new standard for photos on Android.

**Comment by tibbi** [comment]
It should technically be there in 6.23.2 on Android 12+. It doesnt show up on my device though, but it might be some codec glitch or something. We will see.

**Comment by TheLastGimbus** [comment]
In 12+ ? That is like... almost noone?

**Comment by tibbi** [comment]
well, thats when Android received the support. And no, over 23% of new app installs come from Android 12

**Comment by tibbi** [comment]
Google Photos likely have some deep support for it, they many tons of developers for every aspect of the app

**Comment by kolAflash** [comment]
I also like to see support for new, patent free formats like AVIF 👍😀

&nbsp;

Sadly for me AVIF pictures on Android-10 ([e/OS/](https://e.foundation) on FP3+) stay black. I guess this is due to Android-10!?

&nbsp;

Related or maybe duplicate requests:
- https://github.com/SimpleMobileTools/Simple-Gallery/issues/2441 _add support for avif image format_
- https://github.com/SimpleMobileTools/Simple-Gallery/issues/2496 _AV1 support_
