### ISSUE TITLE
Swap aspect ratio x:y on double click at cropping

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#1158]

**Comment by jmichael2497** [comment]
likely referring to wanting a quick toggle to rotate common aspect ratios, based on target goal of ending up with landscape vs portrait image, regardless of source shape.

for example: maybe starting with a portrait image and want to end up with a landscape, so just using the common 16:9 crop and done, but...

with that same portrait image, maybe want to stay in portrait mode, so quick toggle tap to change that 16:9 to 9:16 crop and done.

**Comment by sbliven** [comment]
+1 to this feature (as described by @jmichael2497). Fixed aspect ratios are very nice, but I'm currently using a rotate-crop-rotate workaround to get portrait aspect ratios. Alternating 16:9 with 9:16 would be an intuitive implementation imo.

**Comment by tibbi** [comment]
you can already press the Custom aspect ratio at the Pro version where you can select both 16:9 and 9:16 to make it quicker

**Comment by jmichael2497** [comment]
> you can already press the Custom aspect ratio at the Pro version where you can select both 16:9 and 9:16 to make it quicker

i recently noticed this, so maybe i just hadn't updated in a while, close as resolved, thanks.

**Comment by tibbi** [comment]
this is already available in the new editor
