### ISSUE TITLE
App deletes its own icon

### ISSUE THREAD

**Issue by Instagit** [SimpleMobileTools/Simple-Gallery#1159]
I used the custom color function. Now the app icon is gone with no apparent way of getting it back.

This is on a Sony so maybe it's related to their UI customization.

Open/Uninstall options are also not available in the app store. Only refund.

Are settings like "change app icon color" really worth it when they can break the app like this? I'd rather pay 5$ for a stable version without such experimental features, because the app itself is actually really good.

**Comment by tibbi** [comment]
it is a launcher issue, not something on my side. Some launchers do not handle icon customization properly. I will actually show a warning at using it from the next version. You can launch the app via playstore and change it back to the original orange #F57C00

**Comment by Instagit** [comment]
>You can launch the app via playstore and change it back to the original orange #F57C00

Like I said, that was not possible. The app store only had "refund", open and uninstall options were gone. I had to refund and buy again to reinstall it.
