### ISSUE TITLE
Directory exclusion doesn't work

### ISSUE THREAD

**Issue by Instagit** [SimpleMobileTools/Simple-Gallery#1160]
I tried to exclude the internal directory

````
/storage/emulated/0/DCIM/.thumbnails
````

but it still shows up. Might be because of the dot in the beginning?

After a reinstall to work around https://github.com/SimpleMobileTools/Simple-Gallery/issues/1159 I can't reproduce this anymore.

**Comment by tibbi** [comment]
dont you have the folder or some parent folder at the app settings -> manage included folders? What app version do you have?

**Comment by Instagit** [comment]
It's possible that I had the parent directory included and the child dir excluded, yeah. I can't check since I reinstalled, so I'll close this issue.

I would generally expect the more specific setting to always work, i.e. sub directory setting takes precedence over parent dir setting. Some kind of notification could be useful if that's not the case. Anyway, thanks for the quick response and happy holidays. :)

**Comment by polyzen** [comment]
Having this same issue. No dirs are explicitly included. 6.4.1

**Comment by tibbi** [comment]
you mean that you have a folder at the app settings -> manage excluded ones, nothing is at the included ones and it still shows up? Do you have hidden item visibility enabled?

**Comment by polyzen** [comment]
Yes. No. `/storage/emulated/0/Books` and `/storage/emulated/0/audiobooks`.

**Comment by tibbi** [comment]
hm, dont you have one of those devices where the internal storage can be referenced in multiple ways? If you select one of those excluded folders on the main screen and select "Properties", do you see the path in the format which is listed at the excluded folders? Is the casing the same too?

**Comment by polyzen** [comment]
Woops, I forgot to exclude the `Music` dir. Sorry, I set this up while half-asleep. ;D Works great.
