### ISSUE TITLE
Suggestion - Allow playing videos with third party players by default

### ISSUE THREAD

**Issue by Rikk** [SimpleMobileTools/Simple-Gallery#1168]
Maybe this is the missing piece for me to replace QuickPic completely...
I would like to play videos with MX Player instead of internal player, just like I can do with QuickPic. "Open with" each video is not viable alternative for folders with many videos.

**Comment by tibbi** [comment]
will be added in 6.2.0

**Comment by Rikk** [comment]
Thanks, it is a very nice addition. However, there is a difference from QuickPic:
When MX Player opens a video from QuickPic, it receives a direct path; but when it comes from Simple Gallery, it receives a content:// url and doesn't play next/previous videos in the same folder.
(Android 5.0.2)

**Comment by tibbi** [comment]
direct path cannot be shared anymore, it is an Android system limitation. In some cases the app can retrieve the real path from content uri, but not always.

**Comment by Rikk** [comment]
But for older Android versions, would it be too much work to implement?

**Comment by tibbi** [comment]
it is impossible to upload new Google Play app targeting version older than Android 8. It works in apps like Quickpic just because they havent been updated in ages and so they evade most Android security features etc.

**Comment by Rikk** [comment]
Some tests indicate the problem happens only when the folder name starts with dot (.hidden folders), therefore Simple Gallery sends clean path to MX when the directory is a normal folder, for example:
![s gallery mx player dot folder](https://user-images.githubusercontent.com/2916485/50736352-c725de80-11a3-11e9-8bc2-1697c62f8576.gif)

**Comment by Rikk** [comment]
I'm not doing anything and I doubt MX is either.
For files opened in normal folder, MX uses clean path; for dot hidden folder, it uses content url from Simple Gallery.
If I open video using a **file manager**, MX uses clean path in both kinds of folder. As far I can see as an user, the problem seems related to the way Simple Gallery is handling this, somehow.
