### ISSUE TITLE
Video playing issue

### ISSUE THREAD

**Issue by OLEG4120** [SimpleMobileTools/Simple-Gallery#1193]
Some videos not playing
![scr_20190108_180154 mp4](https://user-images.githubusercontent.com/8065693/50838985-65ff3600-1370-11e9-955c-e6f69dc08de9.gif)
Mediainfo:

*** General
Complete name:  /storage/DE7E-14FE/Media/Videos/bunny_1080p.mp4
Format:  MPEG-4
Format profile:  Base Media
Codec ID:  isom (isom/iso2/avc1/mp41)
File size:  2.72 MiB
Duration:  10 s 22 ms
Overall bit rate:  2 274 kb/s
Movie name:  Big Buck Bunny, Sunflower version
Performer:  Blender Foundation 2008, Janus Bager Kristensen 2013
Composer:  Sacha Goedegebure
Genre:  Animation
Writing application:  Lavf57.56.100
Comment:  Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net

*** Video
ID:  1
Format:  AVC
Format/Info:  Advanced Video Codec
Format profile:  High@L4
Format settings:  CABAC / 4 Ref Frames
Format settings, CABAC:  Yes
Format settings, ReFrames:  4 frames
Codec ID:  avc1
Codec ID/Info:  Advanced Video Coding
Duration:  10 s 0 ms
Bit rate:  1 928 kb/s
Width:  1 920 pixels
Height:  1 080 pixels
Display aspect ratio:  16:9
Frame rate mode:  Constant
Frame rate:  30.000 FPS
Color space:  YUV
Chroma subsampling:  4:2:0
Bit depth:  8 bits
Scan type:  Progressive
Bits/(Pixel*Frame):  0.031
Stream size:  2.30 MiB (85%)
Writing library:  x264 core 148
Encoding settings:  cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=3 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=23.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Codec configuration box:  avcC

*** Audio
ID:  2
Format:  AAC LC
Format/Info:  Advanced Audio Codec Low Complexity
Codec ID:  mp4a-40-2
Duration:  10 s 22 ms
Duration_LastFrame:  -5 ms
Bit rate mode:  Constant
Bit rate:  341 kb/s
Channel(s):  6 channels
Channel layout:  C L R Ls Rs LFE
Sampling rate:  48.0 kHz
Frame rate:  46.875 FPS (1024 SPF)
Compression mode:  Lossy
Stream size:  417 KiB (15%)
Default:  Yes
Alternate group:  1

**Comment by OLEG4120** [comment]
Video
[video.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/2737281/video.zip)

**Comment by tibbi** [comment]
works fine to me. Maybe the folder is not recognized properly, try copying the file somewhere else, or copy another video in this folder. What app version and Android OS version you have?

**Comment by OLEG4120** [comment]
Folder is /sdcard/Downloads/ And other one is /storage/DE7E-14FE/Media/Videos/
I dont understand whats wrong.
[gif.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/2737988/gif.zip)

Moto g5s, Android 7.1.1

**Comment by tibbi** [comment]
try updating to 6.2.2, when the previous video playback has been restored, the new one can be enabled in the app settings. Do all videos work well there?
