### ISSUE TITLE
Choose a custom thumbnail for a folder

### ISSUE THREAD

**Issue by tnguyen14** [SimpleMobileTools/Simple-Gallery#1211]
Is it possible to select a custom thumbnail (instead of just the latest one) for a folder?

**Comment by ouzowtf** [comment]
Yes, already possible

**Comment by tibbi** [comment]
you can do it by long pressing the folder, then Menu -> Change cover image.

**Comment by tnguyen14** [comment]
@tibbi could it be added to the Menu when you're inside a folder? That seems a bit more intuitive/ expected to me.

**Comment by tibbi** [comment]
not really, that doesnt feel intuitive to me :) So far also nobody else requested it.
