### ISSUE TITLE
Check a saving issue at drawing over .png files

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#1244]

**Comment by AbdulRehmanAB** [comment]
how to solve this error   ERROR: G:\AndroidStudioProjects\Simple-Gallery-master\keystore.properties (The system cannot find the file specified)
Open File

**Comment by tibbi** [comment]
according to the reporter they can be saved on an SD card, but not internal storage

**Comment by tibbi** [comment]
cannot reproduce
