### ISSUE TITLE
ERROR: G:\AndroidStudioProjects\Simple-Gallery-master\keystore.properties (The system cannot find the file specified) Open File

### ISSUE THREAD

**Issue by AbdulRehmanAB** [SimpleMobileTools/Simple-Gallery#1245]
ERROR: G:\AndroidStudioProjects\Simple-Gallery-master\keystore.properties (The system cannot find the file specified)
Open File
please help me

**Comment by tibbi** [comment]
well, create the file. There is even a sample one.
