### ISSUE TITLE
java.lang.SecurityException when trying to edit a shared photo

### ISSUE THREAD

**Issue by NWuensche** [SimpleMobileTools/Simple-Gallery#1269]
When I try to edit a photo which was send by another app to the gallery, I get an java.lang.SecurityException in a toast, because I don't have the permission to edit this photo.
Steps to reproduce:

1) Use Dolphin Browser (Other Apps might work too)
2) Download any picture
3) Select the picture in the Download folder and open it with the gallery
4) Click on the edit pen at the bottom

I tried changing the `onClickListener` of the `bottom_edit` from

```
 bottom_edit.setOnClickListener {
    openEditor(getCurrentPath())
}
```

to
```
 bottom_edit.setOnClickListener {
            try{
                openEditor(getCurrentPath())
            } catch (e: java.lang.Exception) {
                applicationContext.toast("CAUGHT!")
            }
 }
```
. However, I still get the SecurityException toast and not the "CAUGHT!" toast. Do you know why this happens and where this exception could be caught?

**Comment by tibbi** [comment]
what app version do you have? openEditor is catching its own exceptions

**Comment by NWuensche** [comment]
I used 5.1.4 (Play Store) and 6.5.1 (GitHub master)

**Comment by NWuensche** [comment]
So might the only way solving this problem is not showing the edit button in this specific case?

**Comment by tibbi** [comment]
I dont know, will get to it someday

**Comment by tibbi** [comment]
many glitches have been fixed in the Pro version, reopen this if it still happens
