### ISSUE TITLE
Cannot write to / delete from SD card

### ISSUE THREAD

**Issue by bwurst** [SimpleMobileTools/Simple-Gallery#127]
When I try to delete a picture, Gallery asks me to "select the card from the next dialog". The Dialog does not have anything to select, only "Recent" which is empty.

Moto G4 german.

**Comment by bwurst** [comment]
Okay, found out and sorry for the noise. The default setting of the open dialog is to **HIDE** the SD card.

Perhaps this could be made clear in the screenshot that appears.

**Comment by tibbi** [comment]
ye sometimes its hidden, sometimes its not. I chose the simpler version just to make it not that confusing ;) Maybe ill recheck it in the future, so far everybody found a solution.

**Comment by bwurst** [comment]
I uninstalled the app the first time because it did not work. ;-) Later, other apps also did show this screen and there, I found out.
