### ISSUE TITLE
Keep thumbnails for videos

### ISSUE THREAD

**Issue by Theobald93** [SimpleMobileTools/Simple-Gallery#1271]
I have a folder with videos on my microSD-Card and sometimes the thumbnails are gone. Regenerating the thumbnails needs a lot of time and power.
I am not using any apps to delete caches or something like that.
Can you change that behaivior and save the thumbnails forever?

More Info:
Folder on the microSD-Card
microSD-Card is hidden in the App
436 files, 2.9 GB
"Crop thumbnails into squares" OFF
"Show video durations" OFF
Xiaomi Redmi 3
Android 7.1.2 - Lineage 14.1
Simple Gallery Pro v6.5.1

**Comment by tibbi** [comment]
Cache is handled by Glide, not me. It is limited to 256mb, cleaned up whenever it thinks it is appropriate. I dont really want to mess with it.
