### ISSUE TITLE
[Feature Request] Add lable background color to titles in thumbnail view.

### ISSUE THREAD

**Issue by Marvinoo** [SimpleMobileTools/Simple-Gallery#1277]
In this screenshot, http://imgs.fyi/img/7c62.jpg some album labels are barely seen over the whiteness of some pictures. So I thought adding a chosen color/accent color as a background for labels would be a nice addition.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by Marvinoo** [comment]
6.5.2 from F-droid. Does this have something to do with the app version?

**Comment by tibbi** [comment]
no, yours is good enough. The dark background has been darkened some time ago, but you have the latest one already

**Comment by tibbi** [comment]
screenshot no longer valid, or maybe imgs.fyig is down
