### ISSUE TITLE
Weird flicks while using the new gestures

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1278]
Sometimes images will "flick" while rotating with two fingers using the new gestures. Link is a quick video showing the issue:
https://youtu.be/j11TSxUhdE0

**Comment by tibbi** [comment]
what app version are you using?

**Comment by NikhilSudhakaranVG** [comment]
increase and decrease column count using gesture is nice feature. but its not smooth.
make it smooth. adding an animation is great

**Comment by floppyD** [comment]
@tibbi 6.5.2 from Play Store.

**Comment by floppyD** [comment]
@tibbi Just noticed that this issue still exists, I'm guessing that commit wasn't enough to fix it?
