### ISSUE TITLE
Deleting or moving file does not delete them completely

### ISSUE THREAD

**Issue by neekless** [SimpleMobileTools/Simple-Gallery#1281]
When a file is deleted (with recycle bin turned off) or moved in 6.5.2, the file is not deleted completely and they can be seen in Google Camera or Google Photos (no backup).

I have tested multiple time switching between 6.5.1 and 6.5.2 and can confirm it only happens on 6.5.2, possibly due to https://github.com/SimpleMobileTools/Simple-Gallery/commit/3272398f49f0287fe582293056c7ac6e76a2ef77, or https://github.com/SimpleMobileTools/Simple-Gallery/commit/e31be23bf4ec763b7acc686085804f8ec0b672c5, or any commit between 6.5.1 and 6.5.2.

Below I will attach two videos showing what I mean. After taking a photo in Google Camera, I proceeded to delete it in Simple Gallery. Then I went back to Google Camera and check the recently taken photos in the bottom right.

6.5.1: https://drive.google.com/open?id=1G9N8pwYmuAlAgQ2fYXQ_4Ro-EXbaX6D2
The newly taken photo is gone and is showing the second most recent photo

6.5.2: https://drive.google.com/open?id=1oclCroqmYcQ1YQyO70xUueOD-HmLzq4N
A low resolution "ghost" of the newly taken photo will still be there, along with the loading circle loading indefinitely.

If I go into Google Photos (backup turned off), the newly taken photo will be gone if deleted from SG 6.5.1, but the "ghost" will also be there if deleted from SG 6.5.2.

This may be a duplicate of this [issue](https://github.com/SimpleMobileTools/Simple-Gallery/issues/1261) but I doubt it, as their issue happens on 6.5.1 but I am confident my issue doesn't happen on 6.5.1, and they are seeing "blank" images while I am seeing low resolution copies of the deleted file.

**Comment by tibbi** [comment]
it is a different issue, it should be fixed in version 6.5.3 released soon. But Ill remove that 20% too to avoid some glitches.
