### ISSUE TITLE
Check FairMail not listing Gallery as an attachment picker

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#1284]
maybe they ask for any generic file, not an image

**Comment by tibbi** [comment]
it apparently isnt a mature project yet

**Comment by ouzowtf** [comment]
I don't know what exactly was tried and in which version of FairEmail, but I just tested to open an image attachment in Simple Gallery from a mail draft and it worked just fine.

FairEmail version: 1.341
Simple Gallery version: 6.5.3
