### ISSUE TITLE
[Feature Request] Different transition animation

### ISSUE THREAD

**Issue by blaxx3r** [SimpleMobileTools/Simple-Gallery#1286]
Would it be possible to implement another transition animation between folders and when you open a picture in a folder, because in my opinion the current slide animation makes the app feel slower than it actually is and cannot do justice to the actual speed of your app. I used Simple Gallery with global animations turned off in developer options and it is way snappier than it feels with the current animation. Have you considered something like a quick zoom animation (like in Samsung Gallery or iOS Gallery) before?

**Comment by tibbi** [comment]
Im using the default system animation, it isnt customized. Some new animations might be added someday, but it isnt a priority for now. Anyway it has been reported somewhere, so Ill close this one. Thanks
