### ISSUE TITLE
Bug: Tapping photo button in camera app doesn't bring up picture just taken

### ISSUE THREAD

**Issue by hockeymikey** [SimpleMobileTools/Simple-Gallery#1291]
How to reproduce: Take a picture and then tap the photo button in your camera app to bring up the gallery and the new picture you just took. It will instead bring up the most recent photo before you took that picture. Go back and try it again and the new photo will finally be pulled up. This is pretty annoying. 

Moto G4 Play, Android 7.1.2 LineageOS 14.1. Using the most recent version from Fdroid. Neither using the default camera nor OpenCamera change anything.

**Comment by tibbi** [comment]
does the proper image open in some other galleries?

**Comment by hockeymikey** [comment]
Yes it does.

**Comment by ChrisLahaye** [comment]
How did you solve this issue?

**Comment by hockeymikey** [comment]
Looks good now.
