### ISSUE TITLE
Feature: Reorder actionbar and menu

### ISSUE THREAD

**Issue by hockeymikey** [SimpleMobileTools/Simple-Gallery#1292]
The file name is always cut off for me because of the two buttons in the actionbar. I can't use the app to quickly sort through images for work.

A nice fix would to allow the user to reorder and remove items from the menu and actionbar. I would like to remove all the items from the actionbar besides the menu button and move some to the menu bar. There are other items I would like to remove all together to clean up the menu since I will never be using them.

**Comment by tibbi** [comment]
that cannot really be done, it is a not that flexible system element. Thanks

**Comment by hockeymikey** [comment]
Like hell the actionbar isn't: https://stackoverflow.com/questions/10322848/how-can-i-add-an-action-bar-item-during-run-time
https://stackoverflow.com/questions/37543244/how-to-show-hide-action-bar-item-programmatically-via-click-event
If I had more time (sadly I don't) I would do it myself to prove a point.
