### ISSUE TITLE
Speed up new image detection using a ContentObserver

### ISSUE THREAD

**Issue by hockeymikey** [SimpleMobileTools/Simple-Gallery#1293]
So when new images are added, the app is always really slow to detect them. It has to rescan all the directories (I assume, haven't checked your implementation) and finally the new images pop up after like 10 seconds atleast. Should declare a ContentObserver and add the new images to the cache/database right when they are created so the user isn't left waiting and the whole process is much more streamlined and elegant. Would be pretty easy to implement I imagine too.

https://developer.android.com/reference/android/database/ContentObserver

**Comment by hockeymikey** [comment]
@tibbi Quick turnaround, but glancing at the code, I don't totally think it's implemented how it should. So the contentobserver should be running in a service in the background, because we want it to pickup the changes to any new images right away when the app isn't in the foreground/active. Actually, in 7.0+ you can do this: https://developer.android.com/reference/android/app/job/JobInfo.Builder.html#addTriggerContentUri(android.app.job.JobInfo.TriggerContentUri)
Make life easier for those devices, but anything under 7.0 should just use a service instead (can be pretty light).

**Comment by tibbi** [comment]
thanks, Ill take a look at it later

**Comment by tibbi** [comment]
added a jobservice, but since it has like 10 seconds delay I left the previous way too, which is instant. Nowadays over 90% of app installs are from Android 7+, so I wont optimize it for the older versions for now.

**Comment by hockeymikey** [comment]
Hey, so in my testing the images instantly appear in folders if you navigate into them, but on the folder view (showing all the folders) it doesn't and you have to manually refresh it and wait.

**Comment by tibbi** [comment]
they should be refreshed too, it just might take a bit longer
