### ISSUE TITLE
Editor shortcut on the editor tool

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1300]
Maybe it's a leftover? All it does is open the editor that is already open.
![screenshot_20190228-230507](https://user-images.githubusercontent.com/29208110/53611555-c6ab3200-3bad-11e9-8e34-c33b3b8b1132.png)

**Comment by tibbi** [comment]
what app version are you using? It should show a list of editor apps, to open the image in another editor

**Comment by floppyD** [comment]
6.5.4. It should, but don't have any other editor installed. Shouldn't be better just remove that shortcut and call the apps list by the same shortcut you open it in the first place? Because opening another editor from a editor doesn't make much sense to me.

**Comment by tibbi** [comment]
it is not doing any harm, I want to keep it there
