### ISSUE TITLE
One finger zoom issue

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1343]
If you perform a one finger zoom and swipe to either left or right, instead of just moving around the image, the next/previous media will be shown.

**Comment by tibbi** [comment]
works fine to me. What app version do you have?

**Comment by floppyD** [comment]
6.6.0
https://youtu.be/93UF6JHFft4

**Comment by tibbi** [comment]
aha Im aware of that. It isnt related to one finger zooming, just zooming in in general. Duplicate of #1256
