### ISSUE TITLE
Sort by Date Taken still not working even with fix

### ISSUE THREAD

**Issue by Avrution** [SimpleMobileTools/Simple-Gallery#1347]
I have seen mention in the past about this, but was under the impression it should work correctly if you use the fix option on the photos.  

I can still only get sorting to work by date modified, though in properties it shows the correct date taken time.

**Comment by tibbi** [comment]
retry with 6.6.3 released soon please. Check it on some test images first, just to check that the file wont disappear.

**Comment by tibbi** [comment]
not enough info
