### ISSUE TITLE
New image is not shown

### ISSUE THREAD

**Issue by bwurst** [SimpleMobileTools/Simple-Gallery#135]
When Gallery is put in the background and I take a picture, then switch back to Gallery, this new image can not be shown by swipe from left to right, without going back to the directory/thumbnail view.

**Comment by tibbi** [comment]
if it works by going to the thumbnail view and refreshing it, then its not a big deal.

**Comment by tibbi** [comment]
ye it seem to be working on other screens. I dont want to refresh the fullscreen view with the new image, that could move the user to another photo and he would be lost
