### ISSUE TITLE
Add info how to unhide folder

### ISSUE THREAD

**Issue by mueller-ma** [SimpleMobileTools/Simple-Gallery#136]
It would be useful to get a popup how to unhide a folder when hiding a folder the first time

**Comment by keunes** [comment]
An option would also be to add a snackbar (with undo option) on each hide.

**Comment by tibbi** [comment]
I probably wont add a snackbar as Im trying to get rid of it everywhere. I have to wrap the whole screen in another layout which makes the code more complex, and I dont think it helps the performance either. What I will do is create some better way of managing excluded folders, as reported in https://github.com/SimpleMobileTools/Simple-Gallery/issues/110
