### ISSUE TITLE
[FEATURE REQUEST] Full Screen Cropped Image

### ISSUE THREAD

**Issue by pyramid3d** [SimpleMobileTools/Simple-Gallery#1365]
Currently on double tap, the image will be zoomed so that both borders (horizontal and vertical) will stretch beyond the screen.

It would be good to have an option to set the behavior to zoom to full screen so that one border. touches the screen edge (while the other goes beyond the screen edge).

**Comment by tibbi** [comment]
I dont really want to complicate zooming that way, it sounds strange. Thanks

**Comment by pyramid3d** [comment]
It is actually the standard behavior of gallery apps, sometimes also called "full screen, keep aspect ratio". Can't find a good reference though, and can understand if it sounds too tedious ;-)

**Comment by pyramid3d** [comment]
Essentially it is rescaling an image to fit a given viewport size without losing aspect ratio. The code is actually quite trivial.
https://gist.github.com/vijinho/5bad31a16beedb9e02c8

**Comment by tibbi** [comment]
that is some random python code, that isnt used in android. Anyway it isnt about the code, I just dont think this feature is needed.
