### ISSUE TITLE
Suggestion - Move video duration to top right

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1368]
If the filename is long enough, it'll overlap the video duration. If it was moved to the top right, things would look a bit better.
![Screenshot_20190402-200008](https://user-images.githubusercontent.com/29208110/55441682-089b0f80-5582-11e9-954b-82376ef9b822.png)

**Comment by OlgaMorales** [comment]
hi @tibbi i'd like to participate on this issue.

**Comment by tibbi** [comment]
sure, you can take it

**Comment by OlgaMorales** [comment]
@tibbi Could you guide me by telling me what is that about this error which I'm facing >> 
 .../keystore.properties (No such file or directory)

**Comment by OlgaMorales** [comment]
hi @tibbi , in my case I don't see the file name and video duration, has been improved that feature?

**Comment by tibbi** [comment]
you have to enable duration showing in the settings, filename at the menu

**Comment by OlgaMorales** [comment]
What's the option to see the file name ? I've found only duration of video .

**Comment by tibbi** [comment]
it is at the top menu, the middle icon on the right side of the screenshot

**Comment by OlgaMorales** [comment]
Thanks, I'll check it

**Comment by OlgaMorales** [comment]
hi @tibbi my PR is done!

**Comment by tibbi** [comment]
will take a look at it later, thanks :)
