### ISSUE TITLE
Custom color doesn't appear on the title bar

### ISSUE THREAD

**Issue by OffifialMITX** [SimpleMobileTools/Simple-Gallery#137]
If you set a custom color and go to the active apps overview the panel's color is still the original one.

Tested on 2 different devices, both stock Android 5.1.1

**Comment by tibbi** [comment]
as far as i know thats one of the things I cannot change with the current level of color customization. Id be able to change it only if I had a couple preset styles the user can choose from, but i might recheck it in the future

**Comment by smichel17** [comment]
As far as I know, you can only set the panel's color in the active apps overview by changing the theme, which means preset styles, like @tibbi said.

I think having a couple preset styles for the primary color would be plenty, especially if the background and text color remains fully customizable. Amaze File Manager has 16 preset colors and it feels like it has most of what anyone would ever want (it is missing a few colors, like pink).

I know I've seen a material color picker dialogue library around somewhere, where you first pick the color, then the shade. It comes pretty close to fully customizable, and adding even a large number of themes is pretty easy as long as you're only changing the primary color (and maybe the primaryTextColor, to swap between black and white depending on background color).

**Comment by tibbi** [comment]
I prefer the current way, maybe in will change in the far future. I dont really want to spend too much time on customization now, want to focus on some features, bugs, other apps.

**Comment by tibbi** [comment]
this is a more general issue affecting all apps, Ill close this one
