### ISSUE TITLE
Playing videos in Conversations fails

### ISSUE THREAD

**Issue by x-jokay** [SimpleMobileTools/Simple-Gallery#1376]
Hello

When trying to play videos (mp4) from Conversations it fails.

The sound can be heard but no image.

![Screenshot_20190406-082855](https://user-images.githubusercontent.com/18613935/55665881-cf46f600-5846-11e9-8edb-1a0a595e7834.png)

Currently I'm using version **6.6.1** on an Android 8.0.0 Stock ROM.

Tried it with unencrypted and OMEMO encrypted videos.

When opening the Simple Gallery app the video can be played.

**Comment by x-jokay** [comment]
When activating this option

![Screenshot_20190406-084935_1b](https://user-images.githubusercontent.com/18613935/55666054-159d5480-5849-11e9-9b7e-333dead580ef.png)

I get a static (preview) image of the video but can't play it anymore.

**Comment by tibbi** [comment]
try with version 6.6.3, some video related things have changed there

**Comment by x-jokay** [comment]
Thank you, version `6.3.3` indeed fixed it 👍
