### ISSUE TITLE
Glitchy 'hidden' notice on folders

### ISSUE THREAD

**Issue by puppykickr** [SimpleMobileTools/Simple-Gallery#1379]
When looking at the folder page, certain folders that have not been hidden show that they have been.

When the selected folder(s) is/are unhidden, the notification may or may not remain.

It might also randomly flash off and on.

This only seems to occur on my 7.1.1 devices, no issue on my 8.1.0 go.

**Comment by tibbi** [comment]
hiding is recursive, arent those some subfolders that got hidden too?

**Comment by puppykickr** [comment]
Some are, some are not.
Either way, it is a crapshoot as to whether or not they will appear or not, and if they will be labeled as (hidden).

**Comment by tibbi** [comment]
what app version do you have?

**Comment by puppykickr** [comment]
I am using 6.6.1 at the moment.

I was using 6.0 for the longest, because it seemed to work flawlessly.
When newer versions came out I had trouble with videos playing and overall app stability.

So I reverted back to 6.0, until I obtained a newer device, an 8.1.0, and
I went ahead and downloaded the most recent version onto it.

I noticed (and liked) a few of the newer additions to the app, and went ahead and installed that version onto my 7.1.1 devices as well.

That is when the issue became apparent, on those devices.

It is quite possible that it is a device dependent issue.

Thank you for the excellent collection of apps, by the way.

This 8.1.0 came with an astounding lack of standard fare apps, and due to your hard work I knew exactly where to go for the best replacement system apps.

**Comment by tibbi** [comment]
try reproducing the issue with the latest version 6.6.4 though, just to ensure that it isnt fixed yet

**Comment by puppykickr** [comment]
Is that available on F-Droid?
I thought I had the most recent version, but F-Droid can be weird sometimes.

**Comment by tibbi** [comment]
6.6.4 is the latest one, it is on f-droid too

**Comment by puppykickr** [comment]
I think that the issue is resolved.
