### ISSUE TITLE
view geo tag

### ISSUE THREAD

**Issue by travisfw** [SimpleMobileTools/Simple-Gallery#138]
A lot of images have an embedded geo tag. It would be good to be able to view this somehow, for instance by opening a map showing the location.

**Comment by keunes** [comment]
+1 But please refrain from Google lock-in (eg using OSM or by allowing users to open in third apps)

**Comment by WalterS** [comment]
Same here. A much wanted feature and please no Google lock-in.

**Comment by tibbi** [comment]
will be added in 2.3.4. An app chooser of apps capable of displaying the map location will be shown, theres no lock-in whatsoever.
