### ISSUE TITLE
[Feature Request] Add possibility to create new album

### ISSUE THREAD

**Issue by Mannshoch** [SimpleMobileTools/Simple-Gallery#1380]
Allow creating new album.

1. Idea: Create a subdirectory Named by the Album-name we would like to have and move picture into it.
1. Idea: Create a tag for album and write the name into following meta tags (only if empty):
```
xmp.iptcext.event = lang="x-default" {ALBUM}
xmp.dc.subject = type="Bag" {ALBUM}
xmp.dc.title = lang="x-default" {ALBUM} 
xmp.acdsee.caption = {ALBUM}
xmp.photoshop.headline = {ALBUM}
iptc.application2.caption = {ALBUM}
iptc.application2.headline = {ALBUM}
```
To show album based on Meta information use _xmp.iptcext.event_ only.

I got the Idea from the Linux Application Shotwell. The listet value get set if you set a Title in Gnome Shotwell.

I would prefer to have the possibility to chose between both ways.

**Comment by tibbi** [comment]
I dont know what you mean, it looks like some geeky stuff. That isnt the target audience of the apps. Thanks

**Comment by Mannshoch** [comment]
Creating Albums on Smartphones has nothing to do with "Geeky" every new Smartphone has this ability included in their gallery.  May the way I propose in Idea 2 could be seen as Geeky.

**Comment by tibbi** [comment]
well you can already create a new folder with Menu -> Create new folder, then just copy something in it

**Comment by Mannshoch** [comment]
Hi @tibbi I tested it as you said, Sorry, I was not aware about this feature, because I know the feature from other gallery and looked for something about "Gallery". But The way it to complicated. In my opinion I only have to mark several images and point "new Album".
