### ISSUE TITLE
Group direct subfolders -- do not show folder count unless >= 2

### ISSUE THREAD

**Issue by lbdroid** [SimpleMobileTools/Simple-Gallery#1386]
Since most directories probably won't have subdirectories, it is just annoying to see them all tagged as "(1)". In the case where it is just 1, don't show that on the UI.

**Comment by Marvinoo** [comment]
TIBBI PLEASE revert back to the old subfolders grouping view or AT LEAST make it optional.

**Comment by lbdroid** [comment]
@Marvinoo : This just removes the unnecessary label that shows the NUMBER of subfolders WHEN THERE ARE NONE.

In other words, "Camera (1)" becomes "Camera", but "Gallery (5)" remains "Gallery (5)".

**Comment by Marvinoo** [comment]
Oh sorry for the inconvenience.

**Comment by lbdroid** [comment]
@Marvinoo: I think this commit is responsible for the behavior you are observing:
https://github.com/SimpleMobileTools/Simple-Gallery/commit/640ff05e204baa1d78593ff4ed839f7d5737cf72

It the behavior bothers you, you should create a new issue related to it.
