### ISSUE TITLE
Nextcloud native support

### ISSUE THREAD

**Issue by gabriellluz** [SimpleMobileTools/Simple-Gallery#1387]
Hi. I'm loving this SG app. Really great and it's working wonders for me as a Google Photos replacement.
One suggestion I have to make is to make it compatible with self-hosted cloud providers like Nextcloud and Syncthing.

Best regards,
Gabi

**Comment by tibbi** [comment]
No, and there is no cloud support on the roadmap either, as it would need access to the internet. Thanks
