### ISSUE TITLE
Pause animated gif in the 'gallery'

### ISSUE THREAD

**Issue by keunes** [SimpleMobileTools/Simple-Gallery#139]
I've downloaded [an animated gif](https://dkl3g0z0k6qzr.cloudfront.net/quickyformapp/images/branded_animated.gif) and since it's the latest image it is used as the 'cover image' for that folder. Since it's animated, there is quite a distracting cover in the Gallery overview. I think that as for videos, animated gifs should be just be represented by one frame (maybe even in a folder view where it is just the image preview).

**Comment by JohnVeness** [comment]
I notice that the setting "Animate gifs at thumbnails", when set to off, doesn't affect an animated gif that is used as a folder cover image.

**Comment by tibbi** [comment]
right thanks, will be fixed in the next version
