### ISSUE TITLE
problem in show viewpager of photos

### ISSUE THREAD

**Issue by CoderoidAcademy** [SimpleMobileTools/Simple-Gallery#1391]
hi, why my viewpager (in Sample Gallery) is like below:
![Uploading Screenshot_20190414-225243_Simple Gallery.jpg…]()
![Uploading Screenshot_20190414-225249_Simple Gallery.jpg…]()
![Uploading Screenshot_20190414-225340_Simple Gallery.jpg…]()

i want to show photos in full size and in center of screen
can you help me?

**Comment by tibbi** [comment]
the images are invalid, not sure what you mean

**Comment by CoderoidAcademy** [comment]
look this video
https://youtu.be/5DI1BmVJ9qQ

**Comment by tibbi** [comment]
This video is unavailable.

**Comment by CoderoidAcademy** [comment]
look this
https://youtu.be/YWYr5FW2idA

**Comment by CoderoidAcademy** [comment]
the photos in ViewPagerActivity place in bottom_right instaed center
and they have small size

**Comment by tibbi** [comment]
send me a sample file please, with which you can reproduce it. What app version are you using?
