### ISSUE TITLE
Navigation bar stays white while using dark theme

### ISSUE THREAD

**Issue by blaxx3r** [SimpleMobileTools/Simple-Gallery#1397]
The navigation bar of my Galaxy S10 is still white while the rest of the UI is dark which really deminishes the user experience.

![Screenshot_20190418-155419_Gallery(1)](https://user-images.githubusercontent.com/47918221/56583183-4adfcb80-65d9-11e9-899b-fedecaaaa151.jpg)

**Comment by tibbi** [comment]
I reported it at https://github.com/SimpleMobileTools/General-Discussion/issues/107 as it affects all apps. Thanks
