### ISSUE TITLE
Deleted pictures showing up on gallery while scrolling

### ISSUE THREAD

**Issue by Ke1i** [SimpleMobileTools/Simple-Gallery#14]
Pictures deleted via the inbuilt delete button somehow show up while scrolling other pictures in fullscreen.
The only way to permanently delete these pictures is to open Es Explorer and delete a couple of 0.00B (0 Bytes) files with the same name as the deleted pictures.
- Picture store location: Default "Simple Photos" directory in internal storage
- Simple Gallery version: 1.15 from F-Droid.
- Device: Samsung Galaxy S4 GT-i9500
- OS: Stock 4.4.2

**Comment by tibbi** [comment]
hello, can you give some more details? From which screen to you delete the images? The one where you have many images, or the one with fullscreen pictures? If its from the one with many images, is it enough to delete one image, or more? Can you reproduce it reliably?

**Comment by Ke1i** [comment]
Sorry I was away for a couple of days.
Its the screen with fullscreen pictures. And the issue arises when you delete just a couple of pictures- not all of them.

**Comment by tibbi** [comment]
hello, were the mentioned images on an SD card by any chance? If so, can you retest please?

**Comment by Ke1i** [comment]
No.
The images were on the internal memory.
I uninstalled the app and I'm using the stock gallery. I'll install and get back to you.

**Comment by Ke1i** [comment]
Downloaded Gallery version 1.30 from f-droid for testing. The problem still exists.

**Comment by tibbi** [comment]
hello, if you could test 1.31 from playstore of fdroid that would be great, a lot of changes have been made there.

**Comment by Ke1i** [comment]
Have you pushed ver. 1.31 already?
F-droid still shows ver. 1.30 as the latest. Let me give it a couple of hours.

**Comment by tibbi** [comment]
I have control only over playstore, f-droid is updating the apps with some daily script, which fetches the updates from https://github.com/SimpleMobileTools/Simple-Gallery/releases

**Comment by Ke1i** [comment]
I don't use google's play store so I can't test that latest version you've pushed.
Let me give it a day, I'll test and report.

**Comment by sakinyu** [comment]
Hello, I'm using v1.41 from f-droid. I can delete pictures from the phone using the button of the app. Nevertheless I can't delete pictures from the SD card and I need to do it with ES explorer or Amaze. Could you find a solution? Thanks a lot, a very useful and great app except for this problem.

**Comment by tibbi** [comment]
Hello, what Android version do you have? SD card handling is not working properly on Android 4

**Comment by sakinyu** [comment]
Hi! I'm using android 5.1 on a fairphone 2 open OS.

**Comment by tibbi** [comment]
so it looks like there is apparently an issue with deleting items from SD cards, I just dont have any device where I could reproduce it :/ It works on my devices.

**Comment by Tony-il-Capo** [comment]
Hi
The issue is still present on latest versions,
I have a Sony Xperia S, this device has 32 GB internal memory, no slots for external SD cards, when trying to delete pictures (from internal memory), pictures will show up again with zero bytes size when using a file explorer (eg. Amaze)

**Comment by tibbi** [comment]
Can you retry with 1.43 which should be on playstore soon please?

**Comment by Tony-il-Capo** [comment]
I don't use any google services, so, I will re-test it when it's updated on F-Droid.

**Comment by Tony-il-Capo** [comment]
V1.43 still have the same problem.
Pictures re-appear on Simple Gallery and I also can see them on Amaze File Manager, as mention before those pictures (files) have zero size.

**Comment by Tony-il-Capo** [comment]
v1.46 from F-Droid, guess what, same problem.
I will probably not check this anymore, I never used Simple Gallery as primary gallery browser and I will probably uninstall it.

**Comment by tibbi** [comment]
there are some issues with the filesystem on some devices which I just cannot reproduce anywhere, so I cannot even fix it for now

**Comment by kTyn9A9Kw3** [comment]
I had this issue with Android 6, it got fixed after the update that asks for storage permission

**Comment by Tony-il-Capo** [comment]
Hi
Version 2.1 from F-Droid seems to have this fixed somehow. Deleted pictures with Simple Gallery no longer re-appear again in file browsers or in Simple Gallery itself.

**Comment by Ke1i** [comment]
Just download version 2.1 from f-droid.. Loving the new look, keep up the good work.
I haven't tested the app much but the issue appears fixed.

*Running Android 5.0.1
*Pictures saved in the internal memory

**Comment by tibbi** [comment]
okay np
