### ISSUE TITLE
Image Details 

### ISSUE THREAD

**Issue by kamilmirza** [SimpleMobileTools/Simple-Gallery#141]
is it possible to show Image Details like dimensions, size & date in non-immersive mode?

**Comment by tibbi** [comment]
not sure what you mean, any more details? Or some screenshot of some app that does it?

**Comment by kamilmirza** [comment]
![screenshot_20170118-030920](https://cloud.githubusercontent.com/assets/6561475/22042142/b4b4aa3c-dd2b-11e6-98de-17208372c1aa.png)
look bottom left of the image; app is QuickPic

**Comment by OLEG4120** [comment]
Some thing wrong with details (position)
![scr_20171102_230106 mp4](https://user-images.githubusercontent.com/8065693/32348448-d6a8716e-c024-11e7-81cf-eba23493c969.gif)
May be better hide it with navbar?

**Comment by tibbi** [comment]
it is supposed to hide with navbar, Ill tweak it someday.
