### ISSUE TITLE
Option of Recycle Bin as First Folder

### ISSUE THREAD

**Issue by puppykickr** [SimpleMobileTools/Simple-Gallery#1410]
I remember that in past versions, if you did not select 'Show Recycle Bin as the last item on the main screen', the Bin was placed as the first item on the main screen.

Now it will come up alphabetically, under 'R'.

Although this is nice as an option, it can be a bit difficult for those that have many folders. (I have 75, all folders and Recycle Bin included.)

In this case, it is better to have the option available for the Recycle Bin to be the first folder on the main screen, as it makes the Bin much quicker and easier to find.

This supurb Gallery app makes it easier to clean unwanted junk out of devices, as the 'Show Hidden Folders' feature allows ads and other cached items to become visible.

As these are deleted and subsequently moved into the Recycle Bin, having the Bin at the top of the list makes it easy to find and double check before final deletion.

Thank you once again for your amazing series of apps.

**Comment by tibbi** [comment]
you can already pin it to the top. Just long press it and select "Pin folder to the top" at the top menu, the icon looks like a pin. Thanks

**Comment by puppykickr** [comment]
Cool.
Sorry about that.
I had never noticed that.
Thank you, once again.
