### ISSUE TITLE
Add option to disable image switch scroll animation

### ISSUE THREAD

**Issue by rogerdahl** [SimpleMobileTools/Simple-Gallery#1416]
Please add an option to show image directly without horizontal scroll animation when swiping to previous/next image.

On my 10 inch tablet, the scroll animation is uncomfortable to watch when flipping through many pix.

**Comment by tibbi** [comment]
you can already enable instant image switching by clicking on screen sides in the app settings

**Comment by rogerdahl** [comment]
True, but when using the keyboard arrow keys, you get a fast sideways scroll instead of instant switch.

**Comment by tibbi** [comment]
well people who swipe can swipe, people who want to tap can tap. Navigation works just fine with gestures, that is the priority.

**Comment by rogerdahl** [comment]
I don't think your reply really adressed either of the two points in my message...

Also, particularly with older tablets with resistive touch screens, and even cheap tablets with capacitive touch screens, a swipe can more reliably picked up than a tap.

**Comment by rogerdahl** [comment]
One reason that people might prefer to swipe instead of tap is that, depending on how you hold the phone, it could be hard to reach one side of the screen in order to tap in that direction, while swipe to either direction can be done at any point where you're touching the screen.

That's the last you'll hear from me on this -- promise :) And thank you for the app! I've purchased it and might look into how I can tweak the behavior on it a bit myself.
