### ISSUE TITLE
Allow tap to next picture further away from the edge of the screen

### ISSUE THREAD

**Issue by rogerdahl** [SimpleMobileTools/Simple-Gallery#1417]
On my tablet, I have to tap on the very edge of the screen in order for the tap to be registered when going to the next/previous image. Not sure if it's the app or the tablet, but taps on the edge of the screen are not reliably detected. I think this issue could be resolved by allowing tap to the next/previous image further away from the edge.

**Comment by tibbi** [comment]
the tap area on tablets will be doubled in 6.7.3. But be aware that other gestures used for example at zooming will not work in that area.
