### ISSUE TITLE
hierarchical folder view - feature request

### ISSUE THREAD

**Issue by ruedihofer** [SimpleMobileTools/Simple-Gallery#1418]
Hi
I really like your tool. Thank you so much for your work! Nevertheless I'd like to hand in a feature request ...

My use case: I have lots of pictures stored on my mobile, mostly from my travels. I am looking for a way to have them better organized and quicker found. 

I'm using a workflow where I process the photos on my desktop computer. Afterwards, I'll copy them to my mobile. I use a certain folder structure:
DCIM -> Travel -> 1809-France
DCIM -> Travel -> 1904-England 
...
Now when I open the gallery, I have a lot of folders on my top pane, including somewhere hidden also the Camera, Screenshots etc. It's too much and searching is too much of scrolling.

I would like to see on the top pane tidied up showing only the folder Travel / Camera / Screenshots. Then when I double-tap the folder 'Travel', it would open up and show only the underlying folders 1809-France, 1904-England ...

I think this is not feasible with the existing exclude/include/hide features, right? 

Implementing the feature could be done this way: It could be done similar to the .nomedia file, by using a file called .noflatview. I could then longpress on the folder 'Travel' and toggle an option 'flat / hierarchical'.

What you think? Any other who would like to see such a feature?

Thanks again ...

**Comment by tibbi** [comment]
you can already enable "Group direct subfolders" in Menu -> Change view type, if you have the Pro version.

**Comment by ruedihofer** [comment]
Thanks ... and yes, I have the pro version, and now I see the option. This is almost what I'm looking for, but not exactly. I would only like to have one folder in hierarchical view (My afforementioned 'Travel' folder), while all the others remain in flat view. Hence the idea with the control file within this folder ..

**Comment by tibbi** [comment]
I dont want to complicate it like that
