### ISSUE TITLE
Date/Time Appears To Be Working Off Wifi GEO?

### ISSUE THREAD

**Issue by 0pLuS0** [SimpleMobileTools/Simple-Gallery#1420]
Hello,

I was testing SimpleGallery 6.4.3 I downloaded through F-Droid, with DAVx5.

I did not use an active sim card in the phone, it was dead, and I used a VPN over my Wifi.

When I added in a Calendar event on a specific date in SimpleGallery, it appeared the following day in the Gmail calendar.

I tested this also with Etar, but it shows an option for the Timezone. Everytime I placed an event for a specific date in Etar, it always appeared correctly in Gmail.

So it appears that SImpleGallery is not using the Phone Settings - Timezone...

Hmm

```P.S. Anyway to get a hold of F-Droid to keep your client more up to date when the new versions come out? This is the worst I've seen F-Droid fall behind in putting out the latest releases...```

**Comment by tibbi** [comment]
I dont get why are you reporting a calendar issue in the gallery. Anyway timezone handling improving is on the roadmap.

**Comment by 0pLuS0** [comment]
WOW sorry can't believe I wrote this up for SimpleGallery instead of the Calendar... :(
