### ISSUE TITLE
Rotation is getting saved despite not saving

### ISSUE THREAD

**Issue by Ketrel** [SimpleMobileTools/Simple-Gallery#1422]
**Version**: 6.7.2 (latest on F-Droid at the moment)  
**Device**: Kindle Fire  
**Path to images**: /storage/emulated/0/Wallpapers  
**Steps to Reproduce**: I use either the gesture or the rotate button to rotate an image, I do NOT hit the check, the  I back out of the program.  
**Expected Results**: Nothing changes  
**Actual Results:** The rotation is saved, and the modification timestamp is updated breaking sorting by date modified.

**Comment by tibbi** [comment]
that is the expected behaviour, the saving check will actually be removed soon

**Comment by Ketrel** [comment]
Please tell me there's a way to make that NOT save.
Or please tell me which is the last version that does not save automatically so I can go back to that.

This destroyed the dates on my photos, and that's something I can never undo now.

**Comment by Ketrel** [comment]
(I just want to add that this is devastating.  I no longer have an unaltered copy of my photo.  It was one thing when I thought it was a bug, but this is far different.)

**Comment by tibbi** [comment]
it is there for quite some time now, Im not sure which version has no autosave. It might have been added in 6.5.0 with gesture rotating.

**Comment by NikhilSudhakaranVG** [comment]
I had complained this issue some months ago.got same reply from dev. It's his choice.
Being an open source app you can do whatever you want. Just make a fork of the app. That's what FOSS IS ALL ABOUT
