### ISSUE TITLE
Share picture with EXIF metadata cleared up

### ISSUE THREAD

**Issue by szpak** [SimpleMobileTools/Simple-Gallery#1428]
I don't want to share my photos' metadata while sending it via Twitter/Messanger/... Currently I use a third-party application to share a picture with that app and later on to share it with (for example) a Twitter client. After migration from the stock Gallery to Simple Gallery I though that there could be a built-in mechanism to (on demand) share a picture with EXIF metadata cleared up. The modified picture preferably should not be save on a "disk"/SD card, but temporarily kept in the persistent memory (if technically possible) to do not create unneeded extra pictures.

It's somehow an extension to #686 (as EXIF modification mechanism needs to be implemented in Simple Gallery in general).

**Comment by tibbi** [comment]
I dont want to add that, it is out of the scope of the app. Thanks
