### ISSUE TITLE
Can 'System UI' Be Disabled?

### ISSUE THREAD

**Issue by 0pLuS0** [SimpleMobileTools/Simple-Gallery#1429]
On my device, I have enabled;

```Automatically hide system UI at fullscreen media```

For me, many times the UI doesn't hide and I need to tap the screen to make it disappear.

Also when it does hide, it first appears, then disappears, it would be great if the UI never when opening images, and it only appeared when the screen was tapped.

Maybe you can make this so it won't appear until the screen is tapped, so that it never first appears, then disappears like it is doing...

Thanks

**Comment by tibbi** [comment]
should be fixed already

**Comment by 0pLuS0** [comment]
2 years later a reply... LOL

Sorry mate, I don't even use this anymore, and personally in OpenSource, which I've been using for 20 years, this is the first time a developer took 2 years to reply, but that is in Linux and Unix. I guess you Android Geeks, work like Windows and Apple.

Anyhow I've moved on in life...
