### ISSUE TITLE
QuickPic like 3 step zoom?

### ISSUE THREAD

**Issue by avamsi** [SimpleMobileTools/Simple-Gallery#1433]
Current behavior of Simple Gallery (please correct me if I'm wrong):
- "Default" view is fit to screen (vertical / horizontal, depending on the image)
- (Assuming "deep zoom" is turned on) First double tap fits to screen vertically
- Second double tap takes back to default view

This feature request:
- Same as Simple Gallery's default view
- First double tap should fit to screen vertically / horizontally depending on the image (instead of just vertically)
- Second double tap should "zoom" 100% (no matter if that means zooming-in or zooming-out from default view)
- Third double tap should take back to default view

I don't care all that much about first double tap (very few images are "taller" than my phone in terms of aspect ratio) but I very much miss the second double tap from QuickPic :|

**Comment by tibbi** [comment]
you can already enable 1:1 zooming at deep zoomable images in the app settings, in the pro version

**Comment by avamsi** [comment]
Oh, thanks!

I noticed if the image is smaller than the screen, you can't slide to the next image -- is that a known issue (or I can open one)?

**Comment by tibbi** [comment]
you can open a new one
