### ISSUE TITLE
[Request] Password Protect Specific Folders

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [SimpleMobileTools/Simple-Gallery#1435]
Would really love to have an option to password protect and hide/encrypt specific folders (Different from the "hidden folders").

To view them you would do something along the lines of: Locked files (Folders hidden from normal viewing > unlock (fingerprint/pin/swipe/pass) > shows locked files > backout (relocks files and hides them from view)

**Comment by tibbi** [comment]
duplicate of #379
