### ISSUE TITLE
rendering pngs

### ISSUE THREAD

**Issue by kilroythe5th** [SimpleMobileTools/Simple-Gallery#144]
Jpgs seem to render perfectly, but with pngs, it won't show them at even close to full resolution, and double tap just zooms in a little bit and makes the picture look all chunky

**Comment by kilroythe5th** [comment]
if it's of any help, you could probably use the rendering engine from GLImageViewer, as it handles pngs fine

**Comment by tibbi** [comment]
im using third party libraries for loading fullscreen images, but the best one doesnt display pngs in good quality. Im using another one for pngs which has worse zoom.

**Comment by KrasnayaPloshchad** [comment]
@tibbi Is it possible to report to their developers?

**Comment by tibbi** [comment]
which one? The one currently used which has bad zoom is designed that way, its made for simple zooms, which only enlarge the already rendered image. Its https://github.com/chrisbanes/PhotoView . The proper zooming one is https://github.com/davemorrissey/subsampling-scale-image-view . I should be rendering pngs as ARGB_8888 as described at https://github.com/davemorrissey/subsampling-scale-image-view/wiki/02.-Displaying-images , but I couldnt make it work. Not much to report anywhere.

**Comment by kilroythe5th** [comment]
I don't know if this is helpful, but whatever library GLImageViewer uses works great, though it's a little slow on my device
