### ISSUE TITLE
i can not sync project  i created keystore.properties and tried to sync but no luck here i am getting this error (I am new any help  will be greatly appreciated) 

### ISSUE THREAD

**Issue by mohiuddinify** [SimpleMobileTools/Simple-Gallery#1444]
Error:Cause: org.jetbrains.plugins.gradle.tooling.util.ModuleComponentIdentifierImpl.getModuleIdentifier()Lorg/gradle/api/artifacts/ModuleIdentifier;

**Comment by mohiuddinify** [comment]
I am new any help  will be greatly appreciated

**Comment by tibbi** [comment]
it is some issue on your end, Im not giving support for building clone apps.
