### ISSUE TITLE
Move/copy problem

### ISSUE THREAD

**Issue by ouafnico** [SimpleMobileTools/Simple-Gallery#145]
Hi

Using copy/move picture, when touching to choose destination, i got a blank box which is not showing dest folders. I add to click to other folders.

Version used is 2.3.3.

**Comment by ouafnico** [comment]
![screenshot_20170120-171451](https://cloud.githubusercontent.com/assets/807350/22156537/0703da10-df34-11e6-9eae-b30085b5eb8e.png)

**Comment by tibbi** [comment]
this should be fixed already, maybe it was related to slow folder loading in general
