### ISSUE TITLE
Shortcuts open wrong folder

### ISSUE THREAD

**Issue by dajusc** [SimpleMobileTools/Simple-Gallery#1450]
First of all: Thx for the great app! :)

I noticed a problem related to shortcuts:
1. Create shortcuts for two folder "A" and "B"
2. Click shortcut "A"  --> Gallery opens folder "A" as expected
3. Press Home-Button
4. Click shortcut "B"  --> Galery opens folder "A" again, but not "B"!

Here some infos about my setup:
* Google Pixel 2, default Android 9 with latest updates
* Simple Gallery Pro from Play Store
* Nova Launcher

**Comment by tibbi** [comment]
"A" stays open, since the home button only pauses the app, doesnt close it

**Comment by dajusc** [comment]
The problem still persists on my phone. :(
I have version 6.9.2 from the Google Play Store.
