### ISSUE TITLE
Simple Gallery icon disappears on Android Q

### ISSUE THREAD

**Issue by bungabunga** [SimpleMobileTools/Simple-Gallery#1459]
Simple Gallery app regularly disappears from the launcher on Android Q beta 4. I bring it back and after some time it disappears again. The icon is not orange, I made it blue. On Android 9 there was no such issue.

launcher: Rootless Pixel Launcher based
device: Pixel 3
system: Android Q beta 4
app version: v6.7.7.

**Comment by tibbi** [comment]
some launchers do not support icon customization, nothing I can do about it. Either use a different launcher, or stick to the default orange color

**Comment by bungabunga** [comment]
but it worked perfectly in Android 9?

**Comment by tibbi** [comment]
well that just proves that it isnt an issue on my side

**Comment by x-jokay** [comment]
Can confirm this for the [Lawnchair](https://lawnchair.app/) launcher as well 🙄
