### ISSUE TITLE
Would it be possible to use formatted strings in the FAQ translations?

### ISSUE THREAD

**Issue by hugomg** [SimpleMobileTools/Simple-Gallery#1477]
Many of the FAQ entries directly mention app settings or menu options directly by their names. For example:

```xml
<string name="faq_11_text">Sure, just use the \"Group by\" menu item 
while at the thumbnails view. You can group files by multiple criteria, including
Date Taken. If you use the \"Show all  folders content\" function you can group
them by folders too.</string>
```

The problem is that whoever is translating this FAQ entry must be careful to ensure that these button names are the same ones being used in the "group_by" and "show_all" keys.

Would it be possible to make Simple Gallery automatically take care of this, perhaps by modifying the faq_11_text entry to be a format string with placeholders like ` %1$s` and ` %2$s` ?

Would it be possible to change these so that instead of repeating the name oof the buttons, this

**Comment by tibbi** [comment]
no, I dont want to add it like that and it would also make it a lot more complicated
