### ISSUE TITLE
Gestures/zooming got really weird with the last update

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1479]
See:
![ScreenRecord-2019-06-22-23-27-50](https://user-images.githubusercontent.com/29208110/59970839-3884fe00-9546-11e9-9294-1cbb8df18cd1.gif)

**Comment by tibbi** [comment]
what app version do you have?

**Comment by floppyD** [comment]
6.8.0 - Play Store

**Comment by tibbi** [comment]
it is there for quite a while now, hasnt been added in the latest version

**Comment by floppyD** [comment]
Duplicate of #1278
