### ISSUE TITLE
the cold start is too slow

### ISSUE THREAD

**Issue by europa** [SimpleMobileTools/Simple-Gallery#1484]
The cold start(launch the app the first time) is too slow,and the page is empty  for several seconds
![cold_start](https://user-images.githubusercontent.com/1930161/60088652-99444e80-9771-11e9-9856-9dee3acb30fa.png). Suggest a loading view when loading the gallery.
.

**Comment by tibbi** [comment]
that is the files screen, not launching the app for the first time. I guess you enabled "Show all folders content" already?

**Comment by europa** [comment]
> that is the files screen, not launching the app for the first time. I guess you enabled "Show all folders content" already?

sorry，the screen is wrong .The first install start is slow , the later is fast.But the file page is always slow.

**Comment by thirtyfiveo** [comment]
Same problem with enabled "Show all folders content" here @ Nokia 7 Plus 
Some pictures are on sd card (SanDisk Extreme Pro 64 GB) and some on the internal storage.

**Comment by tibbi** [comment]
reopen if it still happens with version 6.23.0 and Android 11+
