### ISSUE TITLE
App crashes after saving filtered images

### ISSUE THREAD

**Issue by maszek** [SimpleMobileTools/Simple-Gallery#1500]
Hello Tibor,

I've been using the Simple Gallery since a couple of years now.

Since a while, it has the tendency to crash when I try to save an image after applying a filter to it. I try saving under a modified name. I can prevent this behaviour for one time by stopping the app in android settings, then, after one successful attempt, the crashes reoccur.
The error notification reads: "app has crashed, start again"
I use Android 7.0, app version 6.7.7. I have the photos stored on a micro SD-card (with 70Gb free storage).
Remarkably, the crashes do not occur when I _crop_ an image and save under a different name.
Perhaps you might look into this.

**Comment by tibbi** [comment]
Hey, first of all try updating to the latest app version. Are you saving it on an SD card, or internal storage?

**Comment by maszek** [comment]
I've updated to the latest version 6.8.2. (F-droid does not always notify me of available updates).
The app responds erratically. 
- Most common notification is: "Gallery has stopped. Reload app" (which it does, even if I don't tap the notification. After reload, the same photo is shown as before crash)

- Sometimes the filter modifications will store successfully. I cannot put my finger on it. It's a gamble.

 

Like I wrote in my post, I store my photos on an SD-card.



 

 

Van: Github <notifications@github.com>
Beantwoorden - Aan: SimpleMobileTools/Simple-Gallery <reply@reply.github.com>
Datum: zondag 14 juli 2019 om 21:14
Aan: SimpleMobileTools/Simple-Gallery <Simple-Gallery@noreply.github.com>
CC: Regular Rocker <jan@regularrocker.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [SimpleMobileTools/Simple-Gallery] App crashes after saving filtered images (#1500)

 

Hey, first of all try updating to the latest app version. Are you saving it on an SD card, or internal storage?

**Comment by tibbi** [comment]
Maybe it is running out of memory, filters arent really optimized properly yet. Can you reproduce the issue with some smaller images too, or just bigger photos?

**Comment by JohnVeness** [comment]
This issue occurs for me with v6.9.6, images on SD card. Saving after cropping works fine, but not saving after applying a filter. It worked OK with small image, not normal size one

**Comment by tibbi** [comment]
the editor has been fully rewritten in 6.11.0 so this is no longer valid
