### ISSUE TITLE
Visibility problem in Settings

### ISSUE THREAD

**Issue by proideo** [SimpleMobileTools/Simple-Gallery#1506]
I have black as the primary color and almost black as the background color and in the Settings it is difficult to see some elements such as the titles of each section and the switches of enabled options.
![Gallery](https://user-images.githubusercontent.com/50172751/61301304-8c000a00-a7db-11e9-9d98-c4130b40e441.png)
I think it would be better not to use the primary color in settings and use some opposite color to the background color for those elements.

**Comment by tibbi** [comment]
there is a special Black and White theme for that. Of course if you select 2 dark colors they wont be visible on each other, it is impossible to fix that.
