### ISSUE TITLE
[BUG]Directory's recyclerview becomes empty, and search is only available several seconds after launch

### ISSUE THREAD

**Issue by KnIfER** [SimpleMobileTools/Simple-Gallery#1509]
it becomes empty when you lauch the app and soon click or dismiss the searchview.

 It's because that when the search actionview expands or collapses, a `setupAdapter(mDirs, "")` call will follow, but **mDirs** is still empty.  
And that's further because mDirs is assigned only in  the method `gotDirectories`, which is a very slow process.

My solution:  
Don't `mDirs = dirs.clone()` after everything's finished, instead, assign mDirs = dirs quickly in the  `gotDirectories` method. will there be any drawbacks?

**Comment by tibbi** [comment]
what app version do you have?

**Comment by KnIfER** [comment]
v6.8.3 android8

**Comment by tibbi** [comment]
reopen if it still happens with 6.23.0
