### ISSUE TITLE
Opening attachments of K9 mail doesnt work

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#151]

**Comment by tibbi** [comment]
retry with 2.3.5

**Comment by reverendhomer** [comment]
Actually, if it's true that opening attachments works in 2.3.3 and doesn't in 2.3.4, I can try to bisect this in a few days

**Comment by tibbi** [comment]
i could reproduce it not working in 2.3.4 so it should be fixed in 2.3.5. I always attach .apk files to releases at https://github.com/SimpleMobileTools/Simple-Gallery/releases , so you can check 2.3.5 if you want. It was published yesterday, might take 1-2 days before appearing on f-droid.

**Comment by reverendhomer** [comment]
Oh, I can confirm! This issue is fixed in 2.3.5. And also this release fixed #107 issue, so I'm going to close it. Thank you :)

**Comment by tibbi** [comment]
ok ill close it quick while it works
