### ISSUE TITLE
split off (image) Editor from Gallery

### ISSUE THREAD

**Issue by ronso0** [SimpleMobileTools/Simple-Gallery#1513]
I use the stock android gallery (Album) and I'm actually happy with it, especially the homescreen widget Photos & Videos has a nice UX.
I tried Simple-Gallery because I was looking for a image editor that allows to specify the filenames used to save edited images. I this regard your editor is superior to the Album editor, though, for various reasons, I don't use SimpleGallery itself.

Splitting off the Editor into a separate app would be nice.

**Comment by tibbi** [comment]
I dont plan doing that, the gallery is already small enough. You dont have to use the rest of the app if you dont want.

**Comment by ronso0** [comment]
yes, I know.
just thought splitting off the Editor might highlight it, because right now it's an add-on data not advertised explicitely
