### ISSUE TITLE
make homescreen show the last viewed image

### ISSUE THREAD

**Issue by ronso0** [SimpleMobileTools/Simple-Gallery#1514]
the homescreen widget could be improved if it would show the last viewed image.

Right now, (on my device) it always shows last screenshot I took. This is inconsistent with how the image grid can be set up (All folders view)

**Comment by tibbi** [comment]
it uses the thumbnail depending on the specific folder sorting, might not be always refreshed properly. Showing the last viewed image doesn't make that much sense. You can add a file shortcut if you want specific images.
