### ISSUE TITLE
Fullscreen images not loading, random over time

### ISSUE THREAD

**Issue by Chicken-Bones** [SimpleMobileTools/Simple-Gallery#152]
In a folder with ~100 1-3MB jpgs, opening one in fullscreen and paging through works normally, until after ~10 images one of them will fail to load. Going back to the folder view, and selecting the same image will still fail to load. Continuing to swipe will load the next images, until the issue appears again.

I suspect it's related to memory limits and the cache. I can tell you have a recently loaded cache, because going back through loads the images immediately, until you get to a certain point where they start reloading. Paging back till the cache is reset and then selecting the image I want from the folder view sometimes works, sometimes doesn't. Restarting the app normally works, but then a different image will fail to load.

My guess might be that the image is failing to load due to memory constraints, soon after which the system gets a request to free some memory, and you release the oldest images from the cache and successive images continue loading, but the image that failed to load is stored with a null entry. 

Version: 2.3.5
Phone: Galaxy S3 (GT-I9300)
API Level: 4.3 (18)

**Comment by alugarius** [comment]
Same error
Same error

Annoying as hell, might be a Samsung S3 bug

**Comment by tibbi** [comment]
is it better with the latest version 2.8.6? There have been many improvements lately related to that.

**Comment by alugarius** [comment]
i have a Wiko phone now, is fine here

**Comment by Chicken-Bones** [comment]
Unfortunately I no longer have the test device, might be safe to assume closed for now, until someone else reports it
