### ISSUE TITLE
[Bug]will scans in wrong folder as media

### ISSUE THREAD

**Issue by KnIfER** [SimpleMobileTools/Simple-Gallery#1520]
this app will scans in folders with extension  like '/sdcard/123.mp4/' as media.
version: 6.8.3

**Comment by KnIfER** [comment]
by the way @tibbi I think there're some mistakes in the `getSelectionQuery` method of mediaFetcher.kt
It will generate a string when app starts
the string is: `_data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? OR _data LIKE ? `
what are they used for?

**Comment by KnIfER** [comment]
by the way `mediaFetcher.getFoldersToScan()` is returning 0 on my samsung s7 android 8 device.

**Comment by tibbi** [comment]
not sure what you mean. A file is shown as a folder?

**Comment by KnIfER** [comment]
i mean a folder has a certain name （*.mp4）will be treated as a file，and it will apear in the gallery，un-deletable.

**Comment by tibbi** [comment]
it will be fixed in 6.8.4, but only if you pick "Avoid showing invalid files" at the File loading priority at the app settings. I dont want to always check for this case, it could slow down the app.
