### ISSUE TITLE
The background color changes in CustomizationActivity after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Gallery#1526]
When I change the orientation of the device screen, the color of the background changes
![2019-07-25 00-45-14_before](https://user-images.githubusercontent.com/53469180/62214476-6fe89500-b3a5-11e9-962f-c5159fde5e27.png)
![2019-07-25 00-45-14_after](https://user-images.githubusercontent.com/53469180/62214477-6fe89500-b3a5-11e9-9624-f407678278e6.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
