### ISSUE TITLE
ExcludedFoldersActivity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Gallery#1527]
When I change the orientation of the device screen, ExcludedFoldersActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The last two elements lose their icones
![2019-07-25 04-58-24_before](https://user-images.githubusercontent.com/53469180/62214576-a2928d80-b3a5-11e9-9c41-e8edd5e9a02a.png)
![2019-07-25 04-58-24_after](https://user-images.githubusercontent.com/53469180/62214578-a2928d80-b3a5-11e9-9599-915153975924.png)

-- second case --
It loses the selected objects
![2019-07-24 21-54-42_before](https://user-images.githubusercontent.com/53469180/62214580-a2928d80-b3a5-11e9-9017-766c008ca7e8.png)
![2019-07-24 21-54-42_after](https://user-images.githubusercontent.com/53469180/62214581-a32b2400-b3a5-11e9-9a5e-143105653c5a.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues

**Comment by dlicse** [comment]
Thank you for your answer, could you give me more detail? More precisely, don't you consider them issues because you don't have in mind to fix them or because you don't recognize them as failures?

**Comment by tibbi** [comment]
I dont intend fixing them, it isnt worth it

**Comment by dlicse** [comment]
Don't you think it is frustrating for a user to reinsert the data they've just entered after a device configuration change? Thanks for your collaboration.

**Comment by tibbi** [comment]
no, people dont their devices during inserting anything, so far not a single person reported anything like that
