### ISSUE TITLE
HiddenFoldersActivity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Gallery#1528]
When I change the orientation of the device screen, HiddenFoldersActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
It loses the selected objects
![2019-07-25 05-21-28_before](https://user-images.githubusercontent.com/53469180/62214747-f8ffcc00-b3a5-11e9-9c27-d32432ea0884.png)
![2019-07-25 05-21-28_after](https://user-images.githubusercontent.com/53469180/62214748-f9986280-b3a5-11e9-9a6c-c0af696f6a2c.png)

-- second case --
The last two elements lose their icons
![2019-07-24 20-33-13_before](https://user-images.githubusercontent.com/53469180/62214751-f9986280-b3a5-11e9-8d12-cbb8d9b7dd30.png)
![2019-07-24 20-33-13_after](https://user-images.githubusercontent.com/53469180/62214752-f9986280-b3a5-11e9-863e-23edf2601eb9.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
