### ISSUE TITLE
IncludedFoldersActivity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Gallery#1529]
When I change the orientation of the device screen, IncludedFoldersActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The text in the first screenshot is replaced by another text
![2019-07-25 04-02-01_before](https://user-images.githubusercontent.com/53469180/62214973-5bf16300-b3a6-11e9-9760-bb5a0208f992.png)
![2019-07-25 04-02-01_after](https://user-images.githubusercontent.com/53469180/62214975-5c89f980-b3a6-11e9-8f0a-727d10f53c80.png)

-- second case --
The two elements lose their icones
![2019-07-24 21-20-18_before](https://user-images.githubusercontent.com/53469180/62214977-5c89f980-b3a6-11e9-863a-7cbc5b1e54ea.png)
![2019-07-24 21-20-18_after](https://user-images.githubusercontent.com/53469180/62214979-5c89f980-b3a6-11e9-88ed-dc0c0dbcf832.png)

-- third case --
It loses the selected object
![2019-07-24 20-37-22_before](https://user-images.githubusercontent.com/53469180/62214983-5d229000-b3a6-11e9-845f-41cb91dd9ee0.png)
![2019-07-24 20-37-22_after](https://user-images.githubusercontent.com/53469180/62214984-5d229000-b3a6-11e9-93d4-a2070b2ed184.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
