### ISSUE TITLE
MainActivity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Gallery#1530]
When I change the orientation of the device screen, MainActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The background color changes
![2019-07-24 22-15-35_before](https://user-images.githubusercontent.com/53469180/62215363-1b461980-b3a7-11e9-9451-5a0616a84f45.png)
![2019-07-24 22-15-35_after](https://user-images.githubusercontent.com/53469180/62215365-1b461980-b3a7-11e9-936a-6f145561088d.png)

-- second case --
A TextView appears
![2019-07-24 21-49-02_before](https://user-images.githubusercontent.com/53469180/62215366-1b461980-b3a7-11e9-964c-bc29b7e30eba.png)
![2019-07-24 21-49-02_after](https://user-images.githubusercontent.com/53469180/62215367-1bdeb000-b3a7-11e9-8843-1a11a7c7a2b6.png)

-- third case --
The last two elements lose their icons
![2019-07-24 18-25-21_before](https://user-images.githubusercontent.com/53469180/62215370-1bdeb000-b3a7-11e9-9b6a-b4f158df37e0.png)
![2019-07-24 18-25-21_after](https://user-images.githubusercontent.com/53469180/62215371-1c774680-b3a7-11e9-8d0f-f84c7c4a554e.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
