### ISSUE TITLE
MediaActivity changes its state after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Gallery#1531]
When I change the orientation of the device screen, MediaActivity changes its state. Below there are different examples: the screenshots were taken before and after the screen orientation change and they are paired (before, after), (before, after) ...

-- first case --
The first element of the menu disappears
![2019-07-24 20-03-59_before](https://user-images.githubusercontent.com/53469180/62215589-868feb80-b3a7-11e9-9236-351cf2bd72ea.png)
![2019-07-24 20-03-59_after](https://user-images.githubusercontent.com/53469180/62215592-87288200-b3a7-11e9-8910-c7fc65d77d42.png)

-- second case --
The text written inside the search bar disappears
![2019-07-24 18-52-52_before](https://user-images.githubusercontent.com/53469180/62215593-87288200-b3a7-11e9-88e0-0b2861a9628f.png)
![2019-07-24 18-52-52_after](https://user-images.githubusercontent.com/53469180/62215594-87288200-b3a7-11e9-9b82-bbce5980dc4b.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
