### ISSUE TITLE
SettingsActivity doesn't keep the scroll position after a screen orientation change

### ISSUE THREAD

**Issue by dlicse** [SimpleMobileTools/Simple-Gallery#1532]
When I change the orientation of the device screen, SettingsActivity doesn't keep the scroll position
![2019-07-24 19-15-45_before](https://user-images.githubusercontent.com/53469180/62215775-d8387600-b3a7-11e9-97a0-f7dd9c86bfc4.png)
![2019-07-24 19-15-45_after](https://user-images.githubusercontent.com/53469180/62215776-d8387600-b3a7-11e9-96ba-2041a46ceb50.png)

**Comment by tibbi** [comment]
nothing to fix there, those are not issues
