### ISSUE TITLE
Play Store naming

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1539]
Both the regular version and the Pro version are called "Simple Gallery Pro" on Play Store. I had to use the browser to show both on the same page, but it's the same thing on the app.
![Screenshot_20190805-170339](https://user-images.githubusercontent.com/29208110/62491777-419ef700-b7a3-11e9-8456-fdf3b6dd2779.png)

**Comment by tibbi** [comment]
you mean in Portuguese? It should be fixed already. Thanks
