### ISSUE TITLE
There is no simple way to prevent scanning of subfolder branches

### ISSUE THREAD

**Issue by Coronarius** [SimpleMobileTools/Simple-Gallery#1540]
It looks like Simple Gallery is broken by design, because there is no easy way to prevent scanning, indexing and caching of subfolder branches. 

_.nomedia_ files are not working for subfolders, that's a crazy behavior. But also excluding folders doesn't help. In _Prefs.xml_ is a list of _excluded_folders_ that doesn't seem to work for subfolders.

I've hundreds of thousand of images in nearly 40000 subfolders on SD card and mounted devices e.g. lots of album art files, source code graphics, scientific stuff, ...
The only way I see is to either put each directory path in the list of excluded folders or even worse put a .nomedia file in each subfolder - but the latter will interfere with other apps.

Please tell me that I'm wrong and there is a simple way to exclude a complete branch of subfolders from scanning and indexing. 

The only images I want to see in gallery are my hundred photos from camera.

**Comment by tibbi** [comment]
well ye, excluding and .nomedia currently doesnt stop from scanning, only from showing. Improving it is surely on the roadmap and Ill work on it soon, it just isnt that easy.

**Comment by tibbi** [comment]
actually it seems to work fine already, only the proper folders are scanned. What app version are you using?

**Comment by SebiderSushi** [comment]
Today i noticed that including a folder will, for all its subfolders, switch the behavior of .nomedia files and the exclude folders feature from recusive to shallow.

I.E.:
Exclude or put a .nomedia file in `/foo/bar`. Contents of `/foo/bar`, `/foo/bar/foo` and `/foo/bar/bar` will disappear.
Then, Include the folder `/foo`. Everything except files directly located in `/foo/bar` should reappear.

Related to #1027

**Comment by tibbi** [comment]
this is a separate issue about rescanning, not hiding. Anyway it seems to work fine.
