### ISSUE TITLE
[Request]  Option To Autoplay Videos Muted

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [SimpleMobileTools/Simple-Gallery#1542]
I see the option to autoplay videos, but can we have the ability to autoplay them started muted?

**Comment by tibbi** [comment]
I dont want to add such in the app, audio is handled by your device. Just mute the Media stream.

**Comment by grravity** [comment]
Stupid question, but where is the option to mute the stream?

**Comment by tibbi** [comment]
in the devices audio settings

**Comment by grravity** [comment]
Oh, so there's no way to mute individual streams? Was looking for it yesterday, otherwise the videos play over the audio you have in the background.

**Comment by tibbi** [comment]
you cannot customize it that much

**Comment by grravity** [comment]
Is there anyway we can get the ability to mute videos individually? Like a simple mute button next to the seekbar. I figured that was a basic thing I was confused when I couldn't find it

**Comment by tibbi** [comment]
not really

**Comment by grravity** [comment]
It kinda sucks not to be able to just mute a video..
