### ISSUE TITLE
Simple Gallery Pro - Video > Edit Icon returns "No valid app found"

### ISSUE THREAD

**Issue by curiousrom** [SimpleMobileTools/Simple-Gallery#1543]
With the most recent @ the present Simple Gallery Pro 6.9.1 (260) updated via the [F-Droid](https://f-droid.org/en/packages/com.simplemobiletools.gallery.pro/) app when tapping a video thumbnail to bring it to the foreground & then tap on the Edit pencil icon I get the "No valid app found" popup error.

I got the same error on the previous Simple Gallery Pro 6.8.4 installed via F-Droid.

But when I do the same for a photo I get a popup with choices: Edit with Simple's Editor, Simple's Draw & my other apps capable of editing.

I do not have any editor app set as default on my Galaxy S5 G900M LineageOS 16.0 klte build 2019-08-04 + Open GApps Pico + LineageOS AddonSU, no custom kernel or system mods of any kind.

I rebooted, reproduced the video edit error, captured a logcat with [Syslog](https://play.google.com/store/apps/details?id=com.tortel.syslog) and attached it to this post.

One of the lines in the logcat:

08-08 15:12:20.630 I/ActivityManager(  560): START u0 {act=android.intent.action.VIEW dat=content://com.simplemobiletools.gallery.pro.provider/external_files/storage/49D1-0CE4/Android/data/org.lineageos.snap/files/VID_20190803_171212.mp4 typ=video/mp4 flg=0x1 cmp=com.simplemobiletools.gallery.pro/.activities.VideoActivity (has extras)} from uid 10235

[2019-08-08_15.13-Simple_Gallery_6.9.1_Video_Edit_Error.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/3483793/2019-08-08_15.13-Simple_Gallery_6.9.1_Video_Edit_Error.zip)

**Comment by tibbi** [comment]
Simple Gallery does not contain a video editor in itself, you need to get some other one

**Comment by curiousrom** [comment]
> Simple Gallery does not contain a video editor in itself, you need to get some other one

Thanks for the quick reply. I did not see that info in Simple Gallery Pro > 3-dots > About > FAQ.

I will install a video editing app & see if Simple Gallery Pro offers a choice when tapping on the Edit pencil icon.

Any video editing app recommendation?

BTW why is FAQ under About instead of simply Simple Gallery Pro > 3-dots?

**Comment by curiousrom** [comment]
@tibbi I installed [Crop & Trim Video](https://play.google.com/store/apps/details?id=fnzstudios.com.videocrop) and [Adobe Premiere Clip](https://play.google.com/store/apps/details?id=com.adobe.premiereclip), rebboted & still get the "No valid app found" error.

Any suggestions? Should I open a new issue?

**Comment by tibbi** [comment]
you can open a new one. FAQ isnt that important that it should be at the main screen

**Comment by curiousrom** [comment]
I found an app that will open with the Edit (pencil) icon: [YouCut - Video Editor & Video Maker, No Watermark by InShot](https://play.google.com/store/apps/details?id=com.camerasideas.trimmer)

Others may work via Share or Open with but YMMV.

**Comment by puppykickr** [comment]
@curiousrom

Thank you for this!

I have used InShot apps before and found them to be very functional.

YouCut is another great app by these folks.
