### ISSUE TITLE
Sort by date broken in favorites

### ISSUE THREAD

**Issue by Instagit** [SimpleMobileTools/Simple-Gallery#1545]
I saw that there have been problems with this in the past, but you fixed them. Sorting by date taken generally works, but not for the favorites. They are sorted by modification date instead. I think this was broken by a recent update, because I'm pretty sure it worked correctly until recently.

**Comment by Instagit** [comment]
Do I have to do something for this to work? Right now, it seems unchanged.

**Comment by Instagit** [comment]
It works now after "fix date taken", but when opening a directory with such pictures, they visibly jump around after loading. Is there a way to properly re-import the pictures to avoid this?

**Comment by tibbi** [comment]
does it always jump around? Not just for the first time?

**Comment by Instagit** [comment]
Yes, happens every time I open a directory with date fixed images.

**Comment by tibbi** [comment]
try finding the app in your device settings and do a "Clear data" (or "Clear storage") on it. It will just reset some settings and clear the recycle bin/favorites, wont delete any files.

**Comment by Instagit** [comment]
After clearing the app cache and data, "fix date taken" doesn't work anymore (images stay in the wrong order, even after force kill and restart) and of course all my settings and hundreds of favorites are gone. :sweat:

**Comment by tibbi** [comment]
well I wrote previously that it will be cleared. If you check an individual files Properties, does it show the proper Date Taken?

**Comment by Instagit** [comment]
I had to configure the sort order again, of course that got lost too. It seems to work now.

> well I wrote previously that it will be cleared

Yeah, but knowing what will happen doesn't make it better :) At least the problem is fixed. Thanks.

**Comment by tibbi** [comment]
alright thanks, sorry for the issues.

**Comment by Instagit** [comment]
Don't worry, thanks for the great software. :)

**Comment by Instagit** [comment]
> It works now after "fix date taken", but when opening a directory with such pictures, they visibly jump around after loading. Is there a way to properly re-import the pictures to avoid this?

After clearing everything, I just hid and excluded some directories and started adding favorites again and now the jumping is back. It happens on every directory where I have favorites set.

**Comment by tibbi** [comment]
okay then, Ill take a look at it soon
