### ISSUE TITLE
[Feature Request] Separate titles/switches color from primary color

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1546]
So you can use a dark background and still see them. Also would avoid having to hard-code some colors for the Black&White theme.
![Screenshot_20190812-141034](https://user-images.githubusercontent.com/29208110/62884786-bfb44e00-bd0d-11e9-97b6-69d02c01cf30.png)

**Comment by tibbi** [comment]
there is special handling for the B/W theme. But if oyu select dark colors, of course they cannot be seen on top of each other. I dont really plan adding any new solutions related to selecting too many dark colors.

**Comment by floppyD** [comment]
I really think you should use a secondary color for elements like switches and some texts. It's really makes the app much more customizable. I would suggest to make the color wheel available for every color option too, but it's up to you.
![Screenshot_20190812-170815](https://user-images.githubusercontent.com/29208110/62895145-a074eb00-bd24-11e9-9063-746d9b2fadd4.png)
