### ISSUE TITLE
UI element seems to be a bit off

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1549]
Or is this intended?
![Screenshot_20190812-222545](https://user-images.githubusercontent.com/29208110/62908831-615c8f00-bd50-11e9-9cba-2ca34718f077.png)

**Comment by floppyD** [comment]
Just to be more specific, I'm talking about the orange line under the top bar.

**Comment by tibbi** [comment]
that is a system line, not added by me
