### ISSUE TITLE
[Feature Request] Add little gif icons to differentiate them from regular images

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1550]
Just like you do for videos. Something like this would look great:
![Screenshot_20190813-005700](https://user-images.githubusercontent.com/29208110/62914209-adfe9500-bd65-11e9-92bf-7ac766017ab9.png)

**Comment by puppykickr** [comment]
You can set it up so that the gif thumbnails  are in motion.

Isn't that even better?

**Comment by floppyD** [comment]
Kinda, but this would be nice if you don't want to see a bunch of moving things while scrolling and yet want to know which files are gifs.

**Comment by tibbi** [comment]
closing it as a child of #1559, as I want to mark other items too, not just gifs
