### ISSUE TITLE
Play/pause button is still clickable even after hiding the UI

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1555]
![ScreenRecord-2019-08-19-13-58-59](https://user-images.githubusercontent.com/29208110/63284566-3a3f1980-c28a-11e9-8629-a26c07ee6249.gif)

**Comment by tibbi** [comment]
that is the intended behaviour for now

**Comment by floppyD** [comment]
oh, okay
