### ISSUE TITLE
Sort by date taken is glitchy

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1556]
I already tried selecting all files and using the "Fix Date Taken Value" option but nothing changes.
![ScreenRecord-2019-08-19-14-16-07](https://user-images.githubusercontent.com/29208110/63285518-475d0800-c28c-11e9-8e0e-bb9d8382dfd3.gif)

**Comment by tibbi** [comment]
1. what app version are you using? 2. if you try using the "Fix Date Taken values", do you get a success, or an error message? I could try sending you a test version with some messages appearing, can you try it out? You will have to reinstall the app.

**Comment by floppyD** [comment]
1. I'm using 6.9.2 - Play Store. 
2. I get a toast message with "Fixing...", and nothing else. Actually, every time I enter the album it gets kinda randomized and then sorts itself a second later, just like in the gif. If I close the app and open it again, the order is fixed but the album image is not, and sometimes it glitches and do the refresh thing again, but it's not often.
3. Sure I can try.

**Comment by tibbi** [comment]
write me at hello@simplemobiletools.com please, it is easier to send attachments and communicate there

**Comment by tibbi** [comment]
I have one more thing to try, shoot me a message if you want to test it :)

**Comment by tibbi** [comment]
"Fix Date Taken values" should work more reliably in 6.12.0 released soon
