### ISSUE TITLE
Can't open from Firefox

### ISSUE THREAD

**Issue by ObserverOfTime** [SimpleMobileTools/Simple-Gallery#1558]
Firefox/Fennec has the ability to open links in another app. However, when I try to open an image, I can only see the stock Gallery app and Google Photos.

**Android:** `8.0.0 (Honor 8 Lite)`
**Gallery:** `6.9.2 (F-Droid)`
**Firefox:** `68.0 (F-Droid)`

**Comment by tibbi** [comment]
what links you mean? Why would a gallery, especially an offline one, open a link?

**Comment by ObserverOfTime** [comment]
Any image link. Rather than having to download and then open it, Firefox lets you open it directly in any app that can handle it. Simple Gallery should be able to handle it but it doesn't appear in the list.

**Comment by tibbi** [comment]
aha no, it cannot handle it. The app has no internet access.

**Comment by ObserverOfTime** [comment]
Right, that makes sense.
