### ISSUE TITLE
porting app to desktop

### ISSUE THREAD

**Issue by gitlerat** [SimpleMobileTools/Simple-Gallery#1562]
Hi, i like your app very very well - however i like to use it ony my linux machine. The style of images/gifs/videos mixed and the autoplay style of the files is the only tool I can find in the whole web.
So i am newbie when its coming to this. Is this even possible with the architecture of the code basis of the app? When its possible can someone give me a wink to the right direction? :)
kind greetings

**Comment by tibbi** [comment]
not sure how would that be possible, but I dont plan supporting any desktop app versions
