### ISSUE TITLE
Image editor: add zoom capability

### ISSUE THREAD

**Issue by maulwuff** [SimpleMobileTools/Simple-Gallery#1563]
When editing an image in gallery pro, to paint on the image, it is currently not possible to zoom into the image for more accurate painting.
Please add the possibility to zoom into the image.

**Comment by tibbi** [comment]
the editor has been fully rewritten in version 6.11.0, this is already added there

**Comment by adatum** [comment]
How does zooming work when editing images? I am using v6.19.6 from F-Droid, and can't zoom using the finger pinch method.

**Comment by tibbi** [comment]
the f-droid version has the old basic editor, the app from Google Play has the advanced one.
