### ISSUE TITLE
Last update broke doube tap to zoom

### ISSUE THREAD

**Issue by nikkopt** [SimpleMobileTools/Simple-Gallery#1564]
If "Allow deep zooming images" and "allow 1:1 zooming in with two doube taps" is enabled, if you double tap the image several times so it zooms out to its normal size, it will zoom out to a very tiny image instead of filling the screen like it did in previous versions. It doesn't happen with every image. It's mainly small images in portrait mode.
You can see what i mean in here: https://m.imgur.com/a/4AjhVNJ

And here is a sample pic that i know it triggers the bug: https://imgur.com/a/olV7Mti

**Comment by nikkopt** [comment]
Forget about it. I think i'm confused and this is it's normal behaviour. I just don't think it used to be like this and i'm also not sure why it's not like that for all small pictures

**Comment by tibbi** [comment]
what app version do you have? What resolution is that image? Try it with some bigger casual jpg.

**Comment by nikkopt** [comment]
App version 6.9.4

I tried several different pictures. Big images don't behave like that (images taken with the camera for example), only small ones and not all. For example, that image i showed in the video is 236 x 315. But i also tried 400x400 and 500x500 and they don't behave like that, they don't get super small when i double tap them. Then i tried a 736 x 1209 image and it behaves like the one in the video too.. strange that some do and some don't. My screen is full HD, by the way.

**Comment by tibbi** [comment]
If the image is smaller than the actual display, of course 1:1 causes a zooming out. Nothing to be changed here.

**Comment by nikkopt** [comment]
I know it sound obvious that it should do that but:

1- Why is it only doing it now? It didn't in the past
2- Why does it not zoom out a 500x500 image? It's smaller than the screen. It only zooms out specific small images, not all of them
3-Why is this even a feature? I can't think of a single good reason to why this would be useful apart from showing the picture to an ant (and by this i mean, zooming out a small image). If it's useful then why can't i zoom it out with 2 fingeres?

**Comment by tibbi** [comment]
maybe it was broken previously, it seems to work just fine now. Anyway, it is disabled by default, you had to enable it manually. If you dont want to use it, just disable it. It is useful to many people for seeing the real photo size.

**Comment by nikkopt** [comment]
It's not working fine. Like i said, it doesn't zoom out all small pictures, just some. Anyway, thanks.
