### ISSUE TITLE
Add OpenStreetMap to show photo locations

### ISSUE THREAD

**Issue by BuZZ-dEE** [SimpleMobileTools/Simple-Gallery#1569]
Add OpenStreetMap to show photo locations

**Comment by tibbi** [comment]
Im invoking the casual location intent, your system decides which app gets open

**Comment by BuZZ-dEE** [comment]
You do that for one photo or what do you mean? As I can see, this is only possible for one photo. I mean, it would be great all locations of all photos in one map.

**Comment by tibbi** [comment]
ye, one photo only. I dont plan integrating any map directly
