### ISSUE TITLE
Image viewer : Top gradient always stay visible (ChromeOS)

### ISSUE THREAD

**Issue by Alain-DEPUILLE-WDFR** [SimpleMobileTools/Simple-Gallery#1576]
This only occurs on my Chromebook (emulated android version 7.1.1), I use Simple Gallery on many other android devices without any problem.

The background gradient that shows when the top buttons are visible always stay there, even when the buttons are hidden.

A video is worth a thousand words : https://drive.google.com/file/d/1E9aENzOkoWLjmTj9EjzyjPc3Oi4Y1cs5/view

**Comment by tibbi** [comment]
how about the bottom actions? I couldnt see them there. Do you have the "Show some action buttons at the bottom of the screen" enabled in the app settings? What app version are you using?

**Comment by Alain-DEPUILLE-WDFR** [comment]
I'm using v6.9.4 from F-Droid

If I enable "Show some action buttons at the bottom of the screen", they never disappear, unlike on my smartphone. In fact you can see the only thing that disappear is the text at the top, for the bottom bar the gradient and the tools always stay displayed.

Video : https://drive.google.com/file/d/1k8fTZmBgpboK8mvOWQSD7scXtdG9Sg35/view
