### ISSUE TITLE
folder label name not showing completely for large font 

### ISSUE THREAD

**Issue by hussamjan** [SimpleMobileTools/Simple-Gallery#158]
I'm using large font in my device and this is how the folder label is looking see photo

http://www.m5zn.com/newuploads/2017/02/06/png//1418132d71a1e42.png

can it be fixed?

**Comment by tibbi** [comment]
I can check it in the future, but wont be a priority for now

**Comment by tibbi** [comment]
@hussamjan can you please check if it works fine in 2.3.8? Thanks

**Comment by hussamjan** [comment]
yup can confirm it is solved now!
