### ISSUE TITLE
save/export images

### ISSUE THREAD

**Issue by termitavee** [SimpleMobileTools/Simple-Gallery#1585]
I'm not sure This functionality exist or is planned but It's possible to export all images keeping the creation date?

I wanted to export all phone images/photos regarding the origin (twitter, whatsapp, telegram, camera etc) and keep ther ordered by the time it was stored/created. I managed to copy them but the date created/modified is when I copied it, not when I took them

So I'd like to ask for this functionality or if it exist how it should de done.

**Comment by tibbi** [comment]
you can already select the files by long pressing, then Menu -> Select all, then use Menu -> Fix Date Taken values. It should work just fine, even more if you use the latest Pro version.
