### ISSUE TITLE
Display month change on regular scrolling

### ISSUE THREAD

**Issue by szpak** [SimpleMobileTools/Simple-Gallery#1586]
I know about a "info bubble" when scrolling items by scrollbar dragging, however it would be nice to have a small information (at the bottom?) about a month (or a month and a year) displayed also during a normal scrolling (such as ).

I've found it useful in the old gallery app in Moto G. In addition, hearing complains from a left-handed colleague, scroller on the right is not very comfortable if you use a left hand to scroll and the aforementioned feature would be a workaround.

Probably it should be able to turn on/off in the application settings.

**Comment by tibbi** [comment]
not sure what you mean. If you enable Menu -> Group by, you will see info on the screen mentioning what date are you at

**Comment by szpak** [comment]
Initially I was thinking about the "info bubble" (as mentioned in the application configuration) to be (optionally) displayed also with a normal scrolling. However, grouping by (about which I didn't know before) does what I wanted - distinguish between months while scrolling. Thanks.
