### ISSUE TITLE
In Split screen mode window becomes dark

### ISSUE THREAD

**Issue by IT-Tool** [SimpleMobileTools/Simple-Gallery#1589]
If i use split screen on Android 7 the app (Simple Gallery) looks darker then the stock gallery with the same picture (even if window is active). And the buttons move to the top of the screen. This is a big minus, especially when you need to compare 2 images on the screen. Other apps work fine in split screen. And when i back to full screen window of Simple Gallery is fine again. Is it possible to fix it?
Thanks for great and simple app!
![Screenshot_20190915](https://user-images.githubusercontent.com/53435741/64952389-bb7cd280-d86f-11e9-93bc-e914f018b5db.png)

**Comment by IT-Tool** [comment]
Any ideas how to fix this?

**Comment by tibbi** [comment]
all you can do it maybe disabling bottom action menu items at the app settings, not much else you can do. I plan improving the split screen behaviour.

**Comment by tibbi** [comment]
should be fixed in 6.10.5
