### ISSUE TITLE
Feature request: Provide 'next action' setting for deletion

### ISSUE THREAD

**Issue by Friptick** [SimpleMobileTools/Simple-Gallery#1590]
At present, when a picture is deleted in full-screen view, the screen advances to the **previous** picture.

When going thru a bunch of near-identical photos in order to delete the duds (something I do regularly), it would be much more satisfactory and logical to do it in chronological order. In other words, on deletion of a picture, the screen would advance to the **next** picture. Either changing this behavior or providing a setting would be great.

For me this is now literally the only thing missing from this otherwise excellent project.

**Comment by puppykickr** [comment]
What I would do is set the folder to sort by date modified (this can be folder specific), and then start at the beginning of the folder.

That was the simple fix for me in the same case.

**Comment by Friptick** [comment]
> set the folder to sort by date modified

Nice idea, thanks. An acceptable workaround for now.

**Comment by Friptick** [comment]
Closing because the workaround turns out to be good enough.
