### ISSUE TITLE
Add links to simplemobiletools.com and/or github to About page

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Gallery#1597]
At the moment (v6.9.6) the About page links to Google Play for the More Apps and Rate Us links, and to Facebook and Reddit. For those of us who try to avoid Google Play or Facebook or similar, please can you add links to your own website https://simplemobiletools.com/ and maybe also to github too? Thanks.

**Comment by tibbi** [comment]
It used to be there, but sadly I cannot add it back, as it contains a Donate button. That is forbidden by Googles policy. I might reconsider some way of hiding the button if accessed from mobile or so, for now I prefer having the button without link in the app. Anyone can find it easily, it is mentioned in the email address too.
