### ISSUE TITLE
apply transparent background color of EXIF information dialogue

### ISSUE THREAD

**Issue by WanderMax** [SimpleMobileTools/Simple-Gallery#1599]
Hi,
I have tried the latest version, and find that the background color of EXIF information dialogue is just black. 
How about applying the transparent style for this information dialogue?

**Comment by tibbi** [comment]
you mean at the Extended details?

**Comment by WanderMax** [comment]
![20190928152832](https://user-images.githubusercontent.com/15909056/65813219-b53e0d00-e204-11e9-88fc-bce250d17654.jpg)
You can see as picture.
I think it's better to apply the transparent background

**Comment by tibbi** [comment]
it would be hard to read on some images, I prefer having a black one. There is some transparency on it.
