### ISSUE TITLE
Simple gallery recreates deleted directory

### ISSUE THREAD

**Issue by MickeyKnox** [SimpleMobileTools/Simple-Gallery#16]
It doesn't matter, whether I delete a directory within Simple Gallery itself or with a file manager, Simple Gallery will recreate it shortly after deletion. Simple Gallery can even display the images inside that recreated directory, although the files inside the recreated directory are empty.

If Simple Gallery is not running, the deleted directory is recreated on the next launch of Simple Gallery.

Possibly related to another issue: Deleted pictures showing up on gallery while scrolling #14

**Comment by Tony-il-Capo** [comment]
Is this fixed?
Same here [#14](https://github.com/SimpleMobileTools/Simple-Gallery/issues/14)

I still have this problem, pictures show up again with 0 Bytes after deleting them with Simle-Gallery.
I'm using last version form F-Droid.

**Comment by tibbi** [comment]
it hasnt been fixed yet. Do those images disappear if you refresh the current screen with the pull to refresh thing? Like at Facebook, swiping down from the top.

**Comment by Tony-il-Capo** [comment]
No, they still there.

**Comment by tibbi** [comment]
hello, was the mentioned directory on an SD card by any chance? If so, can you retest please?

**Comment by sakinyu** [comment]
Hello, same issue here. I can delete files from phone, but not from SD card. Files keep reappearing after being deleted... Any solution?

**Comment by tibbi** [comment]
shouldnt be happening anymore, reopen if it does

**Comment by sakinyu** [comment]
Hello! Tested on fairphone 2, and it works! Thanks a lot!

2017-09-05 14:49 GMT+02:00 Tibor Kaputa <notifications@github.com>:
