### ISSUE TITLE
Hiding folders seems broken

### ISSUE THREAD

**Issue by hman2** [SimpleMobileTools/Simple-Gallery#1609]
Release 6.10.0 running on Nougat.

In the release before that, hiding seemed to be broken altogether, now it seems that hiding only hides the precise folder marked for hiding (thus being listed in 'manage hidden folders'), but not sub-folders. Strangely, when clicking the three dots of such a visible sub-folder, the option "unhide" is listed, so it should be hidden, but isn't.

Also, when temporarily unhiding all hidden folders, none of them gets marked as hidden, which was the behaviour of previous releases.

Thanks for looking into it,
hman2

**Comment by tibbi** [comment]
do you have any folders listed in the app settings -> manage included folders?

**Comment by hman2** [comment]
Yes, of course, otherwise the content of the SD card would be missing... And all media are stored there...

**Comment by tibbi** [comment]
recheck with 6.10.5, the "(hidden)" label got some improvements. If it still wont work properly, just remove the given folders from the app settings -> manage included folders.
