### ISSUE TITLE
Crash after deleting portrait photos

### ISSUE THREAD

**Issue by neekless** [SimpleMobileTools/Simple-Gallery#1611]
Crash log here: https://del.dog/gogivuteje

I think it has something to do with the empty folder left behind after deleting the portrait photos. I don't have the delete empty folders settings turned on.

Pixel 2xl Android 9, simple gallery pro 6.10.0

**Comment by tibbi** [comment]
thanks, there are still some portrait related issues, this is just the initial implementation
