### ISSUE TITLE
App crash after latest update

### ISSUE THREAD

**Issue by anirudhnihalani** [SimpleMobileTools/Simple-Gallery#1613]
Thanks for the great work!

The latest version has been crashing on startup. I tried clearing cache, reinstalling but no luck. I am on Android 10, installed from f-droid

**Comment by tibbi** [comment]
I guess you have version 6.10.0. It has already been hotfixed with a new version release some time ago as 6.10.1, just wait till it becomes available on f-droid I guess. Thanks
