### ISSUE TITLE
Check hidden folders missing in the app settings on Android 10

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#1614]
Folders containing .nomedia are not properly recognized in the app settings -> manage hidden folders, seems to be an Android 10 issue.

**Comment by neodada** [comment]
Any update on this? Noticed same problem.

**Comment by tibbi** [comment]
not really, wasnt checking it now

**Comment by tibbi** [comment]
closing this as with version 6.23.0 and Android 11+ you wont be able to see hidden files anymore
