### ISSUE TITLE
Wonderful gallery with weaknesses in image presentation

### ISSUE THREAD

**Issue by Goarli** [SimpleMobileTools/Simple-Gallery#1615]
Many mobile phones today are already equipped with very good cameras and support the Camera2 API to save images in the lossless DNG format (RAW). The support of DNG (RAW) image files is present in your gallery, but unfortunately the output quality is really unconvincing (banding, color depth, resolution, anti-aliasing etc). Also the output of JPG (sRGB) could be better. Among other things, I use your "Simple Gallery" on an Android set-top box which outputs a color depth of 10 bit by default. Also, my TV (Panasonic OLED 65 ") is able to output the highest picture quality. At times I connect the phone directly to the TV. **It may be rude of me, but please compare the quality of the image output from a file explorer** ("File Viewer App" by Sharpened Productions). The output quality is at first glance the much better and that of a file explorer? Also in terms of speed, unfortunately, I can only give a satisfactory rating. I have a lot of folders, each with a lot of image files on the phone and on the set-top box. Each time I wait forever, until everything is loaded and your application comes to a halt. Please consider this criticism as a positive criticism of your remaining wonderful development.

With best regards
Goar

**Comment by tibbi** [comment]
What app version are you using at all? Try enabling the "Show images in the highest possible quality" in the app settings.

**Comment by Goarli** [comment]
Thank you for your quick response!

I have been using the app for a while now and have always installed the latest version from the PlayStore. Currently I use the version 5.1.4 I know all available settings of your application. Also of course the "Show images in the highest possible quality". Please do not misunderstand me, but I think you can screw it on whatever you want. I think there should be something more changed - not?

Thank you very much
Goar

**Comment by tibbi** [comment]
that app version is deprecated, no longer updated since November. Try with the Pro version at https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro

**Comment by Goarli** [comment]
That was my information error now, and I did not refer to the Pro version. Of course I have your Pro Version (6.10.1) in use. Also, I once again made a direct comparison of the output of a DNG file with the "File Viewer for Android" 
https://play.google.com/store/apps/details?id=com.sharpened.androidfileviewer&hl=en_US. 

**Please try out a picture comparison yourself and you know what I mean by more quality at DNG.**

**Comment by Goarli** [comment]
Addendum (File Viewer for Android):
I am sorry, but:
In the direct comparison I recognize a very clear banding with your JPEG.
In a direct comparison, your DNGs do not nearly reach the quality. Is that possible?

**Comment by tibbi** [comment]
not sure what you mean. So both JPEG and DNG are bad? They are handled in a whole different way, so they can be different indeed.

**Comment by Goarli** [comment]
Please do not misunderstand me, but compare for example the output quality of your JPEG and your DNG files to the output quality (JPEG <-> JPEG and DNG <-> DNG) with the app that I have already mentioned several times. Just compare the different results (your app to the other other app). I do not mean the direct difference between JPEG and DNG when it comes from the same app. I realize that there is basically a difference between JPEG and DNG. There are worlds in between - of course! Please compare the results of your and the other app, no matter if it is JPEG or DNG. The JPEG are better represented in the other app (no banding in the blue sky) and the DNG are shown much better in the other app (no pixel rendering, better resolution and so on)! You have to see it yourself, if you would only try it yourself !?

**Comment by Goarli** [comment]
Information about my output devices: On my mobile phone with AMOLED display, the resolution WQHD (2560x1440) is set. My Panasonic OLED upscaled to 4K .....

**Comment by tibbi** [comment]
I tried it, but I cannot see any difference. Can you maybe send a sample image?

**Comment by Goarli** [comment]
**_You see no difference? I really can not believe that!_**
I have each made a screenshot of a JPEG and a DNG from both apps. The files are named after the app. I think the result of the DNG explains itself - if you look closely! With the File Viewer synonymous more magnification of the image is possible (see section). In the JPEG picture Iherer app can be clearly seen the banding in the sky. If you switch back and forth between the two results, you may be able to see it. Also in the detail accuracy (sharpness) lags behind your JPEG file (unfortunately in the screenshot not so good to recognize). The screenshots were taken with a Galaxy S7.

**JPEG Simply Gallery**
![Screenshot_JPEG_simply_gallery](https://user-images.githubusercontent.com/56468495/66719506-267ae400-edf1-11e9-8f0e-649bf77f3684.jpg)
**JPEG File Viewer**
![Screenshot_JPEG_file_viewer](https://user-images.githubusercontent.com/56468495/66719588-33e49e00-edf2-11e9-82df-ca31f6c326d6.jpg)
**DNG Simply Gallery**
![Screenshot_DNG_simple_gallery](https://user-images.githubusercontent.com/56468495/66719616-ae152280-edf2-11e9-873a-f8bd92ad4fed.jpg)
**DNG File Viewer**
![Screenshot_DNG_file_viewer](https://user-images.githubusercontent.com/56468495/66719628-d3099580-edf2-11e9-8cf8-69c3d9c327d3.jpg)

**Comment by tibbi** [comment]
I mean send me some sample images themselves, not just screenshots

**Comment by Goarli** [comment]
As a developer of a photo viewing software, you need to be able to make your own RAW images to compare them. In order to recognize my described problem, you do not need extra pictures of me. I rather have the impression that you do not want to go into detail. Maybe you can not see the difference in quality because your eyes are not able to. Maybe you have to see the ophthalmologist ?! Be that as it may, I have no desire to communicate in that way. Thanks for your efforts. Thankfully, there are better alternatives.

**Comment by ouzowtf** [comment]
Thankfully, there are more grateful and helping users.

**Comment by chilliger** [comment]
> 
> 
> As a developer of a photo viewing software, you need to be able to make your own RAW images to compare them. In order to recognize my described problem, you do not need extra pictures of me. I rather have the impression that you do not want to go into detail. Maybe you can not see the difference in quality because your eyes are not able to. Maybe you have to see the ophthalmologist ?! Be that as it may, I have no desire to communicate in that way. Thanks for your efforts. Thankfully, there are better alternatives.

wow... you only had one step left and he would have looked into it. Instead this shitty comment. Well done.
