### ISSUE TITLE
Bug (only?) on Android 5.0, 5.1, 6.0 devices: bottom icon row missing in image editor

### ISSUE THREAD

**Issue by STPKITT** [SimpleMobileTools/Simple-Gallery#1618]
The following bug seems to happen at least on devices running Android 5.0, 5.1 or 6.0. I have no Android 4.x devices to try this on, but on Android 7.x this bug does not happen. I also have no devices running Android >7.x to try this on.

When I open a picture, then click on the pencil symbol to open the image editor there are supposed to be three rows of functions/icons on the bottom of the display, the first row showing functions for aspect ratio (FREE, 1:1, 4:3 etc.), the second row has icons for turning, resizing etc. and the bottom row has icons for filters, toogle the second icon row on and off and drawing.

The bug is that on the Android 5.x devices I tried this with the bottom row does never appear, the space is just grey. The top two function/icon rows always show up though.

I checked the changelog and my suspicion is that this bug was introduced with the change in Simple Gallery Pro Version 6.7.8 (2019-06-11) titled "Show the available aspect ratios at the editor by default".

**Comment by tibbi** [comment]
the editor has been fully rewritten in version 6.11.0, this is no longer valid
