### ISSUE TITLE
folders maintenance should have edit and the option for wildcards

### ISSUE THREAD

**Issue by patrickdrd** [SimpleMobileTools/Simple-Gallery#1623]
please give us the option to manually add a folder (by pasting its path) and
the option to edit a folder in order to include wildcards to them
when including/excluding and hiding a folder

also, the last exported path (for setttings) should be remembered/saved,

thanks

**Comment by tibbi** [comment]
you can already add a folder in the app settings -> manage included folders, it works recursively. Not sure what you mean by exported path, but report only one thing per issue. Thanks

**Comment by patrickdrd** [comment]
you closed the issue even though not only you didn't answer a single one of my questions,
but you didn't understand them either!

I cannot understand why developers are so eager to close issues when they're doing nothing about them!

anyway, I said I wanted the option to add a folder **manually**, that means pasting its path,
because I want to add folders that don't exist currently, on this device at least,
but could exist in the future,

I also said that wildcards, such as "*" (without the quotes) are highly desirable

I'll open another issue for the 3rd thing, ok
