### ISSUE TITLE
Add option to auto clear recycle bin after X days

### ISSUE THREAD

**Issue by stickydrive** [SimpleMobileTools/Simple-Gallery#1631]
hey, 

I use the option of steer erased photos to recycle bin but I find myself spending time to clean it every week or so.

For that I'd like to suggest an feature to help some free storage space, by adding option to active a task which empty recycle bin after X days .
In other words, everything which is sitting in recycle bin over X days will be permanently removed.

Thanks!

**Comment by stickydrive** [comment]
Similer to issue #1596

**Comment by stickydrive** [comment]
similar to issue #1596

**Comment by tibbi** [comment]
it is set to 30 days now, customizing it might be added later
