### ISSUE TITLE
folders maintenance should have edit and the option for wildcards

### ISSUE THREAD

**Issue by patrickdrd** [SimpleMobileTools/Simple-Gallery#1632]
so it seems I have to open a new issue to get the attendance required,

anyway,
I would like the option to add a folder manually, that means pasting its path,
because I want to add folders that don't exist currently, on this device at least,
but could exist in the future,

I also think that wildcards, such as "*" (without the quotes) are highly desirable (if you make the path editable as mentioned before this would work)

**Comment by tibbi** [comment]
you can already add not recognized folders in the app settings -> manage included folders. They have to exist though, I dont plan allowing adding fake folders.
