### ISSUE TITLE
Add custom order

### ISSUE THREAD

**Issue by brunetton** [SimpleMobileTools/Simple-Gallery#1634]
Hi,
This is related to #633 (sorry if you think this is a duplicate !)

I'd really need a custom sorting option (only for some specific folders) to view my photos in a pre-defined order.

Use case details: 
- I'm a musician, and I use simple gallery on stage on a tablet to view my notes. When a song finish I need to super quickly display the next one. 
- For now I've to manually rename all my pics to (something like `1 - first song notes.jpg`, `2 - second song notes.jpg`, etc) and sort by alphabetical order in the app. - But sometimes just before the show the singer decides to change the order, and I've to open a file browser on the tablet, and rename songs to have my order. This is tricky and quite long. 

I'll maybe try to make a PR, but I didn't wrote a single line in Java for years !
Do you plan to add this ?

Thanks a lot for this wonderfull piece of software !

**Comment by tibbi** [comment]
ye, drag and drop is on the roadmap. The app is written in Kotlin, there is no Java whatsoever :) Anyway, it will need a new table in the database, so dont really try doing it. Ill close it as a duplicate though.
