### ISSUE TITLE
Override original photo by default when editing and preserve original as a hidden file

### ISSUE THREAD

**Issue by uncertainquark** [SimpleMobileTools/Simple-Gallery#1635]
I get that it maybe desirable to not delete the original photo after editing but most of the times:
a) The editing is quick and simple (like a crop) and is likely to be not with the intent of preserving the original
b) It clutters the gallery.

One solution could be what the iOS Photos app does. It hides the original file on edit, and has a menu option called "Restore original" to do the same.

I believe this may be a good default behaviour. After all, it's likely that people using Simple Gallery don't need advance functions and need hassle-free defaults.

**Comment by tibbi** [comment]
closing this as with version 6.23.0 and Android 11+ you wont be able to see hidden files anymore
