### ISSUE TITLE
Allow rotating photos by 1 degree

### ISSUE THREAD

**Issue by uncertainquark** [SimpleMobileTools/Simple-Gallery#1636]
Just like Google Photos, iOS Photos and others. A few degrees of rotation is sometimes all that's needed to fix a photo.

![photo_2019-11-08_16-13-17](https://user-images.githubusercontent.com/22585732/68470734-af473d00-0242-11ea-8263-cd99e020e719.jpg)

**Comment by alekksander** [comment]
Yes, probably useful. Still, does it belong to gallery viewer?

**Comment by puppykickr** [comment]
@alekksander 
Why wouldn't it?
There is an editor feature on the app already, this could be a nice addition.

**Comment by tibbi** [comment]
the editor has been fully rewritten in version 6.11.0, this is already added there
