### ISSUE TITLE
Use grouping like Google Photos for "All Folders" view

### ISSUE THREAD

**Issue by uncertainquark** [SimpleMobileTools/Simple-Gallery#1637]
Google Photos does this really neat thing where in the stream view (All folders view on Simple Gallery), it groups photos beyond 2 rows. Would be nice to default to in Simple Gallery as well.

![photo_2019-11-08_16-17-18](https://user-images.githubusercontent.com/22585732/68471016-49a78080-0243-11ea-9481-42bb0864516b.jpg)

Also notice how it just gives the name of the folder and not the entire path, which is IMO cleaner. It's unlikely that people want to see folder paths all the time. If they do, they can check info.

**Comment by ForgottenUmbrella** [comment]
My two cents as another user: I would not want this to be the default behaviour, as the current all folders view allows me to view all images in a single view, which this change would prevent. On the other hand, the use case that this feature request would satisfy, of having quick access to the most recent image(s) of each folder, is already provided to a degree by the folder view and sort settings (most recent is in the folder thumbnail, images can be accessed by selecting the folder and then the image in only two taps), so it's more a matter of personal preference for how things are displayed; implementing this option would detract from the simplicity of *Simple* Gallery in my opinion.
I do agree that shortening the paths to only include the shortest unique suffix would be neater, but that should be a separate issue of low priority given its added algorithmic complexity and the current simple solution working fine.

**Comment by tibbi** [comment]
it isnt on the roadmap
