### ISSUE TITLE
Add optional grid overlay as composition aid

### ISSUE THREAD

**Issue by Friptick** [SimpleMobileTools/Simple-Gallery#1639]
Feature request. It would be really useful to have a grid overlay when comparing the composition of photos. For example, to judge easily whether a horizon is straight or a building is vertical.

The grid could be 3x3 or 4x4 or crosshairs, or even (ideally) a choice of those.

Thanks for your consideration.

**Comment by tibbi** [comment]
such things might belong to a camera, not really a gallery. You can already open the editor and see the lines there at the Crop action.
