### ISSUE TITLE
Edit default app

### ISSUE THREAD

**Issue by hussamjan** [SimpleMobileTools/Simple-Gallery#164]
When clicking on "Edit" on a picture, it will ask always what app to use to do the editing. 

I think it should display the the list of apps once and then after choosing the app it should make that app the default one instead of asking every time.

**Comment by tibbi** [comment]
quickpic and google photos behave the same way, looks like an editor cannot be set as default like a browser. Ill leave it here for the future, maybe it changes.

**Comment by tibbi** [comment]
turns out its actually simple to do, an "Always" button should be there at next version.
