### ISSUE TITLE
Optional grid overlay for photo comparison

### ISSUE THREAD

**Issue by Friptick** [SimpleMobileTools/Simple-Gallery#1641]
Feature request. This was deleted as "something for a camera app", perhaps because of the word "composition", now removed.

The idea: the possibility of a grid overlay (3x3, 4x4 or crosshairs etc) to aid comparison of near-identical photos. For example, to judge easily whether a horizon is flat or a building vertical.

Yes, it is for camera apps, but **not only**. The usual use case is _to speed up the choice of bad photos for deletion_. To get a good picture serious photographers use the technique of *bracketing", i.e. taking essentially the same picture a bunch of times while varying one factor (exposure, tilt, alignment), and then deleting all but the best. That requires fine comparison to know which photos to delete and which to keep.

This absolutely **is** a feature for gallery software, as evidenced by the fact that i need it every single day when using this gallery software. So it is very possible I am not the only one.

(In contrast, the editing and cropping features, are photo *manipulation*. Personally I do not see what they are doing in a gallery app. They belong in editing software.)

**Comment by tibbi** [comment]
Sorry, but I dont want to add such feature in a gallery. You can already see grids in the editor.
