### ISSUE TITLE
Moving files overwrites destination files without warning

### ISSUE THREAD

**Issue by Instagit** [SimpleMobileTools/Simple-Gallery#1642]
1. Move pictures to a directory that has a picture with the same name
2. The original file in the destination directory will be overwritten

Would be nice if there was a warning.

**Comment by puppykickr** [comment]
There is a warning.
In fact, a menu pops up and gives you multiple options:

Skip
Overwrite
Keep Both.

**Comment by tibbi** [comment]
ye, I guess you use an old app version. Conflict resolution has already been added. If it really still happens, tell us some more info about how could I reproduce it.
