### ISSUE TITLE
Temporarily showing hidden files/folder error

### ISSUE THREAD

**Issue by hman2** [SimpleMobileTools/Simple-Gallery#1646]
With 6.10.5 the bug was fixed, that when hidden items were temporarily shown, hidden folders were not marked "hidden". Thanks for the fix.

But 6.10.5 does not mark hidden _files_ to be hidden, when they are temporarily shown... With folders it does that correctly...

Thanks
hman

**Comment by tibbi** [comment]
closing this as with version 6.23.0 and Android 11+ you wont be able to see hidden files anymore
