### ISSUE TITLE
Hiding  Folder

### ISSUE THREAD

**Issue by krushnarathod** [SimpleMobileTools/Simple-Gallery#1651]
After hiding folder.   folder only hided in this app.  it is  still visible in another apps

**Comment by tibbi** [comment]
have you used the real "Hide" function, which adds a hidden ".nomedia" file in it, or "exclude"?

**Comment by krushnarathod** [comment]
I use the both function but it wont work

**Comment by tibbi** [comment]
check with some file manager if the given folder contains a hidden ".nomedia" file. If it does, there is nothing else we can do about it. For other way of hiding a folder try prepending its filename with a dot.

**Comment by puppykickr** [comment]
Perhaps he is using Simple Mobile Tools File Manager, or similar, that has a 'show hidden files' feature.
