### ISSUE TITLE
Allow setting a folder to open by default at app start

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#1653]

**Comment by v1r0x** [comment]
Great feature! It's the reason I didn't switch from google photos to this as default app

**Comment by roland-kister** [comment]
Hey @tibbi , I would like to contribute.

Where would be the best place to put this setting? Into the settings of a given folder (for example: Use this folder as default folder) or the app settings.

**Comment by tibbi** [comment]
Try the menu of the given folder, the app settings are already more crowded than Id like. Thanks

**Comment by roland-kister** [comment]
Okay, I will get on it

**Comment by tibbi** [comment]
will be added in 6.18.0
