### ISSUE TITLE
After moving the photos to another folder, it is not sorting correctly

### ISSUE THREAD

**Issue by aha999** [SimpleMobileTools/Simple-Gallery#1657]
If i move the pictures from the phone storage to the sd card into another folder, the 'Sort by image creation date' sorts by when was the image changed/moved, so it messes up all the moved photos' order of creation date/time and it randomly sorts them, although i have the sorting turned on by creation date (when the image was taken).

In short: If the photos are moved to another folder, the sorting is not correct and it randomizes the sorting, although it is set the same as before.

**Comment by tibbi** [comment]
what app version are you using? Try selecting the wrong file thumbnail and using Menu -> Fix date taken values.

**Comment by aha999** [comment]
v 6.10.6 Pro.

Thanks, while it does seem that the 'fix date values did fix the pictures date of creation sorting, now all the videos are on top, and in the properties of videos, there is no creation date. just the date of last modification/change (which is basically the move date). 

Second. I just recorded the video in Gcam, OpenCamera and Stock LineageOS cam. There is no 'Date taken' (not creation date as i said before, i just switched to english theme), but just Last Modified value.
There's no Date Taken for any of the videos so it throws them all on top after i select 'fix date taken value'.

**Comment by tibbi** [comment]
retry with 6.12.0, especially "Fix Date Taken values" has been changed
