### ISSUE TITLE
Folder specific columns and square thumbnails settings

### ISSUE THREAD

**Issue by subpub** [SimpleMobileTools/Simple-Gallery#1659]
I want to keep some photos like stickers or emojis in a folder and increase columns because they are small, but every other folder gets increased. Also turn off square thumbnails.

So folder specific:

- [] Square thumbnails
- [] Column setting

![](https://picat.drycat.fr/agN4UltJ.webp)

**Comment by tibbi** [comment]
ah no, saving those in a folder specific way would really complicate everything, I want to avoid such settings. Thanks though

**Comment by subpub** [comment]
Um, it already stores sort by and group by in a folder specific manner, right?

**Comment by tibbi** [comment]
ye, but it makes sense there. Storing these in a folder specific way hasnt been requested by a single person yet, out of millions of users.

**Comment by subpub** [comment]
Okay then
