### ISSUE TITLE
Back Button in Title Bar not Working

### ISSUE THREAD

**Issue by SwetaTanwar** [SimpleMobileTools/Simple-Gallery#167]
The new update of manage excluded folder is having issue. The back button in Manage Excluded Folders Screen is not working.
![screenshot_2017-02-27-14-19-56-606](https://cloud.githubusercontent.com/assets/19969451/23355008/b37368aa-fcf9-11e6-85f4-29a36a8c6f4e.jpeg)

**Comment by tibbi** [comment]
ah, so somebody actually uses that button :D I didnt even test it apparently

**Comment by SwetaTanwar** [comment]
Yes somebody do use that button, and thanks to it's use the bug could be reported.

**Comment by tibbi** [comment]
Apparently its broken at getting from thumbnail view to the initial view too, it will be fixed in the next version.

**Comment by SwetaTanwar** [comment]
Okay
