### ISSUE TITLE
Can't view video properties when the video thumbnail is opened

### ISSUE THREAD

**Issue by aha999** [SimpleMobileTools/Simple-Gallery#1672]
When i select a video with a long finger press (for multiple selecting), the video's properties can be viewed from the menu in the top right menu. But when i click the video thumbnail to open it and press menu, there's no Properties option.

**Comment by tibbi** [comment]
it is most likely shown at the top menu as a circled "i", as the most common actions are shown at the bottom action bar by default

**Comment by aha999** [comment]
right, it's there. it confused me because it wasn't in the menu.
