### ISSUE TITLE
When pressing a certain video, that is not the first in the order, it opens the first one in the gallery

### ISSUE THREAD

**Issue by aha999** [SimpleMobileTools/Simple-Gallery#1673]
I press a first video thumbnail, it opens the first
I press a second video, it opens the first
I press a third video, it opens the first
I press a fourth video, it opens the first
etc.

That's literary it. happens a lot of the time but not always.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by aha999** [comment]
v 6.10.6. pro

**Comment by mhartung** [comment]
This faulty behaviour exists as well with pictures and not just videos.
I click on any file in /sdcard/Pictures via file-manager 'Dir'. Simple gallery always opens the latest file in this folder and not the one I clicked on.
