### ISSUE TITLE
Buttons inaccessible in split-screen

### ISSUE THREAD

**Issue by IT-Tool** [SimpleMobileTools/Simple-Gallery#1678]
In continuation to the already fixed bug [https://github.com/SimpleMobileTools/Simple-Gallery/issues/1589](url)

Main functions in buttons are inaccessible in split-screen. Can you return the buttons to the bottom? If this is difficult to do, maybe when you switch to split-screen mode, app can move the buttons automatically in the menu on the right side?

I know i can disable bottom action menu items at the app settings, but this is not the most convenient option anyway :)
![photo_2019-12](https://user-images.githubusercontent.com/53435741/71379810-d339c480-25dd-11ea-95c2-5ca9099bdad3.jpg)

**Comment by tibbi** [comment]
is that a tablet, or what?

**Comment by IT-Tool** [comment]
right, it's only on tablet

Screen Resolution - 1600 x 2560
Screen Size - 113 mm x 181 mm
Screen Diagonal - 8.4 inches
Pixel Density - 359 dpi
xdpi / ydpi - 360 / 359 dpi

**Comment by tibbi** [comment]
should be fixed already
