### ISSUE TITLE
Add pre-made Dark and OLED black themes

### ISSUE THREAD

**Issue by Cormak** [SimpleMobileTools/Simple-Gallery#169]
Not everybody needs to customize their theme from scratch. Most people just want an option in the settings to switch to a dark theme and an OLED theme. It would also be helpful to make sure these pre-made themes work with all visual elements of the app, as some elements can be made illegible if you select the wrong color. 

This would also be good to add to all of the Simple Mobile Tools.

**Comment by tibbi** [comment]
yea, some premade themes are on the roadmap. Nowadays I focus on the gallery and a bit on the calendar, the rest of the apps is quite behind.

**Comment by Cormak** [comment]
@tibbi That's not surprising considering that the gallery and the calendar are in high demand right now because of Quickpic being sold and most Calendar apps requiring too many permissions. Thanks for the premade themes option. That option will make your "simple" apps even simpler to use.

**Comment by smichel17** [comment]
I made a new issue that's a copy of this one over on Simple Commons, where the theming code is: https://github.com/SimpleMobileTools/Simple-Commons/issues/33

**Comment by tibbi** [comment]
ok thanks, ill close this one then
