### ISSUE TITLE
Allow to include a folder but keeping some of its subfolders excluded

### ISSUE THREAD

**Issue by proideo** [SimpleMobileTools/Simple-Gallery#1697]
I don't know if there is any way to do it but when I add the main folder (storage/emulated/0) of my device to **Included Folders** and the _Android_ folder (in storage/emulated/0) to **Excluded Folders**, the app does not respect this last setting and shows all the contents of the main folder. I know that I can add the folders one by one except _Android_, but is there no other way to do it?

**Comment by tibbi** [comment]
you definitely shouldnt include the main Internal storage folder, as it will scan all subfolders more thoroughly. If a folder is both included and excluded, it will show, I dont plan changing it for now.
