### ISSUE TITLE
Make app icon into a circle to fit Android 7.0 aesthetics

### ISSUE THREAD

**Issue by Cormak** [SimpleMobileTools/Simple-Gallery#170]
It seems Android 7.0 and beyond is going with circular icons, so it would be suitable to turn all the Simple Mobile Tools icons into circles instead of rounded squares. Some people may disagree on this but I think it would make Simple Mobile Tools apps fit in better with other modern apps.

**Comment by tibbi** [comment]
added rounded launcher icons. Its a separate field in the App manifest, so devices under Android 7 will still use the square ones.
