### ISSUE TITLE
Need meaning for a string

### ISSUE THREAD

**Issue by unbranched** [SimpleMobileTools/Simple-Gallery#1700]
Hi, I was about to send a translation update but one string is stopping me: in filters, there is a "Portraits" option. What do you mean with it?
It doesn't find any in my gallery.

**Comment by tibbi** [comment]
Hey, portrait images are a pretty new Android feature, which basically creates multiple photos of the given object. With it you can achieve for example doing a selfie with your head being ok, with blurring the background. But you also have a photo where both your head and the background are ok, sharp. There is some explanation at https://www.androidauthority.com/what-is-portrait-mode-945061/ . I guess you should just leave it as "Portrait", it isnt really something translated often.

**Comment by unbranched** [comment]
Thanks a lot! With your info I've been able to translate it correctly!
