### ISSUE TITLE
How to compile and use without PESDK license?

### ISSUE THREAD

**Issue by SammysHP** [SimpleMobileTools/Simple-Gallery#1701]
Version 6.11 is not available via f-droid because of the introduction of the proprietary, commercial PhotoEditor SDK.

1. F-droid will not accept the app as long as it requires proprietary libraries. It is stuck now to 6.10.8 and might be removed if it is outdated for too long.
1. How do I compile Simple-Gallery myself if I don't have a PESDK license?

While I don't like the inclusion of proprietary software, I can accept it as long as I can use it unlimited for free.

A solution would be to replace the editor in the f-droid version with the previous implementation (which was enough for my use cases).

Also I couldn't find any contribution and/or compile instructions. It would be great to add a file which describes dependencies and prerequisites to compile this app and how/if you would like to get contributions.

**Comment by tibbi** [comment]
you can compile it just like any other project. The library is downloaded from the internet, it is not added in any special way.

**Comment by SammysHP** [comment]
What about f-droid? And I don't need a license file to use it? Great!

**Comment by tibbi** [comment]
you need it, it is uploaded too

**Comment by SammysHP** [comment]
Found it, thank you!

What about f-droid? Do you want it to be removed or do you plan a different release for f-droid?

**Comment by tibbi** [comment]
I dont plan maintaining 2 versions, so it will stay as it is for now

**Comment by SammysHP** [comment]
A separate "Simple Photo Editor" app would have been a better way to do this. The integration in the app would be the same as it just calls the edit intent where you select your preferred app.

**Comment by licaon-kter** [comment]
@tibbi So this functionality can't be separated in a gradle flavour that doesn't load non-FOSS libs?

**Comment by tibbi** [comment]
I dont plan separating it for now, we will see in the future.
