### ISSUE TITLE
Make multi-select clearer

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Gallery#171]
At the moment, which images you have selected in a multi-select operation (initiated by a long-press) are indicated by changing their colour. Depending on the mixture of images in a folder, this can sometimes be hard to see.

I suggest, in addition to changing the colour, adding another kind of highlight, like maybe adding a border or a tick.

Many thanks for this great app, and for making it open source.

**Comment by JohnVeness** [comment]
Many thanks for this commit. It is now a lot easier to see which items are selected.

Unfortunately the tick clashes with the icon for videos. In the below image there is one video and three photos, all selected, but the tick for the video is underneath the “play" icon and hard to see. I suggest either using a different corner, or putting the tick on top of the play icon.

![screenshot_20170806-093054](https://user-images.githubusercontent.com/2512915/29001744-d66de4ac-7a8a-11e7-88f4-6472646fb59c.png)

**Comment by tibbi** [comment]
heh right, weird I didnt notice that.
