### ISSUE TITLE
Lost string 

### ISSUE THREAD

**Issue by LuisAlfredo92** [SimpleMobileTools/Simple-Gallery#1713]
![Screenshot_20200107-223042](https://user-images.githubusercontent.com/17792760/72003548-3b5bed80-320f-11ea-8da9-08f795ed04db.png)
I found this text that doesn't exist in the values

**Comment by tibbi** [comment]
there is a note at the bottom of every Strings file, about additional strings found in Simple Commons at https://github.com/SimpleMobileTools/Simple-Commons/tree/master/commons/src/main/res . It contains strings reused by multiple apps.
