### ISSUE TITLE
After picture transfer: Pictures not correctly sorted by "date taken" or "last modified"

### ISSUE THREAD

**Issue by Utini2000** [SimpleMobileTools/Simple-Gallery#1729]
Hey there,
I just transferred my whole DCIM folder from my old phone (Nexus 6P) to my new phone (Pixel 4 XL).
I then noticed that the pictures won't be sorted correctly by neither "date taken" and "last modified" although the data on the images is correct. 

Newly created pictures are sorted fine, but everything else is just sorted as if it was taken or last modified on one single days (which is the day when I transferred it to my new phone).

I also tried the "fix date taken value" which gave me a "success" notification, but it didn't help at all.

Any ideas? Maybe something I can do differently when transferring my pictures?

Thanks!

**Comment by tibbi** [comment]
what app version are you using? It has been rewritten in 6.12.0 that just started rolling out a couple hours ago and it isnt available to everyone yet.

**Comment by Utini2000** [comment]
I am still on 6.11.8 and have no update in google play store.

Is there also going to be a way to "fix" a whole folder by clicking on that one folder instead of clicking on every single of my 350 pictures inside the folder? :)

**Comment by tibbi** [comment]
no, but you can long press 1 item to start the selection mode, then click on the top left corner at 1/350 to select them all. There is also a Select All item at the top menu, just press the three dots in the corner.

**Comment by Utini2000** [comment]
Awesome thanks, then I will wait for the update to roll out and give it another try. 

It seems to be happening with all my folder, no matter if located in DCIM or not.
Everything I transferred from my old phone to my new one is affected.

**Comment by Utini2000** [comment]
Can I download the 6.12.0 release somehwere else? F-droid and google both still have 6.11.8 Pro

**Comment by tibbi** [comment]
ye, it is at https://github.com/SimpleMobileTools/Simple-Gallery/releases . It is still rolled out only to 30% at Google.

**Comment by Utini2000** [comment]
Thanks, that fixed the issue. Great job, great app, I am a happy Pro user ;-)

**Comment by tibbi** [comment]
cool, enjoy :)
