### ISSUE TITLE
Videos can disable "show hidden files"

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1736]
It's not consistent, but happens far too often.
Ex:
https://files.catbox.moe/x5lh2i.mp4
Android 9.0
Simple Gallery 6.12.0 Pro

**Comment by tradej** [comment]
Also a problem for me. It seems to happen with bigger videos more often.

**Comment by tibbi** [comment]
closing this as with version 6.23.0 and Android 11+ you wont be able to see hidden files anymore

**Comment by tradej** [comment]
@tibbi you mean that you won't be able to access folder starting with `.`? Is there more info about why? It's a crucial feature for me. Thanks.

**Comment by tibbi** [comment]
yeah, galleries wont be able to see hidden files anymore due to the storage restrictions, only apps like file managers will be able to do it
