### ISSUE TITLE
auto rotate screen

### ISSUE THREAD

**Issue by lucamp** [SimpleMobileTools/Simple-Gallery#174]
Hi,
could you please consider adding "auto rotate screen" option?
So users don't have to enable it system wide when viewing landscape photos.

Maybe you could check "document viewer" code as they already have implemented it
https://github.com/SufficientlySecure/document-viewer

Thanks for yuor app
Luca

**Comment by Jazcafe** [comment]
Yes please, I had this feature in another app and it worked really well.
