### ISSUE TITLE
Icons on top right depend on the orientation you opened the image

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1740]
If you open an image when on portrait mode:
![Screenshot_20200211-151309_Galeria](https://user-images.githubusercontent.com/29208110/74265495-6c817f00-4ce1-11ea-98cc-2eb5d721ba70.png)

If you open an image when on landscape mode then rotate back to portrait:
![Screenshot_20200211-151300_Galeria](https://user-images.githubusercontent.com/29208110/74265580-8f139800-4ce1-11ea-8f6e-793a333d583e.png)

You can do the opposite for landscape mode and get the same outcomes.

**Comment by tibbi** [comment]
that is handled by the system, not the app

**Comment by floppyD** [comment]
But can't you check the current orientation and hide the extra icons if necessary? That would make things more consistent. Maybe even give us an option to customize these icons just like we can customize bottom actions.

**Comment by tibbi** [comment]
No, Im not messing with how many buttons are shown at all. The system takes care of it fully.
