### ISSUE TITLE
Navigation drawer on the main menu

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1742]
In my opinion it would make the app look better overall, also decluttering the options menu a little bit and giving the Trashcan a proper place, instead of having it as a weird folder.
![Screenshot_20200211-233755_Memoria](https://user-images.githubusercontent.com/29208110/74298122-99f11b80-4d27-11ea-895c-b7da9d1cb5e4.png)

**Comment by tibbi** [comment]
I dont like the navigation drawer. Having a button at the top left corner is ridiculous.

**Comment by floppyD** [comment]
The button is there just to show that the drawer exists, and I think I've seen some apps without it already.
