### ISSUE TITLE
Renaming tool and menu item vanished

### ISSUE THREAD

**Issue by uli-on** [SimpleMobileTools/Simple-Gallery#1745]
Though checked in the extended options, the renaming tool is vanished from my toolbar and also from the menu.

App v6.12.5
Android 6.0.1, Moto G4

**Comment by tibbi** [comment]
maybe you added it at the bottom actions? The icon looks like a cursor, it is pretty much impossible that it disappeared. It might not be shown only at third party intents, when the real file path isnt known.

**Comment by uli-on** [comment]
It's even a third thing, and I didn't realize, sorry, that I only tried to work from **there** after updating the app today: Simple Gallery seems to treat the **recycle bin** differently in that the renaming tool is removed. So maybe it's a technical restriction, but if it's possible to add renaming (back?): I'd really like to be able marking certain photos in the trash can by renaming those I'm not certain to delete. Or sharing some after customizing their name.  Thanks!

**Comment by tibbi** [comment]
if I dont know where is the actual file located, I cannot rename it
