### ISSUE TITLE
Two old photos recognized as 2202 after upgrade to 6.12.5

### ISSUE THREAD

**Issue by szpak** [SimpleMobileTools/Simple-Gallery#1747]
After upgrade to the last available beta version in Google Play (6.12.5) two photos taken in November 2019 started to be recognized as November 2202.

Clicking on the `i` icon I see that `date taken` and `last modified` is still November 2019.  They were displayed in the correct place until now. I haven't touched them recently.

My sorting is "Last modified" descending.

**Comment by tibbi** [comment]
At which place is the November 2202 mentioned?

**Comment by szpak** [comment]
In the "Camera" folder at the top (next is "Feb 2020"). I have grouping by month enabled.

**Comment by tibbi** [comment]
try selecting it at the thumbnails view and using Menu -> Fix Date Taken values

**Comment by szpak** [comment]
It helped. Thanks for your suggestion.

Was there anything wrong with just those two files or it is a glitch in the sorting mechanism in SG (and I just should remember of that workaround)?

**Comment by tibbi** [comment]
not sure, it must be something device specific. I guess that some app changed the date taken of those files, maybe you were experimenting with something.

**Comment by szpak** [comment]
Hmm, I cannot exclude that. Would that "experimenting" take place recently or it could be "broken" long time ago and only started to be visible after the latest upgrade to 6.12.5?

**Comment by tibbi** [comment]
not sure, it depends. There have been some sorting related changes now, maybe it was unnoticed before that. Just let me know if it happens somehow again with some info.
