### ISSUE TITLE
[BUG] Excluded folders back button

### ISSUE THREAD

**Issue by Woodzrul** [SimpleMobileTools/Simple-Gallery#175]
Version: 2.5.0
Phone: OnePlus 2 A2001
ROM: AOSP 6.0.1

Open Gallery app -> Settings -> Manage excluded folders

When on this screen the back arrow button located in the top left does not appear to work. I therefore have to use the hardware back button key instead. Note that I do not exclude any folders so my list is therefore empty.

If you can resolve then that would be great.

Thanks

**Comment by tibbi** [comment]
Hey, it has been fixed already like 4 days ago, its just not updated on f-droid yet for some reason. Hope it will be soon :)

**Comment by Woodzrul** [comment]
Appreciate the prompt response. I'll keep an eye out for the updated apk.
