### ISSUE TITLE
Simple Gallery doesn't work with Google Camera

### ISSUE THREAD

**Issue by alcoolfire** [SimpleMobileTools/Simple-Gallery#1756]
When using the Google Camera app, clicking the button to the right of the shutter release button shows the last photo taken. I'm not sure exactly how that relates to a gallery app, but it does. With Google Photos disabled/uninstalled and with Simple Gallery installed on a Nexus 5 phone running Android 6.0.1, that function of Google Camera works as expected. But the same setup on a Google Pixel 3a phone running Android 10 does not. If I do not enable/install Google Photos as well, the button in question briefly shows the last photo but then immediately disappears as the screen reverts to the (now blacked out) viewfinder camera mode.

Is there a setting somewhere in Simple Gallery or Google Camera that I'm just not seeing that explains the difference or does one of Simple Gallery or Android 10 have a bug that is breaking this functionality? I very much do not want Google Photos on my phone.

(The title I chose for this issue is too vague. Something better is welcome.)

**Comment by tibbi** [comment]
Do other gallery apps work better? Google Camera has hardcoded apps to be open on some devices and it cannot be changed.

**Comment by alcoolfire** [comment]
QuickPic (before it got bought up by a click fraud company) worked on the Nexus 5 (Android 6.0.1) too. On the Pixel 3a (Android 10), [A Photo Map/Manager](https://f-droid.org/en/packages/de.k3b.android.androFotoFinder/) won't run at all. [Camera Roll](https://f-droid.org/en/packages/us.koller.cameraroll/) didn't work. [LeafPic Revived](https://f-droid.org/en/packages/com.alienpants.leafpicrevived/) doesn't work either.

Is there a way a non-developer can check if a particular phone has that hardcoding? I sure hope you can find a solution for Pixel phones as this is a pretty major stumbling block for Camera app users.

**Comment by tibbi** [comment]
I checked the preinstalled Camera apps on Nokias before, they are explicitly specifying the package name of the app that should be invoked. There is just no way to overwrite that. I havent checked any intent interceptors before, but you can try apps like https://play.google.com/store/apps/details?id=lt.andro.broadcastlogger or https://play.google.com/store/apps/details?id=info.maigo.lab.intentviewer , or look for some "intent interceptor" or so. Check if there is the Google Photos package name "com.google.android.apps.photos" mentioned at pressing the last taken photo.

**Comment by alcoolfire** [comment]
[Internal Broadcasts Monitor](https://play.google.com/store/apps/details?id=lt.andro.broadcastlogger) captures nothing at all related to the Camera app. Maybe Android 10 isn't letting it run in the background? Google Camera app won't do split screen. The app's Settings menu item is greyed out. Perhaps not compatible with Android 10.

[Intent Viewer](https://play.google.com/store/apps/details?id=info.maigo.lab.intentviewer) does nothing whatsoever.

If [Intent Intercept](https://f-droid.org/en/packages/de.k3b.android.intentintercept/) records anything, I surely cannot find it anywhere.

Is there a way to find intent references in the APK file? I downloaded [this APK file](https://www.apkmirror.com/apk/google-inc/camera/camera-7-3-018-291816413-release/google-camera-7-3-018-291816413-2-android-apk-download/), unzipped it, and used **objdump -s** on its shared objects files, but found nothing useful. Not sure if that was a correct approach though.

**Comment by tibbi** [comment]
No, there is nothing related to that mentioned in the camera app. It is fully done in the gallery. Im not sure what non dev way there is for it. Anyway, I guess that if no gallery app works well, that is the case. Google Photos is hardcoded into it.

**Comment by alcoolfire** [comment]
You've confused me there, @tibbi. If "com.google.android.apps.photos" is not referenced in the Google Camera code somehow (which is what I was looking for), then Google Photos is **not** hardcoded into Camera and you should be able to make Simple Gallery work with Camera too. Maybe I confused things by saying "intent references" when I should have said "package name" in my earlier message.

I can now add that [Gallery Go by Google Photos](https://play.google.com/store/apps/details?id=com.google.android.apps.photosgo) doesn't work with Google Camera either, which might support your contention that it's hardcoded. When Google figures out that their own Gallery Go doesn't work, they might have to open that function up.

**Comment by tibbi** [comment]
ye sorry, I told it wrong. It has to be hardcoded into the camera app obviously. Anyway the camera app is not open source so unzipping it like that and searching for some string wont work. If not even Gallery Go works, other galleries obviously wont.

**Comment by tibbi** [comment]
just tested a huawei device too, they are launching a hardcoded camera app too. There isnt anything I can do in such cases.
