### ISSUE TITLE
Pinch-Zoom broken for certain images

### ISSUE THREAD

**Issue by katzenpapst** [SimpleMobileTools/Simple-Gallery#176]
Just noticed that image zooming only works for some photos on my phone. Usually the first one I select from the main screen. When I swipe to another photo, I cannot zoom anymore, not even the first one. Others become zoomable after a while, others don't.

I can reproduce this with versions 2.5.0, 2.4.0, 2.3.9 and 2.3.8, earlier versions are no longer on f-droid.

The Phone is a Samsung Galaxy S5, Model SM-G900F, Android 5.0, rooted. 
I will also try attach one of the affected photos, in case there is something wrong with them.

**Comment by katzenpapst** [comment]
![20170303_143712](https://cloud.githubusercontent.com/assets/8077005/23553709/3d967394-0022-11e7-9fd4-db5b5b55a280.jpg)

**Comment by Avispa** [comment]
Can confirm this.
Version 2.10.4 from F-Droid bug is still around.

**Comment by katzenpapst** [comment]
I can still confirm this on Android 6

**Comment by tibbi** [comment]
can you try with smaller images? Maybe its some memory issue.

**Comment by katzenpapst** [comment]
Might very well be. Just scrolled a little through my old galaxy S2 photos, everything seems to work fine there. Also, it might actually work better on android 6, after all. after clicking back and forth between an image and the overview a few times it seems to actually allow me to zoom at some point.

Everyone knows that android sucks and memory management in regard of pictures. Could you maybe try adding a more aggressive approach to garbage collection? maybe as an option, if it would be too hard on the battery?

**Comment by tibbi** [comment]
Im not doing garbage collection, images are loaded by third party libraries which are doing it better than I ever could. Theres still a couple things I want to tweak and experiment with, its a long process. Im preloading 2 images per side now to allow faster swiping, but its balanced by using lower quality images, 16 bit. For very most photos its perfectly fine, the lower quality is visible just at some simple jpgs with gradient background or so.

**Comment by katzenpapst** [comment]
Hm well, it does mostly occur when I swipe... 
Maybe something like: when the user attempts to zoom, unload the other preloaded images?

**Comment by Avispa** [comment]
What is the status after more than a year? I can Still confirm this issue as like as **katenpapst**; also Galaxy S5 (SM-G900FD), Android 5.0 -- _not_ rooted; _SimpleGallery_ 3.5.2 (F-Droid).

Even though this is not representative, but while testing again for this post every 4th picture is not zoomable while on the 12 picture _SimpleGalaxy_ just crashed --  leaved phone unusable since I couldn't use touch anymore to "confirm" that Gallery crashed. After some timeout _SimpleGallery_  seemed to recovered/restarted and phone was fine again. However this may be the extreme but but in general not so uncommon behaviour.

Second try: 2 zoomable, 2 not, 2 zoomable, 2 not, black screen. Only solution: going back to home screen and enter again.

**Comment by tibbi** [comment]
not much new, guess it can still glitch in some cases. I couldnt reproduce the bug on my devices, so it doesnt seem like some major issue.

**Comment by tibbi** [comment]
retry with 6.2.0, reopen if still broken

**Comment by tibbi** [comment]
well your device is running out of memory then. I guess it is caused by the rooting, maybe a custom ROM too?

**Comment by katzenpapst** [comment]
No custom rom.

Cleared some Samsung bloat now (last time I bought a samsung...), have about 700mb worth of free ram now. Out of 1.8GB, this is ridiculous... It seems to mostly work now. Though sometimes it takes several seconds before a picture can be zoomed. Some pictures take quite a while to display at all. 

I GUESS you can leave this closed. Maybe add a warning somewhere that this app doesn't properly work on samsung phones because samsung is shit.

I still can test this app occasionally, but I'm not going to actually use it. The default samsung gallery works much better. Maybe this is not a coincidence *tips tinfoil hat*

**Comment by tibbi** [comment]
it doesnt really matter how much ram your device has, even on top notch devices 1 app wont have more than 192mb available.

**Comment by tibbi** [comment]
I improved some memory handling in version 6.2.2, you might want to recheck it. Not sure if it will change anything whatsoever in your case, we will see.

**Comment by katzenpapst** [comment]
Ok, I'll try it when the version arrives at fdroid

**Comment by katzenpapst** [comment]
It arrived. No difference, sorry :/
