### ISSUE TITLE
Lot's of useless pictures; crash

### ISSUE THREAD

**Issue by github-user-1** [SimpleMobileTools/Simple-Gallery#177]
Since the last version 2.5.0 (from F-Droid, on Android 5) I have suddenly hundreds of folders listed - all music folders as far as I can tell and each with just one pic (the album cover).

If I go the 'show individual pictures' view then I get an option called "Exclude" (not visible/available in the folder view), however if I click this option (hoping to find a way to get back the old, original views) the app silently crashes.

I really loved the app and would hate to switch to another one.

**Comment by tibbi** [comment]
you should have an exclude option in folder view too, if you long press an item. The files are probably visible only if you have the option "Show hidden folders" selected in settings. I want to add some way of hiding the parent folder of all those folders, and also drag-select will come in the future. The crash obviously isnt correct, Im working on fixing such issues.

**Comment by github-user-1** [comment]
I don't see an "Exclude" option when in folder view:

![screenshot_2017-03-03-16-36-59](https://cloud.githubusercontent.com/assets/6796538/23558169/e922a402-0032-11e7-99fd-c62f987d32ae.png)

But I do see it when in the individual picture view:

![screenshot_2017-03-03-16-38-42](https://cloud.githubusercontent.com/assets/6796538/23558206/ff8bd498-0032-11e7-8800-49ddbc2aa27a.png)

(this is the one which is crashing). Long-pressing on each folder is not an option (a few hundred of them; and they are changing quite often).

My settings are:

![screenshot_2017-03-03-16-39-07](https://cloud.githubusercontent.com/assets/6796538/23558273/3f297506-0033-11e7-9523-914ea616434b.png)

**Comment by tibbi** [comment]
Yea there needs to be a different solution for those many folders. The long pressing at the folder view is obviously made for a couple folders only. I will probably add an exclude/hide button even if nothing is selected, and let the user pick a folder.

**Comment by tibbi** [comment]
The new solution seems fine to me, you can easily select parent folder at the exclusion dialog now.
