### ISSUE TITLE
Regression: drawing and filters are no longer present in the F-Droid version

### ISSUE THREAD

**Issue by nbmrjuhneibkr** [SimpleMobileTools/Simple-Gallery#1772]
After updating from v6.10.8 to v6.13.1 on F-Droid, filters and drawing features have disappeared from the editor completely. This is not mentioned in the changelog on F-Droid, and this also means that the description of the app is now incorrect.

It's a rather large and obvious regression. I sincerely hope that this is not a deliberate attempt to handicap the FOSS version in favor of the proprietary one.

**Comment by tibbi** [comment]
the Google Play version has a brand new editor that f-droid wont accept. I dont really plan improving the old editor, but I can keep this here just in case someone wants to do it.

**Comment by nbmrjuhneibkr** [comment]
This isn't about "improving" anything. This is about keeping features that were already present instead of removing them from the FOSS version completely.

**Comment by puppykickr** [comment]
@nbmrjuhneibkr 
This is very aggrevating.
Simple Gallery is easily the best gallery app (and so much more) available.

The dev works tirelessly, and has multiple apps in the Simple Mobil Tools collection.

Personally, I like the built in editor.
But, it is not open source, and I can see the viewpoint against including it on a platform that is designed for FOSS apps only.

That being said, some people have been giving this dev what I consider to be undue grief about the matter.

It has gone on endlessly fpr months now, and it deems that hardly a day goes by without somebody saying that the editor needs to be removed, that they don't use it anyway, it's not FOSS, etc.

It must be very disheartening for this dev to have to keep rehashing this issue.

I appreciate what this dev has done-  his apps have made my device much better.

To see him badgered repeatedly over what is possibly his greatest app-  well, I sort of take that a bit personally.

Don't look a gift horse in the mouth.

These apps are provided on F-Droid free of charge, they don't have to be.

Sorry for the rant, but these guys have been hammering on this dev for a very long time about this editor.

If the newest version of an app does not suit your needs, it is not hard to download a previous version.

In your F-Droid settings, be sure to activate the F-Droid Archive repository, and when you update your repositories all versions of apps will become available.

Or, you can download a small, excellent app from this same dev-  called Draw.
It has the features that you find missing in the new Gallery and some others, as well.

I have had it for quite some time anyway, so hopefully this changeover will go smooth for me.

**Comment by nbmrjuhneibkr** [comment]
That's a big wall of text with not a lot of meaning in it.

Let me repeat: it's not about implementing some new features in the FOSS version. It's about keeping features that were already implemented. v6.10.8 had a perfectly fine simple editor. v6.13.1 on F-Droid still has an editor, but now it's missing features for no good reason. Why not just keep the features that were already there?
Just because it's provided free of charge doesn't mean that no one should have any expectations about it. Not removing features in an update is a very reasonable expectation for any software. What if it suddenly stops opening half of the images in the next update? Should that be acceptable too?
If the dev wants to make the app proprietary, and only provide it on Google Play from now on - he can do this, sure. But if he commits to release an update on F-Droid, it should have feature parity with the previous F-Droid version, at least.

"Just use the old version" is an absolutely terrible advice for any software (because no app will stay compatible with new hardware and operating systems forever), but especially for software that is still being updated and released as open-source.

**Comment by puppykickr** [comment]
@nbmrjuhneibkr 
Do you understand what FOSS is?
Obviously not.

F-Droid is a repository of FOSS apps.
The editor that was included in previous editions of the app was not FOSS.

If you are too dense to just download the Draw app which has the features missing from the Gallery app, then just download Simple Gallery from the Google Play Store.  That version still has the editor that you like.

And telling you to use an older version that has the features you want is not bad advice-  it is the solution to your 'problem'.

Whether or not you like it is up to you.

Personally, I like the old editor too, but I have seen the misery that the inclusion of non-FOSS material has brought this dev, and do not wish to see it continue.

Seeing as how that editor has been removed, my guess is that the dev is tired of it as well.

So either download the older version with the editor, or download the new version with the editor from Google Play, or get the Draw app and deal.
