### ISSUE TITLE
A couple theming issues

### ISSUE THREAD

**Issue by smichel17** [SimpleMobileTools/Simple-Gallery#178]
- [ ] The `Text color` setting should change the color of folder and file names.
- [ ] When viewing a picture, the status bar should not be tinted, since the app bar is transparent.

**Comment by tibbi** [comment]
Im not changing the text color as the background is a colored photo, which could give weird combinations with regards to readability. The gradient background is not a lifesaver either.
Ill check the status bar, makes sense.

**Comment by smichel17** [comment]
It feels weird that there's an option that doesn't actually do anything.

I vaguely recall you talking about a vision where you can just set the color in one place and it will effect the colors of all the SimpleMobileTools apps. If my memory is correct and that's still the plan, then this is only a temporary issue and it doesn't need to be fixed.

**Comment by tibbi** [comment]
ye its still on the roadmap. However that currently wouldnt change the album text color, its hardcoded to white on black gradient, to make sure its always readable. It might change in the future, but I want to leave it like that now.

**Comment by gsantner** [comment]
Yeah, the notification area color is disturbing while viewing pictures.
Just a quick comparision:

<table>
<tr>
<td>
Simple Mobile Gallery
![photo_2017-05-01_16-28-58](https://cloud.githubusercontent.com/assets/6735650/25585795/d9038f32-2e8b-11e7-88ec-5b0964dfe60e.jpg)
</td>
<td>
Lineage Gallery
![photo_2017-05-01_16-30-19](https://cloud.githubusercontent.com/assets/6735650/25585806/e1dae7a4-2e8b-11e7-98ad-87979fccbe37.jpg)
</td>
</tr>
</table>

**Comment by tibbi** [comment]
Well I honestly like the left one a lot more. The one on the right doesnt look native to android at all, especially with the action buttons at the bottom.

**Comment by gsantner** [comment]
Its not about the actions, or how they are aligned, its about the top orange

**Comment by tibbi** [comment]
ye i know, just had to say it :) Anyway I dont want to change the top color, I just like it this way. If you have an Android version higher than 4.x, you can easily swipe between images in fullscreen mode, how people usually do (Im pretty sure you are aware of it, just saying)

**Comment by gsantner** [comment]
Yeah, but most people I would say dont do that extra click :D

**Comment by smichel17** [comment]
The Lineage gallery looks bad for other reasons. Here is the actual proposed change:

| Current Orange  | Proposed Black |
| ------------- | ------------- |
| <img height="550" src="https://cloud.githubusercontent.com/assets/6563664/25726085/7845ec96-30f0-11e7-93cc-4d400779883d.png" alt="current orange">  | <img height="550" src="https://cloud.githubusercontent.com/assets/6563664/25726089/7b36319a-30f0-11e7-99da-d04037c2f2b7.png" alt="proposed black"> |

@tibbi Do you still like the orange better, here?

**Comment by smichel17** [comment]
I played around with different values and my personal favorite is orange, but made much darker (eg, just ramp up whatever transform you do to change colorPrimary into colorPrimaryDark).

**Comment by gsantner** [comment]
@smichel17 as said, the screenshot was about the orange part and nothing else :)

**Comment by smichel17** [comment]
@gsantner I know, but it's still difficult to pick them apart in your head when you're looking at the picture :)

**Comment by tibbi** [comment]
I still like the orange one better, I dont want to change the status bar color between screens for no apparent reason. Anyway I want to focus on bugs and features more than on such things. Apparently for hundreads of thousands of people like the orange.

**Comment by tibbi** [comment]
Im closing it, as I dont want to change any of the 2 reported things for reasons mentioned above.

**Comment by gsantner** [comment]
Sad to hear that, while in any other activity/view the orange works good, it's really disturbing when viewing pictures. I really hoped for a checkbox preference which make it black/transpatent in viewing.. well, if you are so much against it. It's 3 lines xml, and 1 line of java code.

**Comment by smichel17** [comment]
@gsantner I'm still using it as my primary app gallery; after some more, I settles on `#2D2D2D` as my primary color. I still slightly prefer orange as the header color but I've gotten used to the gray.

**Comment by tibbi** [comment]
Ill make the statusbar pure black too when the "Black background and status bar at fullscreen media" setting is enabled
