### ISSUE TITLE
Make settings titles bold/bigger

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#1780]
It would make things easier to see, specially in the black theme.
![Screenshot_20200309-023747_Galeria](https://user-images.githubusercontent.com/29208110/76185900-6501a880-61af-11ea-84ec-778a30e8ab8e.png)

**Comment by alekksander** [comment]
Yes please.

**Comment by tibbi** [comment]
it has been redesigned already, will be added in the next app version
