### ISSUE TITLE
sort by date taken not working correctly

### ISSUE THREAD

**Issue by m7-41** [SimpleMobileTools/Simple-Gallery#1782]
Hi,
I've pictures from two different mobiles in my gallery and have the list sorted by date taken descending, which does not sort these pictures correctly.
I'm attaching two of them as examples (hopefully the properties stay intact while uploading...)
kr
(IMG_20200215_105705 is shown before the other one) 
![IMG_20200215_105705](https://user-images.githubusercontent.com/58701474/76294422-1c331800-62b3-11ea-913f-2d81c2139bbf.jpg)
![20200215_115453](https://user-images.githubusercontent.com/58701474/76294481-37058c80-62b3-11ea-8fa6-c06d0bb7e92d.jpg)

**Comment by tibbi** [comment]
what app version do you have? Try selecting the wrong file thumbnails and use Menu - Fix Date Taken values.

**Comment by duesseldorferjung** [comment]
Good Day. I was experiencing the same issues and the solution suggested by @tibbi is working for batches of let's say 100 pictures. As I have around 7000 it would be great if select all and Fix Date would work. Anyway I can help with testing?

**Comment by tibbi** [comment]
it should work, Ill close this as he is not responding. Thanks

**Comment by duesseldorferjung** [comment]
the select all is not working

**Comment by tibbi** [comment]
whats not working there? Isnt it just slow?
