### ISSUE TITLE
Recycle bin location

### ISSUE THREAD

**Issue by Jakeler** [SimpleMobileTools/Simple-Gallery#1786]
The recycle bin is really useful feature, but currently the it is located in the app data, which is problematic for various reasons:
For example on my phone the microSD card is larger than the internal storage, so i usually save the pictures/video files on the sd card. If many or big video files are moved to trash the internal storage has no space left. In addition it always requires a real copy operation, which can be slow and causes unnecessary write load. 
I think it would be better to stay on the same filesystem for this implementation, so the move is more efficient (effectively just renaming the path) and it would also prevent out of space conditions.

An idea is to create a `.trash` folder directly under the path where the file originally was and move it in there. The trash folders could be marked with `.nomedia` so other apps don't show them. This would also make the trash more obvious and manageable in a file manager.

Please let me know what you think and if you see any disadvantages with this approach @tibbi. I would be happy to look into changing it and possibly make a pull request, if you willing to merge it.

**Comment by tibbi** [comment]
There are some drastic file handling related changes coming within a few months to Android, I basically wont be access files by their real path. The best way to store such files is, and especially will be, within the apps internal storage. So I dont plan moving it anywhere else.

**Comment by Jakeler** [comment]
Even if you target Android 11 it is still possible to get broad storage access with `MANAGE_EXTERNAL_STORAGE` which enables access to `MediaStore.Files` and raw paths. 
Or are you planning to not ask for additional permissions and use strictly `MediaStore.Images`? Then users have to grant write/trash/delete permission for specific files, so the trash is then managed by the system anyway.
After reading more through the storage API docs I still strongly disagree with the "best way is internal storage". There is stated:
> Internal storage has limited space for app-specific data. Use other types of storage if you need to save a substantial amount of data.

So I would not consider dumping possibly GBs of media there as proper use... Another problem that i have encounterd with it that it blows up the backup size and  there is no reliable way to split that from app settings, databases etc. that are usually saved there.
Please switch at least to app specific external storage, usually in `/storage/emulated/0/Android/data/appID/...` (but can be also on a sd card), that would already fix most of the mentioned problems and it works absolutely fine with scoped storage.

Sources:
https://developer.android.com/training/data-storage
https://developer.android.com/preview/privacy/storage

**Comment by floppyD** [comment]
Maybe just append a ".trash_" before the file name?

**Comment by tibbi** [comment]
the MANAGE_EXTERNAL_STORAGE will be available only for file managers, I dont think a gallery will receive the permission for using it.. Not even my Contacts app received permission for accessing the call log... If you dont have enough space on your internal storage, just move the app itself on the SD card too and the trashbin will be there too.

**Comment by Jakeler** [comment]
Moving apps requires adoptable storage, which makes it impossible to read the card from other devices... i don't like that. And then it is still slow and the makes the app backups big...
I don't get why you are against moving it to other locations, app specific "external" storage is the better choice for large amounts of data and works just like the "internal" pedant, if you are concerned about permissions.
On old devices this was especially important, in a fixed size data partition this would have immediately caused problems for many users. No other app (that I know of) does this.


> Maybe just append a ".trash_" before the file name?

Would be also fine it think.

**Comment by tibbi** [comment]
because as I said, I wont be able to access the external storage within a couple months. I wont be working on a new solution just to delete it in a few weeks.

**Comment by Jakeler** [comment]
Not true, as I said, you will be able to access external **app specific** storage. Just read the documentation:
> apps that target Android 10 (API level 29) and higher are given scoped access into external storage, or scoped storage, by default. Such apps have access only to the app-specific directory on external storage, as well as specific types of media that the app has created.

Or try it out without `requestLegacyExternalStorage`.
