### ISSUE TITLE
Deleting files from recycle bin does actually not delete them

### ISSUE THREAD

**Issue by Jakeler** [SimpleMobileTools/Simple-Gallery#1787]
After normal deletion (with recycle bin enabled) the files the files are in the app data under:
``` 
/data/data/com.simplemobiletools.gallery.pro/files/storage/emulated/0/DCIM/...
```
and visible in the app under the recycle bin tile, so far so good.

If i open it there and tap again on delete they end up in in:
```
/data/data/com.simplemobiletools.gallery.pro/files/data/user/0/com.simplemobiletools.gallery.pro/files/storage/emulated/0/DCIM/...
```
and are not visible anymore in the app, but are still there and consume space, which is really unexpected. 
Only emptying the whole recycle bin does actually delete the files. 

App Version: 6.13.4 (on Android 10)

**Comment by tibbi** [comment]
it works just fine to me, so it might be something device specific. Havent you just checked the bins place too early? Deleting can take some time. Also more reliable than going to the folder itself could be checking the app size in your device settings, thats what matters to me.

**Comment by Jakeler** [comment]
No, in fact I have just noticed it a few days later because the size was big without anything visible in the bin. Also it creates these /data/data/... subfolders in the app data and moves the files into them, they are not normally there. 
I am able to reproduce it in an emulator, apparently has something to do with the "open with" dialog that always shows up when opening a video in the gallery, so i selected this gallery and choose "Always". Then opened the file from the bin and hit delete, the confirmation dialog asks even if it should be moved to the bin, so it does this not recognize anymore that it is already in the bin... 
It works fine though when selecting/deleting it on the bin overview, without opening.

**Comment by tibbi** [comment]
do you have a rooted device that you are browsing through data/data? If you do, couldnt rooting break something?

**Comment by Jakeler** [comment]
Yes it is rooted, but it was already broken before i looked into it with adb.
Try a video, open it from the bin and hit delete again. You still can't reproduce it?

**Comment by tibbi** [comment]
that must be some device specific issue, if still valid

**Comment by licaon-kter** [comment]
Can this be reopened?

Seening this for a long time on F-Droid 6.25.5 (and older). AOSP11, Calyx11, Sony9, Pixel10 (none have root so I can't confirm what's using the space) etc.

Basically the app data size grows continously and I need to clean app data (lose recycled items :( ) to recover the space.

**Comment by tibbi** [comment]
are you sure it is caused by some files in the recycle bin? Have you found those files by browsing a rooted device or so?

**Comment by licaon-kter** [comment]
As I said I have no root.

Whan else could take that space exactly? 

Eg. If thumbnails why not store that in cache so we can clean it up?

**Comment by tibbi** [comment]
thumbnails are already in cache. Would be good to find a way of reproducing the issue though, or at least ensuring that the trashbin is really causing it.
