### ISSUE TITLE
Write star/favorite rating into the file

### ISSUE THREAD

**Issue by jakommo** [SimpleMobileTools/Simple-Gallery#1796]
I'm creating this issue as a fork of https://github.com/SimpleMobileTools/Simple-Gallery/issues/282 because it's only about one part of what's requested in https://github.com/SimpleMobileTools/Simple-Gallery/issues/282 and I think it would be more easy to implement this than adding a complete Exif editor. 

It would be nice if the star/favourite rating would be stored/written into the image/video file itself, so that it does not get lost when copying the files to a different device or reinstalling.
Preferably it would be done in a way so that this information could be retrieved in other applications as well, i.e. in shotwell/digiKam  om the PC.

This would also help to differentiate Simple-Gallery from other Gallery apps, at least I couldn't find any Android Gallery app that does store the rating in file.

**Comment by tibbi** [comment]
there is no official EXIF field for favoriting a file so I dont want to create a custom one. That wouldnt be recognized by any other app. There is a system-wide official support for favorite media files coming with Android 11, I will use that one.

**Comment by jakommo** [comment]
ok I see. Just out of curiosity, where is the information currently stored? And is this something I as a user could extract somehow?

**Comment by tibbi** [comment]
not sure what information you mean now. EXIF values are in the file itself, Favoriting at the apps own database. Maybe you can access it with some rooted device, not in a casual way.

**Comment by jakommo** [comment]
Thanks, I meant the favourites in the database.

**Comment by spmp** [comment]
> there is no official EXIF field for favoriting a file so I dont want to create a custom one. That wouldnt be recognized by any other app. There is a system-wide official support for favorite media files coming with Android 11, I will use that one.

Surely you can use the 0-5 'Rating' field as 1 star (or any number of stars). I'd love to be able to rate them, but even being able to favourite (1 star) an image is such a massive win/killer feature.

I'd love this for Digikam import as with OP.

**Comment by spmp** [comment]
Any chance of re-opening and addressing this?
