### ISSUE TITLE
"Use app in English" works only partially

### ISSUE THREAD

**Issue by uli-on** [SimpleMobileTools/Simple-Gallery#1800]
Android 6.0.1 (Moto G4), Gallery 6.14.0 Pro

The part working is the coloured top area, where "Gallery", "Settings", "Customize colors", " Included folders" etc is displayed, so at first sight all seem fine. But menus, window contents, dialogs remain in the system's language.

**Comment by tibbi** [comment]
try restarting the app, murder it by removing from Recents too

**Comment by uli-on** [comment]
Thanks for the hint, but no effect, unfortunately.

**Comment by tibbi** [comment]
try it in the free version too please. You might have some other generic glitch, where the font size setting in some apps doesnt work either. It hasnt been there in the free versions yet.

**Comment by uli-on** [comment]
Hm, I've no font size setting (still on Pro version). Does that answer your question sufficiently, already?

**Comment by tibbi** [comment]
no, the font setting is available only in other apps, not in the gallery. It was a bit offtopic mentioning from me, I wanted to tell that it is a glitch affecting all apps, not just the gallery. Test the free gallery version please.

**Comment by tibbi** [comment]
Alright, dont need anything else, it is good enough for now. Sadly it that given system issue, not much I can do about it for now. It has to be fixed in Android. Thanks

**Comment by uli-on** [comment]
I couldn't use my backup apk for restoring, I got a system message "could not install", I've had to install v6.14.0 from G store. Is that still a fully functional pro version, without nagging screens, demo period, etc?

**Comment by tibbi** [comment]
you mean from Google Play? Sure, it is the full version. Pro versions are almost the same everywhere, the only difference is that the Google Play version contains an advanced photo editor which is not open source and thus not accepted on f-droid and such sources.

**Comment by uli-on** [comment]
I was perplexed cause I've downloaded my backuped apk from G Play, but it behaved as if I wanted to update it with an apk from F-Droid.

**Comment by tibbi** [comment]
language picker has been added already on Android 13+
