### ISSUE TITLE
Restoring reclycle bin problems

### ISSUE THREAD

**Issue by cmh2** [SimpleMobileTools/Simple-Gallery#1806]
I'm using Simple Gallery in my phone.
This morning I took a photo. Then I wanted to delete it and I did it with Simple Gallery. I made a mistake and deleted the camera folder thinking it was just the photo. I didn't know that could be possible, I thought I deleted the photo.
Seeing that all the photos in the camera folder were in the trash, I restored the deleted items.
Now there is nothing in the camera folder and there is no trash.
What I can do? Is it possible to get it back?

**Comment by tibbi** [comment]
what app version are you using? Check https://photos.google.com/ if there is no backup. There is even a red warning at deleting folders, I cannot add more warnings.

**Comment by cmh2** [comment]
The app version is v 5.2.0.
There was no red warning, just one question as always. I thought I deleted the photo.

**Comment by tibbi** [comment]
Right, that is the old no longer developed version. If you have no backup on Google Photos, try some app like DiskDigger for recovering deleted files. Also upgrade to the Pro version at https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro , it has many trashbin and deleting improvements too.

**Comment by cmh2** [comment]
The app version is v 5.2.0.
There was no red warning, just one question as always. I thought I deleted the photo.

**Comment by cmh2** [comment]
The problem was not to erase, but the recycle bin restore failed and deleted the files and the recycle bin itself.
The program crashed and you suggest updating to the paid version. No thanks, I don't trust your software nor your support.
I'm sorry I chose your app. I will uninstall it and try not to use anything of yours.
Thanks for your answer.
