### ISSUE TITLE
PIN/pattern/password protection for hidden folders

### ISSUE THREAD

**Issue by touzainanboku** [SimpleMobileTools/Simple-Gallery#181]
Would be greatly appreciated 🙏

**Comment by manuelpaulo** [comment]
Indeed +1  :)

**Comment by jerryn70** [comment]
+1

**Comment by pizzadude** [comment]
+1

**Comment by AboShanab** [comment]
+1 also Fingerprint, It's important feature.

**Comment by tibbi** [comment]
i was researching encrypting folders, but seems like its a lot more difficult than I thought. Maybe I will just protect toggling the hidden folder visibility for now.

**Comment by touzainanboku** [comment]
Yeah that's what I'm requesting. I don't want to be forced into using encryption.

**Comment by tibbi** [comment]
initially I wanted to make it in a way that if you encrypt a folder in the Simple Gallery, other apps wont be able to open it either. Thats not going to happen anytime soon tho so Ill just pin protect displaying the hidden folders for now.

**Comment by manuelpaulo** [comment]
Using the .nomedia trick?

**Comment by tibbi** [comment]
what? O.o thats just the standard way of hiding folders from media apps in Android, its not protected in any way whatsoever.

**Comment by manuelpaulo** [comment]
So, you'll use private app storage? You do realize any rooted Android will be able to see the files?

**Comment by tibbi** [comment]
it will be just a protection for toggling hidden file visibility inside this app, nothing outside of it. It can be used for avoiding children viewing hidden files or so. People who want security have password on the device itself, they dont just hide a folder inside an app.

**Comment by manuelpaulo** [comment]
Sorry to say but it's useless then.

**Comment by tibbi** [comment]
Well, thats what this issue is about. Encrypting folders is something totally different.

**Comment by touzainanboku** [comment]
@manuelpaulo it's useful for me. And that's this issue is requesting anyway.

**Comment by AboShanab** [comment]
@manuelpaulo it's useful for me too, Just go ahead.

**Comment by tibbi** [comment]
Added pattern/pin protection for showing hidden items. Ill leave it open for adding fingerprint in the future, I just dont have any device for developing it.

**Comment by tibbi** [comment]
so Ive bought a device for it, will be added in the next version :)
