### ISSUE TITLE
Why "proprietary release" in apk file name?

### ISSUE THREAD

**Issue by KPSH7AmcSRcfCqdJ** [SimpleMobileTools/Simple-Gallery#1813]
https://github.com/SimpleMobileTools/Simple-Gallery/releases

Why do all apk file names (since version 6.13.0) have this name at the end "proprietary release"?

**Comment by tibbi** [comment]
Because that app version contains a photo editor which is not open source. Websites like f-droid contain another app flavor, "foss" instead of "proprietary". The "foss" app version has the old open source photo editor which is a lot more basic than the proprietary one which is on Google Play.

**Comment by KPSH7AmcSRcfCqdJ** [comment]
Can you change it or make it better?

**Comment by tibbi** [comment]
change what?

**Comment by KPSH7AmcSRcfCqdJ** [comment]
> change what?

photo editor

**Comment by tibbi** [comment]
the proprietary one will keep improving, I dont plan working on the old one
