### ISSUE TITLE
Explain in readme how photos are "protected"

### ISSUE THREAD

**Issue by BrendanBall** [SimpleMobileTools/Simple-Gallery#1820]
The readme states: 
• Protect your photos & videos with a pattern, pin or fingerprint
• Use pin, pattern & fingerprint to protect the app launch or specific functions too

I expected protect to mean encrypt, however it's clear photos aren't encrypted from this [issue 1045](https://github.com/SimpleMobileTools/Simple-Gallery/issues/1045).

So if photos aren't encrypted then it sounds like fingerprint/pin are just smoke and mirrors and photos aren't actually protected. I am not that familiar with exactly how android storage per app works and whether other apps can access its storage. I think it would be great to explain to users how photos are currently "protected" and what the pin/fingerprint actually does. 

I'm actually looking for an app that actually encrypts the photos but I don't trust closed source apps for this. Call me a conspiracy theorist, but you're basically telling the app developer you don't want these photos shared and have no way of validating your blind trust in some random app.

I might even be able to contribute to implementing the encryption if this seems like the best app to work off of.

**Comment by tibbi** [comment]
as soon as you try locking an individual folder there is a warning that the locking works in-app only, it is not supposed to replace real encryption
