### ISSUE TITLE
Allow root access

### ISSUE THREAD

**Issue by Lordcorvin1** [SimpleMobileTools/Simple-Gallery#1821]
So I'm using encfs to mount encrypted folder outside /storage/ to view files. Specifically in /mnt/ 
I found no gallery app that is capable in viewing the data as no root access permission is ever asked.
Is it possible to enable this in feature releases?

**Comment by tibbi** [comment]
no, it isnt on the roadmap for the gallery

**Comment by Mar2ck** [comment]
@Lordcorvin1 Btw you can access mounted volumes using non-root apps by setting your selinux to permissive. Encfs works with simple gallery this way
