### ISSUE TITLE
Allow changing the order of bottom action buttons

### ISSUE THREAD

**Issue by Charles-770** [SimpleMobileTools/Simple-Gallery#1822]
3 features requests:
* 1. When you reorganize the Action bar, you should be able to modify the position of the buttons.

 Similarly, we should be able to choose the 2 buttons appearing at the top, and choose their layout.

* 2. It would be practical to be able to rename (edit the name of) a file by clicking on its name at the top of the screen.

* 3. In the Editor, you should add the possibility of annotating the image with a line, arrows, frames or smileys.

**Comment by tibbi** [comment]
I will keep it here for the first point, I dont plan adding the 2nd and 3rd. But report 1 thing per issue in the future.

**Comment by Charles-770** [comment]
OK
Thanks. 
IMHO, it would be useful to be able to properly annotate an image (of text) by adding an underline, a frame or an arrow. 

Sincerely 
Simon

**Comment by tibbi** [comment]
I dont plan adding reordering, sounds too advanced
