### ISSUE TITLE
Moving files to the recycle bin overwrites files with the same name without confirmation

### ISSUE THREAD

**Issue by Instagit** [SimpleMobileTools/Simple-Gallery#1826]
1. Move a photo to the recycle bin
2. Make a new photo, which has the same file name as the delete one, because the phone goes by the name of the last file in the photo directory
3. Move the new photo to the recycle bin

Result: The first photo is gone, overwritten by the last deleted photo.

**Comment by tibbi** [comment]
makes sense to me, I dont really plan changing it
