### ISSUE TITLE
Run At Startup permission is unclear

### ISSUE THREAD

**Issue by Wilker-a** [SimpleMobileTools/Simple-Gallery#1827]
hi \^\^

this is more of a question.  
i have been using this program for a while and so far the permissions that it asked seemed reasonable so far, but in the recent update it now demands a permission to run at the system startup and i don't know why. i made sure to read the recent changelogs so i could know why it would be necessary, but i coudn't find a clear info on that.

i could have missed something, so i'm just writing this question so it could be clarified.  
thank you for the help \^\^

**Comment by tibbi** [comment]
ye, the first SD card file scanning after a restart is usually really slow. So with the new way I try scanning the files right after restarting first, so by the time the user launches the app manually it will be quicker already. Ill add it at the Privacy Policy, maybe someone reads it there.

**Comment by Wilker-a** [comment]
i see it now. thank you \^\^
