### ISSUE TITLE
Auto-purge trash after x days?

### ISSUE THREAD

**Issue by KopfKrieg** [SimpleMobileTools/Simple-Gallery#1837]
It would be nice if the trash could be purged in a regular interval. E.g. files that are longer than 14 days in trash get removed automatically.

I'd probably use a background job each time the app is in foreground to remove files/folders from the trash that are older than x days.

**Comment by tibbi** [comment]
trashbin files are already deleted after 30 days, it just isnt customizable yet. That is a different issue though.
