### ISSUE TITLE
Favorite Tag readable for Nextcloud

### ISSUE THREAD

**Issue by duesseldorferjung** [SimpleMobileTools/Simple-Gallery#1839]
Really enjoying this great app! As I am using Nextcloud to synch my pictures I am wondering if the information favourite which is set in the Gallery app can be transferred somehow to Nextcloud.

**Comment by tibbi** [comment]
no, it is stored in the app only. Android 11 already has a system-wide favorite item marking, but that probably wont sync to anything either.
