### ISSUE TITLE
[feature request] add a button at top to allow group by taken date (daily/monthly)

### ISSUE THREAD

**Issue by snakejoe** [SimpleMobileTools/Simple-Gallery#1844]
Currently we need to open the menu to set this option. Could it be 

1. After choose this option: group by taken date , show a button at top to allow switch between daily and monthly

2. Like Google photo, change to monthly when zoom out to certain level, i.e. 6 columns. Change to daily when zoom in

Thanks

**Comment by tibbi** [comment]
I want to avoid such redundant buttons, you dont toggle between them often
