### ISSUE TITLE
impossible to compile in Linux

### ISSUE THREAD

**Issue by eremitein** [SimpleMobileTools/Simple-Gallery#1845]
hello

any suggestions why i have this errors?

https://del.dog/lohanyravy.txt

logs from build folder [manifest-merger-proprietary-debug-report.txt](https://github.com/SimpleMobileTools/Simple-Gallery/files/4692278/manifest-merger-proprietary-debug-report.txt)

**Comment by tibbi** [comment]
just compile the foss app flavor then
