### ISSUE TITLE
copycat issue??

### ISSUE THREAD

**Issue by biladina** [SimpleMobileTools/Simple-Gallery#1846]
https://play.google.com/store/apps/details?id=com.photogallery.photography.galleryapp

I found this app from [issue](https://github.com/zhanghai/MaterialFiles/issues/291) on Zhang material files apps, its look like [they](https://play.google.com/store/apps/dev?id=4847281291926075694) using this code to build their own app with closed source and contain ads..

if this is copycat violation, help developer to report these apps in Play store with "Flag as inappropriate", or [submit a report form](https://support.google.com/googleplay/android-developer/contact/takedown) online.

**Comment by tibbi** [comment]
there are tons of clones out there, I reported many of them. Google doesnt care as it is an open source project. The best thing you can do is giving some bad review mentioning the original authors. Thanks
