### ISSUE TITLE
Adding comment on a picture (in edit mode)

### ISSUE THREAD

**Issue by AnastasiaLovelace** [SimpleMobileTools/Simple-Gallery#1848]
Drawing on a picture is cool but sometime I'de like to add a comment to keep a "review" or to name a plant for exemple (just like below). 
![IMG_20190824_114805](https://user-images.githubusercontent.com/34100220/83283142-03177480-a1db-11ea-9296-9fd66eeb9821.jpg)
I think adding a text on a photo can be usefull (:

**Comment by tibbi** [comment]
you can already do that in the Pro app versions editor

**Comment by AnastasiaLovelace** [comment]
Sorry, I thought I had the pro version because it's name that way on fdroid but apparently not 
My bad and thanks for the quick respond !

**Comment by tibbi** [comment]
f-droids editor doesnt have text writing, but the version from Google Play does. That is the only difference, the Google Plays editor is not open source so it isnt in the f-droid version.
