### ISSUE TITLE
Images don't open

### ISSUE THREAD

**Issue by kinclma1** [SimpleMobileTools/Simple-Gallery#185]
For a while now, opening an image shows nothing, thumbnails and editing are as expected.
Device: Huawei Y300, Android 4.1.1

**Comment by tibbi** [comment]
Is it working fine already? Some things have been improved.

**Comment by kinclma1** [comment]
Unfortunately not.

**Comment by tibbi** [comment]
hm, which app version are you using? Are the photos on an SD card?

**Comment by kinclma1** [comment]
2.7.3, just updated. All photos are on the SD card, which is however set as the default storage (most apps recognize it as the internal storage). I'll try to copy something to the phone memory.

**Comment by tibbi** [comment]
SD cards are not handled properly on Android 4.x, images should still be displayed tho.

**Comment by kinclma1** [comment]
But it worked something like 2 months ago before the big .nomedia changes. And the weird thing is that when I select Edit from the context menu, the photo shows just fine.

**Comment by tibbi** [comment]
If you can, it would be good to determine in which version did it break, because I dont really know what could cause it. All releases lately are listed also on https://github.com/SimpleMobileTools/Simple-Gallery/releases . You have to allow installing apps from unknown sources in the security settings of your device, then uninstall the current version you have and download the app-release.apk of the particular release on your mobile and click it. Theres some release notes and dates too, telling which release broke it would help a lot. Thanks

**Comment by kinclma1** [comment]
Version 2.3.9 is the first broken.

**Comment by tibbi** [comment]
nice, thanks. I will take a look at it later. I dont want to update the app now anyway, people are getting upset because of the frequent updating :)

**Comment by kinclma1** [comment]
Thanks

**Comment by ngdias** [comment]
I can confirm this issue also happens in my phone, a Samsung GT-I8190N.

**Comment by jrd** [comment]
Exact same thing as kinclma1 for me FYI

**Comment by tibbi** [comment]
Hey, can you test this version? You will have to delete the current version and allow installing apps from unknown sources in the security settings of your device. 
Please rename the attachment "app-release.zip" to "app-release.apk", github doesnt allow uploading apk files so I had to rename it. The easiest way you can test this version is downloading the attachment, renaming to app-release.apk and sending it to your email. Downloading and running the email attachment from your mobile device should then be straightforward.

[app-release.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/907523/app-release.zip

**Comment by kinclma1** [comment]
Nothing changed. Regarding fullscreen, it's not possible, because it doesn't react to anything inside the grey area where the image is supposed to be.

**Comment by tibbi** [comment]
Do you see the image title at the actionbar? Is it a png or a jpg file? Can you swipe?

**Comment by kinclma1** [comment]
I can see the title with the rotation button an the delete button. It is a jpeg, swiping doesn't work.

**Comment by tibbi** [comment]
weird... so no image opens properly?

**Comment by kinclma1** [comment]
exactly

**Comment by tibbi** [comment]
Check this version please, what messages do you see at opening fullscreen image?
Does opening videos work well?

[app-release.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/907579/app-release.zip)

**Comment by kinclma1** [comment]
It says `init     ` and `got <number> images` even for videos

**Comment by tibbi** [comment]
ah, looks like a stupid typo at a crashfix, can you try this one? Seems like it was broken only for android 4.1
[app-release.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/907597/app-release.zip)

**Comment by kinclma1** [comment]
It works! Thank you. Another annoyance appeared, but that's for another ticket.

**Comment by tibbi** [comment]
Great, thanks for the help. That was a pretty primitive issue, but it happens..
