### ISSUE TITLE
Simple Gallery becomes default gallery in Open Camera

### ISSUE THREAD

**Issue by bovergaauw** [SimpleMobileTools/Simple-Gallery#1851]
Hi,
I don't know whether this is a problem with Simple Gallery or Open Camera (https://opencamera.org.uk/ and https://sourceforge.net/projects/opencamera/), but as soon as I install Simple Gallery it is used as Open Camera's default viewer rather than the system's default Gallery app. According to Open Camera's documentation, it uses the system's Gallery app.
I will submit this report also to the Open Camera bug reporting system.

**Comment by tibbi** [comment]
it cannot be set to system default automatically. Once you install a new gallery you are asked what gallery app you want to use for handling the given intent. Some app is automatically launched only if it is the only app capable of handling the given intent, or if you made the given app the default one.

**Comment by bovergaauw** [comment]
Hi @tibbi,
Just for your information, here's what I did following your answer:
- I uninstalled Simple Gallery;
- I checked that Open Camera used the default Gallery again;
- I restarted my mobile (Samsung Galaxy S9 running Android 10);
- I checked that Open Camera still used the default Gallery;
- I reinstalled Simple Gallery from F-Droid again;
- I opened Open Camera, and checked which app was used to open the thumbnail, and Simple Gallery opened;
- I checked the value of Simple Gallery's app setting for "Set as default", which was "None set as default".
I'll update this issue when the author(s) of Open Camera provide useful information.

**Comment by tibbi** [comment]
well it is indeed some special handling in their app then, it definitely isnt any issue in Simple Gallery

**Comment by bovergaauw** [comment]
Hi @tibbi,
Thanks for your rapid reactions and help 🙏👍. And of course for the great apps.
