### ISSUE TITLE
When deleting, cannot navigate to directory to allow permissions

### ISSUE THREAD

**Issue by plaidpants** [SimpleMobileTools/Simple-Gallery#1853]
On my S9+ when I select an image to delete from a custom added folder on the SD card the internal downloads directory is displayed but there is no way to navigate to the folder to allow permissions. It can show and hide the internal storage but cannot access the SD card. The folder has .nosearch and .nomedia in the directory if that makes a difference. The SW is up to date running the Android 10, May 1, 2020 release. I suspect an incorrect file navigation type is used.

**Comment by tibbi** [comment]
you just have to select the top SD card folder on that screen, do not navigate into the specific folder. It is needed only at the first SD card file operation.

**Comment by plaidpants** [comment]
![Screenshot_20200605-074757_Files 1](https://user-images.githubusercontent.com/8979271/83878207-63d60e00-a701-11ea-933b-0cf0819886e0.jpg)
![Screenshot_20200605-074810_Files 1](https://user-images.githubusercontent.com/8979271/83878242-72bcc080-a701-11ea-8464-784b0010f308.jpg)
![Screenshot_20200605-074817_Files 1](https://user-images.githubusercontent.com/8979271/83878263-7e0fec00-a701-11ea-82d1-b18393402cbe.jpg)

Here are some screenshots of what is available from the permission selection, as you can see none of the options allow me to navigate to the SD card, I can only see the internal download directory.

**Comment by tibbi** [comment]
does it work well in any other downloaded apps? I mean really downloaded ones, not preinstalled ones.

**Comment by plaidpants** [comment]
I've not had any trouble with other apps downloaded or otherwise.

**Comment by plaidpants** [comment]
Your file manager app appears to have the same issue, trying to delete an arbitrary file.

**Comment by plaidpants** [comment]
Seems to work OK for directories on the internal storage. The .nomedia and .nosearch presence or lack of presence do not seem to make a difference.

**Comment by plaidpants** [comment]
Does this help? https://android.stackexchange.com/questions/96500/how-to-allow-apps-to-delete-sd-card-content

**Comment by plaidpants** [comment]
I think I found the problem com.android.externalstorage package was disabled on my device, re-enabling this allows things to work as expected. I think this ticket can be closed.

**Comment by tibbi** [comment]
right, messing with such system things usually breaks stuff :) Thanks
