### ISSUE TITLE
Feature request: show location when grouping by date

### ISSUE THREAD

**Issue by bellegarde-c** [SimpleMobileTools/Simple-Gallery#1855]
Oneplus Gallery app has a cool feature, it groups photos by date and shows location next to date:

https://cdn.guidingtech.com/imager/assets/213856/google-photos-vs-oneplus-gallery-8_4d470f76dc99e18ad75087b1b8410ea9.jpg?1547448956

Should be awesome to have such feature in Simple Gallery.

I can sponsor this feature.

**Comment by tibbi** [comment]
it cannot be done, the app has no internet access

**Comment by bellegarde-c** [comment]
By design ?

**Comment by tibbi** [comment]
sure, that is one of its biggest benefits and unique features
