### ISSUE TITLE
[Feature request] Enable reverse swipe direction

### ISSUE THREAD

**Issue by ungutknut** [SimpleMobileTools/Simple-Gallery#1856]
When opening pictures from a file manager (total commander in my case) which is set to alphabetical order, swiping in simple gallery happens to be reversed. 

Is there a workaround for this? If not I'd like to request a feature to let the user decide in which direction to swipe.

**Comment by tibbi** [comment]
the gallery cannot know what sorting you used in some file manager. There is a Menu -> Sort by button at the top menu in the gallery, you can toggle ascending/descending to flip the order.
