### ISSUE TITLE
Full screen image loading

### ISSUE THREAD

**Issue by FPSUsername** [SimpleMobileTools/Simple-Gallery#1858]
### First issue
The full screen image viewer keeps showing a cached version.

Steps to reproduce:

- Open an image
- Edit with simple gallery
- Crop the image
- Save the image under the same name (replacing the original)
- The image that you see is the same as the unedited version (however, it is cropped if you edit the image again or copy it to another location).

### Second issue
First opened image is shown again after editing another image without leaving the full screen viewer.

Steps to reproduce:
- Open an image in a folder with multiple images
- Scroll a couple of images further
- Edit the image that's now open
- Save the image under the same name (replacing the original)
- The app now shows the first image that you opened in step 1 (scroll further to find your edited image)

App version: 6.15.0

**Comment by tibbi** [comment]
will be fixed in 6.15.1
