### ISSUE TITLE
Critical: After renaming several images at once, files are missing

### ISSUE THREAD

**Issue by impeira** [SimpleMobileTools/Simple-Gallery#1859]
I renamed multiple files at once with following pattern: "Man at Work 10.06.20 #%i" and the images are gone. Reproduceable.

**Comment by tibbi** [comment]
you cannot see them in a file manager either? Or just hidden in the gallery? What app version are you using? Are those files on an SD card, or internal storage?

**Comment by impeira** [comment]
The files aren't hidden nor in another folder. Immediatelly after confirming the rename action the files are gone.
APP Version: 6.15.0 Pro (Android 9, Fairphone3).
Internal Storage.

**Comment by tibbi** [comment]
so batch renaming with some other patterns work well? Can you maybe play around with it to see which part is causing the issues?

**Comment by impeira** [comment]
I hadn't any problems before. I will try it again later.
I suspect the #-sign and maybe space character.

**Comment by impeira** [comment]
Ok I got some of it.
If I use one period in the pattern (e.g. "a.a" without the ".jpg") than the filetype (".jpg") does not get attached automaticly. And therefore the Gallery is ignoring these files because of the missing filetype in the name.
But if I don't use periods at all the filetype will be attached. This seems to be inconsistent.

BUT when I use more than one period on any position (e.g. "bb..bb") without specifying the filetype I can't even find the file in the filemanager.

**Comment by tibbi** [comment]
ok Ill try reproducing it like that. Thanks
