### ISSUE TITLE
Copy cat on Play Store

### ISSUE THREAD

**Issue by uli-on** [SimpleMobileTools/Simple-Gallery#1861]
Following a warning from another F-Droid coder, I visited the Play Store and found on the page by Appbox Apps a copy of Simple Gallery, version from January '20, with adverisings, the editor part removed. I reported that app as inappropriate, but as I also read that only the original author can ask Google to take a copied app down, I'm posting here.

**Comment by tibbi** [comment]
I reported tons of apps already, Google doesnt care. Just give them a bad review mentioning the original author. Thanks
