### ISSUE TITLE
Retain favorites when upgrading to pro

### ISSUE THREAD

**Issue by wepanx** [SimpleMobileTools/Simple-Gallery#1862]
Hi,

i managed to import my favorites from regular into pro version (adb backup of old and pro app data, copy db directory, restore app data). When starting the pro version, I can see my favorites for some seconds. After that, it seems that the image db is rebuilt and all my favorites are gone again.

Is there anything I can do to retain my favorite images / let the pro version not delete my favorite marks?

**Comment by tibbi** [comment]
migration currently isnt possible, they are stored in a whole different way

**Comment by wepanx** [comment]
Thanks for this quick answer!

If they're stored so differently, why is the pro app able to load the old db and show all favorites in the first place? ... is it planned to retain the favorite flag or migrate whole db if an old db has successfully been loaded?

**Comment by tibbi** [comment]
no migrating is on the roadmap

**Comment by wepanx** [comment]
ok.... if anyone else is interested, I did a manual migration by adb backup old and pro app, extracting the sqlite databases, running the following sqlite commands on the pro database and repacking + restoring the modified adb backup.

`ATTACH '/PATH/TO/apps/com.simplemobiletools.gallery/db/gallery.db' AS db2;
UPDATE main.media
SET is_favorite = (SELECT is_favorite FROM db2.media WHERE main.media.full_path = db2.media.full_path)
WHERE EXISTS(SELECT 1 FROM db2.media WHERE main.media.full_path = db2.media.full_path);
INSERT into main.favorites (full_path, filename, parent_path) select full_path, filename, parent_path from media where is_favorite = 1;`
