### ISSUE TITLE
[Feature Request] enhancements for photo editor

### ISSUE THREAD

**Issue by takase1121** [SimpleMobileTools/Simple-Gallery#1863]
I replaced my default gallery with this app and is very satisfied. However, the photo editor is kind of sub-par in my opinion. Here is a few suggestions. 

1. Image transforms should be chainable (eg. Draw after cropping). Currently you would have to save to another file then edit that file instead. There should be an "Apply transform" button that allow u to apply the transform so that you can proceed to draw or crop or something.

2. Undo stack should be global. AFAIK the undo is only available to draw function only. If (1) is implemented, (2) would be a nice complementary feature to have.

3. Color transforms. Probably adjusting the brightness, contrast, hue, saturation, etc?

4. Basic shapes and arrows _because my fat fingers can't draw them nicely_.

**Comment by tibbi** [comment]
there is a lot more advanced editor available at the Google Play version, get it from https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro . F-droid contains a really basic one, but I dont plan working on that.

**Comment by maximbaz** [comment]
Hi @tibbi, is it possible to get a more advanced editor in the F-Droid app? I am using a phone without Google services, so it's not really possible to install Google Play version. This app looks like the best replacement for default Gallery if it could have a better editing, like described in the first message.

**Comment by tibbi** [comment]
it is not open source, so sadly not. You can get the Google Play version from github releases at https://github.com/SimpleMobileTools/Simple-Gallery/releases , but you wont be receiving updates

**Comment by AntoninCurtit** [comment]
Hi !
I was wondering why F-Droid didn't had that "advanced" editor promised on the screenshot, got it why. (Seems like there's none who's FOSS on Android)
Would you agree to have a mention about in the readme ?

Thanks !
