### ISSUE TITLE
Add H-Scroll View of bottom_actions.xml.

### ISSUE THREAD

**Issue by BeyondSpace609520** [SimpleMobileTools/Simple-Gallery#1866]
It's hard to control bottom actions buttons when i add all buttons in bottom.
At the moment, app can show 4 or 10 buttons in bottom when on portrait or landscape.
But total is 14 buttons, so please add horizontal scroll view for bottom action buttons.

**Comment by tibbi** [comment]
it isnt really on the roadmap, woul be too crowded and some items would become hidden. That breaks the point of having them there and easy to click at the first place.
