### ISSUE TITLE
Overflow color does not respect theme

### ISSUE THREAD

**Issue by nvllsvm** [SimpleMobileTools/Simple-Gallery#187]
The scroll overflow color does not respect the theme's color. It remains orange regardless of which colors are set.
![screenshot_20170310-005430](https://cloud.githubusercontent.com/assets/6550543/23784000/5bbb7f80-052d-11e7-8c6f-9868fcf2d434.png)

**Comment by tibbi** [comment]
ye thats one of the things I couldnt change easily. I want to avoid reflection as it could have performance drawbacks and its not worth it.

**Comment by tibbi** [comment]
will be fixed in 3.0.0
