### ISSUE TITLE
Slide&Quick double tap is not working

### ISSUE THREAD

**Issue by speedpoint2019** [SimpleMobileTools/Simple-Gallery#1871]
Hello,
When I select a image and slide left/right, then image changed.
And normally double tap in image view work as zoom in/out.
But slide left/right and quick double tab is not working as I'm [thinking.](https://drive.google.com/file/d/1cuQp1S_CRZZ-zGO-xr8s0ytbH-RXl0YP/view?usp=sharing)
Could you please fix this error for me?
I'm using this app for 3 years and found this bug before a week.

I think this action should work such as Gestureviews's demo(https://drive.google.com/file/d/1ooflj9vKSoW_qnDhuvhoQT4HlDfXAHpz/view?usp=sharing)

**Comment by tibbi** [comment]
what do you mean by selecting and sliding? Do you mean the thumbnail view, or the fullscreen one?

**Comment by speedpoint2019** [comment]
I updated my comment.
Please check these two videos.
This will help us to understand current issue.

**Comment by speedpoint2019** [comment]
1. [issue video](https://drive.google.com/file/d/1cuQp1S_CRZZ-zGO-xr8s0ytbH-RXl0YP/view)
2. [real action video] (https://drive.google.com/file/d/1ooflj9vKSoW_qnDhuvhoQT4HlDfXAHpz/view)

**Comment by speedpoint2019** [comment]
Did you reproduced this error?
"Slide & Wait a moment & Double Tap" is working correctly.
But "Slide & Immediately Double Tap" is not working correctly.

**Comment by tibbi** [comment]
right, loading in the zoomable image can take a moment. Improving the performance is on the roadmap, it just isnt that easy. It is already reported elsewhere though, so Ill close this. Thanks
