### ISSUE TITLE
[Bug] Share videos

### ISSUE THREAD

**Issue by black-cerberon** [SimpleMobileTools/Simple-Gallery#1873]
Android 9
Simple Gallery v.6.15.2 Pro

Bug description: App not show existing videos when I try choose them and share through another app. 

For reproduce: Any app > Send file (or share) > Recent > swipe right and tap Simple Gallery > no one video file not visible.

**Comment by tibbi** [comment]
Well, dont you have videos filtered out at the top Menu -> Filter? If you launch Simple Gallery the casual way, do videos show up?

**Comment by black-cerberon** [comment]
> Well, dont you have videos filtered out at the top Menu -> Filter?
All marks enabled.
If you launch Simple Gallery the casual way, do videos show up?
Yes.

**Comment by tibbi** [comment]
I need more exact steps for reproduction. It definitely isnt "Any app", tell one where I could reproduce it properly.

**Comment by black-cerberon** [comment]
This app https://github.com/Mishiranu/Dashchan

**Comment by tibbi** [comment]
that is a heavily deprecated app, you shouldnt be using these. Does it happen in any other app?

**Comment by black-cerberon** [comment]
Snapseed, but this app for images. Anyway, if I choose default gallery or Leafpic instead Simple Gallery, videos will be show up.

**Comment by cunninglemming** [comment]
I think this is the duplicate of #1828

**Comment by tibbi** [comment]
still needs steps for reproducing

**Comment by cunninglemming** [comment]
I thought this comment [here](https://github.com/SimpleMobileTools/Simple-Gallery/issues/1828#issuecomment-863275135) explained it well, no?

**Comment by tibbi** [comment]
I didnt close that issue
