### ISSUE TITLE
First thing first it is not an issue. I am stuck on that code. so I am asking here. 

### ISSUE THREAD

**Issue by BlackBlind567** [SimpleMobileTools/Simple-Gallery#1875]
I am unable to find rate us dialog and another dialog which is linking to other apps of this community

**Comment by tibbi** [comment]
it is in Simple Commons, as it is reused by all apps

**Comment by BlackBlind567** [comment]
c

> it is in Simple Commons, as it is reused by all apps

can you suggest me a path of that.
