### ISSUE TITLE
Put sort option in toolbar with icon

### ISSUE THREAD

**Issue by ecnirp3120** [SimpleMobileTools/Simple-Gallery#1876]
Simple gallery's per folder sorting is really useful but sometimes I keep forgetting when I temporarily change a folder sort depending on my work flow. Fidgeting ensues. An icon immediately in the toolbar specifying the current sorting would help a lot. Also, I think toggle filename visibility isn't as important to be readily available in the toolbar.

Maybe similar to this.
![Screenshot_20200707-194711](https://user-images.githubusercontent.com/66897232/86780383-46dd8380-c08f-11ea-8dff-3e39eb21c98b.png)

Different icons
![Screenshot_20200707-194702](https://user-images.githubusercontent.com/66897232/86780513-67a5d900-c08f-11ea-8be5-fa3be11fa9cf.png)

**Comment by tibbi** [comment]
I dont really plan adding it there, thanks though
