### ISSUE TITLE
Some SVGs not rendered

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-Gallery#1878]
If I open a sent/received SVG file from [Conversations](https://github.com/siacs/conversations) v2.8.8+fcr using Simple Gallery v6.15.2, Simple Gallery just displays a black screen (with the file name and an overflow menu on top, and a share button and a location button at the bottom). The same SVGs render correctly if I open Simple Gallery directly and open the Conversations directory there.

EDIT - wait a second...even if I open Simple Gallery directly and navigate to the Conversations directory, the SVG _preview_ renders correctly, but opening the file results in the black screen described above.

All the SVGs I've tested were made using Inkscape...could test with others 🤔

**Comment by tibbi** [comment]
can you attach a sample file? Maybe it is related to the file itself.

**Comment by contrapunctus-1** [comment]
Okay, I think I know what's going on. The preview seems to use a _white_ background, and the main view a _black_ background. If an SVG is just a black object on a transparent background, it will be visible (black on white) in the preview, but not so (black on black!) in the main view.

**Comment by tibbi** [comment]
doesnt matter what color is the background, the vector file should display properly. Can you send a sample file?

**Comment by contrapunctus-1** [comment]
[svg.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/4907379/svg.zip)

**Comment by tibbi** [comment]
it works fine to me. The fullscreen view background is dark by default, not fully black. If you have a pure black background that might be the issue, as this image is a black one only too.

**Comment by contrapunctus-1** [comment]
Thanks for taking a look. I'm not sure what changes the background color for the full view - changing the theme didn't seem to affect it.

At any rate, it would make life difficult for users if they have to change the background to view certain images (quite a few won't even get there - "This image doesn't work", or "This app doesn't work" 🙂) Could you please make the background a grey-black grid for images with transparent backgrounds?

**Comment by tibbi** [comment]
it might be added in the future, we will see. So far not a single person out of millions of users had such an issue so it just isnt really important now. Thanks
