### ISSUE TITLE
Empty recycle bin - don't require a fingerprint

### ISSUE THREAD

**Issue by primarto** [SimpleMobileTools/Simple-Gallery#1883]
I have enabled " Password protect file deletion and moving " and when i want delete or move photos, a fingerprint is required.
But from recycle bin when i press "Empty recycle bin" photos are deleted without requiring a fingerprint.

By my logic, even at that point, the user should be asked for a password.

**Comment by puppykickr** [comment]
If I remember right the recycle bin self empties after 30 days.
Doesn't it require you to go through the security to place items into the recycle bin in the first place?

How would the recycle bin empty itself if it had to wait for an ok?

**Comment by BraINstinct0** [comment]
Notification for deletion confirmation seems sufficient. Issue seems to be ok to close
