### ISSUE TITLE
[Suggestion] add correction sliders!

### ISSUE THREAD

**Issue by DSDV** [SimpleMobileTools/Simple-Gallery#1887]
Hi,
after switching from MIUI to Linage i really miss the default Gallery.
the privay switch to protect the gallery from preview thumbnails and screenshots is missing but i can try work around that.
but the sliders for example brightness and contrast correction are really a miss. i can live without them and have to use crappy default gallery only for that tasks :/

**Comment by tibbi** [comment]
you can already do that in the Pro apps editor, together with many other attributes

**Comment by DSDV** [comment]
ok ? 
where to get i have gallery pro from F-Droid?

**Comment by tibbi** [comment]
F-droid has a different editor, as it is not open source. Maybe you can get the Pro version from Github Releases too, they are at https://github.com/SimpleMobileTools/Simple-Gallery/releases . It contains the Pro editor, like on Google Play.

**Comment by DSDV** [comment]
Oh thanks for the info!
may i ask why fdroid version is so "limited" / why the other versions are not open source?

**Comment by tibbi** [comment]
It is only the photo editor being developed by third party group of developers, and it isnt open source. It is a commercial product. That is the only app with this being only difference between the Google Play and F-droid versions. Everything else is the same.

**Comment by DSDV** [comment]
![Screenshot_20200728-162126_Gallery](https://user-images.githubusercontent.com/5504857/88678368-ab1fc000-d0ee-11ea-8bcb-a32f387e509b.png)
hm.. i downloaded this: https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery&hl=de

i see the options in the preview but not in the app ? o.o

**Comment by tibbi** [comment]
ye those screenshots are currently just being tested, they are reused from the Pro app version. The free one doesnt have that editor.

**Comment by DSDV** [comment]
so just any paid version correct?

**Comment by tibbi** [comment]
Well it is available in the Proprietary app version, wherever it is. It can be downloaded from Github releases at https://github.com/SimpleMobileTools/Simple-Gallery/releases too

**Comment by DSDV** [comment]
nice i tried that and it works like a charm you should promote that more clearly which features get added and how to download the "full version" 👍

**Comment by tibbi** [comment]
the vast majority of users get the app from Google Play, so theres nothing extra to explain
