### ISSUE TITLE
Secret folders

### ISSUE THREAD

**Issue by hockeymikey** [SimpleMobileTools/Simple-Gallery#1889]
They work like hidden folders except simple gallery still scans them and keeps them updated in cache. The user can toggle showing them (maybe add an optional passcode/pin too). Maybe add a setting to add .nomedia files to them too so they're not scanned by other apps. It's basically the same except its photos the user wants to keep hidden and out of the way like personal photos.

**Comment by tibbi** [comment]
You can already make a folder hidden or password protected, I dont plan adding a new way of doing the same thing.

**Comment by hockeymikey** [comment]
> You can already make a folder hidden or password protected, I dont plan adding a new way of doing the same thing.

Hidden and secret would fundamentally be much different since hidden encompasses things I don't wanna see like thumbnails from an audio app nor do they keep scanned and updated by the gallery. Its functionally a different level yet so similar it males implementation very simple and quick.

**Comment by tibbi** [comment]
you can use Excluded folders for thumbnails etc. Either select a folder by long pressing it on the main screen and exclude it maybe together with its parent folder, or go to the app settings -> manage excluded folders and add it there.
