### ISSUE TITLE
Feature Request : Show how many viewd items

### ISSUE THREAD

**Issue by Marvinoo** [SimpleMobileTools/Simple-Gallery#1890]
Say I've album contains 100 of pic/videos files and I've viewed 45 files of them..
So I want the app to show how many items I've viewed upon opening them, so it would look like this 45/100 
Placing this counter on the top above the viewed media file would be good. Thanks in advance.

**Comment by tibbi** [comment]
I dont really want to flood the UI with that, so dont expect having it. Thanks

**Comment by Marvinoo** [comment]
Can you at least include it in the options from 'Show extended details in full screen' ?

**Comment by tibbi** [comment]
what exactly? If a file was viewed? Of course it was if you are on it.

**Comment by Marvinoo** [comment]
> 
> 
> what exactly? If a file was viewed? Of course it was if you are on it.

No, I mean the counter, sorry my English is not my first language but I mean I want to see how many pics I've viewed in a folder so I know how many the remaining items are..
[Number of viewed items]/[Number of total items in folder]

**Comment by tibbi** [comment]
I dont plan adding it, feels quite useles
