### ISSUE TITLE
Sometimes image shows in the bottom right corner

### ISSUE THREAD

**Issue by jamescruser** [SimpleMobileTools/Simple-Gallery#1895]
![jeaeaigfgoogiboe](https://user-images.githubusercontent.com/69721136/90313308-43a8a380-df29-11ea-97fb-353c0c5e5903.jpg)

Android version 10
I'm getting this issue recently. Please fix this

**Comment by tibbi** [comment]
what app version is that? What is the app resolution?

**Comment by jamescruser** [comment]
It's in the latest version.

**Comment by jamescruser** [comment]
It's in the latest version.
Device 1 : Oneplus 7T
6.67 inches (1440 x 3120)
---------------------------------------
Device 2: Samsung Galaxy S20+ 5G
6.70 inches (1440x3200)

**Comment by tibbi** [comment]
I need a number of the app version, from the bottom of the About page. Is it the Pro verson at all?

**Comment by jamescruser** [comment]
It's 6.15.2. 
Yes it is a pro version.

**Comment by tibbi** [comment]
hm okay, how exactly it happens? Do you have to rotate the screen for it to happen, or not? Do you have "Allow deep zooming images" option enabled in the app settings?

**Comment by jamescruser** [comment]
It happened suddenly with no reason that I know. I did not rotate the screen.
I uninstalled and reinstalled. It went back to normal again
The "deep zooming images" option was enabled. Strange.
Thank you.

**Comment by tibbi** [comment]
do you have "Show images in the highest possible quality" enabled at the deep zoomable section too?

**Comment by tibbi** [comment]
shouldnt happen anymore
