### ISSUE TITLE
Inclusion of # in the filename causes the app to display the image in a lower quality

### ISSUE THREAD

**Issue by Gio1422** [SimpleMobileTools/Simple-Gallery#1897]

**Comment by tibbi** [comment]
what app version are you using? Can you reproduce it like that? By adding # somewhere to the filename?

**Comment by Gio1422** [comment]
yeah, sorry
forgot to check my emails
the bug's present in 6.15.2
when renamed something containing a #, the image appears visibly worse in the app
you also can't zoom in as far as you could before
