### ISSUE TITLE
Multi-rename no longer retains leading or trailing space

### ISSUE THREAD

**Issue by otede** [SimpleMobileTools/Simple-Gallery#1899]
Steps:
1A. Screenshot_20200822-110421 - Append "[space]AA"
1B. Screenshot_20200822-110425 - Prepend "BB[space]"

Actual results:
Screenshot_20200822-110421AA
BBScreenshot_20200822-110425

Expected results:
Screenshot_20200822-110421 AA
BB Screenshot_20200822-110425

It used to work fine not long ago. I used it daily since the multi-rename feature has been released.

**Comment by The-Pyrox** [comment]
HI, i wanted to solve this issue but i am unable to find the file where rename occurs. I found it to be this - package com.simplemobiletools.commons.dialogs.RenameItemDialog. This file is read only.

Can you tell me if i am approaching it the correct way?

**Comment by tibbi** [comment]
sure, functions and other resources used by multiple apps come from Simple Commons, it is at https://github.com/SimpleMobileTools/Simple-Commons

**Comment by The-Pyrox** [comment]
Hi, sorry to bother you again, but can you tell me how can i test my Simple Commons changes that i made for this bug?

**Comment by tibbi** [comment]
In Simple Commons MainActivity.kt just call the proper renaming dialog with hardcoded paths. Make sure you grant the Storage permission to Simple Commons first

**Comment by The-Pyrox** [comment]
I have fixed the above bug in Simple-Commons and submitted a pull request. Please do look into it.

**Comment by tibbi** [comment]
@The-Pyrox the issue is about the case when you are renaming multiple files at once. You changed the one where you are renaming a single file.

**Comment by The-Pyrox** [comment]
@tibbi i checked and tested, the layout to rename multiple files is called from MediaAdapter.kt , where the layout RenameDialog.kt is called and under which this change appears. Kindly do check once again , as i have tested and its working fine.

**Comment by tibbi** [comment]
okay ye, you are right. I thought it is about pattern renaming, but that doesnt make much sense. Works well now, thanks
