### ISSUE TITLE
No marker displayed for selected images

### ISSUE THREAD

**Issue by AlexanderRavenheart** [SimpleMobileTools/Simple-Gallery#19]
There should be a visual indicator of which files are selected (colored border, check mark, etc.) when selecting multiple files.

**Comment by tibbi** [comment]
there is an orange foreground overlay at selected items, unless you use some really old version of the app. What version of the app and OS do you have?

**Comment by AlexanderRavenheart** [comment]
Android version 5.0.2
App version 1.18
![screenshot_2016-08-03-17-11-28-934](https://cloud.githubusercontent.com/assets/7274337/17368598/760fc8be-599d-11e6-8bd6-3151c6381e2b.jpeg)

**Comment by licaon-kter** [comment]
Not seeing any marker either, both themes.
App version 1.19 from F-Droid.

**Comment by titiger** [comment]
I don't see any markers. App version 1.20 from F-Droid.
