### ISSUE TITLE
Deleting a folder results in full device freeze

### ISSUE THREAD

**Issue by pilsnerbeer** [SimpleMobileTools/Simple-Gallery#1900]
I have a folder with a movie in it and attempting to delete it will freeze the device to the point it needs to be manually reset. Deleting small files (images) works with no problems. I suspect this may have something to do with work profile (I use Island) since I never had this issue before (I use simple gallery on my main profile.)

1. have a folder with large file in it (1G)
2. attempt to delete the folder
3. device will freeze
.. ?

Android 10
6.15.2 / f-droid
OP5T

**Comment by pilsnerbeer** [comment]
Internal

**Comment by gouri-panda** [comment]
Can i take the issue?

**Comment by tibbi** [comment]
ye

**Comment by tibbi** [comment]
are you directly deleting the folder, or you have the recycle bin enabled? Or it doesnt matter?

**Comment by pilsnerbeer** [comment]
Doesnt seem to have effect (I have the bin enabled). Tried deleting a big file yesterday. Phone froze for 10-15s, but unfroze later ( no reboot required this time. ) Emptying the bin works w/o freezes.

**Comment by pilsnerbeer** [comment]
1 year later, this is still an issue (app just froze my phone)

**Comment by tibbi** [comment]
guess it wont happen again from 6.23.0
