### ISSUE TITLE
Allowing photos to have tags/label and sort by tags

### ISSUE THREAD

**Issue by rushabhgala** [SimpleMobileTools/Simple-Gallery#1904]
is it possible to implement tagging or labelling photos in gallery for certain photos can be labelled 'owls' and one day I want to see all owls photos I have taken over the years.. I know there are already folders but one photo can have multiple labels/tags and in the folder view, I would have to copy them in every folder.
here is an example for the use case: 

I have two folders : zoo_london and zoo_paris and both of them contain images of owls. I can label the relevant images as owl and then see sort wrt the label to only see owl images from both the folders.

**Comment by tibbi** [comment]
duplicate of #373
