### ISSUE TITLE
[question] Where does the editor export images to?

### ISSUE THREAD

**Issue by danielmmmm** [SimpleMobileTools/Simple-Gallery#1906]
When I export an image from the image editor, I can see SG rendering the image. But then it is just gone, and I have no idea where it was saved to.

The back arrow quits the editor immediately without asking if the image should be saved or not. All I get is a message saying that image editing was cancelled.

What am I missing?

**Comment by tibbi** [comment]
What app version are you using? After using the Export button at the bottom right corner you should be redirected back to the app, where a dialog shows up asking the new file path and name.

**Comment by danielmmmm** [comment]
I am using v6.15.2 Pro from the Play Store.

OK, this is weird, I do get the file save dialog now!
Strange when thing fix themselves like that :-)
