### ISSUE TITLE
v6.15.4 and modified time changed externally

### ISSUE THREAD

**Issue by Rikk** [SimpleMobileTools/Simple-Gallery#1913]
v6.15.4 doesn't reflect changes to file timestamp (mtime) done in file managers. 

For example, I use file manager to change mod time seconds of a picture to have it sorted in a better order; after the change, opening it again in SGallery will still display it in the old order before the time change.

**Comment by tibbi** [comment]
make sure the timestamp is properly updated in the MediaStore too, not sure which File Manager you mean

**Comment by Rikk** [comment]
Works normally with previous versions, I don't remember having this problem before. Looks very related yesterday's changes (last modified)...

**Comment by tibbi** [comment]
ye, it is. Im getting the last modified in other way now as the old one got ridiculously slow on Android 11 for some changes

**Comment by Rikk** [comment]
Still happening in .5
Did it cache dates before .4?
Looks like it caches mod time and doesn't update when changed.

**Comment by tibbi** [comment]
if there is a value in mediastore, it takes it from there. if not, it takes it from cache. Try using the Fix Date Taken values

**Comment by Rikk** [comment]
> if there is a value in mediastore, it takes it from there. if not, it takes it from cache. Try using the Fix Date Taken values

Afaik, "Fix Date Taken" is meant to fix photos metadata. This is not the case.
The problem is that you started caching Modified timestamps of files and if these are changed in the filesystem (or mediastore), Simple Gallery doesn't update the database with the new values on subsequent views of the same images.

**Comment by tibbi** [comment]
well sadly Google began breaking the file system to move everyone on MediaStore. Casual file operations are much slower starting on Android 11, than they were previously. I will be working on improving it.

**Comment by Rikk** [comment]
Maybe you could restrict the new changes to Android 11?

**Comment by tibbi** [comment]
Ill see what needs to be done. The changes are still new and nobody else had such issues.
