### ISSUE TITLE
View/Mount Remote Content (Nextcloud)

### ISSUE THREAD

**Issue by grravity** [SimpleMobileTools/Simple-Gallery#1914]
I know there is an old thread asking about Nextcloud, but this would be genuinely be cool to see.

I saw your concern being to not give internet access. Obviously this could in theory be optional set by a toggle on, off by default permission, could it not? If users don't want to use remote then the app would be offline as normal and the app would be hard permission set to off. Also users can always cholse to use an application level firewall such as Netguard, despite being un-needed.

Or

Maybe consider developing a dedicated middleman like app that would kind of act as a plugin, it can pull from a few network types or self-hosted FOSS sources (Nextcloud, SFTP/SSH, etc).

Then have give it the ability to link into Simpls Gallery, or link into the Simple File Manager.

The ability to "mount" a server filesystem without root (if possible) over SSH or log into a Nextcloud instance (seems more likely without root) into file manager and gallery that can do full RWX (read, write, execute), would be absolutely amazing, as would being able to view photos from a server in Simplemobiletools apps.

The app would essentially act as a middleman, so if that app is not installed, the Gallery and File Manager wouldn't even touch the internet still. The app would obviously be optional to install and without it as I've stated all the apps still have no internet access as normal. 

I would really like to see something like this if possible. It would extend the apps features greatly.

**Comment by tibbi** [comment]
I dont plan adding anything like that, not even optionally
