### ISSUE TITLE
Suggestion - Add 'Settings' link inside menu in image view

### ISSUE THREAD

**Issue by Rikk** [SimpleMobileTools/Simple-Gallery#192]
The addition of 'Settings' link inside menu when image is displayed, because when it's opened from external app there isn't way to access main screen (back key will close app).

**Comment by tibbi** [comment]
and which Setting items do you want to access at fullscreen images?

**Comment by Rikk** [comment]
The main Settings dialog. The same link we have in the menu of the first screen of the app.

**Comment by tibbi** [comment]
I mean which setting do you want to change from the Fullscreen view? Theres already more menu items at the fullscreen images than I wanted, I dont really want a settings there too.

**Comment by Rikk** [comment]
Most options are relevant to image view, eg, background color, auto-play, hide folders, and possibly others you add in future (maybe background color especially). If there was a way to go back to home screen (passing through the thumbnail view of the current folder) it would make this extra button almost completely unnecessary.

**Comment by tibbi** [comment]
I actually want to make that top left corner arrow work like that in other apps too, to move a level up. Now it works the same as pressing Back. Thats how this issue will be solved too.

**Comment by tibbi** [comment]
so while I still want to change the arrow functionality as mentioned, Ive also added the Settings button in both media thumbnail and the fullscreen views. Im adding a couple more settings so it might be needed.
