### ISSUE TITLE
[Bug?] Hide multiple folders requires Pattern/PIN input for each one

### ISSUE THREAD

**Issue by jncosideout** [SimpleMobileTools/Simple-Gallery#1920]
I selected multiple photo albums to hide and as the app processed them I had to enter my PIN, which is the pattern I chose for "Locking" my folders, about 20 times. Eventually I realized the app was making me do it for each folder but there was no prompt explaining that or counting the folders like "hiding 7/20" and incrementing the numerator each time. 

I suggest entering the PIN once for this operation.

**Comment by tibbi** [comment]
closing this as with version 6.23.0 and Android 11+ you wont be able to see hidden files anymore
