### ISSUE TITLE
Hiding a folder with ".nomedia" does not recursively hide subfolders

### ISSUE THREAD

**Issue by ashelleyPurdue** [SimpleMobileTools/Simple-Gallery#1923]
In most other Android apps, a ".nomedia" file marks the folder *and all of its descendants* as hidden.  This app doesn't do that, meaning anything in a subfolder will "leak" and be visible.  That can be worked around by manually hiding each subfolder manually, but that is a lot of manual work if you have lots of subfolders.

**Comment by tibbi** [comment]
it should work like that. What app version are you using? Dont you have something at the app settings -> manage included folders?

**Comment by ashelleyPurdue** [comment]
I'm using version 6.16.1 pro.

I *do* have a "manage included folders" option, but it has the exact same problem: excluding a parent folder does not exclude any of its child folders.

Perhaps I should give you an example.  Suppose I have a file hierarchy looking like this:

    * Memes/
        * lolcat.jpg
        * orly_owl.jpg
        * all_your_base.jpg

    * Emberassing_Memes/
        * .nomedia
        * joke_from_my_childhood_that_didnt_age_well.jpg
        * joke_that_I_think_is_ok_but_my_spouse_disagrees.jpg
        * joke_that_would_change_the_way_my_mother_thinks_of_me.jpg
        * Rage_Comics/
            * forever_alone.jpg
        * Advice_Animals/
            * philosoraptor.jpg
            * courage_wolf.jpg
        * My_Little_Pony/
            * fluttershy.jpg
            * rainbow_dash.jpg

I want everything inside `Embarassing_Memes` to be hidden most of the time.  I can't let people find out that I still laugh at these dated references!  But I don't want them to be hidden *all the time*, because I do still want to browse through them when nobody's looking.  So, I put a `.nomedia` file inside `Embarassing_Memes`, expecting everything below it to be hidden until I press the "temporarily show hidden files" button.

When I open Simple Gallery, I expect to see just this hierarchy:

    * Memes/
        * lolcat.jpg
        * orly_owl.jpg
        * all_your_base.jpg

...until I press "temporarily show hidden files", in which case I want to see the whole hierarchy.

Unfortunately, that's not how it works.  Instead, I end up seeing *this*:

    * Memes/
        * lolcat.jpg
        * orly_owl.jpg
        * all_your_base.jpg

    * Emberassing_Memes/
        * Rage_Comics/
            * forever_alone.jpg
        * Advice_Animals/
            * philosoraptor.jpg
            * courage_wolf.jpg
        * My_Little_Pony/
            * fluttershy.jpg
            * rainbow_dash.jpg

It hid all of the bad jokes at the root `Embarassing_Memes`, but it didn't hide anything in any of the child folders.  Now if I open Simple Gallery on the subway, everyone will see the thumbnail for fluttershy.jpg!  The horror!

A workaround for this would be to add a `.nomedia` file to each and every one of those child folders, like so:

    * Emberassing_Memes/
        * .nomedia
        * joke_from_my_childhood_that_didnt_age_well.jpg
        * joke_that_I_think_is_ok_but_my_spouse_disagrees.jpg
        * joke_that_would_change_the_way_my_mother_thinks_of_me.jpg
        * Rage_Comics/
            * .nomedia
            * forever_alone.jpg
        * Advice_Animals/
            * .nomedia
            * philosoraptor.jpg
            * courage_wolf.jpg
        * My_Little_Pony/
            * .nomedia
            * fluttershy.jpg
            * rainbow_dash.jpg

The thing is...I shouldn't need to do that!  Every other app on my phone dutifully ignores everything inside `Embarassing_Memes`.  Simple Gallery is the only app that does not.

**Comment by ashelleyPurdue** [comment]
Also, I should add: `Embarassing_Memes` is in my included folders list, because it otherwise wouldn't show up even if I had hidden files enabled.

**Comment by tibbi** [comment]
well if a folder is hidden but included, it shows up. That is now the expected behaviour. Other apps obviously arent aware of what folder you have at the included folders, so they hide it. Just remove it from the included ones, it should show up when needed.

**Comment by ashelleyPurdue** [comment]
The issue is that it doesn't show up at all unless it's in the included list.

**Comment by tibbi** [comment]
have you tried removing it from there now? Folders containing media files should be cached and no longer needed to be at the included ones. You can also try renaming the folder, maybe something stuck there.

**Comment by KazKaz90** [comment]
This still happens on the 6.24.1 version, Simple Gallery is the only gallery app I know that have problems with `.nomedia`.
