### ISSUE TITLE
Practical Editor?

### ISSUE THREAD

**Issue by ToddCrimson** [SimpleMobileTools/Simple-Gallery#1926]
Hi, so I've installed your app, but where is the Practical Editor, which you have listed in this image?
https://f-droid.org/repo/com.simplemobiletools.gallery.pro/en-US/phoneScreenshots/app_3.jpg

I would love to have those features at the bottom, which allow me to make changes, including adjusting brightness, exposures, etc etc. I don't see that anywhere in the app.

Please help
![app_3](https://user-images.githubusercontent.com/72161607/94728251-cdaf9e80-0314-11eb-82a4-eb5cc32afd4d.jpg)

**Comment by tibbi** [comment]
it is available only in the Google Play version at https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro . It couldnt be added into f-droid as it is not open source.

**Comment by ToddCrimson** [comment]
Hi Tibbi,

Thanks, so if I wanted to buy that, can I buy and then take the app, and use it on my Android device, which doesn't have any google play services? Or can I buy it directly from you? Its those features that are very attractive to me, but I don't want to have Google Play Services.

So I can use another Android device, to purchase, download, extract the app, and install it on my NON Google Device.
I would just like to know if that will work? If not, then is there any other option?

Thanks.

**Comment by tibbi** [comment]
sure, all app releases are here on Github too at https://github.com/SimpleMobileTools/Simple-Gallery/releases . But you wont be receiving updates that way. The Editor seems to have some issues with Android 11 so it will need an update soon.

**Comment by ToddCrimson** [comment]
Oh wonderful, thanks for explaining that. 
So I'd love to send a donation for your work. This is great.

One curiosity on this, since you release your code here, but it's still not open source?
Are there any features in this app, which upload information about my pics, etc somewhere?

**Comment by tibbi** [comment]
everything but that library is open source. It isnt developed by us, but by a third party group of developers. It is then just included in the app. Everything else is the same as on f-droid, other apps are fully equal. The apps have no internet access so nothing is sent anywhere.
