### ISSUE TITLE
Gif not working

### ISSUE THREAD

**Issue by maverick74** [SimpleMobileTools/Simple-Gallery#1927]
I've been sent this gif via messenger.

https://ufile.io/fsg30729 
(giving the gif's "nature" I've set the download to expire in 24h)

I'm sorry for sharing "this" example, but it's the first I've found... I though it was a problem with the image, but browser reads it fine... So... Here I Am submitting a possible bug...

**Comment by tibbi** [comment]
it is a WebP file, not a GIF one. It has a wrong file extension.

**Comment by maverick74** [comment]
S**t !!!
Why didn't I remembered trying that!!! Lol

Is there a way to check if an extension is the correct one or is it a try-again process?

Maybe using notepad++ or something?

**Comment by tibbi** [comment]
well the real filetype could be checked by pressing some menu button, but I dont really plan adding that.

**Comment by maverick74** [comment]
@tibbi Thanks for your reply. 
No, i don't mean on simple gallery, I mean in a broad way. Like on desktop or in any other way... 

How do you know if a gif is a webm or a png... Is there a specific way? Did you find out just by trying to change the extension or is there a place (desktop/mobile/somewhere/...) one can find what a file really is?

**Comment by tibbi** [comment]
there is probably some way, but now I just guessed. Many people seem to be confusing gif and webp files lately.
