### ISSUE TITLE
Gallery crashed my SystemUI

### ISSUE THREAD

**Issue by NovaStorm64** [SimpleMobileTools/Simple-Gallery#1929]
I was adding a Discord pfp in work mode, and when I went to add a pfp from the normal mode. I chose documents then Simple Gallery, and somehow this sequence of events crashed my SystemUI app. I had to factory reset for this to be fixed (I used this an excuse to install a custom ROM I've been meaning to for ages). I was rather disgruntled, as I love this app and have been using it for ages.
I don't know how this happened, but I feel like this should be fixed.
Thanks.

**Comment by tibbi** [comment]
I dont really see how would that be related to the gallery, not a single person had that issue so far. It must have been some weird sequence of events.
