### ISSUE TITLE
Suggestion - fast releases in Play Store, inside Beta program

### ISSUE THREAD

**Issue by Rikk** [SimpleMobileTools/Simple-Gallery#193]
I think it is great to have apps constantly updated, but I see many people don't like that. One alternative I think would be enabling the Beta program, so people that want to receive builds more often could subscribe to it.
What do you think?

https://developer.android.com/distribute/engage/beta.html
https://support.google.com/googleplay/android-developer/answer/3131213?hl=en

**Comment by tibbi** [comment]
Those frequent updates arent normal, they were caused just by some Android 7 issues which I didnt manage fixing as soon as I wanted. I already wanted to start using staged rollout, which would first release the app to 20% of users, then 50% and 100%. When Im fixing some specific issues, I usually consult them with people who can reproduce it through emails, and send them new versions to check if the bugs are fixed. I know that the beta program exists, but I dont really want to complicate the releasing with that for now.
