### ISSUE TITLE
Google camera portrait photos are not in list anymore

### ISSUE THREAD

**Issue by Myppomeu** [SimpleMobileTools/Simple-Gallery#1930]
App installed from F-Droid. In recent versions (at least from 6.15.5) portrait photos from google camera does not displayed in app even if I include folder with this photos manually.
I've cleaned cache and storage of app, tried to reinstall with no effect.

**Comment by tibbi** [comment]
what Android OS version do you have? Google changed the way portrait images are created in Android 11 again, the new way is not recognized yet. Also make sure "Portrait" is enabled at the top Menu -> Filter.

**Comment by Myppomeu** [comment]
Oh, sorry for that. Android 10 (official LineageOS 17.1 from 2020.06.23), Xiaomi Redmi Note 7, Google Camera port 7.3.018 v2.0 from Urnyx05. I was not upgrade Android, Google camera or anything else, only Simple Gallery.

**Comment by tibbi** [comment]
dont you have "Portrait" disabled at the top Menu -> Filter then?

**Comment by Myppomeu** [comment]
It was enabled, but after disabling and enabling again portrait photos appears in list. And now I'm not able to reproduce issue.
Thank you! For me it is solved now; should I close issue?
