### ISSUE TITLE
Editing images resets their "last modified" time

### ISSUE THREAD

**Issue by TheLastGimbus** [SimpleMobileTools/Simple-Gallery#1934]
I love this app for handling "last modified" time right ❤️

But when I edit the photo and override it/save as new one, it restets to current

Please support this as well 🙏

**Comment by tibbi** [comment]
what app version are you using? Have you got the app from Google Play, or some other source?

**Comment by TheLastGimbus** [comment]
I have F-Droid version 6.16.1

**Comment by tibbi** [comment]
is the given file on an SD card, or internal storage?

**Comment by TheLastGimbus** [comment]
Internal, I don't have sd reader (in Android-dev-language, everything is in "external storage" :P ). Are you asking me because this is a bug, and should normally work? If so, I could provide logs/something...

**Comment by tibbi** [comment]
ye, it should work just fine. Anyway, the f-droid version has an old deprecated photo editor, if you get the app from Google Play or Github, it has a lot more advanced editor. That is the only difference of the f-droid version.

**Comment by TheLastGimbus** [comment]
Isn't the version on Google Play paid for full features?
(few minutes later...)
Okay I installed one from GH relases, and works as it should. I was also wondering why editor wasn't the same as on images on readme 😅 
Why is F-droid version deprecated tho? Is it something with new editor not-being fully open source?

**Comment by tibbi** [comment]
ye, the new editor isnt open source at all, it is a commercial product that I pay for. But the app is still offline, so there is nothing to worry about.

**Comment by TheLastGimbus** [comment]
Whoa, that is some commitment - new editor is cool, without a doubt!
