### ISSUE TITLE
Sorting doesn't work with grouping

### ISSUE THREAD

**Issue by SirMartin** [SimpleMobileTools/Simple-Gallery#1936]
When try to group a folder by creation date (day or month) sorting doesn't work, and always are shown the old pictures before, it doesn't matter of you sort the pictures ascending or descending.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by SirMartin** [comment]
V. 6.16.1 pro From f-droid

**Comment by tibbi** [comment]
current way is the expected one, will see how could sorting + grouping improve

**Comment by licaon-kter** [comment]
No update here? :(
