### ISSUE TITLE
Hiding a folder doesn't work immediately

### ISSUE THREAD

**Issue by smurfix** [SimpleMobileTools/Simple-Gallery#1937]
I just hid a folder with a couple of images, got the `.nomedia` dialog, and tapped "yes".

The folder was still displayed. I had to toggle the "show hidden files" menu option (my phone is set to German so I don't know its English title) twice to no longer see it.

Hiding single pictures is immediate. Hiding folders should be, too.

**Comment by tibbi** [comment]
what app version are you using? Was the folder on an SD card, or internal storage?

**Comment by tibbi** [comment]
should have been improved already
