### ISSUE TITLE
App does not ask for permissions when never opened, but opening image from simple file manager

### ISSUE THREAD

**Issue by vanitasvitae** [SimpleMobileTools/Simple-Gallery#194]
Hi

When you never opened the app via the launcher, but try to open an image from another app via simple gallery, it does not ask for storage permissions, but instead just crash.

There should be a permissions test when opening an image via intent.

**Comment by tibbi** [comment]
I guess it doesnt happen often, but has to be fixed indeed :)

**Comment by vanitasvitae** [comment]
Thank you :)
