### ISSUE TITLE
Incorrect aspect ratio when cropping images for wallpaper with Simple Wallpaper.

### ISSUE THREAD

**Issue by Skaalgard** [SimpleMobileTools/Simple-Gallery#1941]
![Screenshot_20201023-195503](https://user-images.githubusercontent.com/31973127/97064173-aa6dbd00-1569-11eb-9751-e984373717b1.png)

When selecting wallpaper, crop is square instead of a correct 9:16 aspect ratio. Version 6.16.3

**Comment by Skaalgard** [comment]
This seems to be a repeat of issue #1367 which was closed with no fix or explanation.

**Comment by tibbi** [comment]
there is no correct aspect ratio, they are provided by the system. Just press the bottom left icon to change the aspect ratio.

**Comment by Skaalgard** [comment]
This button does nothing.

**Comment by Skaalgard** [comment]
Also, other gallery apps I have tried use the correct aspect ratio for this.

**Comment by tibbi** [comment]
supported wallpaper ratios come from the system, it isnt me hardcoding it. Ill revisig wallpapers in general someday, there are some device specific issues that can happen.
