### ISSUE TITLE
Multi-mime `ACTION_PICK` intent is not handled

### ISSUE THREAD

**Issue by oakkitten** [SimpleMobileTools/Simple-Gallery#1942]
This intent to pick (several) images or videos at the same time works with Google Photos, 1Gallery, F-Stop Gallery and Piktures:

```kotlin
Intent(Intent.ACTION_PICK,
       MediaStore.Images.Media.EXTERNAL_CONTENT_URI).apply {
    type = "*/*"
    putExtra(Intent.EXTRA_MIME_TYPES, arrayOf("image/*", "video/*"))
    putExtra(EXTRA_ALLOW_MULTIPLE, true)
}
```

Simple Gallery, on the other hand, doesn't treat this as a file picking action at all— there's no ✔ button in the toolbar to accept the selection.

Is there perhaps another way to pick images and videos using Simple Gallery?

**Comment by tibbi** [comment]
what app version are you using? How to reproduce the issue?

**Comment by oakkitten** [comment]
v 6.16.4 Pro. to reproduce,  call `startActivityForResult()` with this intent from another application

**Comment by tibbi** [comment]
which application? I want to see a real case scenario

**Comment by oakkitten** [comment]
i don't actually know any apps that use gallery apps for picking files. most apps are opting for built-in pickers.

i'm in a process of making an image/file picker button for my application and i'd rather use an external app for selecting files. `Intent.ACTION_PICK` seems to be the only intent that can open a gallery app directly, and the mentioned combination of parameters seems to be the only one that allows selecting images and videos at the same time.

if i am mistaken, i'll gladly use a more correct approach.

still, this approach was found on SO, so i bet at least some apps must be using it. and however broken the intent might be, i don't think ignoring it completely is correct behavior?

**Comment by tibbi** [comment]
not sure, but I dont want to work on random intents. Reopen this if you have a real case scenario

**Comment by oakkitten** [comment]
so what intent should i use to pick mixed media from Simple Gallery, or is my app not “real case scenario” enough?

**Comment by tibbi** [comment]
ye, doesnt seem to be

**Comment by oakkitten** [comment]
thanks for being rude. i guess you must have a reason for that
