### ISSUE TITLE
undo button appear after deleting content [feature request]

### ISSUE THREAD

**Issue by aha999** [SimpleMobileTools/Simple-Gallery#1943]
after deleting an image, an undo button should appear for a second or two if we happen to make a mistake, which would undelete an image.

**Comment by tibbi** [comment]
that isnt on the roadmap, it is replaced by the confirmation dialog

**Comment by aha999** [comment]
yes, but if you do 'don't ask anymore in this session' and you quickly delete files and accidentally delete the wrong file, it would be nice to undo in one click.

**Comment by tibbi** [comment]
there is already a confirmation and recycle bin, it is more than enough
