### ISSUE TITLE
WebP zoom levels broken 6.16.0+

### ISSUE THREAD

**Issue by kattjevfel** [SimpleMobileTools/Simple-Gallery#1944]
Thought I was doing something wrong for the past weeks but installing 6.15.6 gets the zoom levels working like the other formats.
Instead of filling the screen when double-tapping it will only go between "fit to screen" and "weird zoom", much like the stock gallery app. jpegs still behave as expected.

How to reproduce:
1. Open .webp image
2. Try zoom so it'll fill the screen (and then go to 1:1 with that enabled)
3. Watch as the zoom behaves just like the stock gallery app

I'm not sure how .gifs behave, but perhaps it just assumes every webp is animated and goes into an alternative mode?
Would greatly appreciate this being looked at, since a vast majority of my content is webp.

**Comment by tibbi** [comment]
webp received special support so that animated ones can work too. It wont really be changed anytime soon.
