### ISSUE TITLE
Add option to edit "last modified" file value

### ISSUE THREAD

**Issue by TheLastGimbus** [SimpleMobileTools/Simple-Gallery#1947]
I have an obsession on keeping all of my photos in right order, with correct date

I already love this app for keeping last modified value when moving photos :heart:

But when friends send me photos through some messenger, `last modified` is lost - right now, the **best** option that I know of is to modify it in Termux with `touch -m -t` : confused:

Could you please add a simple classic date/time picker to change it :pray: ?

**Comment by tibbi** [comment]
this will be a part of EXIF editor someday in the future, so closing it. Thanks
