### ISSUE TITLE
gridview: hard to select top right pic

### ISSUE THREAD

**Issue by rms-joe** [SimpleMobileTools/Simple-Gallery#1951]
It's really difficult to select the top right picture in grid view.
During most attempts it shows the current date.

**Comment by tibbi** [comment]
well just move your finger a bit left, do not long press the scrollbar. Also wait till it disappears.

**Comment by rms-joe** [comment]
I said hard, not impossible :D 
Maybe it's extra hard, cause I have a small device,
the spot I need to hit is like 3x3 mm

My current workaround is to do it in landscape.
Thanks for your reply and checking though.

**Comment by tibbi** [comment]
well so try long pressing one item, then dragging your finger over multiple ones to select them, like with a mouse on it. Then click on the ones you want to select.

**Comment by rms-joe** [comment]
I'm good.  I just wanted to point toward it.

**Comment by rms-joe** [comment]
Best way to solve is to reduce columns. But that have to be done for each folder. Thanks for your incredible work btw!
