### ISSUE TITLE
How to change default sorting setting ?

### ISSUE THREAD

**Issue by oldclock** [SimpleMobileTools/Simple-Gallery#1953]
Dears,

I was trying to modify default image sorting to SORT_BY_NAME and ascending, so I modified below code in Config.kt

`var directorySorting: `
`- get(): Int = prefs.getInt(DIRECTORY_SORT_ORDER, SORT_BY_DATE_MODIFIED or SORT_DESCENDING)`
`+ get(): Int = prefs.getInt(DIRECTORY_SORT_ORDER, SORT_BY_NAME)`

But it seems just change the default sorting method in directory view.
How do I change the default sorting method of images  ?

Thanks!

**Comment by tibbi** [comment]
file sorting is reused from Simple Commons, as it is shared by multiple apps. Just change default_sorting in integers.xml

**Comment by oldclock** [comment]
Hi tibbi,

I've found the sorting const in Constant.kt from Simple-Commons project.
So I tried modifying "default_sorting" to value 1.
It works just fine for me.

Thanks a lot for your help!
