### ISSUE TITLE
The new gallery view

### ISSUE THREAD

**Issue by iFUCKINGHATEcomputers** [SimpleMobileTools/Simple-Gallery#1957]
The new gallery view's rounded corners are utterly pointless, and the gaps are an inefficient waste of screen space. If you plan on keeping this layout, there should be an option to choose to choose between the old and new layout when first installing the app, and to later change it in the settings.

**Comment by tibbi** [comment]
it has already been reverted in 6.17.1, just update to it. It will be possible to enable it in the app settings as it has been liked by many people.

**Comment by iFUCKINGHATEcomputers** [comment]
Nice.

**Comment by MPeti1** [comment]
In the last release you've written that rounded corners have been kept.
Could make an option to turn them off? I hate rounded corners from the deepest point of my heart

Otherwise I like the app very much! Keep up the good work

**Comment by tibbi** [comment]
It has been reverted on the main grid view already, will be possible to reenable it soon.

**Comment by HyknuF** [comment]
> It has been reverted on the main grid view already, will be possible to reenable it soon.

nice to hear that. I just loved the new rounded thumbnail.
