### ISSUE TITLE
[Feature Request] Simple doodle on photo editor

### ISSUE THREAD

**Issue by RickyM7** [SimpleMobileTools/Simple-Gallery#1961]
This is a feature that exists in the Miui Gallery. It's a simple and useful feature and it would be great if it were added to Simple Gallery.
**Example (App in Example: Miui Gallery)**:
![Doodle Example](https://user-images.githubusercontent.com/24703825/98403066-1dd1fd00-2047-11eb-9c4d-18f6ccf099a5.jpg)

**Comment by tibbi** [comment]
the current photo editor is developed by a third party group of developers, not us. Dont expect having such feature

**Comment by RickyM7** [comment]
No problem!
