### ISSUE TITLE
Change cover image > Use default

### ISSUE THREAD

**Issue by mtris** [SimpleMobileTools/Simple-Gallery#1963]
Hello Team Super Mobile Tools: 
I have been changing photo album covers by long-pressing on the individual album...Change cover image > Select photo. I would like to use the same photo for every album cover. I see the 'Use default' option, but am unsure how to use it. Would this make all covers the same photo? How do I select a default photo? Is that the function of 'Use default' or how is it used?
Thank you for your consideration and I appreciate your time.
Sincerely,

**Comment by tibbi** [comment]
"Use default" basically reverts the cover photo you set and it will show the first image in the album. It depends on your sorting, it is usually the latest file. if you want to use the same photo for every folder you will have to set it one by one, there isnt really a way around it.

**Comment by mtris** [comment]
👍 Thank you for the reply and the great apps.
