### ISSUE TITLE
Ability to multi keyword search media

### ISSUE THREAD

**Issue by GopnikPrince** [SimpleMobileTools/Simple-Gallery#1964]
Having an option when searching files to search for general keywords typed into the search bar, like how windows explorer searches files.
Like if I have a file that I added '.video.outside.friends.' and another one with '.videos.friends.inside.' at the end of it, I want to be able to search 'video friends' in the search bar to make both media files appear.
Also, I love the multi rename function where you just append the strings to the end of the file name 👍

**Comment by tibbi** [comment]
that sounds weird.. Anyway, tags are on the roadmap, they will be added someday.
