### ISSUE TITLE
Setting default folder breaks fingerprint protection

### ISSUE THREAD

**Issue by v1r0x** [SimpleMobileTools/Simple-Gallery#1976]
I really like this new option! :partying_face: :smiley: 
But now the fingerprint protection seems to be broken.

It perfectly opens my default folder, but it is left unprotected. I can browse through this folder without using my FP (but I can still use my FP to unlock and get rid of the broken FP icon at the bottom).
[Broken FP Screenshot](https://user-images.githubusercontent.com/9248714/99402798-08cc5800-28ea-11eb-9901-412c4699d1c1.jpg)

Without unlocking and going back to see all folders, I get the [correct FP unlock screen](https://user-images.githubusercontent.com/9248714/99402802-0964ee80-28ea-11eb-8d1a-1f4239b3edea.jpg).
But I have to unlock it twice.
When I unlock my default folder and going back to see all folders, I don't have to unlock a second time.

**Comment by tibbi** [comment]
it seems to work just fine to me. Can you tell the exact steps for reproduction?

**Comment by v1r0x** [comment]
I've set up password app protection and remove files protection using fingerprint. After installing 6.17.3 I set up a folder as default folder.
Now when I open the app with the default folder set, I get the broken fingerprint.

I also reset both fingerprint protection and default folder, but it still doesn't work.

Is it possible to get a log or anything I could provide you?

**Comment by v1r0x** [comment]
Works fine now! :tada: Thank you for your fast fix :+1:
