### ISSUE TITLE
Resizing in Editor hard with Android 10 Gestures

### ISSUE THREAD

**Issue by newhinton** [SimpleMobileTools/Simple-Gallery#1979]
With the swipegestures introduced in newer android versions, the handlebars are too close to the border. If the user tries to move them, he or she also triggers the 'back' action. This happens on both sides. Everytime the user does this, the handle moves a fraction, and after a while it behaves normally.

A simple solution would be to move the handles further into the display, or to add a fifth "handle"-dot further in the mid of the screen. This allows to resize, and then move the selection to free the selection from the gesturetrigger.

![Screenshot_20201121-200251_Galerie_1](https://user-images.githubusercontent.com/25279821/99885434-29234c00-2c35-11eb-9cd9-97c31820050f.png)
(The black 'arrow' is the indicator for the gesture. it also happens on the other side of the screen)

**Comment by newhinton** [comment]
It sees adding

`app:cropBorderCornerOffset="20dp"`

to the activity_edit.xm:crop_image_view tag solves this issue on my device. A reasonable offset needs to be determined, it can possibly smaller. (on my device (Galaxy S9) 15dp are slightly to small)

**Comment by tibbi** [comment]
I dont really want to do that just because of some broken navigation. And that editor is no longer being worked on either, there is a more advanced one at the Google Play version.
