### ISSUE TITLE
[Bug] Wrong heading when sorting by date_taken

### ISSUE THREAD

**Issue by tanooki-games** [SimpleMobileTools/Simple-Gallery#1990]
Hi there,

great app. Really love it.

The issue:

When sorting `descending` by `date_taken` sorting seems to work correctly, but the headings show the date of `date_changed`. I have photos that have been taken 2020-08-08 but are listed under 2020-11-16 (which is the date I edited them with ON1). When clicking the info icon ( i ) it shows the correct date under the `date_taken` tag. 

Cheers, Georg

**Comment by tanooki-games** [comment]
I can attach screenshots, if that helps.

**Comment by tibbi** [comment]
Arent you confusing Sort by and Group by? Try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by tanooki-games** [comment]
Yeah you're right. But the sorting is still wrong. What is fixing date taken values? Why is it neccessary?

**Comment by tanooki-games** [comment]
I guess fixing 5000 photos wasn't a good idea. The app crashed.

**Comment by tibbi** [comment]
try fixing in smaller batches then

**Comment by tanooki-games** [comment]
Did it and it worked. Thank you for the fast answer. So why does it happen? Wrong exif version or something like that?

**Comment by tibbi** [comment]
checking file by file would be really slow, so at sorting by Date Taken the app relies on the system MediaStore, which is kind of an internal database storing file metadata, like Date Taken. If you do "Fix Date Taken values", it takes the Date Taken from the file itself and updates the value in the database.

**Comment by tanooki-games** [comment]
Alright. Thanks for explaining. Keep up the great work ; )
