### ISSUE TITLE
About rotating images with gestures

### ISSUE THREAD

**Issue by SuperMonster003** [SimpleMobileTools/Simple-Gallery#1992]
When checked the item as below,

-> Settings
-> DEEP ZOOMABLE IMAGES
-> Allow rotating images with gestures

the image which rotated by gestures will automatically be saved, no mather if this "check mark" icon (which says "save as" when long-click) was touched or not.

Most of the time, i rotated an image with 2 fingers just for the convenience of looking over. I prefer not saving the image and not changing its modified time data.

Thank u for the amazing app.

Device: Sony XQ-AT72 (XPERIA 1 II)
System: Android 10 (58.0.A.4.500)
App: 6.17.3 Pro (from Google Play)

**Comment by tibbi** [comment]
ye, autosave is the expected behaviour, the check will actually be removed.

**Comment by rkolbaskin** [comment]
So having to regularly deal with a bunch of sync conflicts because the app **silently** overwrites the files is not a bug.
Could you at least point to the part of the code I would need to edit to disable this "feature"?
