### ISSUE TITLE
Simple Gallery not recognized as a gallery

### ISSUE THREAD

**Issue by kTyn9A9Kw3** [SimpleMobileTools/Simple-Gallery#2]
Hey! Thanks for the great app, exactly what was missing on the foss community. +1 for your simple apps initiative :)

The bug/missing feature I'm reporting is what title says, Open Camera throws an error "No gallery app available" when clicking the small gallery icon.

Another example is when choosing wallpaper, Simple Gallery is not listed as an app for selecting pictures. And I guess any another actions that require a gallery/image browser...

**Comment by tibbi** [comment]
I was explicitly implementing the feature to list the app as a Wallpaper chooser, also listing it as a picture/video viewer/picker for multiple different usecases and implementations. Those things were implemented with release 1.8, guess you have newer one. Let me know which apps dont list it as an image picker. I will check the Open Camera implementation.

**Comment by kTyn9A9Kw3** [comment]
I can confirm it's working as a wallpaper chooser and image viewer, although on the image viewing dialog it has 2 Simple Gallery apps to choose and only 1 works and "com.simplemobiletools.gallery" is displayed above the icon. Tested with Amaze File Manager.

![gallery](https://cloud.githubusercontent.com/assets/20364510/16719388/39225e6c-4719-11e6-9ca9-78259e8641ed.png)

**Comment by tibbi** [comment]
okay Im aware of this one, its already fixed, just not in a release yet

**Comment by kTyn9A9Kw3** [comment]
Also one thing I forgot about Open Camera, the gallery button works if there are pictures on the device, if there isn't any it throws the error "No gallery app available"

**Comment by tibbi** [comment]
not sure if I can do anything else for the Set wallpaper issue. On my device at "Lock screen wallpaper" I dont see the app. At "Home screen" and "Home and lockscreen" it is there. It depends on the device and ROM, could be somehow limited. Let me know if there is any freely downloadable app (preferably opensource :p) which allows you setting the wallpaper.

**Comment by kTyn9A9Kw3** [comment]
I don't have that problem when choosing the lockscreen wallpaper, but it may vary from rom to rom like you said. Unfortunately there isn't many more open source galleries out there, besides aosp gallery and "LeafPic" also on F-Droid (https://github.com/HoraApps/LeafPic). Your app is kind of unique on this area :)

But besides that everything seems fixed except the Open Camera error "No gallery app available" if there isn't any pictures on the device.

**Comment by tibbi** [comment]
what do you mean by that No gallery app available? Isnt that an issue of Open Camera instead of my Gallery?

**Comment by kTyn9A9Kw3** [comment]
I don't think so because it just calls a gallery app to do the job, maybe Simple Gallery is missing some action. I think if there is pictures on the device Open Camera calls a gallery app to view the image directly, if there isn't it tries to open the gallery normally but it might be a different action (or view/intent, I'm not sure how it's called).

**Comment by tibbi** [comment]
whats the point of opening the gallery if theres no images on the device? Im closing this one, the original issue is already solved.

**Comment by kTyn9A9Kw3** [comment]
Sure it doesn't make sense for Open Camera, but this issue may affect other applications that try to open a gallery for something else, for example for shortcuts. And it makes the app look more solid.

I made a quick search and I found some interesting links, but I don't understand Java. Perhaps the missing intent is android.provider.MediaStore?

https://stackoverflow.com/questions/16928727/open-gallery-app-from-android-intent
https://stackoverflow.com/questions/4979075/button-to-start-the-gallery-on-android

**Comment by tibbi** [comment]
I do handle all the relevant intents at https://github.com/SimpleMobileTools/Simple-Gallery/blob/master/app/src/main/AndroidManifest.xml . Compared it with the official Google gallery too at https://android.googlesource.com/platform/packages/apps/Gallery2/+/master/AndroidManifest.xml . I dont want to spend too much time debugging cases when there are no images on the device, its just totally unrealistic.

**Comment by kTyn9A9Kw3** [comment]
I understand your point, but if you decide to take a second look to the intents available here's the Leafpic AndroidManifest: https://github.com/HoraApps/LeafPic/blob/master/app/src/main/AndroidManifest.xml The "android.intent.category.APP_GALLERY" seems suspicious.
