### ISSUE TITLE
Tablet video GUI (Bug?)

### ISSUE THREAD

**Issue by CrimsonFork** [SimpleMobileTools/Simple-Gallery#200]
On my tablet in the video mode the NavBar overlaps the video bar at the bottom so there's no way you can navigate in the movie.

P.S. do you REALLY excuse yourself for keeping up your good work? + Will there be more strings for the next update?

**Comment by tibbi** [comment]
Hah, for now I pretty much ignored the tablet UI as only a very low percentage uses them.

The latest string is "Temporarily show hidden", I dont know about any string that might be added. I wont be releasing a new version for a couple of days now.

**Comment by OffifialMITX** [comment]
Then I'll try to make a translation update tomorrow.
