### ISSUE TITLE
Annotating an image changes its dimensions

### ISSUE THREAD

**Issue by kaoneko** [SimpleMobileTools/Simple-Gallery#2001]
Annotating an image (with the doodle tool in the editor, that snake like icon in the lower right of the screen) and then saving it results in a file with different dimensions, either smaller or bigger. Here are a few examples:
```
Original:         2000x3000 - 2.6 MB - JPG
After annotation: 864x1296 - 158.1 kB - JPG

Original:         474x711 - 36.9 kB - JPG
After annotation: 864x1296 - 141.3 kB - JPG

Original:         1920x1920 - 2 MB - JPG
After annotation: 1080x1080 - 223 kB - JPG

Original: 1080x1920 - 589.6 kB - PNG
After annotation: 729x1296 - 361.3 kB - PNG
```
Using v6.17.3 Pro from F-Droid.

**Comment by tibbi** [comment]
ye, it saves images in the devices resolution. Anyway, that editor isnt updated anymore as it has been replaced with a lot more advanced one. But it is available only in the Google Play app version at https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro , or Github

**Comment by kaoneko** [comment]
Got it, I'll check it out, thanks!
