### ISSUE TITLE
Show Recycle Bin

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Gallery#2004]
Pls Show Recycle Bin when using Show all folders Content. I only use (show all folders content ) as my default option. If i view deleted photos\videos in recycle bin, i want change  (switch to folder view) then only i can recycle bin. So,pls show Recycle bin when using (show all folders content) i mark on image for sample.

![Ss](https://user-images.githubusercontent.com/75672019/101645508-789eb000-3a5c-11eb-8e80-9d380b663805.jpg)

**Comment by yephny** [comment]
I agree, it's cumbersome to use the recycle bin feature when you prefer all folders view. It's actually quite surprising to me that a button I never use at all, show filenames, is right there, next to the search button whereas it takes me 3 taps and about 5 seconds to open the recycle bin.

**Comment by tibbi** [comment]
an Open Recycle Bin button will be added in 6.26.3
