### ISSUE TITLE
Play/Pause in video editor player

### ISSUE THREAD

**Issue by proideo** [SimpleMobileTools/Simple-Gallery#2006]
Thanks for the new video editor but it's a bit annoying not being able to pause the video while editing.
It would be nice to add a play/pause button in future updates.

**Comment by tibbi** [comment]
you can pause it at the Trim section for now

**Comment by tibbi** [comment]
will be added in 6.20.0

**Comment by Marvinoo** [comment]
> 
> 
> will be added in 6.20.0
sorry for being out-of-topic but any news abt fixing the output video quality & fps after editing?

**Comment by tibbi** [comment]
not yet

**Comment by Marvinoo** [comment]
> 
> 
> not yet

Never mind <3
