### ISSUE TITLE
Feature Request: RGBCMY Color Balance Editing

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Gallery#2010]
Thanks for the massive recently update! Great additional editing tools!

In addition, I'd live to see the addition of a RGBCMY Color Balance editing tool to help with finer color adjustments, stylistic tweaks, and possible manual White Balancing.

**Comment by tibbi** [comment]
the current editor is developed by a third party group of devs, not us. I dont think it will be added, it is way too advanced for the scope of this app already. Even if they add it, I wouldnt really like to have it.

**Comment by Saijin-Naib** [comment]
I mean, I had this type of editing capability on my Samsung feature phone so I'm not sure I agree with it being too advanced, but I understand that it isn't to your preference.

**Comment by Saijin-Naib** [comment]
Is this possible currently?
