### ISSUE TITLE
Add Text

### ISSUE THREAD

**Issue by Github-com-foss** [SimpleMobileTools/Simple-Gallery#2013]
Pls add text option in gallery while edit the picture.

![vgg](https://user-images.githubusercontent.com/75672019/102574859-cdef5700-4117-11eb-9287-7af18467f8cf.jpg)

**Comment by tibbi** [comment]
there is text in the more advanced photo editor that is available in the app version from Google Play at https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro

**Comment by ahstro** [comment]
Should this be available in Simple Gallery Pro from F-Droid? Both are "Pro", but I can't find the option? I can't use Google Play because no Gapps on phone, so gotta access this some other way. Can I "buy" the feature some other way than Google?

**Comment by tibbi** [comment]
the advanced editor is not open source, so it cannot be on f-droid

**Comment by ahstro** [comment]
Alright! For posterity: I found that the proprietary apk is downloadable through releases here on GitHub, soo at least its available without Google Play installed 🙏
