### ISSUE TITLE
Pitch to Zoom

### ISSUE THREAD

**Issue by Github-com-foss** [SimpleMobileTools/Simple-Gallery#2015]
Pls stop unlimited pitch to zoom in (landscape) video player. If i use pitch to zoom it will collapse other gestures like volume and brightness also. For eg if i try to raise brightness gesture, the video will up if down the video goes down, same happen volume. when Now a days most of video player provide only to two option fit and zoom.  

Solution: plsu implement only two option in gesture Fit and zoom only.

**Comment by tibbi** [comment]
it works as expected currently
