### ISSUE TITLE
Gradient Banding (wrong pixel format/bit depth for surface?)

### ISSUE THREAD

**Issue by wyatt8740** [SimpleMobileTools/Simple-Gallery#202]
I'm experiencing color banding viewing images with this app. Some alternative apps (e.g. LeafPic) do not present this issue. I believe this is due to the pixelformat of the drawing surface not being explictly set.

I am running Android 5.0.1 on a Nexus 6, and using the app from the F-Droid repository.

**Comment by tibbi** [comment]
what pixelformat? O.o Are they pngs?

**Comment by wyatt8740** [comment]
Sorry, looks like f-droid's still got 2.6.6. I'll try 2.7.3 tonight.

**Comment by tibbi** [comment]
yea, f-droid seems to be lagging behind lately. In case you want to test the latest you can always download the latest app-release.apk from https://github.com/SimpleMobileTools/Simple-Gallery/releases

**Comment by wyatt8740** [comment]
Yeah, I got a moment, I'm doing it now.
It's a .jpg, by the way. the unix `file` command shows it as:
`a.jpg: JPEG image data, JFIF standard 1.01, aspect ratio, density 1x1, segment length 16, Exif Standard: [TIFF image data, little-endian, direntries=7, orientation=upper-left, xresolution=98, yresolution=106, resolutionunit=2, software=Adobe Photoshop CS5.1 Windows, datetime=2013:09:18 05:21:35], baseline, precision 8, 1080x1920, frames 3`

**Comment by tibbi** [comment]
The problem seems to be with the decode format, as I use a RGB_565 for jpgs as they are usually photos. If its not a photo but some other shapes, it can be low quality. Ill try finding some more advanced way of determining which to use, not just by the extension. Displaying all images as ARGB_8888 could cause memory issues on some devices so Id like to avoid that.

**Comment by wyatt8740** [comment]
You could possibly check available memory, or add a "low-memory" mode to settings. Just a couple ideas.

**Comment by tibbi** [comment]
Hey, can you test this version? Github doesnt allow uploading .apk files, so please rename "app-release.zip" to "app-release.apk" before launching it.Thanks
[app-release.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/865630/app-release.zip)

**Comment by wyatt8740** [comment]
@tibbi This appears to work properly, thanks. Could you show me what commit you did this in? I'd like to know so I can try patching a couple other apps that do this.

**Comment by tibbi** [comment]
yea, well I mixed 2 things together at https://github.com/SimpleMobileTools/Simple-Gallery/commit/ac63a8648d25d02d425075dfbcfbb53e413b8e65 . Its usable only if the app is using Glide for loading the images. The point is to use DecodeFormat.PREFER_ARGB_8888 at jpgs too. It takes twice the memory of DecodeFormat.PREFER_RGB_565, but the quality is better. We will see if people will be getting out of memories. 

Im still using RGB_565 at folder and media thumbnails as it has better performance and uses less memory, but it should be good enough for the thumbnails.

**Comment by wyatt8740** [comment]
@tibbi yeah, thumbnails are small enough that it shouldn't matter as much. Thanks!

And if people get errors, I would definitely suggest a "low memory mode" option in settings.

**Comment by tibbi** [comment]
I can always use a callback, catch the error, then try loading the low memory one :) A button for users is only plan Z.
