### ISSUE TITLE
Add Lock option

### ISSUE THREAD

**Issue by Github-com-foss** [SimpleMobileTools/Simple-Gallery#2020]
Add Lock Option in video player. (Press to lock )(press to unlock ) It helps to reduce accidental touch while watching movie...

![VLC-screenshot-2016-712x400_1](https://user-images.githubusercontent.com/75672019/102706241-29efe200-42b6-11eb-8d69-fe3c3fe247f4.jpg)
![Video-Player-All-Format-screenshot-2019-712x400_1](https://user-images.githubusercontent.com/75672019/102706258-51df4580-42b6-11eb-9f02-5941b22da6e6.jpg)

**Comment by tibbi** [comment]
it isnt really on the roadmap
