### ISSUE TITLE
Why app need new QUERY_ALL_PACKAGES permission?

### ISSUE THREAD

**Issue by IT-Tool** [SimpleMobileTools/Simple-Gallery#2021]
In the new v6.18.0, the app now asks for a new permission QUERY_ALL_PACKAGES. As far as my experience with this, this permission let to get a list of installed apps in Android 11.

"In rare cases, your app might need to query or interact with all installed apps on a device, independent of the components they contain. To allow your app to see all other installed apps, Android 11 introduces the QUERY_ALL_PACKAGES permission. In an upcoming Google Play policy update, look for guidelines for apps that need the QUERY_ALL_PACKAGES permission."
https://medium.com/androiddevelopers/package-visibility-in-android-11-cc857f221cd9

Can you describe what use case this permission was added for?

**Comment by tibbi** [comment]
ye, it is sadly needed for any communication between apps. In the gallery it is needed only in case someone wants to use the Shared Theme. In some other apps like Contacts, Dialer, SMS Messenger it is needed for sharing private contacts between apps.
