### ISSUE TITLE
Your Apps are Being used in stock firmware by Onyx International on their Boox Devices

### ISSUE THREAD

**Issue by diabl0w** [SimpleMobileTools/Simple-Gallery#2023]
Just thought I'd let you know that modified versions of your apps are being shipped on Boox devices made by Onyx International Inc. They use the same package name (org.simplemobiletools.*). I've pulled the Gallery app from the system and uploaded it here: https://www.androidfilehost.com/?w=files&flid=321140. They also use 1 or two others, Voicerecorder and Clock I believe.

**Comment by tibbi** [comment]
well it doesnt look like any popular distro, thanks for reporting :)
