### ISSUE TITLE
Missing feature

### ISSUE THREAD

**Issue by duergrim** [SimpleMobileTools/Simple-Gallery#2025]
I want to use simple gallery as my main gallery, but the missing feature makes me not want to use the app.

My current gallery app has a folder with all my media, WHILE STILL having seperate folders when leaving the folder. Please add this feature asap

![Screenshot_20201225-133045__01__01.jpg](https://user-images.githubusercontent.com/44030905/103135685-3a3efd00-46ba-11eb-9ae7-dafed1777ce8.jpg)

**Comment by tibbi** [comment]
adding some quick toggle for "Show all folders content" is on the roadmap, might be added as a folder itself too. But it is already reported.

**Comment by duergrim** [comment]
Pls add this asap. Will translate the app to danish then
