### ISSUE TITLE
Exporting edited videos fails (6.18.1)

### ISSUE THREAD

**Issue by proideo** [SimpleMobileTools/Simple-Gallery#2029]
After edit videos, the export process fails with the last update (6.18.1) in my secondary device (LG L90 - Android 5.0).

In the previous version the export failed with videos of a resolution higher than 1280x720 but I think it is due to some hardware limitation of the L90 (some video editors limit their output to that resolution on that device). But with version 6.18.1 the export process fails with all videos, regardless of their resolution. The message "Exporting ..." is displayed but it stays that way all the time.

On the other hand, on my LG G5 (Oreo) that update has not affected the export of edited videos.

**Comment by proideo** [comment]
It seems fixed in the new update (6.18.3) but still fails to export videos of a resolution higher than 1280x720 with the LG L90.

**Comment by Aulig** [comment]
Same issue here. In 99% of cases it gets stuck at 0.0% while exporting a screen recorded video from my Poco X3.

**Comment by tibbi** [comment]
how about 6.20.1? Can you retest it?

**Comment by Aulig** [comment]
Working for me now, thank you!

Tibor Kaputa ***@***.***> schrieb am So., 29. Aug. 2021,
12:55:
