### ISSUE TITLE
[Feature] add nested recycler view display mode

### ISSUE THREAD

**Issue by Drhaal** [SimpleMobileTools/Simple-Gallery#2030]
I think adding a new view constituted of horizontal recycler view  to display the different albums would be a really nice feature.
It allow to rapidly see the photo in an album without having to tap to open it.

Here's an example of how it's implemented on Camera-roll:
![Screenshot_20210106-140424_Camera_Roll](https://user-images.githubusercontent.com/33057913/103773002-b0345400-502a-11eb-8b8f-c475122a573d.png)

**Comment by tibbi** [comment]
that has been reported already ages ago
