### ISSUE TITLE
Can't delete photos from sdcard (6.18.0; 6.18.1)

### ISSUE THREAD

**Issue by paulle** [SimpleMobileTools/Simple-Gallery#2036]
Can't delete photos from sdcard (6.18.0; 6.18.1). My Photos are normally stored to the sdcard and it was never a problem to delete them with Simple-Gallery. With the last two versions this don't work.
If I try to do it, I get the following screen (see sreenshot) and when I confirm with ok, I get the message unknown error and nothing happens.
android 10  sony xperia5
![Screenshot_20210106-101821](https://user-images.githubusercontent.com/4852079/104015584-21077780-51b5-11eb-92df-709707079a9f.png)

**Comment by tibbi** [comment]
try finding the app in your device settings and do a "Clear data" (or "Clear storage") on it. It will just reset your app settings and clear the recycle bin/favorites, wont delete any files.

**Comment by paulle** [comment]
I did it and cleared storage, but the app shows the same behaviour as before.

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by tibbi** [comment]
does it work well in any other downloaded app? Dont you have a rooted device, or some disabled system services?

**Comment by paulle** [comment]
Device isn't rooted and don't disabled some system services in the last time. I've changed nothing in my system configuration and worked well in simple gallery I believe before version 6.18.0 (all from f-droid).
I tried deleting pictures from sdcard with a file manager (solid explorer) and this worked. I deleted simple-gallery and installed it from new, but this didn't change anything.

**Comment by paulle** [comment]
Problem is solved. The phone got an update to android11 but even with the update the problem remained the same so I did a complete reset of the phone and instaaled everything from new and the issue is solved. The bad thing is that I have no idea why.

**Comment by tibbi** [comment]
could be something device specific, Ill close it
