### ISSUE TITLE
Videos from editor have low quality

### ISSUE THREAD

**Issue by TheLastGimbus** [SimpleMobileTools/Simple-Gallery#2039]
Hi!

I'm really thankful for the video editor!

I have a problem, that I wanted to cut video from 9:16 to 16:9, and cut out portion is noticably worse than in original

I can send the video if you want

Maybe adding some "quality picker" would help

**Comment by Marvinoo** [comment]
Also in the video editor, the output viedo has less (lowered) framerates than the original video

**Comment by tibbi** [comment]
should be fixed already
