### ISSUE TITLE
Side handler for navigation doesn't help at all. 

### ISSUE THREAD

**Issue by ProblematicDude** [SimpleMobileTools/Simple-Gallery#2040]
Most of the devices these days has Side Navigation gesture. 
In the folder view the handler to navigate doesn't seems to work well. As , when i try to drag it to scroll fast. The Android detect it as gesture ( which is back gesture in my case ). and Gallery navigates back to home screen. 

Can you move that handler a bit outside of the side screen.
Something like shown in the image.  ![IMG_20210115_170126.jpg](https://user-images.githubusercontent.com/59223300/104721059-52eb8180-5753-11eb-852a-8607321515df.jpg)

**Comment by tibbi** [comment]
that sounds like a system issue, not related to the app
