### ISSUE TITLE
New feature: List decrypted spaces

### ISSUE THREAD

**Issue by DorKeinath** [SimpleMobileTools/Simple-Gallery#2048]
I would like to see pictures stored in a container encrypted with VeraCrypt. I'm opening that container with [EDS lite ](https://github.com/sovworks/edslite).

The **files** manager of LOS tells me the Uri _content://com.sovkworks.eds.android.providers.documents.lite/document/..._. and the Raw mimetype _vnd.android.document/directory_

May be it helps you to implement this feature if you know that [OpenCamera](https://sourceforge.net/p/opencamera/code/ci/master/tree/) is getting access to this kind of folders, too.

**Comment by tibbi** [comment]
that is a way too advanced thing for this app. Thanks
