### ISSUE TITLE
Cropping and saving GIF currupts it

### ISSUE THREAD

**Issue by PreciousWarrior** [SimpleMobileTools/Simple-Gallery#2056]
Expected behavior:

Open a GIF in gallery app, then select the edit option and crop it, then save it. The modified GIF file should move, and be cropped as well.

Actual behavior:

Open a GIF in gallery app, then select the edit option and crop it, then save it. Only the first frame of the GIF appears to be saved to the new file.

Opening the modified GIF in simple-gallery, the thumbnail (first frame) shows up, and the cropping looks correct. When opening the gif, nothing loads.

Device info:
lavender, unmodded LineageOS, Android 10

Latest version of app as of this issue (from FDroid)

**Comment by tibbi** [comment]
the editor isnt supposed to be working on GIFs, just images

**Comment by PreciousWarrior** [comment]
Sooo can this issue stay as a suggestion instead or do I create a new issue for that?

**Comment by tibbi** [comment]
There is no GIF editor on the roadmap, no need to keep it here.
