### ISSUE TITLE
Option to increase brightness to maximum while viewing media

### ISSUE THREAD

**Issue by aibaraiduas** [SimpleMobileTools/Simple-Gallery#206]
It would be nice if Simple-Gallery had the option of automatically increasing the screen brightness to maximum when viewing media (not when viewing folders, etc., just when one picture/movie is displayed).

So often I have to manually increase the brightness when looking at a picture, then turn it back down to prevent the battery from draining too quickly when done. This simple option makes life easier ([LeafPic](https://github.com/HoraApps/LeafPic) implements this, as an example).

Thanks.

**Comment by tibbi** [comment]
it has been added back in 2.7.1 already, just f-droid is slacking with updates.
