### ISSUE TITLE
Custom Folder Order

### ISSUE THREAD

**Issue by 6543** [SimpleMobileTools/Simple-Gallery#2065]
It would be nice to costomize order of folders.

I propose, instead of order by ... (e.g. Name,Date, ...), "Custom" where you can deside the order

Alternative a "pin folder" with priority could do it too

Thanks for the great app :)

**Comment by tibbi** [comment]
you can already pin wanted folders by long pressing them and using the top Menu -> Pin folder at the top. Custom order by drag and drop is already on the roadmap, duplicate of #633
