### ISSUE TITLE
[BUG] Widget keeps disappearing after some time

### ISSUE THREAD

**Issue by GithubUser699** [SimpleMobileTools/Simple-Gallery#2070]
**What I did**
Long press on my Launcher -> Widget -> Gallery -> choose my Folder

**Result**
I do have my widget with that desired folder now.

**But after some time…**
…it disappears (only visibility is affected) completely.
But after pressing on that space, where I placed my widget, it enters the app normaly and the thumbnail is visible again.
And again - after some random (?) time, it disappears again.

**Expected behaviour**
It shouldn't disappear.

I tested it with other widgets as well, but it didn't appear on those. I also tested it on two different launchers:
`OpenLauncher (com.benny.openlauncher)`
`Trebuchet (com.android.launcher3)`

Result remains the same.

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by GithubUser699** [comment]
**App**
com.simplemobiletools.gallery.pro (FDroid edition)
versionCode="335"
versionName="6.19.0"

**OS**
Android 10
Official LineageOS-NIGHTLY version

**PS**
I didn't set the 'Battery Background restriction' for your app.
I didn't restrict any AppOps via ADB (such as After startup, widget updating etc.)

**Comment by osirisinferi** [comment]
Same happens with the "Digital clock" widget from the stock Fairphone 4 OS (which is the [Google LLC "Clock" app](https://play.google.com/store/apps/details?id=com.google.android.deskclock)).

Disappears for no reason at unlocking, tapping it doesn't reveal it (but *does* open the app), only long-press *with* a little wiggle (so the "Remove" and "Resize" buttons appear) makes it re-appear.
