### ISSUE TITLE
Videos auto play even when autoplay disabled

### ISSUE THREAD

**Issue by xamerintime** [SimpleMobileTools/Simple-Gallery#2072]
Device i am using is a Oneplus 7t
android 10
Even when "Play videos automatically" is disabled, videos will stay play when selected. This is a issue because if I want to edit a video, i have to click a image and then scroll to said video so it doesn't autoplay.

**Comment by tibbi** [comment]
Im not sure what you mean. Where is the video playing? In the video editor? That setting isnt about the editor.

**Comment by Fich420** [comment]
> Im not sure what you mean. Where is the video playing? In the video editor? That setting isnt about the editor.

Correct, when tapping a video in "Simple gallery" it opens in Simple Gallery's editor, and it auto plays. Id record a video but after uploading this, and changing the autoplay setting 5 times, it no longer auto-plays.

**Comment by tibbi** [comment]
the autoplay toggle in the settings doesnt apply to the editor, we will see if the video editor received some option for toggling it
