### ISSUE TITLE
[Bug]No response when deleting pictures

### ISSUE THREAD

**Issue by xushet** [SimpleMobileTools/Simple-Gallery#2076]
Android11,After deleting the picture in the picture interface, there will be no response for a few seconds, and the picture cannot be swiped left and right during these few seconds,

**Comment by tibbi** [comment]
what app version are you using? Is the file on an SD card, or internal storage?

**Comment by xushet** [comment]
> 您正在使用哪个应用程序版本？文件位于SD卡或内部存储设备上吗？

version 6.19.1，pictures are stored internally，and when the app is cold-started, the image reading speed is very slow, which seems to be related to android11

**Comment by tibbi** [comment]
like how many files do you have on your device? I mean images and videos shown in the gallery.

**Comment by xushet** [comment]
> like how many files do you have on your device? I mean images and videos shown in the gallery.

There are about 6,000 pictures.

**Comment by Marvinoo** [comment]
I've the same android version and the same problem.
But I've less number of media files but as far as it seems, it has nothing to do with the number of files but the readability speed on A11. I never seen this when I used A10.

**Comment by Marvinoo** [comment]
Also most notably, the pull-to-refresh spinner takes way longer time to finish comparing to A10.

**Comment by tibbi** [comment]
some related changes will be added in 6.23.0
