### ISSUE TITLE
[FR] "Undo" button after an image is deleted 

### ISSUE THREAD

**Issue by mizzunet** [SimpleMobileTools/Simple-Gallery#2083]
Show the Undo button for few seconds after deleting in case that some are deleted accidentally.
![Screenshot_20210219-194406_1](https://user-images.githubusercontent.com/10193999/108515364-3676c380-7282-11eb-9372-fd63eb340301.png)

**Comment by tibbi** [comment]
I dont plan adding that, there is a recycle bin for recovering deleted files
