### ISSUE TITLE
Apps can't recognize pictures edited with Simple Gallery

### ISSUE THREAD

**Issue by drewblasphemepatchwork** [SimpleMobileTools/Simple-Gallery#2084]
When editing any picture with Simple Gallery, the picture choosers on apps can't recognize the image. (for example Whatsapp, Telegram, Signal, https://imgur.com/a/PNPbRBv). I can still send it if i share it from internal storage. Also, it happens if i set the format as PNG or JPG, but JPEG works. This doesn't happen on other gallery apps regardless of the format.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by drewblasphemepatchwork** [comment]
Sorry, forgot to mention it. Version 6.19.1 from F-Droid.

**Comment by tibbi** [comment]
are those files on the SD card, or internal storage?

**Comment by drewblasphemepatchwork** [comment]
Internal storage

**Comment by mathsen** [comment]
Same problem here - files in my case are on SD card. After editing a picture (e.g. cropping) with Simple Gallery (also from F-Droid), no app (Signal, Telegram, Androids Gallery) detects the picture anymore.

**Comment by spajak** [comment]
Same here. Twitter can't see screenshot images edited with Gallery...

**Comment by thaumu** [comment]
Still active. Instagram file picker doesn't recognise files saved with Simple Gallery Pro. Need to open jpg with another image editor and save without any changes to just become visible to Instagram.
Simple Gallery Pro (v 6.21.2 Pro)
Android 11 RKQ1.200826.002

**Comment by tibbi** [comment]
just upgrade to 6.22.0

**Comment by thaumu** [comment]
Problem solved, thanks for your quick response, @tibbi
Thought I've had the latest version but Google Play Store didn't show the "Update" button despite of showing the new version. F-Droid did well after updating the repositories. (just as a hint if someone runs into the same situation).
