### ISSUE TITLE
[Feature Request] Persistent App Unlock & Show Hidden Files

### ISSUE THREAD

**Issue by grravity** [SimpleMobileTools/Simple-Gallery#2088]
Suggesting the ability to have two added sub options:

The first being an option so if you have enable lock to open the app, once you do it once it is persistently unlocked until you click to your lockscreen.

The second one being the same idea, however with hidden directories/media. Also it will still be toggleable by clicking "stop showing hidden media", however it allows the user the option of persistent showing until they lock their screen (or manually stop showing).

I suggest these persistency options be added to Simple File Manager as well, seeing these two apps interact with each other in some ways.

Again both would be additional options, and they'd be two individual options ideally so the user can chose if they want persistency on app unlock but not on hidden files for example.

**Comment by tibbi** [comment]
That sounds way too confusing, dont really expect any extra settings related to that.

**Comment by grravity** [comment]
The whole point is to avoid the user needing to type in the password every two seconds they decide to open the app. it's extremely tedious and time consuming.
The only way is to remove the app lock however if they don't want to do that they now have to unlock it everytime they open the app instead of just keeping persistency until they go to the lock screen. Unlock once, it's persistent for that session.
