### ISSUE TITLE
Option to enable automatic rotation when viewing an image

### ISSUE THREAD

**Issue by Jazcafe** [SimpleMobileTools/Simple-Gallery#209]
This would turn on automatic rotation just before showing an image (if it is not already on).  Then when you finish viewing images, it would return the automatic rotation setting to its original state.

This is different to the current 'auto-rotate' option, which always rotates every image 90 degrees clockwise.

**Comment by tibbi** [comment]
the current implementation doesnt always rotate by 90 degrees, it checks the image aspect ratio. Some cameras (like Simple Camera used to) are broken, and they store the image resolution wrong. I might make it more advanced to handle such cases properly in the future.

Not sure what do you mean by this report tho, I guess fixing that issue would make it obsolete?

**Comment by Jazcafe** [comment]
Hi,

On my device most images, even full portrait images are rotated.

If not sure that your solution is trying to solve the same issue that I am proposing?  If it is, then may I suggest that my solution is very simple and solves a few other issues as well. Maybe take a look at how it works in LeafPic.  No need to think about resolution or a broken camera, and the user can rotate clockwise or anti-clockwise (or choose not to rotate at all).

I hope this makes sense :)

**Comment by Jazcafe** [comment]
I am happy, of course, to stick with your solution but please don't rotate the image until the device is rotated.

**Comment by tibbi** [comment]
Not sure which Leafpic rotation you mean, its not rotating to me. Rotating the image separately when the device rotates sounds quite like a mess.

**Comment by Jazcafe** [comment]
"Not sure which Leafpic rotation you mean".  It's an option in LeafPic > Settings > 'Force use of Accelerometer'

"Rotating the image separately when the device rotates sounds quite like a mess".  It's the same behaviour as turning on 'Auto-Rotation' in your phone settings.

**Comment by tibbi** [comment]
ah I see. I want to leave my implementation for now, that other one feels weird

**Comment by Jazcafe** [comment]
I understand.  The option that you have developed has a different purpose to my suggestion.  Would you please consider an option to enable the Android built-in automatic rotation when viewing an image.

**Comment by tibbi** [comment]
having 2 autorotating options could be confusing, so I dont promise anything for now

**Comment by Jazcafe** [comment]
Thanks.  Please consider it.

**Comment by tibbi** [comment]
ill reopen it as more people had the same issue, so Ill recheck the user experience soon

**Comment by Jazcafe** [comment]
Thanks for the auto-rotation - perfect.
