### ISSUE TITLE
Two lists for hidden folders

### ISSUE THREAD

**Issue by martin-holy** [SimpleMobileTools/Simple-Gallery#2090]
Hi, I think that there should be two lists for hidden folders. One for folders with content that I don't want to see 99% of time like application cache, resources,... and another one for folders with content that I frequently want to show or hide.
These two lists should be controlled independently.

Thank you for your work on this useful application.

**Comment by tibbi** [comment]
I dont really plan adding it, it is too confusing.

**Comment by martin-holy** [comment]
Well, then I have to wait until I have a chance to fork your code, learn Kotlin a do it myself. 😁
I have known about this app for years, but I will not start to use it until the main thing of gallery app (browsing folders and media) isn't done sufficiently enough which includes hiding cache and resources of other apps and classical folder browsing that I mention here: https://github.com/SimpleMobileTools/Simple-Gallery/issues/1987#issuecomment-782835018
It might be usable for one Camera folder, but not with tens of folders with a logical structure.
