### ISSUE TITLE
[Feature Request] Can you add flip option to the Simple Gallery Image editor?

### ISSUE THREAD

**Issue by alexpaul1994** [SimpleMobileTools/Simple-Gallery#2092]
Hello so Only Snapseed has that Flip option to images and even google photos doesn't have it and I use Simple Gallery Pro along with those apps and I use the Flip Image option regularly on Snapseed and I use Simple Gallery Pro for sometime now,It would be nice if you add flip image option to the image editor.

**Comment by tibbi** [comment]
it is already there both in the Google Play and in the F-droid version.
