### ISSUE TITLE
Inconsistent theme colouring in custom theme

### ISSUE THREAD

**Issue by rushabhgala** [SimpleMobileTools/Simple-Gallery#2098]
when I change the theme from dark to custom, the colour of the overflow menu and the back arrow(both grey) doesn't match with the colour of the rest of the icons. 
this only happens when I long press to select a photo. 

if I deselect the photo, the grey colour of the arrow and the overflow menu goes back to white and becomes consistent with the other icons.
I've attached screenshots of my custom colours, icons before selecting a photo and after selecting a photo
![Screenshot_20210303-234424](https://user-images.githubusercontent.com/46610083/109913028-35c72f80-7c7b-11eb-894f-52fd2300ff3b.jpg)
![Screenshot_20210303-234332](https://user-images.githubusercontent.com/46610083/109913032-38298980-7c7b-11eb-87b5-8e732ca92bbd.jpg)
![Screenshot_20210303-234340](https://user-images.githubusercontent.com/46610083/109913035-3b247a00-7c7b-11eb-815c-c5a212de376e.jpg)

steps to reproduce the bug:
Go to settings and change the theme to custom. select 000000 as the background colour, select orange as the primary colour. exit from settings. select any image or image folder and notice the colour of the icons. 
P.S. even though, I've not uploaded the screenshot, this issue was observed even when I selected primary colour other than orange.

**Comment by tibbi** [comment]
ye the menu is difficult to customize, it will have to be remade fully. Anyway, it affects all apps, not just gallery, so Ill close this. Im aware of it. Thanks
