### ISSUE TITLE
Order by acquiition time not working

### ISSUE THREAD

**Issue by igor-cali** [SimpleMobileTools/Simple-Gallery#2099]
Order by acquisition time (EXIF metadata) does not work properly.

Actions:
1. Copied old pictures (with old EXIF acquisition dates) from the PC --> file timestamps are newer due to the file copy).
2. Selected "Order by acquisition time" in the options, descendant order.

Observed behaviour: These old pictures are shown first in the folder
Expected behaviour: Pics correctly ordered by acquisition dates.

Thanks!

**Comment by tibbi** [comment]
Hey, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by igor-cali** [comment]
> Hey, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

It fixed the ordering.
Any reason why this has to be done manually?

**Comment by tibbi** [comment]
ye, file management on Android is a big mess and background activity is limited always more
