### ISSUE TITLE
Add "quick actions"

### ISSUE THREAD

**Issue by andree182** [SimpleMobileTools/Simple-Gallery#210]
Would be nice, if there was at least one action button to edit image in external image editor (e.g. Snapseed; also it should remember it + there should be a way to change it), and one button/icon for sharing the image (to social network, email etc. - this one should probably ask at each use).

**Comment by tibbi** [comment]
Hello, there is an Edit actionmenu button and you can set a default editor too, you just cannot reset it inside the app. System settings should be used for changing default apps, individual apps shouldnt be messing with that.

You have a Share button too at both fullscreen view and thumbnails, just long press a thumbnail. Share action always asks for an app to select, you cannot set a default one.

**Comment by andree182** [comment]
Okay, the former and latter are fair points.

But I don't see the edit button, nor share button - only menu entries. Or is that whay you meant?

http://cdn03.androidauthority.net/wp-content/uploads/2016/04/Gallery-KK-screenshot-840x473.jpg is +- what I had in mind (the middle pic, -the layout).

Anyhow, perhaps I'll find some time to create a pull request (if you thing it would be even accepted), if no one finds time for it in the meantime.

**Comment by tibbi** [comment]
You should see such entries at photos. If you dont see them, the image might not be properly recognized as an image type. I dont want to add any floating action buttons, every action is just 2 clicks away and people dont need any action in 99% of times, they just want to view the images.
![screenshot_20170327-133800](https://cloud.githubusercontent.com/assets/528931/24354589/b1910704-12f2-11e7-9bdc-e93b8422887b.png)

**Comment by andree182** [comment]
Yes, of course it's there. Counterargument - the floating button is quite non-invasive, and can be hidden in full-fullscreenmode (when not even menu is shown). And IMO it is much faster/pleasant to use, than the menu.

But in the end you are the author, so unless you don't even want an setting for this, you can close this ticket. In the worst case, I'll do it in a fork (but more likely just get used to the current state :) ).

**Comment by tibbi** [comment]
It is easy to add, but like how often do people need the Edit button? Really rarely. Thats what I want to avoid with my apps, showing features they dont need. Maybe you use Edit often, but maybe someone uses Share often, someone wants Delete there. Making that action customizable would also create an unnecessary setting, so Im closing it for now.
