### ISSUE TITLE
[Bug] Incorrect Indian holidays 

### ISSUE THREAD

**Issue by mohitsoni-dev** [SimpleMobileTools/Simple-Gallery#2100]
Many Indian holidays for year 2021 are wrong in the calendar. Examples:
Actual date for Holi is 28 March IST in the app it is 23
![image](https://user-images.githubusercontent.com/59525097/110197045-cdd93a80-7e6e-11eb-8b5d-cd8a1cfe79f5.png)
Mahavir Jayanti is on 25 Apr and Sri Ram navami is on 21 Apr but these events are on wrong dates in the app.
![image](https://user-images.githubusercontent.com/59525097/110197087-0f69e580-7e6f-11eb-8e81-295715c34815.png)

There are many more wrong holidays.

**Comment by tibbi** [comment]
you reported it into the Gallery repository, please move it to the calendar
