### ISSUE TITLE
Mark favorites in overview (star)

### ISSUE THREAD

**Issue by PinkPlasticBeach** [SimpleMobileTools/Simple-Gallery#2102]
Hello
And first of all thanks for the many nice "simple" apps in orange.

I like the simplicity of this APP but Theres one thing im really missing:
When marking photos AS Favorites (star) i find them in a special Album/folder but i cant See its a favorite Ehen scrolling through the overview.
This would be great for sorting out photos when theres many that are alike and i just want to keep one/two best shots. I usually swipe through the photos in fullscreen mode and give the ones i really like a star. But going back to overview i cant identify the ones i chose, cause theyre so small i cant See the difference. I would like to select multiple photos in overview and delete all that look alike, keeping the favorites.

I believe thats not hard but would make the APP a lot better for me.
I think it should be default with opt-out in the settings.

Next nice thing would be writing the star to exif-info of the image to be able to quickly identify favorites if i dump the whole collection to my desktop...but thats another wish actually.

Thanks again for these nice tools, kindly
Plastic Beach

**Comment by AlbatorV** [comment]
I reuest this too. Please add a litlle star icon over image when browsing folders.
