### ISSUE TITLE
Pin location using 'Pin to the Top' is somehow out of place (list view)

### ISSUE THREAD

**Issue by arol9** [SimpleMobileTools/Simple-Gallery#2109]
Wouldn't be better to locate 'Pin icon' in upper area (see pics) of path section. This lower Pin position is somehow out of place.

![pin](https://user-images.githubusercontent.com/80759040/111806971-45688a00-88b1-11eb-94de-3df500f9650c.png)

![pin fixed](https://user-images.githubusercontent.com/80759040/111807024-50bbb580-88b1-11eb-97f4-33a93729f453.png)

**Comment by tibbi** [comment]
dont you have folder thumbnail on the left side? What app version are you using?

**Comment by arol9** [comment]
The image was cropped to focus on pins position in question

**Comment by tibbi** [comment]
that is the intended behaviour, as there are more possible icons being shown and folder names with paths can be long, so it was moved at the bottom

**Comment by arol9** [comment]
take a look at how it'd look in reverse order ...

![reverse order](https://user-images.githubusercontent.com/80759040/111917028-97014800-8a5c-11eb-9acc-a3aba9c62c06.png)
