### ISSUE TITLE
Add round/circle pattern for cropping pictures

### ISSUE THREAD

**Issue by linesquarecube** [SimpleMobileTools/Simple-Gallery#2118]
Hi, first of all - I love Simple Gallery and some other SimpleMobileTools :)

But, there is one Feature I really miss in the editor of Simple Gallery. It would be great to have a round/circle pattern for cropping pictures. Currently there is only the possibility to crop an image with a square or rectangular pattern as shown in the screenshot below. 

Thanks for considering this for a future update!

<p align="left">
  <img src="https://user-images.githubusercontent.com/81855936/114766590-e0e10380-9d66-11eb-8ec5-648438af969c.png" width="350" title="screenshort">
</p>

**Comment by tibbi** [comment]
that is the editor of the deprecated app version, it wont receive anything new. Get the Pro version from Google Play for the advanced editor (it doesnt have circle crop either though)
