### ISSUE TITLE
[feedback]Slow loading speed on devices with a large number of pictures

### ISSUE THREAD

**Issue by xushet** [SimpleMobileTools/Simple-Gallery#2119]
Maybe it's a problem,

When the number of device pictures is too large, the pictures will be displayed blank for a while before loading pictures.

The number of pictures on my device is about 10,000 to 15,000

![Screenshot_20210416-101444_图库.png](https://user-images.githubusercontent.com/34502902/114962582-86968e80-9e9d-11eb-81a7-9796b3d68025.png)

**Comment by tibbi** [comment]
some performance improvements are already on the roadmap and reported. Make sure "Speed" is selected as the "File loading priority" at the top of the app settings and not "Compromise".
