### ISSUE TITLE
Simple Gallery Pro without Play Store

### ISSUE THREAD

**Issue by Pippo8291** [SimpleMobileTools/Simple-Gallery#2120]
Is it possible to purchase the Simple Gallery Pro without the connection to google services? The installation of the current apks fails and my suggestion is, that this corresponds to the missing connection to Google play or at least to missing google services. Is this correct and is there a possibility to get the full Simple Gallery Pro version?

The version i've got is named Simple Gallery Pro, but there are some editor settings missing(video editor and some filter options in comparison to the provided screenshots in the play store), which would be very nice to have.

PS: Thanks for multiple great apps that are using the minimal amount of permissions and giving the nearly maximum of useful functionality.

**Comment by tibbi** [comment]
ye, all Google Play .apk versions can be found here on Github too, at https://github.com/SimpleMobileTools/Simple-Gallery/releases . You wont be receiving updates by downloading the file though. You can send any optional donation at https://www.simplemobiletools.com/donate/ . Thanks

**Comment by Pippo8291** [comment]
Y, but the installation of those apks always say, that the app wasn't installed. I was guessing, that this is connected to the missing google services or play store maybe. Am i right with this and is there a way to change this? The installation from f-droid is possible, but the editor looks very different to the picture of the playstore and some functions are missing (insert text, stickers, and so on).

**Comment by Pippo8291** [comment]
Just to show what happens this pic is the output on my trial to install the current apk (6.19.6) from this git release section. Same output for former releases 6.19.5 or 6.19.4.

![db04ca3e-6154-4c4b-8b20-b038737025bb](https://user-images.githubusercontent.com/28839076/115200314-5e549d00-a0f4-11eb-868e-077370d87715.png)

My gallery editor options, installed from F-Droid, are looking like this:
![933a79b7-439a-4e5e-8c03-641022ab949d](https://user-images.githubusercontent.com/28839076/115200396-775d4e00-a0f4-11eb-846e-7181a29b517d.png)

I was wondering if there are some options missing, because on the picture of the playstore there are options like "Text Field" and "Sticker" shown to insert. Thank you for your quick reply and help.

**Comment by tibbi** [comment]
Github version should work just fine and it contains the advanced editor. The app doesnt require anything Google specific, so that isnt causing your issues. It is hard to say where is the issue, could easily be something device specific. You will have to look around for some solution.
