### ISSUE TITLE
Sharing single image with ExifEraser stopped working with 6.19.6

### ISSUE THREAD

**Issue by szpak** [SimpleMobileTools/Simple-Gallery#2121]
I'm no longer able to share a single image with ExifEraser (sharing multiple images works fine). I initially reported it there, but they had no changes in the meantime and I suspect that [change](https://github.com/SimpleMobileTools/Simple-Commons/commit/c9c5682bc1a43eb495c598cc3014ea19a0f53946) in commons caused it. The author of ExifEraser [joined that opinion](https://github.com/Tommy-Geenexus/exif-eraser/issues/25#issuecomment-827350778):
> A single image shared with ExifEraser has an improper MIME type (text/uri-list) instead of image/jpeg,
and as such is flagged as unsupported.

and suggested:
> You may ask the author of said app to create a ClipData with a proper Uri MIME type (i.e. not using ClipData.newRawUri() but ClipData.newUri() instead)

What was the reason of that change? Would it be possible to bring it back?

**Comment by meelon** [comment]
I have the same issue using Scrabled Exif app. It was working before, but now it is not working neither fro one file or multiple files. It just show at the bottom error "An error occured while scrambling <File name>...". Scrabmling itself works using different gallery apps.

**Comment by tibbi** [comment]
should be fixed in 6.20.0
