### ISSUE TITLE
Enhancement: provide a grey theme that doesn't have the colored top bar or fine tune the UI so it follows Material Design v2 guidelines

### ISSUE THREAD

**Issue by blackandyellowgecko** [SimpleMobileTools/Simple-Gallery#2123]
Currently, the Simple Gallery (and all of the Simple Mobile tools) uses Material Design v1, which is outdated and doesn't play well in dark mode (because of the top colored bar). The pitch black resembles Material Design v2, but the Material Design v2 guidelines advises using dark grey to avoid eye strain.

Version: 6.19.6
OS: Android 11

**Comment by tibbi** [comment]
report it at https://github.com/SimpleMobileTools/General-Discussion/issues please, it affects all apps
