### ISSUE TITLE
Suggestions for hiding albums

### ISSUE THREAD

**Issue by Ciel-Chen** [SimpleMobileTools/Simple-Gallery#2124]
It is hoped that when the user hides an album and needs to open the hidden album, there will be a separate space for the hidden album, instead of showing the hidden album and the unhidden album mixed together.
In addition, I found that when I used photo album to crop pictures after taking screenshots in the system, the newly generated pictures would be slightly green, like an extra layer of mask.
Finally, thank you very much for this software. I like it very much.

**Comment by tibbi** [comment]
Hiding works as expected. By default the hidden folders arent shown, only if you enable it. 2. you mean that if you edit an image with this gallery, it has a green layer? Does it happen to new screenshots only, or any image?

**Comment by Ciel-Chen** [comment]
> Hiding works as expected. By default the hidden folders arent shown, only if you enable it. 2. you mean that if you edit an image with this gallery, it has a green layer? Does it happen to new screenshots only, or any image?

1.Is there any way to temporarily hide other non-hidden files when hidden files are displayed?
2.Yes, my mobile phone is OnePlus 8Pro, but when I use simple-gallery to edit the image after screenshots, there will be a very light green layer. Interestingly, this situation will only appear after the screenshots of WeChat chat, but other software interface screenshots have not been found.

**Comment by tibbi** [comment]
I dont plan changing the way un/hiding works now. Related to the screenshots, I dont think it is our apps issue. Seems like they are adding the green layer.
