### ISSUE TITLE
[Bug] "Group direct subfolder" hidden files issue

### ISSUE THREAD

**Issue by nicpadilla** [SimpleMobileTools/Simple-Gallery#2126]
**Steps to reproduce:**
- "Group direct subfolders" is enabled
- Select image/video to either move/copy
- select "move to" or "copy to" on selected image
- in the "select destination" menu that appears, click on the eye button at the bottom to display hidden files/folders
- select a hidden folder to view hidden sub-directories

**Expected behavior:**
- Menu should now display all (hidden) sub-directories within the previously selected (hidden) directory

**Current behavior:**
- None of the hidden sub-directories populate. The menu is blank, as if we have not just selected the eye button to show hidden items
- The eye button is no longer available to press either

**Device info :** Oneplus 8 Pro - OOS 11.0.5.5.IN11AA
**App info :** Simple Gallery Pro 6.19.6 Purchased from Google Play.

**Comment by nicpadilla** [comment]
I should also note, this bug does not occur if before I do any of the mentioned steps, I go into the menu and select "Temporarily show hidden".

**Comment by tibbi** [comment]
closing this as with version 6.23.0 and Android 11+ you wont be able to see hidden files anymore
