### ISSUE TITLE
Copy files from oldest to newest when option to preserve Last-Modified is active in settings

### ISSUE THREAD

**Issue by findow** [SimpleMobileTools/Simple-Gallery#2135]
Long story short, after a bit of research apparently Android 7 (which I have) does not have any API to copy the Last-Modified value of a file to an SD Card, it was introduced in Android 8.

After trying different apps I arrived at a conclusion: I do not care about the Last-Modified value at all, all I care is that the copied images at the SD destination get shown on any Gallery App in the same order I see them on my tablet (when sorted by Sort by Last-Modified).

So here is my request: when doing batch copying of files from tablet/smartphone to an SD card (I suppose in general this is valid to any destination) _please sort the copying order of the selected files from oldest to newest when copying to destination_, this way the showing order by Last-Modified on any Gallery Apps should be preserved.

I have no idea if this works at all, and I do not know if a small delay should be introduced after each copied file so that New Last-Modified value at the destination keeps to be incremented with each copied file.
Note: Apparently Last-Modified has a resolution of 1 millisecond, so in theory at least 1 millisecond should be waited with each copied file, better 2 milliseconds.

This request extends to Simple-File-Manager too.
Thank you.

**Comment by tibbi** [comment]
have you disabled the last_modified preservation in the app settings? What app version you use at all?

**Comment by findow** [comment]
As far as I know I have the setting enabled on both apps, as for version I have the latest on f-droid.

**Comment by tibbi** [comment]
I dont know what you mean then, just disable the setting if you want it changed.

**Comment by findow** [comment]
If in Simple File Manager I select a folder (or multiple folders) and decide to copy it (them) on an SD card, in which order are the files copied to destination?

My request is: 
1) list (in the app logic) all files to be copied from oldest Last-modified to newest
2) Copy said files one by one with a wait of 2 milliseconds after each copy

Result:
At the destination on the SD all files will have a new Last-Modified (the time they were copied on SD) but it will be incremental (thanks to the 2 milliseconds delay)

Gallery App should now show them in the same order as if they were on the smartphone since the Last-Modified incremental order is preserved.

**Comment by tibbi** [comment]
They should be copied in the order they were selected, or if you select a whole folder, they are copied in the order in which the system lists its files. I dont plan adding any artificial delay or difference there.
