### ISSUE TITLE
[Feature request] Video control for animated gifs

### ISSUE THREAD

**Issue by TheDeveloper65** [SimpleMobileTools/Simple-Gallery#2138]
Some animated gifs have long playtimes, making them more like videos. However, the current full-screen mode plays animated gifs the moment they are loaded, even when they are not the item in focus. For short looping gifs, this behavior is not noticeable, but for gifs with playtimes comparable to videos, you'll find them partway through the animation instead of starting from the beginning. Which results in the user having to exit and re-enter full-screen mode to start the gif from the beginning.

For gifs with multiple images, could you:
- Implement video-like controls? (Time/Frame scrubber)
- When in full-screen mode, pause the GIF when they are not in focus.

**Comment by tibbi** [comment]
I dont plan adding video controls, gifs work in a different way. We will see if pausing will be added, likely not anytime soon. Ill close this for now.
