### ISSUE TITLE
[Feature Request] Option to Sync to Cloud? 

### ISSUE THREAD

**Issue by pixincreate** [SimpleMobileTools/Simple-Gallery#2141]
I know, this might go against your idealogy but I think it's one of the most needed feature as of today's generation!    
## What I want:
- An option to sync with the **Cloud storage**.  

#### My thinking:
I use Nextcloud as my server for syncing my data(images, videos, Joplin notes, etc..).  
On the other hand, Google photos have the ability to sync the photos to Google drive.  
What I'm expecting is that, **giving an option in the _gallery_ app to sync with the Cloud would make the things get better!**.   

## Alternatives that I've considered:
Nothing but, syncing everything directly to Nextcloud via AutoAdd option.

## Suggestion:
If you're pleased with my **Feature Request**, I'd recommend you adding multiple cloud options for sync like we've in Solid Explorer.  You can basically use any of the favourite cloud service. Right?
If yes, here are some cloud services that you can add:
- Nextcloud(require URL, Username and Password)
- Owncloud
- OneDrive(Not recommended for Privacy reasons, but you can add and the option is left to users).
- Dropbox
- Mega
- Google Drive(Not recommended for Privacy reasons, but you can add and the option is left to users).

**Comment by tibbi** [comment]
yep, the app has no internet access so dont expect any cloud support. You can set up some other app for syncing while Simple Gallery just shows the loca lfiles.
