### ISSUE TITLE
Performance issue WEBP

### ISSUE THREAD

**Issue by Nabokov86** [SimpleMobileTools/Simple-Gallery#2146]
Starting from version 6.16, the application consumes significantly more resources when displayed WEBP in full-screen mode. When the WEBP is displayed, CPU heats up to 70 degrees, then the throttling starts.

Before the version where WebP animation support was added, there is no performance issue.

App version: 6.16.0 - 6.20.1
Device: arm, android 7 and 9

**Comment by tibbi** [comment]
do you have a rooted device, or one modified in a similar way?

**Comment by Nabokov86** [comment]
@tibbi 
My apologies for the late reply.

Yes I have a rooted device. You need a logcat, right? For some reason, I can't get logcat on my device. If I can figure it out, I'll send it to you. Sorry for that.

**Comment by tibbi** [comment]
I dont need logcat, that wouldnt help. Does it work well in other apps?

**Comment by Nabokov86** [comment]
@tibbi Yes, works well in other galleries. And as I mentioned earlier, everything is fine in the older versions. Now I downgraded on version 6.15.6, work great.

**Comment by tibbi** [comment]
retry with 6.26.8 once it becomes available

**Comment by Nabokov86** [comment]
@tibbi Sorry for the delay! I have just installed version 6.26.8 and unfortunately I am still able to reproduce it.

**Comment by gmasil** [comment]
I can reproduce this issue. Static webp images produce significant more CPU usage and even with animated webp files you can see that more fluent animations will be less heavy on CPU than more slideshow like animations.
I will investigate and try to fix this.

**Comment by tibbi** [comment]
should be fixed in 6.28.x
