### ISSUE TITLE
Crop and draw without saving in between

### ISSUE THREAD

**Issue by franga2000** [SimpleMobileTools/Simple-Gallery#2147]
Currently (v6.19.5) it does not seem to be possible to both crop an image and draw on it without saving and re-opening it in between. I'm not sure whether this is a bug or simply not a feature - in case of the latter, consider this a feature request :grin: 

**Steps to reproduce:**

 - Open image in editor
 - Crop it
 - Switch to drawing mode

**Expected behavior:** You can draw on the cropped image

**Current behavior:** The crop is reset - you're drawing on the whole image

The same happens in the reverse order (see video) and only the crop or the drawing is present in the saved image (so it's not just a UI issue).

https://user-images.githubusercontent.com/3891092/119981763-49560e00-bfbe-11eb-9472-98128b7d9e66.mp4

**Comment by ubergeek77** [comment]
@tibbi Will the latest version with the improved editor be released on F-Droid soon? 6.21.2 (latest on F-Droid) still has the old editor.

I see the proprietary version of the updated APK in your GitHub releases, but I would like to have this on F-Droid with the rest of my apps.

**Comment by tibbi** [comment]
that advanced editor is not open source so it cannot be added on f-droid. It will never get there.

**Comment by ubergeek77** [comment]
I see. It's a shame that decision was made.

Well, I still see source tags for 6.22.3, will F-Droid be updated to that regardless of the editor?

**Comment by tibbi** [comment]
yeah, f-droid uses a basic editor, the app will keep being updated. The separation between the advanced and basic editor is there for like 2-3 years now, it is nothing new.

**Comment by ubergeek77** [comment]
Ah, ok, I misunderstood. Just started using this app today.

Well, pretty much all of my concerns of using the closed source version were addressed when I saw that there doesn't seem to be any trackers in the app, and it doesn't even have permissions to go online. So that's good enough for me.

Thanks!

**Comment by tibbi** [comment]
yeah, being closed source doesnt mean that it is dangerous at all
