### ISSUE TITLE
Images with "BURST" in filename not shown

### ISSUE THREAD

**Issue by adatum** [SimpleMobileTools/Simple-Gallery#2150]
Simple Gallery seems to filter out images with `BURST` in the filename, such as those taken in Portrait mode of Google Camera. Is this a "feature" and can it be disabled so that all images are shown? 

Right now it is tedious editing filenames manually to have them appear in Simple Gallery. Other image gallery apps are not affected.

**Comment by tibbi** [comment]
Try enabling "Portrait" at the top Menu -> Filter. What app version are you using at all?

**Comment by adatum** [comment]
That's it! The checkbox for "Portrait" in Menu -> Filter was not selected by default. I can't believe I didn't see that, but at least it's not a bug. I'm using v5.20.1 Pro from F-Droid.
