### ISSUE TITLE
Videos edited through Simple Gallery freezes at the last few seconds

### ISSUE THREAD

**Issue by mudslapj** [SimpleMobileTools/Simple-Gallery#2157]
Whenever I do some quick video editing through this app (cropping, trimming, etc.), the last few seconds of the video post-edit gets frozen to a single frame, yet the audio continues to play until the video ends.

Tried playing the video with other players and the same issue persists, so it's most likely the editor or the video renderer part of the app that's messing up the videos.

**Comment by tibbi** [comment]
retry with 6.20.2 that will be released soon
