### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by OffifialMITX** [SimpleMobileTools/Simple-Gallery#216]
Please do not write the english translations to fill the other languages, it makes it harder to find the strings which must be translated.

**Comment by tibbi** [comment]
Its an android rule, all language files must contain all strings. And at least the order of the strings is the same everywhere. If you want to see which strings changed recently, press the History button right near the pencil at the given strings.xml.

**Comment by OffifialMITX** [comment]
Well, I've seen plenty of apps which do not follow that rule.

I'm using Stringlate by the way, there's no history option.

Am 30. März 2017 11:59:42 MESZ, schrieb Tibor Kaputa <notifications@github.com>:
>Its an android rule, all language files must contain all strings. And
>at least the order of the strings is the same everywhere. If you want
>to see which strings changed recently, press the History button right
>near the pencil at the given strings.xml.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Gallery/issues/216#issuecomment-290362383

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9/p≡p gesendet.

**Comment by tibbi** [comment]
maybe the check can be disabled somehow, but I dont want to mess with it anyway. That wouldnt be maintainable
