### ISSUE TITLE
Motion Photo support

### ISSUE THREAD

**Issue by dic1911** [SimpleMobileTools/Simple-Gallery#2160]
Hello, I'm aware of there's existing issue related to motion photo, but here's a [commit](https://github.com/dic1911/Simple-Gallery/commit/2c007071fce290febf81df151b36a0d684b56d43) as a reference.

(The code already has the ability to detect and extract video from motion photo produced by google camera.)

**Comment by tibbi** [comment]
duplicate of #1426
