### ISSUE TITLE
System-UI crashes after trying to delete an already deleted screenshot

### ISSUE THREAD

**Issue by impeira** [SimpleMobileTools/Simple-Gallery#2161]
To reproduce:
1. Take a screenshot
2. Delete it (within the app or an explorer so the app notification with the screenshot stays put)
3. Now try to delete it via the app notification
4. System-ui crash

**Comment by tibbi** [comment]
What app and OS version are you using? Do you have a rooted device, or one modified in a similar way?

**Comment by impeira** [comment]
Fairphone 3 with Android 10.
It is neither rooted nor modified (i assume).
I'm using F-Droid, maybe this can narrow it down.

**Comment by tibbi** [comment]
how is it related to our app at all actually? Screenshot deleting with those quick buttons arent related to the gallery, it is handled by the system

**Comment by impeira** [comment]
Oh.. you're totally right. I guess the possibility that the system itself is fauly was not what I expected.
My mistake, sorry for the inconvenience!
