### ISSUE TITLE
New icons 

### ISSUE THREAD

**Issue by iJahangard** [SimpleMobileTools/Simple-Gallery#2165]
I like new outline google material icons (quantum icons)
I tried some of them by moding the app

https://mega.nz/file/6JohWArR#TVBBgDnvL9D6t6xSvtHzRk0RuNlNMei9Qy_IGczA5xI

https://mega.nz/file/PVxF2KDS#YBxWkflalicOsTNA5-GP6YvGG1Q_tpcKRU-qjR_gNJc

**Comment by tibbi** [comment]
not really, I dont want to change them. Thanks
