### ISSUE TITLE
[Improvement] Add tooltips to icons on the bottom bar

### ISSUE THREAD

**Issue by Aga-C** [SimpleMobileTools/Simple-Gallery#2167]
Hi,
I think that it would be useful to add tooltips to icons on the bottom bar. Currently, icons on the title bar have tooltips, so it would make UX more consistent.
It would be especially useful in the photo editor.
Thanks!

**Comment by tibbi** [comment]
Do you have the app from Google Play, or some other source? There are 2 versions of the editor.

**Comment by Aga-C** [comment]
I am using the F-Droid version.

**Comment by tibbi** [comment]
that editor isnt worked on anymore. Anyway, some long press tooltips at the fullscreen view could be added
