### ISSUE TITLE
Gesture Controls Are Active Even When Off

### ISSUE THREAD

**Issue by puppykickr** [SimpleMobileTools/Simple-Gallery#2169]
I have gesture controls off.
During video play, when I inadvertently move my hand/finger up or down the right side of screen, the volume goes up and down- on the left side the brightness goes up and down.

It appears that the changes to these settings are only during the use of the app, as they revert to previous settings when leaving the app, so that is ok, I just wanted you to know.

Android version: 9
Device: Motorola e6 (XT2005DL)
App version: 6.20.2

**Comment by tibbi** [comment]
not sure what you mean here. Those gestures are handled by our app, not the system.
