### ISSUE TITLE
Move to new folder

### ISSUE THREAD

**Issue by stonecrusher** [SimpleMobileTools/Simple-Gallery#2172]
Is it possible to move a selection of pictures into a new folder that can be named?
Exact location of folder is not important. But I don't transfer photos from my phone to the PC every week, so it is important that they are sorted / grouped beforehand.

I can move pictures to an existing folder that already has pictures in it.
If I create a folder with anther app, it is not shown because it is empty.

**Comment by tibbi** [comment]
sure, just press "Other folder" at the bottom left corner of the destination picker, navigate to the wanted parent folder and create a new one by pressing Plus at the bottom right corner.

**Comment by stonecrusher** [comment]
aah there, got it.
thank you!
