### ISSUE TITLE
Editing Tools not showing

### ISSUE THREAD

**Issue by yesNOmaybe69420pogchamp69** [SimpleMobileTools/Simple-Gallery#2178]
A lot of the editing tools aren't showing. (Im using the pro version from fdroid)
![](https://file.io/j7om8HrtHbNf)
![](https://file.io/FgQQ7y7ISnLS)
![](https://file.io/7OxCPLbsLZUy)

**Comment by tibbi** [comment]
F-droid doesnt have the advanced editor as it is not open source. It is available only in the Google Play or Github version.
