### ISSUE TITLE
'Hide folder' causes havoc

### ISSUE THREAD

**Issue by pilsnerbeer** [SimpleMobileTools/Simple-Gallery#2179]
I created a new folder 'ABC' in root storage. I moved some pictures there and because I wanted to hide them , I went over to simple gallery, selected the folder and clicked 'hide folder'. It gave warning about .nomedia,  so I clicked yes. Folder hidden, but now when I check it using file explorer I see that somehow its full of stuff that I never put there, presumably from /Downloads but perhaps from other locations also.

**Comment by tibbi** [comment]
the app doesnt support root folders, dont expect having it

**Comment by pilsnerbeer** [comment]
Tibor, can you elaborate? so far the app is working correctly whilst showing all my pictures and videos found in emulated/0/  i.e what I called root storage. The app was also successful at hiding the folder.

**Comment by tibbi** [comment]
that is the internal storage then, not root. I dont know what files were put in there, our app isnt creating anything

**Comment by pilsnerbeer** [comment]
as mentioned in the issue, as soon as I told the app to hide the folder, it got populated with tens of files (likely from my Downloads folder, I am guessing they were moved).
