### ISSUE TITLE
Slow performance when updating content

### ISSUE THREAD

**Issue by Marvinoo** [SimpleMobileTools/Simple-Gallery#2181]
My Gallery's overall performance feels slow specially when I try to update content by pulling to refresh. 
Here's a video shows how much time it takes the spinner to stop after pulling it in a folder that contains little number of files. 

https://user-images.githubusercontent.com/45720537/126319759-2457bbcf-2397-4e91-b674-e7fc72b82b36.mp4

I don't remember I had this problem back in the days of Android 7, but since upgrading to Android 11, I noticed this performance degradation. But then I thought it might be my Settings that could be responsible for this _(Since I use sorting by Random on all albums)_ but this morning I reset all the app's settings to their defaults and reinstalled the app but after trying it freshly installed, I found the slowness is still there no matter what I do.

My device and system :
- Device : Samsung Galaxy Note 3 
- Android 11, (LineageOS based Rom)
- Latest Pro version of Gallery from Playstore. 

Note  : I tried other gallery apps from PS like Piktures, and apparently they're much faster and take like no time to load content.

**Comment by tibbi** [comment]
what do you have selected as the "File loading priority" at the top of the app settings? Do you have "Portrait" images enabled at the top Menu - Filter?

**Comment by Marvinoo** [comment]
I reinstalled the app so that all the settings are set by default. 

> what do you have selected as the "File loading priority" at the top of the app settings? 

Speed. _(default setting)_

> Do you have "Portrait" images enabled at the top Menu - Filter?

Portrait is **_Unchecked_** but all the options above it are **_Checked_**. _(default setting)_

**Comment by tibbi** [comment]
how about using some other sorting? Are all of them slow?

**Comment by Marvinoo** [comment]
> 
> 
> how about using some other sorting? Are all of them slow?

I made my test and found that **All** sorting methods run fast except by **Date taken** & **Last modified.** This is when I pull the spinner whilst inside folders. But in the Main view _(where all folders are showing),_ spinner will always take time to finish loading no matter what custom sorting method is set inside folders or in the main view itself!

**Comment by tohojo** [comment]
I'm also experiencing severe performance problems, but only when opening large folders: my main camera folders takes about 25 seconds to open - i.e., it doesn't display *anything* on the screen for 25 seconds. This folder has just over 6k images in it, and the delay seems to be roughly the same regardless of sort or group settings.

I have two other folders with between 1-1.5k images in them. One opens instantly whereas the other takes 10-15 seconds. The slow folder contains images from the phone camera (so high-res and with Exif data), whereas the other is mostly images downloaded from apps (so smaller and mostly without exif).

The stock gallery app has no problem displaying the main (6k) photo folder pretty much instantly...

**Comment by tibbi** [comment]
retry with 6.23.0 once it gets, whole file fetching will change on Android 11+
