### ISSUE TITLE
Selected pictures reset when changing orientation.

### ISSUE THREAD

**Issue by vi** [SimpleMobileTools/Simple-Gallery#2182]
Steps:

1. Orient the device in portrait mode
2. Start Simple Gallery Pro version 6.20.3 from F-Droid
3. Go to, for example "Camera" folder
4. Long-press on some photo, observe orange checkmark appear on it
5. Change device orientation to Landscape

Expected:

Gallery shows landscape UI, preseving selection mode and selected photos.

Actual:

Gallery shows landscape UI in usual mode, as if without "4.".

**Comment by tibbi** [comment]
ye it is a more generic issue, I dont really handle rotations anywhere, so Ill close this specific one

**Comment by vi** [comment]
Was is meant by "handling rotations"?

For example, it stays in the same folder after rotation instead of going to root. Does it count is handling rotations?

If including selection into model that is preserved by rebuilding UI after rotations is too tricky to implement then at least rotations should be temporarily disabled when doing multi-select. It is not fun to lose selections of e.g. 50 photos from 600 just because of some unfortunate movement of the device.

> so Ill close this specific one

I think the issue should stay open even if there is no intention to implement it. This prevents it from being reported again and again, helps prioritisation by counting reactions and attracts third-party contributions aimed at fixing this.

**Comment by tibbi** [comment]
it should be somewhere at the General Discussion repository as it affects all apps. But I dont really plan doing any major work around rotations now.
