### ISSUE TITLE
Cannot batch-unselect a range of pictures

### ISSUE THREAD

**Issue by vi** [SimpleMobileTools/Simple-Gallery#2183]
1. Start Simple Gallery Pro version 6.20.3 from F-
2. Long-press some photo to enter selection mode. Observe the orange checkmark
3. Long-press another photo to select e.g. a series of 40 photos. Observe many more checkmarks.
4. Within a range of selected pictures, long-press on some checkmarked photo.

Expected:

Selection is removed from that photo, second long-press on a selected photo deselects a range of selected pictures.

Actual:

There is short vibration feedback as it accepts the long-press, but nothing visibly changes - the photo remains checkmarked.

**Comment by tibbi** [comment]
I dont plan changing that, it would become really confusing
