### ISSUE TITLE
Problem with sort by 'date taken'

### ISSUE THREAD

**Issue by sciurius** [SimpleMobileTools/Simple-Gallery#2184]
I have a gallery with a couple of images. Sorting is set to 'date taken' but it seems that the actual sort is on 'last modified'.

When I view the images one by one and show the exif data, there are two timestamps, the modfied date and under it the date taken. The order the images are shown is on modified date, even though the setting is to sort on date taken.

![photo_2021-07-20_21-47-34](https://user-images.githubusercontent.com/1118804/126386415-e8de7c76-ac7f-437f-a76e-adb4601e1cc2.jpg)

Note that the filenames are derived from the date taken exif data. Also, the last 4 digits are the image sequence number from the camera.

Can you reproduce this?

Gallery v 6.20.3 Pro on Samsung Galaxy Note S4, Android 10.

**Comment by tibbi** [comment]
try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by sciurius** [comment]
Does this mean that Gallery somehow picked the wrong date initially?

**Comment by tibbi** [comment]
checking file by file would be really slow, so at sorting by Date Taken the app relies on the system MediaStore, which is kind of an internal database storing file metadata, like Date Taken. If you do "Fix Date Taken values", it takes the Date Taken from the file itself and updates the value in the database.
