### ISSUE TITLE
Copy/move dialog start location

### ISSUE THREAD

**Issue by cunninglemming** [SimpleMobileTools/Simple-Gallery#2187]
Right now when moving/copying files the dialog start location is set to the root of gallery. I think it would be more useful to start from the same location from which files were selected. This is actually already the case when choosing "Other Folder" option for directory tree navigation.

**Comment by tibbi** [comment]
well you see the main screen with folders, all of them are obviously shown there. I dont really want to change that.

**Comment by cunninglemming** [comment]
Ok I actually thought about situation when _Group direct subfolders_ option is enabled. Would it make more sense then?

**Comment by tibbi** [comment]
there are many improvements needed with grouping, will have to think it through.
