### ISSUE TITLE
Implement Easy Secure Photos (ESP)

### ISSUE THREAD

**Issue by gsitreble2019** [SimpleMobileTools/Simple-Gallery#2194]
You may know that a new paper: “Encrypted Cloud Photo Storage Using Google Photos“ is built using Simple Gallery: 

https://www.schneier.com/blog/archives/2021/07/storing-encrypted-photos-in-googles-cloud.html

https://www.cs.columbia.edu/~nieh/pubs/mobisys2021_esp.pdf

**Comment by tibbi** [comment]
the app has no internet access at all so it cannot handle anything cloud related
