### ISSUE TITLE
Fix handling of /Android/data folders on SDK 30

### ISSUE THREAD

**Issue by pankajtalaviya97** [SimpleMobileTools/Simple-Gallery#2196]
Not working copy, delete, move and other android 11 os version, so help for working in android 11.

**Comment by tibbi** [comment]
what app version are you using? Are you getting some error or what happens?

**Comment by pankajtalaviya97** [comment]
my mobile android version is 11 and not delete, rename and move file features not working

**Comment by tibbi** [comment]
does it happen to files on an SD card or internal storage?

**Comment by pankajtalaviya97** [comment]
internal storage file

**Comment by tibbi** [comment]
so every folder is broken? Or you are trying a special place like /Android/data?

**Comment by pankajtalaviya97** [comment]
no bro user can not move file in android data and then access or change, so how to get permission for edit and delete request for already placed location. so take write permission for any place of media

**Comment by tibbi** [comment]
right, that is a different issue then, improving it is on the roadmap. /Android/data folder handling changed with Android 11

**Comment by tibbi** [comment]
has been implemented already, will be added in the next app version
