### ISSUE TITLE
crash/freeze

### ISSUE THREAD

**Issue by filipe-maia** [SimpleMobileTools/Simple-Gallery#22]
Hi,

Don't know if this is an Open Camera problem or a Simple Gallery problem, but this doesn't happen with other gallery apps (I have tried with the default android gallery and QuickPic).

In the default photos save folder (internal_memory/DCIM/Camera) there are pictures taken with the Open Camera app and with the default android camera app.
Problem replication:
If I'm in the Open Camera app and press the button to go to the gallery to see what pictures were taken before, the phone will freeze and I have to take the battery out (the problem depends on what pictures are in the default photos save folder (internal_memory/DCIM/Camera) and depends on which picture is the first one, only some pictures will cause this problem to happen). The problem usually happens immediately, but in very rare cases it will take 1 second to happen or it will happen only the 2nd time.

If I try to open the problematic pictures without using Open Camera (i.e., using directly Simple Gallery or using a file manager to navigate to the picture and opening it with Simple Gallery), the problem won't occur.
I haven't tried another camera app.

I'm attaching one of the problematic pictures.
[picture.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/415579/picture.zip)

I'm using Android 5.0. Ask me for more details, I will try to help as I can.

**Comment by tibbi** [comment]
so if you are in the camera and click the last taken photo, from the available apps you choose Simple Gallery? Do I understand it right? If you choose another gallery, it wont freeze?

**Comment by filipe-maia** [comment]
Hi,
That is correct.
