### ISSUE TITLE
Please add Network Drive (NAS, SMB) support.

### ISSUE THREAD

**Issue by anthony75smith75** [SimpleMobileTools/Simple-Gallery#2204]
Please add Network Drive (NAS, SMB) support. This would allow us to use the easy features of Simple Gallery to access photos stored externally. We may wish to edit these external photos or to slim down large folders of similar photos using "Bottom Action" quick delete in full screen mode. For simplicity the external connection photos would best be displayed in a separate section of the gallery and not bundled with local device photos. 

Many open source file managers such as "Material Files," "FE File Explorer," and "CX File Explorer" support access to Network shared NAS storage but do not allow us to edit photos or to easily repetitive delete photos from full screen. Material Files allows Simple Gallery to be set as "the" image viewer but Simple Gallery does not work properly when the passed photos are from a network source.

**Comment by tibbi** [comment]
the app has no internet access so dont expect having something like that

**Comment by anthony75smith75** [comment]
Right. Well I wasn't expecting Dropbox or other cloud services just local Network drives. Local Network doesn't need internet but all good.

**Comment by arkar787** [comment]
The simple gallery is a too good product which tick mark all the requerment met except NAS, SMB which most people need today, Even I am ready to pay extra for this feature as an addon but sadly Simple Mobile Tools team is not wanted to add this option, many time send Email to Developers but receive only one reply that " we do not want to add Internet access in-app " but I failed to convince them that we do not need Internet access in-app, just want local Network access.
Now I am requesting to [WSTxda](https://forum.xda-developers.com/m/wstxda.9147586/) how moded QuickPic Gallery (https://forum.xda-developers.com/t/mod-app-gallery-quickpic-2022.3790425/) for just add SMB or NAS storage support in QuickPic whitch is already lack many of futures compare to the simple gallery but there is no any alternate option.
