### ISSUE TITLE
When using an RTL language, arrow is in wrong direction

### ISSUE THREAD

**Issue by mhmdanas** [SimpleMobileTools/Simple-Gallery#2206]
Just change to an RTL language (Arabic, Persian, etc.), then open any page other than the main page, such as settings, and look at the top right.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by mhmdanas** [comment]
Argh, I can't believe I forgot to post the app version (maybe add a template?). I'm using Simple Gallery 6.20.3 on Android 11.

**Comment by mhmdanas** [comment]
This issue is back now, probably due to https://github.com/SimpleMobileTools/Simple-Commons/commit/40cbf47ade94508a2595f23fe9ef4b378aeca322.
