### ISSUE TITLE
App crash after show information of certain images

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimpleMobileTools/Simple-Gallery#221]
Steps to reproduce:
1. Open this page: https://commons.m.wikimedia.org/wiki/File:%D0%9B%D0%B5%D1%9A%D0%B8%D0%BD_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D1%98.JPG
2. Click original file to download
3. Open with Simple Gallary
4. Open Information menu item

Then system show me a dialog that app is crash.

**Comment by tibbi** [comment]
I cannot seem to reproduce it with the original file "Лењин_Николај.JPG" (1536x2048). Can you reliably crash it always at that image? It might be some coincidence as I dont see any crashes related to it at the playstore dashboard (if you didnt get the app directly from playstore Ill never see it there)
