### ISSUE TITLE
Not working APNG Animated on 6.21.0.

### ISSUE THREAD

**Issue by Kafu-Yukimura** [SimpleMobileTools/Simple-Gallery#2212]
When I heard that APNG support was added, I immediately installed it and tested it.
However, the app still recognizes the APNG as a regular PNG and the animation doesn't work.
What settings do you need? Or is there a problem with the app?

**Comment by Kafu-Yukimura** [comment]
I found the cause. It was an extension problem.
When saving an APNG file, the PNG extension is used, but I confirmed that there is also an APNG extension when saving an APNG on the wiki site. After changing the extension to APNG, the result of checking in the app.
nice! It works very well. It seems that using the PNG extension ignores animation detection within the app, can I improve the APNG to work with the PNG extension as well?

**Comment by tibbi** [comment]
well if the file has ".png" extension, the app wont even try animating it. That looks good to me.
