### ISSUE TITLE
more flexible color editing in theme

### ISSUE THREAD

**Issue by OmlineEditor** [SimpleMobileTools/Simple-Gallery#2213]
few standard colors. I want to edit this value and manually enter the color. make more flexible and convenient color reactor.

![Screenshot_20210830-022847](https://user-images.githubusercontent.com/13348933/131392618-770b914b-66df-41a6-bac2-a34c89aea7ac.jpg)

**Comment by tibbi** [comment]
Some colors cannot be changed dynamically, so some preset themes had to be created. Once it is possible to change them, we will adjust it.

**Comment by OmlineEditor** [comment]
> Some colors cannot be changed dynamically, so some preset themes had to be created. Once it is possible to change them, we will adjust it.

then open the tick. why did you close it?

**Comment by tibbi** [comment]
well, because it is not possible to do now. And anyway it affects all apps, not just Simple Gallery.
