### ISSUE TITLE
Wishlist: extra filter media options

### ISSUE THREAD

**Issue by Virgus** [SimpleMobileTools/Simple-Gallery#2216]
Hello, this Gallery apk seems to be the best one available !
I'm using it more and more since I discovered it.

I'd really love to see an option to filter internal/sd content directly from the filter media options panel.

When I need to clean up the internal memory I have to go to the filter media panel to select videos or pictures and then to "Settings"/"Visibility"/"Manage excluded folders" and add the SD card temporarily, so to be able to see only internal videos and pictures.

After deletion/copy/move to external SD card of the files i have to go back to the settings and remove the exclusions, and then to adjust the filters back to normal.

It would be much easier to toggle between internal/external/both storages in the filter media panel which is so easy to access.

Last but not least it would be really helpful to have a set of configurable paths in the "Other folder" panel which is accessible when moving or copying files. A drop down list or an extra button with preferred destination paths, anything which might shorten the burden of searching the destination archive path for every single file. I'm using a 256GB micro SD card and the archive folders are hundreds, so it would be much easier to have a few "categorized" ones accessible from a panel or a list.

Thanks and have a nice day,
V.

**Comment by tibbi** [comment]
I dont plan adding such filter, just use sorting by path or something
