### ISSUE TITLE
Can't make as default image viewer on Android 11

### ISSUE THREAD

**Issue by wpisarski** [SimpleMobileTools/Simple-Gallery#2218]
My phone came back from repair reset and updated to Android 11, after reinstalling everything i can't set Simple Gallery Pro as default image viewer. Phone is Nokia 5.3. App works fine when opening directly, files and multimedia permissions are granted.

There's no explicit setting like ones for default browser or messaging app. There was no popup for choosing an app when opening image for the first time. I've tried clearing default opening settings for Google's stock photo app and it didn't help. After disabling stock app in the apps settings page there's just a popup stating that there's no app for opening this kind of files.

It works fine on my old phone (Nokia 6.1) and worked well before on current phone while it had Android 10.

**Comment by tibbi** [comment]
Where are you opening the gallery from, some camera app? Some apps have hardcoded default galleries in them, there sadly just isnt anything we can do about it. It is the case with some preinstalled camera apps too.

**Comment by wpisarski** [comment]
I've tried opening an image downloaded in Firefox and directly from Simple File Manager. Both give me only a brief error message when stock app is disabled and only Simple Gallery installed.

**Comment by tibbi** [comment]
Do other galleries work? Try downloading something else.
