### ISSUE TITLE
in the editing mode, rotate the image by an arbitrary angle

### ISSUE THREAD

**Issue by OmlineEditor** [SimpleMobileTools/Simple-Gallery#2222]
now you can rotate the image only by 90, 180 and 270 degrees. other values are missing.
I ask you to make it possible to rotate the image at an arbitrary angle with an accuracy of 1 degree in the editing mode.

**Comment by tibbi** [comment]
you can rotate to any degree, but make sure you use the Pro version from Google Play or Github

**Comment by OmlineEditor** [comment]
> you can rotate to any degree, but make sure you use the Pro version from Google Play or Github

my version from github. but I can only rotate by an arbitrary angle in view mode, and I can't rotate by an arbitrary angle in edit mode.

please open a ticket

**Comment by tibbi** [comment]
what view or edit mode? You might be using some other apps editor, not ours.

**Comment by OmlineEditor** [comment]
> hat view or edit mode? You might be using some other apps editor, not ours.

I'm using your app in edit mode.
you need to add the ability to change not only by 90 degrees but also by an arbitrary angle.
please open a ticket

![edit](https://user-images.githubusercontent.com/13348933/133941387-74602a6f-72fd-4c3a-97ec-21230d30069a.jpg)

**Comment by tibbi** [comment]
that is the old basic photo editor. As written previously, the version on Google Play and Github have the better one.

**Comment by tibbi** [comment]
You mean that you downloaded the latest version from Github Releases section, or you built the app yourself from the source?

![Screenshot_20210920-220010](https://user-images.githubusercontent.com/528931/134067218-882e4d7b-cdd4-4e76-b9bf-9a0b6ea4af44.jpg)

**Comment by OmlineEditor** [comment]
> You mean that you downloaded the latest version from Github Releases section, or you built the app yourself from the source?


I have the latest version with f-droid, it is taken from the sources from github

**Comment by tibbi** [comment]
as written previously, you have to have the version from Google Play or Github. The advanced editor is not open source, thus cannot be added to f-droid.

**Comment by OmlineEditor** [comment]
I realized, very much, that part of the code is not open source
