### ISSUE TITLE
After editing the video - sound is shattered

### ISSUE THREAD

**Issue by qwertiger** [SimpleMobileTools/Simple-Gallery#2223]
After editing the video in app v. 6.21.2 (I tried also different versions and I have the same problem) the sound is shattered:
Here is the original video:

https://user-images.githubusercontent.com/54217779/133214805-4024b024-acd4-4364-9ab3-06fc07855d41.mp4

And here is the "cropped" video after export from gallery:

https://user-images.githubusercontent.com/54217779/133216554-9062db48-1fbc-49a6-a424-cb2c9a96644a.mp4

I also noticed that framerate is somehow "reduced" after export.

Is there some setting which can fix this - or is it due to some "codec"?
Here is my settings export:

[gallery-settings.txt](https://github.com/SimpleMobileTools/Simple-Gallery/files/7159724/gallery-settings.txt)

**Comment by tibbi** [comment]
can you try with https://play.google.com/store/apps/details?id=com.photoeditorsdk.android.app please?

**Comment by qwertiger** [comment]
Hmm interesting, here it's not a problem after I export the video:

https://user-images.githubusercontent.com/54217779/133247622-f0e2170c-a84b-415b-a563-2fefc1fa2d50.mp4

But there is also the same problem while video is being played within the edit mode:

![Screenshot_20210914-131201](https://user-images.githubusercontent.com/54217779/133247552-e692b5ef-3231-45f6-a50d-cdf81db2c8b2.jpg)

the same occurs also within the Gallery app - but in gallery app also after export.

**Comment by qwertiger** [comment]
Hello again.
Update:
After editing and saving some more videos, I found out, that the export is also shattered using the img.ly editor too. Not sure, why for the first time it wasn't happening, strange.. So I guess it's kind of "library" bug which your gallery app is using

**Comment by tibbi** [comment]
retry with 6.21.3 that just started rolling out, reopen if it is still broken

**Comment by qwertiger** [comment]
Hello @tibbi 
Unfortunately, the problem is still present, also in the updated version.
And I think I don't have access to reopen the issue again.

**Comment by qwertiger** [comment]
Hello @tibbi 
Everything works perfectly with the latest version (6.22.0)
I think this bug can be closed
