### ISSUE TITLE
Gallery slider

### ISSUE THREAD

**Issue by Valdnet** [SimpleMobileTools/Simple-Gallery#2225]
Steps:

1. Select image.
2. Select "Copy to" from the menu.
3. Scroll the gallery, e.g. to the last one.
4. Click on the "eye" icon.

The gallery slide slider remains in place. It does not disappear (does not change its position) as with normal swiping of the finger.

![obraz](https://user-images.githubusercontent.com/47037905/133424429-888c7814-edd8-49b3-ac13-dbf83d4372f5.png)

**Comment by tibbi** [comment]
slider can sometimes be glitchy, but it is a more generic issue affecting other apps too. So Ill close this one.
