### ISSUE TITLE
overwrite action deleting existing file and not writing new file

### ISSUE THREAD

**Issue by sidmint** [SimpleMobileTools/Simple-Gallery#2226]
steps to reproduce:
1. create file say p1 in two folders say f1 and f2.
2. create file p2 in f1.
3. delete file p1 from f1 and rename p2 as p1 in f1.
4. copy p1 from f1 to f2 and select 'overwrite' option.

result: in f2, there's no p1, neither new nor old.

expected: f2 should have new p1 copied from f1.

v6.21.0 from Fdroid

**Comment by tibbi** [comment]
is any of those folders on an SD card? Recheck with 6.21.2 once it becomes available there, something related has just changed.

**Comment by sidmint** [comment]
> is any of those folders on an SD card?

no.

**Comment by sidmint** [comment]
thank you for the app, it's very useful.

> Recheck with 6.21.2

fixed,
