### ISSUE TITLE
Cannot browse through images in full screen mode

### ISSUE THREAD

**Issue by kinclma1** [SimpleMobileTools/Simple-Gallery#224]
When I display an image in full screen, swiping doesn't work. It just turns off the full screen mode just as if I just tapped the screen.

**Comment by tibbi** [comment]
this one is sadly related to Android 4.x, when the app is in fullscreen mode and you touch it I dont receive any events that I could react on, it just turns off fullscreen mode. I dont think it works in any gallery app.

**Comment by kinclma1** [comment]
It works fine in QuickPic, but who knows how they did it.

**Comment by NatusChaos** [comment]
Full-screen visualization and swipe to see the other photos must be default way of the app when we touch a photo, without these overlays and empty borders, thanks for the app, in no time this is gonna be the best gallery.

**Comment by tibbi** [comment]
ye there is a fullscreen mode that can be easily enabled with a click, things just work differently on android 4 and Im not sure how to do it there.
