### ISSUE TITLE
Trouble Moving Files With Invalid Characters In Filenames

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-Gallery#2246]
It seems the app has trouble moving files with characters such as emojis in the filename. 
It gives some Java nullpoint error, then just moves all the other files, and leavs the few behind. This is really annoying to go in and manually fix every filename if it's something that was downloaded.

**Comment by tibbi** [comment]
I dont think you are supposed to have emojis in a file name
