### ISSUE TITLE
[Feature] Easily switch all folders view and folder view

### ISSUE THREAD

**Issue by dmint789** [SimpleMobileTools/Simple-Gallery#2247]
I think it would be very convenient if there were two tabs with buttons at the bottom, where one takes you to the all folders view and the other takes you to the individual folder (album) view, like in other gallery apps. Right now it's not the most convenient, because you have to tap the three dots and then select the desired view from the (fairly big) dropdown.

**Comment by soredake** [comment]
How it's done in another gallery app
![Screenshot_20211227-212403_Gallery_Go.png](https://user-images.githubusercontent.com/5204968/147501322-b94f4046-4ace-4637-abbd-0883201078ef.png)

**Comment by clodi95** [comment]
Please add this!

Or at least add an extra album in "Folder View" that quickly shows all pictures.
