### ISSUE TITLE
Sorting by Date taken actually sorts by Last modified

### ISSUE THREAD

**Issue by TwisX** [SimpleMobileTools/Simple-Gallery#2260]
When sorting by Date taken, everything is actually sorted by Last modified. For example, photos that Simple Gallery knows were taken in 2012 are placed next to photos that were taken in 2018. This can also be confirmed by sorting by Last modified and observing that everything is sorted the same as if Date taken was selected.

App version: 6.22.0 Pro

**Comment by tibbi** [comment]
Hello, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.
