### ISSUE TITLE
Android version 11 copy,rename,move and delete not working (target SDK 30)

### ISSUE THREAD

**Issue by Ankitinnovatree** [SimpleMobileTools/Simple-Gallery#2261]
my project target SDK is 30 (Android version 11). and perform copy,rename,move and delete operation to not perform and show the message (please give permission) and i normally add permission external_storage_read and write.

without use of MANAGE_EXTERNAL_STORAGE permission how can i do this copy,move,rename and delete in Android version 11?

**Comment by tibbi** [comment]
we do not have SDK 30 yet

**Comment by BraINstinct0** [comment]
Discussed in #2196 , seems like work is underway in #2073
