### ISSUE TITLE
"java.util.NoSuchElementException" error

### ISSUE THREAD

**Issue by Flam3z** [SimpleMobileTools/Simple-Gallery#2269]
This error occurs when I try to delete an album that contains 100+ photos, is the app able to handle that much at once?

**Comment by tibbi** [comment]
sure, that isnt much. What app and OS version are you using? Is that folder on an SD acrd or internal storage?

**Comment by Flam3z** [comment]
App version 6.22.0
Android 11
The folder is on an SD card

**Comment by tibbi** [comment]
file operations have been rewritten heavily for Android 11+, it should be fixed in the next app version
