### ISSUE TITLE
saving photos after editing

### ISSUE THREAD

**Issue by hussamjan** [SimpleMobileTools/Simple-Gallery#227]
when i edit a photo (crop, rotate, etc), and click the check mark, it asks for a new name and have to change the name otherwise it will say already exists. 

isn't it more convenient to skip this message and save the changes directly?

**Comment by tibbi** [comment]
ye its broken only if the image is on an sd card. It should allow overwriting the existing image like at saving to internal storage. Editing from fullscreen mode should also allow overwriting existing files, like reported at #182

**Comment by azat11** [comment]
Also can't save image after editing if changing file name, popup tells that there's no available space.

**Comment by tibbi** [comment]
umm, no available space, or Out of memory? thats two different things.

**Comment by azat11** [comment]
Yes, out of memory. Sorry, got lost in translation there for a bit. Using the russian version.

**Comment by tibbi** [comment]
overwriting the existing file will be allowed in the next version. Out of memory is a different issue, Ill take a look at it too if I can improve it.
