### ISSUE TITLE
Toggle visibility icon is misleading

### ISSUE THREAD

**Issue by tswistak** [SimpleMobileTools/Simple-Gallery#2280]
Hi,

I think that toggle visibility icon is very misleading. Instead of showing current file state, it shows what will happen after tapping it. On contrary, toggle favorite and change orientation buttons are showing the current state.

In my opinion, if the file is not hidden, the icon should be a normal eye. Crossed eye should be shown when file is hidden. If it will be too misleading for current users to change it, maybe it would be worth to add other tooltips? Instead of "toggle visibility" tooltip, you could set two separate: "hide file", "show file" (and then similarly to favorite and orientation button).

**Comment by tibbi** [comment]
nevermind I reverted it, it was just fine previously
