### ISSUE TITLE
Count files in headers

### ISSUE THREAD

**Issue by AlbatorV** [SimpleMobileTools/Simple-Gallery#2281]
Hi
When you group files in folder, can you add files counter in parenthesis for each group headers

e.g. If group by month…

Fevrier 2021 (14)
Janvier 2021 (24)
Décembre 2020 (6)

Regards

**Comment by Aga-C** [comment]
@tibbi What about adding this as an optional checkbox in the Group By dialog box?

![image](https://user-images.githubusercontent.com/85929121/144856632-bc80b473-9569-4d27-803a-669e1775044f.png)

**Comment by AlbatorV** [comment]
+1
Yes, It's the good place for this option

**Comment by tibbi** [comment]
ye, you can add it there as "Show file count at section headers"
