### ISSUE TITLE
App Crashes after new update :bug:

### ISSUE THREAD

**Issue by ynsnf** [SimpleMobileTools/Simple-Gallery#2294]
The app hangs after I clear the recyle bin and the files don't seem to be deleted until i reopen the app. This has happened many times since the last update. Anyways, Thank you for all the hardwork! :+1: 

I am using Redmi Note 8 v6.22.1

**Comment by tibbi** [comment]
what OS version is that?

**Comment by ynsnf** [comment]
That's the App Version. OS Version is Android 11

**Comment by tibbi** [comment]
try reinstalling the app, if it will still happen

**Comment by tibbi** [comment]
so does it still happen or not anymore? Try with 6.22.2

**Comment by ynsnf** [comment]
It's not crashing now, Thanks!
