### ISSUE TITLE
Question: how does simple gallery hide pictures?

### ISSUE THREAD

**Issue by Pauler221** [SimpleMobileTools/Simple-Gallery#2298]
Does anyone know how "simple gallery" hides pictures or folders when pressing on "hide"? 

Other Gallery apps can't view pictures that have been hidden by simple gallery. I thought it just puts a "." (dot) in front of the folders or pictures but it doesn't. Also hidden pictures are still accessible with a file manager but not other gallery apps.

So how is this working?

**Comment by Aga-C** [comment]
It's described when you're hiding a folder for the first time:

> This function hides the folder by adding a '.nomedia' file into it, it will hide all subfolders too. You can see them by toggling the 'Show hidden items' option in Settings. Continue?

`.nomedia` is a standard way of hiding folders for all galleries in Android, that's why you can't see it.

**Comment by tibbi** [comment]
files are hidden by prepending filename with a dot, folders by adding an empty ".nomedia" file in them
