### ISSUE TITLE
Add favorites items to export file

### ISSUE THREAD

**Issue by AlbatorV** [SimpleMobileTools/Simple-Gallery#2308]
Can you add favorites items in export file like pinned folders.

**Comment by codethief** [comment]
By "export file" you are referring to the exported settings? I don't think that would make much sense, given that settings persist over a long time but photos might get moved off the phone and/or deleted all the time. So I'd rather vote for a separate export functionality for favorites.

**Comment by AlbatorV** [comment]
I agree, export favorites in separate file.
