### ISSUE TITLE
App completely breaks and also repeatedly corrupts phone SD card when trying to sync Nextcloud folder

### ISSUE THREAD

**Issue by Tanman897** [SimpleMobileTools/Simple-Gallery#2313]
I am using the free pro version of this app from F-Droid. So I have setup the app to include the Nextcloud content folder on my phone. I setup Nextcloud to backup and migrate mew photos on my phone to that folder. It used to work flawlessly to show any new and already present photos contained within my Nextcloud folder on my phone. Within the last few weeks or so, I have noticed that the app now shows any new photos as blank grey squares with their titles only. Also, the app is glitching and showing two, three, four, or more folders with the same name when, in reality, only one folder exists with that name on my phone. It will randomly assign glitched blank photos to these glitched folders. For example, the app will show four "camera" folders with randomly distributed blank unreadable photos on each but my Nextcloud folder on my phone clearly only has one "camera" folder and all of the contents are completely readable and as designed. When I open the app, some sort of message quickly appears and the disappears in like 1/20 of a second so I have no idea what it says. It will glitch like that over and over again in random intervals whenever I go to the home screen. 

The problem does not stop here. The app also appears to be repeatedly corrupting my SD card. When I have the app installed and I insert my newly-reformatted SD card, the card quickly becomes corrupted as indicated by my phone. The card stays just fine if I upload and download stuff to it on my pc. This is a newer SD card which I have even long-reformatted to scan for broken partitions to make sure it is not the card. The common denominator seems to be the app. At this point the app is completely broken and unusable in this state and a danger to my phone's hardware. I have no idea how an app could be THIS bad. 

I have tried uninstalling the app and then reinstalling and it has done nothing to solve the issue. I am running an Android Galaxy S10 Lite with the latest updates installed for both the phone and the app.

**Comment by tibbi** [comment]
do other recently updated galleries work well? What app and OS version are you using?

**Comment by Tanman897** [comment]
@tibbi yes, the default Samsung gallery app works just fine.

The app version for Gallery Pro is 6.22.2. The OS version of my Android is 11, One UI version 3.1, Kernel version 4.14.190-22585437.

**Comment by tibbi** [comment]
try some downloaded gallery, not a preinstalled one. Those work differently. Is your device rooted?

**Comment by Tanman897** [comment]
@tibbi, I just downloaded F-Stop. It detected my Nextcloud photo folder by default without touching any settings. It also immediately detected and properly shows new photos in that folder and immediately deletes them when I delete them in my Nextcloud (and thus off of my phone too). F-Stop does not show all the mysterious blank photos or duplicate folders that this app is showing.

My Android is not rooted.

**Comment by kojid0** [comment]
Don't know if this is the same bug but when I sync a photo folder in the nextcloud app, the images (which are in this folder) are not visible in simple-gallery app. They are shown as gray/blank files. They are clickable and their details can be shown.
The file size of a photo is "0 B". 
Storage says "/storage/emulated/0/(invalid)/storage/emulated/0/nextcloud/username/FolderWithFile)".

I think the problem is with "invalid". Can you replicate this issue when having the above setting @tibbi ?

**Comment by Tanman897** [comment]
@kojid0, yes, mine is the same exact circumstances. I tried your solution but the glitch still persists. I think that perhaps it is because I have Nextcloud set to save backed up files to my SD card and not my internal storage so including an internal storage folder would not fix this. I tried also including the same folder path for my sd card and it also did not fix anything. I also checked and saw that I have no excluded folders listed. My SD card is encrypted so maybe that is where the issue lies; Idk, I am not an app developer and just guessing here.

I will say that this glitch has made this app completely unusable for me. I have had to switch to another third-party gallery app which does not have this problem. Hopefully they fix this soon.

**Comment by tibbi** [comment]
retry with 6.23.0 once it gets, whole file fetching will change on Android 11+

**Comment by tibbi** [comment]
6.23.0 isnt even released yet, how could you check it..

**Comment by Tanman897** [comment]
@tibbi Okay but, wouldn't the correct course of action to be to wait for it to be released, then check if this fixes things on the user's side? It seems out of order to close the issue simply because it is theoretically fixed on your side but I haven't even had a chance to check yet.

**Comment by tibbi** [comment]
the whole way of fetching data on Android 11+ will be changed drastically and we wont be able to solve it if something doesnt work there anymore
