### ISSUE TITLE
Only 2 buttons are displayed in portrait mode

### ISSUE THREAD

**Issue by Pushkin31** [SimpleMobileTools/Simple-Gallery#2315]
In portrait mode (with and without selection), only 2 buttons are displayed, in the folder, when in landscape mode - much more.
Tell me - how could I increase the number of displayed buttons on the panel?
P.s: I'm just doing some modifications for myself - I put the buttons on the panel, but this restriction prevents me..

<details>
<summary>Without selection</summary>

![2](https://user-images.githubusercontent.com/35974828/147371414-e7e14e0a-cd78-450f-801a-f0d1bcee86a4.jpg)
![2-2](https://user-images.githubusercontent.com/35974828/147371417-f1b748d5-3ad5-49a4-851a-ce80200ebfb1.jpg)

</details>

<details>
<summary>In selection mode</summary>

![1](https://user-images.githubusercontent.com/35974828/147371382-e161368a-218b-4c2c-b2d4-fbe820e3ab47.jpg)
![1-1](https://user-images.githubusercontent.com/35974828/147371383-4dcd8310-3e56-48ff-88c5-411105465dfa.jpg)

</details>

**Comment by tibbi** [comment]
that is handled by the system, I dont want to force adding too many buttons
