### ISSUE TITLE
show_all is not a clear opposite if folder_view

### ISSUE THREAD

**Issue by Meteor0id** [SimpleMobileTools/Simple-Gallery#2318]
The menu options of simple gallery are a bit chaotic. You would expect settings about 'view' to all be part of the 'view' menu options, but some options are in the hamburger menu instead. One of those is "view all" which sounds like "unhide all folders" but actually means "overview without folders" and is the opposite if another hamburger menu option called "folder view".

It would be helpful to rename "view all" and move it to the "view" menu where you would expect to find this choice.

More columns and less columns would also make sense as options in the view menu.

**Comment by tibbi** [comment]
6.26.0 will have menu icons for those, should be clearer
