### ISSUE TITLE
Option to add stamps containing date, day and/or time

### ISSUE THREAD

**Issue by vatonbero** [SimpleMobileTools/Simple-Gallery#2320]
Hi there,

Option to add stamps containing dates, day and/or time would help us if we need to edit picture and put a quick timestamps visible on the image.

Right now you can type that data using existing options in program however quickly adding stamps would speed up the process greatly.

**Comment by tibbi** [comment]
that isnt really on the roadmap, dont expect having it. The advanced editor is developed by a third party group of developers too, not us. So just add the dates as text.
