### ISSUE TITLE
Add option to keep zoom level and viewport location when changing media

### ISSUE THREAD

**Issue by mnsc** [SimpleMobileTools/Simple-Gallery#2323]
I have a habit of taking multiple pictures with the approximate same composition with different settings, (shutter/iso/hdr) and I would like to have an option to quickly zoom to 100% then move the viewport to the part of the image I want to inspect and then easily switch to the photo before/after, comparing them while keeping the zoom level and viewport location. 

I'm thinking that I want to double tap to zoom in, then move the viewport with two fingers and keep the single finger swipe to change photo like when not zoomed in. But I'm open to alternatives?

Fixing this issue will mean I'm gonna donate a beer! 😅 (I'm gonna donate a coffee right away because I'm already blown away by the quality of the app!)

**Comment by tibbi** [comment]
It isnt really on the roadmap, dont expect having it. Thanks though

**Comment by mnsc** [comment]
Do you have any guidelines for contribution or should I just fork and fix this for myself?

**Comment by tibbi** [comment]
I dont plan accepting such feature, so you should just fork it.
