### ISSUE TITLE
Java.lang.nullpointer error when renaming an image.

### ISSUE THREAD

**Issue by Flam3z** [SimpleMobileTools/Simple-Gallery#2326]
When renaming an image the error "java.lang.nullpointerexception" appears then another toast saying "an error has occure". I tried to rename on multiple photos but I am unable to.

**Comment by tibbi** [comment]
What app and OS version are you using? Is the file on an SD card or internal storage?

**Comment by Flam3z** [comment]
Android 11, 6.22.3 and also the same issue occurs when editing an image as well

**Comment by KryptKode** [comment]
@Flam3z  What steps did you take so I can try to reproduce? Could you make a video?

**Comment by Aga-C** [comment]
@KryptKode I can reproduce this issue on emulator on SD card. Just try renaming photo in the photo grid, or in the photo view.
