### ISSUE TITLE
Automatically delete items from recycle bin

### ISSUE THREAD

**Issue by janilowski** [SimpleMobileTools/Simple-Gallery#2329]
Add the option to automatically remove items from the recycle bin if they've been laying there for more than 30 days.

[Feature request]

**Comment by Aga-C** [comment]
It currently works like this, it's described in the FAQ in About section of the app.

**Comment by licaon-kter** [comment]
Can you reopen this?

On my devices (AOSP11 and Calyx 11) F-Droid 6.25.5 does not seem to delete files, as I still have files that were deleted long ago.
