### ISSUE TITLE
Performance regression when opening from external file manager

### ISSUE THREAD

**Issue by tp0** [SimpleMobileTools/Simple-Gallery#2332]
When opening an image from a file manager app ("open with" way), it takes about 2 seconds before the image is actually visible. Simple Gallery opens instantly but for those nearly 2 deconds displays the empty background. ([Screenshot](https://i.imgur.com/PLUIxRc.png))

* File is stored on internal storage. File size makes no difference, happens with very small files too.

* Issue occurs in 6.22.3 and 6.22.2, but not in 6.22.1 or 6.22.0.

* File managers tested: Simple File Manager Pro (6.11.3), Material Files

Device: Motorola G8 Power
Android: 11

**Comment by tibbi** [comment]
the gallery fetches all files in the given folder to make it swipable, not just the given 1 image. I guess if you use Simple File Manager you can swipe to other images too, but with Material files you cannot, right? Or how does it work, is it slow in both cases?
