### ISSUE TITLE
Add marker-styled drawing option

### ISSUE THREAD

**Issue by Animyos** [SimpleMobileTools/Simple-Gallery#2334]
Hey there,
one thing that I'm missing in the Simple Gallery app are half transparent, marker-like drawing options, so you could mark things like text easily.

Could you add this? Because it would make a lot of things easier (and I see the Apple users doing this all the time... 🙃)

Kind regards
AnimyosFox

**Comment by tibbi** [comment]
you can already do that in the Pro app versions editor

**Comment by Animyos** [comment]
Ok. I didn't know this. Sorry for the inconvenience.

**Comment by Animyos** [comment]
I installed the pro version from F-Droid (and according to the website the pro version in the Play Store only has an additional movie editor, but I can't find tge ootion there.

**Comment by tibbi** [comment]
it has an advanced photo editor and a new video editor

**Comment by Aga-C** [comment]
This is only in Pro version from Google Play or GitHub.
