### ISSUE TITLE
Storage Access Framework permissions needed to save edited images to SD card

### ISSUE THREAD

**Issue by EmberHeartshine** [SimpleMobileTools/Simple-Gallery#2338]
App version: 6.22.3 (F-Droid)
OS: Samsung One UI 3.1 (Android 11)
Platform: Samsung Galaxy S20 5G (arm64-v8a)

**Steps to reproduce:**
1. Open app
2. View an image
3. Edit the image
4. Try to save the image onto your SD card

**Expected behavior:**
The image saves.

**Actual behavior:**
![Screenshot_20220120-082043_Gallery](https://user-images.githubusercontent.com/50666308/150346811-c2ff5c28-f252-446b-80c7-a57e2be46fdb.jpg)

**More info:**
Related to #806 but *not* a feature request. As of Android 11, all apps must now request access to the file system in order to save files. Hilariously, permission is *not* needed to delete or move existing files, so file movement operations work just fine. It's *just* the editor that needs these permissions.

I often wonder if Google even understands why people choose Android over iOS.

**Comment by BedHedd** [comment]
I'm getting the same bug
![Screenshot_20220130-013641_1](https://user-images.githubusercontent.com/27317528/151691320-ebfa1d39-ff0e-4ee2-a80a-6c7185456c7e.png)

It occurs when I edit from the gallery. If I open the image with simple gallery from my file explorer, I'm able to saveedits.

App version: 6.22.3 (F-Droid)
OS: Sony (Android 11)
Platform: Sony Xperia V ii (Model: XQ-AS62)
