### ISSUE TITLE
Images disappear after edit

### ISSUE THREAD

**Issue by azat11** [SimpleMobileTools/Simple-Gallery#234]
After rotating an image taken from the back camera and saving it "out of memory" popup appears. After trying saving the image again "unknown error" popup appears, and when moving back out of the image it simply disappears as if I just deleted it.
This doesn't happen for images taken from the frontal camera, possibly the size of an image is an issue. 5mp at the front and 13mp at the back. OnePlus One device.

**Comment by tibbi** [comment]
I couldnt make it more optimized now, so Ive just added an extra thing to avoid deleting the original file if the saving fails for some reason.

**Comment by tibbi** [comment]
Starting with the next version Ill be modifying the exif metadata at rotating, so it cannot get out of memory anymore.
