### ISSUE TITLE
#feature request : make a option by which it can delete its cache everytime i exit the app

### ISSUE THREAD

**Issue by suraj3486** [SimpleMobileTools/Simple-Gallery#2340]
Please include this feature in app it will keep app storage usage to minimal.
Sometimes it gets heavy due to cache it make aroung 250mb...
I think giving an option to delete cache at every time u exit app automatically will be really a good feature.

**Comment by tibbi** [comment]
that isnt on the roadmap, it will be solved with some other cache limitations
