### ISSUE TITLE
[Feature Request] Full Screen 

### ISSUE THREAD

**Issue by basings** [SimpleMobileTools/Simple-Gallery#2341]
What about a full screen Option?

The upper bar (menu) could be hidden unless it is triggered by a swipe downwards (hidden when swiping upwards) for a better UI

**Comment by tibbi** [comment]
you can already toggle fullscreen mode by clicking on the image

**Comment by basings** [comment]
@tibbi yes, but that's not what I meant. I mean full screen mode when scrolling through the image database

**Comment by tibbi** [comment]
it isnt on the roadmap for the thumbnails view

**Comment by Aga-C** [comment]
Here is a similar issue: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2231.
