### ISSUE TITLE
the image does not scale (spontaneous bug)

### ISSUE THREAD

**Issue by OmlineEditor** [SimpleMobileTools/Simple-Gallery#2345]
- I'm running the program
- opening the image
- I'm trying to use two fingers to change the scale of the image
- it doesn't work, I just move my fingers, but nothing happens

then I remove my fingers and put them on again and try to change the scale, sometimes it starts to work sometimes you need to remove your fingers a third time and put them on again to change the scale, this happens spontaneously and not always.

Simple Gallery Pro 6.22.3 (358) f-droid
Redmi Note 7 (Androin 9)

**Comment by tibbi** [comment]
try just waiting a bit longer before zooming in, it should work

**Comment by OmlineEditor** [comment]
it's weird, why wait if the image has already opened? other apps never required waiting. Look at the code, maybe there is a small error there.

**Comment by tibbi** [comment]
Loading in the deep zoomable image can take some time. Improving it is on the roadmap, but it isnt that easy. Anyway, it is already reported somewhere and I'm fully aware of it so Ill close this one.

**Comment by OmlineEditor** [comment]
do you recognize this as a bug or not? will you fix the problem?

**Comment by tibbi** [comment]
sure, Im aware of it and want to fix it, but it is difficult
