### ISSUE TITLE
Edit option in video isn't working in Andriod 12 

### ISSUE THREAD

**Issue by dtbj** [SimpleMobileTools/Simple-Gallery#2350]
I am using fdroid latest version the edit icon shows no valid app found
![image](https://user-images.githubusercontent.com/87176273/153414381-5424ec0a-8c81-4da2-a2e3-3a5facef331c.png)

**Comment by dtbj** [comment]
Update: LOL Play Store version is 6.22.0 while fdroid version is 6.22.3 so it's probably bug in the latest version. I hope you will fix it soon I really need your video editor I use it a lot.

**Comment by Aga-C** [comment]
F-Droid version doesn't contain video editor and extended photo editor, because they have proprietary license. Version from GitHub releases has it.

**Comment by dtbj** [comment]
@Aga-C Can you explain once more I am unable to get your point.

**Comment by tibbi** [comment]
the advanced photo/video editor used in the Google Play version is not open source, thus cannot be added to f-droid

**Comment by dtbj** [comment]
Oh ok then so is there any risk in that proprietary photo editor? I mean like app don't have access to internet so any type of tracking or anything can't be done right?

**Comment by tibbi** [comment]
no, there is no risk. The app still has no internet access, so the library cannot do anything online whatsoever either.
