### ISSUE TITLE
using PVS studio to detect errors?

### ISSUE THREAD

**Issue by OmlineEditor** [SimpleMobileTools/Simple-Gallery#2356]
do you have a large and complex project, do you use the PVS studio program to analyze errors and problems?
this program will be free for you because it is free for open source projects.
https://pvs-studio.com/en/pvs-studio/

**Comment by tibbi** [comment]
thanks, but no

**Comment by OmlineEditor** [comment]
why? this will make it easier to find errors and the program is free

**Comment by tibbi** [comment]
I dont see the benefit of such programs in our case

**Comment by OmlineEditor** [comment]
you have a lot of programs and probably have bugs. the program will help you find them. well, if abc has something else, then that's good. a person can make mistakes and needs something that will help him find these mistakes. thank you for answering the question
