### ISSUE TITLE
Images not shown after they are moved to another folder

### ISSUE THREAD

**Issue by khartahk** [SimpleMobileTools/Simple-Gallery#2360]
Android 11
One Plus Nord2
NOT rooted
Simple Gallery PRO version 6.22.3

I'm using nextcloud to upload images after I take them with the Camera app. After they are uploaded nextcloud app moves them to it's folder. I have that folder set up as the one to watch in simple gallery pro. All the images that are currently in that folder appear in the gallery as expected but new ones added after the fact do not show up. If I re-add the same folder as being watched they are then shown.

Expected behaviour:
- take a photo
- nextcloud uploads and moves the photo
- photo is visible in the simple gallery pro app

What happens:
- take a photo
- nextcloud uploads and moves the photo
- photo is not visible in the simple gallery pro app 

Work arround:
- after the photo is uploaded and moved go in to settings
- manage included folders
- click on +
- click ok
- the photos are now vissible

Similar issue: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2311#issuecomment-1030664092

**Comment by tibbi** [comment]
many things changed with 6.23.x, should be fixed already
