### ISSUE TITLE
Wrong image if opened from file manager

### ISSUE THREAD

**Issue by Nemris** [SimpleMobileTools/Simple-Gallery#2365]
Simple Gallery appears to display the wrong picture if the picture is "opened" from a file manager and there are multiple images in a directory.

The image displayed doesn't seem to follow a pattern, and the bug isn't specific to this app version. This bug doesn't appear using e.g. QuickPic.

## To reproduce
1. Using a file manager, open an image from a directory which houses multiple images.
2. Observe that the image displayed isn't the one selected, _most of the time_.

## Device info
OS: Samsung One UI 3.1 (Android 11)
Device: Samsung Galaxy A40 (SM-A405FN)
App version: 6.22.3

**Comment by Nemris** [comment]
Might have to do with #559.

**Comment by tibbi** [comment]
it should be fixed in 6.23.0 that will be released soon, reopen if not
