### ISSUE TITLE
Deleting images from the single-image viewer doesn't immediately update the multi-image gallery

### ISSUE THREAD

**Issue by Twinov** [SimpleMobileTools/Simple-Gallery#2368]
Phone: Google Pixel 6 Pro
OS: Android 12 (rooted with Magisk if that matters)
Version: 6.22.3 Pro from FDroid

When looking at a folder from the multi-image gallery (sorry if I got the terminology wrong, the normal folder gallery view), if you delete an image, a toast comes up with "Deleting # images", and then the thumbnail is removed from the gallery view, which is what I would expect.  

However, if you instead click on the image to view it in full screen and then delete it and press back to go to the gallery view, you'll still see the thumbnail there for several seconds until the app refreshes. Tapping the phantom thumbnail during this period does nothing.  
Additionally, if you instead click delete in the single-image view and wait, for me the app goes to a black screen with information about the deleted image still displayed, or in some cases proceeds to the next non-deleted image, but then after a second or two returns to displaying the previously deleted image. Clicking the properties button shows a screen like so (this is the case where I got a black screen): 
![image](https://user-images.githubusercontent.com/23278147/155421847-947bb325-d17d-4e44-acb4-9f284ab3a28e.png)
The expected functionality would be that when deleting an image, the next non-deleted image is displayed, and when pressing the back button, the gallery view doesn't have it anymore, as is already the case when you delete an image from that view instead. 
Hope this is a good description!

**Comment by tibbi** [comment]
many file operation related improvements will be added in 6.23.0 released soon, especially related to Android 11+. Create a new issue if it will still misbehave somehow, Ill close this till then.
