### ISSUE TITLE
F-droid version misnamed? Seems to be basic version and not the pro.

### ISSUE THREAD

**Issue by tuxayo** [SimpleMobileTools/Simple-Gallery#2374]
No issues with the pro version being sold. It's about the F-Droid having it named "Simple Gallery Pro" while not having the text editor and it's UI is simpler than the 3rd screenshot [1] so this seems to show that it's the basic version. Is that correct or is the F-Droid and hybrid an has some features of the pro?

[1] https://f-droid.org/fr/packages/com.simplemobiletools.gallery.pro/

**Comment by tibbi** [comment]
Hi, the advanced editor is available in the Google Play variant only, as it is no open source and cannot be added to f-droid.

**Comment by tuxayo** [comment]
So this confirm the F-Droid version shouldn't be named "Simple Gallery Pro" ?

**Comment by tibbi** [comment]
it should

**Comment by tuxayo** [comment]
it should be named "Simple Gallery Pro" even if it lacks the advanced editor?

**Comment by tibbi** [comment]
yes, because the Pro version has tons of other improvements, it isnt just about the editor at all

**Comment by tuxayo** [comment]
So the F-Droid version is like an hybrid version that has everything the Pro version has except the advanced editor?

**Comment by tibbi** [comment]
well ye, something like that
