### ISSUE TITLE
Theme Bug

### ISSUE THREAD

**Issue by GithubContributor832** [SimpleMobileTools/Simple-Gallery#2377]
I recently noticed on your apps that the theme change requires a restart for full effect like with the white theme. The three vertical dots for options are white after change instead of black. I have to restart to get change into full effect on white theme. Thus is a problem on many apps that I use from you including the Thank You which keeps setting button hidden on white theme even after a restart. Also if I change the theme then hit recent apps the app closes. Running 6.22.3. 

Steps to reproduce:

1. Change theme in settings hit back button couple times and no shut down of app sometimes but requires restart for white theme to take effect without working on some apps like Thank You.
2. Change theme and hit recent apps to change app and it shuts down.

**Comment by tibbi** [comment]
3 dots are difficult to customize, the rest needs an app restart for technical reasons. Some icon related improvements for white theme will be added in the next app version. But it affects all apps so Ill close this one here.
