### ISSUE TITLE
Still gradient banding in latest release.

### ISSUE THREAD

**Issue by wyatt8740** [SimpleMobileTools/Simple-Gallery#238]
See #202 : "Gradient Banding (wrong pixel format/bit depth for surface?)"
The build in that issue fixed the banding, but the most recent release still displays the banding problem.

**Comment by tibbi** [comment]
ye I had to switch back jpgs to use rgb_565, as people were getting out of memory. Only pngs will be argb_8888, thats the best solution I could do for now, it should be good enough for very most people.

**Comment by wyatt8740** [comment]
Wouldn't a configuration option be possible? ACV is a comic viewer for android that offers a "low memory mode" option.

BTW this is the only thing that drives me up-the-wall crazy in an otherwise great viewer.

**Comment by tibbi** [comment]
Ill check how can I optimize it in the future.

**Comment by tibbi** [comment]
should be better in the next release 2.14.0

**Comment by wyatt8740** [comment]
Thanks for the notification; I'll check it out soon.

**Comment by wyatt8740** [comment]
@tibbi I'm still experiencing the RGB_565 decoding method being used on my pixel 2 with the latest release on f-droid (4.4.0.) Any idea why?

**Comment by tibbi** [comment]
@wyatt8740 try toggling "Replace deep zoomable images with better quality ones" in the app fullscreen settings, that will cause a different library to be used.
