### ISSUE TITLE
"Overwrite" option when moving file doesn't overwrite it.

### ISSUE THREAD

**Issue by cordelia04m** [SimpleMobileTools/Simple-Gallery#2382]
Android 10

Huawei Y6P

App version 6.22.3 from F-droid

Problem: When I move or copy files to another folder, files whose names are the same names as some files in the destination folder will show the options of what to do; skip, overwrite, or keep both. 

What happened: I chose Overwrite, and the files move to the other directory successfully. But the files with duplicated name get the "(1)" append to their name. 

What I expected: the files should be overwrite, not adding "(1)" to the files with the same name.

**Comment by tibbi** [comment]
it happens only to SD card folders, right?

**Comment by cordelia04m** [comment]
@tibbi yes, it happened when moving files to SD card.

**Comment by tibbi** [comment]
just for info, same happens on Android 11+ if you just change a letters case, like "one.jpg" to "One.jpg"
