### ISSUE TITLE
Remove Animations in Image Viewer or in general as an option?

### ISSUE THREAD

**Issue by firefoxlover** [SimpleMobileTools/Simple-Gallery#2385]
### Problem
You make double photos because you want to have a perfect one. When there are multiple ones and there is only one spot, where one is better than another, its really helpful to compare the photos by switching back-forth-back-forth.

The slide-animation distroys that, you cant compare them anymore (this flipping technique was actually used to discover new planets in the past, as some small details blink into your eyes)

### Solution
Just an option to disable the swipe animation would solve it.

In the old Samsung Gallery there was a small bar showing a camera roll / horizontal photos before and after the current one. But this is actually too much, not needed for that purpose and destroying the minimalist interface a bit.

Thank you for this awesome gallery!

**Comment by tibbi** [comment]
you can already enable instant photo switching by clicking on screen sides in the app settings

**Comment by firefoxlover** [comment]
> you can already enable instant photo switching by clicking on screen sides in the app settings

Boy your apps are too good! Okay then Its solved!
