### ISSUE TITLE
Rotating and saving as same name creates renamed image regardless

### ISSUE THREAD

**Issue by uli-on** [SimpleMobileTools/Simple-Gallery#2389]
After rotating an image I can't save it under the same name. I'm asked whether I'm aware that this image already exists and if I want to overwrite it. I tap OK and a new image with a new numbered suffix is created. If I tap Cancel nothing happens, so the two buttons aren't exchanged but  the OK button doesn't behave as announced.

Simple Gallery v6.22.3 from F-Droid

**Comment by tibbi** [comment]
retry with 6.23.0 please

**Comment by uli-on** [comment]
Will report back. TIA!

**Comment by uli-on** [comment]
Is fixed in fact. Thanks, Tibbi!

**Comment by tibbi** [comment]
alright, thanks
