### ISSUE TITLE
choosing the editing method

### ISSUE THREAD

**Issue by OmlineEditor** [SimpleMobileTools/Simple-Gallery#2390]
I ask you to add an option with a long hold to open the selection menu than edit. if you select once by default, then this choice cannot be changed. I want to change the editing program with a long hold on the button.

![1](https://user-images.githubusercontent.com/13348933/160478666-56e0522f-e6d4-415e-b475-5baccb5da0fd.jpg)

**Comment by tibbi** [comment]
thats not how Android works, you can reset the device editor in your device settings
