### ISSUE TITLE
Please add category to manifest to allow launcher sorting

### ISSUE THREAD

**Issue by Quackdoc** [SimpleMobileTools/Simple-Gallery#2394]
currently simple-gallery is one of the better galleries for android TV, however the lack of categorization makes most launchers shove it into the "apps" section. it would be nice to add `android:appCategory="image"` to the manifest 

see https://developer.android.com/reference/android/R.attr.html#appCategory for explanation

**Comment by tibbi** [comment]
it has been added in 6.23.0
