### ISSUE TITLE
Hidden images unfavouriting themselves. 

### ISSUE THREAD

**Issue by shengud1** [SimpleMobileTools/Simple-Gallery#2395]
Sometimes all of the hidden images I have favourited just unfavourite themselves. I don't know why it's doing this.

**Comment by tibbi** [comment]
what app version are you using?

**Comment by shengud1** [comment]
I've got the latest version available in F-Droid, 6.22.3.

**Comment by tibbi** [comment]
right, Ill close this though as starting with next version 6.23.0 apps like this wont be able to show hidden items anymore on Android 11+
