### ISSUE TITLE
121212 and/or 181818 as primary colors

### ISSUE THREAD

**Issue by 06041989** [SimpleMobileTools/Simple-Gallery#2398]
Currently there aren't any muted colors to chose from in the gallery. Adding 121212 can give users the option to have dark mode without using full black witch strains the eyes (at least for me). 
I got 121212 from here: https://material.io/design/color/dark-theme.html#properties
181818 is also good. I think both are better than 424242 or 616161 which are too bright in my opinion.

**Comment by tibbi** [comment]
we use material colors, adding custom ones isnt on the roadmap

**Comment by 06041989** [comment]
Could #212121 be used? It is meterial grey 900 in meterial grey.

https://mui.com/customization/color/
https://v1.mui.com/style/color/

**Comment by tibbi** [comment]
its not, we are using material colors

**Comment by 06041989** [comment]
From https://mui.com/customization/color/ 
> Hue & Shade: A single color within the palette is made up of a hue such as "red", and shade, such as "500". "red 50" is the lightest shade of red (pink!), while "red 900" is the darkest. In addition, most hues come with "accent" shades, prefixed with an A.

Grey 900 is #212121 and is part of the offical material color pallete as seen bellow from thier website
![grey](https://user-images.githubusercontent.com/93400100/161783272-fcf56c4d-acbb-40f6-b890-a8e37a84c89d.png)

**Comment by 06041989** [comment]
Just to add a bit to what I mean, looking at https://github.com/SimpleMobileTools/Simple-Commons/blob/beb62cf4b9c3f88c139b9578e997eeb0a4ae83cc/commons/src/main/res/values/colors.xml

```
   <color name="md_grey_white">#FFFFFF</color>
    <color name="md_grey_200">#EEEEEE</color>
    <color name="md_grey_300">#E0E0E0</color>
    <color name="md_grey_400">#BDBDBD</color>
    <color name="md_grey_500">#9E9E9E</color>
    <color name="md_grey_600">#757575</color>
    <color name="md_grey_700">#616161</color>
    <color name="md_grey_800">#424242</color>
    <color name="md_grey_black">#000000</color>
```
All these colors match with the material color pallete except 212121 has been replaced with 000000. In my opinion 212121 is the most inportant one after 000000, if not the most important, because it allows for a dark primary color, which none of the dozens of colors allow for. Thats why I think adding 212121 is a good idea. As for making space for it in the menu, maybe removing a color would work, or some other method.

**Comment by tibbi** [comment]
thats not material colors, just some miui ones

**Comment by 06041989** [comment]
Its the same in material ui
https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=212121&secondary.color=424242
