### ISSUE TITLE
Obtain Pro version on ungoogled phone?

### ISSUE THREAD

**Issue by IngwiePhoenix** [SimpleMobileTools/Simple-Gallery#2400]
Hello!

I am using microG and Aurora Store to get the basic needs for most android apps sorted. However, this also means that I do not have the Google Play Store installed.

How can I upgrade to the pro version in this situation? I really want to use a few of the pro-features such as sub-folders or folder locking to hide some sensible images from peeking friends and family.

Thank you and kind regards,
Ingwie

**Comment by tibbi** [comment]
Hi, the apps are available on F-droid too, for example the gallery is at https://f-droid.org/packages/com.simplemobiletools.gallery.pro . Just change the URL to get to other apps. All apps are the same as on F-droid, just Simple Gallery Pro has a more advanced photo/video editor on Google Play. Then you can optionally send some donation at https://www.simplemobiletools.com/donate

**Comment by IngwiePhoenix** [comment]
Ah, so I must use the Google Play Store version to unlock all the pro features? Well I wanted to avoid having to use the official Play Store on my phone but I guess that can't be helped. Or can I also unlock Pro by sending a donation instead?

**Comment by tibbi** [comment]
you can get the full Pro one from Github at https://github.com/SimpleMobileTools/Simple-Gallery/releases too, but that wont be autoupdating
