### ISSUE TITLE
Since Exoplayer. Pause-Play is Not Smooth Anymore.

### ISSUE THREAD

**Issue by UMBRAGITHUB** [SimpleMobileTools/Simple-Gallery#2409]
Since v4.3.2
Video pause and play is incorrect.

I'm in v4.3.1 anyway and won't update because of that.

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by inson1** [comment]
@tibbi Maybe its time to close this issue? He doesnt responds, nobody gave him like, we dont know versions etc. And or me its smooth.
