### ISSUE TITLE
Compiling signature error

### ISSUE THREAD

**Issue by Pushkin31** [SimpleMobileTools/Simple-Gallery#2416]
Hello. I am modifying the application for myself and ran into the problem of a signature error even without making changes to apk (specially tried for the test). When I try to sign the application, I get the following error:
`I: Подпись...
I: Sign File (V1 + V2): /storage/emulated/0/Apktool_M/gallery-359-foss-release_src/gallery-359-foss-release_src.apk
W: Signature (V1 + V2) failed! 
W: Malformed APK: not a ZIP archive
W: com.b.a.a.a(ApkSigner.java:202)
W: com.b.a.a.a(ApkSigner.java:178)
W: ru.maximoff.apktool.c.bf.a(SignUtil.java:223)
W: ru.maximoff.apktool.c.be.a(SignTask.java:44)
W: ru.maximoff.apktool.c.a.a(AbstractTask.java:71)
W: ru.maximoff.apktool.c.a.doInBackground(Unknown Source:2)
W: android.os.AsyncTask$3.call(AsyncTask.java:394)
W: java.util.concurrent.FutureTask.run(FutureTask.java:266)
W: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W: java.lang.Thread.run(Thread.java:920)
W: ZIP End of Central Directory record not found
W: com.b.a.a.b.a(ApkUtils.java:48)
W: com.b.a.a.a(ApkSigner.java:200)
W: com.b.a.a.a(ApkSigner.java:178)
W: ru.maximoff.apktool.c.bf.a(SignUtil.java:223)
W: ru.maximoff.apktool.c.be.a(SignTask.java:44)
W: ru.maximoff.apktool.c.a.a(AbstractTask.java:71)
W: ru.maximoff.apktool.c.a.doInBackground(Unknown Source:2)
W: android.os.AsyncTask$3.call(AsyncTask.java:394)
W: java.util.concurrent.FutureTask.run(FutureTask.java:266)
W: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W: java.lang.Thread.run(Thread.java:920)
I: Времени затрачено: 00:00:00.111`

I tried to sign with different methods, but the result is the same (Tell me how to sign now, because there were no problems before.

**Comment by tibbi** [comment]
I dont know, but I dont support fake app versions
