### ISSUE TITLE
Add back previous all-files permission for github-foss / f-droid flavors

### ISSUE THREAD

**Issue by statesecret** [SimpleMobileTools/Simple-Gallery#2417]
@tibbi please add back previous all-files permission for github-foss / f-droid flavors, and thus bringing back hidden files function, separating it from github-proprietary / playstore flavors.

**Comment by tibbi** [comment]
I dont want to maintain multiple app versions that are so different

**Comment by nbmrjuhneibkr** [comment]
Maybe you don't want to maintain two versions, but this permission change now also leads to the loss of user data, which is totally unacceptable: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2321
It needs to be fixed, one way or another.

**Comment by Plut0nio** [comment]
> I dont want to maintain multiple app versions that are so different

Surely using compiler directives and new build variants would make this much easier, no? I really hope the ability to hide files and folders and then view them gets re-added back into the non-Google Play versions someday. It was extremely useful to me and quite possibly the biggest reason why I chose this over other gallery apps.

**Comment by nbmrjuhneibkr** [comment]
This issue has been fixed in FOSS v6.23.6 (365).
It affected FOSS versions 6.23.0-6.23.5 (359-364).
