### ISSUE TITLE
Hidden files and ACTION_OPEN_DOCUMENT_TREE.

### ISSUE THREAD

**Issue by RuRo** [SimpleMobileTools/Simple-Gallery#2418]
Hi, you have removed the ability to see hidden files in a recent update. You claim, that this is due to restrictions in the Android 11+ update. I'm am not an Android expert, so forgive me if my understanding is wrong, but couldn't you implement the old "Included Folders" mechanism using [`ACTION_OPEN_DOCUMENT_TREE`](https://developer.android.com/training/data-storage/shared/documents-files#grant-access-directory) together with [`FLAG_GRANT_PERSISTABLE_URI_PERMISSION` and `FLAG_GRANT_PREFIX_URI_PERMISSION`](https://developer.android.com/reference/android/content/Intent#FLAG_GRANT_PERSISTABLE_URI_PERMISSION).

Sorry, if this is a stupid question, I just have trouble believing that the latest update completely kills the possibility for apps to access arbitrary files. Wouldn't this completely destroy File Managers, Terminal Emulators, Anti-viruses and a lot of other apps?

**Comment by tibbi** [comment]
some apps are eligible for accessing all files as previously, but gallery apps have only restricted access to media files and so we have to use the mediastore

**Comment by RuRo** [comment]
If you mean [this notice](https://developer.android.com/training/data-storage/manage-all-files#all-files-access-google-play), then it lists "Document management apps" as eligible, which I would argue this application is.

Also, you didn't answer the first part of the question. `ACTION_OPEN_DOCUMENT_TREE` that I've mentioned is part of the as "Storage Access Framework" API which is allowed even for "regular" apps, AFAIK.

**Comment by tibbi** [comment]
no, this is not a document management app, we manage media only. SAF framework is ridiculously slow and problematic, especially on Android 11+
