### ISSUE TITLE
Can't access hidden folders after the update

### ISSUE THREAD

**Issue by johndoe432** [SimpleMobileTools/Simple-Gallery#2419]
Hi! Noticed that after the latest updates I can no longer see my hidden folders. Can I access them anyhow? Had some stuff in them that I don't want to lose

**Comment by tibbi** [comment]
Hi, apps like this can no longer show hidden files on Android 11+. It is a Google Play limitation, not something we chose to do ourselves. You can try unhiding them with some file manager or the old free gallery app version.

**Comment by DragoonAethis** [comment]
@tibbi Please pin this issue so that anyone looking for the missing feature will not create even more issues about this :D

**Comment by jeanor72** [comment]
see also this other issue:
https://github.com/SimpleMobileTools/Simple-Gallery/issues/2420
it seems the only way is to downgrade to 6.21.2.
