### ISSUE TITLE
"Temporarily show hidden" option ?

### ISSUE THREAD

**Issue by repsorp** [SimpleMobileTools/Simple-Gallery#2420]
This option available in 6.21.2 works fine even with Android 11 or 12...
Why was it removed from 6.21.3?

**Comment by rolo-r** [comment]
Looks like they got rid of the ability to hide folders altogether with this latest update. This is in the changelog for 6.23.0:

> Changed some file operations to comply with the latest Google permissions policy, apps like this can no longer show hidden items on Android 11+

**Comment by Carpe-Diem-Postero** [comment]
The change was done to comply with some google policy crap, the app can be in the play store.

I had to downgrade to 6.21.3 to recover that function, and set f-droid to ignore any future updates.

F-droid version should DEFINITIVELY keep that feature. Google is cutting our software fredom enough already.

**Comment by jeanor72** [comment]
I agree with carpe-diem-postero: this is my most important function and i cannot live without it. i had to downgrade to 6.21.2 (i cannot find any 6.21.3 and i suppose it was a typo) and i will stuck to it.
