### ISSUE TITLE
Group direct sub folders 

### ISSUE THREAD

**Issue by Tommyclues** [SimpleMobileTools/Simple-Gallery#2421]
When group direct is enabled and I try to move sub folders to any position it completely jumps every folder into a random mess making everything frustrating because it can not stay in place and be properly organized.

Another bug when group direct is enabled is if the user enters a sub folder and rotates their device it would kick the user back to the main folders.

Last bug I found with group direct sub folder is if you enter a sub folder while your screen is half way down (up or down depending on scenario) the screen while continue to stay in the same position instead of starting you at the top of you enter a sub folders. 
**Note:** this bug is only noticable if the main folders and sub folders pages are both scrollable.

The sub folders and main folders seem to act the exact same instead of independent and causing these bugs. That's my guess though

**Comment by tibbi** [comment]
please report them one by one, many subfolder grouping issues have already been reported
