### ISSUE TITLE
Samba Support

### ISSUE THREAD

**Issue by fsoullier** [SimpleMobileTools/Simple-Gallery#2422]
It would ne nice to be able to access photos stored onlineespecially stored on  Samba/CIFS shares.

**Comment by tibbi** [comment]
our apps have no internet access, so dont expect having any local networks either

**Comment by OkyDooky** [comment]
@fsoullier I wonder if you might be able to use something like Amaze file browser to connect to a remote folder and then see it in the Gallery app? Not sure if those folders can be accessible by other apps, but there might be some way to set that up. You could try posing that question to the anons on the Worksafe Requests board of 4chan (https://boards.4channel.org/wsr/).
I may do so for myself, but if you get to it first, reply to me here.
