### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lipici** [SimpleMobileTools/Simple-Gallery#2424]
When you delete a photo from internal memory or memory card with recycle bin activated or deactivated the application is asking to acces memory card.

App version 6.23.1 and android 11 non rooted

**Comment by tibbi** [comment]
can you send a screenshot of the dialog that is shown?

**Comment by lipici** [comment]
![Screenshot_20220421-105830](https://user-images.githubusercontent.com/46893370/164407888-19acf064-6c80-44ae-aa15-f8ba2a9eab87.png)
![Screenshot_20220421-105819](https://user-images.githubusercontent.com/46893370/164407893-3c216ddb-d77f-49c3-8c4e-ce299c9b3980.png)
![Screenshot_20220421-105800](https://user-images.githubusercontent.com/46893370/164407896-65082a29-9bd1-4959-98a7-45e787c658e4.png)
![Screenshot_20220421-105752](https://user-images.githubusercontent.com/46893370/164407899-64e6b2d5-dbfd-491f-a4d0-99d8376ca95d.png)

**Comment by lipici** [comment]
It didnt asked from begining of update, after 1-2 days. I deleted pictures and was ok and now i get this window.

**Comment by tibbi** [comment]
that is not an SD card dialog, but the new write permissions dialog that the system requires. Just do what is written there, it works as expected.

**Comment by lipici** [comment]
For permision it ask you at begining when you open gallery for the first time and i already accepted so if never asked me until now why it ask now ?
What changed ?

**Comment by tibbi** [comment]
the apps target SDK changed, it brought many file operation related changes
