### ISSUE TITLE
Inconsistent font size in settings

### ISSUE THREAD

**Issue by GOGOsu** [SimpleMobileTools/Simple-Gallery#2425]
In settings, the font size in each option is inconsistent.

Android 11 (MIUI 13) on Xiaomi Pad 5 Pro.

![Screenshot_2022-04-22-19-47-11-441_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/31916454/164710046-b4ef068c-f181-46a0-a9a5-99225c774436.jpg)

**Comment by tibbi** [comment]
what app version is that?

**Comment by GOGOsu** [comment]
I tested it on both v6.23.1 and v6.22.3 (both downloaded from release tab, proprietary-release.apk), both looks same.
