### ISSUE TITLE
Cannot delete images

### ISSUE THREAD

**Issue by Crankle437** [SimpleMobileTools/Simple-Gallery#2428]
Hi,

since the new updates I can no longer delete images in the latest version (6.23.1 (360), Android 11, Xiaomi). When I try to delete the image I get the message "Confirm external storage access" than I click on "Use this folder". There I get the system message (error) "System service for selecting files and folders is unavailable."

The old version 6.21.2 (348) is working well.

**Comment by tibbi** [comment]
that is a system issue, guess you disabled some system services. Guess you have a rooted device, or modified in a similar way

**Comment by licaon-kter** [comment]
I also see `system_service_disabled` but I'd like to report to the ROM builder which app they missed, or Intent or Activity or whatever, as there are 5 places here: https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/kotlin/com/simplemobiletools/commons/extensions/Activity.kt 

Which one is used say for File deletion on Android 11?

**Comment by tibbi** [comment]
it will likely be Intent.ACTION_OPEN_DOCUMENT_TREE, but ROMs should usually handle Intent.ACTION_CREATE_DOCUMENT too. Those things will sadly be needed once apps start updating target SDK to 31.

**Comment by tibbi** [comment]
I mean target SDK 30, there havent really been any major file operation changes in 31

**Comment by licaon-kter** [comment]
Does this log help in any way? https://gist.github.com/licaon-kter/bd4a1403cabaa16c3854387fa786d507

It's at the moment I press "Use this folder" in the Gallery popup dialogue.

**Comment by tibbi** [comment]
we dont need help there, it is the system that has to support it. Nothing wrong on our side.

**Comment by licaon-kter** [comment]
Yup, `com.android.documentsui` was uninstalled for current user via adb. Restoring that fixed it.

**Comment by sedrubal** [comment]
For others with the same problem: AFAIK, in my case it was `com.google.android.documentsui`. `pm install-existing <package id>` reinstalls it. I had to restart my phone afterwards.
