### ISSUE TITLE
Edit (crop or scale down) + save produces a file of same size

### ISSUE THREAD

**Issue by vmicho** [SimpleMobileTools/Simple-Gallery#2433]
My version: Simple gallery pro 6.23.1, from fdroid, on android 11

Edit (crop and/or scale down) to modify a bit the picture from camera and/or to save size before sharing : after saving the file with the original name (overwrite) the resulting file has the same size as the original, while it should be much less.
E.g.: take foto (2 MB), edit with Simple gallery, crop or resize to about 1/2 of original res, save with the original name (i.e. delete the automatic '_1' suffix). The new file has the same size (2MB). Doing the same but saving as new picture (i.e. originalpic_1.jpg) reduces the size to e.g. 300 KB.
This did not happen in the previous version.
As a workaround I save now as new picture and use that one for further purposes.

**Comment by J4CKED** [comment]
Strange, but in my case this bug does not occur. 
v6.23.1 and A12.

**Comment by vmicho** [comment]
Retest:
I downgraded to 6.21.1 -> the bug is not there :D
Then upgraded to 6.23.0, new permissions asked+granted -> and the bug is here again
Then to 6.23.1 -> bug still there

Wanted to test on my 2nd phone (android 10) but the highest version available there is 6.21.2, no bug.

**Comment by vmicho** [comment]
![image](https://user-images.githubusercontent.com/66125746/165621999-79e277a7-e0f0-41f9-854d-b1ff1e2c6ea2.png)
So I checked the file: 3 files: 1 original (no suffixes), one scaled and saved as seprate file IMG_20220427_215417_1.jpg, one scaled to the same res and saved to itself (overwrite) IMG_20220427_215417-scaledOverwrite.jpg.

Looking quickly inside, the badly saved (overwrite) file begins as the small file, and ends as the big file.
So for me it looks like the app only writes 228716 bytes at the beginning of the existing big file, without erasing it, i.e. wrong file mode when opening it?

**Comment by Arrappathor** [comment]
Can confirm for Moto G6+ Android 12/LineageOS 19.1

**Comment by Naveen3Singh** [comment]
@Arrappathor what app version are you using? 
Can you guys still reproduce this issue with recent versions like 6.26.0?

**Comment by Arrappathor** [comment]
Version 6.26.1 pro.
But the bug is gone since an Upgrade of Lineage 19 a while ago: i was asked by the app to grant a different form of file permissions - et voilà.
Thank you!

**Comment by Naveen3Singh** [comment]
Ah, I see it now. The bug can only be reproduced if the app doesn't have "File management" permission. Thx much!

**Comment by vmicho** [comment]
I did not observe it since few months after app update, so looks fixed (I did not do any update to OS since long time, so looks like the app fixed it)
