### ISSUE TITLE
Camera folders cannot be sorted by shooting time

### ISSUE THREAD

**Issue by hnzzmyr** [SimpleMobileTools/Simple-Gallery#2434]
The camera folder cannot be sorted by the time it was taken, even though I have selected it in the settings.  It is still sorted by modification time.  Very hopeful to be able to fix it, thank you.

**Comment by hnzzmyr** [comment]
Hello, the button to fix the date taken can make the date of the photo show the correct time, and the photos can also be sorted by the date of the photo in google photos. But the same photo in the simple gallery is still sorted by modification time even if sorting by shooting time is selected. I'm guessing the problem might be language related?

**Comment by tibbi** [comment]
what app and OS version are you using at all?

**Comment by paulle** [comment]
V 6.231 f-droid android11

Gesendet von ProtonMail mobile

-------- Original-Nachricht --------

**Comment by hnzzmyr** [comment]
The latest version 6.23.1 download from github, android 12L, pixel 4

**Comment by tibbi** [comment]
should be working in 6.23.5 already

**Comment by hnzzmyr** [comment]
It worked in 6.23.3, thanks😊
