### ISSUE TITLE
Since update / Android 12 Gallery needs permission for every single folder

### ISSUE THREAD

**Issue by firefoxlover** [SimpleMobileTools/Simple-Gallery#2437]
The solution probably is to just request the permission "read all files".

Atm I have to grant the gallery access over every viewed folder, when moving images.

In the past this wasnt the case, I could just give permission over SD-Card once and that was it.

VERSION
com.simplemobiletools.gallery.pro
6.23.1 FDroid

Android 12 (LineageOS 19.1 unofficial)

**Comment by tibbi** [comment]
nope, that is not the solution. Anyway, it should be improved in 6.23.2 released soon
