### ISSUE TITLE
Zoom in when drawing

### ISSUE THREAD

**Issue by yephny** [SimpleMobileTools/Simple-Gallery#2440]
It's difficult to draw when you're working with only a tiny segment of the image. It'd be much easier if you could zoom in.

v.6.23.1 F-Droid

**Comment by tibbi** [comment]
that editor wont be developed anymore, you have to use the Google Play version for the better one

**Comment by OkyDooky** [comment]
@yephny If you need to do more detailed operations (i.e. more than drawing a simple line or circle after several seconds of trial and error), then I recommend using Pocket Paint from F-Droid. It is fairly usable, now, and can work with layers and other tools. The two issues I have with it are 1) that you can't easily expand the canvas size or determine a specific size for a new file and 2) the current tool (brush, image import, shape, etc.) will perform an operation when switching to another tool.
Aside from those annoyances, it should take care of any of your image editing needs on mobile.
