### ISSUE TITLE
Dialog button colors should use 'Text color' instead of 'Primary color'

### ISSUE THREAD

**Issue by varaki** [SimpleMobileTools/Simple-Gallery#2447]
When setting a dark color theme, dialog buttons are almost unreadable, especially in bright sunlight.
Maybe a separate color config option for dialog buttons would be nice.
It's up to you whether you consider this as bug or feature request 😃

Thank you,

Some examples:

Color settings:
`text_color=-1
background_color=-16777216
primary_color_2=-12434878
accent_color=-689152
app_icon_color=-12232092`

![Screenshot_20220503-195110_crDroid Home](https://user-images.githubusercontent.com/23281360/166512168-566e5d4a-f956-4fa5-bece-dc400173b249.png)

Example dialog:
![Screenshot_20220503-195057_crDroid Home](https://user-images.githubusercontent.com/23281360/166512414-ea7fdfee-1b31-45ce-94c0-1b59a0d62ca7.png)

Setting the Primary color to the same as Text color:
![Screenshot_20220503-195134_crDroid Home](https://user-images.githubusercontent.com/23281360/166513241-be7761ed-7767-40d0-a04d-fcb031fdc026.png)

**Comment by tibbi** [comment]
nope, they should use the primary color. If you want to use B&W theme, that has special handling with accent color
