### ISSUE TITLE
Different icon colors

### ISSUE THREAD

**Issue by Pushkin31** [SimpleMobileTools/Simple-Gallery#2448]
If you change the system language (for example a russian in english) - the color of the icon changes (without changing the colors of the application).
<details>
<summary>screen</summary>

![1](https://user-images.githubusercontent.com/35974828/166578374-9492233a-a5ae-4278-ac57-ddf74ff352be.jpg)
![2](https://user-images.githubusercontent.com/35974828/166583708-9b992483-7fb7-4b7a-a1da-bb1b2c36fb75.jpg)

</details>
 
In russian in the information about the application, as well as in the window to select the editor application - the icon is yellow (although in the launcher in russian - orange)
<details>
<summary>screen</summary>

![3](https://user-images.githubusercontent.com/35974828/166583853-3ae2a600-ecf1-4960-813d-c7246c71541f.jpg)
![4](https://user-images.githubusercontent.com/35974828/166583890-b17365e1-d845-4546-9dd6-3c41b76285be.jpg)

</details>

I understand that for any locale there should be an orange icon...

**Comment by tibbi** [comment]
language doesnt affect the icon color. If it does, it is an issue of your launcher.
