### ISSUE TITLE
Can't delete any images 

### ISSUE THREAD

**Issue by WalterS** [SimpleMobileTools/Simple-Gallery#2459]
When trying to delete an image e.g. from the screenshot folder, Simple Gallery shows the delete message and stalls.
Force closing and restarting the app leads to an empty view as if Simple Gallery has lost all permissions.
Rebooting at least fixes the view.
This behaviour started with version 6.23.3

Samsung S20
Android 12
Simple Gallery 6.23.5 with media management enabled.

**Comment by seniorm0ment** [comment]
Encountering this as well. Moving files seems a bit buggy too.

**Comment by tibbi** [comment]
should be working with 6.23.6+

**Comment by Larx** [comment]
I have lots of problem with file management related stuff since the option "allow this app to manage media" has been introduced, and not only within Simple Gallery, but also in other apps (e.g. media storage provider ot the phone crashing all the time etc.). Is this related to this bug and has it also been fixed?

**Comment by tibbi** [comment]
havent you disabled some system services?

**Comment by Larx** [comment]
None that I know of. As soon as I enable the "manage media" switch, anything accessing the media storage (e.g. camera) starts misbehaving/crashing/etc. Might be a ROM issue, obviously, however Simple Gallery itself behaves like described in the first post.
If I leave the switch for manage media turned off, everything works (however the switch keeps popping up).

**Comment by tibbi** [comment]
well, if you have a custom ROM, that will be the issue

**Comment by seniorm0ment** [comment]
>I have lots of problem with file management related stuff since the option "allow this app to manage media" has been introduced

Same, no issues previously. Issues with gallery have only started for me since this has been implemented.

**Comment by Larx** [comment]
So, shouldn't this one be reopened? I would be surprised if it was a "custom ROM" issue....

**Comment by WalterS** [comment]
It is definitely not a custom ROM issue, I have an unaltered, non-rooted stock Samsung ROM.

**Comment by OzakIOne** [comment]
I have this issue for moving / cropping (into saving) photo and I do have a custom rom, is there anything I can do on my side to fix this ?
I didn't have this problem until recent version (I don't remember)

**Comment by tibbi** [comment]
doesnt have to be a custom ROM, it is enough if you disabled some system services, this one specifically needs com.android.documentsui

**Comment by OzakIOne** [comment]
`com.google.android.documentsui` was indeed disabled, everything working with it enabled

**Comment by Larx** [comment]
How does it get disabled? I have not disabled anything knowningly.

**Comment by OzakIOne** [comment]
> How does it get disabled? I have not disabled anything knowningly.

I have rooted my phone so I can disable app / services with various apps (in my case I use OandBackupX), if you aren't root, I have no idea

**Comment by Larx** [comment]
I have root, but I have not disabled any service. And another poster in this thread has the same problem with a stock ROM.

**Comment by WalterS** [comment]
Got the security update SMR-MAY-2022 for my S20 from Samsung and the problem hasn't occurred since then.

**Comment by Larx** [comment]
For me the recent update on FDrroid of Simple Gallery works.
