### ISSUE TITLE
FIX SELECTION ICON

### ISSUE THREAD

**Issue by 3BD-R** [SimpleMobileTools/Simple-Gallery#2462]
Selection icon looks like this when the view minimized 
![Screenshot_20220512_165334_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/33579200/168105002-55cba5a0-f097-48a0-b26b-876ce6ed89a4.jpg)

**Comment by tibbi** [comment]
that is not an issue

**Comment by andsofine** [comment]
why is it not?
