### ISSUE TITLE
Simple Gallery Pro playstore version not getting update

### ISSUE THREAD

**Issue by cyberboh** [SimpleMobileTools/Simple-Gallery#2465]
Hi, 
I have 2 device
1. Xiaomi Mi A1, running stock android one (android pie 9.0) already getting update 6.23.5
2. Poco X3 Pro, running custom roms android 12.1, but not getting an update, still old version 6.22.0

why this happen?

**Comment by tibbi** [comment]
6.23.x hasnt rolled out at 100% yet, we keep releasing new versions for fixes
