### ISSUE TITLE
Show media size when Deleting

### ISSUE THREAD

**Issue by subpub** [SimpleMobileTools/Simple-Gallery#2467]
Version 6.23.5 pro
when deleting it would be convenient if media size is displayed 

"Are you sure you want to move "video.mp4" (200MB) into the recycle bin?"

"Are you sure you want to move 3 items (500MB) into the recycle bin?"

"Are you sure you want to delete 13 items (7GB)?"

**Comment by tibbi** [comment]
it has been added already
