### ISSUE TITLE
Photo that edited can't be save

### ISSUE THREAD

**Issue by IM71** [SimpleMobileTools/Simple-Gallery#2468]
I use this app to edit photos (especially the text adding feature)
Since i switch to S22U,It can't no longer save the photo that being edited
I've already open all permissions and tried pressing "Use this folder" but it won't work
Are there any tips i should try? Or can you pls fix this problem?
THX

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by IM71** [comment]
> what app and OS version are you using?

App: Simple Gallery Pro (Latest)
OS: Stock OS -> One Ul 4.1

**Comment by tibbi** [comment]
I need the app version number from the bottom of the About section, there have been many versions released recently to just some users.

**Comment by IM71** [comment]
> I need the app version number from the bottom of the About section, there have been many versions released recently to just some users.

Version 6.23.6

**Comment by IM71** [comment]
> ok, what folder are you saving to? Is it on an SD card or internal storage?

Same folder.
Internal storage

**Comment by tibbi** [comment]
But it is a subfolder I suppose? Not directly on the internal storage. Does it not work in any folder whatsoever?

**Comment by IM71** [comment]
> But it is a subfolder I suppose? Not directly on the internal storage. Does it not work in any folder whatsoever?

Yes, it's a subfolder.
And yes,it can not work in any folder.
I tried to tap "use this folder" when the hint popup,then it'll shows that folder is unavailable.

**Comment by tibbi** [comment]
does deleting or copying into that folder work?

**Comment by IM71** [comment]
> does deleting or copying into that folder work?

Yes

**Comment by venun1810** [comment]
I have the same issue on MIUI Global 13.0.3, using 6.23.7 version of Gallery.

**Comment by Lexter224** [comment]
Same problem here on MIUI 12.5.8.0.

**Comment by tibbi** [comment]
does deleting in the given folder work? Retry with 6.24.0 once it becomes available

**Comment by IM71** [comment]
It's fixed.
THX!
