### ISSUE TITLE
Can't seem to edit videos via built-in video editor

### ISSUE THREAD

**Issue by nucspl** [SimpleMobileTools/Simple-Gallery#2472]
I know I was able to at some point, but now it's just showing this:
![Screenshot_20220519-145101_Gallery](https://user-images.githubusercontent.com/80261260/169323124-a4ad91dd-e36f-466d-bb44-47c94a618910.png)

**Comment by tibbi** [comment]
arent you using the foss app variant? That has no video editor

**Comment by nucspl** [comment]
I see, proprietary variant has it. You have my thanks.
