### ISSUE TITLE
material you issues

### ISSUE THREAD

**Issue by andsofine** [SimpleMobileTools/Simple-Gallery#2474]
1. material you chooses some strange poisonous color

another problem is that when I select the system theme I can't adjust the color of the bottom navigation bar
although this is not only with the system theme, the ability to choose a color for the bottom navigation bar also absent in auto light/dark mode.

2. (actually i don't want to customize its color i just want this line to be gone)

https://user-images.githubusercontent.com/99369164/169629775-f00cfcdf-3c8c-44a4-a328-4ab2bbfe0e3e.mp4

https://user-images.githubusercontent.com/99369164/169629776-4ffe9793-726e-4f25-8ea3-41a5b0abf15b.mp4

**Comment by tibbi** [comment]
report such generic issues at General-Discussion please. But explain them properly, do not just throw in some random videos.

**Comment by andsofine** [comment]
how else can i explain it
