### ISSUE TITLE
Suggestion for the screenshot editor

### ISSUE THREAD

**Issue by paradiseturtle** [SimpleMobileTools/Simple-Gallery#2478]
Hello, thanks for your work on the app i have been using simple gallery for years but the screenshot editor ui have been painful to use since forever to me

The most important thing is that it's missing a share button, that mean you have to edit it, save it somewhere, re open the gallery, find the picture, open it and share it, quite crazy! Secondly it's a bit painful to have to navigate all the menu just to crop and draw on it, it would be nice to have a lighter editor when simple gallery is called to edit a screenshot. 
But the share button is what it's really missing before all, i have suffered for years of that missing button

https://user-images.githubusercontent.com/105655912/169711225-642fef63-1026-4f45-ab32-9adc17a2ce1f.mp4

i used to have Markup screenshot editor app from Google, i really liked this one as it was quick, easy and with a share button next to save :

https://user-images.githubusercontent.com/105655912/169711208-0978b05e-b927-4c3d-a1ab-b26d106f04bc.mp4

thanks!

**Comment by tibbi** [comment]
that editor is developed by a third party group of developers, not us, so we cannot add it ourselves

**Comment by tibbi** [comment]
sure, we have it in our own one
