### ISSUE TITLE
Sort by name is not accurate with numerical filenames

### ISSUE THREAD

**Issue by forestlovewood** [SimpleMobileTools/Simple-Gallery#248]
There is an issue with the gallery that causes numerical filenames to be sorted as normal string filenames. I suggest that gallery could detect numeric filenames and sort them numerically instead.

Steps to reproduce:

- Create a folder with over ten images named 1, 2, 3 ... 9, 10, 11
- Observe the folder when sorted by name. Filenames can be seen jumping from 1 to 10 then 11 before continuing to 2, 3 and so on.

**Comment by tibbi** [comment]
should be working fine already
