### ISSUE TITLE
wrong file is being deleted / displayed when swiping in fullscreen

### ISSUE THREAD

**Issue by rohieb** [SimpleMobileTools/Simple-Gallery#2480]
I installed 6.23.7 from F-Droid yesterday, but I still have trouble with file deletion.
Steps to reproduce for me:

* take some pictures that you don't care about (optional, but recommended 😁)
* open Simple Gallery app
* go into folder
* open first picture in fullscreen
* swipe to the next picture
* press "delete button"
* confirmation dialog shows the file name from the previous file
* when I press "Yes" in the confirmation dialog, the view doesn't change, and when I go back to the folder view, the other image, which was not shown in fullscreen when I pressed "Delete", has vanished.

I noticed that when I press the "Info" button in fullscreen view, the image filename also doesn't change in this case. However it seems to work with some images… 🤔 I think I can only reproduce this when I open the first (most recent) image in the folder in fullscreen, otherwise it seems to be fine. Also if I swipe left from the most recent image more than once, and then to the right again, the filenames are all updated correctly.

**Comment by tibbi** [comment]
yeah, it has been fixed already, just needs an app update
