### ISSUE TITLE
Renaming is broken and deletes the filename when attempting to do so

### ISSUE THREAD

**Issue by nucspl** [SimpleMobileTools/Simple-Gallery#2481]
**App Version: 6.23.7, proprietary**
**Android 11**

### Steps to replicate
- `adb shell cmd role add-role-holder android.app.role.SYSTEM_GALLERY com.simplemobiletools.gallery.pro`
- Try renaming anything in Downloads, screenshots or anything outside that was moved into Downloads won't work.

The system prompt for editing files (Allow or Deny) in Downloads is skipped but it seems that the app doesn't know how to handle it.

### Here's what happens when attempting to rename anything in Downloads:
- "Error: java.util.NoSuchElementException"
- "Source file [file path] doesn't exist" aka file was renamed to "temp..."
![image](https://user-images.githubusercontent.com/80261260/169987951-fc782e2d-8af7-4e2a-9118-bc5f6b86cbee.png)

**Comment by nucspl** [comment]
- A11
- No
- GitHub, proprietary

**Comment by nucspl** [comment]
I found the culprit, revised the issue. I set the role to `android.app.role.SYSTEM_GALLERY` so I could delete files in my Downloads folder more conveniently as I would be prompted this system dialog for every file:

![prompt](https://user-images.githubusercontent.com/80261260/170143919-967319fe-7518-4182-90ad-f4d592d8789f.png)

Didn't think it would break renaming.

**Comment by KryptKode** [comment]
Hi @nucspl. 

1. Did you get any error when you ran 

`adb shell cmd role add-role-holder android.app.role.SYSTEM_GALLERY com.simplemobiletools.gallery.pro`? 

2. Can you post the output of what you got? 
3. Is your device rooted? 
4. Does the Simple Gallery app come pre-installed on your device?

**Comment by nucspl** [comment]
- None
- Used a rooted terminal to execute the command, same output when using adb shell on a computer ![Screenshot_20220525-111157_1](https://user-images.githubusercontent.com/80261260/170172172-3cd53a54-7416-49bf-ad01-c33fc3af59fe.png)
Confirmed by doing `dumpsys role`
![Screenshot_20220525-112219_1](https://user-images.githubusercontent.com/80261260/170173182-ed4214a4-476c-48f1-9516-1e4ca7193bda.png)
- Yes
- Yes but there's no difference regardless

**Comment by tibbi** [comment]
that will be some system issue caused by rooting and messing with the terminal, noone else reported anything like that

**Comment by varunpilankar** [comment]
So even if we move simple gallery pro as system app under /system/priv-app and use this command with root
`cmd role add-role-holder android.app.role.SYSTEM_GALLERY com.simplemobiletools.gallery.pro?`

It still cannot be a system default gallery? And to be used inside camera preview binding?

I'm on OnePlus 7 - Android 10 (rooted)
