### ISSUE TITLE
restore ability to see hidden folders/files

### ISSUE THREAD

**Issue by michaelschloe** [SimpleMobileTools/Simple-Gallery#2482]
In the latest update of the gallery app, I no longer have the option to view hidden folders/files (those whose names start with a dot, e.g. ".example"). This was a useful feature and I miss the option to display hidden folders.

For clarification, I am using android 12 on a Samsung S20 FE 5G and the installed app version is 6.23.7 Pro. I've installed the app from the Play store and from fdroid, neither source gives me the option to view hidden folders.

**Comment by tibbi** [comment]
you can see it at the F-droid version already, the foss variant
