### ISSUE TITLE
Theme properly not working with white primary color

### ISSUE THREAD

**Issue by AdityaMishra135** [SimpleMobileTools/Simple-Gallery#2485]
![Screenshot_20220526_161134](https://user-images.githubusercontent.com/94228705/170473565-9c88525a-26e5-4743-8b7e-b8685d429c8b.png)
![Screenshot_20220526_161016](https://user-images.githubusercontent.com/94228705/170473589-f11cd18f-7e09-4032-b42c-51d859a54871.png)
![Screenshot_20220526_160918](https://user-images.githubusercontent.com/94228705/170473594-24dab344-2ea7-4e06-9898-2cacc007c269.png)

**Comment by tibbi** [comment]
just use the specially handled White theme for that with some accent color.
