### ISSUE TITLE
"Show images in the highest possible quality" doesn't seem to handle big images very well

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#2487]
https://user-images.githubusercontent.com/29208110/170836791-da6c0c71-24f2-49a8-a401-a4018b135957.mp4

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by floppyD** [comment]
Android 10 - MIUI 12.0.4
Simple Gallery 6.23.8 Pro

**Comment by floppyD** [comment]
I updated to Android 11 - MIUI 13.0.1 and the issue was solved, so I guess it was Xiaomi's fault.
