### ISSUE TITLE
Previously hidden folders are still gone or broken.

### ISSUE THREAD

**Issue by EkriirkE** [SimpleMobileTools/Simple-Gallery#2489]
How can I get previously hidden folders to appear since that ability was "Removed"?
What is interesting is that if I move files to an "Other folder" that was previsouly-hidden, the folder now appears but only shows the new moved content, not the rest of the hidden content.  However if I go to the location in other apps (incl. Simple File Manager) all the files are there. 

And interesting again, the UI to browse in Simple Gallery gives file counts that exclude the old files, but the seemingly identical UI in File Manage accounts for it all.

I tried clearing cache, data and cache, etc.  The mystery partial folders stay this way.  They all exist in /sdcard/Pictures/My Collections

**Comment by tibbi** [comment]
you can unhide files with the free gallery for now, or basically any file manager

**Comment by EkriirkE** [comment]
The trouble is it's only Gallery that thinks they are hidden.  They are easily findable everywhere else...  And as far as I know "hidden" in native android means a preceding "." which none of these files or folders have

**Comment by tibbi** [comment]
nope, hiding in gallery apps is also done by putting an empty ".nomedia" file into a folder
