### ISSUE TITLE
[bug] low resolution photo

### ISSUE THREAD

**Issue by creeper451** [SimpleMobileTools/Simple-Gallery#2490]
first off thanks for this amazing app I love it
I found a bug when i go to this photo it gets messy 
![fmryipszzk091](https://user-images.githubusercontent.com/92668459/170854260-d8a17158-e8aa-4780-bbe4-13f9c69d23c8.jpg)

**Comment by tibbi** [comment]
not sure what you mean, what is messy?

**Comment by creeper451** [comment]
when I open this photo the dark area looks pixilated but in google images it looks just fine here is a zoomed in screenshots in both google image and simple gallery
google images:
![photo from google images](https://user-images.githubusercontent.com/92668459/170858979-1a5acb27-79e8-46c3-9e05-81cf1b1baa46.png)
simple gallery:
![photo from simple gallery](https://user-images.githubusercontent.com/92668459/170858987-b44ec192-e85f-4696-bad5-1439a428c0a3.png)

**Comment by tibbi** [comment]
enable showing images in the highest possible quality in the app settings
