### ISSUE TITLE
Why copy/move to sd card is very slow ?

### ISSUE THREAD

**Issue by AlbatorV** [SimpleMobileTools/Simple-Gallery#2491]
Hi,
Why copy/move to sd card is very slow ?
Since many release, I use Samsung Gallery or Samsung Explorer or Solid explorer to copy/move medias beacause Simple Gallery is very very very slow or operation is not progressing or stop.

Test :
- Move 100 files (30mo) to SD card with Simple Gallery -> 3min to move 30 files then nothing
- Same opération, same files, same destination with Samsung Explorer "My files" -> 25sec

Simple Gallery 6.23.8
Samsung S9 / Android 10

**Comment by Majura-fi** [comment]
You might want to try version 6.22.3. After updating to version 6.23.0 the file transfer becase super slow.

**Comment by tibbi** [comment]
should be fixed in 6.23.10

**Comment by AlbatorV** [comment]
Confirmed. Thanks
