### ISSUE TITLE
Wrong files get deleted in fullscreen view

### ISSUE THREAD

**Issue by Midi-In** [SimpleMobileTools/Simple-Gallery#2492]
This bug occurs only sometimes, and I am not sure what triggers it, but sometimes, when I attempt to delete an image, which is currently in fullscreen, it stays untouched, and instead a file which is immediately next to it (usually the newer one, date-of-creation-wise) gets removed. This is s serious bug, because the user can unknowingly delete her important files.

Environment in which this bug occurs:
• Simple Gallery 6.23.7 (F-Droid)
• Android 9 Pie
• Asus X00TD

**Comment by tibbi** [comment]
has been fixed in 6.23.8 already
