### ISSUE TITLE
Bypass paywall - customize colors

### ISSUE THREAD

**Issue by Quinten0508** [SimpleMobileTools/Simple-Gallery#2493]
Using an Activity Launcher app (I used https://github.com/MuntashirAkon/AppManager here), one can launch the activity Customize Colors (Pro):
"com.simplemobiletools.gallery/com.simplemobiletools.commons.activities.CustomizationActivity"

Problem is, one can launch this activity without actually having paid for the Pro license, and you are able to change the app and app icon colors this way.

**Comment by tibbi** [comment]
the Pro versions can be downloaded for free anyway
