### ISSUE TITLE
Show hidden folders missing on Play Store version

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#2494]
6.23.7 Pro from F-Droid has the feature, but 6.23.8 from Play Store doesn't.

**Comment by tibbi** [comment]
ye, it cannot be there due to new system restrictions

**Comment by floppyD** [comment]
Gallery apps aren't allowed to use MANAGE_EXTERNAL_STORAGE? I thought they were on the exception list

**Comment by tibbi** [comment]
nope, they cannot access it

**Comment by hashnag** [comment]
FYSA, I assume this is the policy referred to: https://support.google.com/googleplay/android-developer/answer/10467955?hl=en
