### ISSUE TITLE
Rename image field uses an orange accent color

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#2495]
It should follow the accent color set under "Color customization"
6.23.7 F-Droid

![Screenshot_2022-05-30-01-17-23-192_com simplemobiletools gallery pro](https://user-images.githubusercontent.com/29208110/170916379-a368fc34-5b80-4ad9-93b8-b25eca03d9cc.jpg)

**Comment by tibbi** [comment]
and what is your accent color, white?

**Comment by floppyD** [comment]
ECECEC
Black & White theme

It's only on that dialog box, renaming folders and images without opening them is fine

**Comment by floppyD** [comment]
Just to be clear

https://user-images.githubusercontent.com/29208110/170995945-f3010e96-259b-4457-a22a-79b72b095590.mp4

**Comment by tibbi** [comment]
ye, I know what you mean. The fullscreen view uses a different theme as the system bar and navigation work differently, will take a look at it.

**Comment by tibbi** [comment]
will be fixed with other styling updates in 6.24.0
