### ISSUE TITLE
how to set config.defaultFolder

### ISSUE THREAD

**Issue by 06041989** [SimpleMobileTools/Simple-Gallery#2498]
I was looking for how to make such an option when i found `openDefaultFolder()` already exists (in mainactivity). I tried setting 
`defaultFolder = /storage/emulated/11/[folder]` at the bottom of the config file and imported it but it did not work. I also couldn't find the `setAsDefaultFolder` setting in the options menu. What can I do to make it work? I don't mind changing some code. Thanks

**Comment by saefthe** [comment]
Hello, sorry for the delay in the message, only I can't speak English

Saef

في الخميس، ٢ حزيران ٢٠٢٢, ١١:٣٢ م Tibor Kaputa ***@***.***>
كتب:
