### ISSUE TITLE
UI : Bottom bar 

### ISSUE THREAD

**Issue by S-Sajith** [SimpleMobileTools/Simple-Gallery#2500]
>Add bottom bar with tabs like
---> Folder view
---> Timeline view 
---> Settings

>For UI reference , I like the UI of this app which has been abandoned , maybe you can look to it for some inspiration
https://play.google.com/store/apps/details?id=com.curator.android&hl=en_IN&gl=US

![Screenshot_20220603-220833-654](https://user-images.githubusercontent.com/88919814/171908753-6ce67255-d074-4aa9-9eed-c67f2f134fc8.png)

>Also you can use material 3/you style styling to the bottom bar to give the app a much needed facelift.

![Screenshot_20220603-221750-086](https://user-images.githubusercontent.com/88919814/171909643-33912113-11e2-4086-a97e-d4d73ec851ec.png)

**Comment by tibbi** [comment]
that isnt really on the roadmap, moving the menu in general at the bottom is planned though
