### ISSUE TITLE
Keep old last-modifield value not working

### ISSUE THREAD

**Issue by J4CKED** [SimpleMobileTools/Simple-Gallery#2501]
The "**Keep old last-modifield value on file operation**s" option is checked but does not work. I also tried unchecking this option, same situation.
The date of modified files is updated.

Android 12
v6.23.9 proprietary

**Comment by saefthe** [comment]
مرحبا
لا اريد الغاء


Saef

في السبت، ٤ حزيران ٢٠٢٢, ٢:٣٧ م J4CKED ***@***.***> كتب:

**Comment by J4CKED** [comment]
An old bug from the topic
https://github.com/SimpleMobileTools/Simple-Gallery/issues/2321

**Comment by J4CKED** [comment]
Why closed?

**Comment by tibbi** [comment]
duplicate of #2321
