### ISSUE TITLE
"Manage hidden folders" option

### ISSUE THREAD

**Issue by Kietyo** [SimpleMobileTools/Simple-Gallery#2503]
Similar to how in the settings we have "Manage included folders" and "Manage excluded folders", I'd like the option to manage hidden folders as well. The downside of the current hide system is that it does not allow you to hide a parent directory if that parent directory does not contain any photos.

**Comment by tibbi** [comment]
that wont be added, you will be able to temporarily show excluded in the next app version to replace hiding in some way
