### ISSUE TITLE
Deleting a file while using an RTL language takes me back to first picture in folder

### ISSUE THREAD

**Issue by mhmdanas** [SimpleMobileTools/Simple-Gallery#2508]
Steps to reproduce:
1. Switch to an RTL language (Arabic in my case)
2. Open any folder in Simple Gallery
3. Tap on an image to view it in fullscreen
4. Press on the trash icon at the bottom to delete the image, and confirm the deletion when the confirmation dialog is shown 

## Expected behavior

The picture next to the one just deleted in the folder is displayed (at least this is what happens when I set the system language to English).

## Actual behavior

The first picture in the folder is displayed.

**Comment by DrSaad77** [comment]
It happens also to me, lets say there are 100 pic is a folder, and during sliding pic with SimpleGalery, I decided I dont like picture 34, and I want to delete it. After deleting it, hope I brings back and show the first picture of the folder!

**Comment by Naveen3Singh** [comment]
Seems related to this line: https://github.com/duolingo/rtl-viewpager/blob/940f12724ff0fe624f12e8218b2b967891aa5396/src/main/java/com/duolingo/open/rtlviewpager/RtlViewPager.java#L98

maybe it's time to switch to ViewPager2

**Comment by tibbi** [comment]
we can switch to whatever works
