### ISSUE TITLE
Viewing videos snaps back to first file in folder instead of desired file.

### ISSUE THREAD

**Issue by akeb1a** [SimpleMobileTools/Simple-Gallery#2509]
Don't know when exactly this started happening, currently using 6.23.11 Pro, on Android ~~11~~ 10
Folder structure is like this:

SD card root
- Folder ABC
-- Folder 123
--- x number of video files
-- Folder 456
[etc]

I tap on any video file but the first, when the preview window opens, it displays the thumbnail of the chosen file for half a second before snapping back to display the first file in the folder (even if it's not a video file), and I have to manually swipe right all the way to whatever video I wanted to watch. This gets annoying quick in a folder with 30+ videos. I can prevent this by immediately playing the video before it snaps to the first file (or checking "Play videos automatically" in the settings), which seems to "interrupt" this behavior, allowing me to play the desired file, but doing so prevents me from being able to swipe right/left to the next or previous video afterwards, when you could do this in earlier versions.

This behavior happens in folders with one or more of the following types: .webm, .mp4, .mov files. 
Strangely, .mkv doesn't seem to be affected. 

edit: .gif files are also unaffected, so this should purely be something with video files.

**Comment by hydrargyrum** [comment]
I experience the same problem for jpg files (I did not test videos): when selecting any image from a file manager, it briefly displays the chosen image (a few milliseconds) and quickly switches to the first image (by name) of the folder, which is very irritating because I won't swipe to reach the desired image when there are dozens (or hundreds!) of photos.

**Comment by hydrargyrum** [comment]
Version 6.23.7 is the last version that works properly, all subsequent versions are buggy.

**Comment by DrSaad77** [comment]
I am experiencing the same issue, from version 6.23.X !
You described the issue properly, I did not know at first, if was related to my files manager, or to Simple Galery!!
And each time, a new version is pushed and the issue persist.

**Comment by DrSaad77** [comment]
> Don't know when exactly this started happening, currently using 6.23.11 Pro, on Android 11 Folder structure is like this:
> 
> SD card root
> 
> * Folder ABC
>   -- Folder 123
>   --- x number of video files
>   -- Folder 456
>   [etc]
> 
> I tap on any video file but the first, when the preview window opens, it displays the thumbnail of the chosen file for half a second before snapping back to display the first file in the folder (even if it's not a video file), and I have to manually swipe right all the way to whatever video I wanted to watch. This gets annoying quick in a folder with 30+ videos. I can prevent this by immediately playing the video before it snaps to the first file (or checking "Play videos automatically" in the settings), which seems to "interrupt" this behavior, allowing me to play the desired file, but doing so prevents me from being able to swipe right/left to the next or previous video afterwards, when you could do this in earlier versions.
> 
> This behavior happens in folders with one or more of the following types: .webm, .mp4, .mov files. Strangely, .mkv doesn't seem to be affected.
> 
> edit: .gif files are also unaffected, so this should purely be something with video files.

I installed version 6.22.2, and it works without that issue.

**Comment by akeb1a** [comment]
> I experience the same problem for jpg files (I did not test videos): when selecting any image from a file manager, it briefly displays the chosen image (a few milliseconds) and quickly switches to the first image (by name) of the folder, which is very irritating because I won't swipe to reach the desired image when there are dozens (or hundreds!) of photos.

I didn't notice since I generally only use Simple File Manager for copying/moving files around the filesystem, but you're right, this behavior seems to also happen when opening files in Gallery via SFM, so it may be related.

**Comment by Naveen3Singh** [comment]
Hey guys!

I could not reproduce this with a bunch of videos placed as `/DCIM/Recorded/*.mp4`. Images also seem to load just fine on my phone, clean install.

Does it happen only sometimes?
Could someone pls share a recording or step-by-step instructions to reproduce this bug?

**Comment by tibbi** [comment]
possibly related to https://github.com/SimpleMobileTools/Simple-Gallery/issues/2508

**Comment by akeb1a** [comment]
> Hey guys!
> Does it happen only sometimes? Could someone pls share a recording or step-by-step instructions to reproduce this bug?

Hi, I did some more testing - the most reliable way of triggering this seems to be if one of the folders in the path is actually hidden, ie (SD_ROOT:\**_.HiddenFolder_**\ContainerFolder\004.mp4), though this isn't a catch-all, I think. 
I will try to capture some footage of this and do some more tests, but I need to find a smaller SD card first since it takes a really long time to get Simple Gallery to do a fresh load of my 128GB card just renaming folders and files over and over

**Comment by akeb1a** [comment]
Here's the folder structure of the files I used to test on a fresh SD card:
![image](https://user-images.githubusercontent.com/85966015/173438411-7e04f170-9c46-4266-8822-c4718e425dc1.png)
Note: I added both ROOTFOLDER_TEST and ROOTFOLDER_TEST\.HID_FOLDER to Included Folders for good measure.
For some reason, it does not trigger on the first time you open the file, hence why I open each file twice to demonstrate.
https://user-images.githubusercontent.com/85966015/173443802-dd242a78-a43e-4957-af23-3abc827cbe8a.mp4

This second recording is demonstrating @hydragyrum and @DrSaad77's issue with the filemanager which may be related in some way.
https://user-images.githubusercontent.com/85966015/173443805-aae04c86-02e7-4217-887c-44f5454cdbf8.mp4

**Comment by tibbi** [comment]
so you have the app from F-droid and not Google Play? You haven't mentioned that.

**Comment by akeb1a** [comment]
I believe the version I have installed is from Google Play

**Comment by tibbi** [comment]
not really, that cannot be the case. You say that you included some folders and you also have a Temporarily show hidden files there.

**Comment by akeb1a** [comment]
I have "Show hidden items" unchecked (see at 0:15-0:16), that's why "Temporarily show hidden files" is in the menu, if that's what you're asking. I included the folders just to make sure they would show up since sometimes it takes a while for the app to pick up all the folders on the card. The same behavior still happens after removing the folders from included.

**Comment by tibbi** [comment]
Im saying that hidden items and included folders arent supported on Google Play version on Android 11+ anymore

**Comment by akeb1a** [comment]
...Did some quick checking, sorry, I'm on Android 10, not 11. Is it no longer supported?
I'll update my first post. I definitely have only installed the app from Google Play's store, however.

**Comment by Catfriend1** [comment]
I went back to 6.19.1 which lay around and the problem did not reoccur. On recent versions, I could reproduce it by deleting files with the material files app from the DCIM/Camera folder and then the weird behavior began after opening another still existing jpg image from material files using simple gallery pro. It snaps to the first image, plus, when I tried to delete another image from the folder through SG, the wrong file (1 index after) got deleted.

**Comment by Naveen3Singh** [comment]
Thank you all for the reports.
I'm working on this and the bug will be fixed soon :+1:

**Comment by Naveen3Singh** [comment]
Anyone up for testing?

If you prefer and can build an apk yourself, build from this branch: https://github.com/Naveen3Singh/Simple-Gallery/tree/position_glitch

or

If you want to just install an apk, download debug apk from here: https://github.com/Naveen3Singh/Simple-Gallery/releases/download/position_glitch/gallery-370-foss-debug.apk

thanks

**Comment by akeb1a** [comment]
I'll be able to test after the weekend and hopefully close this issue then, thanks for your work :)

**Comment by akeb1a** [comment]
Hey again, I had a chance to quickly test out the provided apk - seems to fix the issue with both the gallery and opening from file manager in my test cases. I'll probably play around with it for a bit longer to make sure it doesn't break with something else, but as far as I can tell, this works!
If other users experiencing can test to confirm as well that would be great.

I will close the issue for now as it seems to be fine on my end, so I will wait for the official update with this, thanks!

**Comment by tibbi** [comment]
alright thanks, let me know if you find some related issue
