### ISSUE TITLE
Gallery constantly prompts for All Files access

### ISSUE THREAD

**Issue by Steve-at-Ford-Lodge** [SimpleMobileTools/Simple-Gallery#2518]
Gallery does not need All Files permission for its basic functionality, but requests that the user enables it EVERY TIME the app starts. This is bugging me so much that I may de-install it.

The best solution would be to have a setting in the app that the user can enable or disable, and ask ONCE for the permission if the option is changed.

**Comment by tibbi** [comment]
Just find it in your device settings then and grant it the Media files access.

**Comment by Steve-at-Ford-Lodge** [comment]
Please re-read the issue. The app is nagging for ALL FILES permission. If I hadn't granted Media Files permission, none of the functionality would work.

Anyway. I've uninstalled it.
