### ISSUE TITLE
Remove EXIF of multiple images

### ISSUE THREAD

**Issue by yephny** [SimpleMobileTools/Simple-Gallery#2519]
You can go to the info page of each image and clear the exif data one by one, which isn't feasible when you want to do it for multiple images. It would make sense to add a `remove exif` button under `Fix data taken value` in the menu when you select multiple images.

**Comment by tibbi** [comment]
isnt it there already?

**Comment by tibbi** [comment]
I mean it is there at the Properties, where it is at selecting a single item

**Comment by yephny** [comment]
@tibbi I did take note of the existing remove exif feature in my post. The feature I am requesting here is removing exif of multiple images at the same time, say 1000 images.

**Comment by yephny** [comment]
Would you mind reopening the issue?

**Comment by tibbi** [comment]
you can check Properties and delete EXIF there

**Comment by saefthe** [comment]
مرحبا كيف حالكم

Saef

في الجمعة، ١٧ حزيران ٢٠٢٢, ١٢:٤١ ص Tibor Kaputa ***@***.***>
كتب:

**Comment by yephny** [comment]
@tibbi You're right, I'm sorry for wasting your time. The feature's there already, it really took me a full day to realize what you actually meant.
