### ISSUE TITLE
DocumentsUI file access prompt for App-Specific directories (/Android/data or obb) does not appear for SD Card - Included folders

### ISSUE THREAD

**Issue by jonathan2384** [SimpleMobileTools/Simple-Gallery#2521]
# Summary
When using the "Included Folders" feature (available when All Files permission is enabled and within the in-app Settings), the app prompts the user to `Please allow the app accessing the selected storage on the next screen by pressing 'Use this folder' at the bottom.` when an app-specific directory restricted in Android 11 (e.g `/storage/emulated/0/Android/data/`) is selected for inclusion. 

![Screenshot_20220619-021652_Gallery](https://user-images.githubusercontent.com/93066841/174450004-57b86edb-75c0-43b2-bbc0-f8c68c2223fc.jpg)
*The prompt before the DocumentsUI system permission. Please note that the path selected includes "Internal".*

When confirmed, it pops up a DocumentsUI pane that allows the user to give permission. 

![Screenshot_20220619-021900_Files](https://user-images.githubusercontent.com/93066841/174450036-9460d09f-6ce4-4e45-ad9c-b0a684cb1c37.jpg)

After the permission is granted, access to all app-specific directories are available. Please note the "1 folder" in the below screenshot signifying that access is available.
![Screenshot_20220619-021820_Gallery](https://user-images.githubusercontent.com/93066841/174450123-10ba04c1-efe4-433d-8f17-41cd1584e150.jpg)

---

However, this prompt does not appear for an app-specific directory located on the SD card (e.g `/storage/abcd-efgh/Android/data/`). It only appears for the directory in the Internal Storage.

This results in Simple Gallery being unable to read and include directories (through the Included Folders feature) that are located in /Android/data and on the SD card. 

![Screenshot_20220619-021748_Gallery](https://user-images.githubusercontent.com/93066841/174450134-594d44f2-242b-435b-afbe-9147f3c7f7a6.jpg)
*Because there is no SAF file access prompt in the SD card, Simple Gallery is unable to display and access files contained in app-specific directories of other apps - the app is only able to access its own directory ("1 Folder") and not the others.*

# How to reproduce
1. Insert a SD card. Ensure that the Android/data directory is populated by apps.
2. Open the Included folders settings pane.
3. Click on the "Internal" in the top left corner and switch the directory to "SD Card".
4. Navigate to Android/data or /obb folder. There should be no file permission prompt.

**Comment by tibbi** [comment]
so to wrap it up, what is the final issue here? Im a bit confused. File operations in some folders arent possible?

**Comment by jonathan2384** [comment]
Yes; file operations in the /Android/data and /Android/obb directories on the SD card is not possible.

-------- Original Message --------

**Comment by tibbi** [comment]
why is your /Android on an SD card? What setting have you changed?

**Comment by KryptKode** [comment]
Android does not let us select `Android/[data|obb]` on the SD card with Storage Access Framework on Android 12, just the primary volume. I will confirm on Android 11.

**Comment by KryptKode** [comment]
I was wrong. 
On testing, I found out it's actually possible to select the `Android/[data|obb]` on the SD card with Storage Access Framework on Android 11+. 

I will raise a pull request for the changes. 

@jonathan2384  could you help test? I will send the APK

**Comment by jonathan2384** [comment]
Hey - thanks for addressing this issue and providing the test APK. I've installed it and given it a spin, and I can confirm that the Simple Gallery application can read data from the SD card's OBB/data directory once given permission with the newly implemented permission prompt.

![Screenshot_20220620-100225_Gallery_debug](https://user-images.githubusercontent.com/93066841/174509303-38bf00ed-bb78-4d08-8075-652258f6ab1c.jpg)
![Screenshot_20220620-100521_Gallery_debug](https://user-images.githubusercontent.com/93066841/174509312-e884d00e-1d7e-49e9-bdf2-57cf993c808d.jpg)
*able to read from SD card's obb/data directory perfectly*

---

However, I think this may have revealed a different second bug in the Simple Gallery - images from an included directory that is in any `Android/obb or /data`, regardless of whether it is in the internal emulated storage or the SD card do not appear in the gallery, although it appears that Simple Gallery is able to read from those directories. I've confirmed that the functionality works correctly with other directories that are not `Android/obb or /data`.

![Screenshot_20220620-102734_Files](https://user-images.githubusercontent.com/93066841/174509834-add05285-6e2c-431a-badf-b20d7889559e.jpg)
*Directory is added to "Included folders" and it's populated with images.*

![Screenshot_20220620-102751_Gallery](https://user-images.githubusercontent.com/93066841/174509911-91f6d0b1-bcdf-4208-960c-53ed4f539f18.jpg)
*Despite that, contents of the directory do not show in the Gallery view. SD card and Emulated Storage root is excluded but including overrides the exclusion*


This pull request does appear to be unrelated to this new bug, and it appears to allow the Simple Gallery application to read perfectly from a SD card's OBB or data directories - thank you for that. 

It also appears that it will address the DocumentsUI file access issue on SD card for all Simple Apps, including the Simple File Explorer, so I believe it is best to merge the PR and close this request, and create a new issue for the second `images from an included directory that is in any Android/obb or /data, regardless of whether it is in the internal emulated storage or the SD card do not appear in the gallery, although it appears that Simple Gallery is able to read from those directories` bug.

**Comment by jonathan2384** [comment]
> why is your /Android on an SD card? What setting have you changed?

I believe that Android automatically creates default directories on every drive (both SD and OTG USB) that is mounted, including /Android. This has been default behavior for a while; it's been documented on various websites including https://forum.xda-developers.com/t/prevent-otg-from-creating-folders.4064663/
