### ISSUE TITLE
Feature Request: Button at top to show all folder content 

### ISSUE THREAD

**Issue by Rafee-M** [SimpleMobileTools/Simple-Gallery#2525]
![Screenshot_2022-06-21-02-53-25-71_29b563cd0bc4fd07bd0c105b17b28204_1](https://user-images.githubusercontent.com/69535896/174676760-9c070346-67d3-4b1d-98e9-4e3f1c503247.jpg)
An option to add a button here to show all the folders content quickly could be really useful instead of going to the menu at the top right.

**Comment by DesignRTL** [comment]
+1

@tibbi 

Yes : THIS IS A MUST MUST MUST HAVE FEATURE.

I also find very frustrating going to menu and show all, and that loads slow also.

Having a button on the top (also if u could make it fast load somehow) would be so much relief.

**Comment by AliWhoi666** [comment]
@tibbi This'd be really amazinggg

**Comment by Rafee-M** [comment]
Has been added

**Comment by saefthe** [comment]
مرحبا كيف حالكم
سحاول افعل كما طلبتو مني
وشكرا التعبكم

Saef

في السبت، ٦ أيار ٢٠٢٣, ٧:٥٤ ص Raf ***@***.***> كتب:
