### ISSUE TITLE
Do not overwrite Original Picture after editing

### ISSUE THREAD

**Issue by jerryn70** [SimpleMobileTools/Simple-Gallery#253]
When I edit a picture and didn't give it a new name then It will be overwrited an i will loose the original picture.  If I give a new name while saving it saves as a seperate picture keeps the original. 

Most of the time accidentally we(me) forget to give different name. It will leads to loss of file.

●HOW TO REPRODUCE●

Open a picture - edit - crop - save without giving new name or anything.  

Result = orginal picture will be overwrited by the edited one.

Open a picture - edit - crop - save it with a new name .
Result = Original and edited will be in the gallery.

**Comment by tibbi** [comment]
if you save the edited file with the originals name, of course its rewritten, nothing wrong with that.

**Comment by Theobald93** [comment]
Maybe a security message would "defuse" this "problem". But i am fine with the logics right now.

**Comment by Theobald93** [comment]
Tibbi added the overwrite dialog in release 2.10.7
