### ISSUE TITLE
multiple images (Picker) not handled 

### ISSUE THREAD

**Issue by baraa272** [SimpleMobileTools/Simple-Gallery#2534]
Poco X3 pro 
MIUI 13.0.4
Version 6.23.11 
It's very important function and it seems it was broken with newer updates since I was able to select multiple images (Picker) for other programs like discord/Instagram and such
I'm on F-droid version 6.23.11 and facing this issue where when you open simple gallery from other applications (multiple images picker) it doesn't handle it properly (doesn't show done button) and open like you normally opened gallery for viewing however other gallery apps like miui gallery / google gallery works as intended

**Comment by tibbi** [comment]
It should work just fine, try selecting multiple thumbnails by long pressing them. If it still doesnt work, tell exact steps for reproducing the issue please.

**Comment by baraa272** [comment]
Issue fixed in this build from fdroid 
![Screenshot_20220729-233513_Gallery](https://user-images.githubusercontent.com/32843097/181839391-c6e0cb0d-a8ca-483c-925d-eec71122dd40.png)
