### ISSUE TITLE
Cannot swipe to change video media in fullscreen view

### ISSUE THREAD

**Issue by kingishksh** [SimpleMobileTools/Simple-Gallery#2539]
Whenever I view any video file within a folder, I am unable to swipe left/right. Swiping left/right for picking any other media type works just as intended, and the only way to swipe when viewing a video file is by first picking a different media file

**Comment by tibbi** [comment]
does it depend on the video or folder, or it happens always everywhere? Do you use random sorting in the given folder by any chance?

**Comment by kingishksh** [comment]
happens in all folders i use. they are all organized by last-modified. this happens anytime i select a video (.mp4, .webm, etc.) in fullscreen. my apologies for not mentioning this sooner, i will change the title accordingly. here's a video demonstrating the issue as well
[Screen_Recording_20220704-054032_Gallery.webm](https://user-images.githubusercontent.com/58454027/177158984-4e34fe80-3f6f-41c7-a409-7f48b2a0d106.webm)

**Comment by Naveen3Singh** [comment]
Hey @kingishksh 

If you can test out a possible fix, download the apk from here: https://github.com/Naveen3Singh/Simple-Gallery/releases/download/pager_fix/gallery-371-foss-debug.apk

If you do test it, lmk how it goes, thanks

**Comment by kingishksh** [comment]
@Naveen3Singh I couldn't install it on my phone but I tested it out on Bluestacks and it seems to have solved the issue in question
