### ISSUE TITLE
Limit the number of itens to be shared

### ISSUE THREAD

**Issue by edcaron** [SimpleMobileTools/Simple-Gallery#255]
I selected 1k+ items and tried sharing but, the app does nothing and crashes after some seconds. Can it be because its too many items?

If its the cause, the app should have a validation before sharing.

**Comment by tibbi** [comment]
Ive added exception handling at sharing files, it should print a message instead of a crash if something goes wrong. Theres no limit I could apply, just catch errors and show it to the user.
