### ISSUE TITLE
Option to hide filenames

### ISSUE THREAD

**Issue by josefson** [SimpleMobileTools/Simple-Gallery#2551]
I think it would be good to have an option to hide filenames. Most filenames are auto-generated and consistent of alfa-numeric values.
Having them displayed at the bottom right of the picture gives little to no value except pollute the screen.
So I think it would be a good addition to have an option to hide filenames from being shown.

**Comment by tibbi** [comment]
on which screen you mean? Havent you enabled them accidentally at the thumbnails by the top menu item?
