### ISSUE TITLE
Unknown authority com.android.externalstorage.documents

### ISSUE THREAD

**Issue by MarcoReckless** [SimpleMobileTools/Simple-Gallery#2555]
I'm getting this **error** whenever I tried to delete any picture, I'm running **Android 11** (OxygenOS) and **have given all the permissions** asked by the app.

![unnamed](https://user-images.githubusercontent.com/13008862/178489212-880c5c68-6bd2-487e-9b5f-6e3aa36715e7.jpg)

**Comment by tibbi** [comment]
try reinstalling the app
