### ISSUE TITLE
[Bug] Navbar not properly colored when using 'System Default' theme

### ISSUE THREAD

**Issue by robotwombat** [SimpleMobileTools/Simple-Gallery#2560]
The navbar background color is great in the standard theme:
![Screenshot_20220716-135958_Gallery](https://user-images.githubusercontent.com/44946401/179366854-4d8ae806-8ac2-4b07-bdd0-115ab3beafe1.png)

However, when using the 'System Default' theme, the navbar background color doesn't match:
![Screenshot_20220716-135928_Gallery](https://user-images.githubusercontent.com/44946401/179366999-05001590-20d7-4cf8-8e6f-31ee62b4ee33.png)

**Comment by tibbi** [comment]
can you maybe test how it works with Simple Music Player from https://play.google.com/store/apps/details?id=com.simplemobiletools.musicplayer ? All apps are currently being redesigned a bit and the music player is the latest updated app.

**Comment by robotwombat** [comment]
> can you maybe test how it works with Simple Music Player from https://play.google.com/store/apps/details?id=com.simplemobiletools.musicplayer ? All apps are currently being redesigned a bit and the music player is the latest updated app.

I appreciate the quick reply! :)

The navbar here is perfect:
![Screenshot_20220716-141628_Music Player](https://user-images.githubusercontent.com/44946401/179367320-3d46db28-318a-4162-9c31-dadd90434f9f.png)


However, I think the navbar background in this instance (below) should be white to match the page:
![Screenshot_20220716-141647_Music Player](https://user-images.githubusercontent.com/44946401/179367347-306d2819-c424-40ad-8914-167eff01ac35.png)

**Comment by tibbi** [comment]
alright, it will eventually be fixed automatically with the next update released soon in the gallery too, so Ill close this now to not forget doing it later :) Thanks

**Comment by robotwombat** [comment]
> alright, it will eventually be fixed automatically with the next update released soon in the gallery too, so Ill close this now to not forget doing it later :) Thanks

Thanks!
