### ISSUE TITLE
Set as wallpaper no default aspect ratio matching the screen format

### ISSUE THREAD

**Issue by Sylvain303** [SimpleMobileTools/Simple-Gallery#2564]
like in # #2309

Use-case lockscreen wallpaper (Android 9), no left right more screen only one full screen.

When I want select an image in SimpleGallery (6.23.13 Pro) as a wallpaper I do:

1. open SimpleGallery
2. navigate to an image
3. triple dot menu: "set as"
4. Wallpaper (I've a choice for as a contact too)
5. then I get a crop application, but the default doesn't match my screensize (in case of lockscreen there's no left or right screen need) 
![image](https://user-images.githubusercontent.com/274026/180135874-5b4832a6-03c4-44a1-b99e-2fb1c202d4c5.png)
6. I can use the bottom ratio button but the full screen ratio is not provided

If I'm remembering well, there was a correct aspect ratio before. So for me it's a regression.

Note, that I found I can go to the top triple dot menu, there's an "allow changing the aspect ratio"
and in this case the ratio is free and I can crop to a size that would fit the screen, but which is not bound to the actual screen size. So I've to guess and do some trial and error.

Suggested fix:

use the 
![image](https://user-images.githubusercontent.com/274026/180137219-2f5a63b5-8f1b-4469-971c-5330febbcfa3.png)
crop ratio button to allow to swap between : large multiple screen, and single screen crop.
May add a text message about the current mode selected. Actually it seems to have 3 modes in aspect ratio pre-selection, none of them seems to match my screen size (one screen wide or 3 screen wide)

**Comment by tibbi** [comment]
the required aspect ratio comes from the system. If it doesnt fit you, you can use custom aspect ratio from the top menu.

**Comment by Sylvain303** [comment]
Hi @tibbi 

As I said, it used to work previously on this phone. 

The ![image](https://user-images.githubusercontent.com/274026/180137219-2f5a63b5-8f1b-4469-971c-5330febbcfa3.png) button, was changing to a ratio that was matching the correct system screen size. I think I were able to swap from two aspect ratio: "3 times wide width of the system screen" to "one screen wide only". My actual background was set that way.

Actually the aspect ratio computed is wrong (the white area fro cropping). And, on image that already have aspect ratio similar to the screen ratio, the white box selector may even forbid to select some part of the image. That's why I call that a regression.

Obviously you're right I can "use custom aspect ratio from the top menu" but it's not as simple than having a cropping area of the correct aspect ration that could have been moved easily on the picture.

Probably it is OS version dependent? Some values may have been deprecated or available on some version not on other. I've no skill on Android app yet. So I cannot debug more for now.

What is the expected behavior of the button ![image](https://user-images.githubusercontent.com/274026/180137219-2f5a63b5-8f1b-4469-971c-5330febbcfa3.png)?

**Comment by tibbi** [comment]
that button toggles between portrait, landscape and square aspect ratio. It comes from the system so if it is wrong, the system is giving us wrong data.

**Comment by Sylvain303** [comment]
OK interesting.

Form a screenshot information I made, I got the resolution: 1440 x 2560 (I suppose it's my screen resolution)

The kungfu-panda image is: 800 x 1070

![KFP3-promo-po4](https://user-images.githubusercontent.com/274026/180483565-7ad0a2c3-714d-4038-826d-178fcdd4e794.jpg)

I suppose we are talking about this code `setupAspectRatio()`

https://github.com/SimpleMobileTools/Simple-Gallery/blob/e121a9b72b6945fbf26a3b56d972bff1d156d366/app/src/main/kotlin/com/simplemobiletools/gallery/pro/activities/SetWallpaperActivity.kt#L96

May it could be an external lib regression or behavior change?

`crop_image_view.setAspectRatio(heightToUse, widthToUse)`

I suppose `crop_image_view` is defined in the XML file [`com.theartofdev.edmodo.cropper.CropImageView`](https://github.com/SimpleMobileTools/Simple-Gallery/blob/1526b592ab8426d7ab513828f3e026435b0450a3/app/src/main/res/layout/activity_set_wallpaper.xml#L9)

Which could be this code: https://github.com/edmodo/cropper

And the 3 aspect Ratio I noticed and you explained are defined here:
https://github.com/SimpleMobileTools/Simple-Gallery/blob/e121a9b72b6945fbf26a3b56d972bff1d156d366/app/src/main/kotlin/com/simplemobiletools/gallery/pro/activities/SetWallpaperActivity.kt#L22

```kotlin
    private val RATIO_PORTRAIT = 0
    private val RATIO_LANDSCAPE = 1
    private val RATIO_SQUARE = 2
```

I wish I could debug it to have the value at runtime. ;-)

When I do "set as" on the image above without any change I get a square like area on the crop area which should be `RATIO_PORTRAIT` at the beginning and should be much more a rectangle:

![Screenshot_20220722-190220](https://user-images.githubusercontent.com/274026/180489295-19fda185-3862-438b-a5b3-c1e213e34211.png)

From the screenshot above in Gimp the white square is: 1440 × 1620 pixels

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>
<head>
	
	
	<title></title>
	<meta name="generator" content="LibreOffice 6.4.7.2 (Linux)"/>
	<style type="text/css">
		body,div,table,thead,tbody,tfoot,tr,th,td,p { font-family:"Liberation Sans"; font-size:x-small }
		a.comment-indicator:hover + comment { background:#ffd; position:absolute; display:block; border:1px solid black; padding:0.5em;  } 
		a.comment-indicator { background:red; display:inline-block; border:1px solid black; width:0.5em; height:0.5em;  } 
		comment { display:none;  } 
	</style>
	
</head>

<body>


  | W | H | ratio (W/H)
-- | -- | -- | --
kungfu | 800 | 1070 | 3/4
screenshot | 1440 | 2560 | 5/9
white | 1440 | 1620 | 8/9


</body>

</html>


no more clue yet.
