### ISSUE TITLE
Hidden pictures still visible in other apps

### ISSUE THREAD

**Issue by LohseBoi** [SimpleMobileTools/Simple-Gallery#2567]
As described in the title, the pictures I hide in the gallery can still be seen from other apps, while being hidden in the gallery app, usually when I'm uploading media (messaging, or forum posts). I don't know if this is a problem only for me, I am currently running `e/os/` on my old OnePlus 5, if that information helps.

**Comment by J4CKED** [comment]
This is normal. I'm not sure, but I think there is a message before hiding that hiding only works in this application.

There are other more advanced hiding apps.

**Comment by tibbi** [comment]
you mean individual images, right? Not folders? Images are hidden by prepending their filename with a dot. That is the system way of doing it, so if some app ignores it, it is an issue on their side.
