### ISSUE TITLE
[Feature Request] Make "Group direct subfolders" a explorer like QuickPic Gallery

### ISSUE THREAD

**Issue by KazKaz90** [SimpleMobileTools/Simple-Gallery#2571]
**QuickPick Gallery**
_The folder "Pixiv" is present_
![unknown1.jpg](https://user-images.githubusercontent.com/90075041/181657004-0ada11b7-2eda-4580-be16-5b81b178adb1.jpg)

**Simple Gallery**
_The folder "Pixiv" is not present_
![unknown2.jpg](https://user-images.githubusercontent.com/90075041/181657059-42ebb7d6-4976-426d-a663-a20c8d98b81b.jpg)

_Instead it's on the upper directory even though "Pixiv" folder is inside "DCIM" folder_
**I think it's also because I added another folder inside "Pixiv" called "1" where the images are located but yeah, can you make it like a "Explorer Mode" from QuickPic Gallery**
![unknown3.jpg](https://user-images.githubusercontent.com/90075041/181657342-8b2a8f7a-6543-4b3f-936e-c9886cafdac2.jpg)
![unknown4.png](https://user-images.githubusercontent.com/90075041/181657489-11f9db22-8e05-4d39-8de6-e7a2ad3d2075.png)

Making it more like QuickPic Gallery _"Explorer Mode"_ could help because this _"Group direct subfolders"_ is so confusing.

Here's the github page:
https://github.com/WSTxda/QP-Gallery-Releases

**Comment by Aga-C** [comment]
@tibbi Similar app, also with calendar app, is on the Play Store, all with ads: https://play.google.com/store/apps/developer?id=TINY+ENTERTAINMENT. Looks like plagiarism.

**Comment by KazKaz90** [comment]
> @tibbi Similar app, also with calendar app, is on the Play Store, all with ads: https://play.google.com/store/apps/developer?id=TINY+ENTERTAINMENT. Looks like plagiarism.

That is not the app, the github page of QuickPic Gallery is linked below this issue, additionally, Simple Apps are FOSS apps, so seeing a clone with ads on the PlayStore is not surprising.

**Comment by KazKaz90** [comment]
The dev has completely ignored this, so I'm closing it.
