### ISSUE TITLE
Buttons at the bottom are gone or invisible (ver. 6.24.0)

### ISSUE THREAD

**Issue by Saboe** [SimpleMobileTools/Simple-Gallery#2575]
There aren't any buttons at the bottom visible when one or more pictures are selected.
In the settings --> bottom actions - show some action bottoms ... - is checked, several buttons are selected, but none of theses buttons are visible.
Simple Gallery ver. 6.24.0 Pro

Used phone:
Fairphone FP3
Android 11, build 8901.4.A.0010 release-keys

**Comment by tibbi** [comment]
that setting is about the fullscreen view, not thumbnails view
