### ISSUE TITLE
[bug] png gets worst when selected

### ISSUE THREAD

**Issue by creeper451** [SimpleMobileTools/Simple-Gallery#2584]
https://user-images.githubusercontent.com/92668459/184480312-a402d327-738b-4e88-b27c-867df6744fca.mp4

here's the image:
[image bug.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/9331257/image.bug.zip)

**Comment by tibbi** [comment]
what app and OS version are you using? Apparently the deep zoomable image loads the image differently, you can disable it in the app settings for testing.

**Comment by creeper451** [comment]
I'm running Android 7 with simple gallery 6.23.11,
i tried disabling deep zoom and it displays correctly now, thank for the help.

**Comment by tibbi** [comment]
right, that has been reported somewhere else already, so Ill close this one. Thanks
