### ISSUE TITLE
Updating media externally resets date taken to last modified date when sorting

### ISSUE THREAD

**Issue by Terrance** [SimpleMobileTools/Simple-Gallery#2586]
For context: I use digiKam on a PC to tag my photos, along with Syncthing to both pull the photos from my phone and later push the tag updates back, keeping the phone and PC copies in sync.  I'm not changing the date taken on any pictures, but when I edit other tags on a photo, the app starts using the new modified date as the date taken when sorting.

If I then view the photo, the corner metadata shows the correct date taken, which suggests this only affects the sort order.  I can see this has been reported before (e.g. #2260) and the response has been to use the Fix Date Taken option, which I assume updates a cached copy of the date taken?  This doesn't work well when working with tags across many photos at once, as I have to do this regularly to large chunks of my camera roll in order to send them back to the dates where they belong.

As it stands, the app seems to detect changes to the metadata (the sort order becomes upset straight away), so this ought to trigger a rescan and re-read the date taken, or failing that shouldn't update the date at all -- modified date is only representative when the file is first seen (i.e. as a proxy for creation date).

**Comment by tibbi** [comment]
if you check the file Properties, does it show the proper date taken value?

**Comment by Terrance** [comment]
The extended details was showing the right date, didn't check the properties popup at the time.

Having just fiddled with the grouping setting, I can't seem to repro this now -- previously this was happening routinely with sort by date taken / no grouping, but it seems to be sorting correctly now whether grouping or not.

**Comment by Terrance** [comment]
Having done another batch of tagging, I've now got a hundred or so photos appearing under the modified date again, despite both grouping and sorting set to date taken.

> if you check the file Properties, does it show the proper date taken value?

Both the properties screen and the extended details are showing the correct date taken (last week) and last modified (yesterday).

**Comment by Wintandre** [comment]
Just came here to raise the same issue.

I have Gallery set to Sort by "Date Taken", "Descending", and Group by is set to "Date Taken (monthly)", "Descending".

I connected my phone to the PC and copied a bunch of images from the PC to the phone into a sub-folder of the DCIM folder. I then unounted the phone from the PC, and started the Gallery app. Within the new folder/section, all images are all grouped as September 2022. However, if I view the properties of any of the images, they all show the correct date of 10 years ago.

Version is 6.24.1 Pro

**Comment by Wintandre** [comment]
Sorry @tibbi I swear I tried that before, however it did resolve the issue for me. Thanks.

**Comment by tibbi** [comment]
Checking file by file would be really slow, so at sorting by Date Taken the app relies on the system MediaStore, which is kind of an internal database storing file metadata, like Date Taken. If you do "Fix Date Taken values", it takes the Date Taken from the file itself and updates the value in the database.

**Comment by tibbi** [comment]
anyway, it works as expected now, we cannot do much else there as it is described in the FAQ too. I dont want to do any rescanning and fixing in the background.

**Comment by Terrance** [comment]
Fair enough, though the last part of the original issue still stands:

> ...or failing that shouldn't update the date at all -- modified date is only representative when the file is first seen (i.e. as a proxy for creation date).

What's the rationale for using the modified date as date taken?  Either the image has a previous date taken cached (in which case it should probably be kept as-is if you don't want to rescan) or it didn't have one before (in which case the modified date when the file was first scanned should have been cached, and shouldn't be updated again now).
