### ISSUE TITLE
Can't recognize .nomedia

### ISSUE THREAD

**Issue by KazKaz90** [SimpleMobileTools/Simple-Gallery#2589]
I'm not sure why, but Simple Gallery continues to display photos and videos that have been hidden with `.nomedia`, other gallery apps recognize the presence of `.nomedia`, but Simple Gallery does not. **"Temporary show hidden"** and **"Show hidden items"** are disabled.
Tried refreshing my mediastore also tried restarting my phone a lot of times already but it still does not recognize the `.nomedia`.

App Version: 6.24.1 FOSS
Device: Tecno Spark 6

**Comment by tibbi** [comment]
havent you added the folder or a parent folder in the included folders?

**Comment by KazKaz90** [comment]
Oh I see, that's really confusing but thanks

**Comment by saefthe** [comment]
Hello, I have read the message
Can you restore the audio files, please?
I hope so as soon as possible

Thank you all. Greetings

Saef

في الثلاثاء، ١٦ آب ٢٠٢٢, ٣:٤٤ م KazKaz90 ***@***.***> كتب:
