### ISSUE TITLE
Non-hidden folders hide!

### ISSUE THREAD

**Issue by NitroNils** [SimpleMobileTools/Simple-Gallery#259]
I recently started hiding and excluding directories and now only a couple if folders visible upon opening the program. Tried to hide/unhide, exclude/include and pin my main directory, but have to manually make hidden visible everytime!

PHONE_MODEL=ALE-L21
CUSTOM_DATA=
BRAND=Huawei
ANDROID_VERSION=6.0
APP_VERSION_NAME=2.9.1

**Comment by tibbi** [comment]
Hey, hiding and excluding works recursively, so even the subfolders are hidden/excluded. Maybe theres some .nomedia file hidden at some root folder?

**Comment by NitroNils** [comment]
Well, I found 15! What are those?
Removed them and your app immediately recovered! Thanks alot!

**Comment by tibbi** [comment]
.nomedia is the standard way of hiding folders containing media from some apps like galleries. Its used for example at some folders containing song album covers, so they dont show up in galleries.
