### ISSUE TITLE
Favorite Videos redirect to folder where video originated from

### ISSUE THREAD

**Issue by AdozenBABYdogs** [SimpleMobileTools/Simple-Gallery#2591]
Happens after about 2-5 seconds in the  video. It seems to index at the same number in favorites in the origin folder (i.e., if the video is inldex 4 in the favorites, it will pull up index 4 in the folder the video is stored in)

Steps to reproduce

Add videos and pictures to a folder
Favorite a video (preferably in the middle of the folder)
Watch the video

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by AdozenBABYdogs** [comment]
v 6.6.3
Carbon-CR-8.0-PAX-UNOFFICIAL-surya-20210701-1903

**Comment by tibbi** [comment]
that is an ancient app version, get the latest one from https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro

**Comment by AdozenBABYdogs** [comment]
Is it no longer on FDroid?

**Comment by tibbi** [comment]
it is

**Comment by AdozenBABYdogs** [comment]
Different problem populates where I cannot update the application, I'm not sure if I should generate a new ticket, or continue to use this bug report.  Does not work on either google play or FDroid and my suspicion is that because this application is packaged with CARBON OS, it cannot be removed without using root to wipe it from the device.  

I'll see if I can do that, but I am still researching how to do that

**Comment by tibbi** [comment]
ROM issues arent problems on our side
