### ISSUE TITLE
Changing sort causes lengthy refresh when managing a large library

### ISSUE THREAD

**Issue by kisaragi-hiu** [SimpleMobileTools/Simple-Gallery#2594]
With a large media library (probably 100s of folders, multiple years worth of photos, at least 10000s of images), changing sort settings in the initial folders view becomes really sluggish.

(The behavior seems to be present regardless of library size, it's just most noticeable when the screen refresh triggered by (I think) [`getDirectories`](https://github.com/SimpleMobileTools/Simple-Gallery/blob/4ed9b0be5cd2abba3388b27d06ea406b62d04d43/app/src/main/kotlin/com/simplemobiletools/gallery/pro/activities/MainActivity.kt#L511) takes more than a few seconds.)

It should be possible to reproduce this by creating copies of a 1MiB jpeg in like 250 folders, each containing like 500 copies. This corresponds to about 25 events per year for 10 years (about 100~200 GiB) and is not an unreasonable amount of data.

**Comment by tibbi** [comment]
some performance improvements have already been reported, so Ill close this
