### ISSUE TITLE
"No valid app found" while trying to edit a video.

### ISSUE THREAD

**Issue by LendirHijau** [SimpleMobileTools/Simple-Gallery#2597]
im using simple gallery foss on android 12, and after the update i can't edit videos. there is bar saying "No valid app found" when pressing the edit button (the pencil symbol). but i have no problem editing photos.

![Screenshot_2022-08-24-15-23-38-26_29b563cd0bc4fd07bd0c105b17b28204](https://user-images.githubusercontent.com/94510517/186369129-6677ce01-016f-476f-b453-cd238d1334fd.jpg)

and yes, reinstalling does nothing.
downloading the google play store version on the other hands, fixed it. but i dont want to use the gplay store version.

**Comment by tibbi** [comment]
the foss app variant doesnt contain the video editor as it is not open source. Only the proprietary variant from Github or Google Play contains it.

**Comment by LendirHijau** [comment]
> the foss app variant doesnt contain the video editor as it is not open source.

then can i request something? a proprietary version with access permission to all files, not just media.

**Comment by tibbi** [comment]
that doesnt exist yet, might be added someday

**Comment by LendirHijau** [comment]
then i will wait it out with great patience. this app is really good man.

**Comment by e-t-l** [comment]
> the foss app variant doesnt contain the video editor as it is not open source. Only the proprietary variant from Github or Google Play contains it.

@tibbi I had the same issue so I just uninstalled the fdroid version and downloaded the latest github release instead. I still get "no valid app found" when attempting to edit video. Do you know what's going on?

**Comment by Aga-C** [comment]
@e-t-l The latest version doesn't have the proprietary release. Here is the latest proprietary release: https://github.com/SimpleMobileTools/Simple-Gallery/releases/download/6.25.4/gallery-379-proprietary-release.apk.

**Comment by e-t-l** [comment]
> @e-t-l The latest version doesn't have the proprietary release. Here is the latest proprietary release: https://github.com/SimpleMobileTools/Simple-Gallery/releases/download/6.25.4/gallery-379-proprietary-release.apk.

Thank you, that solved it. Why in the world was the editor removed in just this latest release?

**Comment by tibbi** [comment]
My bad, forgot adding it. I edited the release and added it too.

**Comment by e-t-l** [comment]
Thanks! Is that just on github? Or if I update Simple Gallery from Play store/Aurora store, will it have the editor?

**Comment by tibbi** [comment]
yes, the Google Play Pro version is the exact same as the proprietary one on github

**Comment by BlackSandPearl** [comment]
Curious to know how to go about resolving this issue without causing a train wreck in the current fully updated app I am using. My app is loaded with pictures, videos, and numerous file folders. I have seen some people post that they caused themselves a lot of headache by not knowing the proper step by step protocol beforehand. Any thoughts?

PS: I just bought you a coffee

**Comment by saefthe** [comment]
مرحبا
كيف حالكم

Saef

في الاثنين، ٥ كانون الأول ٢٠٢٢, ١٢:٢٦ ص e-t-l ***@***.***>
كتب:
