### ISSUE TITLE
 Please add Network Drive (NAS or SMB) support.

### ISSUE THREAD

**Issue by arkar787** [SimpleMobileTools/Simple-Gallery#2598]
The simple gallery is a too-good product that tick marks all the requirements except NAS or SMB which most peoples need today, but sadly Simple Mobile Tools team is not wanted to add this option. I want to clarify that we not requesting in-app Internet access,  just want local Network access. 
Even if developers want they can add this feature as an extra paid Add-on for simple gallery pro so those people who do not want this can use a normal simple gallery or pro version.

**Comment by tibbi** [comment]
I dont plan adding local networks either, they also require similar permissions than internet.

**Comment by kha84** [comment]
> I dont plan adding local networks either, they also require similar permissions than internet.

So what? Are you afraid to scare users to death that their shots will float to internet?

You could request this priv as soon as user first attempts to use that proposed feature, it doesn't need to be requested by default.

**Comment by tibbi** [comment]
internet is granted by default, users dont have to allow it explicitly
