### ISSUE TITLE
View reset to first picture after rotating screen at 480dp

### ISSUE THREAD

**Issue by Eskamhl** [SimpleMobileTools/Simple-Gallery#2601]
Steps to reproduce the issue:

1. Set display size to 480dp on phone settings.
2. Open a picture
3. Swipe to a different picture (e.g. the next one)
4. Rotate the screen in landscape (or portrait if it was already landscape)

After rotating the screen, simple gallery will show back the first open picture from the album.

If the display density is changed no issue occurs.

I experienced this on a OnePlus Nord A12.1 (LOS 19.1) , app version 6.25.0 (both from play store and f-droid).
On a Samsung A50 A11 (stock) I wasn't able to reproduce the issue.

**Comment by tibbi** [comment]
is it really related to the display size?

**Comment by Eskamhl** [comment]
> is it really related to the display size?

Seems like the case, I don't know if it's directly related or not but for sure when I set a different dp the issue is gone.
@480dp issue
@470dp no issue
@520dp no issue

**Comment by Naveen3Singh** [comment]
I couldn't reproduce this issue on my devices (one of them is running a custom ROM).

Are you on an unofficial lineage os build? Your model isn't there on the official list of lineage os supported devices. There's only one Oneplus Nord device there (N200).

Have you observed this behavior on your device when using other ROMs too?
