### ISSUE TITLE
[Feature Request] Need a dedicated page for indexing large libraries.

### ISSUE THREAD

**Issue by JoeBiller** [SimpleMobileTools/Simple-Gallery#2604]
I have a picture library consisting of over 12,000 pictures, arranged in sub-folders following the scheme "year/year-month/year-month-day". I understand this is a lot of data to go through, and while the app currently does a respectable job trying to index all of it, having to constantly swipe down from the top to refresh is less than ideal, especially since refreshing stops as soon as the app loses focus or the screen locks. Plus it's hard to check if everything has been indexed without manually checking if every single picture is there (granted that wouldn't be a problem if I didn't use sub-folders). It would be nice if there could be a page in the settings dedicated to just indexing media. A page that could have a progress bar or verbose output, and can be left running in the background. If such a page were to also display the total number of pictures currently indexed, I would be able to compare that to the number of pictures I know are in my library to confirm everything is there.

**Comment by JoeBiller** [comment]
After some consideration, I have decided to rearrange my picture library to use the sub-folder scheme of "year/year-month" instead, and I am happy to report that the indexing was much faster and more reliable. It only took a couple of refreshes to get what appears to be everything. I still think a dedicated indexing page could be beneficial, especially for people with even larger libraries than mine or for people with lots of sub-folders.

**Comment by tibbi** [comment]
that isnt really planned
