### ISSUE TITLE
Add functionality to crop videos in the video editor

### ISSUE THREAD

**Issue by adarsh1001** [SimpleMobileTools/Simple-Gallery#2608]
The app does allow changing the resolution of a video to some preset ones but an option to crop the video (just like we have for photos) would be useful. For example, I just took a screen recording and wanted to crop out the unwanted parts at the top and bottom but had to rely on a competition app for this.

UI-wise, this can be kept similar to photo cropping. A free-flowing adjustable rectangle appears on top of the video and whatever is inside the rectangle is the new video.

**Comment by tibbi** [comment]
the current video editor is developed by a third party group of devs, so Ill close this one here.
