### ISSUE TITLE
Open From File Manager Unable To Swipe

### ISSUE THREAD

**Issue by seniorm0ment** [SimpleMobileTools/Simple-Gallery#2609]
If you go to SimpleMobileTools File Manager, open a photo file, if it launches SimpleMobile Gallery.

You are unable to swipe left or right to view other photos in that current directory. 
It would be very nice to be able to swipe between them all.

OS: Android 13 GrapheneOS

App: Simple File Manager Pro (F-Droid) 6.14.0, Simple Gallery Pro (F-Droid) 6.25.0

**Comment by tibbi** [comment]
it should work just fine, maybe GrapheneOS is limiting it. Does it work well in any other file manager/gallery combination?

**Comment by seniorm0ment** [comment]
On you're partially right it does work as it should, however it seems like this is an issue with hidden folders specifically.

**Comment by tibbi** [comment]
the gallery cannot access hidden files anymore on Android 11+, thats why it shows the current one only
