### ISSUE TITLE
Videos shows as black and can't be opened

### ISSUE THREAD

**Issue by jerryn70** [SimpleMobileTools/Simple-Gallery#261]
Some videos shows as black color and that video can't be played. 
Normal phone gallery and other gallery apps shows this video. And the video i said is mp4 format that is supported by android.
![screenshot_20170520-164555](https://cloud.githubusercontent.com/assets/23030460/26275397/0ee50a04-3d7d-11e7-8f49-57e6d4550854.png)

●HOW TO REPRODUCE●

OPEN gallery folder with images and videos . 
Open a image 
Slide to other images 
After sliding if a video comes it shows at black. 

I have waited 5 to 10 mins but still its shows as black

**Comment by jerryn70** [comment]
Now i have found a temporary fix. 

Early my camera files list order was like this. :-

Image (1), image(2), image(3), video(1), video(2), image(4), video(3), image(5) etc etc

When I was on this order , when i open an image and swipe from image (1) to image(5) , the video(3) has no preview it looks like the above screenshot and I can't open it.


Now i changed order to this (i changed dates of some images using date changer app and created this order)

 Image (1), image(2), image(3), video(1), video(2), image(4), image (5), image(6), video(3), image(7) etc etc

Now the issue is gone. I think this issue is related to performance.

Sorry for my bad english.

My gallery contains personal files otherwise I will provide u a video showing this issue, sorry for that.

**Comment by jerryn70** [comment]
![screenshot_20170526-173045](https://cloud.githubusercontent.com/assets/23030460/26493840/70ff2704-4239-11e7-99ab-4a3bc4b8689e.png)

Some videos preview looks like cracked see screenshot. And when I press play button nothing happens.

**Comment by jerryn70** [comment]
To see the cracks you need to download this pic and view it with full brightness

**Comment by tibbi** [comment]
some issues related to this have been fixed already
