### ISSUE TITLE
Editor: add some mark tools to highlight elements

### ISSUE THREAD

**Issue by freMea** [SimpleMobileTools/Simple-Gallery#2612]
I often use these tools in the OnePlus gallery : arrow, rectangle. We could add ellipse too.

![Screenshot_20220916-211554_Gallery__01.png](https://user-images.githubusercontent.com/22337329/190715780-56ee6512-64a6-463e-befa-dc9901fe746c.png)
![Screenshot_20220916-211626_Gallery__01.png](https://user-images.githubusercontent.com/22337329/190715807-07080c0e-5643-4902-9d7f-d1a69723fe4a.png)

**Comment by tibbi** [comment]
the current editor is developed by a third party group of developers, not us, so we cannot add it directly. But it has been reported already.
