### ISSUE TITLE
Exclude filter broken in "All Folders" view in latest release

### ISSUE THREAD

**Issue by JVimes** [SimpleMobileTools/Simple-Gallery#262]
After yesterday's release, the All Folders view ignores my exclude filter. My filter is `/storage/emulated/0/Android/data`. I'm on a Nexus 5X (Android 7.1.2), Simple Gallery v2.10.4. I tried clearing the app's data.

**Comment by tibbi** [comment]
should be fixed in the next version

**Comment by NitroNils** [comment]
Excellent! Back to normal! My favorite gallery, thanks a million!

**Comment by JVimes** [comment]
I second that ☺️ Amazing that nobody else has an All Folders view. So glad it persists the view. Really appreciate it!
