### ISSUE TITLE
Deleting Latest Clicked photo from Camera folder

### ISSUE THREAD

**Issue by DesignRTL** [SimpleMobileTools/Simple-Gallery#2622]
After this version, The app is automatically deleting files from my storage (SD card).

Plz fix this, I lost many pics

**Comment by tibbi** [comment]
what do you mean? Tell exact steps for reproducing please

**Comment by DesignRTL** [comment]
Its not deleting now. Dont know how but earlier it was only deleted when I open Simple gallery app.

but Now its not doing it.
Thanks
