### ISSUE TITLE
Video partly off-screen in horizontal, RTL 

### ISSUE THREAD

**Issue by maemunman** [SimpleMobileTools/Simple-Gallery#2625]
My device uses a right-to-left language locale. When I play a video in horizontal orientation, the video is off-center and part of it is off-screen:

![Screenshot_۲۰۲۲۱۰۰۵-۰۴۴۸۳۶_Gallery](https://user-images.githubusercontent.com/32847759/194054221-399899d6-12a7-473b-82e4-1b00b4228344.jpg)

Whereas if I enable “Use app in english” in the settings, it looks fine.

<details><summary>Click to expand screenshot</summary>

![Screenshot_۲۰۲۲۱۰۰۵-۰۴۵۰۱۹_Gallery](https://user-images.githubusercontent.com/32847759/194054580-1c704706-ac18-4472-9104-857ad4cbbf86.jpg)

</details>

**Comment by tibbi** [comment]
what app version are you using?

**Comment by maemunman** [comment]
@tibbi Looks like *6.25.0 Pro*

**Comment by tibbi** [comment]
should be fixed in 6.25.2
