### ISSUE TITLE
Differences between Free and Pro version

### ISSUE THREAD

**Issue by coldner** [SimpleMobileTools/Simple-Gallery#2627]
What's the differences between github release ( https://github.com/SimpleMobileTools/Simple-Gallery/releases/tag/6.25.1 ), Google play paid version ( https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery.pro ) and Google play free version  ( https://play.google.com/store/apps/details?id=com.simplemobiletools.gallery ) ?
Why isn't there explicit information about differences?

**Comment by tibbi** [comment]
the f-droid version has All files access and thus it can work with hidden files too, but the Google Play one has a lot more advanced photo and a video editor. The free Google Play one is a very old one, theres a ton of differences.

**Comment by coldner** [comment]
How can I verify proprietary code of Google Play pro version?

**Comment by tibbi** [comment]
you cannot verify it

**Comment by coldner** [comment]
@tibbi ok, so:
- github release/fdroid version - up-to-date **100%** open source app
- Google play paid version - open source app but with some proprietary code
- Google play free version - poorly maintained old version of app

Is it true also for other apps from SimpleMobileTools?

**Comment by tibbi** [comment]
all other Pro apps are exactly the same on f-droid and Google Play, they differ only by some buttons in the About section.

**Comment by coldner** [comment]
@tibbi So why would someone want to buy other Pro apps (except Gallery ofc)? I can't understand this business model.
