### ISSUE TITLE
Two tabs(All images & Album) at main page

### ISSUE THREAD

**Issue by Pranab009** [SimpleMobileTools/Simple-Gallery#2638]
Two tabs (All photos & Album) at main page.
Please add this feature it is more handy.

See this images
![Screenshot_20221019-103325_1](https://user-images.githubusercontent.com/65340361/196602104-1dbb4df7-5dd4-4914-b5e7-d4696d3076f4.png)

**Comment by tibbi** [comment]
hi, it isnt on the roadmap like this, but it has already been reported so Ill close it
