### ISSUE TITLE
Make Moving files to hidden folder more simple

### ISSUE THREAD

**Issue by jerryn70** [SimpleMobileTools/Simple-Gallery#264]
Moving files to hidden folder is not that much simple. When we click to move items, there is no option to show hidden folders. In quick pic gallery we can enable show hidden folders from the 3 dot menu when moving.

According to the current version of simple gallery we need 'enable show hidden folder' from the settings then move file to it and again we need to go settings then hide it .  Or we should choose 'other folder' option and manually find the location of  the hidden folder and paste it. These 2 methods are not simple .  It will be great if you make an option "show hidden folder" when moving files. So that we can click show hidden folders and move items to it.

**Comment by jerryn70** [comment]
I think it's not working as you said .

1st opened gallery, then clicked "temporary show hidden files'. Now hidden folders are got visible . Then I selected the image i what to move and clicked 'move to'  
Now what happens ? The temporarily shown folders are got hidden so I can't continue.

**Comment by tibbi** [comment]
It still shows the hidden folders to me, i can check what could go wrong there. Anyway theres a "Temporarily show hidden" after you open a particular folder too, maybe that will help.

**Comment by jerryn70** [comment]
This method shows works
