### ISSUE TITLE
[Feature request] Add Brightness- Contrast adjustments

### ISSUE THREAD

**Issue by luke-2136** [SimpleMobileTools/Simple-Gallery#2643]
As it is now have to open another editor if need to adjust brightness or contrast of an image..

Would be great if it could be done with the Simple-Gallery editor - a 'simple' slider perhaps for brightness and contrast would be very useful at times  

(saturation, hue, etc. not an issue)

Thanks for Simple apps

**Comment by tibbi** [comment]
you can do that in the app editor already

**Comment by luke-2136** [comment]
..well ..you must be talking about filters because i definitely cannot find any other way to change the brightness/contrast (unless there is something i'm missing)

..filters are very limited and do not allow any control though.. 

Thanks anyway..

**Comment by tibbi** [comment]
guess you use the foss app variants basic editor then, those advanced settings are in the proprietary one

**Comment by luke-2136** [comment]
yes it's the one from F-Droid - 6.25.4 currently

that explains it though - okay thanks for clarifying
