### ISSUE TITLE
Hiding UI Using Fullscreen Transitions Slowly

### ISSUE THREAD

**Issue by 0pLuS0** [SimpleMobileTools/Simple-Gallery#2644]
Hello,

First let me say, thanks for all the great apps you make, I really love them and Simple Gallery is my favorite!

My Specs:
---------------
Version: 6.25.4 (F-Droid)
OnePlus 5T 
ROM: e-1.4-r-20220922220394-dev-dumpling
Android: 11
Rooted: Yes
GCam: NGCam_8.2.300-v1.8_snap by Nikita

I checked; ```Automatically hide system UI at fullscreen media``` but the UI still appears and takes 2 seconds for it to disappear.

Is there a way for you to make fullscreen mode, so the UI never appears, when tapping on an image, it just goes straight into fullscreen?

The biggest probem I have, is when using GCam, and I take a picture, and then I tap on the preview button, Simple Gallery opens, the image first appears in fullscreen, then the UI appears, then it goes back to fullscreen. It's really irritating as it's doing this, because it slows the process down, to like 3-4 seconds before it stops flashing around.

Please don't misunderstand, I don't mean Simply Gallery is irritating, the situation is rritating is all, Simple Gallery is great. For whatever reason, when using the GCam preview, Simply Gallery acts up like this.

I also don't like that the UI appears too before going into fullscreen mode.

I hope you can make this, so the UI doesn't appear at all when using fullscreen.

THANKS

**Comment by tibbi** [comment]
you cannot make it quicker, thats how it is done to avoid some glitches
