### ISSUE TITLE
Black background at fullscreen media crashes GCam Preview

### ISSUE THREAD

**Issue by 0pLuS0** [SimpleMobileTools/Simple-Gallery#2645]
SPECS
-----------
Version: 6.25.4 (F-Droid)
OnePlus 5T
ROM: e-1.4-r-20220922220394-dev-dumpling
Android: 11
Rooted: Yes
GCam: NGCam_8.2.300-v1.8_snap by Nikita

When I use in the settings; ```Black background at fullscreen media``` and take a picture, then tap on the preview button, Simple Gallery starts to appear with the image, then flashes off screen and closes and I'm back to the main UI of GCam.

But if I click on the preview button again, Simple Gallery opens and shows the image.

For whatever reason, every time I take a picture, then try the preview this happens, but I tap the preview again and Simple Gallery will now always open up and show the image.

Not sure why it crashes the first time.

Also another issue I noticed, now when I uncheck ```Black background at fullscreen media``` then take a picture, and tap on the preview, Simple Gallery opens up and shows the image first with a black background, then the default background color appears showing the UI, then the UI disappears and the image appears in full screen with the default background color. hmm

Here's my logcat

[logcat.txt](https://github.com/SimpleMobileTools/Simple-Gallery/files/9845565/logcat.txt)

THANKS

**Comment by tibbi** [comment]
are you sure it is related to that setting? I dont see anything crash related in those logs

**Comment by 0pLuS0** [comment]
Actually my mistake, I see now that sometimes with different GCam versions, the gallery might open and close when clicking the preview button too.

But, if I disable ```Black background at fullscreen media``` Simple Gallery still opens up and shows the image first with a black background, then it shows the default background.

For now I gave up on GCam, to many problems with /e/ R Android 11, so I'm sticking to Open Camera for now.

THANKS
