### ISSUE TITLE
Newly downloaded videos not showing in gallery

### ISSUE THREAD

**Issue by jerryn70** [SimpleMobileTools/Simple-Gallery#265]
Today I downloaded a video from internet. The file is avi format, and after downloading i checked gallery but the video is not there, i used swipe down refresh (i don't know whether it is a real refresh or just only an animation )  but it's not showing the video. 

I checked the video using quickpic gallery and it shows that file.

So for testing I downloaded a 3gp video, that video also not showing in the gallery.

Note : There is no problem for images.

**Comment by jerryn70** [comment]
I think this issue is related to media scanner . The complete test report is given below :-

1, I downloaded avi format video using futorrent app.  
Result = simple gallery didn't show that file . 
Quickpic gallery shows that. 

2, I download 3gp video using ogyoutube app.
Result = simple gallery didn't show that file.
Quickpic gallery shows that.

3, I downloaded 3gp video using ADM app.
Result = Simple gallery and Quickpic gallery shows file.

4 , I downloaded mp4 video using brave browser.
Result = Simple gallery and Quickpic gallery shows the file.

**Comment by tibbi** [comment]
ye thanks, it is related to the media scanner. Ive changed the app to use the media scanner for fetching media instead of browsing folders by files, as it was a lot faster in many ways. I might find some way of fine tuning it in the future.

**Comment by tibbi** [comment]
Ive added a rechecking of files every 3 seconds, that should improve the situation. Its a quick check for the file with highest modified timestamp, shouldnt cause any issues. The version will start rolling out in a couple minutes.

**Comment by jerryn70** [comment]
Give me some time i will test and tell you

**Comment by jerryn70** [comment]
I didn't get playstore update so I downloaded it from here and tried . I think the issue is solved.

**Comment by tibbi** [comment]
Im using staged rollout which means that only some percentage of people get the latest version. If nothing goes wrong Im increasing the percentage, so it can take some time till everyone gets the app. Its on 100% for a couple of hours already tho.

**Comment by jerryn70** [comment]
I have downloaded a video mp4 format using futorrent app https://play.google.com/store/apps/details?id=com.futorrent.torrent.client 
But the video is not showing in the gallery . I'm on the latest version of simple gallery.

**Comment by tibbi** [comment]
Media file rescaning has been improved a lot since then, this should be ok already.

**Comment by jerryn70** [comment]
@tibbi I have saved a pic using this app https://play.google.com/store/apps/details?id=droidtuts4you.com.shoton but the saved image is not showing in gallery . Iam using the latest version.

**Comment by tibbi** [comment]
does the pic show in other galleries? Maybe they arent adding the item in the mediastore properly, the app has pretty bad rating and reviews. To make Simple Gallery rescan folders file by file and not rely on the mediastore, the folder has to be explicitly included at Settings -> Manage Included Folders.

**Comment by jerryn70** [comment]
Yes working fine with quikpic and mixplorer

**Comment by tibbi** [comment]
ok then ill try the app someday

**Comment by tibbi** [comment]
shoud work in 3.7.0

**Comment by ghomem** [comment]
Thanks for developing Simple Gallery. It is a great tool.

Just a note: 

Auto rescan does not work on 3.6.3 (the latest version I am able to see on Google Play) by default, but it does work if you include one specific folder in the "Manage included folders" list. I used the folder Downloads, which then I use for downloads and uploads.

I think this behaviour is totally fine, the only problem is that it was not at all trivial do understand how to get this working.

Perhaps "Manage included folders" could be called "Automatically scanned folders" to make it easier for users to understand?

**Comment by tibbi** [comment]
I dont really plan renaming it, we will see in the future. Thanks
