### ISSUE TITLE
'Sort by' uses wrong entry in file for 'Date taken'

### ISSUE THREAD

**Issue by ZarVladimirII** [SimpleMobileTools/Simple-Gallery#2653]
Gallery 6.25.4 Pro

I did re-organise pictures and sorted them.

Now moved files who should be at the end of the list by 'Date taken' are at the beginning as "newest" because the creation/modified date changed through 'move files'.

Pictures data:
4640 x 3472 (16.1MP)
29.10.2022, 14:16          <-- modified?
12.10.2020, 16:59          <-- Date taken
F/1.8 ...

Changing to 'last modified' does move some files with the same time entry by minute, then identical time alphabetically.

https://github.com/SimpleMobileTools/Simple-Gallery/issues/2573#issuecomment-1198971255 is not obvious and that it exists. Especially given that the properties give the expected information. This is not a solution, only a workaround hotfix for now.

**Comment by tibbi** [comment]
Are you moving with Simple Gallery? If you are, ry granting the app All files permission, then it should be able to set the dates after move correctly.

**Comment by ZarVladimirII** [comment]
No with the PC - Windows-Explorer

**Comment by tibbi** [comment]
that isnt an issue on our side then, the dates arent properly updated in the system mediastore

**Comment by ZarVladimirII** [comment]
But working with it to keep simplicity?
'Google Photos' doesn´t care about it and does not show the same behaviour. They implemented a workaround 🤔
[I keep it installed for reference ;) ]

On my side it´s a wrong read out of the EXIF data 'Date taken'. Information that has not changed at all. And 'SimpleGallery' showes me the correct date on all places where 'date taken' is displayed.
## As a dumb and simple user (At least as long the displayed date is correct) I don´t care if it is a different systems error or something, then I don´t understand and don´t want to now. I only now it is displayed wrong and it shouldn´t.

Where or what is the 'system mediastore'? An Android database, thus the information is not read from the file itself?
Does a reboot change anything?
Thanks!

**Comment by tibbi** [comment]
it is an internal database, checking file by file would be really slow
