### ISSUE TITLE
Suggestion: keep the custom image size scale.

### ISSUE THREAD

**Issue by huamumian** [SimpleMobileTools/Simple-Gallery#2657]
Is it possible to keep the ratio of my own custom image size in Editor in the new version. I really need this feature, thank you very much!
![Edit-CUT1](https://user-images.githubusercontent.com/41187381/199387137-1d36a35c-9f8c-473d-89b7-e5ad0e26b556.png)
![Edit-CUT2](https://user-images.githubusercontent.com/41187381/199387200-abd11f2d-224d-45c3-8ca7-0b12ac788ce7.png)

**Comment by tibbi** [comment]
you mean in the Pro apps editor or where?

**Comment by huamumian** [comment]
Sorry, I made a mistake. The latest version of Foss has this function. The Pro version I downloaded last time did not have this function.
