### ISSUE TITLE
"Show the Recycle Bin"

### ISSUE THREAD

**Issue by kyoyacchi** [SimpleMobileTools/Simple-Gallery#2659]
Can you add 
![Screenshot_20221102-190453](https://user-images.githubusercontent.com/63583961/199540856-a92a87ae-9ae4-40a6-9e49-1a55bbdd147c.jpg) when opening gallery from any app(like selecting avatar for discord from gallery)
There are currently these, but sometimes i want to choose from recyle bin. I know i can enable it by opening main gallery app.

![Screenshot_20221102-190544](https://user-images.githubusercontent.com/63583961/199541117-daf432b9-0c7d-4b62-b1fb-8a8000e24ce4.jpg)

**Comment by tibbi** [comment]
isnt the main screen of the gallery shown as you open it? There you can select Recycle bin

**Comment by kyoyacchi** [comment]
> isnt the main screen of the gallery shown as you open it? There you can select Recycle bin

No, i mean opening gallery app from any app. I can't see that option when i do that. 

For example: Go to Discord > Settings > User Profile > Change Avatar > Gallery 
![Screenshot_20221106-001434](https://user-images.githubusercontent.com/63583961/200141630-eb265152-889e-442d-85c4-ba3a07073b7c.jpg)
"Şuradan aç"("*open from*")

**Comment by nbmrjuhneibkr** [comment]
I have updated from 6.25.5 to 6.26.1 FOSS, and the option to quickly show/hide the Recycle Bin doesn't seem to exist anymore.
Now I have to open settings every time I want to do this, which is inconvenient.
I don't see any mention of this change in release notes.

**Comment by kyoyacchi** [comment]
> I have updated from 6.25.5 to 6.26.1 FOSS, and the option to quickly show/hide the Recycle Bin doesn't seem to exist anymore. Now I have to open settings every time I want to do this, which is inconvenient. I don't see any mention of this change in release notes.

Yeah, i talked about it in https://github.com/SimpleMobileTools/Simple-Gallery/issues/2719 it seems he doesn't want to add it back

**Comment by tibbi** [comment]
you can toggle it in the app settings indeed

**Comment by kyoyacchi** [comment]
@tibbi why did you close this issue?

**Comment by tibbi** [comment]
because it can be toggled in the app settings, I dont plan adding the menu item

**Comment by nbmrjuhneibkr** [comment]
> I dont plan adding the menu item
It's not about "adding" something. It's about not removing features that were already implemented in previous versions.

**Comment by nbmrjuhneibkr** [comment]
Quite a few people may not want to see the Recycle bin in the list all the time, but still want to have a quick and easy way to access it whenever they want to empty it, or to restore something.

I would argue that it's more useful than "Temporarily show hidden files" (which are usually hidden for a reason). But don't take this as a call to remove yet another menu item, please.

**Comment by nbmrjuhneibkr** [comment]
If keeping the menu as short as possible is the top priority (for some reason...) than both the Recycle bin and hidden files could be added as filters, at least. It wouldn't be optimal, but it's better than keeping the option buried in the settings menu.

**Comment by nbmrjuhneibkr** [comment]
Thanks. This is a pretty great solution. It's even more convenient than previous implementation, probably. This way you can always be certain that Recycle bin will stay hidden after you clean it.

**Comment by tibbi** [comment]
Well, this new button is usable with "Show all folders content" too, which wasnt the case previously. I have to keep an eye on optimizing such things to avoid too many menu buttons, else the app would become too flooded and wouldnt be simple anymore.
