### ISSUE TITLE
[Feature Request] WebP

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimpleMobileTools/Simple-Gallery#266]
WebP is an image format employing both lossy and lossless compression. It is currently developed by Google, based on technology acquired with the purchase of On2 Technologies.

**Comment by tibbi** [comment]
whats with it?

**Comment by KrasnayaPloshchad** [comment]
Resource for support this format is available here: https://developers.google.com/speed/webp

**Comment by tibbi** [comment]
webp displays fine to me. You dont see it, or whats the issue here?
