### ISSUE TITLE
Additional attention to the Video Editor

### ISSUE THREAD

**Issue by SecularSteve** [SimpleMobileTools/Simple-Gallery#2660]
This is more of a personal suggestion than anything, but it's mostly because I couldn't help but notice the complete lack of any proper Android Video Editing Tools.

I'm not looking to turn this into an iMovie Clone, just to give a little more thought to one of the most overlooked, and unclean ecosystems in the world of Android Apps.

I have yet to find a proper Android Video Editor that isn't some type of proprietary spyware, abandonware, or thoroughly lacking in features without a pre-paid subscription plan/registration (not that this one does mind you, it's good for what you can get for a small fee).

In the end, it's your software. I'm not trying to force anything.

**Comment by tibbi** [comment]
the video editor we use is also proprietary one, not developed by us

**Comment by SecularSteve** [comment]
Alright then...
Good to know. No worries.
Like I said, it's good for what it already can do, but it could possibly do more.
It's kind of an untapped economy where this app could thrive if a bit more thought was given to it.
If you could somehow pass this on to the real developers (or point me to where I can do it myself), that would be nice.

With kind regards, succes, good luck 🍀, have a nice evening, and great software above all else 👍
