### ISSUE TITLE
Enable "Show images in the highest quality" by default

### ISSUE THREAD

**Issue by mesonium** [SimpleMobileTools/Simple-Gallery#2661]
The "Show images in the highest quality" setting has been introduced in 6.5.3 and it's disabled by default.
Unfortunately this makes images look really bad (c.f. https://github.com/SimpleMobileTools/Simple-Gallery/issues/).

I think now in the end of 2022 devices should be fast enough so that it's save to enable it.

If you disagree, a hint respectively a manual setup screen when first opening the app would help a lot to discover the setting and to understand why images look worse than in the stock gallery app.

---

Android 13, Simple Gallery 6.25.4 (F-Droid)

**Comment by horazont** [comment]
Seconded, I thought my phones camera was really really bad for half a year or so until I actually looked at the pictures more closely on another device.

**Comment by tibbi** [comment]
it lags on many devices so I dont want to enable it. The default is just fine
