### ISSUE TITLE
Option to delete RAW file alongside with JPEG

### ISSUE THREAD

**Issue by mesonium** [SimpleMobileTools/Simple-Gallery#2662]
On my Android phone the camera takes both JPEG and RAW files. However, when deleting a JPEG the corresponding RAW file in the `RAW` folder is kept, which leads to additional work to look for unwanted RAW pictures.

It'd be useful if Simple Gallery checked the RAW folder for files with the same name and asked if those should be deleted / moved to the trash as well. 

---

Android 13, Simple Gallery 6.25.4 (F-Droid)

**Comment by tibbi** [comment]
I dont really like adding such automatic things
