### ISSUE TITLE
Timestamp of image is lost when image is edited

### ISSUE THREAD

**Issue by foss-** [SimpleMobileTools/Simple-Gallery#2666]
Reproduce

- edit an image e.g. draw a line with pen
- save image

Currently: Image has new timestamp, which is point in time, when image was saved

Expected: keep timestamp of when the image was actually taken

The rational behind that is: just because an image is edited, that does not change the timestamp when the image was taken. I don't understand why that would be altered. Is there a setting to prevent this form happening?

**Comment by tibbi** [comment]
what app and OS version are you using? Have you granted the app All Files access or Media only?

**Comment by foss-** [comment]
LineageOS 19.1 2022-11-07
Simple-Gallery 6.25.4 Pro
Permissions: Files and media (All Files)

**Comment by Aga-C** [comment]
I don't have this issue on my Android 12 (non-rooted), 6.25.4 Pro (proprietary release), with All Files access and `Keep old last-modified value at file operations` option selected.

**Comment by foss-** [comment]
`Keep old last-modified value at file operations` is enabled here as well.

**Comment by foss-** [comment]
This could be a dupe of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2582
