### ISSUE TITLE
How come the F-Droid doesn't have the newest version?

### ISSUE THREAD

**Issue by e3b** [SimpleMobileTools/Simple-Gallery#267]
F-Droid has 2.10.4, Google Play Store 2.10.6. How come? I don't want to be rude; I'm just curious.

**Comment by tibbi** [comment]
2.10.6 has been released just 3 days ago, it can take a couple days till F-droid updates it. Theres nothing I can do about it, they have automated scripts for it. Anyway F-droid already has 2.10.6 so Im closing it.
