### ISSUE TITLE
Editor - Line drawing offset from original touch point

### ISSUE THREAD

**Issue by xxz3** [SimpleMobileTools/Simple-Gallery#2674]
**Platform**
Phone: Pixel 7
Android: 13 (TD1A.221105.001)
Simple-Gallery: 6.25.5

**Issue**
When drawing on images, the lines are shifted down from where I'm touching. The offset seems equal to status bar + app's navbar size.

https://user-images.githubusercontent.com/16058143/203745714-3f166e00-1ce8-4554-a32e-e78a28f7d160.mp4

**Comment by aaronwi** [comment]
I can confirm this is also an issue on the pixel 4a 5g with calyxos, Android 13

**Comment by mohzart** [comment]
same here, on Redmi Note 7, lineage os, microG, A11
