### ISSUE TITLE
Duplicate images in Play Store description

### ISSUE THREAD

**Issue by RafeeDaBoy** [SimpleMobileTools/Simple-Gallery#2675]
In the Play Store app description, there are duplicates of some images.
![Screenshot_2022-11-24-21-56-34-11_50ecd26a21c2c56ce608de5e94733463](https://user-images.githubusercontent.com/69535896/203826154-f2ac60a7-aa86-49dc-b80f-f333c01fe0d3.jpg)

**Comment by tibbi** [comment]
thats because they display the tablet ones too on a pc
