### ISSUE TITLE
transparent background arround the pill ?

### ISSUE THREAD

**Issue by o13e** [SimpleMobileTools/Simple-Gallery#2677]
hello, if isn't too much asking it would look better if the background around the pill would be transparent in folder view like it is in image or video mode. Thanks

![Screenshot_20221125-130500](https://user-images.githubusercontent.com/109251285/203983547-459345e7-d413-4d27-a447-a8f1559f878a.png) 
![Screenshot_20221125-131659](https://user-images.githubusercontent.com/109251285/203984446-7f602a2e-50dc-4c42-a229-556e06ef132c.png)

**Comment by J4CKED** [comment]
As far as I know, this pill belongs to the Android system, I disabled it.

**Comment by tibbi** [comment]
having 1 small transparent line there would be weird, dont really expect having it for now

**Comment by OkyDooky** [comment]
@o13e If you can add the feature, maybe you could open a PR for it? Maybe it could be added as a toggleable setting, if it causes oddities by default?
I'm just thinking if you could compile a version with it, yourself, maybe it might be worth it to put in the extra effort to add it back in as a feature upstream.
