### ISSUE TITLE
Sound autoplays when viewing videos

### ISSUE THREAD

**Issue by wktra** [SimpleMobileTools/Simple-Gallery#2678]
Fix this please. Hate to have to lower my volume all the way before scrolling through questionable vids

**Comment by tibbi** [comment]
guess you enabled autoplaying videos? Just disable it back in the app settings

**Comment by wktra** [comment]
@tibbi When previewing videos through swiping, users don't want to be blasted in the face with sound unless they either unmute or click the video.

**Comment by tibbi** [comment]
sure, thats what the setting is there for
