### ISSUE TITLE
Feature request: Show AV1-video thumbnails

### ISSUE THREAD

**Issue by hubertmeier** [SimpleMobileTools/Simple-Gallery#2681]
while AV1 videos are not supported by the player, i can use vlc for playing videos. A thumbnails of the video would be nice ...

Thank you

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2496.

**Comment by tibbi** [comment]
duplicate of #2496
