### ISSUE TITLE
Toast app icon doesn't change

### ISSUE THREAD

**Issue by julianfairfax** [SimpleMobileTools/Simple-Gallery#2686]
When you change the app icon colour, toast notifications, such as those for deleting or moving files, still have the original icon. This makes the user experience somewhat inconsistent. Is it in any way possible to "fix" or change? Or is that not possible on Android apps?

**Comment by tibbi** [comment]
Hard to say, that might not be customizable on our side. What app and OS version are you using?

**Comment by tibbi** [comment]
thats not how it is supposed to work...

**Comment by tibbi** [comment]
Well, it differs from every other app and it isnt what the user expects to see. WIth that attitude every app would look and behave differently.
