### ISSUE TITLE
Edit with pen on tablet 

### ISSUE THREAD

**Issue by XCD2018** [SimpleMobileTools/Simple-Gallery#2695]
I recently installed the app on my tablet but i can't use the pen to make some editing on the pictures.
the pen is not recognised by the gallery

**Comment by jonfre** [comment]
I have maybe related issue; pen is drawing with an offset (arround 40%) to the lower right. 

Android 13
V 6.25.5

**Comment by tibbi** [comment]
that has been fixed already, it just needs an app update

**Comment by rimatech987** [comment]
> that has been fixed already, it just needs an app update

@tibbi , where? Do you mean in the next version? Because in the latest version (6.25.5 Pro) there is still the bug (there is an offset when drawing a line).

**Comment by tibbi** [comment]
it will be fixed in 6.26.0, but it hasnt been released yet
