### ISSUE TITLE
pen is inaccurate.

### ISSUE THREAD

**Issue by Corylus-Core** [SimpleMobileTools/Simple-Gallery#2697]
I'm having the problem that when i'm editing something the pen tool is completely inaccurate. Strange behaviour...

**Comment by tibbi** [comment]
it has been fixed already, just needs an app update

**Comment by tibbi** [comment]
yeah, will be fixed in 6.26.0

**Comment by kyoyacchi** [comment]
> yeah, will be fixed in 6.26.0

When will you publish it?

**Comment by tibbi** [comment]
in 1-2 weeks
