### ISSUE TITLE
Exclude folder

### ISSUE THREAD

**Issue by DerLude** [SimpleMobileTools/Simple-Gallery#27]
Hey!
I love your app because it is so simple and can play videos out of the box. There is only one feature I am missing. I would like to exclude specific folders from being scanned.
In my case I have many albums of music on my phone, each with a cover as image in the respective directory. In consequence, there are many many folders to scroll through which I don't want to see in my gallery.
Do you think it is possible to add such an option in settings?

**Comment by tibbi** [comment]
will be added in 1.24
