### ISSUE TITLE
Fotos are not sorted by creation date (Reopened #1022)

### ISSUE THREAD

**Issue by pcre73** [SimpleMobileTools/Simple-Gallery#2701]
Hi,

I installed a couple of days ago  6.25.5 Pro on an Android 12 (Doogee S98Pro up to date). When I try to group by "Creation date" (German: "Aufnahmedatum"), daily or monthly doesn't matter, It only groups by the date I copied it on the phone. Particularly the MOV video files are grouped correctly, just the JPGs are sorted by modification date. 

--
Greetings
Peter

**Comment by tibbi** [comment]
Select the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.
