### ISSUE TITLE
Bug: Excluded Folders are not recursive 

### ISSUE THREAD

**Issue by Saijin-Naib** [SimpleMobileTools/Simple-Gallery#2703]
Excluding a folder does not exclude images in any sub-folders, limiting the usefulness of this great feature.

**Comment by Saijin-Naib** [comment]
Does not here under Android 10, permission to access all files, and Excluded directories on microSDXC volume.
 v6.25.5pro, as well.

**Comment by tibbi** [comment]
dont you have them included too?

**Comment by Saijin-Naib** [comment]
> dont you have them included too?

Yes, and they are not recursive excluding child directories.

**Comment by tibbi** [comment]
well, if they are both included and excluded, they will show

**Comment by Saijin-Naib** [comment]
> well, if they are both included and excluded, they will show

They are not explicitly included. They are explicitly Excluded and still show.

**Comment by tibbi** [comment]
havent you had some folders included previously?

**Comment by Saijin-Naib** [comment]
No, and it didn't resolve after resetting the app storage and cache, either.

Is there an issue with the path, somehow?

**Comment by tibbi** [comment]
it doesnt work at all, or just on SD cards or so?

**Comment by Saijin-Naib** [comment]
Has always worked properly on internal storage, first time I've had external storage for my android.

Could the filesystem be corrupted somehow?

Does this work for other folks?

**Comment by tibbi** [comment]
yeah, it works just fine to others
