### ISSUE TITLE
Can't see the Recycle Bin 

### ISSUE THREAD

**Issue by kyoyacchi** [SimpleMobileTools/Simple-Gallery#2719]
After the latest update  "show the recycle bin" option is gone from dropdown menu in gallery app.
I can only see the recycle bin by enabling this.
![Screenshot_20230112-014440](https://user-images.githubusercontent.com/63583961/211934093-f3ed784b-aa9f-48f7-a1f3-ca787c55f5bc.jpg)

It was pretty useful please bring it back to dropdown menu.
![Screenshot_20230112-014453](https://user-images.githubusercontent.com/63583961/211934220-8856a882-990b-4e8e-85d5-7a6acb5226e4.jpg)

**Comment by tibbi** [comment]
it shows up only if not empty

**Comment by kyoyacchi** [comment]
> it shows up only if not empty

It's not empty. You can see in ss that it takes up 800MB~ space

**Comment by tibbi** [comment]
right, it will be shown as a casual folder then.

**Comment by kyoyacchi** [comment]
> right, it will be shown as a casual folder then.

Can't you just add it back please?

**Comment by tibbi** [comment]
I dont want to add that button back, theres already too many menu buttons

**Comment by kyoyacchi** [comment]
Ok

**Comment by collapsoid** [comment]
Second this.
Can you please reconsider your decision? This feature is useful enough (and I personally relied on it in some cases) to simply remove it from the list. Maybe you need a different approach for displaying folder actions if you don't want to pollute one menu list?

**Comment by nbmrjuhneibkr** [comment]
> theres already too many menu buttons

I have never used more than half of them, but I've been using "Show/hide the Recycle Bin" regularly - until it was removed without prior notice.

**Comment by kyoyacchi** [comment]
@tibbi at least, can you add an option or something like that for it? It was really useful.

**Comment by tibbi** [comment]
a button "Open Recycle Bin" has been added if you have the recycle bin enabled, but showing as folder is disabled
