### ISSUE TITLE
Doubt with the application 

### ISSUE THREAD

**Issue by gallegonovato** [SimpleMobileTools/Simple-Gallery#2725]
Good afternoon @tibbi 

First of all thank you very much for all your work and effort. And for your wonderful contributions.

Comment that I have a terminal with Lineageos and without anything from Google and without gaps.

I use your fdroid and github contributions.

I do not know with this I will continue to have the free version or the pro version.

Or if there is a way to make a payment or something to have the pro without going through Google?.

Best regards

**Comment by tibbi** [comment]
Hey, there are multiple ways of donating at https://www.simplemobiletools.com/donate , you can pick whatever suits you. Thanks

**Comment by gallegonovato** [comment]
Good afternoon:

Years ago when I was using Google stuff I bought the pro versions.

I didn't know about paypal. I'm going for it :)

And while I'm at it I'll take a look at your new terminal.

Best regards
