### ISSUE TITLE
Update the screenshots of the app

### ISSUE THREAD

**Issue by jcperil** [SimpleMobileTools/Simple-Gallery#2727]
Recently, simple apps went through significant UI changes and the older screenshots in google play or fdroid do not reflect that. I think it is only fair that the users know about the interface before installing.

**Comment by tibbi** [comment]
most apps have to get new images, but the changes arent done yet

**Comment by jcperil** [comment]
Are you saying they will be updated soon? Sorry, I did not understand.

**Comment by tibbi** [comment]
sure, they will be, once the design itself is final
