### ISSUE TITLE
Picture shared to Threema is treated as a video and cannot be viewed 

### ISSUE THREAD

**Issue by johnnydvc** [SimpleMobileTools/Simple-Gallery#273]
Same as title

**Comment by tibbi** [comment]
Hey, I cannot reproduce it. From which screen do you share the image? What is the image extension? Its only 1 image, not multiple at once right?

**Comment by johnnydvc** [comment]
Still reproduceable in my case. I'm inside the gallery and select a picture that was taken by the camera. Then I select share and pick Threema. There I choose the contact. The contact gets the picture with a play button on it. Trying to play it will crash the Google Video Player. But when opened with Gallery I get the picture with a frozen progress bar indicating a video file.

**Comment by johnnydvc** [comment]
The image extension is jpg or png. 
I attached some screenshots showing the bug.

**Comment by bbukowski** [comment]
Same here, running LineageOS 14.1. For some reason, Gallery detects the mine type of every image which gets shared as video/ffmpeg.

**Comment by tibbi** [comment]
recheck with 2.10.9 once its available please, Ive tweaked it

**Comment by bbukowski** [comment]
Already built it from source. But I waited for the new version to arrive to give you feedback. Working perfectly now. Thanks!
