### ISSUE TITLE
Mosaic layout

### ISSUE THREAD

**Issue by Donkey-Doug** [SimpleMobileTools/Simple-Gallery#2731]
Consider adding a mossic layout:

![Screenshot_20230116-003229_Trebuchet](https://user-images.githubusercontent.com/50382414/212573563-1f4326f2-9134-433d-acfd-4516a4db242b.png)

![Screenshot_20230116-003308_Trebuchet](https://user-images.githubusercontent.com/50382414/212573570-78512ee3-59c8-4366-900e-004d4bf3f342.png)

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/1567.

**Comment by jcperil** [comment]
The padding between the thumbnails are so slick. What is this application?

**Comment by Donkey-Doug** [comment]
> The padding between the thumbnails is so slick. What is this application?

Aves Gallery
