### ISSUE TITLE
UI Bugs with Hide Cutout developer option enabled

### ISSUE THREAD

**Issue by pudup** [SimpleMobileTools/Simple-Gallery#2732]
This affects all the Simple apps that have had the new UI design added to them.
It is only present when the "Hide Cutout" feature is enabled in Developer Options to shift the screen down below the camera in the screen. Other apps do not get affected by that setting.

![Screenshot_20230116-143338_1](https://user-images.githubusercontent.com/35901162/212639855-e0ea189c-91a2-4a2d-8b39-a5a6366baeb8.png)

![Screenshot_20230116-143322_1](https://user-images.githubusercontent.com/35901162/212639913-e2c338b1-a625-4743-a8ea-ecee4f833f07.png)

**Comment by earthly-alien** [comment]
This is not only the case with Hide cutout enabled. I've got the same issue with default device setting (Corner cutout). Downgraded to 6.25.5 where all works fine.
![Screenshot_20230117-114535](https://user-images.githubusercontent.com/89748257/212880001-b07d9013-0890-4d5d-8842-6d0c74ca50a2.png)

**Comment by pudup** [comment]
Seems related to UI size then

**Comment by tibbi** [comment]
Can you try this one? Unzip it first though. But Im mostly interested in the default behaviour, I dont care about some developer settings changes.

[gallery-382-proprietary-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/10434238/gallery-382-proprietary-release.apk.zip)

**Comment by earthly-alien** [comment]
Yes, this one displays fine for me.

**Comment by pudup** [comment]
It fixes it for me too. The dev option simply resizes the UI anyway.

**Comment by tibbi** [comment]
alright thanks, will be fixed in 6.26.2 released soon
