### ISSUE TITLE
Make Repeat/Loop mode more accessible

### ISSUE THREAD

**Issue by jcperil** [SimpleMobileTools/Simple-Gallery#2733]
You have placed the option of enabling repeat/loop videos in Settings. Instead, I feel it should be somewhere in the screen of the video you are watching. Why?

Sometimes you want to loop a video and sometimes you don't. We have to go to settings each time to enable/disable that. That is why, I think there should be a toggle for Repeat mode that is easily accessible from the screen itself. Even music players place the Repeat toggle in the song playing screen instead of settings. I present two alternatives below.

### First alternative
Like vlc media player, the Repeat mode can be made accessible from **More options** menu in the screen of the video itself.
![loop](https://user-images.githubusercontent.com/89805719/212750565-9aed182a-5aa2-463e-ba0c-f712275bf7a0.jpg)

### Second alternative
In `Settings >> Manage visible bottom actions`, you can add Repeat mode. Then users can access it from bottom toolbar.
![managevisibleactions](https://user-images.githubusercontent.com/89805719/212749958-066530ad-26cb-4f18-be9d-73ba9fb995e9.jpg)

**Comment by tibbi** [comment]
I dont really want to add it there, there are already more than enough buttons

**Comment by jcperil** [comment]
But then we have to go to settings each time to enable/disable looping. Don't you think it would be better if it is easily accessible from the screen itself? I cited instances of music players and vlc media player.

**Comment by tibbi** [comment]
you dont really want to toggle that often, at least so far not a single person had issues with it

**Comment by jcperil** [comment]
What sort of argument is that?! Nobody had any issues with the previous search button. By your logic, you shouldn't have had implemented the new search bar.

**Comment by tibbi** [comment]
thats wrong on so many levels.. It was requested often and the vast majority of people really like the new design.

**Comment by jcperil** [comment]
> you dont really want to toggle that often, at least so far not a single person had issues with it

Sure you don't want to toggle that often. Despite that, why do you think it is better to have the loop mode in settings instead of the screen itself? If you don't want to implement it, I would understand. But you have not provided any valid reason.

I am one person requesting it. How often does it have to be requested for you to consider it?
