### ISSUE TITLE
Incorporate Exoplayer for better video playback?

### ISSUE THREAD

**Issue by Cormak** [SimpleMobileTools/Simple-Gallery#274]
Google's ExoPlayer is increasingly being used in open source Android apps. I don't think we currently use ExoPlayer, but perhaps take a look at it to see if it can fix any existing video playback issues?

https://github.com/google/ExoPlayer

**Comment by tibbi** [comment]
Ive tried it in the beginning but it was an overkill. I might check it in the future.

**Comment by jerryn70** [comment]
Whats the use of adding this ? Will it support to play wmv ,vob etc formats ?

**Comment by Cormak** [comment]
@jerryn70 It will definitely support more formats but not necessarily the ones you mentioned. Exoplayer is actually actively maintained so it will likely result in a more stable and functional video playback backend for Simple Gallery. I expect a lot of video playback issues to be fixed if tibbi adds it.
