### ISSUE TITLE
[Feature Request] Adding Black night mode option when using auto theming

### ISSUE THREAD

**Issue by Voralberg** [SimpleMobileTools/Simple-Gallery#2741]
Good morning, I've been using your fundamental application for a while now, I would like firstly to thank you for your work!

If it was possible I would ask of just one improvement, when customizing the colors of the application one chooses the "follow system color" for white and dark mode, would be possible to add (As highlighted in the example of _Material Files_ in attachment) the option to select "Black Dark mode" to have a black background instead of the grayish one?

![Black Dark mode](https://user-images.githubusercontent.com/53734126/213157446-27105e1c-fb78-4068-b2c1-6401f8b0a350.png)

At least I'm referring to **Android version 11** and below, I do not know it this was implemented with the version above.

Yet again, thank you for your work!

**Comment by tibbi** [comment]
I dont plan adding that, it is too advanced.
