### ISSUE TITLE
Setting to "save with default filename and path" 

### ISSUE THREAD

**Issue by e-t-l** [SimpleMobileTools/Simple-Gallery#2743]
[Feature request] It would be nice if there were an option in Settings to bypass the rename dialog that appears when saving an edited image. Given that this dialog already pre-populates the path (with the same folder as the original file), and the filename (with an appended version of the original filename), all I ever do is tap "OK." Much easier would be a setting to simply accept these default values and save the image without any further user interaction after tapping the original " <ins>↓</ins> " save button.

**Comment by tibbi** [comment]
it is already reported somewhere so Ill close this, it is on the roadmap
