### ISSUE TITLE
"Show all folders content" for single folder(s)

### ISSUE THREAD

**Issue by dnngll** [SimpleMobileTools/Simple-Gallery#2749]
Hello,

it would be great, if one could set the feature "Show all folders content" for select folders.

Basically, have a "Show **this** folders content" in the individual folder options. See my professional 😊 mockup:

![Screenshot_20230123-144303](https://user-images.githubusercontent.com/12801866/214054750-fb285e80-d5fa-431d-beca-23cc273def09.png)

Reason being: Via Syncthing I regularly sync

- QR-Codes of Tickets
- Labels
- Passes
- Lists
- Quick ToDo's
- Screenshots of maps
- etc...

to my phone, which I then usually use right away, and delete after. Having the contents of the folders, to which I sync these to, be always displayed would help.

Let me know, what you think.

Thanks

**Comment by tibbi** [comment]
I dont know what you mean here, just open a folder to show its content

**Comment by dnngll** [comment]
Hello @tibbi ,

let me try to explain.

As of now, on the Gallery-Screen we either see
- folders, which you then open and see the pictures
**OR**
- all the pictures, regardless of the folder structure (if the feature "Show all folders content" is activated)

I am suggesting a mix of both: Show folders **and** individual pictures (from select folders, see above) there. So the pictures of your important folders are always shown.

**Comment by tibbi** [comment]
dont really expect having anything like that

**Comment by dnngll** [comment]
Hey @tibbi ,

why not? To difficult to build? Or no one would use this?

**Comment by tibbi** [comment]
it even sounds confusing, cant even imagine how could that work

**Comment by dnngll** [comment]
Well... 🤔

![2023 01 25, 17 59 42](https://user-images.githubusercontent.com/12801866/214630031-27cc6e38-10bc-4b20-98f1-d241d1e5745b.png)

Just like any folder with subfolders and pictures in it...

**Comment by dnngll** [comment]
Well... 🤔

![image](https://user-images.githubusercontent.com/12801866/214630799-2b839047-d3ba-42a1-8b8b-f8a3682b6add.png)

Just like any folder with subfolders and pictures in it...

**Comment by dnngll** [comment]
Well... 🤔

Just like any folder with subfolders and pictures in it.

Before:

![2023 01 25, 18 05 10](https://user-images.githubusercontent.com/12801866/214631522-4ff7b60e-92bb-4a7f-ba66-00f5ddbc377a.png)

After:

![2023 01 25, 18 04 13](https://user-images.githubusercontent.com/12801866/214631548-39874f4d-1626-475d-8364-10554a33818f.png)
