### ISSUE TITLE
Simple Gallery displaying two icons in open with list

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimpleMobileTools/Simple-Gallery#275]
In X-plore, when I long press an image, then press Open With on the menu, then I see two icons for Simple Gallery.

**Comment by tibbi** [comment]
And both of them work? Same thing happens? Does it happen to videos too?

**Comment by KrasnayaPloshchad** [comment]
After update Simple Gallery to new version the problem disappeared to me, so this is fixed. ✌
