### ISSUE TITLE
Resuming/Pausing Video Inaccurate

### ISSUE THREAD

**Issue by kairusds** [SimpleMobileTools/Simple-Gallery#2750]
I noticed that ever since I started using the app, resuming/pausing video playback seems to be inaccurate and would always "autocorrect" itself in a way that ignores the video's milliseconds duration.

I have also confirmed that this is the case for all other supported video file formats.

Here's a demonstration:

https://user-images.githubusercontent.com/32636532/214215067-3d8ed07b-7357-4237-8d19-6a5bf93beb9a.mp4

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by kairusds** [comment]
> what app and OS version are you using?

Simple Gallery Pro v6.26.3
Android 11 MIUI 12.5.7

**Comment by kairusds** [comment]
Hello, have there been any updates for a fix regarding this issue? @tibbi

**Comment by tibbi** [comment]
not yet, we plan updating the video player library soon
