### ISSUE TITLE
Implement encrypted or private directory

### ISSUE THREAD

**Issue by slmb3** [SimpleMobileTools/Simple-Gallery#2752]
I see previous discussion/mentions on
* https://github.com/SimpleMobileTools/Simple-Gallery/issues/181
* https://github.com/SimpleMobileTools/Simple-Gallery/issues/1045
* https://github.com/SimpleMobileTools/Simple-Gallery/issues/1820

Given this was several years ago, have you put any more thought into it since then?

While encrypted directories would be most ideal, I think at least supporting directories in the private app storage is a pretty good suggestion, as it would make the files inaccessible to other apps at least, and I'm guessing it would be easier to implement compared to encryption.

**Comment by tibbi** [comment]
no, but we plan adding it into the file manager first, once we find a way to do it
