### ISSUE TITLE
Set as wallpaper defaults to landscape instead of portrait

### ISSUE THREAD

**Issue by mecuricat** [SimpleMobileTools/Simple-Gallery#2756]
When I click on `Set as wallpaper`, the default orientation is landscape.

![landscape](https://user-images.githubusercontent.com/89805719/215251044-4ad91fc9-86c0-48af-bad5-fbe26c0309ad.jpg)

Since smartphone screens are portrait, shouldn't the default orientation also be portrait?

![portrait](https://user-images.githubusercontent.com/89805719/215251058-12d8842f-94ab-4560-b669-a07590776e14.jpg)

**Comment by Aga-C** [comment]
I think it would be better if the app would set default landscape or portrait depending on picture's aspect ratio. Landscape wallpapers have sense because people mostly have multiple screens.

**Comment by mecuricat** [comment]
But it always choose landscape regardless of picture orientation.
