### ISSUE TITLE
Simple gallery not deleting Whatsapp sent files

### ISSUE THREAD

**Issue by humam2104** [SimpleMobileTools/Simple-Gallery#2759]
I included the sent file from WhatsApp images, videos, and GIFs. What happened is that I can't delete images anymore even though I could delete them earlier. Every time I delete something it shows me that it was deleted and then it comes back after 1:00 or 2 seconds from my deletion command. I've never encountered this with any other folders except for these send folders from WhatsApp.

**Comment by tibbi** [comment]
what app and OS version are you using? Have you granted the app All Files access?

**Comment by humam2104** [comment]
![Screenshot_2023-01-29-22-11-47-670_com android settings](https://user-images.githubusercontent.com/41898465/215346724-c9d579f8-9f42-495d-8ab0-2e38b69c0bbe.jpg)
Attached is my mobile specs. And yes, I gave permissions for files.

**Comment by tibbi** [comment]
Can you maybe try deleting files from other hidden folders? If that isnt the issue.

**Comment by humam2104** [comment]
All other hidden folders in the same directory have the same problem. Also, sometimes it does delete files. I noticed that if I removed the folder from the Included Folders list and added it again, I could delete files.

**Comment by Naveen3Singh** [comment]
@humam2104 have you tried deleting the file after opening it? That is, open a file and try deleting using the delete button at the bottom.

**Comment by humam2104** [comment]
I have just tried that.. the issue still persists

**Comment by Naveen3Singh** [comment]
What I tried:
 - Include the "Whatsapp Sent Images" folder in the Simple Gallery settings
 - Delete a sent image by long pressing and pressing delete on the top bar.... doesn't work, the image pops back after a second. I checked the folder using a file manager and the file is still there.
 - Tap on the image I want to delete, and press the delete button at the bottom... works. The image doesn't come back no matter how many times I restart the app. I checked using a file manager again and the file is properly deleted this time. I'm also testing this using an MIUI 13 device running Android 12

(This is not meant to be a workaround or fix in any way, I'm just looking for more info)

**Comment by humam2104** [comment]
Sometimes, removing the folder from the Included folders and adding it again makes the problem go away sometimes.

**Comment by Naveen3Singh** [comment]
If you are willing to test, I have uploaded a test APK here: https://github.com/Naveen3Singh/Simple-Gallery/releases/tag/fix_deleting_nomedia

or if you want, you can compile one yourself from https://github.com/Naveen3Singh/Simple-Gallery/tree/fix_no_media_deletion

let me know how it goes, thanks

**Comment by humam2104** [comment]
It worked for now. I will be trying the test APK for a few days and will tell you what happens. Because sometimes it works when I reinstall the app. I'm afraid that this might be the case, but I hope not.
