### ISSUE TITLE
Only Basic Editor available in first-time association prompt

### ISSUE THREAD

**Issue by otede** [SimpleMobileTools/Simple-Gallery#2760]
Latest SGP from f-droid
Android 12
Moto G52

It's even the case when I press the edit icon while viewing photos in SGP.

**Comment by tibbi** [comment]
f-droid has only he basic editor, not the advanced. It is not open source.

**Comment by otede** [comment]
> f-droid has only he basic editor, not the advanced. It is not open source.

But the f-droid has better file Access implementation, correct?

**Comment by tibbi** [comment]
not anymore, you can grant All Files access to the proprietary Google Play version already aswell

**Comment by otede** [comment]
> f-droid has only he basic editor, not the advanced. It is not open source.

But the f-droid has better file Access implementation, correct?

> not anymore, you can grant All Files access to the proprietary Google Play version already aswell

Got it!

I'm getting ahead of myself here but can't you ship SGP with the advanced editor on F-Droid with an "antifeauture" or similar indication, per F-Droid regulations?

**Comment by tibbi** [comment]
right, the advanced photo and video editor is not open source, thus cannot be added to f-droid.
