### ISSUE TITLE
Audio does not work

### ISSUE THREAD

**Issue by XabiNarkos** [SimpleMobileTools/Simple-Gallery#2761]
The audio does not work whenever I attempt to watch a video through the app. Whenever I select the "play as audio" option, the screen immediately takes me back to the gallery.   

Videos will play audio after I've either restarted my phone or after I have listened to a video through the gallery app that came with my phone, but only one video at a time before the audio is muted.   

I only just started experiencing this issue today. I have a Samsung S22 Ultra, I cleared the cache, the app has all of the permissions it asks for, and is my default photo app, and was downloaded via F-Droid.  

Thank you

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by XabiNarkos** [comment]
Tibbi -

So I posted this after I had not slept in over a couple of days and upon checking Github this morning (after a good night's sleep) I realize that I should have posted this to VLC 😅 

I'm really sorry for the waste of time but I really appreciate you getting back to me even though my post probably didn't make much sense considering I was describing VLC features. 

But thank you for getting back to me regardless

All the best,
Javier
