### ISSUE TITLE
[Feature request] Allow resizing in editor 

### ISSUE THREAD

**Issue by nevillepark** [SimpleMobileTools/Simple-Gallery#2764]
Hi, I've been using the app for years and love it. But it's kind of annoying to edit an image, then have to exit the editor and resize it separately. Could there please be a "resize" option, perhaps in the Transform menu, so editing and resizing can be done in one step? Thanks.

**Comment by tibbi** [comment]
that editor is developed by a third party group of developers, not us. But we requested it too already.

**Comment by nevillepark** [comment]
Thanks, good to know!
