### ISSUE TITLE
Color banding in full size view

### ISSUE THREAD

**Issue by JVimes** [SimpleMobileTools/Simple-Gallery#2766]
I'm seeing color banding when I open some images. No color banding visible for the same image during transition animations or in Google Photos.

Version 6.26.3

Color banding in Simple Gallery:

![banding](https://user-images.githubusercontent.com/6148201/217156385-e91a7a5b-5e13-4792-b66d-1b2855af07ee.png)

No banding in Google Photos:

![no-banding](https://user-images.githubusercontent.com/6148201/217156408-865cdbe9-b401-4792-81ef-dbcf7e3dfe76.png)

Uncropped image:

![PXL_20230202_221140117](https://user-images.githubusercontent.com/6148201/217156481-f4ba6ca6-2275-4884-b999-580c903010b4.jpg)

**Comment by tibbi** [comment]
try enabling "Show images in max available quality" in the app settings

**Comment by JVimes** [comment]
That was it, thank you. I don't know what deep zoomable images are, but I guess my camera supports them.

**Comment by soshial** [comment]
It caused me significant worries, why my photos look worse in Simple Gallery, than in other gallery applications. I think that this setting should be enabled by default!


Samsung Gallery vs Simple Gallery:

<img src="https://github.com/SimpleMobileTools/Simple-Gallery/assets/100644/be705671-2c4d-4eeb-aba5-112c44a17032" width="300px" />

<img src="https://github.com/SimpleMobileTools/Simple-Gallery/assets/100644/b4d7d382-85c8-4a73-ad4b-122501c98ec5" width="300px" />

**Comment by tibbi** [comment]
it might lag on some devices with ridiculous resolution cameras, we have to improve it the other way

**Comment by JVimes** [comment]
Maybe can load max quality on background thread while current image shown in meantime?

**Comment by tibbi** [comment]
thats not how it works..
