### ISSUE TITLE
Animated webp is played endlessly.

### ISSUE THREAD

**Issue by z0cMWWKmGfudsDG** [SimpleMobileTools/Simple-Gallery#2767]
Animated webp format picture sets cycle times to itself, but Simple-Gallery ignore it and play them circularly and endlessly.
Version: 6.26.3 Pro.

**Comment by tibbi** [comment]
can you send a sample file?

**Comment by z0cMWWKmGfudsDG** [comment]
[test.webp.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/10674414/test.webp.zip)

Open it in web browser then see it has two layers and plays only one time.

**Comment by gmasil** [comment]
This was fixed in https://github.com/SimpleMobileTools/Simple-Gallery/pull/2954.

**Comment by z0cMWWKmGfudsDG** [comment]
> This was fixed in #2954.

No, it was not.

**Comment by gmasil** [comment]
When I take your example image it shows a drawn 1, then changing to a drawn 2 and then stays like that forever. It doesn't repeat. What is happening for you? How did you test it?

**Comment by z0cMWWKmGfudsDG** [comment]
> When I take your example image it shows a drawn 1, then changing to a drawn 2 and then stays like that forever. It doesn't repeat. What is happening for you? How did you test it?

I am sorry. I was dizzy at that time. Yes, it was fixed. Thank you.
