### ISSUE TITLE
Horizontal swipe gestures improvements

### ISSUE THREAD

**Issue by nvllz** [SimpleMobileTools/Simple-Gallery#2768]
It would be cool to be able to customize the video timeline gestures a bit more. These are my ideas for video playback within Simple Gallery:
- The first is autoplay. Even if you previously paused the video, when you drag the slider with a gesture, the video starts playing by itself. It would be more intuitive to capture when the video is paused and only autoplay when it's not. If you don't want it to work this way by default, please consider making it an option.

- My next idea is to make the horizontal gesture work a little differently. I sometimes face a problem when I want to zoom a video and the playback slider moves when I try to make a zoom gesture. To prevent such errors, you could make it slide only when the user holds down a video screen for about a second. You could also add a subtle haptic feedback to let users know they're about to slide the video. This way, you can make sure the feature is only used when it is intended, without the possibility of making such an easy mistake. This is how it works in the Samsung Gallery app and is very intuitive.

- The final idea that would definitely improve the gesture aspect of the app is the ability to improve the precision of the swipe rewind by dragging up (to the top of the screen) while holding the slider/swiping with a horizontal gesture. The higher we drag up, the more precise the rewind will be (the playback position will move horizontally more slowly, which may allow skipping up to single frames). This in combination with the first idea would allow us to find fast moments in dynamic videos with ease.

Please try to respond to each of these and estimate the possibility of my ideas making the app.
Thanks!

**Comment by tibbi** [comment]
report things one by one please, if they havent been reported yet
