### ISSUE TITLE
Improving the User Experience of the Horizontal Gesture in Video Playback

### ISSUE THREAD

**Issue by nvllz** [SimpleMobileTools/Simple-Gallery#2770]
Make the horizontal gesture work a little differently. I sometimes face a problem when I want to zoom a video and the playback slider moves when I try to make a zoom gesture. To prevent such errors, you could make it slide only when the user holds down a video screen for about a second. You could also add a subtle haptic feedback to let users know they're about to slide the video. This way, you can make sure the feature is only used when it is intended, without the possibility of making such an easy mistake. This is how it works in the Samsung Gallery app and is very intuitive.

Original issue: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2768

**Comment by tibbi** [comment]
this one isnt really on the roadmap either. If you want to rewind by 10 seconds, just click on the max or current duration
