### ISSUE TITLE
Making video playback more intuitive

### ISSUE THREAD

**Issue by nvllz** [SimpleMobileTools/Simple-Gallery#2771]
Even if you previously paused the video, when you drag the slider with a gesture, the video starts playing by itself. It would be more intuitive to capture when the video is paused and only autoplay when it's not. If you don't want it to work this way by default, please consider making it an option.

Original issue: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2768

**Comment by tibbi** [comment]
I dont plan changing it now, I want autoplay on drag

**Comment by tibbi** [comment]
because that is what I expect from it and I dont remember anyone having issues with it
