### ISSUE TITLE
Enhancing video navigation with precision swipe rewind

### ISSUE THREAD

**Issue by nvllz** [SimpleMobileTools/Simple-Gallery#2772]
It would be cool to have ability to improve the precision of the swipe rewind by dragging vertically (to the top of the screen) while holding the slider/swiping with a horizontal gesture. The higher we drag up, the more precise the rewind will be (the playback position will move horizontally more slowly, which may allow skipping up to single frames). This in combination with the first idea would allow us to find fast moments in dynamic videos with ease.

Original issue: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2768

**Comment by tibbi** [comment]
that is way too advanced for an app like this
