### ISSUE TITLE
UI question/option for older layout

### ISSUE THREAD

**Issue by hockeymikey** [SimpleMobileTools/Simple-Gallery#2775]
I updated to the most recent version and was very disappointed to see the new bar at the top. It's a huge step backwards and glaringly ugly.  Without digging in too much, these changes were introduced per this discussion I take it: https://github.com/SimpleMobileTools/General-Discussion/issues/180
And on that note, can the legacy/older layout be added back as an option? I think there are others like me and I really can't tolerate the UI in the current state. Reminds me of Android 12, which there's a strong reason I don't use it

**Comment by tibbi** [comment]
we dont really plan adding it back now

**Comment by hockeymikey** [comment]
@tibbi Looks like I'm forking. Where was it introduced?

**Comment by tibbi** [comment]
well, you can see it in the code

**Comment by hockeymikey** [comment]
@tibbi Obviously, but I was hoping for just a quick reference for guidance to get started instead of disregardment, but whatever that's cool.
