### ISSUE TITLE
hidden folder can't be shown again after they were moved

### ISSUE THREAD

**Issue by Meteor0id** [SimpleMobileTools/Simple-Gallery#2779]
1. If I hide a folder in simple gallery,
2. then use some other app to move that folder into another folder,
3. and then cone back to simple gallery and use 'show hidden folders'

This folder will still not show up

I'm on Android 10 if it matters. I've tested tjis quite a lot and thus far it happens every time.

App version 6.25.5 pro

**Comment by tibbi** [comment]
what app you use in step 2 for moving the folder? Maybe they dont refresh the files in the mediastore properly. Or do other galleries show them?

**Comment by Meteor0id** [comment]
I test it again a few times. Initially the folfer was indeed missing as soon as I moved it, but would reappear after a few minutes. Right now if I do it the folder does not go missing (=cannot reproduce issue right now)

I was gonna try it with another gallery app but right now that makes no sense because it is not happening. I've seen it often through, I am sure it will happen again.

I move files and/or folders using an app called total commander

**Comment by tibbi** [comment]
refreshing files in the mediastore can take some time, sometimes a device restart too
