### ISSUE TITLE
menu is confusing, a few suggestions

### ISSUE THREAD

**Issue by Meteor0id** [SimpleMobileTools/Simple-Gallery#2780]
The drop down menu is quite confising and here is why:
- "show folder content" and "switch to folder view" are not obvious opposites because they are not phrased with the same verb. Instead write something like "switch to content in folders" and "switch to content without folders"
Stay away from "switch to content only" as it would not be clear as opposed to what

- the options to switch between folderview and content only view could be moved to be a suboption of "change view" (the same menu where you switch between raster and list view)

- the options "more columns" and "less columns" could be move to be a subopition of the menu "change view" (the same menu where you switch between raster and list view). And it could instead be a numeric selector with a + and - button labeled "number of columns"

- The options "Temporarily show hidden" and "Stop showing hidden media" are not clear opposites because one mentions "media" while the other does not. (in translation to dutch for example those becomes "temporarily unhide items" and "stop hiding media" which looks like they are about different things.) Either speak of "hidden items" or speak of "hidden media" in all strings across the gallery app

Hope this suggestions makes sense, do ask if you need more motivation.

**Comment by tibbi** [comment]
report things one by one please, this cannot be managed like this

**Comment by tibbi** [comment]
will consider those in the future
