### ISSUE TITLE
Must have Option to password protect Recycle bin also

### ISSUE THREAD

**Issue by WANTEDJAAT** [SimpleMobileTools/Simple-Gallery#2782]
Lets assume a case,  I want to delete photos one by one. And I hav enabled password/pin to delete it. It will be a headache to do that everytime.
But I also want a protection so that anybody cant delete my files.

But if we have an option to protect recycle bin. So I have to enter my password once, while emptying or deleting from recycle bin.

That option must be there. 
Thanks.

**Comment by kyoyacchi** [comment]
https://user-images.githubusercontent.com/63583961/220844470-c7a46a01-bd39-4b08-b5e2-00a81b40afd2.mp4

Like this?

**Comment by tibbi** [comment]
right, you can actually lock it just like any other folder, by long pressing it and using Lock folder.

**Comment by WANTEDJAAT** [comment]
Your recycle bin is not secured @tibbi . I can just go to settings and empty the recycle bin. 😀

**Comment by kyoyacchi** [comment]
> Your recycle bin is not secured @tibbi . I can just go to settings and empty the recycle bin. 😀
> 
> I need that protection

Settings > enable "Show Recycle bin at the folders screen" then long press Recycle bin folder then select "Lock folder" option from dropdown menu

**Comment by WANTEDJAAT** [comment]
@kyoyacchi 
I am not talking about this option. I know that.

If u think your recycle bin is secured... Just go to Settings in the Last Click empty recycle bin... An your secured Bin will be empty.. 😀😀

**Comment by kyoyacchi** [comment]
> @kyoyacchi I am not talking about this option. I know that.
> 
> If u think your recycle bin is secured... Just go to Settings in the Last Click empty recycle bin... An your secured Bin will be empty.. 😀😀

I see, that'd be bad really..😆

**Comment by WANTEDJAAT** [comment]
Thats Y I requested to make a seperate option to Secure Recycle bin in All Scenerios.

**Comment by WANTEDJAAT** [comment]
One more thing is there... If anybody wants to delete photo directly
He can also disable Recycle bin Option (i.e. 1st option _Move items into the Recycle Bin Instead..._ ) without any security..
And also delete all your photos 

😶🙄🙄

**Comment by WANTEDJAAT** [comment]
@tibbi , So could u plz add only one lock. And that's on settings.

It will do all. Everything will be resolved then
Thanks

**Comment by tibbi** [comment]
just lock the app...

**Comment by WANTEDJAAT** [comment]
@tibbi @kyoyacchi 
Today I was able to enter Gallery through Camera app. Then able to enter settings from there. And finally able to empty recycle bin

So Neither your app is a password protected nor recycle bin.

Thats Y I requested just 1 thing. SETTINGS LOCK
