### ISSUE TITLE
Selecting an image and pressing "Move to" then showing hidden folders brings up several previously excluded folders. 

### ISSUE THREAD

**Issue by kylewhite0225** [SimpleMobileTools/Simple-Gallery#2787]
Screenshot below, I've set the following folders to excluded: Blossom, .thumbnails, .statuses, .appcache, and com.sec.gallery3d, yet they show up only when selecting an image, selecting move to, and pressing the eye icon and unlocking to show hidden folders. 

If I show hidden folders *without* selecting move to first, these folders do not show up. 

![Screenshot_20230303_092144_Gallery_1.jpg](https://user-images.githubusercontent.com/66845776/222789200-554d051e-ea28-464d-84ec-d0280ae2b942.jpg)

Happens in both version 6.26.3 and 6.26.4. 

Samsung S23 Ultra on Android 13

If needed:
Baseband version:
S918USQU1AWBE
Kernel version:
5.15.41-android13-8-25800099-abS91 8USQU1AWBE
#1 Tue Feb 14 12:54:05 UTC 2023
Build number:
TP1A.220624.014.S918USQU1AWBE

**Comment by tibbi** [comment]
that is currently the expected behaviour, the button shows both hidden and excluded folders
