### ISSUE TITLE
Sort by "date taken" does not work 

### ISSUE THREAD

**Issue by Co-7** [SimpleMobileTools/Simple-Gallery#2788]
Hello, I have noticed for a while that many of my photos were not well sorted. As you can see on the pictures, I sorted by "date taken" but the application sorts the pictures by date of modification for some pictures. And this even when I launch the correction utility in the drop down menu

![photo_2023-03-05_17-51-38 - Copie](https://user-images.githubusercontent.com/48591820/222975257-ec95fbe6-450e-474d-8e5d-37a3e35a8064.jpg)
![photo_2023-03-05_17-51-37 - Copie](https://user-images.githubusercontent.com/48591820/222975263-b32155b7-11a8-4e7c-92a4-d4bebf5cb66e.jpg)
![photo_2023-03-05_17-51-36 - Copie](https://user-images.githubusercontent.com/48591820/222975327-abd904f7-dbe4-41ae-91cb-e5167c0dc534.jpg)
![photo_2023-03-05_17-51-18 - Copie](https://user-images.githubusercontent.com/48591820/222975348-57861ef0-999d-4e63-a022-cfdcbc202de2.jpg)
![photo_2023-03-05_17-51-35 - Copie](https://user-images.githubusercontent.com/48591820/222975349-b006c383-c438-41ef-b79b-db1f6f23f6f0.jpg)
![photo_2023-03-05_17-51-34 - Copie](https://user-images.githubusercontent.com/48591820/222975363-bc1ede25-ddca-4159-9597-fac06f137f7d.jpg)

Thank you for your help 👌

**Comment by tibbi** [comment]
try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by Co-7** [comment]
As you can see on the screenshort it doesn't work (It's just written in french)

**Comment by tibbi** [comment]
make sure you arent confusing sorting and grouping

**Comment by Co-7** [comment]
Oh, I didn't know we could group, thanks
