### ISSUE TITLE
Sort by "date taken" does not work 

### ISSUE THREAD

**Issue by Co-7** [SimpleMobileTools/Simple-Gallery#2789]
Why was my [issue](https://github.com/SimpleMobileTools/Simple-Gallery/issues/2788#issue-1610283408) closed when the person answered completely wrong? 

Link to my issue here :

https://github.com/SimpleMobileTools/Simple-Gallery/issues/2788#issue-1610283408

**Comment by tibbi** [comment]
duplicate of #2788
