### ISSUE TITLE
Can't select multiple photos when using the gallery in whatsapp

### ISSUE THREAD

**Issue by hani-yassine** [SimpleMobileTools/Simple-Gallery#2791]
hello when i want to share multiple photos from whats app i select simple gallery but i cant select multiple photos i keep holding on 1 photo and it just select it and dont give me an option to select other photos 
Edit: it seems it's something related to whatsapp because i tried another gallery and same thing cant select multiple photos, but it will be great if you can do a workaround im using whats app business latest version

**Comment by tibbi** [comment]
if there isnt a flag for selecting multiple items in the given intent, we dont want to support it. You can do it the other way around by selecting multiple files at the gallery thumbnails, then using Menu -> Share.

**Comment by hani-yassine** [comment]
> if there isnt a flag for selecting multiple items in the given intent, we dont want to support it. You can do it the other way around by selecting multiple files at the gallery thumbnails, then using Menu -> Share.

yeah that what im doing but it's not convinient when you are talking with someone on whats app it's faster to open the gallery from within whatsapp if you can fix it that would be great

**Comment by tibbi** [comment]
there is nothing to fix, it isnt an issue on our side
