### ISSUE TITLE
Add This Feature 

### ISSUE THREAD

**Issue by Tronak007** [SimpleMobileTools/Simple-Gallery#2792]
Best Application And I Purchased But Getting 1 Prob That Whenever I Open Any Video It Asks Me To Choose Gallery Or Any Other App To Play I Can't Set Gallery As Default B'coz I Watch Movies And All In VLC Or MX Player So Please Fix This Thing As Whenever I Tap On Any Video It Will Play Automatically B'coz Always Choosing The App Is So Frustrating And Some Other Apps Provide This Already Apps Like Memoria And Some More I Tried Please Add That 

Attached A Screenshot With The Thing 
![Screenshot_20230307-203527](https://user-images.githubusercontent.com/106589892/223524931-5fb144f0-ebce-48fd-afc1-b581391d6b42.png)

**Comment by tibbi** [comment]
that is handled by the system, not us. Just press Always there when the gallery is shown as the default
