### ISSUE TITLE
[FP4] Can't switch to simple gallery to view taken Pictures

### ISSUE THREAD

**Issue by jokeks** [SimpleMobileTools/Simple-Gallery#2794]
Device: Fairphone 4
Rom: Stock

I believe they use a modified Aosp Camera App.
The Google Photo app is disabled.

- Open Stock Camera app
- Take a Picture
- Click on small image preview
- An error message appears: "Google photo is disabled, pleas enable it first." ![IMG-20230308-WA0001](https://user-images.githubusercontent.com/2502808/223688105-aecbcb88-857f-4267-a7a1-396a44adcc1d.jpg)

Is it possible to replace google photo with this app to view the pictures?
Or does this need a fix from the vendor?

**Comment by tibbi** [comment]
sadly some cameras have a hardcoded gallery and others cannot replace them
