### ISSUE TITLE
Slow deleting to recycle bin and restoring

### ISSUE THREAD

**Issue by DangerPie** [SimpleMobileTools/Simple-Gallery#2795]
Judging by speed it just copy and delete.

Gallery 6.26.3, internal memory.

Total Commander works fast. 

TC's author mentioned moveDocument(): https://www.ghisler.ch/board/viewtopic.php?t=45165

**Comment by tibbi** [comment]
recycle bin works differently, it isnt a casual storage. We currently do copy/delete instead of move as it is way too unreliable. But that is already reported somewhere.
