### ISSUE TITLE
App rejected from Playstore

### ISSUE THREAD

**Issue by Raghu2106** [SimpleMobileTools/Simple-Gallery#2803]
I got the app rejected from Play Store based on an issue found "Not a core feature" because MANAGE_EXTERNAL_STORAGE is sensitive permission. 

1) Which option to select from below to submit an answer for "Why does your app need to use the all files access permission?" 
Answer Options: 
	1. Core functionality
	2. Personalisation
	3. Security or Fraud prevention
	4. Analytics
	5. Ads or monetisation 

2) What should be the technical reason?

Can you provide the above two answers?

**Comment by tibbi** [comment]
core functionality

**Comment by Raghu2106** [comment]
What should be the technical reason?

**Comment by tibbi** [comment]
just explain whatever is the usecase of it in your app, we cannot say
