### ISSUE TITLE
Bug in read (pendrive or orthers usb storage)

### ISSUE THREAD

**Issue by Sukii23** [SimpleMobileTools/Simple-Gallery#2804]
the photos and videos do not appear in the gallery, even when selecting the folder where the videos and photos are located on the pendrive or memory card. Yes, I have given read and write permission.

Android (Motorola): 10

**Comment by tibbi** [comment]
just add any missing folders in the app Settings -> Manage included folders.

**Comment by Sukii23** [comment]
i did that and selected the folders that contain the files but they don't appear in the gallery
