### ISSUE TITLE
Feature Request - Provide an option to Clear Thumbnail Cache at exit

### ISSUE THREAD

**Issue by Crowned-Eagle** [SimpleMobileTools/Simple-Gallery#2812]
Provide an option so that the app will create thumbnail cache only for the folders visible in gallery at time of viewing and not for subfolders.

Also provide an option so that thumbnail cache will be cleared at the click of button or preferably at the time of app closing/exit.

**Comment by tibbi** [comment]
that isnt on the roadmap
