### ISSUE TITLE
Including a folder doesn't included the subfolders

### ISSUE THREAD

**Issue by kjlhgfds** [SimpleMobileTools/Simple-Gallery#2814]
When I add the folder "Media" from WhatsApp (containing documents, images, gif, etc) in the "included folders", it doesn't show anything from the subfolders.
I have to add each and every subfolders to make their content apear in the galery.
Is it possible to change this behaviour to make it so when you add a folder to the "included folders" it also scan for media in the subfloders ?
Thanks

**Comment by tibbi** [comment]
it should scan them already, but isnt the folder hidden?

**Comment by Aga-C** [comment]
If you have the `.nomedia` file also in subfolders, then you have to include these subfolders too.

**Comment by kjlhgfds** [comment]
The problem was the ".nomedia" files.
Thanks !
