### ISSUE TITLE
Filter by favorites

### ISSUE THREAD

**Issue by dimdenGD** [SimpleMobileTools/Simple-Gallery#2815]
Is it possible to only show favorited images in a folder? If not I'd like for it to be a feature

**Comment by tibbi** [comment]
not really, you cannot do that. It isnt really on the roadmap either.

**Comment by dimdenGD** [comment]
Really weird how it's not a feature... I have lot of different folders with different favorited images, and often I want to see favorites only from specific folder. Feels kinda essential and weird to not have this
