### ISSUE TITLE
Can not edit video

### ISSUE THREAD

**Issue by roxkaf93** [SimpleMobileTools/Simple-Gallery#2816]
When trying to edit the video I receive a message that app is not found (see attachment). This is for .mp4 files I generate from my camera app or receive via whatsapp. 
Using version 6.26.6. 
![Screenshot_20230407-104004291](https://user-images.githubusercontent.com/130135651/230565717-c162f56c-1e7d-4a74-acf2-c137e57dbd62.png)

**Comment by tibbi** [comment]
guess you got the app from F-droid, the video editor isnt available there.
