### ISSUE TITLE
Foss vs proprietary

### ISSUE THREAD

**Issue by popogomo** [SimpleMobileTools/Simple-Gallery#2823]
Thanks for creating such a great app!
This one is just a question: whats the difference (functionality) between foss and proprietary version of the app? Cannot find any info anywhere. Thanks!

**Comment by tibbi** [comment]
the proprietary one has a more advanced photo and a video editor

**Comment by Secret-chest** [comment]
wasn't SMT supposed to be open source? @tibbi

**Comment by tibbi** [comment]
it is open source, but I couldnt find any good open source video player
