### ISSUE TITLE
Slow at displaying pictures on app launch

### ISSUE THREAD

**Issue by tenzap** [SimpleMobileTools/Simple-Gallery#2825]
When I open the app the list of pictures remains blank for about 7-8 seconds until the pictures are displayed.

Any idea on how to fix this?

Device: Android 12 (Xiaomi redmi note 9s)

**Comment by tibbi** [comment]
what app version and sorting are you using?

**Comment by tibbi** [comment]
right, some performance issues are already reported though so Ill close this one

**Comment by tibbi** [comment]
for example https://github.com/SimpleMobileTools/Simple-Gallery/issues/2549

**Comment by tibbi** [comment]
well, performance improvements are always on the roadmap, it isnt a classic one time ticket that can be fixed forever
