### ISSUE TITLE
go to directory

### ISSUE THREAD

**Issue by lockcher4** [SimpleMobileTools/Simple-Gallery#2827]
I don’t know how, after opening a photo through the command, after exiting the photo, get into it in a folder, but it throws me into the termux. And I did not find the activity itself to get into the directory.

steps to play:
```
am start -d file:///storage/emulated/0/DCIM/Camera/IMG_20230407_084927.jpg -n com.simplemobiletools.gallery.pro/com.simplemobiletools.gallery.pro.activities.PhotoActivity
```

Termux app
Android 12
Xiaomi miui 13.0.10

**Comment by tibbi** [comment]
I dont know what you mean at all
