### ISSUE TITLE
Request: Spaces-Padding Between Pictures

### ISSUE THREAD

**Issue by 0pLuS0** [SimpleMobileTools/Simple-Gallery#2830]
Hello,

First let me say, thanks for all your hard work and all the great apps you make!

I had a look through the settings, so forgive me if this ability is here, but I didn't see it.

I'd like to request, hopefully this won't be difficult, if you can put some spacing/padding between the pictures, so they aren't right next each other.

For me this will look more comfortable on the eyes, and I really hope you can please implement this.

I took one of the screen shots off the repo and made them now appear with more spacing/gapps between the pics.

THANKS

![s gallery_gaps](https://user-images.githubusercontent.com/36190223/232716395-c272fa4c-5119-4b8d-9a26-c205c7893333.jpg)

**Comment by tibbi** [comment]
you can already change spacing in the app Settings -> File thumbnail style

**Comment by 0pLuS0** [comment]
Ok thanks, sorry for the post then...
