### ISSUE TITLE
Sort by "date taken" does not sort by datetime

### ISSUE THREAD

**Issue by TilmanJimenez** [SimpleMobileTools/Simple-Gallery#2837]
This might fall somewhere between bug and feature request...
When sorting by "date taken" I expected the pictures to be also sorted by the time they where taken during that date. Instead they are sorted randomly within the day they where taken!

**Comment by tibbi** [comment]
Hello, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by TilmanJimenez** [comment]
Sorry, I seem to have missed that in the FAQ! My bad!
