### ISSUE TITLE
File grouping by Date Taken gets broken when some files don't have EXIF data

### ISSUE THREAD

**Issue by twisteros** [SimpleMobileTools/Simple-Gallery#2839]
I have a folder with photos. Some of them have EXIF data and some of them don't. 
If I group them by Date Taken then the non-EXIF files get mixed with EXIF ones into one big group.
Might be a separate non-EXIF group placed at the end of the gallery would be a solution? 
Then the rest of the files would get grouped as they should.

**Comment by saefthe** [comment]
مرحبا كيف حالكم يا اصدقائي
كيف يكون هذا بخلط الصور بحسب التاريخ لا ادري ولا اتذكر التاريخ ارجو
المساعده شكرأ الكم

Saef

في السبت، ٦ أيار ٢٠٢٣, ١١:٢٠ ص twisteros ***@***.***> كتب:

**Comment by tibbi** [comment]
Hello, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by twisteros** [comment]
> Hello, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

Thanks.
I've got tens of them and the number is still growing. 
Given the number and the fact they get grouped with exif'd ones it's really hard to identify the non-exif ones.

**Comment by tibbi** [comment]
just use Select All and fix all dates
