### ISSUE TITLE
[Feature request] Add video editing functionality

### ISSUE THREAD

**Issue by vanitasvitae** [SimpleMobileTools/Simple-Gallery#284]
I dont know, if this fits into the scope of this app. I miss a FOSS Android app which is capable of editing video files (changing start and stop at least), so it would be really great to have this in Simple-Gallery :)

**Comment by Theobald93** [comment]
I thought this is a simple image gallery app and no video editing tool... Oo

**Comment by vanitasvitae** [comment]
I thought of this because the app contains a photo cropping feature. Currently I have no possibility to cut videos I made to length. No need for filters or such fancy stuff.

**Comment by Cormak** [comment]
This is an image gallery, not a video editor. Quickpic is the most famous Android image gallery and it did NOT have video editing. Just video playback like every other gallery viewer. Adding this would defeat the point of having a "simple" gallery.

**Comment by gbdomubpkm** [comment]
Simple-Gallery has a photo editor. We can modify photos.. Gallery plays videos (.avi not supported though !). I'm not asking for anything very powerful but I would be very happy if Gallery simply allowed extracting pieces of video in the original format and quality and possibly merging them.
I don't see anything that does this under F-Droid, and I don't want an app full of trackers from the play-store.

**Comment by gbdomubpkm** [comment]
I'm not talking about Simple-Gallery which is a perfectly clean app of course. 🙂 👍. And that is precisely why I have full confidence in it to have the extracting piece of video feature if possible.
