### ISSUE TITLE
Copy/move to window size and layout

### ISSUE THREAD

**Issue by AlbatorV** [SimpleMobileTools/Simple-Gallery#2842]
There is difference between native and Material You for the move/copy to window.
Native window is larger and 'Other folder/Ok/Cancel' buttons are visible.
Material You window is smaller and buttons are not well laid out.

![2023-05-12_121243+](https://github.com/SimpleMobileTools/Simple-Gallery/assets/2797485/e217b7dc-8616-4108-ba3a-1a9da8976396)

**Comment by tibbi** [comment]
thats handled by the system, not us
