### ISSUE TITLE
Combine/merge images into one.

### ISSUE THREAD

**Issue by manieKMP** [SimpleMobileTools/Simple-Gallery#2845]
Would it be possible to add image merging functionality to the advanced editor or somewhere else in the app?
An option to choose several images, tapping "merge/combine" button then select "horizontal/vertical..." position of those images (maybe with preview) and hitting "save". It could be in similar "style" to changing names of files (menu option).

**Comment by tibbi** [comment]
that isnt really on the roadmap. And the advanced editor isnt developed by us, so we cannot add it directly either
