### ISSUE TITLE
[Feature request] Folder combining 

### ISSUE THREAD

**Issue by Qwerty-Space** [SimpleMobileTools/Simple-Gallery#2847]
I understand that there's an option to group direct subfolders, however it would be nice to be able to select folders to group and "combine" 

For example, my camera app will save photos, videos, macro shots, and panoramas etc all in different folders. It would be nice to combine all of these into a "camera" folder/tag so that in the gallery app, they all show up in the same folder.

**Comment by tibbi** [comment]
that isnt really on the roadmap, tags will be added in the future
