### ISSUE TITLE
Opening photo from Xiaomi camera does not work

### ISSUE THREAD

**Issue by cewbdex** [SimpleMobileTools/Simple-Gallery#2853]
I use Xiaomi camera app, as I didn't find anything that performed as good, but I disabled the nightmare Xiaomi gallery app. While this gallery app is a bit too simple, I started to like it. However, when I take picture and open it from camera app (the small thumbnail bottom left), it does not do anything. Will provide any info or help if needed.

![IMG_20230526_144728_097](https://github.com/SimpleMobileTools/Simple-Gallery/assets/9021297/e3c8ee67-3eb9-465a-919e-6a45e1e60318)
![IMG_20230526_144728_119](https://github.com/SimpleMobileTools/Simple-Gallery/assets/9021297/c706ebf0-ba7b-4d19-ac14-a666a7840fde)

**Comment by tibbi** [comment]
does any other gallery work? Some apps have a hardcoded gallery into them and if you disable it, no other gallery can work.

**Comment by cewbdex** [comment]
I don't have any other gallery app, not sure which one should I try, but it seems to me that if I get asked which app to open in, it's not hardcoded, just it's probably some messy request that the app does not handle.

**Comment by cewbdex** [comment]
None of the apps seem to handle the request well, only termux displays something reasonable.

![Screenshot_2023-05-26-22-38-49-261_com termux](https://github.com/SimpleMobileTools/Simple-Gallery/assets/9021297/4649b623-71c1-4e14-8a75-e4733091f1be)

**Comment by tibbi** [comment]
that is some weird intent if it shows not only galleries, but all kinds of apps. Not an issue on our side though

**Comment by cewbdex** [comment]
Those are not really all kind of apps, those are apps that process images, office does OCR, banks QR payments and termux seems to have a handle for literally anything when I share stuff, but it's up to you to not implement this feature that could bring you more Xiaomi users. The issue is most likely on your side, when termux can handle the file, but this app can't.
