### ISSUE TITLE
Previous/next image with mouse wheel

### ISSUE THREAD

**Issue by gl-dev** [SimpleMobileTools/Simple-Gallery#2855]
A great feature for a "manual" slideshow and mouse usage (via USB or BT) would be configurable next/previous image with the mouse wheel

**Comment by tibbi** [comment]
I dont think that is the expected behaviour, dont really expect having it

**Comment by gl-dev** [comment]
What a pity, it would have been nice to not always slide fotos on a tablet but to use other input alternatives especially afar from the tablet
