### ISSUE TITLE
Can't set app to two defaults simultaneously

### ISSUE THREAD

**Issue by Pootismancer** [SimpleMobileTools/Simple-Gallery#2860]
Like the title says, I can't set Simple Gallery as the default app for Gallery and Video Player at the same time. I set the app to one default and it clears the other.

Device: Redmi Note 11
OS: MIUI 13

![Screenshot_2023-05-30-13-17-27-472_com android settings_1](https://github.com/SimpleMobileTools/Simple-Gallery/assets/56169871/e113adae-f041-4b73-a43e-7eba022baec5)

**Comment by tibbi** [comment]
that is all handled by the system, not us
