### ISSUE TITLE
Can you remove this or make it show up ONCE only ? "Show a welcome screen at upgrading from the free version"

### ISSUE THREAD

**Issue by siubb** [SimpleMobileTools/Simple-Gallery#2862]
Now everytime I start the app or restart the phone (and then start the app),
this message shows up.

**Comment by tibbi** [comment]
just uninstall the old free one then

**Comment by siubb** [comment]
The new one has some something I want.
The old free one has some something I want.
It is hard to choose one.
I am not an expert so I didnt understand it is very difficult to do this "remove this or make it show up ONCE only".
I understand now. Thanks.
