### ISSUE TITLE
USB image is blurry

### ISSUE THREAD

**Issue by wan0ge** [SimpleMobileTools/Simple-Gallery#2867]
When connecting via USB, the images in the USB are not loaded at their highest quality and appear blurry.

![2023-6-14_15-32-14](https://github.com/SimpleMobileTools/Simple-Gallery/assets/82034747/93b3f37e-134e-44f2-ac55-56eddd8eed87)
![1686728972281](https://github.com/SimpleMobileTools/Simple-Gallery/assets/82034747/ced0fb82-23f5-4577-bdb3-af22a5a2d2e7)

**Comment by wan0ge** [comment]
> do other apps show them well? It doesnt matter where are the files located.

I tried to record a video.It seems that the problem is that the image in the external USB has not been fully loaded, or only the preview image has been loaded?

https://github.com/SimpleMobileTools/Simple-Gallery/assets/82034747/464632a6-3b50-4047-80da-e31424cfdab2

**Comment by tibbi** [comment]
some png or other image quality is already reported, it doesnt matter where is the file stored
