### ISSUE TITLE
[Simple Gallery Pro] Why do you limit the size of the transformation tool?

### ISSUE THREAD

**Issue by rado84-github** [SimpleMobileTools/Simple-Gallery#2870]
I'm using Simple Gallery Pro and I noticed that since Android 12 (now it's Android 13) the minimum size of the transformation tool (to crop the image) is limited. For instance, if I wanna have a screenshot of the top right corner of the whole screen (the whole screen is image-1), first I have to crop it to the allowed minimum, then save it to image-2, then open image-2 and crop it to image-3-targe-size. I can't do that in one go which is quite annoying. And the tool is set to "Free transformation" which makes it even more annoying bc there's nothing free in that.
IDK if that's a bug or you're limiting it on purpose.

Nokia G21, if it matters.

![screenshots](https://github.com/SimpleMobileTools/Simple-Gallery/assets/41172201/06a07a52-fb68-4251-836a-c21f82ffe1a8)

**Comment by Aga-C** [comment]
Do you mean simple or advanced editor?

**Comment by rado84-github** [comment]
IDK what you mean. I'm talking about the tool in the yellow rectangle:

![Screenshot_20230615-091613](https://github.com/SimpleMobileTools/Simple-Gallery/assets/41172201/ced4b0aa-f026-4af0-9255-acd4222858ac)

**Comment by rado84-github** [comment]
I didn't know that. I don't suppose you wanna share any contact details for these third party developers?

**Comment by tibbi** [comment]
it is obviously public, https://img.ly/products/photo-sdk does it

**Comment by rado84-github** [comment]
How am I supposed to know it's a public tool? I'm not a developer.

**Comment by tibbi** [comment]
I meant it in a way that the app is open source so we cannot really hide it :)

**Comment by rado84-github** [comment]
Problem fixed by IMG.LY, now all you have to do is release a new version for Simple Gallery Pro, whenever they release their updates.

![Picture_created_12-07-2023_19-18-35](https://github.com/SimpleMobileTools/Simple-Gallery/assets/41172201/0a6363d8-093a-4336-92f2-e7c1119ce8a3)
