### ISSUE TITLE
[Simple SMS] Suggestion

### ISSUE THREAD

**Issue by rado84-github** [SimpleMobileTools/Simple-Gallery#2871]
The current layout of Simple SMS when you send a new message to someone is a waste of space, so I'd like to suggest something. Either:
• make the text field larger (variant 1)
OR
• make that empty space display the contact's picture they've set for themselves (variant 2).

![Simple-SMS-suggestion](https://github.com/SimpleMobileTools/Simple-Gallery/assets/41172201/46f02d60-442e-40b8-85a8-2726ac1f1978)

**Comment by Aga-C** [comment]
You should submit this issue here: https://github.com/SimpleMobileTools/Simple-SMS-Messenger.

**Comment by rado84-github** [comment]
Right, my mistake! I thought I clicked the Messenger repo, I guess I didn't.
Delete this topic here, I just posted it where it should be.
