### ISSUE TITLE
Easier moving of photos

### ISSUE THREAD

**Issue by contrapunctus-1** [SimpleMobileTools/Simple-Gallery#2874]
# Background
I categorize my photos into folders quite often. This means I -
1. view many photos (often zooming into them)
2. see if they fit the category
3. select the ones that do, and
4. move them into the folder.

This is repeated many times, moving multiple batches of photos to the same folder. 

# The problem
Each time I move the photos, I have to navigate to the same folder, since Simple Gallery always opens the current directory, rather than the last directory I navigated to.

The destination folders are not important enough to warrant adding them to favorites.

# Possible solutions
1. Make repeated move operations less painful, by opening the last directory rather than the current directory.

2. Reduce the need for multiple move operations, by implementing marking of photos. Photos could be marked when they are opened for viewing.* Marking is conceptually similar to selection, but the critical difference is that one can mark photos and continue to view other images.

   This way, I could view and mark/unmark as many files as I want, and would only need to move all the (marked) files once.

* Marking could also be performed after selecting files in the folder view, but that's less important.

**Comment by tibbi** [comment]
you mean at clicking "Other folder"? You arent selecting the destination from available albums containing images?

**Comment by contrapunctus-1** [comment]
Right, I use "Other folder". I just tried the album picker, and it takes about as much time to find the folder there as to use "Other folder" 🤔

**Comment by contrapunctus-1** [comment]
Thank you very much for implementing #1. It's made things much better in most situations that I face.

**Comment by saefthe** [comment]
مرحبا كيف حالكم
نعم بفضلكم انتم باتت الإمر طيب في احسن حال

Saef

في الجمعة، ٢٥ آب ٢٠٢٣, ١١:٤٢ م Tibor Kaputa ***@***.***> كتب:
