### ISSUE TITLE
Temporarily store zoom level when switching between the photos

### ISSUE THREAD

**Issue by alukycode** [SimpleMobileTools/Simple-Gallery#2875]
Feature request:
When I switch between photos by tapping the sides of the screen, I want the zoom level to be temporarily stored for the last 3-4 photos.

Use case:
I often take multiple similar photos, and then I spend some time choosing the best one. For example, sometimes I need to compare faces in the photos. I use the Gallery365 app, which has the requested feature. To compare the faces in consecutive photos, I usually zoom in on the first photo to focus on the face. Then, I tap on the side of the screen to switch to the second photo. I zoom in on the second photo in the same way, and then I switch back to the first photo, where the zoom level was stored. This allows me to better see the differences. Zoom is stored only for the last 3 seen photos, so when I move to the next photos, zoom levels are reset automatically, and I don't need to un-zoom all photos manually.

**Comment by tibbi** [comment]
that isnt on the roadmap
