### ISSUE TITLE
Feature Idea - Compare two photos

### ISSUE THREAD

**Issue by Dragurashiphylax** [SimpleMobileTools/Simple-Gallery#2877]
I would like to be able to compare two images. The comparison could be made by tapping, then the first image would switch to the second or by side by side comparison. I'd like to be able to zoom in this mode to smaller areas of the images.
> The good example could be Ditto from Google Play

Ps: What about a program that would check for differences in the image?

**Comment by tibbi** [comment]
you can already enable instant photo switching by clicking on screens side in the app settings

**Comment by Dragurashiphylax** [comment]
I don't think that's going to work as photos aren't in the same place and time frame.

**Comment by tibbi** [comment]
nothing more advanced is on the roadmap for photo comparing
