### ISSUE TITLE
Image resizing bug

### ISSUE THREAD

**Issue by VladToreton** [SimpleMobileTools/Simple-Gallery#2883]
There is a bug in 6.26.9 and 6.26.10:
- resize image
- rename it before saving 
- having a bug message and thus, no saving new image!
P.S. When we don't rename resized image - its OK, and have no bug!
I have back in 6.26.8 and don't have this issue!

**Comment by tibbi** [comment]
what does the bug message say?

**Comment by Aga-C** [comment]
![Screenshot_2023-06-25-12-42-48-35_29b563cd0bc4fd07bd0c105b17b28204_1.jpg](https://github.com/SimpleMobileTools/Simple-Gallery/assets/85929121/2311e577-8cb6-4c0d-87cd-75e01454cb78)

**Comment by VladToreton** [comment]
> what does the bug message say?

![Screenshot_2023-06-25-13-48-48-05_29b563cd0bc4fd07bd0c105b17b28204](https://github.com/SimpleMobileTools/Simple-Gallery/assets/95141396/ea728e16-ab1d-4d23-8ff9-eaeec502b131)

**Comment by ChocoTaco1** [comment]
Same
