### ISSUE TITLE
[Bug] Eyedropper position inaccurate when canvas zoomed in

### ISSUE THREAD

**Issue by e-t-l** [SimpleMobileTools/Simple-Gallery#2888]
When an image is fully zoomed out (aka how it normally is), the "eyedropper" color picker in the Edit > Brush mode works as expected, i.e. it samples the part of the image beneath the user's touch.

However, if the user zooms in (e.g. with a two-finger pinch), the eyedropper no longer tracks correctly with the part of the image beneath the user's touch.

I suspect this is due to some miscalculation between the absolute X,Y coordinates of the user's touch on the screen, the absolute X,Y coordinates of the whole image, and the relative X,Y coordinates of the _part_ of the image that is visible on the screen.

To demonstrate this bug, I recorded two short screen captures. I used an image of a colorful number grid to more easily visualize which part of the image the eyedropper is sampling. In video 1, I first how the eyedropper works as expected at 100% zoom. In video 2, I zoom in and demonstrate the unexpected behavior: the image sample in the circular eyedropper cursor no longer corresponds to the part of the image my fingertip is touching.

https://github.com/SimpleMobileTools/Simple-Gallery/assets/40775958/a1265aec-1a48-4d9d-9bda-849b03a7e3cb

https://github.com/SimpleMobileTools/Simple-Gallery/assets/40775958/5b5d2ff6-38c9-46b4-8b56-9e9a25c6c0e9

**Comment by tibbi** [comment]
that editor isnt developed by us. Anyway, what app version are you using? It will be updated in 6.27.0 that will start rolling out now.

**Comment by e-t-l** [comment]
Ah sorry I had forgotten to put system specs! Simple Gallery Pro (F-Droid) v.25.5* on Google Pixel 7 running GrapheneOS 13.
*the latest one available on F-Droid

> that editor isnt developed by us

Sorry, didn't know that! I can repost this bug report in the correct dev's repo. Who develops the editor? I didn't see anything in the readme to indicate it was from a 3rd party..

**Comment by tibbi** [comment]
you seem to be confusing something, that advanced editor isnt available in the F-droid gallery app variant.

**Comment by e-t-l** [comment]
Huh, I was pretty certain I was getting updates via fdroid, but I just installed release-392-proprietary from Github and it updated successfully, so I guess that's the signature I was using. Apologies a third time!

Regardless, the issue does persist in v6.27.0. Where can I find info about the project for the advanced editor? Even if that's part of the proprietary codebase, I should still be able to send the devs an email, no?

**Comment by tibbi** [comment]
sure, it is the PhotoEditorSDK for Android at https://img.ly/products/photo-sdk
