### ISSUE TITLE
Option to hide search bar

### ISSUE THREAD

**Issue by cyber199** [SimpleMobileTools/Simple-Gallery#2892]
How easy would it be to add an option to hide the search bar?  I don't use search at all, instead preferring to organise images into files and just drill down through those.  Additionally, I prefer the look of the colourful top bar, rather than the transparent search bar.

Priority is like the lowest there is, since I can happily use the app without this change, and it's basically just aesthetic preference, but given the extensive colour and theming options already present, this feature request would make sense.

**Comment by tibbi** [comment]
that isnt on the roadmap now, maybe after some redesign

**Comment by saefthe** [comment]
مرحبا
ممكن استخدام الغة العربيه
شكرا لكم على اهتمامكم في

Saef

في الاثنين، ١٠ تموز ٢٠٢٣, ١٢:٤٨ ص Tibor Kaputa ***@***.***>
كتب:
