### ISSUE TITLE
[Suggestion] Delete from here all the way

### ISSUE THREAD

**Issue by xDonatello** [SimpleMobileTools/Simple-Gallery#2895]
Suggestion for a new implementation.

When you select a photo/video, it would be convenient a button "Select all the way" and "Select up here" in the menu.

For example, I have the WhatsApp Images folder with around 6.000 items, and I would like to delete all photos in the folder received after a certain date.
If I'm in the middle of the folder, it takes a long time to get to the bottom.

**Comment by Aga-C** [comment]
You can select the file range. According to FAQ: "The third way of selecting multiple items is long pressing one item, then long pressing another one and everything in between gets selected."

**Comment by tibbi** [comment]
there are already multiple ways of selecting files, I dont plan adding more
