### ISSUE TITLE
Sort by "Date taken" is not working

### ISSUE THREAD

**Issue by johanneskind** [SimpleMobileTools/Simple-Gallery#2918]
Version 6.27.1 installed from F-Droid, on Graphene OS 20230726, Google Pixel 6a

Hi, 

since at least version 6.26.10 the feature "sort by Date taken" does not work as intended, but applies the sorting "Last modified".  Applies for both "Ascending" and "Descending". Switching "Grouping" on and off does not have an effect.

**Comment by tibbi** [comment]
Hello, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by johanneskind** [comment]
Thanks a lot! Keep up the outstanding work :)
