### ISSUE TITLE
Bug or am I missing a setting?

### ISSUE THREAD

**Issue by mawar108** [SimpleMobileTools/Simple-Gallery#2920]
Since the new update all Mainfolder are missing and only the Subfolder appering on the Mainscreen. With and without the setting "Group direct Subfolders" (dont know the orginal naming in english) doesnt do anything and i dont see any other Setttings what can cause this ^^" If anyone knows how to set it back that the Mainfolders appering back i would be happy, bacause now its reallly messy.. :D

ps.: Deinstall and install with default settings didnt do anything and even with the setting above

**Comment by tibbi** [comment]
we will revert some related changes soon
