### ISSUE TITLE
empty recycle bin from three dot menu from the default folder view pls 🙏

### ISSUE THREAD

**Issue by valtoree** [SimpleMobileTools/Simple-Gallery#2922]
hi
love your app,
can we please get the above integrated please.
currently I have to scroll down to the recycle bin folder, then enter it, then hit the three dot menu to empty recycle bin.
but I would rather just from default view, starting app view, for me is folders view, and then go to three dot setting and empty the rubbish bin.
tx 4 reading.

**Comment by tibbi** [comment]
that isnt really planned
