### ISSUE TITLE
Thumbnails missing for animated webp

### ISSUE THREAD

**Issue by gmasil** [SimpleMobileTools/Simple-Gallery#2923]
Hi,

I played around with the thumbnails settings and I was enabling "Animate GIFs at thumbnails", which worked out fine for GIFs, but removed all thumbnails of my animated webp files. It looks like a transparent image, in some folders with only animated webp files it seems that the folder is empty, but you can touch on the correct positions to open and view the animated files.
So now I disabled that option again, but the thumbnails are still transparent/missing.

![2023-07-31 09_47_02-Clipboard](https://github.com/SimpleMobileTools/Simple-Gallery/assets/54176035/ce48a330-7c52-415e-91da-97f8e15e9313)

I tried reinstalling the app, clearing all caches, browsing those files in other galleries in the hope they might recreate thumbnails (valid thumbnails are shown in other apps btw.), but without any luck.

I built the app from current master and tried it on my phone (Pixel 6a w/ Android 13) and in Android Studio with a Virtual Pixel 6a API 33, but strangely without touching the option no thumbnails for animated webp files are shown. Originally I had the latest Pro version installed from Google Play Store.

Here is an example webp to reproduce: https://mathiasbynens.be/demo/animated-webp-supported.webp

Any ideas what I could try? I am willing to investigate how this is happening and how to fix it, it would be helpful if you could explain at which point a thumbnail is created and/or where its loaded from, that would bring me up to speed.

Thank you very much in advance,
Simon

**Comment by gmasil** [comment]
This is not a feature request, but a bug report. This used to work perfectly fine.

I tested some versions:

master (5da3f4ccb3096d6561a91249acb2aa65814e52bc) - not working
6.27.2 - not working
6.27.1 - not working
6.27.0 - works
6.26.10 - works
6.26.8 - works

So the bug must be introduced here: https://github.com/SimpleMobileTools/Simple-Gallery/compare/6.27.1..6.27.0

**Comment by tibbi** [comment]
well, it is supposed to animate gifs, not webp files. Those are different.

**Comment by tibbi** [comment]
will be fixed in 6.27.3
