### ISSUE TITLE
[Feature request] Two-finger-rotate

### ISSUE THREAD

**Issue by danielmmmm** [SimpleMobileTools/Simple-Gallery#293]
Being able to rotate pictures would be very useful. Especially when one has zoomed into a part of an image, and when the rotation button is not available in full screen mode.

**Comment by Solarunit** [comment]
Agree. I miss this feature.

**Comment by maulwuff** [comment]
would be great to see this geasture

**Comment by vertigo220** [comment]
This is one of the big ones I immediately noticed missing compared with QuickPic, and I would love to see it implemented. But I would also like an option to have images saved in the new orientation when rotated. I realize many people don't like the auto-save for this, but if it's an option they could choose. Though I don't think it should change the modified date, and I'm aware there are other technical issues involved, but I just wanted to mention my preference. I always find it irritating when I rotate an image, then come back to it shortly after only to have to rotate it again, over and over. Perhaps a compromise could be a database that would save the orientation of rotated pictures so they're always viewed in that orientation, but it wouldn't change the picture's EXIF data or actually rotate it.

**Comment by danielmmmm** [comment]
As long as jpeg's are transformed losslessly, autosaving the rotation would be acceptable. Otherwise, the image quality would deteriorate with every rotation.

**Comment by tibbi** [comment]
this has already been added

**Comment by poisonborz** [comment]
@tibbi How can this be turned on? If an issue like this is closed, the resolution should detail on how to solve it.

**Comment by tibbi** [comment]
it is enabled by default, just make sure you use the Pro version
