### ISSUE TITLE
Some Photos get sorted/grouped by File Change Date despite settings being on Image Taken

### ISSUE THREAD

**Issue by linuzzx** [SimpleMobileTools/Simple-Gallery#2930]
I have some photos that get sorted by their file changed exif tag, not the photo taken tag, despite having the settings for photo taken tag

![Screenshot_20230803-113443_Galerie](https://github.com/SimpleMobileTools/Simple-Gallery/assets/57060126/bdbb944d-03cc-4cdc-8cb2-6c3467ed137d)

In this case the app acts like the picture was taken in 2023 despite it being from 2017

**Comment by tibbi** [comment]
Hello, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by linuzzx** [comment]
Already did, I don't have the problem anymore since I switched to gcam. Seams to be a problem with the EXIF tags of the lineage OS camera

**Comment by poltak** [comment]
@tibbi That fixed this problem for me. Thanks. Though I'm curious what is "Fix Date Taken" actually doing?
