### ISSUE TITLE
When watching Videos the video is crashing or has a black screen

### ISSUE THREAD

**Issue by Git08hb** [SimpleMobileTools/Simple-Gallery#2932]
Like the title says.

Is the app crashing? No the video is crashing and sends me back to the folder or sometimes the video goes black and there's no playback.

Fdroid Verison Simple Gallery: 6.27.2

**Comment by tibbi** [comment]
what OS version are you using? What is the file extension?

**Comment by Git08hb** [comment]
> what OS version are you using? What is the file extension?

GrapheneOS

MP4

**Comment by tibbi** [comment]
I mean what Android version, like 13?

**Comment by Git08hb** [comment]
13

**Comment by tibbi** [comment]
does it happen at every video? Do those broken videos play well in other apps?

**Comment by Git08hb** [comment]
It happens sometimes not always and it doesn't matter which Video I'm watching, it's just happening when the app wants it. For example i watched a video and the crash happened then I tried watching it again a few times and it didn't crash. I tried it on a few videos and like i said, it crashes when the app wants to? The videos work without issues on other apps
