### ISSUE TITLE
[Feature request] Whitelist folders

### ISSUE THREAD

**Issue by danielmmmm** [SimpleMobileTools/Simple-Gallery#294]
With the current behaviour of included and excluded folders, one can only blacklist sub-folders. If one wants to only include/show "sdcard\pictures", one has to exclude all other folders under "sdcard\*".

One way to whitelist folders would be to show only included folders, as long as the list of excluded folders is empty.
Another possibility would give sub-folders priority. E.g. when a folder on the included or excluded list is a sub-folder of the excluded or included list, the list-type of said sub-folder determines, whether it will be shown or not.

**Comment by tibbi** [comment]
ah, Ill leave it here as a feature request, but i dont really want to complicate the app with such complex features barely anyone needs

**Comment by danielmmmm** [comment]
Personally, I find whitelisting incredibly useful. But I get how it can be confusing if not expected by users.
Thanks for the quick reply and an opensource alternative to QuickPic!

**Comment by sagarsiddhpura** [comment]
I would be glad if you could add this

**Comment by tibbi** [comment]
Ive changed the behaviour so that if a folder is both excluded and included, its shown. That way you can exclude the root folder and include any folders you want. Its a simple and totally predictable way to do it, should solve your problem.

**Comment by danielmmmm** [comment]
Thanks a lot! :-D
