### ISSUE TITLE
Find images from text 

### ISSUE THREAD

**Issue by neirusalwa** [SimpleMobileTools/Simple-Gallery#2941]
Hi I recently got an android phone after years of using an iphone and so far so good but a sore spot for me has been the lack of a "good" gallery app (understand : it ticks all the boxes i want). A lot of people have recommended simple gallery because out of the 2 features I need which are hiding pictures with biometrics and finding images from their contents it ticks one of those 2 really well and I'm glad for that. I'm however sad that I have to use 2 separate apps to achieve what I could with just one. Samsung's default gallery app which came with my new phone has such a feature and it works alright and is all on device (as far as I understand). 
I have been wondering if implementing such a feature in simple gallery would be possible but I'm not a dev and not aware of the feasability of such thing. 
[This app from the play store](https://play.google.com/store/apps/details?id=com.mamsie.memescanner) seems to do it on device but I don't know if their way of doing it is something that can be replicated here because it seems to use some Google stuff for it.

Thanks.

Edit : Besides Samsung's (uses on device Bixby vision) and the one i've mentionned above (some Google framework), Google Photos can also do it but the images HAVE to be backed up since it does ir server side which also means you can't even reliably use it for freshly backed up images as it needs to populate some kind of index before it shows you any results. I've tried to enable backup but selectively turn it off on a test folder and then try and look for very easy text strings in the images from that folder but it returned nothing everytime.

**Comment by sojusnik** [comment]
That's a great idea! Local [OCR](https://en.wikipedia.org/wiki/Optical_character_recognition) on all pictures would be tremendously helpful to have!

**Comment by tibbi** [comment]
thats way out of the scope of this app
