### ISSUE TITLE
Selfies are automatically displayed mirrored if viewed in fullscreen

### ISSUE THREAD

**Issue by linuzzx** [SimpleMobileTools/Simple-Gallery#2947]
Why is this and how can I disable it?

**Comment by tibbi** [comment]
you have to toggle that in your camera app, the gallery just shows already existing files in a way they have been created

**Comment by linuzzx** [comment]
in any file manager they display correctly

**Comment by saefthe** [comment]
مرحبا كيف حالكم
ابحث على جميع الملفات ولم اجد ملفاتي

TEST
احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by linuzzx** [comment]
https://upthis.de/dl/ni7bki/screen20230817132615.mp4

Made a selfie of my finger so you can see what I mean

**Comment by linuzzx** [comment]
but it just reverses the effect my camera setting has

**Comment by tibbi** [comment]
what app version are you using at all?

**Comment by linuzzx** [comment]
6.27.2 the newest from fdroid

Tibor Kaputa ***@***.***> schrieb am Do., 17. Aug. 2023,
15:35:
