### ISSUE TITLE
AVIF and HEIC images not opening

### ISSUE THREAD

**Issue by alerikaisattera** [SimpleMobileTools/Simple-Gallery#2948]
AVIF and HEIC images cannot be opened

Device: Galaxy M12
Android: 13
Version: 6.27.2

**Comment by jlHertel** [comment]
Having the same issue with all my AVIF photos.

Device: OnePlus 9
Android: 13
OS: Lineage OS for MicroG 

The files are generated with FFMPEG from jpg using the command: `ffmpeg -i "$fileName" -c:v libaom-av1 -still-picture 1 "${rawFileName}.avif"`

**Comment by tibbi** [comment]
not even thumbnails appear?

**Comment by jlHertel** [comment]
No, both Thumbnail and the image itself are black.
The app doesn't crash or anything, it just shows a black image.

**Comment by tibbi** [comment]
do they open in other downloaded gallery apps?

**Comment by jlHertel** [comment]
Good point.
I only use this app, but downloaded some random apps to test including Google Photos and none of them is able to open the images.
Curiously they open fine in KDE and also on Firefox in Desktop.

**Comment by tibbi** [comment]
well, it might be some device glitch then with codecs or who knows what

**Comment by jlHertel** [comment]
Is there any debug mode or more verbose logs I can look into?
Happy to help track this down.

**Comment by tibbi** [comment]
not really, it is hard to solve such issues

**Comment by alerikaisattera** [comment]
> not even thumbnails appear?

Thumbnails don't work as well

**Comment by alerikaisattera** [comment]
> do they open in other downloaded gallery apps?

I don't have any other galleries, but AVIF can be viewed in Bromite

**Comment by Aga-C** [comment]
There is already an open issue for adding AVIF support: https://github.com/SimpleMobileTools/Simple-Gallery/issues/2496.
