### ISSUE TITLE
Support creation date for videos too

### ISSUE THREAD

**Issue by tamas646** [SimpleMobileTools/Simple-Gallery#2950]
I seeked and found an exif tag called `Media Create Date` in a video file recorded with my camera app. Maybe this could be used to display video creation date in 'Properties'.
Also expanding the `Fix Date Taken value` feature to work with videos too would be awesome.

What do you think?

**Comment by tamas646** [comment]
@tibbi whould you please explain why did you close this issue without any explanation/comment?

**Comment by tibbi** [comment]
well, it is already described in #950, which you even linked

**Comment by tibbi** [comment]
Im not sure, do other galleries use it? Not sure how reliable it is.

**Comment by tamas646** [comment]
The only gallery I use is SimpleGallery which does not, so I'm not sure...
But if you say it cannot be used for some reason than fine, I accept it. I was just waiting for an explanation.
