### ISSUE TITLE
[question] What does 'Fix Date Taken value' function do exactly?

### ISSUE THREAD

**Issue by tamas646** [SimpleMobileTools/Simple-Gallery#2951]
I found this function in the app and it's been suggested in a lot of sorting related issues. I found it myself working fine too.

But I did not found any relevant info about what it does exactly... I thought that it changes some exif tag of the files, but I did not notice any changes between the two versions (before and after).

So what does this function really do with the images?

**Comment by tibbi** [comment]
Hi, checking file by file would be really slow, so at sorting by Date Taken the app relies on the system MediaStore, which is kind of an internal database storing file metadata, like Date Taken. If you do "Fix Date Taken values", it takes the Date Taken from the file itself and updates the value in the database.

**Comment by tamas646** [comment]
Thanks.
