### ISSUE TITLE
Split simple gallery, and the editor into to separate apps

### ISSUE THREAD

**Issue by K4LCIFER** [SimpleMobileTools/Simple-Gallery#2957]
Keeping with the theme of it being a "simple app", it feels like an unnecessary complication to include a photo editor within the gallery app -- not to mention that the app specifies "gallery" in it's name, rather than "editor". These two things should be separated. I propose that the "simple gallery" app only includes the gallery, and the photo editing/markup part should be put into its own independent app that gets called when you want to edit a photo.

**Comment by tibbi** [comment]
thats not planned
