### ISSUE TITLE
Do not show hidden photos/videos

### ISSUE THREAD

**Issue by kuzuza2** [SimpleMobileTools/Simple-Gallery#2960]
Ver 6.27.2
Android 12
Clicked show hidden folders, granting access to hidden folders, but it only shows previews of videos, not videos (Photos and videos downloaded from telegram).

Tried deleting app data and granting all necessary permissions and then accessing the app. Result, it is fully displayed as expected, but only 2-3 seconds later it returns to the issue I mentioned above.

**Comment by tibbi** [comment]
try enabling permanent hidden item displaying and adding the misbehaving folders in the app Settings -> Manage included folders.

**Comment by kuzuza2** [comment]
Tried "Manage included folders" but it's still the same, it only shows up for 2-3 seconds and then hides again, the folder part is fully displayed but the issue is that it doesn't show up in the "all items" section.

**Comment by kuzuza2** [comment]
Addition: I just realized it still shows a few videos (~1/20), somehow it doesn't show them all, the system library and some other libraries show them all.

**Comment by kuzuza2** [comment]
Update: This can be temporarily fixed by checking "scroll thumbnail horizontally", but it will be a bit inconvenient because the photos/videos below are partially covered.

**Comment by kuzuza2** [comment]
Finally: successfully fixed, ... -> group by -> do not group files.
