### ISSUE TITLE
Deselect files after sharing?

### ISSUE THREAD

**Issue by justinmcgrath** [SimpleMobileTools/Simple-Gallery#2962]
I feel like it would make sense to deselect files after you've using one of the sharing options. Currently, it keeps them selected, so after sharing if you select another picture, it adds that to the selection. This means you need to deselect things yourself, which I find unintuitive and it makes it easy to then, for example, select a file you want to delete, and accidentally delete the ones you had selected to share as well.

**Comment by Sukii23** [comment]
I agree with what he said, but if something is implemented, it could have an option to keep or not keep selected files after sharing, or something like that.

**Comment by tibbi** [comment]
current one is the expected behaviour. Deselecting is really easy, but reselecting after sharing for the sake of deletion etc would be a lot more work.
