### ISSUE TITLE
Weird input delay

### ISSUE THREAD

**Issue by guranu** [SimpleMobileTools/Simple-Gallery#2964]
Hello, whenever i try to open a folder in simple gallery there's (for the lack of better words) a delay here's what i mean: 

https://github.com/SimpleMobileTools/Simple-Gallery/assets/103632948/6273f2b0-22ca-48c2-898c-6bea056412be

**Comment by tibbi** [comment]
what app and OS version do you have?

**Comment by tibbi** [comment]
right, some related improvements have already been reported though, performance can always be better

**Comment by guranu** [comment]
> right, some related improvements have already been reported though, performance can always be better

That didn't answer my question at all.
