### ISSUE TITLE
Animated webp files are black in the grid view

### ISSUE THREAD

**Issue by GambaJo** [SimpleMobileTools/Simple-Gallery#2966]
In the grid view there are no previews of webp files.
![Screenshot_20230905_135447_Gallery](https://github.com/SimpleMobileTools/Simple-Gallery/assets/1378907/98f25933-8eaa-4ab3-9ad9-56021f354408)

Here the same folder in another gallery app for comparison
![Screenshot_20230905_135550_Gallery](https://github.com/SimpleMobileTools/Simple-Gallery/assets/1378907/84f3d82f-eca0-4660-979f-16af48606b27)

**Comment by tibbi** [comment]
should be fixed already in the next app version
