### ISSUE TITLE
Zoom: Fit To Screen

### ISSUE THREAD

**Issue by nixballs** [SimpleMobileTools/Simple-Gallery#297]
Excellent app and very active development.

Greatly appreciate if you could add option for:
first double tap --> zoom: fit to screen (based on rotation h/v)
second double --> zoom: full resolution

**Comment by tibbi** [comment]
tried it, but its not that simple with the current library

**Comment by Michele64** [comment]
One reason I really like your app is exactly this feature! Double tap - > 100%, perfect for checking focus/motion blur. Please leave it as it is

**Comment by tibbi** [comment]
an option for two double taps will be added in 6.2.0, disabled by default
