### ISSUE TITLE
No Deletion Toast on Fullscreen

### ISSUE THREAD

**Issue by rorybd** [SimpleMobileTools/Simple-Gallery#2973]
Normally when deleting an image or moving it to the recycle bin, Simple Gallery shows a toast confirming that the operation has occurred.

This toast fails to appear when viewing images and videos in 'fullscreen' mode.

Version: 6.27.2
OS: Android 13

**Comment by tibbi** [comment]
you mean the "Moving 1 item into the Recycle bin" etc?

**Comment by rorybd** [comment]
Indeed. When in grid view, it appears as normal, but not in the fullscreen viewer.

**Comment by tibbi** [comment]
right, I dont think it fits there though, you can see that it happened and it would be quite spammy when deleting many files

**Comment by rorybd** [comment]
Every other gallery app I've used keeps the toast and it's never been a problem in terms of fitting or spam, but I suppose it's down to personal preference.
