### ISSUE TITLE
"Show images in the highest quality" not available without deep zooming images.

### ISSUE THREAD

**Issue by nikkopt** [SimpleMobileTools/Simple-Gallery#2975]
I have "Deep zooming images disabled" because i like the app to force me to only zoom up to 100% and not more. The problem with this is that images are MUCH lower quality because i can't turn on "Show images in the highest quality"
Examples below, both images are at 100%
![Screenshot_20230913-170110](https://github.com/SimpleMobileTools/Simple-Gallery/assets/2060960/38aabb7b-bcb0-4c44-97d6-5f1c552095c3)
![Screenshot_20230913-170133](https://github.com/SimpleMobileTools/Simple-Gallery/assets/2060960/f56dda87-e0e7-4f67-af84-51962d4cdd72)

Is there some technical reason why one option can't be on without the other?
I have the latest pro version installed and am on android 13

**Comment by tibbi** [comment]
yeah, it is the same library handling those. Anyway, some quality and performance issues are already reported elsewhere, we will try improving it soon.
