### ISSUE TITLE
Sort by date taken, group by date taken uses last modified value for some photos

### ISSUE THREAD

**Issue by Yutsuten** [SimpleMobileTools/Simple-Gallery#2979]
I have a very big folder with about 1500 photos, all with the date taken correctly set.

In the default app of my phone the photos are grouped and sorted as expected, but with Simple-Gallery about 60% of my photos use the last modified value for sorting and grouping instead of the date taken.
If I open a photo that was taken, like, in 2018 and check the properties, the "Date taken" is correctly shown. So Simple-Gallery detected the date taken. But in the sort/grouping, it is using the today's value (the last modified date).

I guess it is an issue with big folders, because with smaller ones the issue seems to not happen.

**Comment by tibbi** [comment]
Hello, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.

**Comment by Yutsuten** [comment]
Oh, there is a workaround! Thank you, I just selected everything and clicked that button.

I still think this should work without manual intervention though. By closing the issue I can see you guys are happy with the workaround. Not so user friendly but well... it works, at least. Thanks again.

**Comment by tibbi** [comment]
it would be ideal, but it doesnt work due to system issues...
