### ISSUE TITLE
Folders should be visually distinguishable from images

### ISSUE THREAD

**Issue by IeP4nieF** [SimpleMobileTools/Simple-Gallery#2981]
I accidentally deleted the "Camera" folder repeatedly when I only want to delete one image. Yes, there was a red warning popup, which asked me if I really want to delete the folder, so it was my fault. But it happened, mostly because I was in a hurry. So my suggestion is, that directories are visually distinguishable from images. At the moment they look the same.

**Comment by tibbi** [comment]
the current warning is enough, will see if it changes in the future
