### ISSUE TITLE
When add including Android/data folder showing error

### ISSUE THREAD

**Issue by AdityaMishra135** [SimpleMobileTools/Simple-Gallery#2988]
Can't access data folder and . nomedia files from Android/data

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2988.

**Comment by Aga-C** [comment]
It's a duplicate of https://github.com/SimpleMobileTools/Simple-Gallery/issues/2869.
