### ISSUE TITLE
Music (*.mp4) is not running in the background

### ISSUE THREAD

**Issue by kanlukasz** [SimpleMobileTools/Simple-Gallery#2989]
Hi,

Not sure if this is a question, bug or feature request but i can't listen music in the background.
When I close or start another application, the music is stopped.
Is this intentional? If so, how listen music in the background?

App version:
- 6.27.2 (pro version)

Android version:
- 12

**Comment by inson1** [comment]
Its bug. I'm using lower android version and lower version of the app and it works.

**Comment by tibbi** [comment]
doesnt that other app play some sound? That stops our music player.

**Comment by tibbi** [comment]
oh right, you mean the gallery, not the music player. Background playback has already been reported somewhere so Ill close this.

**Comment by kanlukasz** [comment]
Ok, do you remember which ticket it is? I would like to follow up with updates

**Comment by tibbi** [comment]
cant see it now, not sure which was it. But it isnt really on the roadmap for the near future.

**Comment by kanlukasz** [comment]
Ok, I understand. I'll try your music player and see how it works. Thanks for the replies

**Comment by inson1** [comment]
@kanlukasz 
Btw music player cant play .mp4
#1080 I think he meant this? I didnt find any more fitting issue. Did you find more fitting issue?
