### ISSUE TITLE
Why can't i update simple gallery pro app?

### ISSUE THREAD

**Issue by Wizjul88o** [SimpleMobileTools/Simple-Gallery#2991]
I can't able to update simple gallery pro app v6.27.2 to v6.28.0

**Comment by inson1** [comment]
@Wizjul88o Try resetting your phone?

**Comment by inson1** [comment]
@Wizjul88o Try reseting your phone?
Google play? F-droid? Android version?

**Comment by tibbi** [comment]
why not, are you getting some error, or what happens? Arent you from Russia or Belarus?

**Comment by licaon-kter** [comment]
@Wizjul88o if F-Droid, see https://github.com/SimpleMobileTools/Simple-Gallery/issues/2990#issuecomment-1742878772 and have patience
