### ISSUE TITLE
bad implementation of content uri

### ISSUE THREAD

**Issue by asklow** [SimpleMobileTools/Simple-Gallery#2992]
Why does the video file name change everytime I open ? Everytime, the video I play from gallery, has a different integer number attached to it. Due to this, I can't able to resume it from where I quit, because I use [mpv-android](https://github.com/mpv-android/mpv-android/issues/542) player, which stores watch-later resume information through the content uri the client provides.

**Comment by tibbi** [comment]
what app and OS version are you using?

**Comment by tibbi** [comment]
that isnt even our video player

**Comment by tibbi** [comment]
do other galleries work better?

**Comment by tibbi** [comment]
well, galleries dont have as many permissions as file managers
