### ISSUE TITLE
Colors not saved in export settings files

### ISSUE THREAD

**Issue by AlbatorV** [SimpleMobileTools/Simple-Gallery#3000]
If you customize color in settings, save settings then apply to new installation, colors are no apply to new installation.

**Comment by Aga-C** [comment]
If you changed colors in Custom theme, they are saved in exported settings. Just the setting to not use Material You is not respected after import. When you go to Settings and change color theme to `Custom`, you will have the same colors as before exporting.

The same issue is in Simple Calendar.

**Comment by AlbatorV** [comment]
You are right, just notice this... but need to be improve.
