### ISSUE TITLE
[BUG] Top bar icons when selecting items don't have consistent colors

### ISSUE THREAD

**Issue by mijorus** [SimpleMobileTools/Simple-Gallery#3017]
![Screenshot_20231024-111749_1.png](https://github.com/SimpleMobileTools/Simple-Gallery/assets/39067225/2684f6cc-ef04-45ca-ad6b-f9aae1059de4)

**Comment by inson1** [comment]
I can't reproduce it.

What Is your android version, android UI version, app version?

What Are your color app/system settings?

Add "[BUG]" before your issue title text

**Comment by mijorus** [comment]
6.28.1 Android 13.

Maybe it's because of the colour scheme? I'm using the material you colour palette

**Comment by inson1** [comment]
@mijorus Because of this issue I changed "colors" to different colors, so I can see the problem.

"I'm using the material you colour palette"
How? Is that in app settings or phone settings? And where?

**Comment by inson1** [comment]
@mijorus I dont think the app can change color of icons? 

@tibbi ?

**Comment by inson1** [comment]
@tibbi And What about the gallery?

**Comment by mijorus** [comment]
Looks like killing the app and reopening fixed it, nevermind then.
Thanks for the quick response
