### ISSUE TITLE
Dumping memory, app will freeze. Brrrr.

### ISSUE THREAD

**Issue by Lonami** [SimpleMobileTools/Simple-Gallery#302]
This toast appeared for a while on my screen and there is no way to get rid of it. I was using the F-Droid version.

<img src="https://user-images.githubusercontent.com/6297805/27989785-5125a4c4-6441-11e7-94fc-71466bce67c5.jpg" height="240px" />

[Here is the gist](https://gist.github.com/Lonami/1b35399708f999e22d06fa0c30428ad1) with the information I could get from it later once the report was ready, it's too lengthy to put it here.

**Comment by tibbi** [comment]
aha right, f-droid is using the debug version of builds :D Ill disable it.

**Comment by Lonami** [comment]
That's what I thought, but it was weird F-Droid deployed a debug version. Anyway, the app did leak a tiny amount of memory so maybe it's good to keep it mind?

**Comment by tibbi** [comment]
Theres always some leaks, the most major ones were already fixed. F-droid keeps deploying debug versions of every app, its not signing them in any way.
