### ISSUE TITLE
Sort on 'Date taken' does not work

### ISSUE THREAD

**Issue by jrpear** [SimpleMobileTools/Simple-Gallery#3028]
When I sort the files in a folder by "Date taken", the files are sorted by the modified date from the filesystem rather than the date taken date from the EXIF data.

I have seen this problem for many months.

[This comment](https://github.com/SimpleMobileTools/Simple-Gallery/issues/3021#issuecomment-1787455041) seems related.

`getExifDateTaken` is only called once in this repo, [here](https://github.com/SimpleMobileTools/Simple-Gallery/blob/3cb12cc41bb579dabb676f2fe83b53a63089fe1b/app/src/main/kotlin/com/simplemobiletools/gallery/pro/fragments/ViewPagerFragment.kt#L76). And that code seems like it's for the properties pop-up.

I couldn't find the code for sorting files in the folder view with some grepping, so I can't provide any more pointers.

**Comment by tibbi** [comment]
Hello, try selecting the wrong files by long pressing their thumbnails and using Menu -> Fix Date Taken values.
