### ISSUE TITLE
Crop: select aspect ratio

### ISSUE THREAD

**Issue by SammysHP** [SimpleMobileTools/Simple-Gallery#303]
When cropping an image it would be nice to select some common aspect ratios like:

- 4:3
- 3:2
- 16:9
- 1:1
- original image / current selection

And the inverse, of course. Or – if it is simpler – just two inputs where the ratio can be set manually.

**Comment by tibbi** [comment]
multiple new aspect ratios will be added in 6.0.3 released soon, Custom aspect ratio will be added later too
