### ISSUE TITLE
[Request] Quick delete with undo button.

### ISSUE THREAD

**Issue by krompus** [SimpleMobileTools/Simple-Gallery#304]
It would be nice to have the option to toggle the delete confirmation popup, so that a little undo popup showed up instead, allowing one to keep tapping the trash icon to delete multiple images from the viewer.

**Comment by tibbi** [comment]
it used to be like that but many people disliked it, so Ill leave the current way. Ill just maybe move the confirmation to the actionbar menu, like quickpic has.

**Comment by krompus** [comment]
Ah, alright. Why not a toggle for both though? Delete confirmation by default, and a toggle to enable the undo popup instead? It's just cumbersome when you want to delete multiple images from the viewer.
