### ISSUE TITLE
Remove exif is gone?

### ISSUE THREAD

**Issue by sombresu** [SimpleMobileTools/Simple-Gallery#3049]
There's nothing in the bottom of properties.

**Comment by tibbi** [comment]
it isnt always available, depends on the storage and your OS version

**Comment by sombresu** [comment]
> it isnt always available, depends on the storage and your OS version

That sounds like bs. It was always available before.

**Comment by inson1** [comment]
@sombresu https://github.com/SimpleMobileTools/General-Discussion/issues/241 Fork https://github.com/FossifyOrg
Idk why tibbi is still responding here
