### ISSUE TITLE
Problema app contatti messaggi telefono

### ISSUE THREAD

**Issue by Giucar060** [SimpleMobileTools/Simple-Gallery#3053]
Non si può modificare o anche solo vedere la descrizione del contatto.Ho pagato per un app che non posso usare con tranquillità.

Ho contatti che hanno più numeri di telefono e non posso sapere ne, nel caso sia errato, cambiare o scegliere il numero.
Sia se telefono sia se mando un messaggio. In pratica L opzione apri con.... Non funziona. Sviluppatori Che faccio? Inoltre la vs mail di contatto è inesistente.

**Comment by Giucar060** [comment]
Mi chiudi senza darmi una soluzione o almeno provarci?

**Comment by Giucar060** [comment]
Mi chiudi senza darmi spiegazioni?

Il sab 6 gen 2024, 22:07 Tibor Kaputa ***@***.***> ha scritto:

**Comment by inson1** [comment]
@Giucar060 1. please use english
SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg

**Comment by Giucar060** [comment]
Thanks, I will!

Il dom 7 gen 2024, 00:36 inson1 ***@***.***> ha scritto:
