### ISSUE TITLE
Show groupled subfolders in search results and main screen when pinned

### ISSUE THREAD

**Issue by ThreeDeeJay** [SimpleMobileTools/Simple-Gallery#3058]
It would be nice to be able to search for grouped subfolders without having to ungroup them first, especially since groups reduce the need for search and might even be faster to just scroll through when there's fewer of them.
Perhaps it could also be combined with the "**Search all files instead of folders on the main screen**" option (or just a separate one) so that search includes both grouped subfolders and files.

Also it might be handy to always show pinned subfolders at the top instead of hidden within their parent group, so that we can have both easy-access folder and the lower priority folders can still remain in their group to reduce clutter.

**Comment by inson1** [comment]
@ThreeDeeJay SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg

**Comment by ThreeDeeJay** [comment]
Oh wow, no wonder it hadn't been updated in a while.
Thanks for the heads up! 👍
