### ISSUE TITLE
Reading Old Cache Image Everytime in Loading Image via Cross App

### ISSUE THREAD

**Issue by the-netspider** [SimpleMobileTools/Simple-Gallery#3060]
If the Image is Opened from the Other App's Cache Directory via Launcher Command and the Image Name is Same It Always shows the first opened Image .

**Eg. Steps:**

1. I have an XApp which Loads an image from the server with name '_**image.png**_'. It Loads and save to XApp's cache Directory.
2. I then open the Image via Launcher Command and Selects SimpleGalleryPro, It Opens.
3. Now In the XApp If I load another Image from server and Image has same name, my XApp Deletes the Old Image and recreate new image with same name '_**image.png**_' , Now When I open the Image via Launcher Command again and Selects SimpleGalleryPro, It Keeps showing the old Image.

Even If I reinstall My XApp, But It SimpleGalleryPro always Stuck on that Old Image. However All other Gallery Apps Refreshes the New Image
I have to clear SimpleGalleryPro Cache everytime, to view the New Image, and it makes no sense 🙂.

Please look into it

**Comment by inson1** [comment]
@the-netspider SMT apps were sold to ad company. Fork is here https://github.com/FossifyOrg

**Comment by the-netspider** [comment]
Closing here, Will Open in Fossify.
Thanks
