### ISSUE TITLE
[Feature Request] Use CLIP for in Image search.

### ISSUE THREAD

**Issue by haldi4803** [SimpleMobileTools/Simple-Gallery#3064]
Hello,

I'm certain I'm not the only one who is jealous of Google Fotos Image search that allows you to search for "tree" and all pictures with trees show up.

It seems like that's possible with CLIP now fully locally on your own device.
A high end device analyzes 1'000 pictures in about 2 minutes. So even bigger libraries can easily be scanned over night even by older devices.

As example check out this app here:
 https://github.com/greyovo/PicQuery

That would be a pretty cool addition to simple gallery or not?
Would it also be feasible?

**Comment by inson1** [comment]
@haldi4803 SMT apps were sold to ad company. https://github.com/SimpleMobileTools/General-Discussion/issues/241
Fork is here https://github.com/FossifyOrg

**Comment by inson1** [comment]
https://github.com/FossifyOrg/Gallery/issues/19 just for other people wondering
