### ISSUE TITLE
[Feature request] Undo deletion or recycle bin

### ISSUE THREAD

**Issue by anonimousse12345** [SimpleMobileTools/Simple-Gallery#307]
Hi

Would love an "undo deletion" feature.

For some reason despite the confirmation dialogue I always manage to accidentally delete important photos.

Perhaps instead of "sure you want to proceed with deletion?" pop-up, you could just immediately delete, but then have an "Undo deletion" option appear for some period, e.g. 10 seconds or until the user moves to a different screen.

(I've been searching everywhere for a photo viewer app with both a true delete feature AND an undo or recycle bin but can find none. Google Photos has the "undelete", but photos that have been "deleted" still remain on the device in their original locations and are still seen by all other apps, such as the backup app I use which continues to unnecessarily back up my "deleted" photos...)

**Comment by tibbi** [comment]
I used to have an Undo in the beginning, but I disliked the general user experience. I dont want to add it back, I just want to move the delete confirmation in the actionbar menu, so its not in the middle of the screen. That way you can delete images accidentally even quicker :)

**Comment by tibbi** [comment]
so for now I wont be moving the delete confirmation in the actionmenu, since Ive added a checkbox for skipping whole confirmation dialog in the given session.

**Comment by biphasic** [comment]
what about a bin ? This would make a confirmation dialogue unnecessary. One could set an auto-delete after 60 days for the bin folder/album

**Comment by tibbi** [comment]
a trashbin will be added, but Ill keep the confirmation dialog too, ideally moved to the actionmenu.

**Comment by trubitsyn** [comment]
Will the exported files be suggested to be moved to trash too (like it asks whether to delete the exported file too when deleting)?

**Comment by tibbi** [comment]
what exported files?

**Comment by trubitsyn** [comment]
Notes, exported to files. Sorry for the typo.

**Comment by tibbi** [comment]
this is about the gallery, you cannot export notes to images. I dont know the details anyway, it is just an idea so far.

**Comment by brunetton** [comment]
Hi @tibbi. Any news on this one ? Just used this *great* app (not just because this is open source, but this is really a great one!) to delete **many** photos from my SD card. Really really better than using the camera interface !
I really enjoy the "don't ask again for this session" option for fast deleting. But this is so fast that I deleted one of my favorites photos :-\ I'd have loved a way to undelete it, wherever it was.

Do you plan to add it? 
Thanks

**Comment by tibbi** [comment]
Hey, a recycle bin will be added someday, but I cannot promise any date. Check https://photos.google.com/ if you have some backup there.

**Comment by brunetton** [comment]
Hi yes I've understood that a recycle bin was implemented some time ago. Thanks for the google plus trick, but I deactivated those sync, plus I was working on a camera's DS card and I don't think it would have been synced anyway.

**Comment by tibbi** [comment]
a recycle bin will be added in 4.3.0, enabled by default. There will be multiple easy ways of disabling it.
