### ISSUE TITLE
Stock Dependencies?

### ISSUE THREAD

**Issue by Baerbeisser** [SimpleMobileTools/Simple-Gallery#31]
Are there any stock dependencies? Cause on SlimKat, Simple-Gallery shows nothing.
If so, could you please implement an option to define your path?

And why orange? :-/

**Comment by tibbi** [comment]
There shouldnt be any dependencies. Dont you use any special security app that prevents Simple Gallery from accessing your photos? It should display photos of whole device split into albums, no path needed.

I like orange :)

**Comment by Baerbeisser** [comment]
Wow. At this time of saturday? :+1: 

No, freshly installed, nothing modified in AppOps. No problems with QuickPick too.
Even though Kitkat has some problems with acces to sdcard, its not the case for SlimKat. I tested it again, all permissions are right.
How does it search for media? (Sorry, too lazy to look in code)

Dark titlebar with dark style would be nicer :(

**Comment by tibbi** [comment]
ye Im working on the Calendar even after midnight, weird indeed :D 
The way it looks for files is through Android ContentResolver https://developer.android.com/reference/android/content/ContentResolver.html , Im not scanning everything on the device manually. It just returns a list of images from everywhere, and I filter them by the parent directory.
Some customization might come in the future, who knows. I want to focus on functionality of apps first.

**Comment by Baerbeisser** [comment]
Hmm... So ContentResolver is dependent from media storage or mediaserver?
Cause i removed them (buggy and sucks on battery).
logcat tells the truth:
  Failed to find provider info for media
  Failed to find provider info for media
  Unable to start service Intent { act=android.media.IMediaScannerService cmp=com.
  android.providers.media/.MediaScannerService } U=0: not found
Sadly, it seems your App is not for me.
Can i close the issue?

**Comment by tibbi** [comment]
not sure what can I do without being able to reproduce it, but I can take a look in the future. Just leave it open.

**Comment by Baerbeisser** [comment]
Nah. You would have to implement an indexer, to make it work without ContentResolver.
Or support for busybox find, with option to choose path of busybox and path to search? :-)
Thanks for your help anyway.

**Comment by tibbi** [comment]
you can use Settings -> Manage Included Folders already for adding folders manually
