### ISSUE TITLE
Add checkmark when item is selected

### ISSUE THREAD

**Issue by sagarsiddhpura** [SimpleMobileTools/Simple-Gallery#311]
While selecting items, it highlights selected items by color overlay. But this is sometimes not enough. If you have plain photos of colours highlight is not apparent immediately. Similarly in album where there are many photos and you have come to bottom and you again go up, it would be better if it also had checkmark. What do you think?
![4d83e5ef-c4c9-40a0-b32f-8b6475c5d172](https://user-images.githubusercontent.com/2182259/28498496-915f9104-6fbc-11e7-9a4e-c8694636e9a0.jpg)

**Comment by tibbi** [comment]
yes, it will be added in #171
