### ISSUE TITLE
Maybe consider removing swipe down to refresh

### ISSUE THREAD

**Issue by sagarsiddhpura** [SimpleMobileTools/Simple-Gallery#312]
Swipe down to refresh is causing selection problems when scroll is set to horizontal.

Steps:  - Select scroll horizontal
 - Longpress first item and slide finger downwards in attempt to select below album
Instead of selecting below album, swipe is activated

Also due to this, horizontal scrolling is not smooth. It ends as soon as you lift finger. In my humble opinion gallery app does not need swipe down to refresh. Any update action like copy/move automatically updates UI and as such under normal circumstances you never need to refresh ui. Maybe you can consider moving it as menu option if it serves another purpose. 

 Thanks for the app :)

**Comment by Theobald93** [comment]
In horizontal scroll mode the app "always" want to refresh because i do not exactly swipe horizontal.
The refresh in horizontal scroll mode should be at the left edge instead on the top edge.

**Comment by tibbi** [comment]
ye I wanted to do it like that, but it wasnt as simple as I was hoping for. Ill get back to it someday.

**Comment by tibbi** [comment]
Ive disabled pull-to-refresh in horizontal scrolling, Ill see how many people will miss it :) I want to improve the long press-dragging thing, currently it scrolls properly only vertically.

**Comment by sagarsiddhpura** [comment]
Hi,

Thanks for action. This will certainly help users.

May I suggest that you enable swipe refresh layout till fetching operation is running and disable it as soon as fetching is complete. This will cure both drag select and scrolling problems. I have implemented this idea and it seems to work fine. 

https://github.com/siddworksinc/My-Gallery/blob/master/app/src/main/kotlin/com/simplemobiletools/gallery/activities/ShortcutsActivity.kt
(search for 'directories_refresh_layout')

**Comment by tibbi** [comment]
not sure what you mean. I see the refreshing circle spinning icon at starting up the app even with horizontal swiping, isnt that what you mean? Btw you can link to a specific line if you click the line number.

**Comment by sagarsiddhpura** [comment]
This is perfect. Please consider it for vertical scrolling too :) 

Lines 168 & 182.

**Comment by tibbi** [comment]
I want to keep vertical refresh for now, in some cases its still needed.
