### ISSUE TITLE
Keyboard does not hide inside FilePickerDialog

### ISSUE THREAD

**Issue by sagarsiddhpura** [SimpleMobileTools/Simple-Gallery#314]
Steps to reproduce:
 - Select any photo
 - Menu: Copy to
 - Button "Other Folder"
 - FAB "New"
 - at this point create new folder dialog opens. Press "cancel"
 - Keyboard would not hide. It is  now impossible to browse and pressing back takes us back instead of hiding keyboard.

**Comment by tibbi** [comment]
it hides properly to me on all devices. What android version do you have?
