### ISSUE TITLE
automatic device orientation changing at fullscreen depending on device sensormode is too sensitive

### ISSUE THREAD

**Issue by lucamp** [SimpleMobileTools/Simple-Gallery#320]
Hi,
thank you for implementing auto rotation at fullscreen.

Is it possible to make it less sensitive?
For instance rotate from vertical to horizontal when device is at 70° or -70° and not at fewer angle. Actually just little movement makes it rotate. The best solution is an option to decide the desired sensitivity so everyone will be happy.

Is there a way to consider the rotation also when device is put on a table? Or at least recognize it and keep the last rotation

Thanks for your efforts 
Luca

**Comment by tibbi** [comment]
hey, I might consider in the further future, but such rotation related things are always tricky and hard to get it right.

**Comment by dajusc** [comment]
Hey @tibbi, 

first of all: Thank you very much for the awesome simple mobile tools! :)

For me, the behaviour described above is a serious issue. On my Nexus 5X the rotation goes crazy, whenever the device is slightly tilted or tabbed. 

I suggest to average the readings from the accelerometer over a period of about 1 second, in combination with a simple hysteresis treshold for the next change of orientation. 

I'f only I was an App developer, I'd try to implement it myself. ;)

Best regards
David

**Comment by tibbi** [comment]
hey, its simple in theory, not that simple otherwise :) Ill google something in the future.

**Comment by dajusc** [comment]
Hehe, true! ;) Thanks for looking into it.

**Comment by lucamp** [comment]
Hi,
you could check "document viewer" at https://github.com/SufficientlySecure/document-viewer.
It's a gpl project and their device orientation works smoothly

**Comment by tibbi** [comment]
thanks, Ill check it out

**Comment by klawdhfzasjhaa** [comment]
Here's another hint for a smoother device orientation change:
https://f-droid.org/packages/org.horaapps.leafpic/
https://github.com/HoraApps/LeafPic/blob/HEAD/README.md

Maybe the methods from can be used in Simple gallery, too.

**Comment by tibbi** [comment]
so have you tried it personally if it works better? Because that project got kind of abandoned even before getting a stable release.

**Comment by klawdhfzasjhaa** [comment]
That's true. Moreover, I like the approach of your Simple Mobile Tools (no unnecessary permissions, no ads, good GUI). LeafPic has some folders / files in the sources named "purchase" which is suspicious..
Yes, I've tried LeafPic. The orientation changes work smoother.

Shall I upload a video or are you able to reproduce the described behaviour by yourself?

**Comment by tibbi** [comment]
They offer in-app purchases if downloaded from playstore, its not a secret :)
Anyway, I should have enough info by now, I will take a look at it someday. Thanks

**Comment by tibbi** [comment]
document-viewer is crashing for me, but Ive changed the rotation threshold from -45,45 to -75,75. Let me know if it still doesnt feel good. Thanks

**Comment by tibbi** [comment]
Im moving it to -60,60 so inbetween + adding a button for locking orientation for example at watching videos

**Comment by tibbi** [comment]
so I changed the degrees back to -75,75 as it is currently too difficult to keep the device in landscape mode. I will try adding some delay or something to it someday, to make it work like at "System setting".

**Comment by klawdhfzasjhaa** [comment]
Hello Tibor,

sorry, I did not response earlier. I tried the new releases, but unfortunately the behaviour persists. See attached GIF. I only tilt back and forth with no left or right turn.

To your question: Yes, I tried LeafPic and the orientation switching is much smoother.

![untitled2](https://user-images.githubusercontent.com/2808094/34457646-1ffef5da-edb7-11e7-9d10-954ffa00fc93.gif)

**Comment by tibbi** [comment]
Aha, thought you are moving your device on a different axis, not like this. Anyway Ill get to tweaking it more someday. Thanks

**Comment by tibbi** [comment]
so I tweaked it again, I found out that I can rely on the system too. From 3.3.0 the "device rotation" will behave the same way as when "System setting" is set with allowed rotation.

**Comment by klawdhfzasjhaa** [comment]
Sounds great 💃 . Will test as soon as the F-Droid build is ready.

**Comment by lucamp** [comment]
Hi, last commit is perfect!
Thanks
