### ISSUE TITLE
Play/seek bar not clickable in landscape mode when playing videos.

### ISSUE THREAD

**Issue by gena01** [SimpleMobileTools/Simple-Gallery#326]
I tend to watch videos fullscreen in landscape mode on my android tablet. I am unable to click on the play/seek bar to seek the video in landscape mode since it's under the area where normal android controls are. Is it possible to add an option to show that bar on top or higher so that it can be useful in landscape mode?

**Comment by tibbi** [comment]
Hey, can you send me a screenshot what you mean, and also tell what device with what Android OS do you have? Thanks

**Comment by gena01** [comment]
![screenshot_2017-08-14-18-34-31](https://user-images.githubusercontent.com/312125/29346444-56321944-8213-11e7-8517-48d1c6323a9c.png)

**Comment by tibbi** [comment]
should be working fine from the next version. I have no device to test it on, but in theory it should work :p
