### ISSUE TITLE
landscape photos are not viewed corretly when device is rotate from landscape to portrait 

### ISSUE THREAD

**Issue by lucamp** [SimpleMobileTools/Simple-Gallery#330]
Hi,
Steps to reproduce:

~ Use app's automatic device orientation setting or android setting
~ Open a landscape photo (for instance 1920 x 1080)
~ take the device in landscape so photo appears entirely on your screen with no zoom
~ rotate physically to portrait and the photo does not appear completely on you screen but is zoomed
~ return again to landscape and photo appear completely on the screen 

With no zoom, photos should always appear entirely on the screen and not cutted, no matter which device orientation has phone 

Thanks 
Luca

**Comment by tibbi** [comment]
ye Im aware of it but the simple solution didnt fix it and its not worth spending too much time on :)

**Comment by tibbi** [comment]
seems to be a bug in the used library, its reported at https://github.com/davemorrissey/subsampling-scale-image-view/issues/155

**Comment by cassist** [comment]
I'm getting a similar error, except landscape images do not show at all if viewed in portrait orientation.

**Comment by gcalzo** [comment]
Same for me on my Motorola Moto G5 plus

**Comment by tibbi** [comment]
zoom should be reset from version 3.4.0
