### ISSUE TITLE
Allow moving pictures to different folders

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#34]

**Comment by ouafnico** [comment]
Very nice app. Same as you, just miss the move option to use it :-)

**Comment by tibbi** [comment]
a Copy function has been added, a more advanced conflict handling + Move will come soon too

**Comment by andreadec** [comment]
Thanks! I'm really interested in this feature.

**Comment by tibbi** [comment]
both Move and Copy are added already. I still need to add conflict resolving, but thats for another issue.
