### ISSUE TITLE
Add Folder Option

### ISSUE THREAD

**Issue by jonathanwash** [SimpleMobileTools/Simple-Gallery#340]
Just wondering if it would be possible to add the ability to add folders within the app a little easier?
I found that I can add an folder if moving/copying a picture and than choosing Other Folder but that is a little unintuitive and would love to replace QuickPic with this and get my company off it too.

**Comment by tibbi** [comment]
ye I need to rethink it, too many people ask about it

**Comment by tibbi** [comment]
should be a bit easier in 2.14.0 released soon, hopefully people will understand how it works ;)
