### ISSUE TITLE
Permission errors when writing to external storage

### ISSUE THREAD

**Issue by tp0** [SimpleMobileTools/Simple-Gallery#342]
**This does not happen with every file**. If the long error message below isn't enough, I can then upload the files that cause this for me.

2.13.3
Android 6.0.1
External storage: regular SanDisk SD card

* When moving a file from internal to external or from a folder on external to another folder on the external:

![screenshot_20170831-033657](https://user-images.githubusercontent.com/5863551/29901171-20c22342-8dff-11e7-983b-bc6f64c6230f.png)

* When renaming a file on the external storage:

![screenshot_20170831-033510](https://user-images.githubusercontent.com/5863551/29901193-45c9e468-8dff-11e7-9fe3-676b43fd0285.png)

**Comment by tibbi** [comment]
can you please shoot me a mail at hello@simplemobiletools.com please, Ill send you a test version. Thanks

**Comment by tp0** [comment]
This was some kind of an issue with cache. No longer reproducible. Closed.
