### ISSUE TITLE
Refresh problem - too slow

### ISSUE THREAD

**Issue by 2SI3NX** [SimpleMobileTools/Simple-Gallery#346]
Everytime i open the gallery app, it always wants to refresh (not that that bothers me) but the problem is, is that it refreshes for a very long time.  I can select a folder to go into without waiting for the refresh to finish, but its a bit frustrating and makes me think that not all photos are correctly accounted for in the main folder menu or in any folder for that matter.

Why does it take so long to refresh every single time the app is opened? surely the "long time refresh" should take long only on first time use.  But not after its done that.

Should you remove the refresh swipe down according to this: https://github.com/SimpleMobileTools/Simple-Gallery/issues/312? Im not too sure if that would help in any case, since other gallery apps still have that feature. however it should not keep refreshing for many minutes each time you open the gallery app or each time you go into a specific folder.

This has been an ongoing problem after many version updates and i thought someone would have picked this up by now.

I love this app and would like to use only this. However at the moment i am using F-stop as well, because the refresh and the showing of new photos is too slow on Gallery.  thanks for this awesome app by the way!

**Comment by tibbi** [comment]
Hey, that issue about removing pull-to-refresh was meant only for horizontal scrolling, to avoid gesture glitches. Anyway, what version of the app do you have? The performance has been improved in 2.13.4, but it has been released only 22 hours ago, so its not on f-droid yet.

**Comment by 2SI3NX** [comment]
Oh ok, i still have 2.13.3 which was updated yesterday.  Will let you know once i get 2.13.4 and give feedback. thanks

**Comment by 2SI3NX** [comment]
Its still doing the same thing :(

**Comment by tibbi** [comment]
Hey, can you retry 2.15.1? It should be improved. Thanks

**Comment by Phoenix1747** [comment]
Small push. Still experiencing this "problem" with the latest version, the apps needs relatively long to load file changes compared to other galleries, but it's not too bad.

**Comment by 2SI3NX** [comment]
@tibbi yea, it hasnt changed, still loads slow.  Any way you could improve the speed?

**Comment by tibbi** [comment]
maybe, its not that easy

**Comment by tibbi** [comment]
I improved something related to general refreshing, will be applied in 3.0.3 released soon. Also check excluded/included/hidden folders/files, if everything is shown only when it should be. Thanks

**Comment by tibbi** [comment]
Quickpic is faster because they dont really validate files at all, I see so many invalid files in the gallery. I prefer my way, slightly slower, but only valid items being shown.

**Comment by Phoenix1747** [comment]
Yeah, it's definitely better to validate files. It's really not too bad, just clearly slower than e.g. the pre-installed (shitty) galleries. I'd not label this as a bug, but more as a general improvement, if you somehow manage to validate faster.

**Comment by Phoenix1747** [comment]
Let's see what 3.0.3 brings us.

**Comment by tibbi** [comment]
well, it doesnt really matter how I label it :) theres no label for general improvement only bug, feature, question

**Comment by Phoenix1747** [comment]
You could technically create your own labels, but not to worry :P

**Comment by tibbi** [comment]
sure, I created these 3 to keep it simple, there were many more by default. None of them has any priority, its just for a brief overview.

**Comment by maulwuff** [comment]
What about refreshing images in a background service when new images are taken?
or maybe refresh pinned folders first, then the ones according to the sort order. After that, everything not yet in the gallery list.

**Comment by tibbi** [comment]
I dont know how to detect if a new image was added since new Android OSs limit background activity, I dont want to do any frequent checks either

**Comment by maulwuff** [comment]
Ok, then maybe my other suggestion would work.
For me it takes 5s best and 15s worst to make the waiting circle dissappear at startup of the app. After that, the new thumbnail shows up on the corresponding folder. This feels like a very recursive way to scan folders ;-)

It's a hard fate to be compared to QuickPics performance, but it's an honor at the same time, too. Nothing else out there, that I have tested so far to replace it, has the same focus and determination than simple gallery (not even f-stop, which I use for my asset management)

**Comment by tibbi** [comment]
I will return to optimizing the performance with some tricks in the future, but for now it's good enough to most people and I want to focus on other bugs/features/apps.

**Comment by tibbi** [comment]
So in the end I improved the refreshing by tweaking a file check, it's faster by like 10-20% on my device, it will obviously be different on other devices. You might see a few invalid files at first run after upgrading to 3.1.1, but after refreshing or relaunching the app you will not see them anymore in any gallery app.

**Comment by maulwuff** [comment]
This is a huge improvement on my device. Takes max 3s even after clearing the cache.
 The more processing intense way of excluding folders is also very fast (everything empty on include). 
I think this issue can be closed now 😉

**Comment by tibbi** [comment]
glad to hear that. There's still some slow devices tho, I guess always will be. I'll keep it open for now anyway.

**Comment by 2SI3NX** [comment]
F-Droid has not pushed update yet. WIll let you know once updated to 3.1.1

**Comment by Phoenix1747** [comment]
It's really strange, on my phone the app is rather slow but on my tablet it loads like instantly. Both are using the exact same version of the app and android. I guess, it heavily depends on the processor speed?

**Comment by tibbi** [comment]
ye such things depend on a lot of things, thats why it is hard to do it right. The manufacturer, Android OS version, processor and memory affect it too. A guy reported that he has a custom OS with Android 7 and a folder with 2 images loads for 30 seconds..

**Comment by Phoenix1747** [comment]
Hm, didn't think that things like this were so complicated. Anyways, it's not too bad and at least the latest update did change it for some devices!

**Comment by tibbi** [comment]
everything is more complicated than it looks like. Working with files in general especially. Once a guy had a totally same phone as me just his SD card was from a different manufacturer and it already had issues.

**Comment by Phoenix1747** [comment]
Oh god, this is some really annoying randomness :/

**Comment by tibbi** [comment]
So it turns out that Quickpic can listen for background file updates probably because they are targetting a very old target Android SDK which doesnt limit background activity that much yet. You can see it also by the Storage permission, which isnt asked at runtime, but it is granted during installing, like it was normal before Android 6. If you check Quickpic at your device settings and remove the Storage permission, then run the app, it wont find any images or ask the permission, it just isnt prepared for it. Google got stricter about it a couple weeks ago and announced that If they dont update their app to the latest SDKs this year they wont be able to update their app from november 2018. They will have to tweak quite a few other things in the app too to make it work properly which will bring many new issues to them, especially considering they dont look like theres anyone actively working on the app ;)

**Comment by Phoenix1747** [comment]
Oh wow, that's some good plot twist right here.

**Comment by tibbi** [comment]
I added an optional extra check to avoid showing invalid files, will be added in 3.4.0. It should prevent showing files for example removed at folder sync. I didnt see any performance difference at media loading on my devices, but apparently it can slow down many of them so I made it optional. Most people dont need it anyway.

**Comment by tibbi** [comment]
should be better in 3.7.0, Im rewriting the way media files are fetched
