### ISSUE TITLE
How to use this library to show only one specific directory ?

### ISSUE THREAD

**Issue by PG90** [SimpleMobileTools/Simple-Gallery#347]
I want to use this library for only one specific directory in android.

**Comment by tibbi** [comment]
Do you want to show the initial screen with the folder name and picture count too? Or just directly the images inside?

**Comment by PG90** [comment]
Nope, directly just the images inside

**Comment by tibbi** [comment]
you can go in Settings -> Manage Excluded Folders and add the root folder "/", that will exclude everything. Then go in Manage Included Folders and add that particular folder you want to see. Then after toggling "Show all folders content" only the main folder content should appear. However, as I see the folder exclusion/inclusion doesnt work there and it still shows all folders, Ill have to fix it in the next version :p

**Comment by PG90** [comment]
how to do it programmatically ?

**Comment by tibbi** [comment]
in the MainActivity make sure `config.showAll` is true, then at GetDirectoriesAsynctask at `val media = context.getFilesFrom("", isPickImage, isPickVideo)` change the first empty string to the folder path you want to see.

**Comment by PG90** [comment]
Hi, appreciate your help.
I've done changes as you mentioned in previous reply but still getting all the images and videos from all directories as all.

**Comment by tibbi** [comment]
aha ok, then in GetMediaAsynctask's doInBackground change the `path` value to the path of the folder you want to see.

**Comment by PG90** [comment]
It's working now, 
Thanks man.

**Comment by PG90** [comment]
Hi, how to copy selected files to predefined directory with just one button click ?

**Comment by tibbi** [comment]
havent tested it, but at MediaAdapter try replacing the line 176 (activity.tryCopyMove...) with these 2 lines
val source = if (files[0].isFile) files[0].parent else files[0].absolutePath
activity.copyMoveFilesTo(files, source.trimEnd('/'), "my/destination", true, true) {

**Comment by PG90** [comment]
ok i'll test it and revert

**Comment by PG90** [comment]
App crashes with Screen exposed for less than 1000 ms. Event not sent

**Comment by PG90** [comment]
Hello, how to change default dark and light theme primary colors programatically ??

**Comment by tibbi** [comment]
In the "Customize colors" settings item? You cannot really do that, that screen is handled by the Simple Commons library.
