### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by Primokorn** [SimpleMobileTools/Simple-Gallery#352]
Hi there,

Some strings are missing so we can't translate.
e.g "Hide folder" from the 3-dot menu.

**Comment by tibbi** [comment]
Hey, many strings are reused between multiple apps, so to avoid duplicate translation they are stored in the commons library. You can find the French strings at https://github.com/SimpleMobileTools/Simple-Commons/blob/master/commons/src/main/res/values-fr/strings.xml . Thanks
