### ISSUE TITLE
Symbols disappear 

### ISSUE THREAD

**Issue by kaizoor** [SimpleMobileTools/Simple-Gallery#353]
When I view a picture the icons for share and delete an the other are shown for just a moment the they disappear. I also van not get it back with a simple click on the image. The same problem also for videos the timeline is only displayed once by opening then never again.
Android 7.1.2 LinageOS14.1

**Comment by sir-harlekin** [comment]
+1 on LOS 14.1

**Comment by tibbi** [comment]
Hey, can any of you please try the attached .apk file? 
To install the test version you first have to uninstall the current one, then allow installing apps from unknown sources in the security settings of your device. Once you run this file on your device it should be straightforward. Thanks https://www.dropbox.com/s/0ix4ij35ld9psm6/app-release.apk?dl=0

**Comment by tibbi** [comment]
or just try updating to 2.14.1 through playstore or soon f-droid, Ive published the latest build

**Comment by sir-harlekin** [comment]
Not working for me. Additionaly all system whide Touch Navigation (via GMD Touch App) ist deactivated too. So i cant even get out of full screen mode without pressing the physical home button.

**Comment by sir-harlekin** [comment]
I forgot to mention, even scrolling to the next Pictures does not make the controls reappear. So actually the situaton got worse.

**Comment by tibbi** [comment]
wow, so far everyone told that the latest update fixed the issues. You can get the older version at https://github.com/SimpleMobileTools/Simple-Gallery/releases , download some app-release.apk, you might want 2.13.4

**Comment by sir-harlekin** [comment]
I stand corrected, i messed up myself (it was 4 am where i live). I am sorry for misleading you and hope you will still accept my feedback in the future.

**Comment by tibbi** [comment]
so is it fixed, or not, or what? :)

**Comment by sir-harlekin** [comment]
Fixed. Thanks!

**Comment by tibbi** [comment]
alright, thanks :)
