### ISSUE TITLE
Image of width 4208px does not display when phone is in portrait (vertical) orientation

### ISSUE THREAD

**Issue by cassist** [SimpleMobileTools/Simple-Gallery#358]
When trying to display a horizontal 4208px wide image in vertical orientation, the resulting picture displays briefly (~1s) before disappearing. This does not happen with vertical images (3120px wide), nor does it happen with smaller resolution images (4000px wide). Rotating the 4208px wide image to vertical makes the image appear, as does rotating the phone to landscape orientation.

**Comment by tibbi** [comment]
retry with 2.14.2 please, once its available

**Comment by cassist** [comment]
issue does not return with 2.14.2, seems to be solved.
