### ISSUE TITLE
folder names

### ISSUE THREAD

**Issue by redojg** [SimpleMobileTools/Simple-Gallery#360]
possibilities to place the count of pictures the same row as filename and hide it
also hide the name
background for text - sometimes the first picture is the same color as text

**Comment by redojg** [comment]
also something for folders with same name like /f1/pics, /f2/pics

**Comment by pongalong** [comment]
Bump for this feature (hiding filenames on thumbnails)

**Comment by tibbi** [comment]
some customization has been added already, hiding filenames on thumbnails is there for ages at the top menu. They are actually hidden by default, guess you enabled them.
