### ISSUE TITLE
Give user an option to enable/disable fast scroll

### ISSUE THREAD

**Issue by ajyotirmay** [SimpleMobileTools/Simple-Gallery#362]
There are times when I accidentally use the fast scroll thumb. Which makes me retrace where I was. It will be nice to have an option to enable or disable the fast scroll from application settings.

**Comment by tibbi** [comment]
i dont really want to add such unnecessary settings. I will update it in a way that the handle itself can be dragged only, clicking elsewhere wont trigger fast scroll.

**Comment by ajyotirmay** [comment]
Thanks, I guess that will do the job. I guess you're trying to keep everything simple, like the name suggests, and that's why you're avoiding to add an extra settings option. That's totally fine.

**Comment by tibbi** [comment]
only the handle will be draggable from the next version, that should be the expected behaviour.
