### ISSUE TITLE
[Feature Request] Shortcut on Homescreen

### ISSUE THREAD

**Issue by symbolisch1234** [SimpleMobileTools/Simple-Gallery#363]
There is a picture that I especially like and I want to look at very often. I'd love to be able to add a shortcut to the homescreen which opens this picture immediately. I don't want the picture itself on the homescreen, like many "pictureframe" widgets, i want a link to the picture. If the icon is a thumb of the picture, great, but this is not necessary.

I don't quite know how Android Shortcuts/Widgets work, but if it is possible to make them folderable (can add them to a homescreen folder), this would be great. Alternatively add the option to link not to a picture, but to a Gallery folder.

Thanks a lot for the great app. Really like it.

**Comment by tibbi** [comment]
A shortcut to opening a folder will be added someday. Maybe opening a specific image too, who knows.

**Comment by Theobald93** [comment]
Workaround: Use a File Shortcut Widget App and choose the picture as file. Choose Simple Gallery as default picture app.

**Comment by tibbi** [comment]
folder widgets will be added in 6.1.0. Some additional features related to that and file widgets might come someday too.

**Comment by Diniodoc** [comment]
Hey great news thank you for adding that great feature!!!
But is it also possible to implement that folder widget as a normal shortcut to be able to stack them into a homescreen folder group? That would be fantastic.

**Comment by tibbi** [comment]
will be added in 6.7.1
