### ISSUE TITLE
Laggy image transitions in fullscreen since version 2.14.1 

### ISSUE THREAD

**Issue by haadr** [SimpleMobileTools/Simple-Gallery#367]
```
Android/OS: LineageOS 14.1, Build Nightly 22.05.17, Android 7.1
Phone: Moto G4 Plus
```

Hi and thanks for the best gallery app on F-Droid!

Since version 2.14.1 I often experience very long freezes when swiping back or forth through images (while in fullscreen mode I guess you'd call it). The best example of this is when I take a picture with my camera app (OpenCamera), tap to open the images and then when wanting to look backwards through the images swiping will hang midway through the sliding animation. The phone itself doesn't hang, just the gallery app. Sometimes when I wait long enough it will stop hanging on subsequent use, but when I take new pictures it hangs again. 

This has made using the app so inconvenient that I've downgraded to the previous version on F-Droid, which is 2.13.4, where this doesn't happen. I've tried upgrading again (uninstalling in-between) and it always happens again in version 2.14.1. 

So I just wanted to let you know, in case something related to the animations changed. Let me know if I can help debug in some way. 

Thanks for reading!

**Comment by tibbi** [comment]
Hey, if you could try this version it would be appreciated. Something have been improved, it should work better. Remove the ".zip" file extension, so the file is called "app-release.apk" (github doesnt allow uploading apk files). Thanks
[app-release.apk.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/1309105/app-release.apk.zip)

**Comment by haadr** [comment]
Thanks the quick response, that version seems to have fixed it for me! There's no more freezing when browsing new images, or browsing images that haven't been browsed before. 

There's still a slight lag spike every few images, but I think that's related to my relatively high image resolutions and/or the relatively slow CPU of the phone. It doesn't happen with small image resolutions/compressed images.

Thanks for investigating, definitely useable again!

**Comment by tibbi** [comment]
alright, Ill close it then so I wont forget. I will publish a new version 2.14.3 today, should get to f-droid in a couple days.
