### ISSUE TITLE
Feature to temporarily rotate images (display only) with a gesture

### ISSUE THREAD

**Issue by Ketrel** [SimpleMobileTools/Simple-Gallery#372]
I used to use Quickpic but dropped it when Cheetah Mobile 'acquired' it.

The one feature I'm missing is, separate from the phone orientation, you could use a two finger rotate gesture to rotate the image and it would snap to portrait/landscape orientation.  It was only for display, and didn't actually modify the image, and was only for that one viewing.  If you went off the pic to a different one, and back, it would be back to it's original orientation (based on the phone's orientation and rotation setting).

Would it be possible to add this? That's the one feature I'm missing.  I could take a video of the feature working in quickpic to demonstrate exactly how it worked.  I still have an old APK of it sitting around.

**Comment by tibbi** [comment]
Gestures will be added in the future, not sure when.
Regarding temporary rotation, it used to be like that, but people wanted instant save. So currently there is instant saving in case the image is a jpg and it is on the internal storage, in other cases you have to Save the rotated image manually (I couldnt do the instant saving for all cases). I plan adding a degree selection after pressing Rotate, but I dont really plan removing the instant save on places where its currently enabled.

**Comment by Ketrel** [comment]
Any possibility to have the instant save as an option.

I often need to rotate image to show them to someone, but I don't want to edit it, or mess up my sorting (which is always Date (descending)).  

I could even deal with lack of gestures entirely if it didn't save the image.

**Comment by tibbi** [comment]
Right, well I can remove the autosave then, as theres many reasons for it. Its currently inconsistent as it applies only in some cases, it updates the last modified date (Im actually modifying it myself in the code) and at least people wont be used to it when gestures arrive. I will release a new version in a couple days, guess it will be removed in it.

**Comment by Ketrel** [comment]
I can't speak for anyone else, but that is the behavior I'd be expecting.  Unless I click a save button or choose save from a menu, I'm always under the assumption that any change I make is purely visual.

**Comment by tibbi** [comment]
Autosave will be removed in the next version released soon. I will close this issue, gesture rotating is reported at #293

**Comment by JohnVeness** [comment]
Hello, this change that rotations aren't saved is a negative one for me. I often rotate photos that I've taken, and found the previous method most convenient, and liked it saving. Now I have to do several additional taps (going into edit and saving afterwards).

Maybe if the user rotates an image, then moves off it (pressing Back, or swiping to the next/prev image), the user would be asked if they want to save the change. If yes, it would save over the existing file, not bring go a Save As window, as it's not a major or destructive change.

**Comment by tibbi** [comment]
ye there are many users who are against every way of doing it. The fact is that I can instantly rotate and save only jpgs on the internal storage. If a file is on an SD card, or it is not a jpeg, he would have to save explicitly anyway. So for consistency I chose never to save automatically.
