### ISSUE TITLE
Did not delete pictures.

### ISSUE THREAD

**Issue by mrprole** [SimpleMobileTools/Simple-Gallery#375]
Hello. I am using Blackberry PRIV. When i am deleting pictures it is disappeared from gallery but after refreshing gallery picture is still present in gallery.

**Comment by tibbi** [comment]
Hey, what android version does it have? Is the image on an SD card? If it is, better backup your SD card as some people lost some photos there.

**Comment by mrprole** [comment]
I have noticed that it did not delete pictures only in storage/externalmemory/DCIM/Camera folder.

**Comment by mrprole** [comment]
Android 6.0.1. Yes, it is on SD card.

**Comment by tibbi** [comment]
Weird, so if you try creating a new folder on the SD card and delete some images from there, it works fine?

**Comment by mrprole** [comment]
Sorry. I was mistaken. It's not deleting in external memory. Only internal.

**Comment by tibbi** [comment]
Alright, can you send me an email at hello@simplemobiletools.com please, so I will send you a debug version of the app in a couple hours, which should help finding the issue? Thanks

**Comment by tibbi** [comment]
To be continued via email
