### ISSUE TITLE
Autoplay videos

### ISSUE THREAD

**Issue by SimpleGalleryFan** [SimpleMobileTools/Simple-Gallery#38]
First, thank you for sharing this program with us, it is great, I use it all the time! 

Could it be possible to add a way to autoplay videos? I.e. every time you swipe to advance to the next file, if it is a video it would autoplay it. 

I have some folders with many videos, and it is a bit cumbersome to have to press the play icon for each videos when looking for a specific one. 

Maybe you could do this as a toggle in the three dots menu?

**Comment by tibbi** [comment]
Hello, Ive put an autoplay toggle to the main Settings, just to not have these settings spread around the whole app.
