### ISSUE TITLE
Some gif files are showing as black while animate gif option is ON

### ISSUE THREAD

**Issue by jerryn70** [SimpleMobileTools/Simple-Gallery#384]
One my friend sent gif file in our whatsapp group but that gif file is not showing in gallery. If I turn off animate gif file option in the settings then it will show. For investigation i contacted him and he told that The gif file is download from pr_nhub.com .
So I downloaded some gif files from pr_nhub and giphy . All the gif from giphy is working well but files from pr_nhub is not .

**Comment by tibbi** [comment]
heh, do you have any gif to send me so I could reproduce it? Are you sure those gifs are actually fully downloaded on your device, dont require an internet connection of any kind?

**Comment by jerryn70** [comment]
yes the gif are fully downloaded and don't require internet. 
how do I sent ? email ?

**Comment by tibbi** [comment]
sure, hello@simplemobiletools.com

**Comment by jerryn70** [comment]
@tibbi ok i will sent you.
 friend remember the gif contains adult materials.

**Comment by jerryn70** [comment]
@tibbi  i have sent u the gif files plz check ur mail.

**Comment by tibbi** [comment]
Alright, Ive got it and I can reproduce it. Ill take a look at it some other time tho, it's not a high priority for now

**Comment by tibbi** [comment]
seems to be working fine already, since the gif rewrite
