### ISSUE TITLE
Can't chooce photo for contact

### ISSUE THREAD

**Issue by OLEG4120** [SimpleMobileTools/Simple-Gallery#389]
![output](https://user-images.githubusercontent.com/8065693/31507619-f2ae0d76-af83-11e7-8956-fc90f32f1b33.gif)

**Comment by tibbi** [comment]
What is your Android version? How about if you open the photo through the gallery directly, then use "Set as" and select "contact picture"? Does it work?

**Comment by OLEG4120** [comment]
Android 7.1.1, and moto G5S, and Android Emulator x86-64 api25
![output](https://user-images.githubusercontent.com/8065693/31511192-9cd5a254-af8f-11e7-884e-311a9567c2f1.gif)

No, it doesn't.

**Comment by OLEG4120** [comment]
On Android 6 it work fine

**Comment by tibbi** [comment]
retest with the latest version 3.1.0 please which will start rolling out soon. I fixed one thing that could potentially fix it

**Comment by OLEG4120** [comment]
Seems to be ok. 3.1.0 works fine.
