### ISSUE TITLE
Immersive mode

### ISSUE THREAD

**Issue by SimpleGalleryFan** [SimpleMobileTools/Simple-Gallery#39]
Could it be possible to add a way to send the app in immersive mode when browsing the pictures and videos of a folder? By immersive mode, I mean hiding the transparent button bar at the bottom of the screen, with the back, home and activities buttons. Or at least, a way to make the bottom bar disappear when you have taped on the screen to hide the file info, the tools icons, the status bar and the process bar for videos. This way, we would have a full screen viewing experience. 

Maybe by adding it as a toggle in the three dots menu?

**Comment by tibbi** [comment]
fullscreen view has been added ages ago
