### ISSUE TITLE
Show the date of the current scroll position

### ISSUE THREAD

**Issue by jaekyeom** [SimpleMobileTools/Simple-Gallery#391]
Showing the date of the current scroll position (e.g. the date of the picture being shown at the top) always or while scrolling, maybe depending on an option, would be nice.

Of course, only when the sorting is based on dates.

**Comment by tibbi** [comment]
if you mean scrolling via the fastscroller at the side, there will be some bubble showing the current value, depending on what are the files sorted by. If its date, it will show the date, if its size, it will show the size etc.

**Comment by tibbi** [comment]
this has been added some time ago already
