### ISSUE TITLE
Simple gallery is not picking up images that were transfered by another app

### ISSUE THREAD

**Issue by MeCias** [SimpleMobileTools/Simple-Gallery#397]
Hi,
I like Simple Gallery a lot and hope that is something that can get fixed. I use next to Simple gallery an app that is called folder sync. Folder sync synchronizes some content between my phone and a nextcloud setup. The synchronization works fine just simple gallery is not picking up the new pictures that got transferred from the cloud to the phone even if I use the manual refresh. As work around I go to the ES File explorer pro on my phone open the first image in that folder or a new copied folder and scroll the images through with the ES File Explorer own image viewer. Just then simple gallery is picking up the new images. If I go to the new image over ES file explorer and open the image directly via simple gallery I am able to open the one I picked but not able to swipe left or right because the other images are still not recognized by simple gallery.

**Comment by tibbi** [comment]
Hey, it seems like Folder sync is not adding the images in MediaStore properly. Check the settings, you might have something related to it there. Or just explicitly add the synced folder in the Included folders (through Settings -> Manage Included Folders), the images should appear then.

**Comment by MeCias** [comment]
Hi,

thanks for your response. I haven't had any issues with the picture app (Quick Pic) that I used before or at least I haven't noticed any missing pictures. Just checked the folder sync settings as well as the sync specific settings for the synchronization job, there is unfortunately nothing storage relevant just synchronization settings.
I will Include the folder as you wrote and will observe whether that has any positive effect on picking up the new images. Thanks a lot.

**Comment by tibbi** [comment]
ok, reopen it if its still broken
