### ISSUE TITLE
Support OTG via Android Storage Access Framework

### ISSUE THREAD

**Issue by heavy-matill** [SimpleMobileTools/Simple-Gallery#399]
From Android 6.0 to access external storage such as OTG, the app has to access data via Android Storage Access Framework or root access to  /mnt. Neither is the case for this app and it would be awesame if it was added, since it would make viewing, searching through and deleteing files on external thumb drive so much easier.

**Comment by tibbi** [comment]
OTG support has been added, report bugs individually in case you find some.
