### ISSUE TITLE
Display all pictures from all folders at once

### ISSUE THREAD

**Issue by Kratsac** [SimpleMobileTools/Simple-Gallery#40]
Is it possible to add a gallery including all pictures from all existing folders? Here, I would prefer to see them ordered chronologically. Thanks!

**Comment by efraletti** [comment]
I second this. Very few gallery apps feature something like this and they hang a lot, or are paid and have too many features like cloud sync and more bloat.
I tested extensively and am using one app that was the more manageable one, but seeing Simple-Gallery featuring all pictures view, as open source and centered on minimalism and performance, would be nice. Too bad it's java and I could only help in python.
Thanks in advance!

**Comment by tibbi** [comment]
will be added soonish :) Im slowly trying to convert all apps to kotlin, but gallery is still mostly in java indeed.

**Comment by tibbi** [comment]
Will be added in 1.47. The Show All mode (displaying both images and videos) will be a fully usable permanent mode, with custom sorting, Settings, About, Open Camera etc.
