### ISSUE TITLE
[Bug] "Out of memory error" when rotating and overwriting the original image on an external SD card. 

### ISSUE THREAD

**Issue by Hikari-chin** [SimpleMobileTools/Simple-Gallery#400]
Encountered this bug recently; when I rotate an image and try to save it over the original image (same name overwrite), Gallery tries for a few seconds then reports "Out of memory error" as a toast. This only happens when the image is on an external SD card, it does not occur if the file is on the internal storage of the device. Additionally, the images I tested it with were ~10MB or less on a 6GB RAM device, so I don't believe it is truly running out of memory. Additionally, the SD card is an EVO from Samsung.com, so I don't think the error could be from access time/read and write lag that'd you'd experience with cheaper/knockoff SD cards.

**Steps to reproduce:**

1. Put a PNG image (possibly large only, most of the ones I tested were 5-10MB) on an external SD card. 
2. Click the hamburger menu in the top right and choose "Rotate". 
3. Click the check mark in the top right, do not change the file name in the prompt that pops up. 
4. Confirm the overwrite.
5. Observe that it fails to save the image after a few seconds, reporting "Out of memory error" in a toast. 

Here are two images I got the error with. Fair warning, their content is a bit strange, but fornat-wise they are standard PNGs. 

* https://a.pomf.cat/gjevxt.png
* https://a.pomf.cat/mhecdx.png

**System info:**
* **Device:** Galaxy Note 8
* **Android Version:** 7.1.1 (August 2017)
* **Specs:** Snapdragon 835, 6GB RAM
* **Modified/rooted?:** No
* **Installed from:** F-Droid
* **App install location:** Internal storage

**Comment by tibbi** [comment]
Thanks for reporting, it happens to some people in some cases. 6GB ram on a device is purely a marketing thing, an app wont have more than around 100mb available anyway (maybe it is more on the latest devices).

**Comment by Hikari-chin** [comment]
Ah, I see. Thanks for acknowledging; I appreciate it.

**Comment by ltGuillaume** [comment]
Could you please consider just NOT recompressing the image when rotating, but just updating the EXIF tag? This way:
1. Rotating will be lossless
2. No need for "save as" (or optional), just overwrite directly after the user presses the check mark button
3. Faster
4. Most probably will fix memory issues

> exif.setTagValue(ExifInterface.TAG_ORIENTATION, newOrientationValue)
> exif.removeCompressedThumbnail() // Unless (most) image viewers DO adhere to the orientation tag for the thumbnail, too 
> exifInterface.saveAttributes();

**Comment by tibbi** [comment]
Thats what I wanted too, but I could modify EXIF only for files on the internal storage, not on an SD card. Also only .jpgs have exif, other file formats dont. So for consistency I disabled autosave after rotating and the user has to explicitly save the rotated file. It was a mess when some images had autosave, some didnt.

**Comment by ltGuillaume** [comment]
That's odd. I've been using the good ol' QuickPic v2.9.6 for ages and it does just that, also on SD cards. It even keeps the modification timestamp in tact.

Are/were there any logcat entries we can work with if you try this? Maybe we can figure this thing out.

**Comment by ltGuillaume** [comment]
Here's what I found online:
> Try adding `<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>` as well (AndroidManifest.xml)
https://stackoverflow.com/a/26893363

> Add checkSelfPermission() / requestPermissions() routine for this operation, too. Or **lower target SDK version to 22**. So basically this https://stackoverflow.com/a/41957460 with WRITE_EXTERNAL_STORAGE
https://stackoverflow.com/a/32636039

**Comment by tibbi** [comment]
I obviously have write permissions, SD card handling permissions too. Im definitely not going to downgrade the sdk version for any reasons, I will take a look at it again in the future.

**Comment by DMSalesman** [comment]
@Hikari-chin Funny seeing you here!

**Comment by tibbi** [comment]
retry with the latest version please, if it still occurs

**Comment by Hikari-chin** [comment]
@tibbi Retested with the latest version; can confirm the issue still occurs.

**Comment by maszek** [comment]
> Could you please consider just NOT recompressing the image when rotating, but just updating the EXIF tag? This way:

    Rotating will be lossless
    No need for "save as" (or optional), just overwrite directly after the user presses the check mark button
    Faster
    Most probably will fix memory issues

Makes sense to me and I understand that there are objections to this, but what about providing an option to users with preference for ItGuillaume's suggestion?

**Comment by tibbi** [comment]
it used to work like that on some images. Sadly I cannot modify EXIF values of images on SD cards and only jpgs have EXIF at all, other image types dont. Because of that I disabled autosave for all images to keep the behaviour consistent, which is the one of the main properties of all apps.

**Comment by travisfw** [comment]
> Sadly I cannot modify EXIF values of images on SD cards…

Why can't you?

**Comment by tibbi** [comment]
I mean the current way doesnt work, it has to be handled differently than at images on the internal storage. Ill take a look at it someday.

**Comment by tibbi** [comment]
rotating should be a lot more optimized in the next version 3.6.0, SD card part will be better on Android 7+ only
