### ISSUE TITLE
Private folder no longer visible

### ISSUE THREAD

**Issue by guushoekman** [SimpleMobileTools/Simple-Gallery#405]
After unlocking private mode, the content of the private folder are not visible. They were visible before, I think it has stopped working since version 2.15.1.

[More info on private mode](https://www.androidcentral.com/understanding-private-mode-samsung-galaxy-s6).

**Comment by guushoekman** [comment]
Was wondering if this something you are planning on fixing? Oddly enough it was working fine before. Would love to know, I've switched gallery viewers for this but would prefer to switch back.

**Comment by tibbi** [comment]
To avoid some issues Im explicitly checking if a file is on the internal storage or SD card, guess Private folder is somewhere else. I don't have any Samsungs for testing, so I don't think it will be fixed anytime soon.

**Comment by guushoekman** [comment]
When available, the private folder shows up alongside of the internal storage and the SD card. It's a folder simply named `Private`.

![Screenshot](http://i.imgur.com/TBUdjtW.png)

Very understandable you won't be able to fix it without a Samsung.

If there are others who also face this problem: an open source gallery app that _does_ show images in this folder is Camera Roll ([F-Droid](https://f-droid.org/packages/us.koller.cameraroll/), [Google Play](https://play.google.com/store/apps/details?id=us.koller.cameraroll))

**Comment by tibbi** [comment]
some things have been changed, this might work already

**Comment by guushoekman** [comment]
Works great! Thanks a lot for the fix!
