### ISSUE TITLE
Can't delete photos from SD card

### ISSUE THREAD

**Issue by juoza** [SimpleMobileTools/Simple-Gallery#412]
Hey,
I just put new 64GB sd card and even though all the permissions are granted for app - i still can't delete photos with simple gallery from sd. With other apps i could delete them without any problem. Also with old sd card (32GB) i didnt have this issue but i think it might be updates related as i think it was working with the new one for few days too.. Not sure anymore. 

Any ideas?

Simple gallery v 2.16.1
Android 7.1.1
Phone Sony F8131

Thanks!

**Comment by tibbi** [comment]
Hey, try finding the app in your device settings and use "Clear Data". It will reset the SD card path and reobtain it, it wont delete any images. If I understand correctly you replaced the SD card in the same device, which Im not handling in any way yet. Thanks

**Comment by juoza** [comment]
It helped! Thanks! Yep, i was replacing sd in the same device. Thanks for great ad free app!
