### ISSUE TITLE
Animated PNG (APNG) support

### ISSUE THREAD

**Issue by Hikari-chin** [SimpleMobileTools/Simple-Gallery#418]
Currently, Gallery displays APNGs as static PNGs (and is slower to load them than regular PNGs, maybe because it's trying to understand the additional animation chunks). It would be nice to see APNG support if possible. Here's some documentation/examples:

* [Overview of APNG](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/APNG)
* [APNG technical specification sheet](https://wiki.mozilla.org/APNG_Specification)
* [Sample APNG reader in Java](https://github.com/openmicroscopy/bioformats/blob/develop/components/formats-bsd/src/loci/formats/in/APNGReader.java)
* [Sample APNG writer in Java](https://github.com/openmicroscopy/bioformats/blob/develop/components/formats-bsd/src/loci/formats/out/APNGWriter.java)
* [APNG encoder in JavaScript](https://github.com/GraFlic/GraFlic)
* [APNG reader in Java with explicit Android support](https://github.com/aellerton/japng)
* [APNG viewer in Java written explicitly for Android](https://github.com/sahasbhop/apng-view)

**Comment by tibbi** [comment]
will be added someday, it is a duplicate of #93

**Comment by Hikari-chin** [comment]
Ah, okay. Thank you!
