### ISSUE TITLE
Show images in folder-based fashion

### ISSUE THREAD

**Issue by pintergreg** [SimpleMobileTools/Simple-Gallery#42]
I'd have a feature request of showing image based on folders.
I like manage image files in folders and viewing them in (filename) order. Most of the image viewer does not support things like this, starting with the stock image viewer app.
At least I would be pleased to see a feature like this even if it only works with Simple File Manager.
(The only known solution is at the moment Ghost Commander, that has an image viewer functionality)
Thanks for considering this.

**Comment by tibbi** [comment]
a list view has been added in 2.15.0, it should be good enough
