### ISSUE TITLE
Loading circle is too fast.

### ISSUE THREAD

**Issue by OffifialMITX** [SimpleMobileTools/Simple-Gallery#429]
Tha loading indicator goes crazy since the last update.

**Comment by tibbi** [comment]
You mean the top spinner is spinning too fast? What Android version do you have?

**Comment by Phoenix1747** [comment]
Can't confirm this issue with Android 7.0

**Comment by OffifialMITX** [comment]
5.1 with a screen of 480x854.

On November 1, 2017 8:41:37 PM GMT+01:00, Tibor Kaputa <notifications@github.com> wrote:
>You mean the top spinner is spinning too fast? What Android version do
>you have?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Gallery/issues/429#issuecomment-341216770

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by tibbi** [comment]
I dont see any attachment, try sending it to hello@simplemobiletools.com. Thanks

**Comment by tibbi** [comment]
I guess it is ok already, reopen if it is still broken on with app version 6.0.1

**Comment by OffifialMITX** [comment]
Oh, sorry, I got a new device and somehow lost track of this issue. Now, technically, the issue does not continue anymore on my Android 7 with v6.0.0. Now it doesn't move at all.

I figured out, however, that it is caused by the Animator Scale that I set to off in developer settings.

**Comment by OffifialMITX** [comment]
(That usually replaces the moving line with an arrow, but that isn't the case with that exact loading indicator, across most apps)
