### ISSUE TITLE
Auto rotate device orientation sensitivity is very high

### ISSUE THREAD

**Issue by jerryn70** [SimpleMobileTools/Simple-Gallery#441]
The sensitivity is too high and very annoying mostly when watching videos . The old sensitivity level was perfect.

**Comment by tibbi** [comment]
I lowered it a bit, also added a "Lock orientation" actionmenu button.

**Comment by jerryn70** [comment]
@tibbi is it possible to add lock button on the screen ? Like below  ![](https://i.imgur.com/rXOj9Oo.png)

**Comment by tibbi** [comment]
I dont have any of those buttons there, maybe once I redesign the screens

**Comment by jerryn70** [comment]
I mean we just need that lock button only, to lock/unlock orientation
