### ISSUE TITLE
Request to to implement a background service

### ISSUE THREAD

**Issue by alpenblauwtje** [SimpleMobileTools/Simple-Gallery#444]
I know this is a strange feature request: please do *not* implement a background service to e.g. monitor internal memory or SD card for changes. Adding background services is one of the main reasons I moved away from QuickPic and Piktures. Fortunately SG is an excellent lightwight replacement! Please keep it that way.
Now you can close this issue :-)

**Comment by tibbi** [comment]
im not doing anything in the background, dont worry :)
