### ISSUE TITLE
Simple Gallery offers to open .webm files

### ISSUE THREAD

**Issue by Zero3** [SimpleMobileTools/Simple-Gallery#457]
When opening an .webm file from another app, Simple Gallery offers itself as an option. But when opening with Simple Gallery, nothing happens. It simply shows the last opened picture like if I manually open Simple Gallery from my home screen.

This particular .webm file only contains an audio track, and no video. Not sure if it is relevant to the issue.

**Comment by floppyD** [comment]
Bumping this, it works now, but the behavior is still kinda weird.
https://youtu.be/ecCc3xbOMYs

**Comment by tibbi** [comment]
well the app is offline, so dont expect playing webm files. I would have to specify every file format to be opened to fix this.

**Comment by floppyD** [comment]
I don't get it, what being offline has to do with it? I have tried other gallery apps and players and they open just fine, only Simple Gallery gets stuck on this black screen for a while.

**Comment by tibbi** [comment]
thought that it needs internet permission. But since Im displaying those videos, that cannot be the case eh.

**Comment by floppyD** [comment]
Yeah, common misconception. WebM is just a container for VP8/VP9 + Vorbis/Opus, it has nothing to do with web other than the fact Google created it to use on their pages and be a replacement for things like .gif

**Comment by tibbi** [comment]
it works fine to me. If it breaks for a particular file, please send it to me, maybe I can reproduce it

**Comment by floppyD** [comment]
Sorry, I just noticed I never replied. I think the issue wasn't related to .webm files, but to the 1000+ files folder I was using. Or maybe it was fixed, because it doesn't happen anymore.

**Comment by BraINstinct0** [comment]
Case closed?

**Comment by Zero3** [comment]
I tested an audio only .webm file today with the latest version of Simple Gallery Pro, and it seems to work fine now. So to the best of my knowledge, this issue has been resolved :).
