### ISSUE TITLE
"Included folders" no longer scans recursively since 2.15.0

### ISSUE THREAD

**Issue by Mar2ck** [SimpleMobileTools/Simple-Gallery#458]
I have a folder with many sub-folders which contain content. Since the folder is located in the root filesystem and has .nomedia applied to it, it isnt picked up by Gallery normally so adding it to "Included folders" would make all contents appear normally. I can confirm this worked last on 2.14.4.
Starting with 2.15.0 and onwards, adding the folder now makes nothing appear and the only way to access these folders is to add each individually including all the folders they contain which is a massive pain.
I've tried removing .nomedia which made QuickPic start recognising it but Gallery still doesn't.

**Comment by tibbi** [comment]
Included folders works recursively, there must be those .nomedia files causing the issues.

**Comment by Mar2ck** [comment]
I've tried removing all .nomedia files and still the same problem. Maybe it's an issue with it being in root?

**Comment by tibbi** [comment]
aha, I didnt notice it is in root, that could be the issue. Why on earth you have a folder with images there?

**Comment by Mar2ck** [comment]
It's because i store my photos in a fuse filesystem (for encryption and syncing with my computer) and you can't mount them to the internal or external storages annoyingly so I have to have it in root. It acts identically to any other folder in root though and like i said this used to work on past versions.

**Comment by tibbi** [comment]
aha, well there have been some structural changes related to performance, Im checking just sd card and internal storage now. I dont really think your issue will be fixed anytime soon as root folders require different handling.

**Comment by tibbi** [comment]
my bad, include should really be recursive from 3.5.0 only, I was mistaken by something there

**Comment by Mar2ck** [comment]
Thanks for fixing, ill test when the update comes to fdroid

**Comment by Mar2ck** [comment]
Just got the update on google play and it seems to work perfectly :)
