### ISSUE TITLE
Some (random) pictures just missing from SimpleGallery

### ISSUE THREAD

**Issue by Avispa** [SimpleMobileTools/Simple-Gallery#462]
I cannot really tell anymore but maybe with version 2.16.0 but maybe earlier (from *F-Droid*) it started that some (random) pictures just went missing in *SimpleGallery*. Currently I am on 2.17.3. In the first place I thought I just missed the shot button on the photo app for example so I was wondering but not really worried but when I lately copied the files from the phone to the computer I found all the pictures which I didn't and still don't see in *SimpleGallery* evidently.

Already before version 2.17.3 it happened to me that about 4.000 (4k) old pictures disappeared suddenly and only a few of the newest ones where shown but the issue disappeared with an update. (Sadly I don't know anymore which version but however the problem seems to persist anyway even though with a smaller impact.)

**Comment by tibbi** [comment]
Is it random images from a particular folder missing, or random folders? Dont they just have some weird extension? Were those missing files on an SD card? What Android OS version do you have? Thanks

**Comment by Avispa** [comment]
Those files are on the SD card and are photos captures with the camera app so the naming is just the date with the reglar JPEG extension. So they are random files form the same folder.

**Comment by tibbi** [comment]
Heh, well it will be hard to figure out the issue like this. There used to be a bug where someone just tried deleting a single image on an SD card and either the whole SD card got wiped, or a whole folder. Not some random images. Sadly F-droid is slacking at publishing latest app versions. Version 2.18.0 is out for 8 days already, they still havent updated it. There hasnt been any updates related to it anyway, but being on the latest version is always a good thing.

**Comment by Avispa** [comment]
> There used to be a bug where someone just tried deleting a single image on an SD card and either the whole SD card got wiped, or a whole folder.
Let me clarify just in case: the files are not deleted, they are just not listed/recognized by *SimpleGallery*. The actually file system is fine (for an android system ;) ).

**Comment by tibbi** [comment]
Aha, can you maybe try renaming the folder (preferably through a pc)? The items might get rescaned and shown properly. Can you test some other gallery, if it works fine? Thanks

**Comment by Avispa** [comment]
Took me a while to figure out the ignored pictures but I checked with another image viewer app and in * LeafPic* for example it is perfectly fine. For whatever reason pictures from Okt. 26. are missing partly (but continously / a burst).
I'm sorry but because of the never fixed bug in the Android file system handling I don't wanna rename the folder and risk to rune the time stamps of the files. However I hope the above information is somehow helpful.

**Comment by Avispa** [comment]
Updated with F-Droid to version 3.0.1 and error persists. Already/even the counter of the directory states wrong:

- *SimpleGallery*: 5033 files
- *LeafPic*: 5058 files

So *SimpleGallery* is off of 25 files. Also I checked with *Amaze* file manager and there are 5058 files (+1 hidden directory `.OutFocus`). EVEN your *SimpleFileManager* knows better and also states 5059 files (remind the one directory)!

**Comment by tibbi** [comment]
Guess you can manually include the folder through Settings -> Manage included folders. That way the folder will be scanned more throughtfully and probably find the missing images. The Gallery also has some validity checks with other apps might not have to make sure I show just the valid files, but I dont think that will be the issue now as the file manager displays all of them.

**Comment by tibbi** [comment]
should be better in 3.4.0
