### ISSUE TITLE
Open videos with external player 

### ISSUE THREAD

**Issue by Wiredframe** [SimpleMobileTools/Simple-Gallery#466]
Please add an option to play a video in an external video player like there is in the thumbnails view. In the fullscreen preview it's missing unfortunately.

Thanks!

**Comment by tibbi** [comment]
there is an "Open With" button at fullscreen media, both images and videos. As I see it is currently crashing on my device, but that's a different issue ;)

**Comment by Wiredframe** [comment]
That doesn't solve the issue unfortunately and is also inconsistent. Please make a persistent option to open videos in an external player. 👍

**Comment by tibbi** [comment]
why doesnt it solve the issue? And why isnt it inconsistent? As you click on a video at the thumbnails view, you should see a list of apps capable of playing the video. If you dont see a list of apps but some app opens by default, find that app in the device settings and do a "Clear Defaults". That should make the list show up and you can select an app for playing videos.

**Comment by Wiredframe** [comment]
I just say that it would be nice to always open a video in an external player both in the overview and detail view. Right now it's inconsistent. Thanks :)

**Comment by tibbi** [comment]
I dont plan opening a third party app when swiping on a video, the UX would be terrible.

**Comment by Rikk** [comment]
+1
