### ISSUE TITLE
Cannot zoom an image after rotating

### ISSUE THREAD

**Issue by JohnVeness** [SimpleMobileTools/Simple-Gallery#468]
After rotating an image (e.g. 90 degrees right) using the toolbar icon, I can no longer zoom the image using two fingers.

**Comment by tibbi** [comment]
Im aware of it so Ill mark it as a bug, but don't really expect being it fixed anytime soon. The rotation is already messed in some cases, I dont want to mess it up even more :)

**Comment by tibbi** [comment]
simple zoom has been added after rotating, the more advanced zoom wont really be added. Should be good enough.
