### ISSUE TITLE
THe picture does not shows details after a zoom

### ISSUE THREAD

**Issue by Janaue** [SimpleMobileTools/Simple-Gallery#469]
My device is samsung s2 running lineage 14 modded by micro-g team. I take this picture
https://abload.de/img/img_20171122_101256gksmx.jpg

but when I zoom in the application com.simplemobiletools.gallery version 2.18.1, installed with YALP STORE, I get this blurry thing, 
https://abload.de/img/screenshot_20171122-1n0se0.png

whereas the other application of gallery, like the AOSP gallery,  quick pic or the gallery from the application SNAP camera, shows very well the words.

I put the original picture on a more recent phone, running the latest resurection remix for nougat, with your application installed, and the words are visible.

**Comment by tibbi** [comment]
it should be better with the new version released soon. The image quality might be lower in general, but zooming should work properly.

**Comment by Janaue** [comment]
with version 2.19, I can see the words in the picture.

**Comment by tibbi** [comment]
okay :)
