### ISSUE TITLE
Feature idea: read-only when pinned

### ISSUE THREAD

**Issue by hcgraf** [SimpleMobileTools/Simple-Gallery#471]
Hi,

I'm looking for a gallery app that locks any write access when pinned (for pinning, see e.g. here: https://www.addictivetips.com/android/pin-and-unpin-screens-in-android-lollipop/)

It's basically to give the gallery to children or "technically-unaware" people without any risk.
When pinned, the app should basically prevent:
* Deletion
* Any persistent modification
* Sharing
* Changing settings

Do you think that's possible (I'm unsure if pinning can be detected)? 
Would that be a reasonable feature for this app?

Thanks
Hagen

**Comment by tibbi** [comment]
Hey, Im not sure about that behaviour, would have to research. Dont really expect it being implemented anytime soon tho.

**Comment by hcgraf** [comment]
Thanks for the fast feedback.
I was just surprised by the fact that there doesn't seem to be a "read-only" gallery out there.
So I just wanted to give the idea to the OSS community to avoid forgetting it :)

**Comment by tibbi** [comment]
I actually dont want to mix 2 whole separate features. Read-only mode might be added someday, you can already password protect file deleting/move.
