### ISSUE TITLE
Play videos into inbuilt player

### ISSUE THREAD

**Issue by PG90** [SimpleMobileTools/Simple-Gallery#474]
In this when we click on any video, then it opens into system default player not into the app inbuilt player.

So how to play videos into App's inbuilt player everytime user clicks on video?

**Comment by tibbi** [comment]
You have to find the system default player in the Device settings, then use the "Clear Defaults" button. After that once you try opening a video, it will ask which player you want to use.

**Comment by PG90** [comment]
Is there any way we can do it programatically ? And why the inbuilt player doesn't support MKV video format ?

**Comment by tibbi** [comment]
If you told your device to always which video player should be used by default, I dont want to constantly show the player picker, that is bad user experience. Mkv should be supported well, what happens in your case? Is it stuck with a black screen?

**Comment by PG90** [comment]
Yes, MKV file stuck with a black screen

**Comment by PG90** [comment]
Everytime MKV video stuck with a back screen.

**Comment by tibbi** [comment]
ok thanks, Ive created a new issue https://github.com/SimpleMobileTools/Simple-Gallery/issues/475 for it, I will take a look at it someday.
