### ISSUE TITLE
Wrong header bar color in recent apps view

### ISSUE THREAD

**Issue by Jiack214** [SimpleMobileTools/Simple-Gallery#476]
I think that the header bar in the recent apps view should change color according to the app theme.
Currently opening the recent apps view on Android, Simple-Gallery has an orange bar though the primary color selected is another one.

**Comment by tibbi** [comment]
ye thats correct. It affects all apps, it is already reported at https://github.com/SimpleMobileTools/General-Discussion/issues/29 .  With the current level of customization it wasnt possible to do. Im already working on a bit limited of selection of Primary Color, which will properly affect the color everywhere.
