### ISSUE TITLE
[Bug] Menu items inaccessible at full screen when in immersive mode (status and navbar hidden)

### ISSUE THREAD

**Issue by yuukieve** [SimpleMobileTools/Simple-Gallery#477]
Just noticed this small bug. If you have immersive mode enabled and go to view an image, tapping on the screen will not bring up Gallery's UI buttons like it typically does, instead, nothing will happen. The only way to rectify this is to pull down to show the hidden status bar for a few seconds, then tap and Gallery will show its UI as expected. 

**Reproduction steps:**
1. Enable immersive mode. I did this on my Galaxy Note8 by doing `adb shell settings put global policy_control immersive.status=*` to hide the status bar and tapping the far left navbar dot to hide the navigation bar. I believe the latter is a Samsung feature, if you don't have this option you can do `adb shell settings put global policy_control immersive.navigation=*` to also hide the navbar or `adb shell settings put global policy_control immersive.full=*` to hide the status and navbar at the same time. 
1. Navigate to any image, tap on the screen to try to display Gallery's three-dot menu, share/rotate icon/etc. Observe that nothing happens.

**Comment by TBuryanek** [comment]
Wanted to report this bug too.

**Steps to reproduce (basically same):**
- immersive mode ON (done by ADB command)
- open any photo
- one tap it to show fullscreen (hides **top Gallery menu** - back arrow, name of file, trash bin, rotate and three dot)
- so far so good
- BUG => one tap should show **this Gallery menu**, but does nothing <=
- without immersive mode I can hide/display this menu by single tap on photo

I have hardware navigation buttons (S7) not like Hikari-chin with software nav. buttons (S8).

I will try to look in code, but I am just very little experienced in Android development. If anybody knows better, I can at least offer testing :-)

**Comment by yuukieve** [comment]
This has been fixed, closing.
