### ISSUE TITLE
Add an option to disable vibrating at pin entering

### ISSUE THREAD

**Issue by tibbi** [SimpleMobileTools/Simple-Gallery#479]

**Comment by tibbi** [comment]
changed vibrating to haptic feedback for now, should be enough

**Comment by Marvinoo** [comment]
Can you please add the option in setting to allow disabling the vibrating when drawing the security pattern? PLEASE! it's very annoying and I cannot disable it!!

**Comment by puppykickr** [comment]
@Marvinoo 
I believe this is a setting on your device, not within the app.

It is called 'haptic feedback' and can be turned off somewhere inside the Settings for your device.

I also don't like it, and I have it off for my entire device, and have never had any vibration when entering a PIN while using this app.

**Comment by Marvinoo** [comment]
> 
> 
> @Marvinoo
> I believe this is a setting on your device, not within the app.
> 
> It is called 'haptic feedback' and can be turned off somewhere inside the Settings for your device.
> 
> I also don't like it, and I have it off for my entire device, and have never had any vibration when entering a PIN while using this app.

I turned off this option an all the apps and system don't make any vibrations except Gallery Pro and I still cannot turn it off :( 
Here's the Rom I use 
https://forum.xda-developers.com/t/rom-10-0-0_r50-resurrection-remix-os-v8-6-6-unofficial-hlte-chn-kor-tmo.4166595/
