### ISSUE TITLE
Immersive mode on the whole app

### ISSUE THREAD

**Issue by marciozomb13** [SimpleMobileTools/Simple-Gallery#492]
I know there's an option to enable full screen when opening media but I can't figure why not immerse the whole app giving a more pleasant experience?

**Comment by tibbi** [comment]
you mean hiding the top status and navigation bar in the whole app, or what exactly?

**Comment by marciozomb13** [comment]
I mean hide status bar in the whole app and hide both navigation and status bars on media viewing.

**Comment by tibbi** [comment]
I dont really want to hide anything more in the app as I hate that behaviour, and at fullscreen media viewing I guess those are hidden properly already.
