### ISSUE TITLE
Error  building ( converting bytecode to dex Multiple dex files define )

### ISSUE THREAD

**Issue by blue4603** [SimpleMobileTools/Simple-Gallery#506]
Hi,

I downloaded the project and opened it in android studio and when i build the project the following error message appears

![capture](https://user-images.githubusercontent.com/2857429/34078274-ebe53956-e327-11e7-8f10-3ce01b674f02.PNG)

Could anyone please help me with this issue.

Thank you
Regards

**Comment by tibbi** [comment]
Hey, nto sure, I never had that. Are you using Android Studio 3?

**Comment by blue4603** [comment]
yes i am using android studio 3.0.1

**Comment by tibbi** [comment]
Try doing a Build -> Clean Project and also a File -> Invalidate Caches/Restart

**Comment by blue4603** [comment]
Still it has some issues
![capture](https://user-images.githubusercontent.com/2857429/34078634-085690ba-e32f-11e7-8038-9988b3124b4b.PNG)

**Comment by tibbi** [comment]
What Android OS version are you building it for? Some real device, or emulator?

**Comment by blue4603** [comment]
both actually
![capture](https://user-images.githubusercontent.com/2857429/34078746-58940164-e331-11e7-94b9-6bd2afcb1d36.PNG)

**Comment by tibbi** [comment]
It must be something on your side. Maybe try building other apps from the suite, if they work fine.

**Comment by blue4603** [comment]
Ok. No problem I will try another one and report back.

**Comment by blue4603** [comment]
So I tried both the simple note and simple file manager. They both build and work fine.

**Comment by tibbi** [comment]
try for example the Calendar, that has multidex enabled too

**Comment by blue4603** [comment]
I tried simple calendar and it is building and working just fine.

**Comment by tibbi** [comment]
heh, not sure. Have you done anything to the project after cloning? Maybe try deleting the whole thing and clone it again.

**Comment by blue4603** [comment]
Nope I didnt change anything. I deleted the project and tried again and still the same issue.

**Comment by ohmerhe** [comment]
I receive the same error,  and the issue #460 maybe the same problem.
From the error info, both of org.apache.commons:commons-io:1.3.2 and commons-io:commons-io:1.3.2 have the same file EmptyFileFilter.

![image](https://user-images.githubusercontent.com/2901935/34326815-ce02a418-e8f0-11e7-91cc-c237acf00fc4.png)

**Comment by tibbi** [comment]
I dont think theres anything I can do about it so Ill close it.

**Comment by trubitsyn** [comment]
I managed to fix this by enabling ProGuard in debug builds a couple of days ago. Not sure whether that's worth enabling in the master branch.

**Comment by tibbi** [comment]
no I dont want proguard in debugging

**Comment by wizdom13** [comment]
I fixed this issue by adding the bellow code in the app build.gralde just before the dependencies.

configurations.all {
resolutionStrategy.dependencySubstitution {
substitute module('org.apache.commons:commons-io:1.3.2') with module('commons-io:commons-io:1.3.2')
}
}

**Comment by gh123man** [comment]
@wizdom13 This also fixes the issue for me.

**Comment by relan** [comment]
Hi,

F-Droid maintainer here. We have this error too: https://f-droid.org/wiki/page/com.simplemobiletools.gallery/lastbuild_155

I tried Gradle 4.4.1 and it solved this issue. F-Droid uses Gradle 4.1 because it's specified in the distribution URL: https://github.com/SimpleMobileTools/Simple-Gallery/blob/3.2.2/gradle/wrapper/gradle-wrapper.properties#L6

@tibbi, could you upgrade Gradle wrapper to 4.4.1?

**Comment by tibbi** [comment]
ah sure, I updated it and released 3.2.3. Thanks

**Comment by relan** [comment]
3.2.3 builds and works just fine, thank you!
