### ISSUE TITLE
Add pictures for f-droid

### ISSUE THREAD

**Issue by blacklight447** [SimpleMobileTools/Simple-Gallery#507]
Since F-droid 1.0, it is now possible to have screenshots displayed of the apps in the repos, I think it would be a good idea to add them to your repo so they can be included in F-droid.
Below you can see some examples of two apps which have already implemented this.

This is Courier:
![whatsapp image 2017-12-19 at 10 18 12 am 1](https://user-images.githubusercontent.com/19261543/34149671-1faed2fe-e4a6-11e7-9c86-2d4738795335.jpeg)
This is Orbot:
![whatsapp image 2017-12-19 at 10 18 12 am](https://user-images.githubusercontent.com/19261543/34149681-250af660-e4a6-11e7-89f0-f2bcf2733ccd.jpeg)

This way, people can have an idea of how the app looks. This will also be a good idea for your other apps, but I will only open an issue here for now so the discussion only has take place, what do you think?

**Comment by tibbi** [comment]
ye I can add it someday. I want to update the app screenshots in general, but it isnt a priority right now so not sure when will I get there. You can move the issue at https://github.com/SimpleMobileTools/General-Discussion/issues , as it affects all apps. Thanks

**Comment by blacklight447** [comment]
I see, Ihave it posted in the general discussion repo and will now close this one.
