### ISSUE TITLE
It takes hours to show folders after install, and takes minutes to open any folder

### ISSUE THREAD

**Issue by onfuryhs** [SimpleMobileTools/Simple-Gallery#510]
Stock 7.1.2, rooted with Magisk 14.0 and Xposed systemless v89.0 installed as a Magisk module.

Simple filemanager works properly, and other gallery apps run normally. After installing Simple Gallery from Google play store and opening it, the gallery shows only blank interface. I just swiped out and about 2 hrs later, all the folders containing pics showed up. But any operation takes hours to take effect, ajusting setting won't help.

**Comment by tibbi** [comment]
Heh, do you have some extra huge amount of photos on your device? A folder with just a few photos is slow to open too? Can you check Settings -> Manage Included/Excluded folders to see, if you have any items there? You will probably have ".../data" in the excluded ones, anything else?

**Comment by onfuryhs** [comment]
Started with initial settings and about 3,000 pics detected together, 'Excluded folders' won't take effect even after reboot.

**Comment by tibbi** [comment]
is that photo on an SD card, or internal storage? Or it doesnt matter?

**Comment by onfuryhs** [comment]
No SD card slot, everything's on internal storage. The 'SD card' folder is emulated.

**Comment by tibbi** [comment]
can you retest with the latest version 3.1.2 please? Some things have been optimized recently. Thanks

**Comment by RenaKunisaki** [comment]
After I added thousands of images over ADB, it took a long time for them to appear in the gallery. But now that they're there, it works fast again.

Possible difference being that I copied them all over from another phone, so it didn't have to rebuild thumbnails?

**Comment by tibbi** [comment]
thumbnails are cached on the device itself, it isnt related

**Comment by tibbi** [comment]
should be faster on 3.7.0, I rewrote some things
