### ISSUE TITLE
About PIN Lock

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [SimpleMobileTools/Simple-Gallery#511]
The app automatically opens the moment the right PIN is entered. It'd be better if user has to tap the check icon after entering the pin. More cumbersome for someone trying to open the app by fluke.

What will be even better is a scrambled layout of the keypad every time the app is opened!

30 minute time lock after 3 or 5 no. of failed attempts.

**Comment by tibbi** [comment]
I dont really want to make it so complicated, its not a super secure thing anyway since you can reset it by clearing app data. If you need more security, you'd better just lock your whole device.

**Comment by iknownothingaboutcomputers** [comment]
Sorry. I forgot the name of the app is SIMPLE Gallery. :)

**Comment by tibbi** [comment]
Yea, Im trying to focus on features that are used by the vast majority of people. Locking the app is already more than I wanted to do, but whatever :)
