### ISSUE TITLE
Buggy Action Bar

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [SimpleMobileTools/Simple-Gallery#512]
Open an image in Simple Gallery and the action bar shows up on top. It disapears after tapping anywhere on the image. But after tapping again on the image it doesn't reappear. Have to open the image again to get those options. This is a bug.

**Comment by tibbi** [comment]
what Android OS version do you have? It might be glitchy on Android 4 as that has fullscreen handled weirdly.

**Comment by iknownothingaboutcomputers** [comment]
Android 5.1. 

If it's OS-related then nvm what I said.

**Comment by tibbi** [comment]
Android 5 should work fine, even tho I dont have such device. Click handling needs some improvements anyway. What app version do you have? It's at the bottom of the About page.

**Comment by iknownothingaboutcomputers** [comment]
@tibbi 3.0.1

**Comment by tibbi** [comment]
should work fine already
