### ISSUE TITLE
Directory/folder get split into two when viewed with Simple-Gallery

### ISSUE THREAD

**Issue by onmyouji** [SimpleMobileTools/Simple-Gallery#52]
Hi there, I'd like to report a bug.

I have one directory named "Owen", there are 6 pictures inside. When I open Simple-Gallery, it shows two directory: "Owen" and "owen", with 3 pictures in each directory.

Not sure what causes this, other image viewer that I use don't have this problem.

**Comment by tibbi** [comment]
Hello, can you check with the latest version, 1.34? Thanks!

**Comment by onmyouji** [comment]
It's still the same, I've tried to uninstall and reinstall.

I also tried to rename the folder using a file manager app, it doesn't get updated on Simple-Gallery. It still display two folder.

**Comment by tibbi** [comment]
then maybe its indeed folders in different places? Can you try opening the folder, long pressing some items and checking the full paths? If they differ.
