### ISSUE TITLE
[Feature Request]  Lock folders from being accidentally deleted

### ISSUE THREAD

**Issue by 2SI3NX** [SimpleMobileTools/Simple-Gallery#531]
Is it possible you can add an option that can allow the user to lock all folders from being deleted to protect from accidental deletion?

ie.  The photos inside the gallery can be deleted one by one, but the option should safe guard the user to mistakenly delete the whole folder, as some people i know that are using Simple Gallery mistakenly delete the WHOLE folder because they wanted to delete a single photo.

Unless you are willing to allow to change the folder cover as a Folder Icon instead of showing the last actual photo as the folder cover.

Maybe both of these should be considered?

1. Being able to change the Folder Cover as a Folder Icon instead of last photo in the folder as a folder cover.
2. Being able to lock folders from being accidentally deleted.

Much love for your app

**Comment by tibbi** [comment]
1. you can already change the folder cover, even tho only to some different image with long pressing -> Change cover image.
2. there is already a confirmation dialog for a reason, I dont want to add any more protection

**Comment by 2SI3NX** [comment]
I wasnt aware of the Cover change option, thanks
