### ISSUE TITLE
Show progress indicator while copy/moving files

### ISSUE THREAD

**Issue by maulwuff** [SimpleMobileTools/Simple-Gallery#547]
I copied a bunch of videos from one folder to another (internal to sdcard), but there is no progress indicator or anything while the app is working. I thought it failed to copy, so I started a file manager and was happy to see one file after the other appearing in the destination folder. 

it would be nice to see 
- that the app is working
- for how long it is already working
- for how long it thinks, it will be working
- when it has finished working.

**Comment by tibbi** [comment]
progressbar has been added already
