### ISSUE TITLE
Make delete faster / fail safe

### ISSUE THREAD

**Issue by PulsarFX** [SimpleMobileTools/Simple-Gallery#548]
When deleting images from the gallery it always takes a while until the image disappears and the next image is shown. As there is no indicator of any kind, I think this is very error prone to delete files by accident (especially if you disable the confirmation dialog)
The deleted file should go invisible immediately and be deleted in the background. This makes image handling much faster. (maybe also link it with #547 )
Also don't forget to update/invalidate the folder thumbnail. I noticed there is a few second delay on my device (v3.1.1)

**Comment by tibbi** [comment]
deleting will be remade in 6.23.0

**Comment by tibbi** [comment]
deleting will be remade in 6.23.0
