### ISSUE TITLE
Manually moved contents

### ISSUE THREAD

**Issue by betovidal** [SimpleMobileTools/Simple-Gallery#555]
I found an unexpected behavior by moving all the files from one folder to another with the mv command in Termux. Simple-Gallery keeps showing the folder as if it had contents and tapping on it to see what's inside I can see the names of the images that were previously in that folder (but no thumbnails), and inspecting with Total Commander I verified the folder was empty.

I tried cleaning Cache in Settings->Apps->Gallery->Clear Cache, but names are still shown.

**Comment by tibbi** [comment]
can you try running the gallery app twice, to see if it's still there? I run some redundant file cleaning once in a week. If they are still visible try using "Clear data", not just clear cache. It will reset the settings and rerun the cleaning again, so run it twice again :)

**Comment by betovidal** [comment]
It's a shame to lose settings :(. I tried selecting every "empty thumbnail" and then deleting them. It took me a couple of tries to not see them again. Just for curiosity is there any other way of clearing that data (e.g. navigating to a certain folder in the system and deleting files)?

**Comment by tibbi** [comment]
there used to be a file.exists() check at obtaining the media files which I removed, as it was really slowing down the initial media fetching. I guess that check would fail if I tried it on a file. What happened if you tried opening the empty thumbnail to fullscreen? Wasnt the file cleared properly?

**Comment by betovidal** [comment]
Opening it full-screen showed a gray screen, the same color of the app's background.

**Comment by tibbi** [comment]
ok, Ill try adding that file exists check there

**Comment by betovidal** [comment]
Thanks a lot!. Should I leave this issue closed or should I reopen it?

**Comment by tibbi** [comment]
ill reopen it just to be sure I dont forget about it

**Comment by tibbi** [comment]
some fix will be applied in 3.2.0, it will just check if the file exists at opening image to fullscreen. If it doesnt, it will try removing it from the mediastore and never show again. I dont really want to do any more advanced stuff there, this should be good enough for now and maybe save some time. Reopen it if theres still some issues with it. Thanks
