### ISSUE TITLE
[Request] Transparent status bar in photo view

### ISSUE THREAD

**Issue by azumukupoe** [SimpleMobileTools/Simple-Gallery#556]

**Comment by tibbi** [comment]
If you enable "Black background and status bar at fullscreen media" it will be black, if you toggle fullscreen it is invisible. I dont want to make it transparent.

**Comment by OLEG4120** [comment]
Yeah, but on devices with on screen buttons it looks awful
![screenshot_20180105-135654](https://user-images.githubusercontent.com/8065693/34606664-4ee89f2c-f221-11e7-932c-9b93b607c7dc.png)

**Comment by tibbi** [comment]
a transparent one will look even more awful, because of the gradient background under it. Just click on the image to toggle fullscreen and it will disappear.
