### ISSUE TITLE
Error in Compiling Android Studio  3.0.1

### ISSUE THREAD

**Issue by wizdom13** [SimpleMobileTools/Simple-Gallery#569]
Information:Gradle tasks [:app:assembleDebug]
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lorg/apache/commons/io/filefilter/AndFileFilter;
Error:com.android.dex.DexException: Multiple dex files define Lorg/apache/commons/io/filefilter/AndFileFilter;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Lorg/apache/commons/io/filefilter/AndFileFilter;
Information:BUILD FAILED in 0s
Information:15 errors
Information:0 warnings
Information:See complete output in console

**Comment by tibbi** [comment]
It was already reported at #506 , but it isnt an issue on my side. Try googling around, I cant help with it as it doesnt happen to me.

**Comment by wizdom13** [comment]
May be its only an isue on linux versions

**Comment by tibbi** [comment]
Im using Linux Mint 18.1 64-bit, I dont think it is related. It has something to do with those apache commons, but not sure what.

**Comment by wizdom13** [comment]
Okay I will try to figure it out. thank you :)

**Comment by wizdom13** [comment]
I fixed this issue by adding the bellow code in the app build.gralde just before the dependencies.

configurations.all {
    resolutionStrategy.dependencySubstitution {
        substitute module('org.apache.commons:commons-io:1.3.2') with module('commons-io:commons-io:1.3.2')
    }
}

**Comment by tibbi** [comment]
cool, thanks
