### ISSUE TITLE
Set wallpaper is a bit blurry

### ISSUE THREAD

**Issue by XyLoNaMiyX** [SimpleMobileTools/Simple-Gallery#57]
When setting a wallpaper from Simple Gallery, the edges are not as smooth as they could be. See the following images for comparison:
### Using Simple Gallery:
![photo_2016-11-14_19-04-52](https://cloud.githubusercontent.com/assets/6297805/20276621/4de2b008-aa9d-11e6-8252-ec0f148f4c58.jpg)

### Using different methods:
![photo_2016-11-14_19-04-55](https://cloud.githubusercontent.com/assets/6297805/20276624/503fb738-aa9d-11e6-98c3-aa5112db17db.jpg)

**Comment by XyLoNaMiyX** [comment]
The reason was quite obvious, on `wallpaperManager.setBitmap(Bitmap.createScaledBitmap(bitmap, wantedWidth, wantedHeight, false))` you had the last parameter set to false (filter = false). I don't know why, but at least I also added the auto mime-type detect so it's not a mini-commit ;)

**Comment by tibbi** [comment]
cool thanks, hope it fixes it then :) Ive changed the default fallback mimetype to image/jpeg, just to have something there
