### ISSUE TITLE
Thumbnail cache settings?

### ISSUE THREAD

**Issue by eMPee584** [SimpleMobileTools/Simple-Gallery#577]
So there is 
```
7.2M    /data/data/com.simplemobiletools.gallery
64K     /storage/sdcard0/Android/data/com.simplemobiletools.gallery
32K     /storage/sdcard1/Android/data/com.simplemobiletools.gallery
```
... Y? :thinking:

**Comment by tibbi** [comment]
Whats the problem here? I dont get what you mean.

**Comment by eMPee584** [comment]
Which of the folders will be used in the long run? Just installed the app and wondered, as right now, only /data seems to be used as thumbnail cache. Then why are the other two being created?

**Comment by tibbi** [comment]
I dont know, those are system folders, I didnt create them manually

**Comment by tibbi** [comment]
real cache folder used by the app is created by the third party library Im using for displaying images, it might be at your internal storage / DCIM/.thumbnails. Just try showing hidden items in the gallery, a hidden ".thumbnails" folder might appear.

**Comment by eMPee584** [comment]
Actually not, it seems (`strace -fe trace=file -p $(pgrep -of com.simplemobiletools.gallery)`) all thumbs are loaded from /data/data/com.simplemobiletools.gallery/cache/image_manager_disk_cache/ ...

**Comment by tibbi** [comment]
cache is handled by that third party library, I dont see any issue here

**Comment by eMPee584** [comment]
Actually that `.thumbCache` folder turned up, but it's only on sdcard0, which is very limited on my device. I'll have an eye on it and comment again if it grows too big.
