### ISSUE TITLE
ISO date format

### ISSUE THREAD

**Issue by azumukupoe** [SimpleMobileTools/Simple-Gallery#587]
Current date format is unfamiliar to me.
I think it's standard in your country but since your app is used by people around the world, I think it should use the global format.

**Comment by tibbi** [comment]
and how does the global format look like?

**Comment by azumukupoe** [comment]
@tibbi
You should be able to find it here
https://www.iso.org/iso-8601-date-and-time-format.html

**Comment by jimbo1qaz** [comment]
You should use the system date format, for both metadata view and scrollbar handles.

**Comment by jmichael2497** [comment]
personally i find it sometimes useful to see the EXIF timestamps down to the second rather than to the minute.

i use Open Camera with full date time naming down to the second, so i can look at that for a workaround.

hopefully just matching system settings should work, as i prefer YYYY-MM-DD and 24h00m00s, which is not the default standard for my region.

**Comment by ray4423** [comment]
its better to display the date based on the user locale by default.
and it has a option to change date format.
i hope other apps display the date in a similar method.

**Comment by pyramid3d** [comment]
I do fully support this request. There are good reasons to use the global ISO 8601 date/time format, though using the user locale is an acceptable alternative (while using the developer's format is not).

Seeing the number of open issues, how can we see if this particular issue would be slated for development and when (as is sequence not in time)?

The app is awesome! Keep up the good work!

**Comment by tibbi** [comment]
there is no particular priority or date when will this be fixed. You can try suggesting it at https://simplemobiletools.com by pressing that small orange Feature request button on the left side, to see how many people will vote on it.

**Comment by tibbi** [comment]
or nevermind, Ill take a look at it now since more people requested it already

**Comment by tibbi** [comment]
a new setting item for changing date format and toggling 24 hour time format will be added in 6.5.3. Ive added some primitive default format guessing, but it will hopefully be improved in the future.

**Comment by ray4423** [comment]
thanks for quick implementation.
but date format is applied on Properties only,
is not  changed in gallery Group by {Last modified | Date taken}.

# should i have opened new isseu?

**Comment by ray4423** [comment]
thanks for quick implementation.
but date format is applied on Properties only,
is not changed in gallery Group by {Last modified | Date taken}.

should i have opened new isseu?

**Comment by tibbi** [comment]
yeah, that is a different thing

**Comment by pyramid3d** [comment]
@tibbi, thanks for the implementation! You are doing awasome work!
