### ISSUE TITLE
I can only see 5 to 7 pictures then they become black

### ISSUE THREAD

**Issue by JulietteGL** [SimpleMobileTools/Simple-Gallery#59]
I just installed the app, I can see all the thumbnails but when I navigate through my pictures, after 5 or 7 pics, all the next ones display black. If I go back to the thumbnails and click on ones of the photo I wanted to see somtimes it displays correctly, sometimes I have to refresh the thumbnails.

**Comment by JulietteGL** [comment]
It does it in my camera and bluetooth folders but not on the download one. The downloaded pictures are way smaller. (And the gallery is very reactive, so pleasant !)

**Comment by tibbi** [comment]
hey, so those images not displayed properly have really high resolution right? If so, it might be out of memory errors, I can check it.

**Comment by JulietteGL** [comment]
The pictures weight around 2 to 2.5 MB. It's the default resolution on my phone.

**Comment by JulietteGL** [comment]
If I go to my old phones pictures that I imported, they weight half and I still have the problem. I have more than 600 photos in that folders. I thought it could be the problem but it does it as well in the bluetooth folder where there is only 64 pictures but some very heavy (4,4MB). The app crash each time I want to see the property of an image in this folder. When I try again it works. And crash on the next image property.

**Comment by tibbi** [comment]
yeah it seems that my viewpager for displaying fullscreen images is leaking badly, Ill try rolling out a fix for it today

**Comment by tibbi** [comment]
okay so Ive improved some things. Id not call the swiping issue fully fixed, but it should be a lot better. The properties dialog will also be ok with version 1.35.

**Comment by JulietteGL** [comment]
Hello, I've updated the app. The photos load faster and I can swipe through 15 but then they become black again...

**Comment by JulietteGL** [comment]
I've uploaded the last version. The problem seems fixed. Thanks you !
