### ISSUE TITLE
Sync & rename leaves blank thumbnails

### ISSUE THREAD

**Issue by gr4nny** [SimpleMobileTools/Simple-Gallery#626]
When I sync my photos with another computer that renames them, gallery continues to display blank thumbnails with the original filename. They seem to go away after some time interval (2 - 48 hrs). They persist even after closing the app and I cannot see a way to force the refresh that clears them. 
PS - great app, thank you for all you do.

**Comment by tibbi** [comment]
if you open the thumbnail to get the fullscreen view, doesnt it refresh itself properly? Thanks

**Comment by gr4nny** [comment]
Yes, they instantly disappear and nothing opens. It's funny because they
are every other picture, causing the blanks to jump back and forth. Thank
you for the quick response.

**Comment by tibbi** [comment]
How about if you long press an empty thumbnail and select Properties? What Size do you see?

**Comment by gr4nny** [comment]
Unknown error occurred

**Comment by tibbi** [comment]
Ok thanks, I will try reproducing some similar behaviour on my device.

**Comment by gr4nny** [comment]
Sure thing. Let me know if I can be more help.

**Comment by tibbi** [comment]
A new option at the Visiblity settings section will be added in the next version 3.4.0. You can allow an extra check to avoid showing invalid files there. It used to be always active some versions before as it doesnt do any performance difference on my devices with ~2k images, but it apparently slowed down the app for many users with even less images, so I made it optional and disabled by default. Most people shouldnt need it anyway. Let me know if it fixed your issues and if you see any notable performance difference with it active. Thanks

**Comment by gr4nny** [comment]
Cool. Thanks!
