### ISSUE TITLE
Offer custom ordering instead of pinned folders

### ISSUE THREAD

**Issue by sagarsiddhpura** [SimpleMobileTools/Simple-Gallery#633]
I propose upgrade to pinned folder functionality. Let user specify order of folders they want pinned at top. Currently user can pin folders but order of that pinned folders is dependant on sort option. Maybe user always wants camera to be first album, downloads to be second and have rest albums sorted by date. Please implement this functionality. If you decide to consider this, I will be more than happy to help with code. 

![screen-1](https://user-images.githubusercontent.com/2182259/35808488-3591ddcc-0a86-11e8-9784-2123da77b04b.jpg)
![screen2](https://user-images.githubusercontent.com/2182259/35808504-41875684-0a86-11e8-88d4-24740f7f7ff8.jpg)

**Comment by tibbi** [comment]
it will be added someday as a custom sorting option, not related to pinned folders in any way

**Comment by tibbi** [comment]
custom sorting by drag and drop will be added in 6.20.0
