### ISSUE TITLE
Offer Album count and Media count as subtitle in title bar

### ISSUE THREAD

**Issue by sagarsiddhpura** [SimpleMobileTools/Simple-Gallery#634]
It would be very helpful if app would show count of albums on main screen and count of media on album screen. This extra information is helpful. We already have album/media count ready.

![mediacount](https://user-images.githubusercontent.com/2182259/35808678-e0eda700-0a86-11e8-8078-c68135bbcf0e.jpg)

**Comment by tibbi** [comment]
I dont really want to clutter the UI with it. You can already see the count on the main screen or after long pressing an item
