### ISSUE TITLE
Crashing when rotated

### ISSUE THREAD

**Issue by Demonkunga** [SimpleMobileTools/Simple-Gallery#64]
I was having an issue in Galley, where it would crash when I rotated my phone. From | | to = and back to | | would make it crash.

**Comment by tibbi** [comment]
on which screen does it happen? When you see albums, photos, or the fullscreen photo?

**Comment by Demonkunga** [comment]
Darn, I can't seem to reproduce it now. I'll let you know if/when/how it happens again.

**Comment by tibbi** [comment]
it could have been a fixed bug, just reopen if it happens again.
