### ISSUE TITLE
Settings: Add optional filter for excluding dng (raw) files

### ISSUE THREAD

**Issue by wistein** [SimpleMobileTools/Simple-Gallery#656]
This makes sense when taking pictured in several formats at the same time, e.g. jpg and dng, jpg to view on the phone and dng to work on later. At the moment both pictures are shown thus dng takes quite some time to show up.

**Comment by wistein** [comment]
Hello Tibor,

Thank you very much for implementing the raw-exclude-feature.

Included here is a slightly improved (2 changes) German strings.xml.

Best regards,
Wilhelm Stein



-----Ursprüngliche Nachricht-----
Von: Tibor Kaputa [mailto:notifications@github.com] 
Gesendet: Samstag, 16. Juni 2018 23:48
An: SimpleMobileTools/Simple-Gallery
Cc: Wilhelm Stein; Author
Betreff: Re: [SimpleMobileTools/Simple-Gallery] Settings: Add optional filter for excluding dng (raw) files (#656)

Closed #656 <https://github.com/SimpleMobileTools/Simple-Gallery/issues/656>  via 5062d3f <https://github.com/SimpleMobileTools/Simple-Gallery/commit/5062d3f087e8bbe23613934e675c9eadb036b6de> .

**Comment by tibbi** [comment]
what strings? I dont see anything :)

**Comment by wistein** [comment]
I attached the strings.xml file to the mail.
But obviously it does not appear in GitHub.

Try to make a pull request.



-----Ursprüngliche Nachricht-----
Von: Tibor Kaputa [mailto:notifications@github.com] 
Gesendet: Sonntag, 17. Juni 2018 16:12
An: SimpleMobileTools/Simple-Gallery
Cc: Wilhelm Stein; Author
Betreff: Re: [SimpleMobileTools/Simple-Gallery] Settings: Add optional filter for excluding dng (raw) files (#656)

what strings? I dont see anything :)
