### ISSUE TITLE
Bug: When to edit video in Simple Gallery

### ISSUE THREAD

**Issue by Daiky96** [SimpleMobileTools/Simple-Gallery#657]
#### Expected behavior
If indeed the simple gallery application can not edit the video then the application developer does not need to add video edit feature when we press the settings. With the addition of video editing feature in simple gallery application of course the user of application can edit video through this application, but I have tried some video but still not succeed. It should be when we press "edit" it will appear menu to edit video.

#### Actual behavior
When I want to edit a video in a simple gallery application a notice appears like this "no support this video, try other video", well, when I try another video it turns out the same result can not.

#### The question
If indeed in this app can not edit the video for what the developer added this feature, they should not need to add this feature because it does not support the video editing in this application. But the answer is not that, any features added by the developer there must be usability and can be used, therefore I conclude that this is a bug.

#### How to reproduce

* App Simple Gallery (simple mobile tools): versi 3.4.1
* Operating system: Android 7.1.2
* Open the application
* Play video
* Click on point three above right
* After that press on the "edit" menu
#### Recording Of The Bug

![videotogif_2018.02.12_23.15.07.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1518454068/mjgxqiqxr113cutg1gcw.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@daiky69/bug-when-to-edit-video-in-simple-gallery">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tibbi** [comment]
it's not a bug, the user might have some third party software for editing videos. Also the error isnt from my app, it comes from your device, from some app.
