### ISSUE TITLE
Swiping the next image positions it incorrectly if the current image is zoomed in and not on the edge

### ISSUE THREAD

**Issue by DragoonAethis** [SimpleMobileTools/Simple-Gallery#664]
If you have any image open and swipe it to show the next one, it correctly appears right on the edge of the screen. However if the current image is zoomed in, moved a bit from the edge (so that, for example, the right image edge isn't on the edge of the screen) and the next image is being swiped in, the new image is positioned next to the touch location instead of the edge of the screen. The attached video shows this issue pretty well.

[SimpleGallerySwipingBug.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/1744327/SimpleGallerySwipingBug.zip)

**Comment by tibbi** [comment]
should be better already

**Comment by DragoonAethis** [comment]
Thanks!
