### ISSUE TITLE
Performance Issues since Android 8.1

### ISSUE THREAD

**Issue by Ketrel** [SimpleMobileTools/Simple-Gallery#677]
Since upgrading from Android 7.0 to 8.1, I've noticed a few performance issues

* Refreshes take much longer, even if no changes  
* When moving an image (in addition to changing the timestamp) it takes close to a minute to register the change and update the view (possibly connected to the refresh issue above)

**Comment by tibbi** [comment]
Do you have an SD card? If you do, does it have many images? Does the move involve the SD card, or it is moving from internal storage to internal storage?

**Comment by Ketrel** [comment]
No, my device is a Oneplus 3T.
Only internal storage.

**Comment by RenaKunisaki** [comment]
I've noticed it taking a minute to move images both on LG G4 (which has SD card) and Essential PH-1 (which doesn't). It's always been slow but recently it's been worse.

**Comment by tibbi** [comment]
should be faster on 3.7.0, I rewrote some things

**Comment by Ketrel** [comment]
I can confirm that this looks fixed on 3.7.0
