### ISSUE TITLE
Samsung Dex Support 

### ISSUE THREAD

**Issue by F3000** [SimpleMobileTools/Simple-Gallery#681]
Please add support for this. More infos can be found here : 

http://developer.samsung.com/samsung-dex/modify-optimizing

http://developer.samsung.com/samsung-dex/modify-optional

The App should be Build withe API 24 and have to support the Android-N multiwindow view.

**Comment by tibbi** [comment]
moved to https://github.com/SimpleMobileTools/General-Discussion/issues/64
