### ISSUE TITLE
Simplify apply changes for edited files

### ISSUE THREAD

**Issue by nulledone** [SimpleMobileTools/Simple-Gallery#685]
Instead of asking a name and extension everytime, it would be better to make it like a confirmation dialog with three options

Apply changes  - 1st
Save as a copy - 2nd (long tap to rename copy maybe)
Cancel - 3rd

Sample layout

(centered text) asking what to do
(leftoption) apply | (rightoption) save as a copy
(centeredbottomoption) Cancel

**Comment by tibbi** [comment]
related to #2438
