### ISSUE TITLE
EXIF Altering

### ISSUE THREAD

**Issue by nulledone** [SimpleMobileTools/Simple-Gallery#686]
Options to remove all EXIF and click alter them in file properties dialog.

Would be a lot better to show all EXIF properties in additional second page of the dialog

Sample

(header) (removeallicon) 
Taken time (remove icon) (editicon)
01.01.1970

**Comment by ramack** [comment]
Not only removeing, but also modification and additon of EXIF tags would be great!

**Comment by krc** [comment]
Would be nice to see all exif data
even nicer to edit/remove. but I'd settle for visibility

**Comment by tibbi** [comment]
duplicate of #282
