### ISSUE TITLE
properly refreshing media properties

### ISSUE THREAD

**Issue by gcalzo** [SimpleMobileTools/Simple-Gallery#689]
After testing date-time keeping on media move I manually reset the correct one (my Moto G2 is rooted) but there is no way to let simple gallery "receive" the update when showing the media properties.
Already tried a media.re.scan and app cache clearing; so far only a media rename from simple gallery is refreshing the media properties.

**Comment by tibbi** [comment]
not sure which properties you mean, there is already a "Fix date taken value" option

**Comment by gcalzo** [comment]
Your "fix date" is useless on Moto G5 plus with Oreo v8.1 and the "properties" I mean are the usual exif data...

**Comment by tibbi** [comment]
make sure you use the latest pro version. Modifying other exif values is reported at https://github.com/SimpleMobileTools/Simple-Gallery/issues/686

**Comment by gcalzo** [comment]
Of course I used the latest pro version for testing...
