### ISSUE TITLE
One-finger zoom - Is this a bug or just normal behavior?

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#694]
Video related
https://my.mixtape.moe/bpsxuc.mp4

**Comment by tibbi** [comment]
the image definitely shouldnt go upside down. Does it happen to every image, or it depends on something?

**Comment by floppyD** [comment]
Looks like it just happens if you check "Replace deep zoomable images with better quality ones".

**Comment by tibbi** [comment]
nice, thanks. So it is apparently a bug in android itself in Nougat, it is already reported by the library creator that Im using at https://github.com/chrisbanes/PhotoView/issues/434 . Ill take a look at what can I do there though.

**Comment by floppyD** [comment]
I'm not an expert in Android development but maybe you can replace the library with this one? It even supports subsampling which is nice since you can have deepzoom without being hard on resources.
https://github.com/davemorrissey/subsampling-scale-image-view

**Comment by floppyD** [comment]
I'm not an expert in Android development but maybe you can replace the library with this one? I use an app that uses it and it's pretty light on resources.
https://github.com/davemorrissey/subsampling-scale-image-view

**Comment by tibbi** [comment]
thats the one I use for deep zooming, but it lowers the image quality too much. If you toggle that setting I replace it with PhotoView.

**Comment by floppyD** [comment]
Hmm, I see. Off-topic but why does your app lags a bit when swiping high quality images while the other one that uses the same library doesn't? (Clover).

**Comment by tibbi** [comment]
You mean with that toggle "Replace deep zoomable images..." disabled, or enabled?

**Comment by floppyD** [comment]
Disabled, using "Subsampling Scale Image View"

**Comment by tibbi** [comment]
I dont know, it lags to me too :) Ill get there someday.

**Comment by floppyD** [comment]
Maybe taking a look at its implementation can help you? Anyway, good luck bro.

**Comment by tibbi** [comment]
I will check someday. The same images in same resolution lag in Simple Gallery and are smooth there?

**Comment by floppyD** [comment]
Yes, actually it never lagged on me no matter how big the image was. I recommend the High resolution or the Photography board if you are going to give it a try.

**Comment by tibbi** [comment]
im not using that library anymore, guess it is solved
