### ISSUE TITLE
Touching total time right of time span in videos doesn't fast forward

### ISSUE THREAD

**Issue by matiasblomqvist** [SimpleMobileTools/Simple-Gallery#697]
...even though it says so in the FAQ. Backwards it works just fine. Btw I would never have even tried to do this if I hadn't translated the FAQ.

**Comment by tibbi** [comment]
ye it might not be intuitive, I might add the casual swiping too. Anyway, how long is the video? Isnt it too short so that the 2% isnt even 1 second?

**Comment by matiasblomqvist** [comment]
> ye it might not be intuitive, I might add the casual swiping too. Anyway, how long is the video? Isnt it too short so that the 2% isnt even 1 second?

Oh. Yeah it seems it doesn't work for short videos (27 sec) but works for longer videos (1:45 min). A simple minimum of 3 seconds could be a solution (I don't see point going only 1 or 2 seconds but ofc that's up to you)

**Comment by tibbi** [comment]
ye I will add some minimum length there
