### ISSUE TITLE
Use English Language not working

### ISSUE THREAD

**Issue by azumukupoe** [SimpleMobileTools/Simple-Gallery#700]

**Comment by tibbi** [comment]
can you try swiping away the app and restarting it, if it works then?

**Comment by azumukupoe** [comment]
@tibbi It's been like this for a while. Deleting cache won't do anything.
![SS](https://i.imgur.com/TZD4Bl1.png)

**Comment by tibbi** [comment]
not deleting cache, press the Square icon at the bottom to go to Recents and swipe away the Gallery. Then after restarting it it still isnt in english?

**Comment by azumukupoe** [comment]
@tibbi No.

**Comment by tibbi** [comment]
weird.. Ill take a look at it, that toggle seems to misbehaving in some cases to some users.

**Comment by tibbi** [comment]
so it is not just Settings misbehaving, the language is set wrong in the whole app, right?

**Comment by azumukupoe** [comment]
@tibbi Yes, right.

**Comment by azumukupoe** [comment]
Actually, restarting the app causes the problem to occur.

**Comment by tibbi** [comment]
will be fixed properly in the next version

**Comment by azumukupoe** [comment]
@tibbi Thank you!

**Comment by azumukupoe** [comment]
I hate to say this but it's not fixed.

**Comment by tibbi** [comment]
it isnt added in the new version yet, you probably just got an older one :)

**Comment by azumukupoe** [comment]
@tibbi Is it still not added?

**Comment by tibbi** [comment]
it is, still doesnt work properly? What app version do you have? What is wrong?

**Comment by azumukupoe** [comment]
@tibbi It's 3.7.1 and the issue is not fixed.

**Comment by tibbi** [comment]
what happens if you switch the toggle? Does the screen or whole app restart?

**Comment by azumukupoe** [comment]
@tibbi the screen refreshes but nothing changes

**Comment by tibbi** [comment]
ok, Ill take a look at it someday, so far it seems that the issue was fixed for everyone else.

**Comment by tibbi** [comment]
should be fixed in 4.1.0

**Comment by azumukupoe** [comment]
Yes, it's fixed. Thanks!
