### ISSUE TITLE
Can not share edited image with Android Messages (SMS)

### ISSUE THREAD

**Issue by voyageur** [SimpleMobileTools/Simple-Gallery#708]
Tested on 2 phones: Motorola G5 (fresh first install from Google Play) and BQ Aquaris X - Android 7.1.1 (logcat captured from the later), Simple Galerie 3.6.0

To reproduce: edit a jpeg image (resize it, or crop it), save the new image either in original directory /storage/emulated/0/DCIM/Camera/ or in downloads, display the new image, try to share the edited image via Android Messages

Toast "Error while loading the attachment" (translated) will come up, and logcat will show:

> 03-19 21:05:54.011 15017 15017 E BugleShareIntent: Unsupported shared content type for content://media/external/images/media/15950:  (image/jpeg)

Opening the image in Google photos and trying to share it will result in same error

Sharing the image via other methods like gmail works. Sharing "normal" images via Android Messages works

Also when saving the edited file, this error comes up in logcat after a few seconds:

> 03-19 21:14:24.027  2875 31492 E DatabaseUtils: Writing exception to parcel
> 03-19 21:14:24.027  2875 31492 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/15952 from pid=19390, uid=10078 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
> 03-19 21:14:24.027  2875 31492 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:608)
> 03-19 21:14:24.027  2875 31492 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:483)
> 03-19 21:14:24.027  2875 31492 E DatabaseUtils: 	at android.content.ContentProvider$Transport.query(ContentProvider.java:212)
> 03-19 21:14:24.027  2875 31492 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
> 03-19 21:14:24.027  2875 31492 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:565)
> 03-19 21:14:31.243  1494  1911 E IzatSvc_PassiveLocListener: E/Exiting with error virtual void izat_manager::IzatPassiveLocationListener::onLocationChanged(const izat_manager::IzatLocation *, const IzatLocationStatus) line 172 "1"

But the file can be displayed, and the application has storage authorization.

**Comment by tibbi** [comment]
parent of #707

**Comment by tibbi** [comment]
should be fixed in 3.6.1

**Comment by voyageur** [comment]
Quick test with 3.6.2, I could share resized image via SMS without a problem. Thanks!
