### ISSUE TITLE
Add grouping by date

### ISSUE THREAD

**Issue by alpha-and-omega** [SimpleMobileTools/Simple-Gallery#709]
Hello guys!
I have seen a killer feature in other android gallery viewer - "View type" - "by days".
My opinion there are no better way to view photo gallery. And surprisingly I have seen it only in one android gallery viewer - in Chinese MIUI.
It looks like this:

**today:**
photo photo photo
photo

**19 march**
photo photo

**08 match**
photo

**1 January**
photo video photo
photo photo photo
photo photo photo
photo

Everything is clustered by sessions - days, and it is easy to find a group of related photos.
Well, the idea is very simple, I hope someone will implement it!

**Comment by tibbi** [comment]
Google Photos does it that way and so far not a single person out of 2 million users requested it, so I guess people dont really need it :) Anyway, maybe it will be added in the far future.

**Comment by alpha-and-omega** [comment]
All of them just miss the point ! :)

**Comment by Theobald93** [comment]
Too much groups of 1...5 photos, waste of space for me ;)
Sorting by date with no groups is the best xD

**Comment by F3000** [comment]
That’s exactly the same thing as on iOS Photos app :) 

It’s better for fast searching a foto

**Comment by tibbi** [comment]
well if you need it, you can always toggle "Show all folders content" with sorting by date. Then drag the side fastscroller and you will see the current date/time.

**Comment by alpha-and-omega** [comment]
@tibbi date is not the point, main idea is clustering. This creates clear magin between non-related photos.
And btw, this mode is default in MIUI gallery viewer which is used by gazillions of china people, and gazillions can't be mistaken...

**Comment by tibbi** [comment]
sure,  Im not saying that they are mistaken, just that so far nobody reported it. I will add it someday in the future.

**Comment by ramack** [comment]
Isn't it the same as #467?
Anyhow I also think this would be good to have.

**Comment by co5mo** [comment]
and group by folder name :)

**Comment by tibbi** [comment]
will be added in 4.2.2

**Comment by delphinuz** [comment]
Please check Pikture app. It shows up the date on title bar when scrolling pictures. It also has a calendar, that you can display the pictures of specified date.
