### ISSUE TITLE
Frequently unable to zoom

### ISSUE THREAD

**Issue by RenaKunisaki** [SimpleMobileTools/Simple-Gallery#713]
Since today I've frequently been unable to pinch to zoom. It seems to happen mostly if the screen is turned off while the app is open. Double tapping usually fixes it.

This had happened occasionally before, but just about constantly today.

**Comment by tibbi** [comment]
Do you have "Replace deep zoomable images..." in Settings enabled?

**Comment by RenaKunisaki** [comment]
No.

**Comment by tibbi** [comment]
How about some additional features related to screen sides? Like changing volume/brightness by dragging on your finger on screen sides, or maybe switching images by pressing screen side? Also, try pinching your fingers more to the screen center once it is broken, to see if it will work.

**Comment by RenaKunisaki** [comment]
Ugh, hit the button by accident.

Thumbnails: crop to square: on
Thumbnails: show media count: on
Scrolling: show info bubble: on
Scrolling: pull to refresh: on
File operations: keep old last modified: on
All other options are off.

Pinching out from the centre did work after a few tries.

**Comment by tibbi** [comment]
some related things will be changed in 5.0.2, reopen if it is still broken
