### ISSUE TITLE
APK Icon Editor doesnt recognize app Icon

### ISSUE THREAD

**Issue by F3000** [SimpleMobileTools/Simple-Gallery#714]
This is due a change of the picture location changed from /drawer/ -> /mipmap 

This should be only a info for further investigation.More infos here:
https://stackoverflow.com/questions/28065267/mipmaps-vs-drawable-folders

**Comment by tibbi** [comment]
what is the issue here? I dont get it

**Comment by F3000** [comment]
Sorry it’s not your fault . It’s from my wrapper . It can be closed
