### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by mrvak** [SimpleMobileTools/Simple-Gallery#715]
Needs good russian translation ( of cource i can help )

**Comment by tibbi** [comment]
it is translated, the strings are at https://github.com/SimpleMobileTools/Simple-Gallery/blob/master/app/src/main/res/values-ru/strings.xml . You found some not translated ones?

**Comment by mrvak** [comment]
Translating is not correct and contains many mistakes

**Comment by tibbi** [comment]
you can press the pencil at the top right corner and update what is needed, full guide is at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file . But make sure the strings are really corrected, not just using a different dialect or something. Thanks
