### ISSUE TITLE
Empty folder shown with grey/black thumbnail 

### ISSUE THREAD

**Issue by mckel-9** [SimpleMobileTools/Simple-Gallery#717]
In the gallery an empty folder remains listed after content was deleted. 
The screenshot attached shows how the folder displays a grey/black thumbnail. 

![empty-folder](https://user-images.githubusercontent.com/8899013/37869593-57fcaa96-2fba-11e8-97d5-6fa9e0da0b39.png)

The folder cannot be opened in the app. A click on the folder does not open it, but one is redirected to the gallery. 

I checked in a file manager that the folder is really empty, also no hidden files. 

Device is a Samsung Galaxy Note 10.1

**Comment by tibbi** [comment]
doesnt it go away after pull-to-refresh, opening the folder, or restarting the app?

**Comment by mckel-9** [comment]
No, neither of this resolves it.

**Comment by tibbi** [comment]
have you done some file operations related to this folder in the past? I mean copying/moving to it, editing some screenshot or so. Also try toggling "Do an extra check to avoid showing invalid files" in settings please, to see if it will solve it.

**Comment by mckel-9** [comment]
I have moved files in the past. 
Enabling option "Do an extra check to avoid showing invalid files" solved the problem.

Many thanks.

Btw: this is a great app.

**Comment by tibbi** [comment]
okay, I guess it was a glitch related to a buggy version, it shouldnt happen anymore. If it does, it should at least be fixed on opening the folder or so :p

**Comment by mckel-9** [comment]
The version is: v3.6.0
Switching the option "Do an extra check to avoid showing invalid files" on/off hides and unhides the folder.
