### ISSUE TITLE
Effective media sorting.

### ISSUE THREAD

**Issue by OffifialMITX** [SimpleMobileTools/Simple-Gallery#720]
Here's a FR I've really been looking for since weeks.

Somehow, data management has always been a big problem on phones, and it wasn't even really affected by the switch from cell phones to smartphones.

In fact, the smartphone era made the problem even worse, with displays so small that they mostly can be covered by a single hand, but but very big storage and fast access to the internet so a bigger mess is created in less amount of time.

On a computer data management is handled well by default. Not only are there easily accessible options of chosing an individual folder for each file that is downloaded but a large or at least medium sized screen allows it to have a large viewed part of files with a visual size where you can understand what is in the preview (if there is one), while, at the same time seing their full names. Or even have a media viewer and every involved folder all open at once.

While on a tablet PC one may come close to the first example, even this is not possible to achieve on a smartphone in a way that is usable.

So now I present my suggestion of how effective advanced mamagement could work:
![](https://i.imgur.com/0CaKQe5.jpg)

I tried my best for this to be self explaining and readable but I'll gladly explain anything that is unclear.

I should mention though that this operation is intended to be toggled by a previous menu containing a list of folders, added by a typical material add buttom, each with two checkboxes of
- [ ] move content from
- [ ] let content be moved into

This menu can always be opened by the bottom right add button and once done, it will put all marked content in the upper box, sorted, but ont separated and all the avalible folders in the bottom section.

Regards,
Me

**Comment by tibbi** [comment]
not really sure what is your intention here, but I dont really plan redesigning the app anyway. The purpose of the app is not moving media, but viewing.

**Comment by OffifialMITX** [comment]
I'm not suggesting a redesign but an additional functionality.

If moving the media is not part of the app's purpose, why does it offer such functionality?

On March 27, 2018 9:47:25 AM GMT+02:00, Tibor Kaputa <notifications@github.com> wrote:
>not really sure what is your intention here, but I dont really plan
>redesigning the app anyway. The purpose of the app is not moving media,
>but viewing.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/SimpleMobileTools/Simple-Gallery/issues/720#issuecomment-376429449

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by OffifialMITX** [comment]
However I'm not going to insist, I respect your choice as the owner of this app.
