### ISSUE TITLE
Does not show media from a 3rd party application called EDS.

### ISSUE THREAD

**Issue by nulledone** [SimpleMobileTools/Simple-Gallery#721]
App link:

https://play.google.com/store/apps/details?id=com.sovworks.eds.android

**Comment by tibbi** [comment]
not sure what was the issue here, but many things related to third party apps have changed, so reopen if it is still broken

**Comment by nulledone** [comment]
Still same @tibbi

**Comment by nulledone** [comment]
![Screenshot_20190313-222214_1](https://user-images.githubusercontent.com/29547468/55090502-47335480-50c0-11e9-855b-f5d4c53051f4.png)
This is the intent that I captured from another application, hope it helps.

**Comment by nulledone** [comment]
@tibbi is it fixed? Or an issue only with my device?

**Comment by tibbi** [comment]
right, I forgot to add a comment. It will be fixed in the next version 6.6.2 released soon

**Comment by nulledone** [comment]
Alright thanks for the quick feedback. Also just wondering what was causing this issue? Long names?

**Comment by tibbi** [comment]
no, just a weird type of URI which I wasnt prepared for. There are just so many ways intents can send file paths
