### ISSUE TITLE
png's not showing up until i change the extension to .jpg

### ISSUE THREAD

**Issue by B33Z5z** [SimpleMobileTools/Simple-Gallery#729]
So pretty much sums it up in the heading.
I was looking for a png photo and it was not showing up. I went to file manager to change the extension to .jpg instead and then it showed up in gallery

Any idea why?

v3.6.3

**Comment by B33Z5z** [comment]
now i changed it back to png and it shows. I have no idea why that happened though.. 
is it possible for a feature like to rebuild the current album if it went "corrupt" somehow?  Because i have a feeling something strange like that happened in the album.

**Comment by tibbi** [comment]
well Im relying on the system mediastore, which is kind of a database storing media files for fast querying. If the file isnt there, Im not aware of it. Renaming most likely added it. You can add any folder in Settings -> Manage Included Folders, it will be scanned more thoroughly file by file then. Improving file discovery is obviously on the roadmap, but I want to make it somehow without slowing down the app.
