### ISSUE TITLE
Make hiding system UI at fullscreen smoother

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#732]
Forcing the UI to sit there a bit more before being hidden gives a smoother experience imo

Example:
https://my.mixtape.moe/ydpngu.mp4

**Comment by tibbi** [comment]
cant view the file, site seems to be offline or something. Are you talking about the "Automatically hide system UI at fullscreen media" option, or manual hiding?

**Comment by floppyD** [comment]
The former. Weird, the website is working fine here, but I got a mirror, check it out:
https://dropfile.to/C3KVcBf

**Comment by tibbi** [comment]
I can see it now. Not sure what you mean though, it is perfectly smooth. I wait with the hiding till everything is prepared already.

**Comment by tibbi** [comment]
ok I see now, will take a look at it

**Comment by floppyD** [comment]
Your current solution is not bad, I mean, it does its job, but it doesn't feel "smooth" as the video related solution, see? I dunno if this is completely subjective or not.

**Comment by tibbi** [comment]
ye I know what you mean, Ill try improving it
