### ISSUE TITLE
Small portion of pictures in each hidden folder are detected

### ISSUE THREAD

**Issue by sbobbo** [SimpleMobileTools/Simple-Gallery#734]
I am trying out Simple Gallery in an attempt to leave QuickPic behind. While it does seem to see all(?) of my .nomedia folders, it is only indexing a small portion of the pictures in each. Maybe around a quarter of them? I could try to do a full comparison if that would help. I have many thousands of pictures on my phone sorted into different folders, some hidden, some not. QuickPic has no issue noticing and indexing all of the photos. For SG, the displayed count is lower, and when I enter the folder, it only shows the number of images indicated by said count, rather than all of the pictures there.

It may be noteworthy that the all of the hidden pictures are on the SD card, in a subfolder of /Android/data, due to the SD card problem mentioned here: https://github.com/syncthing/syncthing-android/wiki/Frequently-Asked-Questions

Galaxy Note 8
Android 8.0

**Comment by tibbi** [comment]
should be fixed in 3.7.0, Im rewriting the way I fetch media
