### ISSUE TITLE
Post-deletion behavior in fullscreen

### ISSUE THREAD

**Issue by mcbaze** [SimpleMobileTools/Simple-Gallery#74]
When i enter fullscreen mode by selecting some picture in album (let's call it "first picture"), make some swipes to the other picture ("second picture"), delete it by pressing icon and confirm deletion, viewer returns me to "first picture" view. But i expect opening of pre- or post- "second picture" view. Please give me some coment. Thank you

**Comment by tibbi** [comment]
thanks, will be fixed in 1.46
