### ISSUE TITLE
Scrollbars bug

### ISSUE THREAD

**Issue by OLEG4120** [SimpleMobileTools/Simple-Gallery#741]
Look at gif
![scr_20180413_092906](https://user-images.githubusercontent.com/8065693/38720534-40d48b46-3eff-11e8-9acf-14c31822abf6.gif)

**Comment by tibbi** [comment]
some scrollbar glitches will be fixed in 4.0.x, let me know if you find more. Ideally give exact steps for reproduction too.

**Comment by tibbi** [comment]
seems broken at changing column count, will see what can I do there

**Comment by OLEG4120** [comment]
Scrollbar loses position
![output](https://user-images.githubusercontent.com/8065693/40530251-b2954848-6000-11e8-8d04-e47aea7e2556.gif)

**Comment by tibbi** [comment]
ye I noticed it too, will try improving it even further in the next version

**Comment by tibbi** [comment]
many scrolling bugs will be fixed in 4.3.0, please reopen with exact steps to reproduction if it still happens
