### ISSUE TITLE
Found a spelling error, what to do?

### ISSUE THREAD

**Issue by NitroNils** [SimpleMobileTools/Simple-Gallery#744]
How can I push (if that's the right term?) changes to strings?
I want to contribute!

**Comment by tibbi** [comment]
Hey, the instructions are at https://github.com/SimpleMobileTools/General-Discussion#how-can-i-suggest-an-edit-to-a-file . It is really simple, you need to update a file either from a value-xx in https://github.com/SimpleMobileTools/Simple-Gallery/tree/master/app/src/main/res , or at https://github.com/SimpleMobileTools/Simple-Commons/tree/master/commons/src/main/res , depending what string it is and what language :) Thanks
