### ISSUE TITLE
Subfolders of hidden folders are not hidden

### ISSUE THREAD

**Issue by tengwar** [SimpleMobileTools/Simple-Gallery#755]
Folders that have a .nomedia file in them are correctly hidden. But their subfolders are always visible even though they shouldn't.

When I invoke a menu on these subfolders, they show the "show" item, not the "hide" item. This is correct as they should be hidden, yet for some reason they are being displayed.

**Comment by tibbi** [comment]
what app version do you have? Can you check Settings -> Manage Included Folders to see if they arent there?

**Comment by tengwar** [comment]
I have 3.7.3, the newest F-Droid version. And yes, they aren't in the Manage Included Folders section, only folders higher in the hierarchy are.

**Comment by tibbi** [comment]
it is the intended behaviour then. If a folder is at the Included ones, only a .nomedia directly in the folde will hide it. The .nomedia doesnt get applied to subfolders in that case. Try removing the folders from included ones.
