### ISSUE TITLE
[Bug] v3.71 -> v3.7.2 Hidden folder via .nomedia no longer shows under "show hidden"

### ISSUE THREAD

**Issue by bentolor** [SimpleMobileTools/Simple-Gallery#756]
I have the folder `/storage/emulated/0/Pictures` which contains a `.nomedia`-File to make it hidden.

Prior to 3.7.2 I could access this folder by using the Simple Since upgrading to 3.7.2 this specific folder no longer appears when I choose "Temporarily show hidden". Even adding it explicitly to the included folders list in the settings does not restore the old behavior. It does appear in the hidden folder, though. 

Downgrading resolves the issue. So I assume this is an intended behavioral change?

P.S.: Thank you very much for this great picture gallery program. Really love it!

**Comment by tibbi** [comment]
Try updating to 3.7.3, that contains the intended behaviour :)

**Comment by bentolor** [comment]
Tested the release version; indeed this fixes it. Thanks @tibbi

**Comment by dylmye** [comment]
I'm having this issue on 3.7.3, any ideas? This is 3.7.3 from Play Store

**Comment by tibbi** [comment]
could you describe your issue? Also what folders you have at Settings -> Manage excluded/included folders and where you have the .nomedia files?

**Comment by dylmye** [comment]
Looks like either `storage/emulated/0` was added to "included folders" or
that behaviour had changed causing all subfolders to be included. Removing
this rule fixed issues. Thanks
