### ISSUE TITLE
8 bit color mode

### ISSUE THREAD

**Issue by scalpremier** [SimpleMobileTools/Simple-Gallery#766]
Can you add an option to have a 8 bit color mode? Like in Camera Roll. An other open source app avaible on fdroid.
On Simple Gallery a gradient in a blue sky is pixellized. And the "better quality" option doesn't help. (At the screen size it ok, but when you zoom in the image it's blur)

I think it's an important feature.

To me, see your images in good quality in an images viewer is the main porpose of this kind of app ;-) 

Thanks a lot.

**Comment by tibbi** [comment]
can you send me a sample image? That "Replace deep zoomable images..." in settings should have fixed it.

**Comment by scalpremier** [comment]
On this image for exemple, without the "Replace deep zoomable images..." checked, There is an artifacts in in the sky but I can zoom in and see cleary the brand of the glove and peopoles' faces. If I check "Replace deep zoomable images with better quality ones" the artfacts disapear but if I zoom in it's blurry, I can't read the name on the glove or see peopoles' faces.

In CameraRoll with the same image, when "8 bit mode" is unchecked,  I have the same result as in SimpleGallery when  "Replace deep zoomable images with better quality ones" is unchecked

But when "8 bit colors" is checked in CameraRoll there is no more artifacts and I can zoom in and see clearly all details

Which is the same result as with quickpic. 
That's why I think this 8 bit color option could inspire you. 

I hope it can help ;-)

![20180422_150605](https://user-images.githubusercontent.com/26877504/39786775-57da7800-5322-11e8-854f-9a338a6685e8.jpg)

**Comment by tibbi** [comment]
I think I found the ideal solution. Starting with version 4.5.0 the toggle will be removed, I will load a zoomable image that will also have good quality. Let me know at hello@simplemobiletools.com if you want to test the version.

**Comment by scalpremier** [comment]
Yes I'm would like to test the new version. I send you a email at hello@simplemobiletools.com

Have you look at the 8 bit color mode in CamerRoll ? or did you find another solution ?

Thanks

**Comment by scalpremier** [comment]
You re right,
I'm not a coder, I'm computer graphic designer and to me, I think it's a probleme of color management, it seems that the image is show in RVB 16 bit instead of RVB 24 bit (8 bit per chanel RVB).So you have only 65 536 colors instead of 16 millions, That's why you have artefacts in gradiants. And the "better quality" option seems to blur the image, artefacts disapear but you lose details. 

But maybe I'm completly wrong ;-) 

I'll try the new version that you sent me.

**Comment by scalpremier** [comment]
I've try a bit and it seems to work properly, no more artefacts and the possibility to zoom in without blur. I'll try on other devices, other images, and the other thing that you asked me and I'll tell you if I find something wrong, but for now it seems perfect ;-)

Thanks a lot.
