### ISSUE TITLE
media rescan every time I open simple gallery 

### ISSUE THREAD

**Issue by ale82to** [SimpleMobileTools/Simple-Gallery#768]
I don't know if it's a bug or what but every single time I open simple gallery I ve got the white spinning circle as the app is doing a rescan for new folder
it s super annoying and mede me switch back to asus Gallery

**Comment by tibbi** [comment]
it searches for new media files, not just folders. New media fetching has been optimized a lot lately so I might remove that spinning circle someday.

**Comment by ale82to** [comment]
cool thanks if possible, add crop functionalities and for me simple gallery would be perfect

**Comment by tibbi** [comment]
you can already crop in the editor. You can either long press an image thumbnail and select Edit, or press it at the fullscreen view.

**Comment by ale82to** [comment]
super thanks just. a little suggestion make it possible to drag from center bacuase for people using apps like smart task launcher or edge gestures like me, it's impossible to drag from both right or left thanks

**Comment by tibbi** [comment]
using such task launcher sounds like a pretty bad idea. Not sure if Ill change it, we will see.

**Comment by tibbi** [comment]
the spinner will be removed in the next version 4.x, it should work out just fine
