### ISSUE TITLE
Sort by date taken

### ISSUE THREAD

**Issue by x-jokay** [SimpleMobileTools/Simple-Gallery#770]
Hello

It would be really great to have the sort by date taken.

I've seen you had removed it: https://github.com/SimpleMobileTools/Simple-Gallery/commit/26aa79294b747b864daed9f1405865132a19891d

Why didn't it working? :)

**Comment by tibbi** [comment]
ye the way files are fetched has been completely rewritten, I couldnt make sorting by date taken work like this. Ill add it back once I find a reliable way for it.

**Comment by tibbi** [comment]
it will be added back in 4.0.1. It will work slightly slower than other sortings, but thats the best I could do for now. It should work reasonably well for the vast majority of users.
