### ISSUE TITLE
Gallery crashes when granting ex Sdcard permission ! 

### ISSUE THREAD

**Issue by ale82to** [SimpleMobileTools/Simple-Gallery#775]
Gallery crashes when granting ex Sdcard permission through Android document provider,also having root i didn't think granting extSD card permission was necessary.
i m on cyanogenmod mod 13 =(marshmallow) and simple gallery has the only app I ve had this problem in over a year.
also in version 4 eventought the spinner has been removed the gallery is still slow in finding new folder when created from scratch it takes about 3 seconds to show new folder with new media with a device on snapdragon 652.
screenshoot of the issue
https://image.ibb.co/mgiGty/screen.png
please any solution ?

**Comment by ale82to** [comment]
I also made sure I had write permission on ext SD card (I am rooted) so why simple gallery crashes ?
screenshot 
https://ibb.co/khPmRJ

**Comment by mindaugas5** [comment]
renata19860315@gmail.com

**Comment by tibbi** [comment]
not sure, rooted devices can have many issues

**Comment by tibbi** [comment]
guess it is fixed already, many things have been changed since then
