### ISSUE TITLE
Implement "Replace share button by rotate screen" on video player mode

### ISSUE THREAD

**Issue by floppyD** [SimpleMobileTools/Simple-Gallery#776]
You can make it just switch between portrait and landscape mode.

**Comment by tibbi** [comment]
there isnt even a rotate button yet for videos

**Comment by floppyD** [comment]
But that's what I'm asking for 🤔

**Comment by tibbi** [comment]
well it sounded like you ask for some toggle in settings. Video rotating is already reported at #484

**Comment by floppyD** [comment]
Oh, that's ok then.

**Comment by floppyD** [comment]
We have the bottom action bar now and the share button is replaced by rename when it's activated. Also Android shows an icon on the navbar to rotate the screen now, making this feature pretty much irrelevant.
