### ISSUE TITLE
Folder thumbnails messed up

### ISSUE THREAD

**Issue by neekless** [SimpleMobileTools/Simple-Gallery#784]
Folder thumbnails used to be the most recent picture added to the folder. With v4.1.0, folder thumbnails are random pictures in the folder.

**Comment by neekless** [comment]
I realized the thumbnails now change according to the sorting. It doesn't make sense. When I change the sorting on the main screen I want to sort the folders, but not the thumbnails. For example now when I change the sorting to alphabetical ascending, the folders get sorted correctly. But the thumbnails become the picture if the folder contents were sorted alphabetically. But my folder contents are sorted by last modified descending.

**Comment by neekless** [comment]
Attached pictures to show what I mean. In both cases, look at the thumbnail for the 'Pictures' folder, and look at the first picture inside the 'Pictures' folder.

4.1.0: 
https://drive.google.com/open?id=1lcJbCdkHWAxIBhvuz9rHWmlaSc5dnCJD
https://drive.google.com/open?id=1ld_GLX1oMwhAgR5KZIhARedsIHIk_Jyk

4.0.0:
https://drive.google.com/open?id=1VNhPNPi4tioCT28zMO599D9PBdT07dGR
https://drive.google.com/open?id=1VIKlcUB7vjM0cWYVOu9zi9e88gJ85v9S


In both cases, the sorting were the same: folders were sorted alphabetical ascending, folder contents were sorted last modified descending. 

The thumbnail used to follow the folder content sorting but now it follows the folder sorting.

**Comment by tibbi** [comment]
should be fixed in 4.1.1
