### ISSUE TITLE
Does not save this delete option - Gallery

### ISSUE THREAD

**Issue by horpeyloaded** [SimpleMobileTools/Simple-Gallery#787]
#### Expected behavior
After changing the delete option for images to`Do not ask again in this section`,  the delete option should not pop up again when next I want to delete an image.

#### Actual behavior
It keeps asking similar option each time I want to delete image after changing the settings to `Do not ask again in this section`

#### How to reproduce
  - Launch Gallery App
  - Open any Images Folder/Dir
  - Open an Image, click delete image and tick the pop out box `Do not ask again in this section`
  - Open another image and click delete icon.
***
* App version: Gallery v4.0
* Operating system: Android 6.0, Marshmallow
* Device: Tecno C9 Pro

#### Recording Of The Bug

![reo](https://image.ibb.co/m4X3t8/ezgif_com_video_to_gif.gif)

**Comment by tibbi** [comment]
will be fixed in 4.1.x

**Comment by horpeyloaded** [comment]
alright thanks
