### ISSUE TITLE
Thumbnail folder overview shows some folders twice

### ISSUE THREAD

**Issue by STPKITT** [SimpleMobileTools/Simple-Gallery#790]
Hi,
in the main screen where Simple-Gallery shows an overview of all folders (without the hidden/exluded ones obviously) some of my folders show up twice.
The only pattern I could make out about which folders show up twice and which don't is that all the folders that show up twice are on the internal device memory. Non of the folders on the external SD-card show up twice.

I'm running  Simple-Gallery v 4.1.1 installed via F-Droid on a Samsung Galaxy S III mini running Cyanogenmod 12.1 (Lollipop 5.1.1).

I completed deleted all Simple-Gallery data but the problem persists. I didn't have the problem on an older version of Simple-Gallery but sadly don't know after which update the problem came up.

The problem did not occur so far on several other devices of friends running stock firmware and LineageOS (although nobody of them runs Cyanogenmod).

If you need any more information please let me know!

**Comment by tibbi** [comment]
Hi, do you have something in Settings -> Manage Included Folders? 
If you long press some duplicate images and select Properties, do you see the totally same Path? I mean same casing? Or is it like "storage/" and "STORAGE/..."
If you disable "Show all folders content" all folders show up only once?

**Comment by STPKITT** [comment]
Thanks for your fast reply!

1. "Included Folders" is empty.

3. Clicking on "Show all folder content" shows every thumbnail of photos in internal memory twice and when viewing the pictures fullscreen they are also shown twice.

2. That seems to be the culprit! On one of the duplicates the path is "/storage/emulated/0/Pictures" and on the other one it's "/storage/emulated/legacy/Pictures"

So I know wonder if something changed in Simple-Gallery in that regard since nothing in terms of ROM and SD-card memory changed on my device for two years and as I said the "error" wasn't there when I started using Simple-Gallery.

Anyway I guess the solution for Simple-Gallery is to include one of the paths in "excluded folders" by default, but I don't know which of the two paths should be the one since I don't know the inner working of Android storage management.

**Comment by tibbi** [comment]
nobody really knows the inner workings of Android storage management, thats the point. And it even varies between every Android OS version and often by manufacturer. If you send me an email at hello@simplemobiletools.com I could send you a test version which should help solving it. Apparently the internal storage can be referenced in 2 different ways. I was already solving a similar case, guess it was at some other part of the app.

**Comment by STPKITT** [comment]
:-) Yeah, that way of storage management is related to backward-compatibility AFAIK but makes it very complicated first and foremost for newbie endusers, but also for developers.
I'll send you an E-Mail now!

**Comment by Jumbo125** [comment]
I have the same problem. How did you solve it?
