### ISSUE TITLE
cannot upload Pic to planet romeo app using simple gallery

### ISSUE THREAD

**Issue by ale82to** [SimpleMobileTools/Simple-Gallery#795]
I really wonder why simple gallery is such a problematic app tonight I tried to upload a Pic from planet romeo app and I cannot do it the errors is shown on on the screenshot can please some tell me what's Goin on ?
screenshot Link URL: http://sendanywhe.re/R9WLS6YF

**Comment by tibbi** [comment]
link unavailable. Should be fixed already though.
