### ISSUE TITLE
Action buttons on the bottom

### ISSUE THREAD

**Issue by matt31** [SimpleMobileTools/Simple-Gallery#799]
Many gallery apps are putting the main action buttons, or toolbar, on the bottom now. And in my opinion it's much better and easier to access, and it even looks better. So, I make this request, to have an option to put these buttons on the bottom when viewing pictures, and maybe even select what buttons and the order they should be on. I have attached a screenshot of Google Photos, the buttons on the bottom are, from left to right: share, edit, properties and delete.
![screenshot_20180603-162752](https://user-images.githubusercontent.com/6638991/40890405-dee63496-674b-11e8-8832-dba20303bd2b.png)

**Comment by tibbi** [comment]
bottom actions will come in version 4.2. It wont be customizable yet, later it probably will be.
