### ISSUE TITLE
Unable to choose a photo to share on social media.

### ISSUE THREAD

**Issue by Strange-IPmart** [SimpleMobileTools/Simple-Gallery#800]
From Facebook or Tapatalk app, i can not select the photos to share. With the other gallery apps the selected photos are directly shared in the social app with which the sharing is launched, with simple gallery the photo is simply opened without allowing selection for sharing.
Is it possible to check? Thank you

P.s. Oneplus 3T, Resurrection Remix Oreo 8.1 rooted with Magisk 16.4.

**Comment by tibbi** [comment]
what app version do you have?

**Comment by Strange-IPmart** [comment]
Latest v.4.1.1 from Play Store

**Comment by tibbi** [comment]
Hm, how can I make Facebook open Simple Gallery to choose an image? I couldnt find any way of doing it nor in facebook, neither messenger. They always offer only their own gallery. The only way I found was pressing Share from within Simple Gallery, but that obviously works well.

**Comment by helq** [comment]
Hi, I've been having the same problem. Many programs run "Photos" app to pick a photo. To open "Simple Gallery" you need to disable "Photos" from "Settings -> Apps".
