### ISSUE TITLE
Cannot enable photo deletion confirmation 

### ISSUE THREAD

**Issue by Yanpas** [SimpleMobileTools/Simple-Gallery#804]
Currently every photo is deleted without confirmation, it has become broken after several recent updates

**Comment by tibbi** [comment]
1. Do you have the permanent confirmation skipping enabled at the bottom of the app settings? 
2. Are you exiting the app properly with the back button?
3. Do you have "Show all folders content" enabled?

**Comment by Yanpas** [comment]
1. Always skip delete confiramtion is disabled
2. After facing this issue I was killing this app and restarting, but what happened before I don't remember. If you are using sqlite for settings storage it's almost 100% fault tolerant.

I've noticed that if I close app with swiping out from multitask launcher - I don't get confirmation. So IMO the confirmation should be per each Activity.
3. Show all folders content is disabled

**Comment by Yanpas** [comment]
It is app's bug. Swiping away is the correct way to exit application.

**Comment by tibbi** [comment]
nope, onDestroy is not called on swiping, nothing is. Just onStop is called, like when you press the home button.

**Comment by Yanpas** [comment]
Maybe reset confirmation on each `onStop`?
PS I've accidenatelly deleted one screenshot :(

**Comment by Yanpas** [comment]
Or reset it each time user opens picture from folder view

**Comment by tibbi** [comment]
I dont want to do those, I will add some timer in the background like at temporarily showing hidden items

**Comment by tibbi** [comment]
Flags for showing hidden files and skipping delete confirmation will be reset from the next version (4.2.0 or 4.1.2) at app launch, together with a 5 mins background check for reseting it.

**Comment by Yanpas** [comment]
Thanks!
