### ISSUE TITLE
A option to use exif-data to sort pictures

### ISSUE THREAD

**Issue by bandits-git** [SimpleMobileTools/Simple-Gallery#805]
Hello,
It would be nice, if I could use the exif-meta-data to sort my pictures with different name conventions. File data like issue date or date of change are often corrupted after copy/ backup actions.

Best regards
bandits

**Comment by tibbi** [comment]
ye fixing that is on the roadmap. Im relying on the system Content Resolver which is kind of an internal database for storing file metadata for fast querying. Checking actual file exif metadata would be really slow so I dont want to do it that way.
