### ISSUE TITLE
[feature request] keep both when moving/copying images

### ISSUE THREAD

**Issue by gregist** [SimpleMobileTools/Simple-Gallery#818]
Please add a 'keep both' option when the destination folder has files with the same names. 
Better still, make it the default behavior like what they did in QuickPic.

**Comment by tibbi** [comment]
adding a third option for conflict resolution "Append with xxx" is on the roadmap

**Comment by Doubl3MM** [comment]
Hi,

can i work on this issue?

**Comment by tibbi** [comment]
ye

**Comment by Doubl3MM** [comment]
I found that i need to change something in Simple-Commons but that is probably used by other apps as well. Woud be this feature acceptable in other projects as well or should i create other solution?

**Comment by tibbi** [comment]
yeah, just try editing Commons too, so it gets applied to the file manager too. You should be able to trigger the copy/move dialog from the Commons sample activity with some hardcoded values.

**Comment by Doubl3MM** [comment]
Isn't there a possibility to use commons as a local project dependency not as a gradle dependency from external repo and try it directly in some app?

**Comment by tibbi** [comment]
Im not aware of any easy way as I wasnt using it that way. Forking Simple Commons and then including it in your project via Jitpack should be usable.
