### ISSUE TITLE
black screen when i try to open picture's MMS

### ISSUE THREAD

**Issue by tigermick** [SimpleMobileTools/Simple-Gallery#82]
I have a problem when i receive a picture in SMS/MMS.
I touch the picture to open it in fullscreen and Android asks me which application I want use.
If I choice simple gallery to open it, simple gallery start and display a black screen ...
Another people have the same issue ?
Thank you

**Comment by tibbi** [comment]
I havent heard anyone having this issue so far, SMS/MMS is rare nowadays

**Comment by tigermick** [comment]
You are right but this is not rare in france ...sadly ... is it possible to try with your phone please ?

**Comment by tibbi** [comment]
I will take a look at it within the next few days, we will see

**Comment by tigermick** [comment]
Thank you very much

**Comment by Nono-m0le** [comment]
I'm experiencing the same on my HTC 10, android 6.0.1.
Indeed, I'm a French guy too ;-)

**Comment by Nono-m0le** [comment]
Humm.. I just retried (since the new version from today and now... The application crash when I try to open a picture.
Should I open a new issue?

**Comment by tibbi** [comment]
no need, Im already taking a look into it

**Comment by tigermick** [comment]
I have the same problem with 1.49 version. Simple gallery crashes when I try to open a picture from SMS/mms application.

**Comment by tibbi** [comment]
so apparently MMS handling is just another thing google cant make properly. It will take some time to untangle with the help of http://stackoverflow.com/a/6446831/1967672

**Comment by tibbi** [comment]
I just cannot seem to fix it... Ill come back to it later, dont want to spend more time now

**Comment by tigermick** [comment]
OK ! No problem. Just think about us later when you will have more time 😉

**Comment by matejdro** [comment]
This still seems to be an issue. Tried with QKSMS. Tapping on MMS image will open gallery for split second with gray background and then close down (no crash though and no related messages in logcat that I could find).

**Comment by tibbi** [comment]
Ill get there one day, it isnt a priority for now. Thanks
