### ISSUE TITLE
Recycle bin "Restore all files" makes pictures inaccessible

### ISSUE THREAD

**Issue by beachtzig** [SimpleMobileTools/Simple-Gallery#837]
When the Recycle Bin folder appeared for the first time, I deleted it, thinking this would remove everything inside.

I did this several times.

I deleted one picture, and opened the app again. Then almost all of my pictures, including several folders, were in the Recycle Bin folder. This might have been a misclick, but I cannot imagine how.

When I saw this, I went into the Recycle Bin folder and used "Restore all files". Now many errors appeared: "File not found" and "Nullpointer exception".

Afterwards all my pictures were gone. Also the pictures that were not in the Recycle Bin before.

The app data folder is 4.5GB in size, so I think the pictures are still in there somewhere, but I do not have access to a computer with ADB, so I cannot backup the app data.

**Comment by tibbi** [comment]
Hm, weird. In the beginning, what do you mean by deleting the recycle bin? You did a "Empty the recycle bin"?

**Comment by beachtzig** [comment]
No, I selected the Recycle Bin folder by long press, then tapped the delete icon.

**Comment by tibbi** [comment]
aha, maybe that glitches, the recycle bin is supposed to be emptied differently. Ill take a look at it.

**Comment by beachtzig** [comment]
Any idea how to get the pictures back? I only have this non-rooted phone and won't have access to a PC anytime soon. Currently travelling through China by bicycle...

**Comment by tibbi** [comment]
Well Im not sure. If "Restore all files" doesnt work, I dont think there is another way of doing it.

**Comment by tibbi** [comment]
fixed some related glitches and also added an extra check to make sure the files are restored properly before removing them from the bin
