### ISSUE TITLE
Photos are blurry (displayed at low resolution)

### ISSUE THREAD

**Issue by longears** [SimpleMobileTools/Simple-Gallery#84]
When I view an image it's displayed at a lower resolution than the screen supports, resulting in a blurry image.  The difference is clear when switching to the same image in Google Photos.  I'd guess it's being displayed at about 50% the native resolution of the screen, so you have to look at fine details to see the difference.

I can still zoom into the image to get full detail, which appears after I release my fingers during a zoom operation.

I was about to delete a bunch of photos because I thought the camera wasn't focusing well.  Turns out it was just the gallery display.

Device: Pixel with Android 7.1

**Comment by longears** [comment]
This effect is most visible when the device is in portrait orientation and looking at landscape-shaped photos.

**Comment by kilroythe5th** [comment]
I think the problem is that it only renders the image at "fit to screen", and 100%, and nowhere in between, so if the picture is viewed in landscape, and the user zooms in, it keeps showing the image at the same resolution as before, making it look blurry.

**Comment by longears** [comment]
It happens at the default "fit to screen" zoom too.  It seems  to be choosing a lower res to display than the screen is capable of.

**Comment by tibbi** [comment]
Ive actually just spent the last couple hours trying to find a better library for displaying the images, which would allow zooming too. Theres not much to choose from. The one thats actually capable of properly zooming in keeps leaking memory, so if I set it to higher quality, it will just stop displaying images after tens of swipes. Ill have to spend some more time with it.
