### ISSUE TITLE
New default behavior breaks sharing if Gallery is opened through other apps as the default image handler.

### ISSUE THREAD

**Issue by yuukieve** [SimpleMobileTools/Simple-Gallery#843]
At some point, Simple Gallery changed to have the "Share" button only available at the gallery screen instead of the single image screen, resulting in being unable to share images opened in Simple Gallery from another application. 

Reproduction: 
1. Use another application to open an image in Simple Gallery; I used the wallpaper app Muzei. 
2. Observe there's no share button available like there used to be. 
3. Be unable to share the image when opening it in Simple Gallery from another application, necessitating locating it by manually reopening Simple Gallery.

**Comment by tibbi** [comment]
should be fixed in 4.3.4

**Comment by tibbi** [comment]
share button should obviously be visible at opening from gallery too. Isnt it at the bottom actions?
