### ISSUE TITLE
Please make the icon in the center of the video player optional

### ISSUE THREAD

**Issue by SebiderSushi** [SimpleMobileTools/Simple-Gallery#847]
In a recent version this has been added but i find it quite disturbing when an icon is blocking my view while watching a video.
I've always liked the video player of Simple Gallery because it never had this before unlike the stock Android video player for example.
After all the icon only exists to visualize the play/pause tap area and that is quite easy to just memorize in turn for having a nicer UI in my opinion :)

**Comment by tibbi** [comment]
The pause icon fades away after 2 seconds, update your app if it doesnt.

**Comment by SebiderSushi** [comment]
Yes it behaves this way, but it's still there long enough to be disturbing.

**Comment by SebiderSushi** [comment]
Also the icon is persistent while a video is paused. Most of the time I want to take a closer look on a single frame when pausing a video. In this case the icon is rather unpractical. I understand that it is desirable to make it visible that the video is paused so I think it would be pretty nice if I as a user could decide on my own whether the app should do this or not.

I've found this aspect of the player perfect in older versions of Simple Gallery but simply using an outdated version also isn't much desirable.

**Comment by tibbi** [comment]
The UI might get updated in the future, I dont want to change it for now. The icon is quite small and somewhat transparent anyway.
