### ISSUE TITLE
ExoPlayer throws error when playing video files

### ISSUE THREAD

**Issue by Theobald93** [SimpleMobileTools/Simple-Gallery#856]
With the newest version you changed the integrated player.
Sometimes it throws errors but can play the video and sometimes it does not play the video.

CAN NOT PLAY the video: Logcat says:
I/ActivityManager( 1129): START u0 {act=android.intent.action.VIEW dat=content://com.simplemobiletools.gallery.provider/external_files/storage/9016-4EF8/3danim/n3vguv H264.mp4 typ=video/mp4 flg=0x1 cmp=com.simplemobiletools.gallery/.activities.VideoActivity (has extras)} from uid 10159 on display 0
I/ActivityManager( 1129): START u0 {cmp=com.simplemobiletools.gallery/.activities.ViewPagerActivity (has extras)} from uid 10159 on display 0
E/RecentsTaskLoader( 1956): Unexpected null component name or activity info: ComponentInfo{com.simplemobiletools.gallery/com.simplemobiletools.gallery.activities.SplashActivity}, null
E/RecentsTaskLoader( 1956): Unexpected null component name or activity info: ComponentInfo{com.simplemobiletools.gallery/com.simplemobiletools.gallery.activities.SplashActivity}, null
I/ExifInterface_JNI( 8107): Raw image not detected
W/ExifInterface( 8107): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.

[alogcat.2018-07-16-21-15-41+0200.txt](https://github.com/SimpleMobileTools/Simple-Gallery/files/2199092/alogcat.2018-07-16-21-15-41%2B0200.txt)

CAN PLAY the video but throws error: Logcat says the same:
[alogcat.2018-07-16-21-44-35+0200.txt](https://github.com/SimpleMobileTools/Simple-Gallery/files/2199103/alogcat.2018-07-16-21-44-35%2B0200.txt)

CAN PLAY the video SOMETIMES but throws error: Logcat says the same: (File from this one uploaded below)
[alogcat.2018-07-16-21-54-06+0200.txt](https://github.com/SimpleMobileTools/Simple-Gallery/files/2199123/alogcat.2018-07-16-21-54-06%2B0200.txt)
[Testfile mp4.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/2199127/Testfile.mp4.zip)

Videos are in an hidden folder on a sd-card.
Xiaomi Redmi 3
Lineage 14.1
Android 7.1.2 rooted

Simple Gallery 4.3.3 (already reinstalled)
Settings that may be important:
Play videos automatically TRUE
Loop videos TRUE
Allow controlling video value... FALSE
Show extended details over fullscreen media TRUE/FALSE (tested both)

**Comment by tibbi** [comment]
those logs dont really help, and the one you copypasted is not related. Anyway some of the exoplayer related issues have already been fixed in 4.3.4+, update whenever a newer version becomes available. Reopen the issue if it is still broken. Thanks
