### ISSUE TITLE
Click on photo does not bring up the UI elements again

### ISSUE THREAD

**Issue by sir-harlekin** [SimpleMobileTools/Simple-Gallery#857]
Hey there,

if in the picture view mode the UI elements disapper after a few seconds, i can not bring back again. How can the elements be shown again?

Using Ressurection Remix Android Oreo.

Kind regards

**Comment by tibbi** [comment]
what app version do you have? Does it happen at every picture? It happens at videos too?

**Comment by tibbi** [comment]
Can you try toggling the "Replace deep zoomable images with better quality ones" in the app settings? A different library will display images, maybe it will work better. I just want to know which layer breaks it, it works fine on my devices.

**Comment by sir-harlekin** [comment]
ill try and report.

**Comment by sir-harlekin** [comment]
i now tried Quickpic and it works like you said. With simple galery the UI elements still dont come up.

Can i somehow log some data to help you fix the problem?

**Comment by sir-harlekin** [comment]
Well, after installing und removing Piktures Gallery, the UI elements show up in Simple Gallery too. Problem fixed i guess, root cause unknown. I will ping this again, if they start dissappearing again. Thanks for your patience.

**Comment by tibbi** [comment]
heh, I somehow had the feeling that capturing a video of nothing happening will be boring. Ill try reproducing it somehow soon. Thanks

**Comment by sir-harlekin** [comment]
With videos i can pinpoint it to a navigation gesture app i am using. I have to disable the app one time to make videos work. maybe it has to do with the accessebility services it is using? basically the app is always on top watching all inputs. still with quickpic and piktures it is working atm.

https://play.google.com/store/apps/details?id=com.ss.edgegestures

**Comment by sir-harlekin** [comment]
disabling accessibility services does not change the problem. this seems absolutely random.

**Comment by singelais** [comment]
I can replicate the same issue on Oreo, with a minor exception. When I first open a image, and only on the first image, I'm able to say, rotate and image but then the ability to save with the check mark disappears and the status bar cannot be pulled down at all.

I have expanded desktop enabled with lineageos. I also use a magisk plugin to completely disable the navbar; however I think this last part is irrelevant to the issue.

I think it has sometjing to do with hiding the status bar in Oreo - the same exact setup worked flawlessly in Nougat

Temporarily disabling expanded desktop for the gallery allows the normal functionality of UI elements.

**Comment by sir-harlekin** [comment]
i also use expanded desktop.

**Comment by tibbi** [comment]
should be better in 4.4.x, let me know if not

**Comment by sir-harlekin** [comment]
Can i test the version right now or wait till release on play store?

**Comment by tibbi** [comment]
send me a mail at hello@simplemobiletools.com, that will be the simplest

**Comment by singelais** [comment]
As of version 4.4.0 the issue is still there.

**Comment by tibbi** [comment]
will be fixed in 4.4.1 only. 4.4.0 was just a test version released to a few people plus f-droid, as I cannot limit it there.
