### ISSUE TITLE
Share image from Personal to Work Profile

### ISSUE THREAD

**Issue by ghost** [SimpleMobileTools/Simple-Gallery#868]
Because the managed profile and the personal profile use separate storage areas, so can't use gallery to share an image inside apps of work profile and I read the relevant developer documentation that FileProvider may solve this problem.

Can the next version provide this feature?

Thank you.

**Comment by tibbi** [comment]
not sure what you mean so it probably wont be fixed anytime soon, but Ill take a look at it someday.
