### ISSUE TITLE
Nokia custom camera app not openening photo with Gallery

### ISSUE THREAD

**Issue by TeeTeeHaa** [SimpleMobileTools/Simple-Gallery#877]
- Nokia 5
- Android 8.1 with all updates
- Nokia's custom preinstalled camera app, version 8.0250.80 (generic version available in [Play Store](https://play.google.com/store/apps/details?id=com.evenwell.camera2&hl=en), but the Play Store says it is not compatible with my device, so it's probably a version customized to Nokia 5)
- SimpleMobileTools' Gallery version 4.3.5
- Google's Photos app is disabled

![nokia-camera](https://user-images.githubusercontent.com/739754/43356636-b0c4c286-9274-11e8-9e6a-81adcf2aa473.jpg)

Inside Nokia's custom camera there is a thumbnail of the last photo taken (purple arrow in screenshot). When touching that thumbnail, nothing happens. My expectation is, that this photo is opened with the default photo/picture/gallery app, in my case SimpleMobileTools' Gallery. As far as I remember Google's Photos app had been opened when it was my default photo/picture/gallery app, before I used all the SimpleMobileTools apps.

I guess (not being a Android developer) that either SimpleMobileTools' Gallery is not my photo/picture/gallery app (how would I set that?) or that SimpleMobileTools' Gallery does not supply the Android intent being made by Nokia's camera app.

I do have a logcat file - you need that? Unfortunately I can't find any interesting information in it.

Finally: I consider the severity of this bug "nuisance".

**Comment by tibbi** [comment]
Please try downloading some other gallery, then pressing the thumbnail and see if something happens

**Comment by TeeTeeHaa** [comment]
I tried it with [LeafPic](https://gitlab.com/HoraApps/LeafPic/blob/HEAD/README.md), another open source gallery from F-Droid. It does not work with this one, too.

As soon as I enable the Photos app, the photo is opened with that app.

**Comment by tibbi** [comment]
from other reporters too it seems like Nokia camera is tied to Google Photos only
