### ISSUE TITLE
[Feature Request] IExif fixer 

### ISSUE THREAD

**Issue by MikuDroid** [SimpleMobileTools/Simple-Gallery#878]
Please kindly add IExif fixer as seen on picture viewer app called [QuicPic](https://play.google.com/store/apps/details?id=com.alensw.PicFolder)

**Comment by chris-w89** [comment]
The dev allready done this in the last build 4.4.0

**Comment by tibbi** [comment]
well it depends what exif values he means. Fixing Date Taken should be possible in 4.4.0 indeed. If you mean other values, specify them.

**Comment by MikuDroid** [comment]
how do i access the date fixer? i can't find any here..
