### ISSUE TITLE
Enableling bottom action items crashes app when opening a picure with immersive mode

### ISSUE THREAD

**Issue by sir-harlekin** [SimpleMobileTools/Simple-Gallery#890]
Since the 4.4.1 preview fixed the UI elements with immersive mode enabled; if i enable botton action items and try to open a picture, the app crashes.

**Comment by tibbi** [comment]
retry with 4.4.4 please whenever it becomes available, some related crash has been fixed

**Comment by sir-harlekin** [comment]
fixed with 4.4.4 - thanks.
