### ISSUE TITLE
Cannot move files to SD card

### ISSUE THREAD

**Issue by Sixthhokage1** [SimpleMobileTools/Simple-Gallery#891]
Whenever I try to move photos from internal storage to SD card, the Gallery app gives me the error "SD card and OTG device paths cannot be the same". There is no OTG device. This is with Android 5.0.1

**Comment by tibbi** [comment]
guess you selected an OTG path in the past. Try doing a "Clear Data" on the app from your device settings to clear the app, it will reset the settings, recycle bin and favorites. Then you should be able to select the path properly. Fixing it better is on the roadmap, it should be already reported somewhere.

**Comment by Sixthhokage1** [comment]
Opening after clearing data, it immediately asks for SD card access. Granting it then ends up with it asking again when interacting with SD files and the error happens again. It only works if the initial access granting is skipped.

I do have it working now, thank you.
