### ISSUE TITLE
Support HEIF image file in android p

### ISSUE THREAD

**Issue by livelazily** [SimpleMobileTools/Simple-Gallery#893]
Android p now support HEIF images encoding: 
https://developer.android.com/about/versions/pie/android-9.0#hdr_vp9_video_heif_image_compression_and_media_apis

Sample files can be found here: https://github.com/nokiatech/heif/tree/gh-pages/content/images

**Comment by utack** [comment]
Maybe it can be done indipendently of system using something like https://github.com/strukturag/libheif

**Comment by tibbi** [comment]
that isnt an android library, just something generic

**Comment by mrJohnNova** [comment]
People send me many images from iPhone. I really need support HEIF image file. Standard Gallery supports this format. But I want to use your application.

**Comment by tibbi** [comment]
I was trying to support it already, but so far I found no way of doing it. Hopefully some way of supporting it will pop up soon.

**Comment by johnkarpn** [comment]
Maybe you add support for HEIC files in Android Pie only? 
https://developer.android.com/about/versions/pie/android-9.0#media

**Comment by tibbi** [comment]
it's too difficult to support manually like that, I'll take a look at it someday again, if there is any better solution out there already

**Comment by tibbi** [comment]
support will be added in the next version 6.8.3. Turns out it is basically supported by default already, guess I was testing it too early previously.
