### ISSUE TITLE
Custom icon color not set with Nova Launcher 6.0 beta 1

### ISSUE THREAD

**Issue by ouzowtf** [SimpleMobileTools/Simple-Gallery#897]
I don't know what exactly Nova changed and don't want to say the Simple Mobile Tools (all of your apps seem to be affected) are buggy in this case, but only want to inform you about this issue.

The icon gets removed (after some time) from the desktop when I change the color in the settings of for example Simple Gallery, but doesn't change the color in the app drawer to have the ability to put the new icon back again on the desktop.

**Comment by tibbi** [comment]
That is the intended behaviour, thats how the system works. Icons have to be moved back to the desktop after changing the color.

**Comment by ouzowtf** [comment]
But the color in the app drawer doesn't change anymore!
I change the icon color in the app to blue, red or whatever, but it stays orange in the app drawer. Worked perfectly fine till the Nova update came out.

**Comment by tibbi** [comment]
if it used to work I dont think it is an issue on my side, I can recheck it someday.
