### ISSUE TITLE
Some parts of the UI are visibly hidden when background and primary color are the same

### ISSUE THREAD

**Issue by ouzowtf** [SimpleMobileTools/Simple-Gallery#898]
Seen in for example the activated switch in the settings or the text in the about screen.

[Screenshot1](https://drive.google.com/file/d/10Vs6WmcgT1yVQqyGzQmKqOWlK_J5WVkt/view?usp=sharing)
[Screenshot2](https://drive.google.com/file/d/1p22ItGxXDuB8pWvGWpVBn9yxO2St9yd2/view?usp=sharing) 

This affects the other Simple Mobile Tools apps too.

**Comment by tibbi** [comment]
if you select the same colors, some parts will obviously get hidden. Not much to do there.

**Comment by ouzowtf** [comment]
What about using font color for those elements, when primary and background color are the same?

**Comment by tibbi** [comment]
I dont want to complicate it like that for now, maybe someday in the future.
