### ISSUE TITLE
Not able to undo deletion

### ISSUE THREAD

**Issue by kTyn9A9Kw3** [SimpleMobileTools/Simple-Gallery#9]
Although there is a small button on the corner to undo deletion when viewing images, it's not possible to undo if there is only 1 picture on the device or folder because the screen exits immediately.
As a suggestion, you could use the same bottom notification on both actions (deleting from view folder/image).

**Comment by tibbi** [comment]
there is already a confirmation dialog at Deletes, so I wont be adding an Undo for these rare cases
