### ISSUE TITLE
PNG quality

### ISSUE THREAD

**Issue by Rikk** [SimpleMobileTools/Simple-Gallery#90]
First of all, my congrats for your initiative of creating such a nice collection of apps with nice design and 100% clean. My good wishes for you! Keep it as is and don't get sold to practices harmful to users' privacy.

Thanks for "Allow swiping between images when app is open from another app" added in 1.45.

Now, I think the "Display pngs in higher quality" still needs a bit more care. Some PNG files are still displayed with bad quality. In the following example, azul0c is ok, but azul1c is bad:

![azul0c comp](https://cloud.githubusercontent.com/assets/2916485/21086031/d4c864c4-bfff-11e6-840b-0ee7a58b9274.png)

![azul1c comp](https://cloud.githubusercontent.com/assets/2916485/21086033/d6c8da9c-bfff-11e6-9485-3222fd97b525.png)

Original files: [azul.orig.zip](https://github.com/SimpleMobileTools/Simple-Gallery/files/645005/azul.orig.zip)

PS: I haven't tested if this quality issue also happens with other file formats.

May I reuse this Issue topic for some extra suggestions?

1. Bug: files which name start with # are not opened nor displayed.
1. Another thing I think would be very useful is a mini horizontal gallery at bottom ('carousel' style) like in the Gallery app from Samsung.
1. Add 'Settings' link in image menu, because when it's opened from external app there isn't way to access main screen (back key will close).
1. Add option to override system Screen Rotation defaults, in QuickPic we can define auto/portrait/landscape for the app itself, independently of what is defined in Android.
1. Make APK available in Releases.

**Comment by tibbi** [comment]
its most likely related to PNGs only. I still havent found a library capable of properly zooming in, that I would be satisfied with.
 Thanks for the other reports, Ill consider them.

**Comment by Rikk** [comment]
Basically, in this case at least, the problem happens only with Flattened images (ie. background only, no layers); in PNGs with a layer (not flatten) it is ok!

(Note: in Gimp, images with visible layer are considered as having an Alpha channel, while in Photoshop they are displayed as unlocked layer (meaning not flatten image)).

I see you use a lib called glide. Did you look at this tip already: https://github.com/bumptech/glide/issues/650 ?

I would risk saying it might be: cache issue (as in linked issue), or images without alpha need different approach. What do you think?

**Comment by tibbi** [comment]
for loading the thumbnails I use glide, PNGs there should be better than they used to. However for fullscreen images Im using https://github.com/davemorrissey/subsampling-scale-image-view , as that contains the zooming feature. And it has real zoom that actually rerenders the selected area for better quality, it doesnt just enlarge the selected area producing crappy quality, like some libraries do.

**Comment by Rikk** [comment]
Wouldn't it be helpful to open an Issue there? Want me to open it referencing here?

**Comment by tibbi** [comment]
no need, I can experiment in the future. The reason is described at the important notes at https://github.com/davemorrissey/subsampling-scale-image-view/wiki/02.-Displaying-images
