### ISSUE TITLE
Manage extended details shows wrong information

### ISSUE THREAD

**Issue by m4mmon** [SimpleMobileTools/Simple-Gallery#909]
Hello,

I am using extended details to show information about pictures, and have issues with two choices from "Manage extended details" settings:

1/ Date taken
Date taken shows file date. For example I take a raw picture with my camera, then export it as jpeg with Light room. File date is of course the export date. However, "date taken" is an exif metadata, and Simple Gallery shows that as "Date taken".
"Date taken" should either be labeled "File date", or, better, should show the real "Date taken", and another option should be present to allow displaying "File date".

2/ EXIF
When selected, we can see aperture, focal length, exposure time and ISO value.
Exposure time is always shown as "1/0s" if value is above 1 second.
Correct value should be displayed.

Thank you for this great program :)

**Comment by tibbi** [comment]
what app version do you have?

**Comment by m4mmon** [comment]
It is v4.4.4

**Comment by tibbi** [comment]
Try updating to 4.5.2 please, if you see the same issues.

**Comment by m4mmon** [comment]
Will look how to do that, F-Droid does not offer such version.

**Comment by m4mmon** [comment]
Got the 4.5.2 version from github, but cannot install it.
Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package com.simplemobiletools.gallery signatures do not match the previously installed version; ignoring!]

I guess I could simply uninstall F-Droid installed version, but to be honest I do not want to lose all my settings.

**Comment by m4mmon** [comment]
OK, sorry forget my previous comment, F-Droid depots were not up to date.

So, tested 4.5.2, same info is displayed as previous versions.

**Comment by tibbi** [comment]
try long pressing the file thumbnail and selecting "Fix Date Taken value", to see if it changes anything

**Comment by m4mmon** [comment]
It does not change anything.

**Comment by tibbi** [comment]
what you mean by "File Date" is probably the last_modified field, it is already there

**Comment by m4mmon** [comment]
Yes you are right. In fact, I was thinking about the file informations you have on some file systems, like "Date created" and "Date modified". If I have not been clear in my previous posts, I mean the "Date taken" acts like a "Date created" or "Date modified", and does not seem to use the EXIF metadata "date taken". May be this information as it is shown today is useful for some people ; keeping it might be important for them, but also having a real "date taken" option which value would be extracted from EXIF would be really nice.

**Comment by m4mmon** [comment]
So I am doing something wrong, or not getting something about "date taken". I have this picture for example:
Date taken:
![props1](https://user-images.githubusercontent.com/14895736/44114533-f609b9f8-9ffa-11e8-8d87-91cb96a3c7f3.png)
this one is just to show the exposure time:
![props2](https://user-images.githubusercontent.com/14895736/44114534-f62d0c82-9ffa-11e8-98f3-cec266a572e0.png)
File system properties:
![props3](https://user-images.githubusercontent.com/14895736/44114679-6f484c94-9ffb-11e8-875d-0aa90d9092f5.png)

In Simple Gallery, I have set this:
![screenshot_20180814-214149](https://user-images.githubusercontent.com/14895736/44114544-fd29db64-9ffa-11e8-82c3-caf765b58820.png)
And get these infos:
![screenshot_20180814-214158](https://user-images.githubusercontent.com/14895736/44114546-fd4dc65a-9ffa-11e8-8a68-12dffdf6ddd6.png)

**Comment by tibbi** [comment]
I dont see what is the issue there. It shows 5.8.2018 on most screenshots as the creation date, that first screenshot has something wrong.

**Comment by m4mmon** [comment]
?
5.8.2018 is the file date.
Date taken is 4.08.2018 21:46. I was there, and it is written in EXIF.

**Comment by m4mmon** [comment]
I think we do not understand each other. EXIF data dump for the same picture:
![exif](https://user-images.githubusercontent.com/14895736/44115575-d059a3d2-9ffd-11e8-8c1e-ea1299957975.png)

**Comment by tibbi** [comment]
there is no such things as File creation date. A file can either have a last modified field, or other dates stored in EXIF. I will take a look at it later, working on something else now. From the screenshots everything looks ok.

**Comment by m4mmon** [comment]
Yes, I get you are working on something else.
Please just listen that I suspect the program is not reading the appropriate date in exif.
Last screenshot, and I stop annoying you :)
![exif2](https://user-images.githubusercontent.com/14895736/44115900-8c8decfc-9ffe-11e8-96b7-1667a9ec3b81.png)

Date taken is not last modified date or anything, at all, especially when you shoot raw files and develop them later.
Thank you for your patience.

**Comment by m4mmon** [comment]
More info:
From https://android.googlesource.com/platform/frameworks/base/+/master/media/java/android/media/ExifInterface.java
new ExifTag(TAG_DATETIME, 306, IFD_FORMAT_STRING),
...
new ExifTag(TAG_DATETIME_ORIGINAL, 36867, IFD_FORMAT_STRING

306 ==> 0x132 : "ModifyDate", "called DateTime by the EXIF spec."
36867 ==> 0x9003 : "DateTimeOriginal", "date/time when original image was taken"

**Comment by tibbi** [comment]
ye that might be the issue, I think Im using TAG_DATETIME. I will have to check if TAG_DATETIME_ORIGINAL is widely used too

**Comment by tibbi** [comment]
Starting from version 4.6.0 Ill prefer date_time_original instead of date_time at "Fix Date Taken values" and at the properties dialog / extended details. Let me know if it still misbehaves somehow.

**Comment by m4mmon** [comment]
Now "date taken" is correct! thank you :)
Exposure time still shows "1/0s" for long exposures.

**Comment by tibbi** [comment]
ye, report all issues separately
