### ISSUE TITLE
Shortcut for starting the slideshow

### ISSUE THREAD

**Issue by pmattke** [SimpleMobileTools/Simple-Gallery#915]
Just wanna quickly start a slideshow, lean back and watch?

I think, a long tap on a photo or video would be a nice way for a shortcut to just start the slideshow with the previously used settings. 

I am not quite much into android development and kotlin, but I tried my best and I have a branch almost ready which implements such a feature. If you want, I can push it and create a pull request :)

**Comment by tibbi** [comment]
I dont like the idea of starting a slideshow with long pressing. Maybe you can add the slideshow button to the bottom actions, then it is really easy to start.

**Comment by pmattke** [comment]
Also a good idea. I will implement this when I have time in the next days and create a pull request.

**Comment by tibbi** [comment]
I dont really want a feature that long pressing with trigger slideshow

**Comment by pmattke** [comment]
I know, therefore I will leave the long-tap-part out. But I like the idea you described, of having a button at the bottom actions that can be used for quick-starting a slideshow, and if that's something you would accept, I would implement it

**Comment by tibbi** [comment]
it is already there. In case you dont have the bottom actions visible, toggle it in the app settings. Once enabled, you can customize which buttons are visible there.

**Comment by pmattke** [comment]
Yep I found it. Nice! I did not know that the bottom actions are configurable :)
