### ISSUE TITLE
Sort by/Group by Date Taken

### ISSUE THREAD

**Issue by mklopp** [SimpleMobileTools/Simple-Gallery#917]
Hi,
I have a problem using the the sort by and group by date taken feature as in it doesn't work like I expect it to work.
I have a few images taken on say 23.07.18 and some on the 19.07.18. If I select Group by to not group them and just select Sort By "Date taken" descending some of the files taken on the 19th will show up over the files on the 23th while I expect them to be below these. Same is for Group By. If I Group by Date taken then some of the images taken on 19th will get grouped with the ones on 23th into the 23 group. I know the date taken from looking into the properties feature.

I should note that I moved these files, so last modified differs from date taken (last modified for the images is the 23th for all of them). So I guess there is some mix up between last modified and date taken.

I would and probably will look into the code myself but I first have to find the right pieces and am neither a Kotlin pro.

Hope my Issue is understandable. If not feel free to ask for further information.

**Comment by mklopp** [comment]
Sorry I just saw the "Fix Date Taken value" entry which magically fixes the Issue. But shouldn't that be done automatically? If not feel free to just close this Issue.

**Comment by tibbi** [comment]
I dont really want to do such things automatically
