### ISSUE TITLE
[Feature request] Add option to show only hidden files

### ISSUE THREAD

**Issue by ertomentis** [SimpleMobileTools/Simple-Gallery#919]
As in the title, an option that allows browsing only hidden files, but showing them in the original folder structure, would be quite useful.

A probably quicker way to achieve similar results would be to add a checkbox in the sorting menu or settings that would sort by whether the file is hidden or not first, and by other options second, putting the hidden files on top of folder / folders with hidden files on top of folders list, maybe with some indicator showing whether the folder has any such files.

**Comment by tibbi** [comment]
I dont really like such an unnecessary feature, so far noone needed it either.
