### ISSUE TITLE
Icon for rotating images (?) in editor

### ISSUE THREAD

**Issue by MartinGSch** [SimpleMobileTools/Simple-Gallery#923]
When editing a picture the last icon is doing nothing for me. From the look of the icon I guess it is for rotating the picture in other angles then 90 or 180 degrees (right?) but I can't get this or anything else done. If it should be for something else, please apologize, then the look of the icon has misled me.
After beginning to edit the icon is highlighted, see the bottom right of the first screenshot. And when I tap on it, the highlighting disappears as well as other editing icons... and that's all I have achieved.

![screenshot_20180820-214344](https://user-images.githubusercontent.com/42523039/44362911-d3462380-a4c2-11e8-9329-eca068ed5d62.png)

![screenshot_20180820-214350](https://user-images.githubusercontent.com/42523039/44363075-549db600-a4c3-11e8-844c-9a0f9af596d9.png)

**Comment by tibbi** [comment]
that is the crop/rotate actions toggle. It shouldnt do anything itself, just activate and show the secondary actions.

**Comment by MartinGSch** [comment]
Ah, now I see, and with that explanation I recognize the logic behind.
But I would maintain that it is a trap for usability, what has mislead me is that the crop/rotate toggle is actually like a navigation button but it looks like all other action buttons. I was expecting to be able to modify the picture when this button is tapped - as it is for the others.
With the current set of editing options you could get along with two instead of three rows of buttons:

- remove the crop/rotate button and move the one for filter effects into one row with the others
- when tapped, the button for filter effects would show it options in the line above, where also the options for different aspect rations (free, 1:1, 4:3 etc.) appear when needed. More consistent.
Think about it... I would find it more logical and user friendly - and simpler, as it is your main intention.
