### ISSUE TITLE
[Feature Idea] Scaling algorithm selection

### ISSUE THREAD

**Issue by olifre** [SimpleMobileTools/Simple-Gallery#925]
It might be useful, especially for people with huge files, to allow to select a good (but slow) scaling algorithm like Lanczos3 / neural network scalers or a fast, but not-as-good algorithm such as simple Bilinear scaling.

**Comment by tibbi** [comment]
what? O.o better image loading is already on the roadmap, it just isnt that simple.

**Comment by olifre** [comment]
Yeah, I was thinking of something along the lines of what `Perfect Viewer` offers. Sadly, they are closed source, so im unsure how they "easily" offer many different scalers.

**Comment by Rikk** [comment]
@olifre I didn't know about Perfect Viewer and it looks great and very powerful! Thanks for the tip! I used to use AA Image Viewer when I wanted to zoom images without anti-aliasing... Now, learning Perfect Viewer.
