### ISSUE TITLE
"What's new" feature

### ISSUE THREAD

**Issue by MartinGSch** [SimpleMobileTools/Simple-Gallery#926]
This morning I found a notification on my phone that a new gallery version 4.6.1 was automatically installed.
I expected to see a list of what has changed as I have the setting "Avoid showing What's New on startup" is deactivated.
But nothing new was displayed...
I have also closed the app and restarted, to ensure that it is not only brought to the front from the background.

**Comment by tibbi** [comment]
Im showing that dialog only at major features, not every update. That would be way too annoying.
