### ISSUE TITLE
Improve user experience for key menu options

### ISSUE THREAD

**Issue by MartinGSch** [SimpleMobileTools/Simple-Gallery#927]
I think the key options that determine how the media files are presented can be offered more clearly for a better user experience.
There are two which determine the overall presentation of media files:
-  The menus "Show all folders content" resp. "Switch to folder view" to toggle between a display of folders or all media files  (_what_ is displayed)
-  The menu "Change view type" to toggle between grid and list view (_how_ items are displayed)
They are essential because they drive not only the overall appearance of the main screen but also which options are available in the menu at the top right.
After installing the app it has taken me a while to figure this out when trying all the different menu optinos and features... because these two options are offered inbetween less significant items of the menu that look the same.

My proposal is to improve the user experience by two changes:
1. Make these two menu items always the first two in the same order.
Ok, the filter one is also essential, maybe have these three on top - but _consistently at the top and in the same order_.
1. Both menu items are for a toggling between two different options, so same type of choice - but implemented differently, leading to different user experience:
For "change view type" a pop up window opens with the two choices. 
For "show all folders content" / "switch to folders view" the menu changes and offers a different entry to switch back. To have always the same menu item, e.g. "change items displayed" and a pop up window with a choice "folders" and "all folders' content" would make it consistent with the other key choice and clearer for the user.
Maybe worth considering to integrate the filtering options for file types here but that would be a second step.

**Comment by tibbi** [comment]
"Change view type" will get more options soon, that's why it is shown differently. I definitely dont think that people change the view type or toggle "show all folders content" often, so I dont want to mess with that. "All folders" might be shown as a folder someday in the future optionally if many people will start asking it, so far it didnt happen. The order of menu items and amount of shown icons is determined by the system, that should not be set manually.
