### ISSUE TITLE
Extended details in fullscreen: shown EXIF values are wrong for long exposures

### ISSUE THREAD

**Issue by m4mmon** [SimpleMobileTools/Simple-Gallery#928]
Hello,

Simple Gallery 4.6.0 (same with previous versions)
Android 8.1.0
If Settings/"Extended details"/"Show extended details over fullscreen media" is checked, and EXIF option is checked in Settings/"Manage extended details", aperture / focal length / exposure length / ISO value are shown.
If exposure length is long, (1 second and above), displayed text is "1/0s".
I do not exactly know when exposure length value starts to be false.
There is an example in incident #909 with a 20s exposure, exif details, etc.

Thank you.

**Comment by tibbi** [comment]
@m4mmon can you send me a sample image at hello@simplemobiletools.com please, and tell what should be the correct value? Just to be sure :) Thanks

**Comment by m4mmon** [comment]
Just sent a few pictures with various time exposure values.

**Comment by tibbi** [comment]
will be fixed in 5.0.2

**Comment by m4mmon** [comment]
thanks :)
