### ISSUE TITLE
[Feature Request] Animated PNG

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimpleMobileTools/Simple-Gallery#93]
[APNG](https://en.wikipedia.org/wiki/APNG) is an extension to PNG, this format work similarly to animated GIF files, also support 24-bit colour and 8-bit transparency which not available in GIFs.

**Comment by KrasnayaPloshchad** [comment]
You can try to get support with this library.
https://sourceforge.net/projects/libpng-apng/

**Comment by KrasnayaPloshchad** [comment]
Altenatively, you can tey to add a patch to parse APNG specific data, then feed them into libpng. See:
https://chromium.googlesource.com/chromium/src/+/7d2b8c45afc9c0230410011293cc2e1dbb8943a7
https://dxr.mozilla.org/mozilla-central/source/media/libpng/apng.patch

**Comment by maverick74** [comment]
what's the state of this feature request?

Is there any plans for it?

I'm voting this as well since i would very much prefer apng rather than webp (which is already implemented).
From a few reviews i've read apng seems a little superior to webp....... 

please add support for it (at least in the pro version)!!! :)

**Comment by tibbi** [comment]
I wasnt researching it yet at all, havent really seen people requesting it. WebP was mentioned a lot more often, so I added that.

**Comment by maverick74** [comment]
i personally prefer apng, but there are a few examples that show it's superiority over webp.

is there a chance we can expect support for it soon?

**Comment by tibbi** [comment]
not sure, probably not soon

**Comment by sbrl** [comment]
[According to Caniuse](https://caniuse.com/apng), Animated PNG is now supported by all major browsers.

**Comment by KrasnayaPloshchad** [comment]
Mozilla has a patch for this.
https://dxr.mozilla.org/mozilla-central/source/media/libpng/apng.patch

**Comment by maverick74** [comment]
Signal messenger also added support for it recently. In fact, from what i understood (i may have gotten it wrong) they're basing their animations on apng.

**Comment by tibbi** [comment]
can you tell an android app that supports apng? I cannot find any

**Comment by tibbi** [comment]
or nevermind, will be added in 6.20.4

**Comment by maverick74** [comment]
Any ETA for it to be released on Stores?

**Comment by tibbi** [comment]
it is already on Google play, should be on f-droid soon

**Comment by maverick74** [comment]
@tibbi I think i found a bug (unless it's on purpose):

an animated image only plays it it's extension is **.apng**, if it is just **.png** (but still animated) it appears as static.

You can take a look at the Wikipedia example at [APNG](https://en.wikipedia.org/wiki/APNG) . The ball image is a .png file but it's still animated.

**Comment by tibbi** [comment]
I want to keep the current behaviour and not try to animate png files, will see if it needs changes in the future

**Comment by maverick74** [comment]
No stress... it's just a question of renaming the file extension to **_.apng_**.
I understand that this way it has the benefit of distinguish which ones are animated and which ones are not.

Still, i'll manifest my vote for it, in the future, include .png as well. :)
