### ISSUE TITLE
Proposal to resize by fingers

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [SimpleMobileTools/Simple-Gallery#94]
I guess you can create a function to resize the image by fingers. This can be done by following methods:
1. Use double fingers to zoom in or zoom out.
2. Double click to resize, you can allow this gesture to let the picture display with 100% large.

**Comment by tibbi** [comment]
You mean like permanently change photo size? I want to keep all editing functions inside the Editor part, not spread it all around.

**Comment by KrasnayaPloshchad** [comment]
Yeah I like to change photo size, but not permanently.

**Comment by tibbi** [comment]
well you can already zoom in with pinch no? On the page where the photo is fullscreen

**Comment by KrasnayaPloshchad** [comment]
Well, this app cannot zoom with pinch.

**Comment by tibbi** [comment]
zoom was implemented ages ago, what version of the gallery do you have? The number at the bottom of About page

**Comment by KrasnayaPloshchad** [comment]
I used v1.51. Now I am clear what’s wrong with me. For example, after download [this image](https://en.wikipedia.org/wiki/File:Animated_PNG_example_bouncing_beach_ball.png) (which is smaller than screen resolution) in my phone and open it, zoom operations does not work.

**Comment by tibbi** [comment]
well its 100x100, so by showing it fullscreen its already stretched to the limit. It works fine for photos so Ill close it.

**Comment by KrasnayaPloshchad** [comment]
Is it possible to add an option to allow these images display with 100% size?

**Comment by tibbi** [comment]
I can check it, but I dont want to spend too much time on it

**Comment by KrasnayaPloshchad** [comment]
I think this is not so hard to do, and necessary for viewing animated images, many of them I have seen on the Internet is smaller than phones
