### ISSUE TITLE
Zoom doesn't work for the first second when image is loaded 

### ISSUE THREAD

**Issue by Solarunit** [SimpleMobileTools/Simple-Gallery#944]
Hi. I've noticed a problem with zoom after update. 
Zoom doesn't work for the ~ first second when image is loaded. 

Simple-Gallery 4.6.2, android 9

**Comment by tibbi** [comment]
it has been like that for quite some time now, it is waiting for the image to get fully loaded. It is intentional for now, it needs more changes to work better.
