### ISSUE TITLE
Global colours for simple Tools don't work

### ISSUE THREAD

**Issue by alpenblauwtje** [SimpleMobileTools/Simple-Gallery#945]
Today I discovered that I can change the colours of all Simple Tools apps at once, at least if you have bought the Simple Thank You app. The latter is the case, so I changed both app and icon colours to blue in the Gallery app. However they don't change, not in the file manager (app colour), not the icons (file mgr and thank you app).

**Comment by tibbi** [comment]
that is mostly a launcher issue from https://github.com/SimpleMobileTools/General-Discussion/issues/83#issuecomment-419615211 , try downloading some other one if it will work.

**Comment by tibbi** [comment]
Ill close this, as a duplicate report is already created, as written above
