### ISSUE TITLE
how to do photo ratio transformation "9:16" ?

### ISSUE THREAD

**Issue by benjamin-bin-shen** [SimpleMobileTools/Simple-Gallery#947]
good app! however not figured out how to do 9:16 transformation. only "free", "1:1", "4:3", "16:9" are possible. would you advise how?

**Comment by tibbi** [comment]
you cannot do it now, ratios will be tweaked later

**Comment by benjamin-bin-shen** [comment]
if it is not a big deal, please add the feature asap. thx!

**Comment by Theobald93** [comment]
Already implemented. #close?
