### ISSUE TITLE
"Create Date" isn't shown for Videos

### ISSUE THREAD

**Issue by mist** [SimpleMobileTools/Simple-Gallery#950]
Videos I take do have a `Create Date` and a `Modify Date` in their Headers. 
`exiftool` shows them correctly, but the gallery seems to ignore them making them sort by Filesystem modify date (which nextcloud android sets to the sync (download) date instead of the real modify date).

Is there a way for Gallery to retrieve this date and order accordingly?

**Comment by tibbi** [comment]
what app version do you have? Try long pressing the video thumbnail and select "Fix Date Taken values".

**Comment by mist** [comment]
I'm using 4.6.2 and "Fix date taken" doesn't seem to do anything except showing a toast "Fixing..." and then "Date fixes successfully".

**Comment by tibbi** [comment]
seems like videos dont have such EXIF values
