### ISSUE TITLE
Dark theme suggestion

### ISSUE THREAD

**Issue by neekless** [SimpleMobileTools/Simple-Gallery#951]
I don't know what you feel about this, but if I'm using dark theme, I feel that the 3-dot menu should also be dark with white text. Now it's still white with black text.

Would like to hear from you what you think. If it's not something you wanna change, it's fine too. :)

**Comment by tibbi** [comment]
ye it is on the roadmap, but changing it isnt easy. Anyway it affects all apps and it is already reported at https://github.com/SimpleMobileTools/General-Discussion/issues/24 , so Ill close it. Thanks
