### ISSUE TITLE
After updating the app, popup What's New doesn't show up

### ISSUE THREAD

**Issue by CatKasha** [SimpleMobileTools/Simple-Gallery#958]
After updating the app, popup What's New doesn't show up

How to reproduse:
1. install the penultimate version of the program from the F-Droid
2. launch the app and close
3. update the application with the latest update from the F-Droid

As i remember after the update should appear What's New

(sorry for my english)

**Comment by tibbi** [comment]
it doesnt appear at every update, just at the more major changes

**Comment by CatKasha** [comment]
Thanks for the answer
