### ISSUE TITLE
Option for hand drawing while editing 

### ISSUE THREAD

**Issue by jerryn70** [SimpleMobileTools/Simple-Gallery#961]
Currently we have crop, filters and few other options. Bug we don't have the ability to draw anything . So it will be a good thing if we have hand drawing brush tool with different colors and size option. 

The main purpose of  requesting this option is because, I test most of the open source apps available in internet and report issues/feature requests. When reporting an issue I need to take screenshot and mark the bug . 
So I was forced to use big pic editing apps that really dont want .

**Comment by tibbi** [comment]
it will be added someday, duplicate of #851

**Comment by jerryn70** [comment]
Oops sorry for the duplicate :relaxed:
