### ISSUE TITLE
Feature Request: Don't show Pause Button over video when starting playback

### ISSUE THREAD

**Issue by Riotous** [SimpleMobileTools/Simple-Gallery#966]
When playing a video from the grid, the video plays in fullscreen but there's a pause button over it that takes a while to go away while the video plays. Can we not have the pause button show up when first playing the video? It would be nice to just have the video play unobscured until we decide to tap it to pause.

Basically, it would be nice to have the video start to play without anything covering it.

**Comment by tibbi** [comment]
the pause button might be moved somewhere, we will see. But I dont want to just remove it. It fades away in like 3 secs, it isnt that much. Some UI report already exists so Ill close this though.
