### ISSUE TITLE
Some images not opening

### ISSUE THREAD

**Issue by MuSqUlA** [SimpleMobileTools/Simple-Gallery#97]
Several image files will not open. They will properly show in the folder preview, but once I tap the preview to open it fully, I'm consistently presented with a blank, black screen. This behavior is the same on all available versions of the Simple Gallery app (latest at this time is 1.51) and on several phones: a Samsung Galaxy S3 running CM13 (Marshmallow), a Samsung Galaxy S3 running original stock 4.1.2 (Jellybean), a ZTE Speed N9130 running stock 4.4.4 (KitKat), and a Motorola Moto E XT1528 running stock 5.1 (Lollipop). Of course, the images open properly with other image viewing apps. 

I can email you several example images. One is included below... 

![difference](https://cloud.githubusercontent.com/assets/24570690/21250605/5099cac0-c30c-11e6-8521-82a0b3212bf0.jpg)

**Comment by MuSqUlA** [comment]
Updated to the new version 2.1 -- problem still persists across all devices.  Do I need to upload more affected pictures?

**Comment by tibbi** [comment]
no need I guess, I just havent got to it yet

**Comment by tibbi** [comment]
Ill publish a new version 2.1.2 soon, which will use a different library for loading the images in case the original one fails. It wont be zoomable, but at least it will be displayed

**Comment by tibbi** [comment]
Ive added some zooming to the plan B way of loading images too, so ill close it already

**Comment by MuSqUlA** [comment]
I apologize for the late response. So, I'm curious... how does Plan B
method of opening images differ from the original? It does indeed now
display the images that didn't show properly, but still many won't zoom,
even in the latest 2.1.3 version.

Thanks a ton,
D

**Comment by tibbi** [comment]
2.2.1 is the latest :)
Plan A was opening images with so called SubsamplingScaleImageView library, which is proper zooming in with redrawing the zoomed in area for better quality. Plan B just displays the images in a PhotoView, which can also be zoomed in, but it actually just enlarges the already drawn image, so the quality is lower if you zoom in. However the Plan A library displays images with rgb_555 which is good enough for casual photos, but for pngs its too low quality and I couldnt change it. The A also cannot display gifs at all.

**Comment by MuSqUlA** [comment]
Very interesting!

So, is that what was happening with my problem pictures using Plan A? (Like
the picture I attached in the first post.) I thought it odd that the
picture's thumbnail/preview would always show properly, but then attempting
to open it would result in a black screen. Was it the redrawing you spoke
of failing?

Also, how do I get version 2.2.1? In F-Droid, it insists that 2.1.3 is the
latest.

Much respect!
-D

**Comment by tibbi** [comment]
fdroid can be behind, but theres nothing I can do about it.
Thumbnails are loaded by Glide, its the same library as I use for loading pngs and gifs. I use Glide to load it into a PhotoView, thats what gives the zooming. Casual photos use the subsamplingscaleimageview which is using rgb_555, but thats good enough for photos.
