### ISSUE TITLE
Show xLevel subfolders and do not show (x-1) subfolders

### ISSUE THREAD

**Issue by jorgemarmo** [SimpleMobileTools/Simple-Gallery#976]
Hi, great app btw!!
I have a folder called "oldPhoneBkUp" and inside, a ton of subfolders. Now, I would like to see just "oldPhoneBkUp" on the main screen and not all the subfolders. (Of course I would like to see them if I go inside oldPhoneBkUp folder)

**Comment by tibbi** [comment]
thanks, but this is a duplicate of #292

**Comment by jorgemarmo** [comment]
Thanks! 
And sorry for the duplicate...  ;)
