### ISSUE TITLE
System UI shadow still visible in fullscreen view

### ISSUE THREAD

**Issue by BOB74j** [SimpleMobileTools/Simple-Gallery#982]
When viewing an image, a shadow backdrop is visible behind the status bar to ensure that status bar icons are visible regardless of the image color. Tapping in the center of the image will cause the system UI to disappear, however, the shadow remains even in this full screen view. This seems to be a new issue as of version 4.6.5. View a white image in full screen to get an example. Also visible in this screenshot:

https://imgur.com/a/a5nInj5

Android 7.0
Simple Gallery 4.6.5

**Comment by tibbi** [comment]
ye, it is related to having disabled Bottom Actions. It has already been fixed, an updated version will be released soon. Thanks
