### ISSUE TITLE
Make folder hiding recursive

### ISSUE THREAD

**Issue by myfreeweb** [SimpleMobileTools/Simple-Gallery#997]
I have music album covers as separate jpegs to save disk space. So I'd like to hide the music folder, but hiding it does not seem to hide the album folders under it :(

**Comment by tibbi** [comment]
it should already be recursive. So you are using the "Hide" function, not "Exclude", right? Both should be recursive though. Is the folder on the internal storage, or SD card?

**Comment by myfreeweb** [comment]
Yes, hide. Exclude removes the music from music players :D No SD card on my phone.

**Comment by tibbi** [comment]
Exclude definitely doesnt affect any apps, as it is stored in the gallery only. Anyway, folder hiding is already recursive, there might be some problem on your end only. Dont you have some folders that you dont want to see at settings -> manage included folders?

**Comment by myfreeweb** [comment]
Hm, yeah, I see in the code that exclude is a local preference. Not sure how that happened then o_0

Yes, turns out it was in the include folders. \*facepalm\*
